Repository trezor/trezor-suite, pull requests merged in 2019-11, with the labels that each got.

#748 Show log in modal
  packages/suite/src/components/suite/Log/index.tsx
Labels: ready to review

#679 Account name component
  packages/suite/src/components/suite/modals/AddAccount/components/AccountSelect.tsx
  packages/suite/src/components/wallet/AccountName/index.tsx
  packages/suite/src/components/wallet/Menu/components/Row/index.tsx
  packages/suite/src/components/wallet/Title/index.tsx
  packages/suite/src/utils/wallet/__tests__/accountUtils.test.ts
  packages/suite/src/utils/wallet/__tests__/fixtures/accountUtils.ts
  packages/suite/src/utils/wallet/accountUtils.ts
  packages/suite/src/views/wallet/account/messages.ts
  packages/suite/src/views/wallet/account/receive/components/ReceiveForm/index.tsx
  packages/suite/src/views/wallet/account/receive/components/ReceiveForm/messages.ts
  packages/suite/src/views/wallet/account/receive/index.tsx
  packages/suite/src/views/wallet/account/send/components/messages.ts
  packages/suite/src/views/wallet/account/send/index.tsx
  packages/suite/src/views/wallet/account/summary/common.messages.ts
  packages/suite/src/views/wallet/account/summary/components/AccountHeader/index.tsx
  packages/suite/src/views/wallet/account/transactions/index.messages.ts
  packages/suite/src/views/wallet/account/transactions/index.tsx
Labels: ready to review

#703 Implement XRP send
  packages/suite/src/actions/wallet/constants/sendFormConstants.ts
  packages/suite/src/actions/wallet/ethereum/blockchainActions.ts
  packages/suite/src/actions/wallet/sendFormActions.ts
  packages/suite/src/actions/wallet/sendFormSpecific/bitcoinActions.ts
  packages/suite/src/actions/wallet/sendFormSpecific/ethereumActions.ts
  packages/suite/src/actions/wallet/sendFormSpecific/rippleActions.ts
  packages/suite/src/constants/wallet/sendForm.ts
  packages/suite/src/reducers/wallet/sendFormReducer.ts
  packages/suite/src/types/wallet/index.ts
  packages/suite/src/types/wallet/sendForm.ts
  packages/suite/src/types/wallet/sendForm/actions.ts
  packages/suite/src/types/wallet/sendForm/index.ts
  packages/suite/src/types/wallet/sendForm/output.ts
  packages/suite/src/types/wallet/sendForm/state.ts
  packages/suite/src/types/wallet/sendForm/transactions.ts
  packages/suite/src/utils/wallet/accountUtils.ts
  packages/suite/src/utils/wallet/sendFormUtils.ts
  packages/suite/src/views/wallet/account/send/components/Address/index.messages.ts
  packages/suite/src/views/wallet/account/send/components/Address/index.tsx
  packages/suite/src/views/wallet/account/send/components/Fee/index.tsx
  packages/suite/src/views/wallet/account/send/components/SendAndClear/index.tsx
  packages/suite/src/views/wallet/account/send/index.tsx
Labels: ready to review

#742 Notification unavailible
  packages/suite/src/actions/wallet/selectedAccountActions.ts
  packages/suite/src/components/wallet/Notifications/components/Account/index.messages.ts
  packages/suite/src/components/wallet/Notifications/components/Account/index.tsx
  packages/suite/src/reducers/wallet/selectedAccountReducer.ts
Labels: in progress

#713 Store remembered device, discovery, accounts, txs in db
  .gitlab-ci.yml
  ci/docker/base/Dockerfile
  package.json
  packages/suite-desktop/tsconfig.json
  packages/suite-storage/package.json
  packages/suite-storage/src/native/index.ts
  packages/suite-storage/src/web/index.ts
  packages/suite-web/tsconfig.json
  packages/suite/package.json
  packages/suite/src/actions/suite/__tests__/storageActions.test.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/wallet/blockchainActions.ts
  packages/suite/src/actions/wallet/sendFormActions.ts
  packages/suite/src/actions/wallet/transactionActions.ts
  packages/suite/src/middlewares/suite/suiteMiddleware.ts
  packages/suite/src/middlewares/wallet/index.ts
  packages/suite/src/middlewares/wallet/persistentStorageMiddleware.ts
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/reducers/wallet/accountsReducer.ts
  packages/suite/src/reducers/wallet/discoveryReducer.ts
  packages/suite/src/reducers/wallet/sendFormReducer.ts
  packages/suite/src/reducers/wallet/transactionReducer.ts
  packages/suite/src/storage/index.ts
  packages/suite/src/storage/migrations/index.ts
  packages/suite/src/support/suite/NoSSR.tsx
  packages/suite/src/support/tests/setupJest.ts
  packages/suite/src/types/wallet/sendForm/state.ts
  packages/suite/src/utils/suite/__tests__/device.test.ts
  packages/suite/src/utils/suite/__tests__/fixtures/device.ts
  packages/suite/src/utils/suite/device.ts
  packages/suite/src/utils/suite/storage.ts
  packages/suite/tsconfig.json
  yarn.lock
Labels: ready to review

#763 Allow node 12+
  package.json
Labels: ready to review

#756 Remove l10n duplicities and check them in CI
  ci/install-and-build.yml
  ci/packages/suite.yml
  packages/suite/.gitignore
  packages/suite/package.json
  packages/suite/src/actions/wallet/receiveActions.ts
  packages/suite/src/actions/wallet/selectedAccountActions.ts
  packages/suite/src/components/suite/Notifications/components/NoBackup/index.tsx
  packages/suite/src/components/suite/PinInput/index.messages.tsx
  packages/suite/src/components/suite/PinInput/index.tsx
  packages/suite/src/components/suite/modals/DuplicateDevice/index.tsx
  packages/suite/src/components/suite/modals/Pin/index.tsx
  packages/suite/src/components/suite/modals/Pin/messages.ts
  packages/suite/src/components/suite/modals/RequestInstance/index.tsx
  packages/suite/src/components/suite/modals/RequestInstance/messages.ts
  packages/suite/src/components/suite/modals/WalletType/index.tsx
  packages/suite/src/components/suite/modals/confirm/Address/index.tsx
  packages/suite/src/components/suite/modals/confirm/NoBackup/index.tsx
  packages/suite/src/components/suite/modals/confirm/UnverifiedAddress/index.tsx
  packages/suite/src/components/suite/modals/confirm/UnverifiedAddress/messages.ts
  packages/suite/src/components/suite/modals/messages.ts
  packages/suite/src/components/wallet/Menu/index.messages.ts
  packages/suite/src/components/wallet/Menu/index.tsx
  packages/suite/src/components/wallet/Notifications/components/Account/index.messages.ts
  packages/suite/src/components/wallet/Notifications/components/Static/index.tsx
  packages/suite/src/support/suite/Messages.ts
  packages/suite/src/views/onboarding/steps/Recovery/components/ModelOne.messages.tsx
  packages/suite/src/views/onboarding/steps/Recovery/components/ModelOne.tsx
  packages/suite/src/views/onboarding/steps/Recovery/components/ModelT.messages.tsx
  packages/suite/src/views/onboarding/steps/Recovery/components/ModelT.tsx
  packages/suite/src/views/onboarding/steps/Recovery/components/WordsInput.messages.tsx
  packages/suite/src/views/onboarding/steps/Recovery/components/WordsInput.tsx
  packages/suite/src/views/onboarding/steps/Recovery/index.messages.tsx
  packages/suite/src/views/suite/index.messages.tsx
  packages/suite/src/views/wallet/account/receive/components/ReceiveForm/messages.ts
  packages/suite/src/views/wallet/account/send/components/AdditionalForm/components/NetworkTypeEthereum/index.tsx
  packages/suite/src/views/wallet/account/send/components/AdditionalForm/components/NetworkTypeRipple/components/DestinationTag/index.tsx
  packages/suite/src/views/wallet/messages.ts
Labels: help wanted, ready to review

#776 TS Electron
  packages/suite-desktop/package.json
  packages/suite-desktop/src-electron/bridge.ts
  packages/suite-desktop/src-electron/electron-next.d.ts
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src-electron/preload.ts
  packages/suite-desktop/src-electron/tsconfig.json
  yarn.lock
Labels: ready to review

#760 rn to 59.10
  .gitlab-ci.yml
  ci/packages/suite-native.yml
  packages/suite-native/.gitignore
  packages/suite-native/android/app/build.gradle
  packages/suite-native/android/app/develop.keystore
  packages/suite-native/android/app/src/main/assets/.gitkeep
  packages/suite-native/android/build.gradle
  packages/suite-native/android/gradle.properties
  packages/suite-native/android/gradle/wrapper/gradle-wrapper.jar
  packages/suite-native/android/gradle/wrapper/gradle-wrapper.properties
  packages/suite-native/android/gradlew.bat
  packages/suite-native/babel.config.js
  packages/suite-native/metro.config.js
  packages/suite-native/package.json
  packages/suite-native/src/App.tsx
  yarn.lock
Labels: ready to review

#764 RN from 0.59.10 to 0.60.6
  packages/componentsStorybookNative/android/keystores/BUCK
  packages/componentsStorybookNative/android/keystores/debug.keystore.properties
  packages/suite-native/.gitignore
  packages/suite-native/android/app/build.gradle
  packages/suite-native/android/app/debug.keystore
  packages/suite-native/android/app/proguard-rules.pro
  packages/suite-native/android/app/src/main/java/io/trezor/suite/MainApplication.java
  packages/suite-native/android/app/src/main/res/values/styles.xml
  packages/suite-native/android/build.gradle
  packages/suite-native/android/gradle.properties
  packages/suite-native/android/gradlew
  packages/suite-native/android/keystores/BUCK
  packages/suite-native/android/keystores/debug.keystore.properties
  packages/suite-native/android/settings.gradle
  packages/suite-native/ios/Podfile
  packages/suite-native/ios/Podfile.lock
  packages/suite-native/ios/TrezorSuite.xcodeproj/project.pbxproj
  packages/suite-native/ios/TrezorSuite.xcworkspace/contents.xcworkspacedata
  packages/suite-native/ios/TrezorSuite.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  packages/suite-native/package.json
  yarn.lock
Labels: ready to review

#787 Fix electron build on catalina/xcode11
  packages/suite-desktop/entitlements.mac.inherit.plist
  packages/suite-desktop/package.json
Labels: ready to review

#775 RN from 0.60.6 to 0.61.4
  package.json
  packages/components-storybook-v2/package.json
  packages/components-storybook/package.json
  packages/components-v2/package.json
  packages/components/package.json
  packages/suite-native/.gitignore
  packages/suite-native/README.md
  packages/suite-native/android/app/build.gradle
  packages/suite-native/android/app/src/main/java/io/trezor/suite/MainApplication.java
  packages/suite-native/android/build.gradle
  packages/suite-native/android/gradle/wrapper/gradle-wrapper.properties
  packages/suite-native/babel.config.js
  packages/suite-native/ios/Podfile
  packages/suite-native/ios/Podfile.lock
  packages/suite-native/ios/TrezorSuiteTests/TrezorSuiteTests.m
  packages/suite-native/metro.config.js
  packages/suite-native/package.json
  packages/suite/package.json
  yarn.lock
Labels: ready to review

#801 Components v2 inputs
  packages/components-storybook-v2/.storybook/config.js
  packages/components-storybook-v2/public/fonts/fonts.css
  packages/components-storybook-v2/public/fonts/roboto/RobotoMono-Regular.woff
  packages/components-storybook-v2/public/fonts/roboto/RobotoMono-Regular.woff2
  packages/components-storybook-v2/src/stories/components/form/all.tsx
  packages/components-storybook-v2/src/stories/components/form/input.tsx
  packages/components-storybook-v2/test/integration/Form.test.js
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-disabled.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-error.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-default-disabled.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-default-error.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-default-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-default.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-disabled-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-error-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short-disabled.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short-error.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short-success.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-small-label.snap.png
  packages/components-v2/src/components/inputs/Input/index.tsx
  packages/components-v2/src/index.ts
Labels: ready to review

#810 Fix txs history
  packages/suite-storage/src/native/index.ts
  packages/suite-storage/src/web/index.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/wallet/transactionActions.ts
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/storage/index.ts
  packages/suite/src/views/wallet/account/transactions/components/TransactionList/index.tsx
Labels: ready to review

#816 Remember window size in suite-desktop
  packages/suite-desktop/package.json
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src-electron/store.ts
  yarn.lock
Labels: ready to review

#785 Fix typescript in react-native
  ci/packages/suite-native.yml
  packages/components-v2/package.json
  packages/components/package.json
  packages/suite-native/android/app/build.gradle
  packages/suite-native/android/app/src/main/java/io/trezor/suite/MainActivity.java
  packages/suite-native/android/app/src/main/java/io/trezor/suite/MainApplication.java
  packages/suite-native/android/settings.gradle
  packages/suite-native/babel.config.js
  packages/suite-native/index.d.ts
  packages/suite-native/ios/Podfile
  packages/suite-native/metro.config.js
  packages/suite-native/package.json
  packages/suite-native/src/App.tsx
  packages/suite-native/src/actions/suite/languageActions.ts
  packages/suite-native/src/actions/suite/routerActions.ts
  packages/suite-native/src/reducers/store.ts
  packages/suite-native/src/support/RouterHandler.tsx
  packages/suite-native/src/support/TemporaryPreloader.tsx
  packages/suite-native/src/views/suite/index.tsx
  packages/suite-native/src/views/suite/settings/index.tsx
  packages/suite-native/src/views/suite/trezor_logo_horizontal.svg
  packages/suite-native/src/views/wallet/index.tsx
  packages/suite-native/tsconfig.json
  packages/suite-storage/package.json
  packages/suite-storage/src/native/index.ts
  packages/suite/src/actions/suite/routerActions.ts
  packages/suite/src/actions/wallet/blockchainActions.ts
  packages/suite/src/actions/wallet/selectedAccountActions.ts
  packages/suite/src/components/suite/AcquireDevice/index.native.tsx
  packages/suite/src/components/suite/DeviceMenu/index.native.tsx
  packages/suite/src/components/wallet/Menu/index.tsx
  packages/suite/src/middlewares/suite/suiteMiddleware.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/types/wallet/index.ts
  packages/suite/src/types/wallet/sendForm/index.ts
  packages/suite/src/utils/wallet/accountUtils.ts
  packages/suite/src/views/onboarding/steps/Backup/components/SeedCard.tsx
  packages/suite/src/views/suite/index.native.tsx
  packages/suite/src/views/wallet/account/index.messages.ts
  packages/suite/src/views/wallet/account/send/components/AdditionalForm/components/CustomFee/index.tsx
  packages/suite/src/views/wallet/account/send/components/Fee/index.tsx
  packages/suite/tsconfig.json
  patches/trezor-connect+8.0.10-extended.patch
  yarn.lock
Labels: ready to review

#821 count number of updated packages and notify in ci job
  .gitlab-ci.yml
  ci/packages/suite.yml
  ci/scripts/outdated.sh
Labels: ready to review
