Repository trezor/trezor-suite, pull requests merged in 2019-12, with the labels that each got.

#857 Components v2 inputs fix
  packages/components-storybook-v2/src/stories/components/form/all.tsx
  packages/components-storybook-v2/src/stories/components/form/input.tsx
  packages/components-storybook-v2/test/integration/Form.test.js
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-disabled.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-error.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-monospace-button.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-monospace-hidden.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-success.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-warning.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-default-disabled.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-default-error.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-default-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-default-success.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-default-warning.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-default.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-disabled-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-error-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short-disabled.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short-error.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short-success.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short-warning.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-small-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-success-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-warning-label.snap.png
  packages/components-storybook-v2/test/support/commands.js
  packages/components-v2/src/components/FluidSpinner/index.tsx
  packages/components-v2/src/components/buttons/Button/index.tsx
  packages/components-v2/src/components/inputs/Input/index.tsx
  packages/components-v2/src/config/colors.ts
  packages/components-v2/src/support/types/index.ts
Labels: components-v2, ready to review

#876 update wait-on lib
  packages/components-storybook-v2/package.json
  packages/components-storybook/package.json
  packages/components-v2/package.json
  packages/components/package.json
  yarn.lock
Labels: ready to review

#871 Components v2 Textarea
  packages/components-storybook-v2/.storybook/config.js
  packages/components-storybook-v2/src/stories/components/form/all.tsx
  packages/components-storybook-v2/src/stories/components/form/textarea.tsx
  packages/components-storybook-v2/test/integration/Form.test.js
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-disabled.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-monospace-button.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-monospace-hidden.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-block.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-default-disabled.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-default-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-default.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-disabled-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short-disabled.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-short.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- input-small-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-block-default.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-block-disabled.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-block-error.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-block-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-block-success.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-block-warning.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-default.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-disabled.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-error.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-short-disabled.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-short-error.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-short-label.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-short-success.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-short-warning.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-short.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-success.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- textarea-warning.snap.png
  packages/components-v2/src/components/FluidSpinner/index.tsx
  packages/components-v2/src/components/Textarea/index.tsx
  packages/components-v2/src/components/inputs/Input/index.tsx
  packages/components-v2/src/config/animations.ts
  packages/components-v2/src/config/index.ts
  packages/components-v2/src/config/variables.ts
  packages/components-v2/src/index.ts
  packages/components-v2/src/utils/colors.ts
  packages/components-v2/src/utils/display.ts
  packages/components-v2/src/utils/index.ts
Labels: components-v2, ready to review

#870 Onboarding in modal view
  packages/suite-data/files/images/onboarding/background.jpg
  packages/suite/src/actions/onboarding/__tests__/fixtures/onboardingActions.ts
  packages/suite/src/actions/onboarding/__tests__/onboardingActions.test.ts
  packages/suite/src/actions/onboarding/connectActions.ts
  packages/suite/src/actions/onboarding/constants/calls.ts
  packages/suite/src/components/onboarding/Preloader/index.tsx
  packages/suite/src/components/onboarding/UnexpectedState/components/Reconnect.tsx
  packages/suite/src/components/onboarding/UnexpectedState/index.tsx
  packages/suite/src/views/onboarding/index.tsx
Labels: ready to review

#882 Fix types in ttm
  packages/suite/package.json
  packages/translations-manager/package.json
  packages/translations-manager/src/cli.ts
  packages/translations-manager/src/services/crowdin/index.ts
  packages/translations-manager/tsconfig.json
  yarn.lock
Labels: ready to review

#881 Upgrade next
  packages/suite-desktop/package.json
  packages/suite-web/package.json
  yarn.lock
Labels: ready to review

#814 Components v2 notifications
  packages/components-storybook-v2/.storybook/config.js
  packages/components-storybook-v2/src/stories/components/notifications/all.tsx
  packages/components-storybook-v2/src/stories/components/notifications/notification.tsx
  packages/components-storybook-v2/test/integration/Notifications.test.js
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-cta-error.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-cta-info.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-cta-success.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-cta-warning.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-cta-error.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-cta-info.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-cta-success.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-cta-warning.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-error.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-info.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-loading-error.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-loading-info.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-loading-success.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-loading-warning.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-second-cta-error.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-second-cta-info.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-second-cta-success.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-second-cta-warning.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-success.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-desc-warning.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-error.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-info.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-loading-error.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-loading-info.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-loading-success.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-loading-warning.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-second-cta-error.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-second-cta-info.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-second-cta-success.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-second-cta-warning.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-success.snap.png
  packages/components-storybook-v2/test/snapshots/Notifications.test.js/Notifications -- notification-warning.snap.png
  packages/components-v2/src/components/Notification/index.tsx
  packages/components-v2/src/index.ts
  packages/components-v2/src/support/types/index.ts
  packages/components-v2/src/utils/colors.ts
Labels: components-v2, ready to review

#886 Fix/asset prefix lol
  packages/suite/src/utils/suite/__tests__/build.test.ts
  packages/suite/src/utils/suite/__tests__/nextjs.test.ts
  packages/suite/src/utils/suite/__tests__/router.test.ts
  packages/suite/src/utils/suite/router.ts
Labels: ready to review

#891 Prevent sendform dispose when route doesn't really change
  packages/suite/src/middlewares/wallet/walletMiddleware.ts
Labels: ready to review

#875 New switch modal
  packages/suite-web/next.config.js
  packages/suite/src/actions/suite/__tests__/fixtures/suiteActions.ts
  packages/suite/src/actions/suite/constants/suiteConstants.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/actions/wallet/discoveryActions.ts
  packages/suite/src/components/suite/Menu/components/DeviceModal/Container.tsx
  packages/suite/src/components/suite/Menu/components/DeviceModal/components/DeviceItem/index.tsx
  packages/suite/src/components/suite/Menu/components/DeviceModal/components/WalletInstance/Container.tsx
  packages/suite/src/components/suite/Menu/components/DeviceModal/components/WalletInstance/index.tsx
  packages/suite/src/components/suite/Menu/components/DeviceModal/index.tsx
  packages/suite/src/components/suite/Menu/components/TopMenu/components/DeviceModal/Container.tsx
  packages/suite/src/components/suite/Menu/components/TopMenu/components/DeviceModal/index.tsx
  packages/suite/src/components/suite/Menu/components/TopMenu/index.tsx
  packages/suite/src/components/suite/Translation/index.tsx
  packages/suite/src/components/suite/__tests__/__snapshots__/Translation.test.tsx.snap
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/middlewares/suite/redirectMiddleware.ts
  packages/suite/src/reducers/suite/__tests__/fixtures/modalReducer.ts
  packages/suite/src/reducers/suite/modalReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/suite/device.ts
  packages/suite/src/utils/wallet/__tests__/fiatConverter.test.ts
  packages/suite/src/utils/wallet/accountUtils.ts
  packages/suite/src/utils/wallet/fiatConverterUtils.ts
  packages/suite/src/views/wallet/account/summary/components/AccountHeader/components/Balance/index.tsx
Labels: ready to review

#878 Components v2 checkbox & switch
  packages/components-storybook-v2/.storybook/config.js
  packages/components-storybook-v2/src/stories/components/form/all.tsx
  packages/components-storybook-v2/src/stories/components/form/checkbox.tsx
  packages/components-storybook-v2/src/stories/components/form/switch.tsx
  packages/components-storybook-v2/test/integration/Form.test.js
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- checkbox-checked.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- checkbox.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- switch-off-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- switch-off.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- switch-on-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- switch-on.snap.png
  packages/components-v2/src/components/Checkbox/index.tsx
  packages/components-v2/src/components/Switch/index.tsx
  packages/components-v2/src/index.ts
Labels: components-v2, ready to review

#908 Packages/update 1
  package.json
  packages/connect-explorer/package.json
  packages/suite-desktop/package.json
  packages/suite-native/src/support/TemporaryPreloader.tsx
  packages/suite-web/package.json
  packages/suite/package.json
  yarn.lock
Labels: ready to review

#911 Packages/update 2
  packages/suite/jest.config.js
  packages/suite/package.json
  packages/suite/src/actions/wallet/__tests__/fixtures/receiveActions.ts
  packages/suite/src/actions/wallet/__tests__/receiveActions.test.ts
  packages/suite/src/actions/wallet/receiveActions.ts
  yarn.lock
Labels: ready to review

#912 Feature/rn bridge
  packages/blockchain-link/package.json
  packages/components-v2/package.json
  packages/components/package.json
  packages/connect-explorer/package.json
  packages/suite-native/android/app/build.gradle
  packages/suite-native/android/app/src/main/AndroidManifest.xml
  packages/suite-native/android/app/src/main/java/io/trezor/suite/BridgeModule.java
  packages/suite-native/android/app/src/main/java/io/trezor/suite/BridgePackage.java
  packages/suite-native/android/app/src/main/java/io/trezor/suite/MainActivity.java
  packages/suite-native/android/app/src/main/java/io/trezor/suite/MainApplication.java
  packages/suite-native/android/app/src/main/java/io/trezor/suite/TrezorException.java
  packages/suite-native/android/app/src/main/java/io/trezor/suite/UsbActivity.java
  packages/suite-native/android/app/src/main/java/io/trezor/suite/Utils.java
  packages/suite-native/android/app/src/main/java/io/trezor/suite/bridge/UDPBridge.java
  packages/suite-native/android/app/src/main/java/io/trezor/suite/bridge/USBBridge.java
  packages/suite-native/android/app/src/main/java/io/trezor/suite/interfaces/BridgeInterface.java
  packages/suite-native/android/app/src/main/java/io/trezor/suite/interfaces/TrezorInterface.java
  packages/suite-native/android/app/src/main/java/io/trezor/suite/receivers/DeviceAttachmentReceiver.java
  packages/suite-native/android/app/src/main/java/io/trezor/suite/receivers/USBPermissionReceiver.java
  packages/suite-native/android/build.gradle
  packages/suite-native/android/settings.gradle
  packages/suite-native/ios/Podfile.lock
  packages/suite-native/metro.config.js
  packages/suite-native/package.json
  packages/suite-native/src/App.tsx
  packages/suite-native/src/actions/suite/routerActions.ts
  packages/suite-native/src/support/Preloader.tsx
  packages/suite-native/src/views/suite/index.tsx
  packages/suite-native/src/views/wallet/index.tsx
  yarn.lock
Labels: ready to review

#933 Remove build libs in native
  ci/packages/suite-native.yml
Labels: W1, ready to review

#904 Suite/design 0
  packages/suite-web/test/integration/suite/device-settings.test.ts
  packages/suite/src/actions/suite/__tests__/deviceSettingsActions.test.ts
  packages/suite/src/actions/suite/__tests__/fixtures/deviceSettings.ts
  packages/suite/src/actions/suite/constants/deviceSettings.ts
  packages/suite/src/actions/suite/deviceSettingsActions.ts
  packages/suite/src/components/suite/AcquireDevice/index.tsx
  packages/suite/src/components/suite/Menu/index.tsx
  packages/suite/src/components/suite/MenuSecondary/index.tsx
  packages/suite/src/components/suite/SettingsLayout/components/index.ts
  packages/suite/src/components/suite/SettingsLayout/index.tsx
  packages/suite/src/components/suite/SettingsMenu/index.tsx
  packages/suite/src/components/suite/SuiteLayout/index.tsx
  packages/suite/src/components/suite/SuiteWrapper/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/components/suite/landing/Loading/index.tsx
  packages/suite/src/components/suite/modals/BackgroundGallery/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/components/wallet/WalletLayout/components/ProgressBar/index.tsx
  packages/suite/src/components/wallet/WalletLayout/index.tsx
  packages/suite/src/reducers/suite/modalReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/views/settings/coins/index.tsx
  packages/suite/src/views/settings/dashboard/index.tsx
  packages/suite/src/views/settings/device/Container.ts
  packages/suite/src/views/settings/device/index.tsx
  packages/suite/src/views/settings/index.tsx
  packages/suite/src/views/settings/wallet/index.tsx
  packages/suite/src/views/suite/backup/index.tsx
  packages/suite/src/views/wallet/dashboard/index.tsx
  packages/suite/src/views/wallet/index.tsx
Labels: ready to review

#935 Packages/update 3
  package.json
  packages/components-storybook-v2/package.json
  packages/components-storybook/package.json
  packages/components-v2/package.json
  packages/components/package.json
  packages/connect-explorer/package.json
  packages/rollout/package.json
  packages/suite-data/package.json
  packages/suite-desktop/package.json
  packages/suite-web/package.json
  packages/suite/package.json
  packages/translations-manager/package.json
  yarn.lock
Labels: ready to review

#906 /static -> /public
  .eslintignore
  packages/rollout/.eslintignore
  packages/suite-data/config.ts
  packages/suite-data/files/browser-detection/browser-chrome.png
  packages/suite-data/files/browser-detection/browser-firefox.png
  packages/suite-data/files/browser-detection/index.js
  packages/suite-data/index.ts
  packages/suite-data/package.json
  packages/suite-desktop/.gitignore
  packages/suite-native/.gitignore
  packages/suite-web/.gitignore
  packages/suite-web/pages/_document.tsx
  packages/suite-web/support/ImagesPreloader.tsx
Labels: W3, ready to review

#941 add translations-manager to CI
  .gitlab-ci.yml
  ci/packages/translations-manager.yml
  packages/translations-manager/package.json
  packages/translations-manager/tsconfig.json
Labels: ready to review

#939 CI nitpicks
  .gitlab-ci.yml
  ci/packages/blockchain-link.yml
  ci/packages/rollout.yml
  ci/packages/suite-desktop.yml
  ci/packages/suite-native.yml
Labels: ready to review

#943 add lighthouse security audits test
  ci/packages/suite-web.yml
  ci/scripts/check-vulnerabilities.js
  packages/suite-web/package.json
  yarn.lock
Labels: ready to review

#942 add refresh button
  packages/suite/src/support/suite/ErrorBoundary.tsx
Labels: ready to review

#936 style settings menu
  packages/suite/src/components/suite/SettingsMenu/index.tsx
Labels: ready to review

#937 style background gallery
  packages/suite/src/components/suite/modals/BackgroundGallery/index.tsx
  packages/suite/src/support/messages.ts
Labels: ready to review

#754 Add <Prompt type=connect-device />
  packages/components-storybook/src/stories/components/other.tsx
  packages/components/src/components/Prompt/index.tsx
  packages/suite/src/components/suite/landing/ConnectDevice/index.tsx
  packages/suite/src/views/settings/device/index.tsx
Labels: ready to review

#951 Remove 8001 port from dev
  packages/suite-web/package.json
  packages/suite-web/test/open-local.sh
  packages/suite-web/test/run-local.sh
Labels: ready to review

#950 Update modules for components v2
  packages/components-v2/package.json
  packages/components-v2/src/components/CoinLogo/index.tsx
  packages/components-v2/src/components/Icon/index.tsx
  packages/components-v2/src/components/TrezorLogo/index.tsx
  packages/components/package.json
  yarn.lock
Labels: ready to review

#909 Feature/dashboard assets
  .eslintrc.js
  package.json
  packages/suite-desktop/pages/dashboard/index.tsx
  packages/suite-web/pages/dashboard/index.tsx
  packages/suite-web/pages/index.tsx
  packages/suite/package.json
  packages/suite/src/actions/suite/__tests__/fixtures/routerActions.ts
  packages/suite/src/components/suite/AssetsCard/components/Asset/index.tsx
  packages/suite/src/components/suite/AssetsCard/index.tsx
  packages/suite/src/components/suite/Card/index.tsx
  packages/suite/src/components/suite/Menu/components/DeviceModal/components/WalletInstance/index.tsx
  packages/suite/src/components/suite/Menu/components/MainMenu/index.tsx
  packages/suite/src/components/suite/NoRatesTooltip/index.tsx
  packages/suite/src/components/suite/PortfolioCard/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/constants/suite/menu.ts
  packages/suite/src/constants/suite/routes.ts
  packages/suite/src/middlewares/suite/__tests__/suiteMiddleware.test.ts
  packages/suite/src/middlewares/suite/redirectMiddleware.ts
  packages/suite/src/middlewares/wallet/discoveryMiddleware.ts
  packages/suite/src/utils/suite/__tests__/router.test.ts
  packages/suite/src/utils/wallet/accountUtils.ts
  packages/suite/src/views/dashboard/Container.ts
  packages/suite/src/views/dashboard/index.tsx
  packages/suite/src/views/wallet/account/summary/components/AccountHeader/components/Balance/index.tsx
  yarn.lock
Labels: ready to review

#946 implement update based on timestamp
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/wallet/constants/fiatRatesConstants.ts
  packages/suite/src/actions/wallet/fiatRatesActions.ts
  packages/suite/src/config/suite/fiat.ts
  packages/suite/src/middlewares/wallet/coingeckoMiddleware.ts
  packages/suite/src/middlewares/wallet/walletMiddleware.ts
  packages/suite/src/reducers/wallet/fiatRateReducer.ts
  packages/suite/src/storage/index.ts
  packages/suite/src/types/wallet/index.ts
  packages/suite/src/utils/wallet/__tests__/fiatConverter.test.ts
Labels: ready to review

#956 Update and delete some modules in components
  packages/components-storybook/package.json
  packages/components/package.json
  yarn.lock
Labels: ready to review

#955 Minor dashboard bugs
  packages/components-storybook-v2/.storybook/config.js
  packages/components-storybook-v2/package.json
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- switch-off-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- switch-off.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- switch-on-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- switch-on.snap.png
  packages/components-v2/src/components/Switch/index.tsx
  packages/suite/src/components/suite/AssetsCard/index.tsx
  packages/suite/src/components/suite/Menu/components/BottomMenu/index.tsx
  packages/suite/src/components/suite/PortfolioCard/index.tsx
Labels: ready to review

#970 Fix/switch, build componentsv2 with TS
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- switch-off-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- switch-off.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- switch-on-small.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- switch-on.snap.png
  packages/components-v2/babel.config.js
  packages/components-v2/package.json
  packages/components-v2/scripts/copyAssets.js
  packages/components-v2/src/components/Switch/index.tsx
  packages/components-v2/tsconfig.json
  packages/suite/src/views/settings/coins/index.tsx
Labels: ready to review

#984 remove useless l10n job
  ci/packages/suite.yml
Labels: ready to review

#981 improve coins settings
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/coins/index.tsx
Labels: ready to review

#980 Urls in one file
  packages/suite/src/components/onboarding/UnexpectedState/components/IsNotNewDevice.tsx
  packages/suite/src/components/suite/Footer/index.tsx
  packages/suite/src/components/suite/landing/ConnectDevice/index.tsx
  packages/suite/src/components/wallet/Notifications/components/Static/index.tsx
  packages/suite/src/constants/onboarding/index.ts
  packages/suite/src/constants/onboarding/urls.ts
  packages/suite/src/constants/suite/urls.ts
  packages/suite/src/views/onboarding/index.tsx
  packages/suite/src/views/onboarding/steps/Backup/index.tsx
  packages/suite/src/views/onboarding/steps/Bookmark/index.tsx
  packages/suite/src/views/onboarding/steps/Hologram/index.tsx
  packages/suite/src/views/onboarding/steps/Newsletter/index.tsx
  packages/suite/src/views/onboarding/steps/Pair/components/Connect/TroubleshootInitialized.tsx
  packages/suite/src/views/onboarding/steps/Pair/components/Connect/TroubleshootTooLong.tsx
  packages/suite/src/views/onboarding/steps/Recovery/components/ModelOne.tsx
  packages/suite/src/views/onboarding/steps/Shamir/index.tsx
  packages/suite/src/views/settings/device/index.tsx
  packages/suite/src/views/suite/bridge/index.tsx
  packages/suite/test/health/urls.test.ts
Labels: ready to review

#964 Components v2 loader
  packages/components-storybook-v2/.storybook/config.js
  packages/components-storybook-v2/src/stories/components/loaders/all.tsx
  packages/components-storybook-v2/src/stories/components/loaders/loader.tsx
  packages/components-storybook-v2/test/integration/Loaders.test.js
  packages/components-storybook-v2/test/snapshots/Loaders.test.js/Loaders -- loader-default.snap.png
  packages/components-storybook-v2/test/snapshots/Loaders.test.js/Loaders -- loader-small-text.snap.png
  packages/components-storybook-v2/test/snapshots/Loaders.test.js/Loaders -- loader-transparent-route.snap.png
  packages/components-storybook-v2/test/snapshots/Loaders.test.js/Loaders -- loader-white-text-transparent.snap.png
  packages/components-storybook-v2/test/snapshots/Loaders.test.js/Loaders -- loader-white-text.snap.png
  packages/components-v2/src/components/Loader/index.tsx
  packages/components-v2/src/config/animations.ts
  packages/components-v2/src/index.ts
Labels: components-v2, ready to review

#874 Components v2 select
  packages/components-storybook-v2/.storybook/config.js
  packages/components-storybook-v2/src/stories/components/form/all.tsx
  packages/components-storybook-v2/src/stories/components/form/select.tsx
  packages/components-storybook-v2/test/integration/Form.test.js
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- select-disabled.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- select-selected.snap.png
  packages/components-storybook-v2/test/snapshots/Form.test.js/Form -- select.snap.png
  packages/components-v2/src/components/Select/index.tsx
  packages/components-v2/src/index.ts
Labels: components-v2, ready to review

#975 #974
  .gitlab-ci.yml
  ci/packages/suite-desktop.yml
  ci/packages/suite-native.yml
Labels: ready to review

#987 Fix/dashboard in suite-desktop
  packages/suite-desktop/next.config.js
  packages/suite-desktop/pages/dashboard/index.tsx
  packages/suite-desktop/pages/index.tsx
  packages/suite-web/pages/dashboard/index.tsx
Labels: ready to review
