Repository trezor/trezor-suite, pull requests merged in 2020-04, with the labels that each got.

#1409 Blockchain link@1.0.10
  packages/blockchain-link/CHANGELOG.md
  packages/blockchain-link/package.json
  packages/blockchain-link/src/types/blockbook.ts
  packages/blockchain-link/src/types/common.ts
  packages/blockchain-link/src/workers/blockbook/utils.ts
  packages/blockchain-link/tests/unit/fixtures/getAccountInfo-blockbook.ts
Labels: ready to review

#1399 Store security features completion, suite reducer cleanup, useTrezorActionEnabled hook
  packages/suite-native/src/actions/suite/routerActions.ts
  packages/suite-native/src/views/suite/onboarding/index.tsx
  packages/suite/src/actions/settings/__tests__/walletSettingsActions.test.ts
  packages/suite/src/actions/settings/walletSettingsActions.ts
  packages/suite/src/actions/suite/__fixtures__/routerActions.ts
  packages/suite/src/actions/suite/__fixtures__/suiteActions.ts
  packages/suite/src/actions/suite/__tests__/storageActions.test.ts
  packages/suite/src/actions/suite/__tests__/suiteActions.test.ts
  packages/suite/src/actions/suite/constants/suiteConstants.ts
  packages/suite/src/actions/suite/routerActions.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/components/dashboard/SecurityFeatures/Container.ts
  packages/suite/src/components/dashboard/SecurityFeatures/components/SecurityCard/index.tsx
  packages/suite/src/components/dashboard/SecurityFeatures/index.tsx
  packages/suite/src/components/suite/Settings/components/Analytics.tsx
  packages/suite/src/components/suite/Translation/components/HelperTooltip/index.tsx
  packages/suite/src/components/suite/modals/PassphraseDuplicate/index.tsx
  packages/suite/src/middlewares/onboarding/__tests__/onboardingMiddleware.test.ts
  packages/suite/src/middlewares/suite/__tests__/suiteMiddleware.test.ts
  packages/suite/src/middlewares/suite/suiteMiddleware.ts
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/storage/index.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/support/suite/ConnectedIntlProvider.tsx
  packages/suite/src/support/tests/IntlHelper.tsx
  packages/suite/src/utils/suite/hooks.ts
  packages/suite/src/views/settings/debug/Container.ts
  packages/suite/src/views/settings/index.tsx
Labels: ready to review

#1411 add missing device settings btn to switch device modal
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
Labels: ready to review

#1408 Fix/receive modals
  packages/suite/src/actions/settings/deviceSettingsActions.ts
  packages/suite/src/components/suite/modals/confirm/NoBackup/index.tsx
  packages/suite/src/components/suite/modals/confirm/UnverifiedAddress/index.tsx
  packages/suite/src/support/messages.ts
Labels: ready to review

#1416 Remove send form connect hotfix
  packages/suite/src/actions/wallet/send/sendFormBitcoinActions.ts
Labels: ready to review

#1418 Feature/select no options intl
  packages/suite/src/components/suite/modals/AddAccount/components/NetworkSelect.tsx
  packages/suite/src/components/wallet/AccountSelector/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/Pagination/index.tsx
Labels: ready to review

#1417 Tertiary button same padding
  packages/components/src/components/buttons/Button/index.tsx
Labels: ready to review

#1424 fix button spinner position
  packages/components/src/components/buttons/Button/index.tsx
Labels: ready to review

#1426 Blockchain-link: fix type in AccountBalanceHistory
  packages/blockchain-link/src/types/blockbook.ts
Labels: ready to review

#1404 News API connect
  packages/news-api/package.json
  packages/news-api/src/index.ts
  packages/news-api/src/server.ts
  packages/suite-desktop/babel.config.js
  packages/suite-desktop/next.config.js
  packages/suite-web/babel.config.js
  packages/suite/src/components/dashboard/NewsFeed/index.tsx
  packages/suite/src/hooks/dashboard/news.ts
  packages/suite/src/support/messages.ts
  tsconfig.json
  yarn.lock
Labels: ready to review

#1448 fix alignment in static notifications
  packages/suite/src/components/suite/Notifications/components/Wrapper.tsx
Labels: ready to review

#1445 pin fixes
  packages/suite-data/files/videos/suite/pin-mismatch.mp4
  packages/suite/src/components/suite/modals/Pin/index.tsx
  packages/suite/src/components/suite/modals/PinMismatch/index.tsx
  packages/suite/src/middlewares/suite/buttonRequestMiddleware.ts
  packages/suite/src/support/messages.ts
Labels: ready to review

#1456 Settings - elements not interactive without device
  packages/suite/src/views/settings/device/Container.ts
  packages/suite/src/views/settings/device/index.tsx
  packages/suite/src/views/settings/wallet/index.tsx
Labels: ready to review

#1454 visual improvements to option tiles
  packages/suite/src/components/onboarding/Option/index.tsx
Labels: ready to review

#1427 Update design layers
  packages/suite/src/components/dashboard/AssetsCard/components/Asset/index.tsx
  packages/suite/src/components/dashboard/AssetsCard/index.tsx
  packages/suite/src/components/dashboard/PortfolioCard/index.tsx
  packages/suite/src/components/dashboard/SecurityFeatures/index.tsx
  packages/suite/src/components/suite/Card/index.tsx
  packages/suite/src/components/suite/Menu/components/MainMenu/index.tsx
  packages/suite/src/components/suite/Settings/components/ActionColumn.tsx
  packages/suite/src/components/suite/Settings/components/Analytics.tsx
  packages/suite/src/components/suite/Settings/components/Section.tsx
  packages/suite/src/components/suite/Settings/components/SectionHeader.tsx
  packages/suite/src/components/suite/Settings/components/TextColumn.tsx
  packages/suite/src/components/suite/SuiteLayout/index.tsx
  packages/suite/src/components/wallet/AccountName/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/support/suite/styles/global.ts
  packages/suite/src/utils/suite/hooks.ts
  packages/suite/src/views/settings/device/index.tsx
  packages/suite/src/views/settings/index.tsx
  packages/suite/src/views/suite/notifications/index.tsx
  packages/suite/src/views/wallet/details/index.tsx
  packages/suite/src/views/wallet/send/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionSummary/components/InfoCard/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionSummary/index.tsx
Labels: ready to review

#1459 fix backup failed in onboarding
  packages/suite/src/actions/onboarding/__fixtures__/onboardingActions.ts
  packages/suite/src/actions/onboarding/onboardingActions.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/onboarding/steps/Backup/Container.ts
  packages/suite/src/views/onboarding/steps/Backup/index.tsx
Labels: ready to review

#1471 Fix/account menu default label
  packages/suite-web/pages/bridge/index.tsx
  packages/suite-web/pages/onboarding/index.tsx
  packages/suite-web/pages/version/index.tsx
  packages/suite/src/components/settings/SettingsLayout/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/components/wallet/Menu/components/AccountGroup/index.tsx
  packages/suite/src/components/wallet/Menu/components/AccountItem/Container.ts
  packages/suite/src/components/wallet/Menu/components/AccountItem/index.tsx
  packages/suite/src/components/wallet/Menu/components/AccountNavigation/index.tsx
  packages/suite/src/components/wallet/WalletLayout/index.tsx
  packages/suite/src/config/wallet/menu.tsx
  packages/suite/src/views/dashboard/index.tsx
  packages/suite/src/views/exchange/index.tsx
  packages/suite/src/views/passwords/index.tsx
  packages/suite/src/views/portfolio/index.tsx
  packages/suite/src/views/suite/notifications/index.tsx
Labels: ready to review

#1476 Coin settings refactor + new design
  packages/suite-desktop/pages/settings/index.tsx
  packages/suite-web/pages/settings/index.tsx
  packages/suite/src/components/dashboard/ConnectionStatusCard/index.tsx
  packages/suite/src/components/dashboard/NewsFeed/index.tsx
  packages/suite/src/components/dashboard/PortfolioCard/index.tsx
  packages/suite/src/components/dashboard/SecurityFeatures/index.tsx
  packages/suite/src/components/suite/Card/index.tsx
  packages/suite/src/components/suite/Settings/components/Row.tsx
  packages/suite/src/components/suite/Settings/components/Section.tsx
  packages/suite/src/components/suite/Settings/components/SectionHeader.tsx
  packages/suite/src/components/suite/Settings/components/TextColumn.tsx
  packages/suite/src/components/suite/Settings/index.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/Container.ts
  packages/suite/src/views/settings/debug/index.tsx
  packages/suite/src/views/settings/device/index.tsx
  packages/suite/src/views/settings/index.tsx
  packages/suite/src/views/settings/wallet/Container.ts
  packages/suite/src/views/settings/wallet/components/Coin/index.tsx
  packages/suite/src/views/settings/wallet/components/CoinsGroup/index.tsx
  packages/suite/src/views/settings/wallet/index.tsx
Labels: ready to review

#1483 micro: make icon clickable in help/buy icons
  packages/suite/src/components/suite/ProgressBar/components/HelpBuyIcons.tsx
Labels: ready to review

#1482 settings - suite version
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/index.tsx
Labels: ready to review

#1478 Firmware translations etc
  packages/suite/src/actions/firmware/firmwareActions.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/firmware/index.tsx
  packages/suite/src/views/onboarding/steps/Firmware/index.tsx
Labels: ready to review

#1468 Select undiscovered wallet on "add wallet" click
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/AddWalletButton/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx
  packages/suite/src/support/messages.ts
Labels: ready to review

#1489 Bugs and improvements
  packages/suite/src/components/dashboard/PortfolioCard/index.tsx
  packages/suite/src/components/suite/Card/index.tsx
  packages/suite/src/views/wallet/transactions/components/NoTransactions/index.tsx
Labels: ready to review

#1492 Fix/minor fixes 123
  packages/components/src/components/Tooltip/index.tsx
  packages/suite/src/components/suite/Card/index.tsx
  packages/suite/src/components/suite/Settings/components/Section.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx
  packages/suite/src/components/suite/modals/PinMismatch/index.tsx
  packages/suite/src/components/suite/modals/QrScanner/index.tsx
  packages/suite/src/components/wallet/Menu/components/AddAccount/index.tsx
  packages/suite/src/components/wallet/Menu/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/wallet/balanceUtils.ts
  packages/suite/src/views/wallet/receive/components/Header/index.tsx
Labels: ready to review

#1491 Feature/responsive layout
  packages/components/src/config/variables.ts
  packages/suite/src/components/settings/Menu/index.tsx
  packages/suite/src/components/suite/Menu/Container.ts
  packages/suite/src/components/suite/Menu/components/BottomMenu/index.tsx
  packages/suite/src/components/suite/Menu/components/MainMenu/index.tsx
  packages/suite/src/components/suite/Menu/index.tsx
  packages/suite/src/components/suite/MenuDrawer/components/AppsButton/index.tsx
  packages/suite/src/components/suite/MenuDrawer/components/Header/index.tsx
  packages/suite/src/components/suite/MenuDrawer/components/Overlay/index.tsx
  packages/suite/src/components/suite/MenuDrawer/index.tsx
  packages/suite/src/components/suite/MenuSecondary/index.tsx
  packages/suite/src/components/suite/SuiteLayout/index.tsx
  packages/suite/src/components/wallet/Menu/components/AccountGroup/index.tsx
  packages/suite/src/components/wallet/Menu/components/AddAccount/index.tsx
  packages/suite/src/components/wallet/Menu/components/AnimationWrapper/index.tsx
  packages/suite/src/components/wallet/Menu/index.tsx
  packages/suite/src/reducers/suite/resizeReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/support/suite/Resize/index.tsx
  packages/suite/src/utils/suite/string.ts
Labels: ready to review

#1501 Hide news in error state
  packages/suite/src/components/dashboard/NewsFeed/index.tsx
Labels: ready to review

#1502 vertical center label in Section, coins (with advanced settings btn) …
  packages/suite/src/components/suite/Settings/components/ActionColumn.tsx
  packages/suite/src/components/suite/Settings/components/Row.tsx
  packages/suite/src/components/suite/Settings/components/SectionItem.tsx
  packages/suite/src/components/suite/Settings/index.ts
  packages/suite/src/views/settings/device/index.tsx
  packages/suite/src/views/settings/index.tsx
  packages/suite/src/views/settings/wallet/components/CoinsGroup/index.tsx
Labels: ready to review

#1505 retry for integration tests
  ci/packages/suite-web.yml
Labels: ready to review

#1447 recovery fixes
  packages/suite/src/actions/recovery/recoveryActions.ts
  packages/suite/src/components/recovery/Error.tsx
  packages/suite/src/components/suite/Prompts/components/ConnectPrompt.tsx
  packages/suite/src/config/onboarding/steps.ts
  packages/suite/src/constants/suite/routes.ts
  packages/suite/src/middlewares/recovery/recoveryMiddleware.ts
  packages/suite/src/views/onboarding/index.tsx
  packages/suite/src/views/onboarding/steps/Final/index.tsx
  packages/suite/src/views/onboarding/steps/Recovery/Container.ts
  packages/suite/src/views/onboarding/steps/Recovery/index.tsx
  packages/suite/src/views/onboarding/unexpected-states/index.tsx
  packages/suite/src/views/recovery/index.tsx
  packages/suite/src/views/settings/device/index.tsx
  packages/suite/src/views/suite/device-recovery-mode/Container.ts
  packages/suite/src/views/suite/device-recovery-mode/index.tsx
Labels: ready to review

#1508 update primary menu design
  packages/suite/src/components/suite/Menu/components/BottomMenu/index.tsx
  packages/suite/src/components/suite/Menu/components/MainMenu/index.tsx
  packages/suite/src/components/suite/Menu/components/TopMenu/index.tsx
  packages/suite/src/components/suite/Menu/index.tsx
  packages/suite/src/constants/suite/menu.ts
  packages/suite/src/support/messages.ts
Labels: ready to review

#1512 fix #1270
  packages/suite/src/utils/suite/homescreen.ts
Labels: ready to review

#1493 Meowing squirell
  packages/suite/src/actions/firmware/firmwareActions.ts
  packages/suite/src/actions/suite/trezorConnectActions.ts
  packages/suite/src/components/suite/CheckItem/index.tsx
  packages/suite/src/components/suite/DeviceInvalidModeLayout/index.tsx
  packages/suite/src/components/suite/Settings/components/Analytics.tsx
  packages/suite/src/components/suite/Settings/components/TextColumn.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/suite/device.ts
  packages/suite/src/views/onboarding/steps/Pair/components/Connect/TroubleshootInitialized.tsx
  packages/suite/src/views/onboarding/steps/Pair/index.tsx
  packages/suite/src/views/onboarding/steps/ResetDevice/index.tsx
  packages/suite/src/views/settings/device/index.tsx
  packages/suite/src/views/suite/device-acquire/index.tsx
  packages/suite/src/views/suite/device-bootloader/index.tsx
  packages/suite/src/views/suite/device-initialize/index.tsx
  packages/suite/src/views/suite/device-no-firmware/index.tsx
  packages/suite/src/views/suite/device-seedless/index.tsx
  packages/suite/src/views/suite/device-unknown/index.tsx
  packages/suite/src/views/suite/device-unreadable/index.tsx
  packages/suite/src/views/suite/device-update-required/index.tsx
Labels: ready to review

#1523 another bunch of visual fixes
  packages/suite/src/components/dashboard/SecurityFeatures/index.tsx
  packages/suite/src/components/suite/Settings/components/Analytics.tsx
  packages/suite/src/middlewares/firmware/firmwareMiddleware.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/firmware/index.tsx
  packages/suite/src/views/onboarding/steps/Firmware/index.tsx
  packages/suite/src/views/recovery/index.tsx
  packages/suite/src/views/settings/index.tsx
  packages/suite/src/views/suite/device-bootloader/index.tsx
Labels: ready to review

#1527 Update/missing intl
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/ru.json
  packages/suite/src/actions/settings/languageActions.ts
  packages/suite/src/components/dashboard/SecurityFeatures/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/support/suite/ConnectedIntlProvider.tsx
  packages/suite/src/views/onboarding/steps/Skip/index.tsx
Labels: ready to review

#1534 Fix dev server error
  packages/suite/src/components/dashboard/NewsFeed/index.tsx
Labels: ready to review

#1530 Fix/blockchain reconnect
  packages/suite/src/actions/backup/__tests__/backupActions.test.ts
  packages/suite/src/actions/firmware/__tests__/firmwareActions.test.ts
  packages/suite/src/actions/onboarding/__tests__/onboardingActions.test.ts
  packages/suite/src/actions/suite/__tests__/suiteActions.test.ts
  packages/suite/src/actions/suite/__tests__/trezorConnectActions.test.ts
  packages/suite/src/actions/wallet/__tests__/blockchainActions.test.ts
  packages/suite/src/actions/wallet/__tests__/discoveryActions.test.ts
  packages/suite/src/actions/wallet/__tests__/receiveActions.test.ts
  packages/suite/src/actions/wallet/blockchainActions.ts
  packages/suite/src/actions/wallet/constants/blockchainConstants.ts
  packages/suite/src/actions/wallet/selectedAccountActions.ts
  packages/suite/src/actions/wallet/storageActions.ts
  packages/suite/src/components/suite/NotificationCard/index.tsx
  packages/suite/src/components/wallet/AccountMode/BackendDisconnected.tsx
  packages/suite/src/middlewares/suite/suiteMiddleware.ts
  packages/suite/src/middlewares/wallet/blockchainMiddleware.ts
  packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts
  packages/suite/src/middlewares/wallet/index.ts
  packages/suite/src/reducers/wallet/blockchainReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/suite/deferred.ts
Labels: ready to review

#1535 Remove headers and account selectors, fix padding
  packages/suite/src/components/suite/Card/index.tsx
  packages/suite/src/components/wallet/WalletLayout/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/receive/components/FreshAddress/index.tsx
  packages/suite/src/views/wallet/receive/index.tsx
  packages/suite/src/views/wallet/send/components/Clear/index.tsx
  packages/suite/src/views/wallet/send/index.tsx
Labels: ready to review

#1533 Update/matej fixes
  packages/suite/src/components/dashboard/AssetsCard/components/Asset/index.tsx
  packages/suite/src/components/dashboard/AssetsCard/index.tsx
  packages/suite/src/components/dashboard/NewsFeed/index.tsx
  packages/suite/src/components/dashboard/SecurityFeatures/components/SecurityCard/index.tsx
  packages/suite/src/components/dashboard/SecurityFeatures/index.tsx
  packages/suite/src/components/settings/SettingsLayout/index.tsx
  packages/suite/src/components/suite/Menu/components/TopMenu/index.tsx
  packages/suite/src/components/suite/NotificationCard/index.tsx
  packages/suite/src/components/suite/Notifications/components/Wrapper.tsx
  packages/suite/src/components/suite/SuiteLayout/index.tsx
  packages/suite/src/components/suite/TransactionsGraph/index.tsx
  packages/suite/src/components/wallet/WalletLayout/index.tsx
  packages/suite/src/constants/suite/layout.ts
  packages/suite/src/reducers/suite/resizeReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/suite/notifications/index.tsx
  packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionSummary/index.tsx
Labels: ready to review

#1539 Various fixes
  packages/suite/src/components/dashboard/NewsFeed/index.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/AccountTypeSelect.tsx
  packages/suite/src/constants/wallet/sendForm.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/Container.ts
  packages/suite/src/views/settings/index.tsx
  packages/suite/src/views/wallet/details/index.tsx
  packages/suite/src/views/wallet/receive/components/FreshAddress/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormEthereum/components/Data/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/Fee/index.tsx
  packages/suite/src/views/wallet/send/components/Amount/index.tsx
  packages/suite/src/views/wallet/send/index.tsx
  packages/suite/src/views/wallet/transactions/components/PricePanel/Container.ts
  packages/suite/src/views/wallet/transactions/components/PricePanel/index.tsx
  packages/suite/src/views/wallet/transactions/index.tsx
Labels: ready to review

#1540 Fix/passphrase input
  docker/trezor-user-env/controller/main.py
  packages/components/src/components/form/Input/index.tsx
  packages/integration-tests/projects/suite-web/plugins/index.js
  packages/integration-tests/projects/suite-web/tests/suite/passphrase.test.ts
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
  packages/suite/src/components/wallet/AccountMode/AuthConfirmFailed.tsx
  packages/suite/src/reducers/suite/deviceReducer.ts
Labels: ready to review

#1549 add limit to label length
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/device/index.tsx
Labels: ready to review

#1544 data collection kick off
  packages/suite-native/src/reducers/store.ts
  packages/suite/jest.config.js
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/actions/suite/trezorConnectActions.ts
  packages/suite/src/middlewares/suite/analyticsMiddleware.ts
Labels: ready to review

#1551 more fixes
  packages/suite/src/components/suite/Menu/components/BottomMenu/index.tsx
  packages/suite/src/components/suite/Menu/components/TopMenu/index.tsx
  packages/suite/src/components/suite/Settings/components/TextColumn.tsx
  packages/suite/src/components/suite/modals/confirm/Address/index.tsx
  packages/suite/src/views/suite/notifications/index.tsx
  packages/suite/src/views/wallet/receive/components/FreshAddress/index.tsx
  packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx
Labels: ready to review

#1554 Add S3 sync script and readme
  packages/suite-web/README.md
  packages/suite-web/scripts/s3sync.sh
Labels: ready to review

#1565 Add menu corners
  packages/suite/src/components/suite/Menu/components/MainMenu/index.tsx
Labels: ready to review

#1564 Better transaction list style
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/TransactionItem/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx
Labels: ready to review

#1570 Fix/matej 321
  packages/suite/src/components/dashboard/SecurityFeatures/index.tsx
  packages/suite/src/components/suite/SwitchDevice/index.tsx
Labels: ready to review

#1558 moar fixes
  packages/components/src/components/form/Input/index.tsx
  packages/components/src/components/form/Select/index.tsx
  packages/components/src/components/form/index.stories.tsx
  packages/components/src/support/types/index.ts
  packages/suite/jest.config.js
  packages/suite/src/components/suite/Settings/components/ActionColumn.tsx
  packages/suite/src/components/suite/Settings/components/Row.tsx
  packages/suite/src/components/suite/Settings/components/TextColumn.tsx
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/reducers/suite/modalReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/recovery/index.tsx
  packages/suite/src/views/settings/device/index.tsx
  packages/suite/src/views/settings/wallet/index.tsx
  packages/suite/src/views/wallet/send/components/Address/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormBitcoin/components/Locktime/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormEthereum/components/GasPrice/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormRipple/components/DestinationTag/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/Fee/components/CustomFee/index.tsx
  packages/suite/src/views/wallet/send/components/Amount/components/Fiat/index.tsx
  packages/suite/src/views/wallet/send/components/Amount/index.tsx
Labels: ready to review

#1589 Fix/rollout test
  ci/packages/rollout.yml
  packages/rollout/integration/fresh-devices.ts
  packages/rollout/integration/get-binary-modifications.ts
  packages/rollout/integration/get-binary.ts
  packages/rollout/integration/with-fw-devices.ts
  packages/rollout/jest.config.integration.js
  packages/rollout/package.json
  packages/rollout/src/index.ts
  packages/rollout/start-integration.ts
Labels: ready to review

#1591 fix and unify Card paddings
  packages/suite/src/components/dashboard/AssetsCard/index.tsx
  packages/suite/src/components/dashboard/NewsFeed/index.tsx
  packages/suite/src/components/dashboard/PortfolioCard/components/DashboardGraph/index.tsx
  packages/suite/src/components/dashboard/PortfolioCard/index.tsx
  packages/suite/src/components/dashboard/SecurityFeatures/components/SecurityCard/index.tsx
  packages/suite/src/components/suite/Card/index.tsx
  packages/suite/src/components/suite/Settings/components/Row.tsx
  packages/suite/src/components/suite/Settings/components/Section.tsx
  packages/suite/src/components/suite/Settings/components/TextColumn.tsx
  packages/suite/src/constants/suite/layout.ts
  packages/suite/src/views/firmware/index.tsx
  packages/suite/src/views/suite/notifications/index.tsx
  packages/suite/src/views/wallet/details/index.tsx
  packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx
  packages/suite/src/views/wallet/send/index.tsx
  packages/suite/src/views/wallet/transactions/components/PricePanel/index.tsx
  packages/suite/src/views/wallet/transactions/components/TokenList/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionSummary/components/InfoCard/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionSummary/index.tsx
Labels: in progress

#1594 Fix/account menu selected
  packages/suite/src/actions/wallet/accountActions.ts
  packages/suite/src/actions/wallet/discoveryActions.ts
  packages/suite/src/actions/wallet/selectedAccountActions.ts
  packages/suite/src/components/wallet/Menu/index.tsx
  packages/suite/src/reducers/wallet/discoveryReducer.ts
  packages/suite/src/reducers/wallet/selectedAccountReducer.ts
  packages/suite/src/utils/wallet/accountUtils.ts
Labels: ready to review

#1602 Fix device settings btn redirection
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx
Labels: ready to review

#1567 optional https server in suite-web
  NOTES.md
  packages/suite-web/.gitignore
  packages/suite-web/package.json
  packages/suite-web/scripts/gencert.sh
  packages/suite-web/scripts/httpsServer.js
Labels: ready to review

#1607 visual fixes
  packages/suite/src/components/suite/modals/confirm/Address/components/DeviceDisconnected.tsx
  packages/suite/src/views/wallet/transactions/components/TokenList/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionSummary/index.tsx
Labels: READY TO REVIEW

#1612 Bug fixes
  .eslintrc.js
  packages/suite/src/components/backup/AfterBackupCheckboxes.tsx
  packages/suite/src/components/dashboard/PortfolioCard/components/DashboardGraph/index.tsx
  packages/suite/src/components/suite/HiddenPlaceholder/Container.ts
  packages/suite/src/components/suite/HiddenPlaceholder/index.tsx
  packages/suite/src/components/suite/Menu/components/BottomMenu/index.tsx
  packages/suite/src/components/suite/Menu/components/MainMenu/index.tsx
  packages/suite/src/components/suite/Menu/components/RoundedCorner/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/BasicDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/IODetails/index.tsx
  packages/suite/src/components/wallet/CoinBalance/index.tsx
  packages/suite/src/components/wallet/Menu/components/AccountItem/index.tsx
  packages/suite/src/views/wallet/transactions/components/TokenList/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/TransactionItem/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionSummary/components/InfoCard/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionSummary/index.tsx
  packages/suite/src/views/wallet/transactions/index.tsx
Labels: READY TO REVIEW

#1619 Feat/desktop initial file
  packages/suite-desktop/pages/_app.tsx
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src/support/VersionCheck.tsx
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#1617 Feat/dashboard exception
  packages/suite-desktop/pages/index.tsx
  packages/suite-web/pages/index.tsx
  packages/suite/src/actions/wallet/discoveryActions.ts
  packages/suite/src/components/dashboard/AssetsCard/components/Asset/index.tsx
  packages/suite/src/components/dashboard/AssetsCard/index.tsx
  packages/suite/src/components/dashboard/PortfolioCard/components/Exception/index.tsx
  packages/suite/src/components/dashboard/PortfolioCard/components/Header/index.tsx
  packages/suite/src/components/dashboard/PortfolioCard/components/Loading/index.tsx
  packages/suite/src/components/dashboard/PortfolioCard/index.tsx
  packages/suite/src/components/dashboard/SecurityFeatures/Container.ts
  packages/suite/src/components/dashboard/SecurityFeatures/index.tsx
  packages/suite/src/components/dashboard/index.tsx
  packages/suite/src/components/suite/NoRatesTooltip/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/AddWalletButton/index.tsx
  packages/suite/src/components/suite/modals/AddAccount/Container.tsx
  packages/suite/src/components/suite/modals/AddAccount/index.tsx
  packages/suite/src/components/wallet/DiscoveryProgress/index.tsx
  packages/suite/src/hooks/suite/index.ts
  packages/suite/src/hooks/suite/useDevice.ts
  packages/suite/src/hooks/suite/useDeviceActionLocks.ts
  packages/suite/src/hooks/suite/useDiscovery.ts
  packages/suite/src/hooks/wallet/index.ts
  packages/suite/src/hooks/wallet/useAccounts.ts
  packages/suite/src/hooks/wallet/useFiatValue.ts
  packages/suite/src/reducers/wallet/accountsReducer.ts
  packages/suite/src/reducers/wallet/discoveryReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/wallet/index.ts
  packages/suite/src/utils/wallet/accountUtils.ts
  packages/suite/src/views/dashboard/Container.ts
  packages/suite/src/views/dashboard/index.tsx
  packages/suite/src/views/recovery/index.tsx
  packages/suite/src/views/settings/device/index.tsx
  packages/suite/src/views/settings/wallet/components/CoinsGroup/index.tsx
Labels: READY TO REVIEW

#1624 Fix/electron reload
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src/support/VersionCheck.tsx
  packages/suite/src/views/wallet/receive/components/FreshAddress/index.tsx
Labels: READY TO REVIEW

#1625 Send bug fixes
  packages/suite/src/actions/suite/trezorConnectActions.ts
  packages/suite/src/components/suite/Card/index.tsx
  packages/suite/src/components/suite/Menu/components/BottomMenu/index.tsx
  packages/suite/src/components/suite/modals/ReviewTransaction/index.tsx
  packages/suite/src/views/wallet/send/components/Clear/index.tsx
  packages/suite/src/views/wallet/send/index.tsx
Labels: READY TO REVIEW

#1627 Fix/tx history unavailable
  packages/suite/src/actions/wallet/accountActions.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/transactions/components/AccountEmpty/index.tsx
  packages/suite/src/views/wallet/transactions/components/NoTransactions/index.tsx
  packages/suite/src/views/wallet/transactions/index.tsx
Labels: READY TO REVIEW

#1630 l10n sync
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/ru.json
Labels: READY TO REVIEW

#1597 Data collection 2
  packages/suite/src/actions/suite/__tests__/analyticsActions.test.ts
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/actions/suite/constants/analyticsConstants.ts
  packages/suite/src/actions/suite/constants/index.ts
  packages/suite/src/actions/suite/constants/suiteConstants.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/actions/wallet/constants/accountConstants.ts
  packages/suite/src/components/dashboard/SecurityFeatures/Container.ts
  packages/suite/src/components/dashboard/SecurityFeatures/index.tsx
  packages/suite/src/components/suite/Menu/Container.ts
  packages/suite/src/components/suite/Menu/components/BottomMenu/index.tsx
  packages/suite/src/components/suite/Menu/components/MainMenu/index.tsx
  packages/suite/src/components/suite/Menu/components/TopMenu/index.tsx
  packages/suite/src/components/suite/Settings/components/Analytics.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/AddWalletButton/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/WalletInstance/index.tsx
  packages/suite/src/hooks/suite/index.ts
  packages/suite/src/hooks/suite/useAnalytics.ts
  packages/suite/src/middlewares/onboarding/__tests__/onboardingMiddleware.test.ts
  packages/suite/src/middlewares/onboarding/onboardingMiddleware.ts
  packages/suite/src/middlewares/suite/__tests__/suiteMiddleware.test.ts
  packages/suite/src/middlewares/suite/analyticsMiddleware.ts
  packages/suite/src/middlewares/suite/suiteMiddleware.ts
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/reducers/suite/analyticsReducer.ts
  packages/suite/src/reducers/suite/index.ts
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/storage/index.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/utils/suite/__tests__/random.test.ts
  packages/suite/src/utils/suite/random.ts
  packages/suite/src/views/settings/device/index.tsx
Labels: READY TO REVIEW

#1633 remove bg, add underline on hover on tertiary btn
  packages/components/src/components/buttons/Button/index.tsx
Labels: READY TO REVIEW

#1631 firmware update improvements
  packages/suite-web/pages/_app.tsx
  packages/suite/src/components/onboarding/Icons/ConnectDevice.tsx
  packages/suite/src/components/onboarding/index.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/support/suite/ErrorBoundary.tsx
  packages/suite/src/views/firmware/index.tsx
  packages/suite/src/views/onboarding/steps/Firmware/Container.ts
  packages/suite/src/views/onboarding/steps/Firmware/index.tsx
  packages/suite/src/views/onboarding/steps/Pair/Container.ts
  packages/suite/src/views/onboarding/steps/Pair/components/Bridge/index.tsx
  packages/suite/src/views/onboarding/steps/Pair/index.tsx
  packages/suite/src/views/onboarding/steps/ResetDevice/index.tsx
  packages/suite/src/views/onboarding/unexpected-states/components/IsNotNewDevice.tsx
  packages/suite/src/views/suite/analytics/index.tsx
Labels: READY TO REVIEW

#1641 fixes
  packages/components/src/components/form/Input/index.tsx
  packages/suite/src/components/dashboard/SecurityFeatures/index.tsx
  packages/suite/src/components/suite/Notifications/FailedBackup.tsx
  packages/suite/src/components/suite/Notifications/NoBackup.tsx
  packages/suite/src/config/wallet/menu.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/TransactionItem/index.tsx
Labels: READY TO REVIEW

#1651 Add staging deploy to the CI pipeline
  .gitlab-ci.yml
  ci/packages/suite-web.yml
Labels: READY TO REVIEW

#1649 Fix XRP send max reserve
  packages/suite/src/actions/wallet/send/sendFormActions.ts
  packages/suite/src/actions/wallet/send/sendFormRippleActions.ts
  packages/suite/src/reducers/wallet/sendFormReducer.ts
  packages/suite/src/types/wallet/sendForm/actions.ts
  packages/suite/src/utils/wallet/sendFormUtils.ts
Labels: READY TO REVIEW

#1654 make pin modal cancelable
  packages/suite/src/components/suite/modals/Pin/index.tsx
Labels: READY TO REVIEW

#1647 Smart fees for ethereum like coins
  packages/suite/src/actions/wallet/blockchainActions.ts
Labels: READY TO REVIEW

#1655 UDev installers for linux
  packages/suite/src/components/suite/Preloader/index.tsx
  packages/suite/src/constants/suite/routes.ts
  packages/suite/src/constants/suite/urls.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/suite/dom.ts
  packages/suite/src/views/suite/device-connect/index.tsx
  packages/suite/src/views/suite/index.tsx
  packages/suite/src/views/suite/udev/index.tsx
Labels: READY TO REVIEW

#1657 SwitchDevice: enable wallet context everywhere
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/AddWalletButton/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/DeviceHeaderButton/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx
Labels: READY TO REVIEW

#1665 fix: #1661
  packages/suite/src/config/wallet/menu.tsx
Labels: READY TO REVIEW

#1669 fix modals rendered from switch device modal
  packages/suite/src/components/suite/SwitchDevice/index.tsx
Labels: READY TO REVIEW

#1667 fix #1660
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
Labels: READY TO REVIEW

#1671 fix #1435
  packages/suite/src/components/suite/Menu/components/BottomMenu/index.tsx
Labels: READY TO REVIEW

#1668 Let connect validate bitcoin like addresses
  packages/suite/src/actions/wallet/send/sendFormActions.ts
  packages/suite/src/reducers/wallet/sendFormReducer.ts
  packages/suite/src/utils/wallet/__tests__/sendFormUtils.test.ts
  packages/suite/src/utils/wallet/sendFormUtils.ts
  packages/suite/src/views/wallet/send/components/Address/Container.ts
  packages/suite/src/views/wallet/send/components/Address/index.tsx
Labels: READY TO REVIEW
