Repository trezor/trezor-suite, pull requests merged in 2020-10, with the labels that each got.

#2390 Fix/perf svg anims
  packages/suite/src/views/dashboard/components/AssetsCard/index.tsx
  packages/suite/src/views/dashboard/components/PortfolioCard/components/Loading/index.tsx
Labels: READY TO REVIEW

#2461 fix(components): SwitchDevice modal display only devices with state
  packages/integration-tests/projects/suite-web/tests/suite/remembering-devices.test.ts
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx
Labels: READY TO REVIEW

#2476 ci: hide beta e2e job
  ci/packages/suite-web.yml
Labels: READY TO REVIEW

#2479 chore: separate intl for review n send and send buttons
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/send/components/ReviewButton/index.tsx
Labels: READY TO REVIEW

#2495 fix(e2e): fix firmware e2e test
  packages/integration-tests/projects/suite-web/tests/firmware/firmware.test.ts
Labels: READY TO REVIEW

#2502 patch(nextjs): add file to allowed protocols for relative urls
  patches/next+9.5.3.patch
Labels: READY TO REVIEW

#2498 fix(send): fixed `useSendForm` hook called at top level
  packages/suite/src/views/wallet/send/index.tsx
Labels: READY TO REVIEW

#2504 Fade out effect for unconfirmed used addresses
  packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx
Labels: READY TO REVIEW

#2512 fix(style): fix analytics screen
  packages/suite/src/views/suite/analytics/index.tsx
Labels: READY TO REVIEW

#2509 fix(suite-desktop): don't try to run bridge on unsupported systems
  packages/suite-desktop/src-electron/bridge.ts
Labels: READY TO REVIEW

#2503 feat(metadata): visual improvements
  packages/suite/src/components/suite/Labeling/components/Metadata/index.tsx
Labels: READY TO REVIEW

#2510 more analytics (fw update)
  docs/SUMMARY.md
  docs/misc/analytics.md
  packages/suite/src/actions/firmware/firmwareActions.ts
  packages/suite/src/actions/suite/__tests__/analyticsActions.test.ts
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/components/firmware/Fingerprint.tsx
Labels: READY TO REVIEW

#2514 docs(analytics): improve docs
  docs/misc/analytics.md
Labels: READY TO REVIEW

#2515 chore(intl): separate message for hidden wallet modal's description
  packages/suite/src/components/suite/modals/Passphrase/index.tsx
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#2516 chore: update suite icon
  packages/suite-data/files/images/icons/512x512.icns
  packages/suite-data/files/images/icons/512x512.ico
  packages/suite-data/files/images/icons/512x512.png
Labels: READY TO REVIEW

#2518 style: proper word-breaking (break on whole words) in toast
  packages/suite/src/components/suite/ToastNotification/index.tsx
Labels: READY TO REVIEW

#2438 Oauth electron
  .eslintrc.js
  docs/SUMMARY.md
  docs/features/index.md
  docs/features/metadata.md
  packages/integration-tests/projects/suite-web/plugins/google.js
  packages/integration-tests/projects/suite-web/stubs/metadata.ts
  packages/integration-tests/projects/suite-web/tests/metadata/token-expires.test.ts
  packages/suite-data/files/oauth/oauth_receiver.html
  packages/suite-desktop/jest.config.js
  packages/suite-desktop/next.config.js
  packages/suite-desktop/package.json
  packages/suite-desktop/src-electron/__fixtures__/http.ts
  packages/suite-desktop/src-electron/__tests__/http.test.ts
  packages/suite-desktop/src-electron/config.ts
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src-electron/http-receiver.ts
  packages/suite-desktop/src-electron/oauth.ts
  packages/suite-desktop/src-electron/preload.ts
  packages/suite-desktop/src/support/BridgeStatus.ts
  packages/suite-native/src/services/metadata/DropboxProvider.ts
  packages/suite-native/src/services/metadata/GoogleProvider.ts
  packages/suite-native/src/utils/suite/oauth.ts
  packages/suite-web/next.config.js
  packages/suite/docs/README.md
  packages/suite/jest.config.js
  packages/suite/package.json
  packages/suite/src/actions/suite/__fixtures__/metadataActions.ts
  packages/suite/src/actions/suite/__tests__/metadataActions.test.ts
  packages/suite/src/actions/suite/constants/metadataConstants.ts
  packages/suite/src/actions/suite/metadataActions.ts
  packages/suite/src/services/google.ts
  packages/suite/src/services/metadata/DropboxProvider.ts
  packages/suite/src/services/metadata/GoogleProvider.ts
  packages/suite/src/services/metadata/UserDataProvider.ts
  packages/suite/src/storage/index.ts
  packages/suite/src/support/suite/ErrorBoundary.tsx
  packages/suite/src/types/suite/metadata.ts
  packages/suite/src/utils/suite/__tests__/metadata.test.ts
  packages/suite/src/utils/suite/__tests__/random.test.ts
  packages/suite/src/utils/suite/metadata.ts
  packages/suite/src/utils/suite/oauth.ts
  packages/suite/src/utils/suite/random.ts
  packages/suite/src/views/settings/index.tsx
  yarn.lock
Labels: READY TO REVIEW

#2521 Hide coinmarket from the menu
  packages/suite/src/config/wallet/menu.tsx
Labels: READY TO REVIEW

#2523 chore: yarn.lock
  yarn.lock
Labels: READY TO REVIEW

#2522 fix(metadata): do not swallow error in fetchMetadata action
  packages/suite-native/src/services/metadata/DropboxProvider.ts
  packages/suite-native/src/services/metadata/GoogleProvider.ts
  packages/suite/src/actions/suite/metadataActions.ts
Labels: READY TO REVIEW

#2530 Update intl messages
  packages/suite-data/files/translations/en.json
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#2543 fix: exclude unsupported networks from coin filter
  packages/suite/src/components/wallet/AccountsMenu/components/AccountSearchBox/index.tsx
  packages/suite/src/components/wallet/AccountsMenu/index.tsx
Labels: READY TO REVIEW

#2537 fix(send): clear "compose" errors when switching between FeeLevels
  packages/suite/src/hooks/wallet/useSendForm.ts
  packages/suite/src/hooks/wallet/useSendFormCompose.ts
  packages/suite/src/hooks/wallet/useSendFormFields.ts
  packages/suite/src/views/wallet/send/components/Fees/index.tsx
Labels: READY TO REVIEW

#2559 fix: layout distorted
  packages/suite/src/components/suite/modals/TransactionDetail/components/IODetails/index.tsx
Labels: October PR

#2557 fix: show correct details for token transaction
  packages/suite/src/components/suite/modals/TransactionDetail/components/AmountDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/AmountRow/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/BasicDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/index.tsx
Labels: October PR, READY TO REVIEW

#2566 feat(suite-desktop): add pre-release runtime flag
  docs/packages/suite-desktop.md
  packages/suite-desktop/package.json
  packages/suite-desktop/src-electron/electron.ts
Labels: October PR, READY TO REVIEW

#2564 fix: replaced wrong url on landing page
  packages/suite-web-landing/components/Layout/index.tsx
Labels: October PR

#2567 feat: add Trade to app menu with coming soon badge
  packages/components/src/components/Icon/icons.ts
  packages/components/src/config/variables.ts
  packages/components/src/images/icons/trade.svg
  packages/suite/src/components/suite/AppNavigation/index.tsx
  packages/suite/src/config/wallet/menu.tsx
  packages/suite/src/support/messages.ts
Labels: October PR, READY TO REVIEW

#2571 Feat/desktop prerelease
  docs/packages/suite-desktop.md
  packages/suite-desktop/package.json
  packages/suite-desktop/src-electron/electron.ts
Labels: READY TO REVIEW

#2565 chore: update intl
  packages/suite-data/files/translations/en.json
  packages/suite/src/components/backup/AfterBackupCheckboxes.tsx
  packages/suite/src/components/firmware/FirmwareProgress.tsx
  packages/suite/src/components/firmware/OnboardingInitial.tsx
  packages/suite/src/components/firmware/ReconnectInNormal.tsx
  packages/suite/src/components/recovery/SelectRecoveryType.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/firmware/index.ts
  packages/suite/src/views/onboarding/index.tsx
  packages/suite/src/views/onboarding/steps/Backup/index.tsx
  packages/suite/src/views/onboarding/steps/CreateOrRecover/index.tsx
  packages/suite/src/views/onboarding/steps/Hologram/index.tsx
  packages/suite/src/views/onboarding/steps/Pair/index.tsx
  packages/suite/src/views/onboarding/steps/Pin/index.tsx
  packages/suite/src/views/onboarding/steps/Recovery/index.tsx
  packages/suite/src/views/onboarding/unexpected-states/components/IsSameDevice.tsx
Labels: October PR, READY TO REVIEW

#2577 fix(metadata): dropbox token renewal
  packages/integration-tests/projects/suite-web/plugins/dropbox.js
  packages/integration-tests/projects/suite-web/plugins/index.js
  packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts
  packages/suite/src/actions/suite/metadataActions.ts
Labels: October PR, READY TO REVIEW

#2524 chore(analytics): updated endpoints, added events, improved tests
  docs/misc/analytics.md
  packages/integration-tests/projects/suite-web/tests/suite/analytics.test.ts
  packages/suite-native/src/utils/suite/env.ts
  packages/suite/src/actions/suite/__tests__/analyticsActions.test.ts
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/middlewares/suite/analyticsMiddleware.ts
  packages/suite/src/utils/suite/__fixtures__/analytics.ts
  packages/suite/src/utils/suite/env.ts
Labels: October PR, READY TO REVIEW

#2553 Move EstimatedMiningTime to components
  packages/suite/src/components/wallet/EstimatedMiningTime/index.tsx
  packages/suite/src/components/wallet/index.tsx
  packages/suite/src/views/wallet/send/components/Fees/index.tsx
Labels: November PR, READY TO REVIEW

#2586 fix: change default window size behavior
  packages/suite-desktop/src-electron/store.ts
Labels: READY TO REVIEW

#2585 docs(e2e): move and update docs on e2e
  docs/SUMMARY.md
  docs/tests/e2e-web.md
  docs/tests/index.md
  packages/integration-tests/projects/suite-web/README.md
Labels: READY TO REVIEW

#2583 chore: remove unused isBeta() util
  packages/suite/src/utils/suite/__tests__/build.test.ts
  packages/suite/src/utils/suite/build.ts
Labels: READY TO REVIEW

#2527 chore: remove dead code
  packages/suite/src/actions/onboarding/__fixtures__/newsletterActions.ts
  packages/suite/src/actions/onboarding/__tests__/newsletterActions.test.ts
  packages/suite/src/actions/onboarding/constants/calls.ts
  packages/suite/src/actions/onboarding/constants/events.ts
  packages/suite/src/actions/onboarding/constants/onboarding.ts
  packages/suite/src/actions/onboarding/newsletterActions.ts
  packages/suite/src/actions/onboarding/onboardingActions.ts
  packages/suite/src/actions/recovery/__tests__/recoveryActions.test.ts
  packages/suite/src/reducers/onboarding/newsletterReducer.ts
  packages/suite/src/reducers/onboarding/onboardingReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/onboarding/events.ts
  packages/suite/src/types/onboarding/index.ts
Labels: November PR, READY TO REVIEW

#2590 chore: sync intl
  packages/suite-data/files/translations/en.json
  packages/suite/src/components/firmware/NoNewFirmware.tsx
  packages/suite/src/components/wallet/AccountException/FirmwareUnsupported.tsx
  packages/suite/src/support/messages.ts
Labels: October PR, READY TO REVIEW

#2597 chore: bump trezor-connect 8.1.6
  packages/suite-data/files/connect/data/config.json
  packages/suite-data/files/connect/data/firmware/2/releases.json
  packages/suite-data/files/connect/iframe.html
  packages/suite-data/files/connect/js/iframe.69d42a7efea1bb253306.js
  packages/suite/package.json
  yarn.lock
Labels: October PR, READY TO REVIEW

#2598 fix(send): validate ERC20 balance when using "set-max" option
  packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts
Labels: October PR, READY TO REVIEW

#2601 chore: update landing page copy
  packages/suite-web-landing/components/Download/index.tsx
  packages/suite-web-landing/components/Layout/index.tsx
  packages/suite-web-landing/pages/index.tsx
Labels: October PR, READY TO REVIEW

#2603 fix(fw-update): webusb button was missing
  packages/suite/src/components/firmware/ReconnectInBootloader.tsx
Labels: October PR

#2608 chore: update copy
  packages/suite-data/files/translations/en.json
Labels: November PR

#2620 hide rbf behind feature flag
  packages/suite/src/config/suite/features.ts
  packages/suite/src/hooks/wallet/useSendForm.ts
  packages/suite/src/hooks/wallet/useSendFormFields.ts
  packages/suite/src/views/wallet/send/components/Options/components/BitcoinOptions/components/Locktime/index.tsx
  packages/suite/src/views/wallet/send/components/Options/components/BitcoinOptions/index.tsx
Labels: October PR

#2624 fix(desktop): add missing camera permissions in macos
  packages/suite-desktop/entitlements.mac.inherit.plist
Labels: November PR, READY TO REVIEW

#2609 fix(send): set "isDirty" also on FeeLevel change
  packages/suite/src/hooks/wallet/useSendFormCompose.ts
Labels: November PR, READY TO REVIEW

#2635 feat: add favicon
  packages/landing-page/pages/_app.tsx
  packages/landing-page/pages/_document.tsx
  packages/suite-data/config.ts
  packages/suite-data/files/images/icons/favicon/favicon.png
  packages/suite-web-landing/pages/_app.tsx
  packages/suite-web-landing/pages/_document.tsx
  packages/suite-web/pages/_document.tsx
Labels: READY TO REVIEW

#2610 Make add-account modal usable in invity exchange
  packages/suite/src/actions/suite/modalActions.ts
  packages/suite/src/components/suite/modals/AddAccount/Container.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/NetworkSelect.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/Wrapper.tsx
  packages/suite/src/components/suite/modals/AddAccount/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
Labels: November PR, READY TO REVIEW

#2645 Download new translations
  packages/suite-data/files/translations/en.json
Labels: READY TO REVIEW

#2649 Extract form validation types from sendForm for better reuse
  packages/suite/src/components/wallet/InputError/index.tsx
  packages/suite/src/types/wallet/coinmarketBuyForm.ts
  packages/suite/src/types/wallet/form.ts
  packages/suite/src/types/wallet/sendForm.ts
Labels: November PR, READY TO REVIEW

#2548 Feat: Trezor Suite desktop - custom title bar
  packages/components/src/components/Icon/icons.ts
  packages/components/src/components/logos/TrezorLogo/index.stories.tsx
  packages/components/src/components/logos/TrezorLogo/logos.ts
  packages/components/src/components/logos/index.stories.tsx
  packages/components/src/config/variables.ts
  packages/components/src/images/icons/window_close.svg
  packages/components/src/images/icons/window_maximize.svg
  packages/components/src/images/icons/window_minimize.svg
  packages/components/src/images/icons/window_restore.svg
  packages/components/src/images/trezor_logo_suite_compact.svg
  packages/components/src/support/types/index.ts
  packages/suite-desktop/pages/_app.tsx
  packages/suite-desktop/pages/_document.tsx
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src-electron/preload.ts
  packages/suite-desktop/src/support/DesktopTitlebar.tsx
  packages/suite/global.d.ts
  packages/suite/src/utils/suite/env.ts
Labels: November PR, READY TO REVIEW

#2663 refactor(suite-desktop): custom titlebar
  packages/suite-desktop/pages/_app.tsx
  packages/suite-desktop/src/support/DesktopTitlebar.tsx
Labels: November PR, READY TO REVIEW

#2623 Feat: Graph touch up
  packages/suite/package.json
  packages/suite/src/components/suite/TransactionsGraph/components/CustomBar/index.tsx
  packages/suite/src/components/suite/TransactionsGraph/components/CustomTooltipAccount/index.tsx
  packages/suite/src/components/suite/TransactionsGraph/components/CustomTooltipBase/index.tsx
  packages/suite/src/components/suite/TransactionsGraph/components/CustomTooltipDashboard/index.tsx
  packages/suite/src/components/suite/TransactionsGraph/index.tsx
  yarn.lock
Labels: November PR, READY TO REVIEW

#2666 fix(suite-web-landing): fix iOS CSS gradients w/ transparent color
  packages/suite-web-landing/components/Feature/index.tsx
  packages/suite-web-landing/package.json
  yarn.lock
Labels: November PR, READY TO REVIEW

#2669 fix(discreet): discreet effect cut out in accounts menu
  packages/suite/src/components/wallet/AccountsMenu/components/AccountItem/index.tsx
Labels: READY TO REVIEW

#2581 style: fix huge values overflowing in token list
  packages/suite/src/components/suite/FormattedCryptoAmount/index.tsx
  packages/suite/src/views/wallet/transactions/components/TokenList/index.tsx
Labels: November PR

#2589 design: new way of displaying changelog
  packages/suite/src/components/firmware/Initial.tsx
Labels: November PR

#2642 fix(dropbox): fix metadata files location for scoped app
  packages/suite/src/actions/suite/metadataActions.ts
  packages/suite/src/services/metadata/DropboxProvider.ts
Labels: READY TO REVIEW

#2690 fix(receive): address row should not be clickable, reveal is only on …
  packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx
Labels: READY TO REVIEW

#2551 feat: add intl support for suite-web-landing
  packages/suite-web-landing/components/Download/index.tsx
  packages/suite-web-landing/components/Layout/index.tsx
  packages/suite-web-landing/components/Translation/index.tsx
  packages/suite-web-landing/package.json
  packages/suite-web-landing/pages/index.tsx
  packages/suite-web-landing/support/styles.ts
  packages/suite/package.json
  packages/suite/src/components/suite/FormattedNumber/index.tsx
  packages/suite/src/components/suite/Translation/components/BaseTranslation/index.tsx
  packages/suite/src/components/suite/Translation/components/ConnectedHelperTooltip/index.tsx
  packages/suite/src/components/suite/Translation/components/HelperTooltip/index.tsx
  packages/suite/src/components/suite/Translation/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/support/suite/ConnectedIntlProvider.tsx
  packages/suite/src/types/suite/index.ts
  yarn.lock
Labels: November PR, READY TO REVIEW

#2682 chore: use l10n message for window titles
  packages/suite/src/components/wallet/CoinmarketLayout/index.tsx
  packages/suite/src/components/wallet/WalletLayout/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/buy/detail/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/offers/index.tsx
  packages/suite/src/views/wallet/details/index.tsx
  packages/suite/src/views/wallet/receive/index.tsx
  packages/suite/src/views/wallet/send/index.tsx
  packages/suite/src/views/wallet/sign-verify/index.tsx
  packages/suite/src/views/wallet/transactions/index.tsx
Labels: READY TO REVIEW

#2702 fix: translations for buy crypto
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#2695 chore: remove graph for fiat rates for a past week
  packages/suite/src/actions/wallet/fiatRatesActions.ts
  packages/suite/src/utils/suite/__tests__/date.test.ts
  packages/suite/src/utils/suite/date.ts
  packages/suite/src/views/dashboard/components/AssetsCard/components/LastWeekGraph/index.tsx
Labels: READY TO REVIEW

#2709 fix(suite-desktop): fix bundling of bridge binaries
  packages/suite-desktop/package.json
  packages/suite-desktop/src-electron/bridge.ts
Labels: November PR

#2707 Update intl messages
  packages/suite-data/files/translations/en.json
Labels: READY TO REVIEW

#2727 fix(suite-desktop): use static BuildId for Next.js
  packages/suite-desktop/next.config.js
Labels: READY TO REVIEW

#2726 fix: Remove ONG from list of supported tokens for buy crypto
  packages/suite/src/utils/wallet/coinmarket/__tests__/buyUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/buyUtils.ts
Labels: READY TO REVIEW

#2741 fix: use buy crypto payment method icons tailored for Suite, improve design
  packages/suite/src/components/wallet/CoinmarketBuyOfferInfo/index.tsx
  packages/suite/src/components/wallet/CoinmarketBuyProviderInfo/index.tsx
  packages/suite/src/components/wallet/CoinmarketPaymentType/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/buy/detail/Detail/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/SelectedOffer/index.tsx
Labels: READY TO REVIEW

#2735 fix(suite): graph causes render errors
  packages/suite/src/components/suite/TransactionsGraph/components/CustomTooltipAccount/index.tsx
  packages/suite/src/components/suite/TransactionsGraph/components/CustomTooltipBase/index.tsx
  packages/suite/src/components/suite/TransactionsGraph/components/CustomTooltipDashboard/index.tsx
  packages/suite/src/components/suite/TransactionsGraph/index.tsx
Labels: READY TO REVIEW

#2734 fix(suite): discreet effect cut off
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/TransactionItem/components/BaseTargetLayout/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/TransactionItem/index.tsx
Labels: READY TO REVIEW

#2733 Desktop Titlebar - Fixes and improvements (functionality and style)
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src/support/DesktopTitlebar.tsx
Labels: READY TO REVIEW

#2722 Invity buy improvements
  packages/suite-desktop/src-electron/config.ts
  packages/suite/src/components/wallet/CoinmarketFooter/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/BuyTransaction/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/ExchangeTransaction/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/detail/components/PaymentFailed/index.tsx
Labels: READY TO REVIEW

#2763 Update intl message
  packages/suite-data/files/translations/en.json
Labels: READY TO REVIEW

#2729 fix(suite): graph tooltips overflow
  packages/suite/src/components/suite/TransactionsGraph/components/CustomTooltipBase/index.tsx
Labels: November PR, READY TO REVIEW

#2762 Desktop - Invity Buy - Change popup flow to default browser
  packages/suite-data/config.ts
  packages/suite-data/files/buy/buy_receiver.html
  packages/suite-desktop/src-electron/buy.ts
  packages/suite-desktop/src-electron/config.ts
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src-electron/http-receiver.ts
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/BuyTransaction/index.tsx
  packages/suite/src/constants/wallet/coinmarket/buy.ts
  packages/suite/src/hooks/wallet/useCoinmarket.ts
  packages/suite/src/hooks/wallet/useCoinmarketBuyDetail.ts
  packages/suite/src/hooks/wallet/useCoinmarketBuyOffers.ts
  packages/suite/src/reducers/wallet/coinmarketReducer.ts
  packages/suite/src/utils/wallet/coinmarket/buyUtils.ts
Labels: READY TO REVIEW

#2755 fix(metadata): fix rerender of address metadata
  packages/suite/src/components/suite/Labeling/components/Metadata/index.tsx
Labels: READY TO REVIEW

#2775 chore(electron): invoke/handle
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src-electron/preload.ts
  packages/suite/global.d.ts
  packages/suite/src/utils/suite/oauth.ts
Labels: READY TO REVIEW

#2773 fix(settings): disable button on empty custom blockbook url field
  packages/suite/src/components/suite/modals/AdvancedCoinSettings/components/CustomBlockbookUrls.tsx
Labels: READY TO REVIEW

#2769 fix(fw-update): make modal cancellable in check-seed step
  packages/integration-tests/projects/suite-web/tests/firmware/firmware.test.ts
  packages/suite/src/views/firmware/index.tsx
Labels: READY TO REVIEW

#2772 Fix app quit on MacOS
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src-electron/utils.ts
Labels: READY TO REVIEW

#2787 fix(suite): remove crazy re-exports in types
  packages/suite/src/types/firmware/index.ts
  packages/suite/src/types/onboarding/index.ts
  packages/suite/src/types/settings/index.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/types/wallet/index.ts
Labels: READY TO REVIEW

#2766 feat(metadata): display address label as a fallback in tx lists if tx…
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/TransactionItem/components/Target/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/TransactionItem/components/TargetAddressLabel/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/TransactionItem/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx
Labels: READY TO REVIEW

#2794 fix(analytics): add wallet event was not reported
  packages/integration-tests/projects/suite-web/tests/suite/analytics.test.ts
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/AddWalletButton/index.tsx
Labels: READY TO REVIEW

#2783 Fix/send form ui improvements
  packages/suite/src/hooks/wallet/__tests__/SendIndex.tsx
  packages/suite/src/views/wallet/send/components/Options/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Address/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/TokenSelect/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/index.tsx
  packages/suite/src/views/wallet/send/components/ReviewButton/index.tsx
  packages/suite/src/views/wallet/send/components/TotalSent/index.tsx
Labels: READY TO REVIEW

#2797 fix(metadata): long label truncating (#2653)
  packages/suite/src/components/suite/Labeling/components/Metadata/index.tsx
  packages/suite/src/components/suite/Labeling/components/Metadata/withDropdown.tsx
Labels: READY TO REVIEW

#2795 update z-cash tx params for canocopy fork
  packages/suite/src/actions/wallet/send/sendFormBitcoinActions.ts
  packages/suite/src/constants/wallet/sendForm.ts
Labels: READY TO REVIEW

#2788 feat(suite-desktop): new way of launching processes
  docs/packages/suite-desktop.md
  package.json
  packages/suite-desktop/package.json
  packages/suite-desktop/src-electron/bridge.ts
  packages/suite-desktop/src-electron/constants.ts
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src-electron/processes/BaseProcess.ts
  packages/suite-desktop/src-electron/processes/BridgeProcess.ts
  yarn.lock
Labels: READY TO REVIEW

#2806 feat(suite-web-landing): Add OG meta tags
  packages/suite-data/files/images/suite-web-landing/mega.png
  packages/suite-web-landing/pages/_document.tsx
Labels: READY TO REVIEW

#2798 chore: bump typescript patch version
  package.json
  yarn.lock
Labels: READY TO REVIEW

#2805 fix(suite-desktop): Unify title bar on MacOS
  packages/components/src/components/Icon/icons.ts
  packages/components/src/config/variables.ts
  packages/components/src/images/icons/window_maximize_mac.svg
  packages/components/src/images/icons/window_restore_mac.svg
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src-electron/preload.ts
  packages/suite-desktop/src/support/DesktopTitlebar.tsx
Labels: READY TO REVIEW

#2821 Fix/pending tx unused addr
  packages/suite/src/actions/wallet/selectedAccountActions.ts
  packages/suite/src/utils/wallet/transactionUtils.ts
  packages/suite/src/views/wallet/receive/Container.ts
  packages/suite/src/views/wallet/receive/components/FreshAddress/index.tsx
  packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx
  packages/suite/src/views/wallet/receive/index.tsx
Labels: READY TO REVIEW

#2817 Fix/send form anim
  packages/suite/src/views/wallet/send/components/Outputs/index.tsx
Labels: READY TO REVIEW
