Repository trezor/trezor-suite, pull requests merged in 2020-12, with the labels that each got.

#3099 ci: adjust assetPrefix in landing page build
  ci/packages/landing-page.yml
Labels: READY TO REVIEW

#3090 fix: ButtonRequest_FirmwareCheck
  packages/integration-tests/projects/suite-web/snapshots/onboarding/firmware-update.test.ts/Onboarding - firmware update -- firmware update error.snap.png
  packages/integration-tests/projects/suite-web/support/commands.ts
  packages/integration-tests/projects/suite-web/support/utils/test-env.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/firmware-update.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/button-requests.test.ts
  packages/suite/src/components/firmware/FirmwareProgress.tsx
  packages/suite/src/components/suite/modals/Pin/index.tsx
  packages/suite/src/components/suite/modals/confirm/Fingerprint/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/reducers/firmware/firmwareReducer.ts
  packages/suite/src/utils/firmware/index.ts
  packages/suite/src/views/firmware/index.tsx
  packages/suite/src/views/onboarding/steps/Firmware/index.tsx
Labels: READY TO REVIEW, Release

#3104 chore: update trezor-connect 8.1.19
  packages/suite-data/files/connect/data/bridge/latest.txt
  packages/suite-data/files/connect/data/bridge/releases.json
  packages/suite-data/files/connect/data/coins.json
  packages/suite-data/files/connect/iframe.html
  packages/suite-data/files/connect/js/iframe.1bf6cd5070b10a517ebd.js
  packages/suite-data/files/connect/js/iframe.8771e344f4978ab26faa.js
  packages/suite-data/files/connect/workers/blockbook-worker.116f8d5317cf8c49c2f9.js
  packages/suite-data/files/connect/workers/blockbook-worker.97bf124d6c0c92a164f5.js
  packages/suite-data/files/connect/workers/ripple-worker.99ea782e5c3fb4c9842e.js
  packages/suite-data/files/connect/workers/ripple-worker.ad597e70f20819f7a320.js
  packages/suite/package.json
  packages/suite/src/support/tests/setupJest.ts
  yarn.lock
Labels: READY TO REVIEW, Release

#3026 fix(send): DOGE fees
  packages/suite/docs/SEND.md
  packages/suite/src/support/messages.ts
  packages/suite/src/types/wallet/sendForm.ts
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx
Labels: READY TO REVIEW, Release

#3102 chore(components): update ltc, btg logos
  packages/components/src/images/coins/btg.svg
  packages/components/src/images/coins/ltc.svg
Labels: READY TO REVIEW

#3098 fix(desktop): border around app for Win/Linux
  packages/components/src/components/Modal/index.tsx
  packages/suite-desktop/src/support/DesktopTitlebar.tsx
  packages/suite-desktop/src/support/DesktopUpdater.tsx
  packages/suite/.stylelintignore
  packages/suite/src/components/suite/Backdrop/index.tsx
  packages/suite/src/components/suite/DeviceInvalidModeLayout/index.tsx
  packages/suite/src/components/suite/DiscoveryLoader/index.tsx
  packages/suite/src/components/suite/Loading/index.tsx
  packages/suite/src/components/suite/Modal/index.tsx
  packages/suite/src/components/suite/Preloader/components/InitialLoading/index.tsx
  packages/suite/src/components/suite/SuiteLayout/index.tsx
  packages/suite/src/components/suite/SwitchDevice/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/Wrapper.tsx
  packages/suite/src/components/suite/modals/AdvancedCoinSettings/index.tsx
  packages/suite/src/components/suite/modals/BackgroundGallery/index.tsx
  packages/suite/src/components/suite/modals/CoinmarketReviewTransaction/index.tsx
  packages/suite/src/components/suite/modals/DisconnectDevice/index.tsx
  packages/suite/src/components/suite/modals/ImportTransaction/index.tsx
  packages/suite/src/components/suite/modals/Log/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/index.tsx
  packages/suite/src/components/suite/modals/PassphraseDuplicate/index.tsx
  packages/suite/src/components/suite/modals/PassphraseOnDevice/index.tsx
  packages/suite/src/components/suite/modals/PassphraseSource/index.tsx
  packages/suite/src/components/suite/modals/Pin/index.tsx
  packages/suite/src/components/suite/modals/PinInvalid/index.tsx
  packages/suite/src/components/suite/modals/PinMismatch/index.tsx
  packages/suite/src/components/suite/modals/QrScanner/index.tsx
  packages/suite/src/components/suite/modals/ReviewTransaction/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/index.tsx
  packages/suite/src/components/suite/modals/WipeDevice/index.tsx
  packages/suite/src/components/suite/modals/Word/index.tsx
  packages/suite/src/components/suite/modals/WordAdvanced/index.tsx
  packages/suite/src/components/suite/modals/confirm/Action/index.tsx
  packages/suite/src/components/suite/modals/confirm/Address/index.tsx
  packages/suite/src/components/suite/modals/confirm/CoinmarketBuyTerms/index.tsx
  packages/suite/src/components/suite/modals/confirm/CoinmarketExchangeTerms/index.tsx
  packages/suite/src/components/suite/modals/confirm/NoBackup/index.tsx
  packages/suite/src/components/suite/modals/confirm/UnverifiedAddress/index.tsx
  packages/suite/src/components/suite/modals/confirm/Xpub/index.tsx
  packages/suite/src/components/suite/modals/metadata/MetadataProvider/index.tsx
  packages/suite/src/constants/suite/layout.ts
  packages/suite/src/utils/suite/env.ts
  packages/suite/src/views/backup/index.tsx
  packages/suite/src/views/firmware/index.tsx
  packages/suite/src/views/onboarding/index.tsx
  packages/suite/src/views/recovery/index.tsx
  packages/suite/src/views/suite/analytics/index.tsx
  packages/suite/src/views/suite/bridge/index.tsx
  packages/suite/src/views/suite/device-connect/index.tsx
  packages/suite/src/views/suite/device-recovery-mode/index.tsx
  packages/suite/src/views/suite/notifications/index.tsx
  packages/suite/src/views/suite/udev/index.tsx
  packages/suite/src/views/suite/version/index.tsx
  packages/suite/src/views/suite/welcome/index.tsx
Labels: READY TO REVIEW

#2896 chore: add instructions on how to clear electron cache
  docs/SUMMARY.md
  docs/misc/notes.md
Labels: READY TO REVIEW

#3103 chore: cleanup Ticker and reuse current rate
  packages/suite/src/actions/wallet/fiatRatesActions.ts
  packages/suite/src/components/suite/Ticker/index.tsx
Labels: READY TO REVIEW

#3114 ci: manual desktop builds on feature branches
  ci/packages/suite-desktop.yml
Labels: READY TO REVIEW

#3124 fix(rbf): update blockTime in replaced tx
  packages/suite/src/actions/wallet/transactionActions.ts
Labels: READY TO REVIEW, Release

#3078 chore(suite-desktop): refactor (splitting into modules and libs)
  packages/suite-desktop/package.json
  packages/suite-desktop/scripts/build.js
  packages/suite-desktop/scripts/dev.js
  packages/suite-desktop/src-electron/__tests__/http.test.ts
  packages/suite-desktop/src-electron/app.ts
  packages/suite-desktop/src-electron/electron-next.d.ts
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src-electron/index.d.ts
  packages/suite-desktop/src-electron/libs/buy.ts
  packages/suite-desktop/src-electron/libs/constants.ts
  packages/suite-desktop/src-electron/libs/http-receiver.ts
  packages/suite-desktop/src-electron/libs/menu.ts
  packages/suite-desktop/src-electron/libs/processes/BaseProcess.ts
  packages/suite-desktop/src-electron/libs/processes/BridgeProcess.ts
  packages/suite-desktop/src-electron/libs/processes/TorProcess.ts
  packages/suite-desktop/src-electron/libs/screen.ts
  packages/suite-desktop/src-electron/libs/store.ts
  packages/suite-desktop/src-electron/libs/user-data.ts
  packages/suite-desktop/src-electron/libs/utils.ts
  packages/suite-desktop/src-electron/metadata.ts
  packages/suite-desktop/src-electron/modules/auto-updater.ts
  packages/suite-desktop/src-electron/modules/bridge.ts
  packages/suite-desktop/src-electron/modules/csp.ts
  packages/suite-desktop/src-electron/modules/dev-tools.ts
  packages/suite-desktop/src-electron/modules/external-links.ts
  packages/suite-desktop/src-electron/modules/file-protocol.ts
  packages/suite-desktop/src-electron/modules/http-receiver.ts
  packages/suite-desktop/src-electron/modules/menu.ts
  packages/suite-desktop/src-electron/modules/metadata.ts
  packages/suite-desktop/src-electron/modules/request-filter.ts
  packages/suite-desktop/src-electron/modules/shortcuts.ts
  packages/suite-desktop/src-electron/modules/tor.ts
  packages/suite-desktop/src-electron/modules/window-controls.ts
  packages/suite-desktop/src-electron/store.ts
  packages/suite-desktop/src-electron/tsconfig.json
  packages/suite-desktop/tsconfig.json
Labels: READY TO REVIEW

#3110 Fix long transaction ID
  packages/suite/src/components/wallet/CoinmarketExchangeOfferInfo/index.tsx
  packages/suite/src/components/wallet/CoinmarketTransactionId/index.tsx
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#3122 tests(e2e): use new trezor-user-env, fix, unskip, rework
  ci/packages/suite-web.yml
  packages/integration-tests/projects/suite-web/plugins/index.js
  packages/integration-tests/projects/suite-web/support/commands.ts
  packages/integration-tests/projects/suite-web/support/utils/shortcuts.ts
  packages/integration-tests/projects/suite-web/tests/firmware/firmware.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/remembered-device.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t1-create-wallet.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t1-recovery-advanced.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t1-recovery-basic.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t2-create-wallet.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t2-recovery-fail.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t2-recovery-persistence.test.ts
  packages/integration-tests/projects/suite-web/tests/recovery/t1-dry-run.test.ts
  packages/integration-tests/projects/suite-web/tests/recovery/t2-dry-run-persistence.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/t1-device-settings.test.ts
Labels: READY TO REVIEW

#3126 fix(invity): cannot select undiscovered account
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/SelectedOffer/components/VerifyAddress/ReceiveOptions/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/SelectedOffer/components/VerifyAddress/index.tsx
Labels: Release

#3128 fix(desktop): Missing offset for notifications
  packages/suite/src/support/suite/styles/notifications.ts
Labels: Release

#3136 fix: hidden wallet number
  packages/integration-tests/projects/suite-web/tests/suite/passhprase-numbering.test.ts
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx
  packages/suite/src/reducers/suite/deviceReducer.ts
Labels: READY TO REVIEW

#2979 fix(recovery): send u2f counter in params
  packages/suite/src/actions/recovery/recoveryActions.ts
Labels: READY TO REVIEW

#3134 fix(landing): use absolute URLs for og:image and twitter:image meta tags
  packages/suite-web-landing/pages/_document.tsx
  packages/suite/src/constants/suite/urls.ts
Labels: READY TO REVIEW

#3135 fix connect metadata provider
  packages/suite/src/utils/suite/oauth.ts
Labels: READY TO REVIEW, Release

#3120 chore(suite): unify account fallback/error screens
  packages/suite/src/components/wallet/AccountException/AccountNotEnabled.tsx
  packages/suite/src/components/wallet/AccountException/AccountNotExists.tsx
  packages/suite/src/components/wallet/AccountException/AccountNotLoaded.tsx
  packages/suite/src/components/wallet/AccountException/AuthFailed.tsx
  packages/suite/src/components/wallet/AccountException/DiscoveryEmpty.tsx
  packages/suite/src/components/wallet/AccountException/DiscoveryFailed.tsx
  packages/suite/src/components/wallet/AccountException/FirmwareUnsupported.tsx
  packages/suite/src/components/wallet/AccountException/components/Wrapper.tsx
  packages/suite/src/components/wallet/AccountExceptionLayout/index.tsx
  packages/suite/src/components/wallet/index.tsx
  packages/suite/src/views/wallet/transactions/components/NoTransactions/index.tsx
Labels: READY TO REVIEW

#3084 Feat/loading skeletons
  packages/components/src/components/Modal/index.tsx
  packages/components/src/config/colors.ts
  packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/address-metadata.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/dropbox-api-errors.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/google-api-errors.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/interval-fetching.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/output-labeling.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/remembered-device.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/switching-providers.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/wallet-metadata.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/passhprase-duplicate.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/passhprase-numbering.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/passphrase-disabled.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/passphrase.test.ts
  packages/suite/src/components/suite/Skeleton/index.tsx
  packages/suite/src/components/suite/TransactionsGraph/components/SkeletonTransactionsGraph/index.tsx
  packages/suite/src/components/suite/TransactionsGraph/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/index.tsx
  packages/suite/src/components/wallet/AccountMode/LoadingOtherAccounts.tsx
  packages/suite/src/components/wallet/AccountMode/index.tsx
  packages/suite/src/components/wallet/AccountTopPanel/components/AccountNavigation/index.tsx
  packages/suite/src/components/wallet/AccountTopPanel/index.tsx
  packages/suite/src/components/wallet/AccountsMenu/components/AccountItem/index.tsx
  packages/suite/src/components/wallet/AccountsMenu/index.tsx
  packages/suite/src/components/wallet/DiscoveryProgress/index.tsx
  packages/suite/src/components/wallet/WalletLayout/components/AccountLoader.tsx
  packages/suite/src/components/wallet/WalletLayout/index.tsx
  packages/suite/src/config/wallet/menu.tsx
  packages/suite/src/hooks/suite/index.ts
  packages/suite/src/hooks/suite/useLoadingSkeleton.ts
  packages/suite/src/views/dashboard/components/AssetsCard/components/Asset/index.tsx
  packages/suite/src/views/dashboard/components/AssetsCard/index.tsx
  packages/suite/src/views/dashboard/components/PortfolioCard/components/Loading/index.tsx
  packages/suite/src/views/dashboard/components/PortfolioCard/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/SkeletonTransactionItem/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionSummary/components/SummaryCards/components/InfoCard/index.tsx
Labels: READY TO REVIEW

#3088 Suite-Desktop: Prioritize update modals
  packages/suite-desktop/pages/_app.tsx
  packages/suite-desktop/src/support/DesktopUpdater.tsx
  packages/suite-desktop/src/support/DesktopUpdater/Available.tsx
  packages/suite-desktop/src/support/DesktopUpdater/Downloading.tsx
  packages/suite-desktop/src/support/DesktopUpdater/Ready.tsx
  packages/suite-desktop/src/support/DesktopUpdater/styles.ts
  packages/suite/src/components/suite/Preloader/index.tsx
Labels: READY TO REVIEW

#3138 fix(e2e): after skeletons passphrase-numbering newly added test fixed
  packages/integration-tests/projects/suite-web/tests/suite/passhprase-numbering.test.ts
Labels: READY TO REVIEW

#3132 fix(invity): dark mode icons
  packages/components/src/config/colors.ts
  packages/suite/src/components/wallet/CoinmarketBuyProviderInfo/index.tsx
  packages/suite/src/components/wallet/CoinmarketExchangeProviderInfo/index.tsx
  packages/suite/src/components/wallet/CoinmarketPaymentType/index.tsx
Labels: READY TO REVIEW

#3131 fix(invity): Buy - add more validation messages
  packages/suite/src/views/wallet/coinmarket/buy/components/BuyForm/Inputs/index.tsx
Labels: READY TO REVIEW

#3143 fix(rbf): disable rbf as default
  packages/suite/src/components/suite/modals/TransactionDetail/components/ChangeFee/index.tsx
  packages/suite/src/hooks/wallet/useSendForm.ts
Labels: READY TO REVIEW, Release

#3146 Fix ETH balance is used when trying to exchange some ERC20 tokens
  packages/suite/src/hooks/wallet/useCoinmarketExchangeForm.ts
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/ReceiveCryptoInput/ReceiveCryptoSelect/index.tsx
Labels: READY TO REVIEW, Release

#3144 chore: upgrade cypress to 5.0.0
  ci/packages/suite-web.yml
  docker/docker-compose.suite-ci.yml
  docker/test-runner/Dockerfile
  packages/integration-tests/package.json
  packages/integration-tests/projects/suite-web/constants/index.js
  packages/integration-tests/projects/suite-web/plugins/dropbox.js
  packages/integration-tests/projects/suite-web/plugins/google.js
  packages/integration-tests/projects/suite-web/plugins/index.js
  packages/integration-tests/projects/suite-web/run_tests.js
  packages/integration-tests/projects/suite-web/scripts/run-ci.sh
  packages/integration-tests/projects/suite-web/support/commands.ts
  packages/integration-tests/projects/suite-web/support/utils/assertions.ts
  packages/integration-tests/projects/suite-web/tests/backup/t2-fail.test.ts
  packages/integration-tests/projects/suite-web/tests/backup/t2-misc.test.ts
  packages/integration-tests/projects/suite-web/tests/backup/t2-success.test.ts
  packages/integration-tests/projects/suite-web/tests/browser/edge.test.ts
  packages/integration-tests/projects/suite-web/tests/browser/outdated-firefox.test.ts
  packages/integration-tests/projects/suite-web/tests/dashboard/dashboard.test.ts
  packages/integration-tests/projects/suite-web/tests/firmware/firmware.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/address-metadata.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/dropbox-api-errors.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/google-api-errors.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/interval-fetching.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/output-labeling.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/remembered-device.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/switching-providers.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/wallet-metadata.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/firmware-update.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/hologram.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/steps-order.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t1-create-wallet.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t1-recovery-advanced.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t1-recovery-basic.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t2-create-wallet.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t2-recovery-fail.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t2-recovery-persistence.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t2-recovery-success.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/transport.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/unexpected-states.test.ts
  packages/integration-tests/projects/suite-web/tests/recovery/t1-dry-run.test.ts
  packages/integration-tests/projects/suite-web/tests/recovery/t2-dry-run-persistence.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/general.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/log.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/t1-device-settings.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/t2-device-settings.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/analytics.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/button-requests.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/connecting-devices.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/initial-run.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/passhprase-duplicate.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/passhprase-numbering.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/passphrase-disabled.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/passphrase.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/remembering-devices.test.ts
  packages/integration-tests/projects/suite-web/tests/wallet/discovery.test.ts
  packages/integration-tests/projects/suite-web/tsconfig.json
  packages/suite/src/utils/suite/metadata.ts
  yarn.lock
Labels: READY TO REVIEW

#3156 Fix exchanges layout
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/Buttons/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
Labels: READY TO REVIEW

#3119 fix(invity): electron receiver address
  packages/suite/src/constants/wallet/coinmarket/buy.ts
  packages/suite/src/hooks/wallet/useCoinmarketBuyOffers.ts
  packages/suite/src/utils/suite/env.ts
  packages/suite/src/utils/wallet/coinmarket/__tests__/buyUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/buyUtils.ts
  packages/suite/src/views/wallet/coinmarket/buy/detail/components/WaitingForPayment/index.tsx
Labels: READY TO REVIEW

#3163 fix: update intl mesages
  packages/suite-data/files/translations/en.json
Labels: READY TO REVIEW

#3055 fix(invity): backup warning
  packages/suite/src/middlewares/wallet/discoveryMiddleware.ts
Labels: READY TO REVIEW

#3176 fix(suite): hide empty account group in accounts menu
  packages/suite/src/components/wallet/AccountsMenu/components/AccountGroup/index.tsx
  packages/suite/src/components/wallet/AccountsMenu/index.tsx
Labels: READY TO REVIEW

#3180 fix(invity): icon background
  packages/components/src/config/colors.ts
Labels: READY TO REVIEW

#3179 fix(suite): make scrollbar visible on every page under SuiteLayout
  packages/suite/src/components/suite/SuiteLayout/index.tsx
Labels: READY TO REVIEW
