Repository trezor/trezor-suite, pull requests merged in 2020-11, with the labels that each got.

#2819 chore: bch fork notif
  packages/suite/src/components/suite/NotificationCard/index.tsx
  packages/suite/src/components/wallet/AccountAnnouncement/BCHFork.tsx
  packages/suite/src/components/wallet/AccountAnnouncement/index.tsx
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW, Release

#2815 chore(fw-update): remove error workaround
  packages/suite/src/actions/firmware/__fixtures__/firmwareActions.ts
  packages/suite/src/actions/firmware/firmwareActions.ts
Labels: READY TO REVIEW

#2834 fix: fix column alignment in transaction item
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/TransactionItem/components/BaseTargetLayout/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/TransactionItem/index.tsx
Labels: READY TO REVIEW

#2850 Fix/2842
  packages/suite/src/views/settings/index.tsx
Labels: READY TO REVIEW, Release

#2851 Fix/2844
  packages/components/src/config/colors.ts
  packages/suite-desktop/src/support/DesktopTitlebar.tsx
Labels: READY TO REVIEW, Release

#2852 fix(tor): custom backed not clearing properly when tor is switched off
  packages/suite/src/actions/wallet/blockchainActions.ts
  packages/suite/src/middlewares/wallet/walletMiddleware.ts
Labels: READY TO REVIEW, Release

#2853 fix(suie): reload the app right after removing db
  packages/suite/src/support/suite/ErrorBoundary.tsx
Labels: Release

#2708 Refactor/translations
  packages/suite/src/components/suite/Labeling/components/Account/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/DeviceHeaderButton/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/WalletInstance/Container.tsx
  packages/suite/src/components/suite/Ticker/index.tsx
  packages/suite/src/components/suite/ToastNotification/index.tsx
  packages/suite/src/components/suite/WordInput/index.tsx
  packages/suite/src/components/suite/hocNotification/components/withTransaction.tsx
  packages/suite/src/components/suite/hocNotification/index.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/AccountTypeSelect.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/AddAccountButton.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/NetworkInternal.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/NetworkSelect.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/NetworkUnavailable.tsx
  packages/suite/src/components/suite/modals/AddAccount/index.tsx
  packages/suite/src/components/suite/modals/AdvancedCoinSettings/components/CustomBlockbookUrls.tsx
  packages/suite/src/components/wallet/AccountsMenu/components/AccountItem/index.tsx
  packages/suite/src/components/wallet/WalletLayout/components/AccountLoader.tsx
  packages/suite/src/components/wallet/WalletLayout/index.tsx
  packages/suite/src/hooks/suite/useTranslation.ts
  packages/suite/src/utils/suite/__fixtures__/device.ts
  packages/suite/src/utils/suite/device.ts
  packages/suite/src/utils/wallet/__fixtures__/accountUtils.ts
  packages/suite/src/utils/wallet/__tests__/accountUtils.test.ts
  packages/suite/src/utils/wallet/accountUtils.ts
  packages/suite/src/views/dashboard/components/SecurityFeatures/Container.ts
  packages/suite/src/views/onboarding/steps/Firmware/Container.ts
  packages/suite/src/views/onboarding/steps/Pair/components/Bridge/index.tsx
  packages/suite/src/views/settings/debug/Container.ts
  packages/suite/src/views/settings/device/Container.ts
  packages/suite/src/views/suite/device-recovery-mode/Container.ts
  packages/suite/src/views/suite/notifications/index.tsx
  packages/suite/src/views/wallet/details/index.tsx
  packages/suite/src/views/wallet/receive/Container.ts
  packages/suite/src/views/wallet/receive/components/FreshAddress/index.tsx
  packages/suite/src/views/wallet/sign-verify/Container.ts
  packages/suite/src/views/wallet/transactions/Container.ts
  packages/suite/src/views/wallet/transactions/components/TransactionSummary/components/SummaryCards/index.tsx
Labels: READY TO REVIEW

#2684 refactor(suite): remove unnecessary async from actions
  packages/suite-native/src/actions/suite/routerActions.ts
  packages/suite/src/actions/backup/backupActions.ts
  packages/suite/src/actions/firmware/firmwareActions.ts
  packages/suite/src/actions/onboarding/onboardingActions.ts
  packages/suite/src/actions/recovery/recoveryActions.ts
  packages/suite/src/actions/settings/walletSettingsActions.ts
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/actions/suite/desktopUpdateActions.ts
  packages/suite/src/actions/suite/logActions.ts
  packages/suite/src/actions/suite/metadataActions.ts
  packages/suite/src/actions/suite/modalActions.ts
  packages/suite/src/actions/suite/notificationActions.ts
  packages/suite/src/actions/suite/resizeActions.ts
  packages/suite/src/actions/suite/routerActions.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/actions/wallet/accountActions.ts
  packages/suite/src/actions/wallet/accountSearchActions.ts
  packages/suite/src/actions/wallet/blockchainActions.ts
  packages/suite/src/actions/wallet/coinmarketBuyActions.ts
  packages/suite/src/actions/wallet/coinmarketCommonActions.ts
  packages/suite/src/actions/wallet/coinmarketExchangeActions.ts
  packages/suite/src/actions/wallet/discoveryActions.ts
  packages/suite/src/actions/wallet/fiatRatesActions.ts
  packages/suite/src/actions/wallet/graphActions.ts
  packages/suite/src/actions/wallet/receiveActions.ts
  packages/suite/src/actions/wallet/selectedAccountActions.ts
  packages/suite/src/actions/wallet/sendFormActions.ts
  packages/suite/src/actions/wallet/signVerifyActions.ts
  packages/suite/src/actions/wallet/transactionActions.ts
  packages/suite/src/types/firmware/index.ts
  packages/suite/src/types/onboarding/index.ts
  packages/suite/src/types/settings/index.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/types/wallet/coinmarketBuyForm.ts
  packages/suite/src/types/wallet/index.ts
Labels: READY TO REVIEW

#2860 fix(suite): pass className to tooltip wrapper, unify tooltip styling
  packages/components/src/components/Tooltip/index.tsx
  packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx
Labels: READY TO REVIEW

#2863 fix(suite-desktop): use binary dir as current dir + library dir
  packages/suite-desktop/src-electron/processes/BaseProcess.ts
  packages/suite-desktop/src-electron/processes/TorProcess.ts
Labels: Release

#2870 fix(suite): fetch account info after blockchain connection
  packages/suite/src/actions/wallet/__fixtures__/blockchainActions.ts
  packages/suite/src/actions/wallet/blockchainActions.ts
Labels: READY TO REVIEW, Release

#2816 chore(analytics): refactor, less spaghetti
  packages/suite/src/actions/suite/__tests__/analyticsActions.test.ts
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/actions/suite/constants/analyticsConstants.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/components/suite/Settings/components/Analytics.tsx
  packages/suite/src/hooks/suite/useAnalytics.ts
  packages/suite/src/middlewares/suite/analyticsMiddleware.ts
  packages/suite/src/middlewares/suite/suiteMiddleware.ts
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/reducers/suite/analyticsReducer.ts
Labels: READY TO REVIEW

#2885 fix(desktop): macOS close button behaviour
  packages/suite-desktop/src-electron/electron.ts
Labels: READY TO REVIEW, Release

#2883 feat(suite): add blog post URL to Bitcoin Cash hard fork
  packages/suite/src/components/wallet/AccountAnnouncement/BCHFork.tsx
  packages/suite/src/constants/suite/urls.ts
Labels: Release

#2891 fix(suite-desktop): close devtools before closing the window
  packages/suite-desktop/src-electron/electron.ts
Labels: READY TO REVIEW

#2890 fix(suite-desktop): set absolute path for dev resources
  packages/suite-desktop/src-electron/constants.ts
Labels: READY TO REVIEW

#2900 fix(static notification): update should not appear if missing backup
  packages/integration-tests/projects/suite-web/tests/firmware/firmware.test.ts
  packages/suite/src/components/suite/Notifications/UpdateFirmware.tsx
Labels: READY TO REVIEW

#2912 fix(onboarding): button containing link should not be underlined
  packages/suite/src/views/onboarding/unexpected-states/components/IsNotNewDevice.tsx
Labels: READY TO REVIEW

#2908 fix(analytics): don't report until user was given chance to opt-out
  packages/suite/src/actions/suite/__tests__/analyticsActions.test.ts
  packages/suite/src/actions/suite/analyticsActions.ts
Labels: READY TO REVIEW, Release

#2901 Onion link inconsistencies and warning for all links on suite-desktop when using Tor
  packages/suite-desktop/src-electron/electron.ts
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/actions/suite/constants/suiteConstants.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/components/suite/BetaBadge/index.tsx
  packages/suite/src/components/suite/ExternalLink/index.tsx
  packages/suite/src/components/suite/ReadMoreLink/index.tsx
  packages/suite/src/components/suite/TrezorLink/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/BasicDetails/index.tsx
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/index.tsx
Labels: READY TO REVIEW, Release

#2914 test(e2e): unskip and finish some tests
  packages/integration-tests/projects/suite-web/tests/dashboard/dashboard.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/t1-device-settings.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/t2-device-settings.test.ts
Labels: READY TO REVIEW

#2920 fix(components): dropdown proper positioning
  packages/components/src/components/Dropdown/index.tsx
Labels: READY TO REVIEW

#2910 Fix hanging bridge spinner and display recommendation on bridge updating for desktop users
  packages/suite/src/support/messages.ts
  packages/suite/src/views/suite/bridge/index.tsx
Labels: READY TO REVIEW, Release

#2915 fix(copy): mistype on fw update screen and missing translation added
  packages/suite/src/components/firmware/ReconnectInNormal.tsx
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#2893 chore(ci): optimize
  .gitlab-ci.yml
  ci/packages/components.yml
  ci/packages/landing-page.yml
  ci/packages/suite-desktop.yml
  ci/packages/suite-web-landing.yml
  ci/packages/suite-web.yml
  ci/packages/suite.yml
  ci/schedules.yml
Labels: READY TO REVIEW

#2929 chore(update): various minor dev patch deps
  packages/blockchain-link/package.json
  packages/components/package.json
  packages/integration-tests/package.json
  packages/landing-page/package.json
  packages/suite-data/package.json
  packages/suite-desktop/package.json
  packages/suite-web-landing/package.json
  packages/suite-web/package.json
  packages/suite/package.json
  packages/translations-manager/package.json
  yarn.lock
Labels: READY TO REVIEW

#2931 chore: trezor-connect 8.1.18
  packages/suite-data/files/connect/iframe.html
  packages/suite-data/files/connect/js/iframe.8771e344f4978ab26faa.js
  packages/suite/package.json
  yarn.lock
Labels: READY TO REVIEW, Release

#2928 fix(suite-desktop): remove link warning for links when not using Tor
  packages/suite-desktop/src-electron/config.ts
  packages/suite-desktop/src-electron/electron.ts
Labels: READY TO REVIEW, Release

#2932 feat(analytics): is tor enabled on suite start?
  docs/misc/analytics.md
  packages/suite/src/actions/suite/__tests__/analyticsActions.test.ts
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/middlewares/suite/analyticsMiddleware.ts
  packages/suite/src/utils/suite/__fixtures__/analytics.ts
Labels: READY TO REVIEW

#2940 chore: update styled components, minor version
  packages/components/package.json
  packages/suite-desktop/package.json
  packages/suite-web/package.json
  packages/suite/package.json
  yarn.lock
Labels: READY TO REVIEW

#2930 Hidden wallet number
  CHANGELOG.md
  packages/integration-tests/projects/suite-web/tests/backup/t2-misc.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/dropbox-remembered-device.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/dropbox-wallet-metadata.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/passhprase-duplicate.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/passhprase-numbering.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/passphrase-disabled.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/passphrase.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/remembering-devices.test.ts
  packages/suite/src/actions/suite/__fixtures__/suiteActions.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/components/suite/Labeling/components/Wallet/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/AddWalletButton/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/WalletInstance/Container.tsx
  packages/suite/src/components/suite/SwitchDevice/components/WalletInstance/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
  packages/suite/src/components/suite/modals/PassphraseDuplicate/index.tsx
  packages/suite/src/reducers/suite/deviceReducer.ts
  packages/suite/src/storage/CHANGELOG.md
  packages/suite/src/storage/index.ts
  packages/suite/src/storage/migrations/index.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/utils/suite/__fixtures__/device.ts
  packages/suite/src/utils/suite/__tests__/device.test.ts
  packages/suite/src/utils/suite/device.ts
Labels: READY TO REVIEW

#2943 fix(suite-desktop): save window dimension on window close
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src-electron/store.ts
Labels: READY TO REVIEW

#2955 Fix account name in buy Info
  packages/suite/src/components/wallet/CoinmarketBuyOfferInfo/index.tsx
Labels: READY TO REVIEW

#2913 feat(analytics): add more events
  docs/misc/analytics.md
  packages/integration-tests/projects/suite-web/tests/suite/analytics.test.ts
  packages/suite-native/src/utils/suite/env.ts
  packages/suite/src/actions/suite/__tests__/analyticsActions.test.ts
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/middlewares/suite/__tests__/suiteMiddleware.test.ts
  packages/suite/src/middlewares/suite/analyticsMiddleware.ts
  packages/suite/src/reducers/suite/analyticsReducer.ts
  packages/suite/src/utils/suite/env.ts
Labels: READY TO REVIEW

#2957 fix: don't focus on element created for copying text to clipboard (pr…
  packages/suite/src/utils/suite/dom.ts
Labels: READY TO REVIEW

#2963 Suite Desktop: return valid HTML and content-type header in HttpReceiver
  packages/suite-desktop/src-electron/http-receiver.ts
Labels: READY TO REVIEW

#2881 chore(eslint): add require-await rule
  .eslintrc.js
  packages/blockchain-link/src/index.ts
  packages/blockchain-link/src/workers/blockbook/index.ts
  packages/blockchain-link/src/workers/ripple/index.ts
  packages/blockchain-link/tests/unit/errors.ts
  packages/blockchain-link/tests/unit/workers.ts
  packages/news-api/src/index.ts
  packages/suite-desktop/src-electron/metadata.ts
  packages/suite-desktop/src-electron/processes/BaseProcess.ts
  packages/suite-native/src/services/suite/metadata/DropboxProvider.ts
  packages/suite-native/src/services/suite/metadata/FileSystemProvider.ts
  packages/suite-native/src/services/suite/metadata/GoogleProvider.ts
  packages/suite-storage/src/native/index.ts
  packages/suite-storage/src/web/index.ts
  packages/suite/src/actions/backup/__tests__/backupActions.test.ts
  packages/suite/src/actions/firmware/__tests__/firmwareActions.test.ts
  packages/suite/src/actions/suite/__tests__/metadataActions.test.ts
  packages/suite/src/actions/suite/__tests__/routerActions.test.ts
  packages/suite/src/actions/suite/__tests__/suiteActions.test.ts
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/actions/suite/desktopUpdateActions.ts
  packages/suite/src/actions/suite/metadataActions.ts
  packages/suite/src/actions/suite/modalActions.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/actions/wallet/__tests__/accountActions.test.ts
  packages/suite/src/actions/wallet/__tests__/coinmarketBuyActions.test.ts
  packages/suite/src/actions/wallet/__tests__/coinmarketExchangeActions.test.ts
  packages/suite/src/actions/wallet/__tests__/discoveryActions.test.ts
  packages/suite/src/actions/wallet/__tests__/selectedAccountActions.test.ts
  packages/suite/src/actions/wallet/__tests__/transactionActions.test.ts
  packages/suite/src/actions/wallet/blockchainActions.ts
  packages/suite/src/actions/wallet/coinmarket/__tests__/coinmarketCommonActions.test.ts
  packages/suite/src/actions/wallet/coinmarket/__tests__/coinmarketTransactionBitcoinActions.test.ts
  packages/suite/src/actions/wallet/coinmarket/__tests__/coinmarketTransactionEthereumActions.test.ts
  packages/suite/src/actions/wallet/coinmarket/__tests__/coinmarketTransactionRippleActions.test.ts
  packages/suite/src/actions/wallet/coinmarket/coinmarketCommonActions.ts
  packages/suite/src/actions/wallet/coinmarket/coinmarketTransactionBitcoinActions.ts
  packages/suite/src/actions/wallet/coinmarket/coinmarketTransactionRippleActions.ts
  packages/suite/src/actions/wallet/fiatRatesActions.ts
  packages/suite/src/actions/wallet/sendFormActions.ts
  packages/suite/src/components/suite/DropZone/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/index.tsx
  packages/suite/src/components/suite/modals/ReviewTransaction/index.tsx
  packages/suite/src/hooks/wallet/useSendFormCompose.ts
  packages/suite/src/hooks/wallet/useSendFormOutputs.ts
  packages/suite/src/middlewares/suite/actionBlockerMiddleware.ts
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/services/coingecko.ts
  packages/suite/src/services/suite/metadata/FileSystemProvider.ts
  packages/suite/src/storage/migrations/index.ts
  packages/suite/src/support/tests/setupJest.ts
  packages/suite/src/utils/suite/__tests__/homescreen.test.ts
  packages/suite/src/utils/suite/__tests__/metadata.test.ts
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Fees/components/CustomFee/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/ReceiveCryptoInput/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/TokenSelect/index.tsx
Labels: READY TO REVIEW

#2972 Cache country select in Buy
  packages/suite/src/views/wallet/coinmarket/buy/components/BuyForm/Footer/index.tsx
Labels: READY TO REVIEW

#2975 Add invity.io to allowed domains in destop version
  packages/suite-desktop/src-electron/config.ts
Labels: READY TO REVIEW

#2978 feat(analytics): add more events
  docs/misc/analytics.md
  packages/integration-tests/projects/suite-web/tests/suite/analytics.test.ts
  packages/suite/src/actions/recovery/recoveryActions.ts
  packages/suite/src/actions/suite/__tests__/analyticsActions.test.ts
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/middlewares/suite/analyticsMiddleware.ts
  packages/suite/src/utils/suite/__fixtures__/analytics.ts
Labels: READY TO REVIEW

#2980 chore: update react-markdown package
  packages/suite/package.json
  yarn.lock
Labels: READY TO REVIEW

#2986 chore: fix some typos
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#2985 fix(invity): disable proceed with exchange below-minimum offers
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/List/Quote/index.tsx
Labels: READY TO REVIEW

#2990 fix(invity): validate zero amounts
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/FiatInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/ReceiveCryptoInput/index.tsx
Labels: READY TO REVIEW

#2989 fix(invity): coin selector search by name
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoSelect/index.tsx
Labels: READY TO REVIEW

#2991 fix(invity): required empty input in buy
  packages/suite/src/views/wallet/coinmarket/buy/components/BuyForm/Inputs/index.tsx
Labels: READY TO REVIEW

#2995 Fix coinmarket messages
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/FiatInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoSelect/index.tsx
  packages/suite/src/views/wallet/coinmarket/redirect/index.tsx
Labels: READY TO REVIEW

#2996 fix(suite): add missing await to isDBAvailable()
  packages/suite-storage/src/native/index.ts
  packages/suite/src/actions/suite/storageActions.ts
Labels: READY TO REVIEW

#3001 fix(suite): add white border around qr code
  packages/suite/src/components/suite/QrCode/index.tsx
Labels: READY TO REVIEW

#3000 chore(suite-desktop): update electron to 11
  packages/suite-desktop/package.json
  yarn.lock
Labels: READY TO REVIEW

#3007 chore: download new messages
  packages/suite-data/files/translations/en.json
Labels: READY TO REVIEW

#3006 style(components): lighter color for scrollbar thumb
  packages/components/src/config/colors.ts
Labels: READY TO REVIEW

#3010 fix(dark-mode): bg color for secondary btn and tooltips
  packages/components/src/components/Dropdown/index.tsx
  packages/components/src/components/buttons/Button/index.tsx
  packages/components/src/components/form/CleanSelect/index.tsx
  packages/components/src/components/form/Select/index.tsx
  packages/components/src/config/colors.ts
  packages/suite/src/components/suite/Settings/components/Row.tsx
  packages/suite/src/components/suite/TransactionsGraph/components/CustomTooltipBase/index.tsx
  packages/suite/src/components/suite/TransactionsGraph/index.tsx
Labels: READY TO REVIEW

#3011 fix(invity): allow only 2 decimals in fiat input
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/FiatInput/index.tsx
Labels: READY TO REVIEW

#2889 fix(suite): discreet mode cut off in accounts
  packages/suite/src/components/wallet/AccountsMenu/components/AccountItem/index.tsx
Labels: READY TO REVIEW

#3025 fix(invity):buy offers in dark mode
  packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/List/Quote/index.tsx
Labels: READY TO REVIEW

#3028 fix(invity) ethereum fee limit
  packages/suite/src/actions/wallet/coinmarket/coinmarketTransactionEthereumActions.ts
  packages/suite/src/hooks/wallet/useCoinmarketExchangeForm.ts
  packages/suite/src/types/wallet/coinmarketExchangeForm.ts
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Fees/components/CustomFee/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Fees/index.tsx
Labels: READY TO REVIEW

#3009 fix(suite-desktop): move request headers to work with dev builds (required by new Bridge)
  packages/suite-desktop/src-electron/electron.ts
Labels: READY TO REVIEW

#3030 fix(invity) disable options while submit progress
  packages/components/src/components/form/SelectBar/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Fees/index.tsx
Labels: READY TO REVIEW

#3029 fix(dark-mode): incorrectly declared color instead of background
  packages/suite/src/components/suite/SwitchDevice/components/WalletInstance/index.tsx
  packages/suite/src/components/wallet/AccountException/FirmwareUnsupported.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/BuyTransaction/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/ExchangeTransaction/index.tsx
  packages/suite/src/components/wallet/DiscoveryProgress/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/SelectedOffer/components/VerifyAddress/index.tsx
  packages/suite/src/views/wallet/sign-verify/index.tsx
Labels: READY TO REVIEW

#2971 feat(suite): graphs shadow opacity adjusted
  packages/suite/src/components/suite/TransactionsGraph/index.tsx
Labels: READY TO REVIEW

#3032 fix(invity) update titles
  packages/suite/src/views/wallet/coinmarket/buy/detail/Detail/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/detail/Detail/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/index.tsx
Labels: READY TO REVIEW

#3034 fix(invity): max input limits
  packages/suite/src/views/wallet/coinmarket/buy/components/BuyForm/Inputs/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/FiatInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/ReceiveCryptoInput/index.tsx
Labels: READY TO REVIEW

#3027 feat(metadata): detect popup close
  packages/suite/src/utils/suite/oauth.ts
Labels: READY TO REVIEW

#2952 chore: rework static notifications panel
  packages/integration-tests/projects/suite-web/tests/firmware/firmware.test.ts
  packages/suite/src/components/suite/Banners/FailedBackup.tsx
  packages/suite/src/components/suite/Banners/NoBackup.tsx
  packages/suite/src/components/suite/Banners/OnlineStatus.tsx
  packages/suite/src/components/suite/Banners/UpdateBridge.tsx
  packages/suite/src/components/suite/Banners/UpdateFirmware.tsx
  packages/suite/src/components/suite/Banners/components/Wrapper.tsx
  packages/suite/src/components/suite/Banners/index.tsx
  packages/suite/src/components/suite/Notifications/UpdateBridge.tsx
  packages/suite/src/components/suite/Notifications/UpdateFirmware.tsx
  packages/suite/src/components/suite/Notifications/index.tsx
  packages/suite/src/components/suite/SuiteLayout/index.tsx
Labels: READY TO REVIEW

#3042 fix(invity): Exchange Receiving address ExtraField requires interaction
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/SelectedOffer/components/VerifyAddress/index.tsx
Labels: READY TO REVIEW

#3053 feat(suite-desktop): bundler for electron source
  packages/suite-desktop/.eslintignore
  packages/suite-desktop/package.json
  packages/suite-desktop/scripts/build.js
  packages/suite-desktop/scripts/dev.js
  packages/suite-desktop/src-electron/config.ts
  packages/suite-desktop/src-electron/electron.ts
  packages/suite-desktop/src-electron/tsconfig.json
  packages/suite-desktop/webpack.config.js
  packages/suite/src/constants/suite/urls.ts
  yarn.lock
Labels: READY TO REVIEW

#2974 Feat/transaction export
  packages/components/src/components/Dropdown/index.tsx
  packages/suite/package.json
  packages/suite/src/config/suite/features.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/suite/array.ts
  packages/suite/src/utils/suite/export.ts
  packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx
  packages/suite/src/workers/export.worker.ts
  yarn.lock
Labels: READY TO REVIEW

#3064 chore: yarn.lock
  yarn.lock
Labels: READY TO REVIEW

#3058 fix(suite-desktop): ignore error display while auto-updater is checking
  packages/suite/src/actions/suite/desktopUpdateActions.ts
Labels: READY TO REVIEW

#3060 refactor(suite): transactionUtils
  packages/suite/src/actions/wallet/coinmarket/coinmarketTransactionEthereumActions.ts
  packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts
  packages/suite/src/components/suite/hocNotification/components/withTransaction.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/index.tsx
  packages/suite/src/reducers/wallet/transactionReducer.ts
  packages/suite/src/utils/wallet/__fixtures__/accountUtils.ts
  packages/suite/src/utils/wallet/__fixtures__/transactionUtils.ts
  packages/suite/src/utils/wallet/__tests__/accountUtils.test.ts
  packages/suite/src/utils/wallet/__tests__/transactionUtils.test.ts
  packages/suite/src/utils/wallet/accountUtils.ts
  packages/suite/src/utils/wallet/transactionUtils.ts
  packages/suite/src/views/wallet/receive/index.tsx
Labels: READY TO REVIEW

#3059 Exchange improvements
  packages/suite/src/components/wallet/CoinmarketExchangeOfferInfo/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Fees/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/Buttons/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/FiatInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/ReceiveCryptoInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/SelectedOffer/components/VerifyAddress/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/SelectedOffer/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/index.tsx
Labels: READY TO REVIEW

#3056 fix(suite-desktop): force app to close on Mac on update install
  packages/suite-desktop/src-electron/electron.ts
Labels: READY TO REVIEW

#3080 fix(dark-mode): dont reset theme on db error
  packages/suite/src/support/suite/ThemeProvider.tsx
Labels: READY TO REVIEW

#3081 feat(suite-web-landing): add links to signatures
  packages/landing-page/pages/wallet/start/index.tsx
  packages/suite-web-landing/components/Download/index.tsx
  packages/suite/src/constants/suite/urls.ts
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#3087 fix(suite-desktop): rename build:lib command to build:electron to prevent postinstall from failing
  packages/suite-desktop/package.json
Labels: READY TO REVIEW

#3089 Suite-Desktop: Fit text in bridge modal
  packages/suite/src/views/suite/bridge/index.tsx
Labels: READY TO REVIEW, Release
