Repository trezor/trezor-suite, pull requests merged in 2020-02, with the labels that each got.

#1119 Welcome modal
  packages/integration-tests/projects/suite-web/support/commands.ts
  packages/integration-tests/projects/suite-web/support/utils/shortcuts.ts
  packages/integration-tests/projects/suite-web/tests/settings/device.test.ts
  packages/suite-data/files/images/welcome/analytics.svg
  packages/suite-data/files/images/welcome/welcome.svg
  packages/suite/src/components/onboarding/UnexpectedState/components/IsSameDevice.tsx
  packages/suite/src/components/suite/Preloader/index.tsx
  packages/suite/src/components/suite/Settings/components/Analytics.tsx
  packages/suite/src/components/suite/Settings/components/Section.tsx
  packages/suite/src/components/suite/Settings/index.ts
  packages/suite/src/constants/suite/routes.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/onboarding/steps/Skip/index.tsx
  packages/suite/src/views/settings/index.tsx
  packages/suite/src/views/suite/analytics/index.tsx
  packages/suite/src/views/suite/index.tsx
  packages/suite/src/views/suite/welcome/index.tsx
Labels: in progress

#1136 connect device modal
  packages/suite-data/files/images/suite/connect-device.svg
  packages/suite/src/views/onboarding/steps/Pair/index.tsx
  packages/suite/src/views/suite/device-connect/index.tsx
Labels: Product!

#1130 Firmware in modal
  packages/suite-data/files/images/firmware/firmware-init.svg
  packages/suite-data/files/images/firmware/firmware-success.svg
  packages/suite-data/files/images/suite/t-device-confirm.svg
  packages/suite-data/files/images/suite/uni-error.svg
  packages/suite-data/files/images/suite/uni-success.svg
  packages/suite-data/files/images/suite/uni-warning.svg
  packages/suite/src/actions/firmware/constants/firmware.ts
  packages/suite/src/actions/firmware/firmwareActions.ts
  packages/suite/src/components/firmware/index.tsx
  packages/suite/src/components/onboarding/index.ts
  packages/suite/src/components/suite/ProgressBar/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/constants/suite/urls.ts
  packages/suite/src/reducers/firmware/firmwareReducer.ts
  packages/suite/src/views/firmware/index.tsx
  packages/suite/src/views/onboarding/index.tsx
  packages/suite/src/views/onboarding/steps/Firmware/index.tsx
Labels: ready to review

#1071 Feature/txs list new design
  packages/components-v2/src/components/Icon/icons.ts
  packages/components-v2/src/components/Link/index.tsx
  packages/components-v2/src/config/variables.ts
  packages/components-v2/src/images/icons/external_link.svg
  packages/suite/.stylelintrc
  packages/suite/package.json
  packages/suite/src/actions/suite/modalActions.ts
  packages/suite/src/components/suite/FiatValue/Container.ts
  packages/suite/src/components/suite/FiatValue/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/WalletInstance/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/BasicDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/Box/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/BoxRow/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/FiatDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/IODetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/components/wallet/Menu/components/AccountItem/index.tsx
  packages/suite/src/reducers/wallet/transactionReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/wallet/__tests__/accountUtils.test.ts
  packages/suite/src/utils/wallet/accountUtils.ts
  packages/suite/src/utils/wallet/transactionUtils.ts
  packages/suite/src/views/dashboard/index.tsx
  packages/suite/src/views/wallet/receive/components/ReceiveForm/index.tsx
  packages/suite/src/views/wallet/transactions/components/NoTransactions/index.tsx
  packages/suite/src/views/wallet/transactions/components/Pagination/index.tsx
  packages/suite/src/views/wallet/transactions/components/PricePanel/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionItem/Container.ts
  packages/suite/src/views/wallet/transactions/components/TransactionItem/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionTypeIcon/index.tsx
  packages/suite/src/views/wallet/transactions/index.tsx
  yarn.lock
Labels: ready to review

#1148 quick fix for switch alignment in switch device modal
  packages/suite/src/components/suite/SwitchDevice/components/WalletInstance/index.tsx
Labels: ready to review

#1149 fake dashboard
  packages/suite-data/files/images/dashboard/fake1.png
  packages/suite-data/files/images/dashboard/fake2.png
  packages/suite/src/components/suite/NewsFeed/index.tsx
  packages/suite/src/views/dashboard/index.tsx
Labels: ready to review

#1141 Fix/pin-passphrase-loading design
  packages/components-v2/src/components/Checkbox/index.tsx
  packages/components-v2/src/components/Icon/icons.ts
  packages/components-v2/src/components/Modal/index.tsx
  packages/components-v2/src/components/inputs/Input/index.tsx
  packages/components-v2/src/config/variables.ts
  packages/components-v2/src/images/icons/back.svg
  packages/components-v2/src/images/icons/hide.svg
  packages/components-v2/src/images/icons/show.svg
  packages/components-v2/src/support/types/index.ts
  packages/integration-tests/projects/components-storybook-v2/snapshots/Form.test.js/Form -- checkbox-checked.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Form.test.js/Form -- checkbox.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Icons.test.js/Icons -- icon-back.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Icons.test.js/Icons -- icon-show.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Icons.test.js/Icons -- icon-t1.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Icons.test.js/Icons -- icon-t2.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Modal.test.js/Modal -- modal-with-cancel.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Modal.test.js/Modal -- modal.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Notifications.test.js/Notifications -- notification-cta-info.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Notifications.test.js/Notifications -- notification-cta-success.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Notifications.test.js/Notifications -- notification-desc-cta-info.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Notifications.test.js/Notifications -- notification-desc-cta-success.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Notifications.test.js/Notifications -- notification-desc-loading-info.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Notifications.test.js/Notifications -- notification-desc-loading-success.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Notifications.test.js/Notifications -- notification-desc-second-cta-info.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Notifications.test.js/Notifications -- notification-desc-second-cta-success.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Notifications.test.js/Notifications -- notification-loading-info.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Notifications.test.js/Notifications -- notification-loading-success.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Notifications.test.js/Notifications -- notification-second-cta-info.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Notifications.test.js/Notifications -- notification-second-cta-success.snap.png
  packages/integration-tests/projects/components-storybook-v2/tests/Icons.test.js
  packages/suite-data/files/images/suite/one-device-confirm.svg
  packages/suite-data/files/images/suite/spinner.svg
  packages/suite-data/files/images/suite/t-device-confirm.svg
  packages/suite/src/components/suite/DiscoveryLoader/index.tsx
  packages/suite/src/components/suite/Loading/index.tsx
  packages/suite/src/components/suite/ModalWrapper/index.tsx
  packages/suite/src/components/suite/PinInput/components/ButtonPin/index.tsx
  packages/suite/src/components/suite/PinInput/components/InputPin/index.tsx
  packages/suite/src/components/suite/PinInput/index.tsx
  packages/suite/src/components/suite/PortfolioCard/components/EmptyWallet/index.tsx
  packages/suite/src/components/suite/Preloader/index.tsx
  packages/suite/src/components/suite/SwitchDevice/index.tsx
  packages/suite/src/components/suite/images/DeviceConfirmImage/index.tsx
  packages/suite/src/components/suite/modals/AddAccount/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/index.tsx
  packages/suite/src/components/suite/modals/PassphraseOnDevice/index.tsx
  packages/suite/src/components/suite/modals/PassphraseSource/index.tsx
  packages/suite/src/components/suite/modals/Pin/index.tsx
  packages/suite/src/components/suite/modals/PinInvalid/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/index.tsx
  packages/suite/src/components/suite/modals/confirm/Action/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/wallet/index.tsx
Labels: ready to review

#1137 backup in modal
  packages/integration-tests/projects/suite-web/plugins/index.js
  packages/integration-tests/projects/suite-web/plugins/python/emulator.py
  packages/integration-tests/projects/suite-web/plugins/python/main.py
  packages/integration-tests/projects/suite-web/tests/onboarding/create-new-wallet.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/device.test.ts
  packages/suite-native/babel.config.js
  packages/suite-native/tsconfig.json
  packages/suite/jest.config.js
  packages/suite/src/actions/backup/backupActions.ts
  packages/suite/src/actions/backup/constants/backup.ts
  packages/suite/src/actions/backup/constants/index.ts
  packages/suite/src/actions/settings/__tests__/backupActions.test.ts
  packages/suite/src/actions/settings/backupActions.ts
  packages/suite/src/actions/settings/constants/deviceSettings.ts
  packages/suite/src/components/backup/AfterBackupCheckboxes.tsx
  packages/suite/src/components/backup/CheckItem.tsx
  packages/suite/src/components/backup/PreBackupCheckboxes.tsx
  packages/suite/src/components/backup/index.ts
  packages/suite/src/components/onboarding/Wrapper/CheckboxWrapper.tsx
  packages/suite/src/components/onboarding/index.ts
  packages/suite/src/components/suite/Notifications/NoBackup.tsx
  packages/suite/src/components/suite/Notifications/index.tsx
  packages/suite/src/components/suite/Preloader/index.tsx
  packages/suite/src/components/suite/ProgressBar/index.tsx
  packages/suite/src/components/suite/SecurityFeatures/Container.ts
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/constants/suite/routes.ts
  packages/suite/src/middlewares/backup/backupMiddleware.ts
  packages/suite/src/middlewares/backup/index.ts
  packages/suite/src/reducers/backup/backupReducer.ts
  packages/suite/src/reducers/backup/index.ts
  packages/suite/src/reducers/store.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/utils/backup/index.ts
  packages/suite/src/views/backup/index.tsx
  packages/suite/src/views/firmware/index.tsx
  packages/suite/src/views/onboarding/index.tsx
  packages/suite/src/views/onboarding/steps/Backup/Container.ts
  packages/suite/src/views/onboarding/steps/Backup/index.tsx
  packages/suite/src/views/onboarding/steps/Security/index.tsx
  packages/suite/src/views/settings/device/Container.ts
  packages/suite/src/views/settings/device/index.tsx
  tsconfig.json
Labels: ready to review

#1129 custom homescreen upload
  packages/suite/src/utils/suite/homescreen.ts
  packages/suite/src/views/settings/device/index.tsx
Labels: Product!

#1161 visual fixes
  packages/suite/src/components/suite/MenuSecondary/index.tsx
  packages/suite/src/components/suite/ModalWrapper/index.tsx
  packages/suite/src/components/wallet/Menu/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/onboarding/steps/CreateOrRecover/Container.ts
  packages/suite/src/views/onboarding/steps/CreateOrRecover/index.tsx
  packages/suite/src/views/suite/analytics/index.tsx
  packages/suite/src/views/suite/welcome/index.tsx
Labels: ready to review

#1163 nicer accounts menu
  packages/suite/src/components/wallet/Menu/components/AccountItem/index.tsx
Labels: ready to review

#1164 progress bar
  packages/suite/src/components/suite/ProgressBar/index.tsx
  packages/suite/src/views/onboarding/index.tsx
Labels: ready to review

#1168 Fix render of fee value in select
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/Fee/index.tsx
Labels: ready to review

#1167 add account design
  packages/suite/src/components/suite/modals/AddAccount/components/AccountSelect.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/AccountTypeSelect.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/AddAccountButton.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/ExternalWallet/index.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/NetworkSelect.tsx
  packages/suite/src/components/suite/modals/AddAccount/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/wallet/accountUtils.ts
Labels: ready to review

#1169 fabulous fake data for weekly graph in dashboard
  packages/suite/src/components/dashboard/AssetsCard/components/Asset/index.tsx
  packages/suite/src/components/dashboard/AssetsCard/components/LastWeekGraph/index.tsx
Labels: ready to review

#1170 Fix/dashboard fiat value
  packages/suite/src/components/dashboard/AssetsCard/components/Asset/index.tsx
  packages/suite/src/utils/wallet/accountUtils.ts
Labels: ready to review

#1166 tips menu item should not be highlighted in wallet
  packages/suite/src/constants/suite/routes.ts
Labels: ready to review

#1172 max width for App notifications + SuiteLayout with menu
  packages/suite/src/components/suite/Notifications/components/Wrapper.tsx
  packages/suite/src/components/suite/SuiteLayout/index.tsx
Labels: ready to review

#1171 remove last device instance if device not connected
  packages/suite/src/reducers/suite/__fixtures__/deviceReducer.ts
  packages/suite/src/reducers/suite/deviceReducer.ts
Labels: ready to review

#1160 Style dry run
  packages/suite-data/files/images/recovery/12-words.svg
  packages/suite-data/files/images/recovery/18-words.svg
  packages/suite-data/files/images/recovery/24-words.svg
  packages/suite-desktop/pages/recovery/index.tsx
  packages/suite-native/babel.config.js
  packages/suite-native/src/reducers/store.ts
  packages/suite-native/tsconfig.json
  packages/suite-web/pages/recovery/index.tsx
  packages/suite-web/pages/seed-input/index.tsx
  packages/suite/jest.config.js
  packages/suite/src/actions/backup/__tests__/backupActions.test.ts
  packages/suite/src/actions/onboarding/__tests__/onboardingActions.test.ts
  packages/suite/src/actions/recovery/__tests__/recoveryActions.test.ts
  packages/suite/src/actions/recovery/constants/index.ts
  packages/suite/src/actions/recovery/constants/recovery.ts
  packages/suite/src/actions/recovery/recoveryActions.ts
  packages/suite/src/actions/settings/constants/index.ts
  packages/suite/src/components/onboarding/Option/index.tsx
  packages/suite/src/components/recovery/Error.tsx
  packages/suite/src/components/recovery/SelectRecoveryType.tsx
  packages/suite/src/components/recovery/SelectWordCount.tsx
  packages/suite/src/components/recovery/index.tsx
  packages/suite/src/components/suite/Preloader/index.tsx
  packages/suite/src/components/suite/ProgressBar/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/constants/suite/routes.ts
  packages/suite/src/middlewares/recovery/index.ts
  packages/suite/src/middlewares/recovery/recoveryMiddleware.ts
  packages/suite/src/middlewares/settings/recoveryMiddleware.ts
  packages/suite/src/reducers/recovery/index.ts
  packages/suite/src/reducers/recovery/recoveryReducer.ts
  packages/suite/src/reducers/settings/index.ts
  packages/suite/src/reducers/store.ts
  packages/suite/src/types/recovery/index.ts
  packages/suite/src/types/settings/index.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/views/onboarding/steps/Recovery/components/ModelOne.tsx
  packages/suite/src/views/onboarding/steps/Recovery/components/ModelT.tsx
  packages/suite/src/views/onboarding/steps/Recovery/index.tsx
  packages/suite/src/views/recovery/index.tsx
  packages/suite/src/views/seed-input/index.tsx
  packages/suite/src/views/settings/device/Container.ts
  packages/suite/src/views/settings/device/index.tsx
  tsconfig.json
Labels: ready to review

#1174 Visual fixes
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/backup/index.tsx
  packages/suite/src/views/firmware/index.tsx
  packages/suite/src/views/settings/debug/index.tsx
  packages/suite/src/views/settings/device/index.tsx
  packages/suite/src/views/settings/index.tsx
  packages/suite/src/views/settings/wallet/index.tsx
  packages/suite/src/views/suite/device-connect/index.tsx
Labels: ready to review

#1173 add backup support
  packages/integration-tests/projects/suite-web/plugins/index.js
  packages/integration-tests/projects/suite-web/plugins/python/emulator.py
  packages/integration-tests/projects/suite-web/plugins/python/main.py
  packages/integration-tests/projects/suite-web/support/commands.ts
  packages/integration-tests/projects/suite-web/support/utils/shortcuts.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/direct-path.test.ts
  packages/suite/src/views/onboarding/steps/Backup/index.tsx
  packages/suite/src/views/onboarding/steps/Final/index.tsx
  packages/suite/src/views/onboarding/steps/Pin/index.tsx
Labels: ready to review

#1180 new hologram video
  packages/suite-data/files/videos/onboarding/TT_hologram.mp4
  packages/suite-data/files/videos/onboarding/_TT_hologram.mp4
  packages/suite/src/views/onboarding/steps/Hologram/components/Hologram.tsx
Labels: ready to review

#1179 fix text
  packages/suite/src/support/messages.ts
  packages/suite/src/views/suite/welcome/index.tsx
Labels: ready to review

#1178 no backup notification text
  packages/suite/src/components/suite/Notifications/NoBackup.tsx
  packages/suite/src/support/messages.ts
Labels: ready to review

#1176 E2e tests dashboard
  packages/integration-tests/projects/suite-web/scripts/open-local.sh
  packages/integration-tests/projects/suite-web/scripts/run-ci.sh
  packages/integration-tests/projects/suite-web/scripts/run-local.sh
  packages/integration-tests/projects/suite-web/tests/dashboard/dashboard.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/direct-path.test.ts
  packages/integration-tests/projects/suite-web/tests/wallet/discovery.test.ts
  packages/suite/src/components/dashboard/AssetsCard/index.tsx
  packages/suite/src/components/dashboard/PortfolioCard/components/EmptyWallet/index.tsx
  packages/suite/src/components/dashboard/PortfolioCard/components/Loading/index.tsx
  packages/suite/src/components/dashboard/SecurityFeatures/Container.ts
  packages/suite/src/components/dashboard/SecurityFeatures/components/SecurityCard/index.tsx
  packages/suite/src/components/dashboard/SecurityFeatures/index.tsx
  packages/suite/src/components/suite/Loading/index.tsx
  packages/suite/src/components/suite/Menu/components/BottomMenu/index.tsx
  packages/suite/src/components/suite/Menu/components/MainMenu/index.tsx
  packages/suite/src/views/backup/index.tsx
  packages/suite/src/views/settings/wallet/index.tsx
Labels: ready to review

#1186 add failed backup notification
  packages/suite/src/components/suite/Notifications/FailedBackup.tsx
  packages/suite/src/components/suite/Notifications/index.tsx
  packages/suite/src/constants/suite/urls.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/device/index.tsx
Labels: ready to review

#1185 nitpick styling
  packages/suite/src/config/wallet/externalNetworks.ts
  packages/suite/src/views/settings/wallet/index.tsx
Labels: ready to review

#1182 add e2e for inital run
  packages/integration-tests/projects/suite-web/tests/suite/initial-run.test.ts
  packages/suite/src/views/suite/welcome/index.tsx
Labels: ready to review

#1175 Visual fixes
  packages/integration-tests/projects/suite-web/support/utils/shortcuts.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/direct-path.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/steps-order.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/transport.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/unexpected-states.test.ts
  packages/suite/src/components/onboarding/UnexpectedState/components/IsNotNewDevice.tsx
  packages/suite/src/config/onboarding/steps.ts
  packages/suite/src/views/onboarding/index.tsx
  packages/suite/src/views/onboarding/steps/CreateOrRecover/index.tsx
  packages/suite/src/views/onboarding/steps/Hologram/index.tsx
  packages/suite/src/views/onboarding/steps/NewOrUsed/index.tsx
  packages/suite/src/views/onboarding/steps/Recovery/Container.ts
  packages/suite/src/views/onboarding/steps/Recovery/index.tsx
  packages/suite/src/views/onboarding/steps/Skip/index.tsx
  packages/suite/src/views/onboarding/steps/Welcome/index.tsx
  packages/suite/src/views/suite/analytics/index.tsx
  packages/suite/src/views/suite/welcome/index.tsx
Labels: ready to review

#1194 Fix: switch device reset wallet params
  packages/suite/src/actions/suite/routerActions.ts
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx
  packages/suite/src/types/suite/index.ts
  packages/suite/src/views/onboarding/steps/Final/index.tsx
  packages/suite/src/views/onboarding/steps/Security/index.tsx
  packages/suite/src/views/onboarding/steps/Skip/index.tsx
  packages/suite/src/views/recovery/index.tsx
Labels: ready to review

#1195 fix for SUITE.UPDATE_PASSPHRASE_MODE
  packages/suite/src/actions/suite/modalActions.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/components/suite/modals/Passphrase/index.tsx
Labels: ready to review

#1190 Add passphrase length check
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
  packages/suite/src/constants/suite/passphrase.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/suite/__tests__/string.test.ts
  packages/suite/src/utils/suite/string.ts
Labels: ready to review

#1192 Passphrase test
  packages/integration-tests/projects/suite-web/plugins/index.js
  packages/integration-tests/projects/suite-web/plugins/python/bin/trezor-emu-legacy-v1.8.3
  packages/integration-tests/projects/suite-web/plugins/python/emulator.py
  packages/integration-tests/projects/suite-web/plugins/python/main.py
  packages/integration-tests/projects/suite-web/support/utils/shortcuts.ts
  packages/integration-tests/projects/suite-web/tests/suite/initial-run.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/passphrase.test.ts
  packages/suite/src/components/suite/DiscoveryLoader/index.tsx
  packages/suite/src/components/suite/Menu/components/TopMenu/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/WalletInstance/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
  packages/suite/src/components/suite/modals/confirm/Address/index.tsx
  packages/suite/src/components/suite/modals/confirm/NoBackup/index.tsx
  packages/suite/src/components/wallet/AccountMode/AuthConfirmFailed.tsx
  packages/suite/src/components/wallet/Menu/components/AccountItem/components/AccountNavigation/index.tsx
  packages/suite/src/views/wallet/receive/components/FreshAddress/index.tsx
  packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx
Labels: ready to review

#1199 Some components -> components-v2
  packages/suite/src/components/suite/Settings/components/ActionColumn.tsx
  packages/suite/src/components/suite/Settings/components/Row.tsx
  packages/suite/src/components/suite/Translation/components/HelperTooltip/index.tsx
  packages/suite/src/components/suite/WordInput/index.tsx
  packages/suite/src/components/wallet/Title/index.tsx
  packages/suite/src/views/onboarding/index.tsx
  packages/suite/src/views/onboarding/steps/Hologram/index.tsx
  packages/suite/src/views/onboarding/steps/Pair/components/Bridge/index.tsx
Labels: ready to review

#1184 Send - Account selector
  packages/components-storybook-v2/src/stories/form/select.tsx
  packages/components-v2/src/components/Select/index.tsx
  packages/suite/src/components/wallet/AccountSelector/Container.ts
  packages/suite/src/components/wallet/AccountSelector/index.tsx
  packages/suite/src/views/wallet/send/index.tsx
Labels: ready to review

#1200 Add 404 page and sort messages
  packages/suite-data/files/images/suite/404.svg
  packages/suite-desktop/pages/_error.tsx
  packages/suite-web/pages/_error.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/suite/error/index.tsx
Labels: ready to review

#1203 Disable passphrase button if passphrase is too long
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
Labels: ready to review

#1201 Add tooltips placeholders to send form
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/send/components/Address/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormEthereum/components/Data/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormEthereum/components/GasLimit/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormEthereum/components/GasPrice/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormRipple/components/DestinationTag/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/Fee/index.tsx
  packages/suite/src/views/wallet/send/components/Amount/index.tsx
Labels: ready to review

#1205 Make modal cancel bigger
  packages/components-v2/src/components/Modal/index.tsx
Labels: ready to review

#1204 Imporve backup
  packages/integration-tests/projects/suite-web/tests/backup/backup.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/device.test.ts
  packages/suite/src/components/suite/Notifications/NoBackup.tsx
  packages/suite/src/components/suite/modals/confirm/Action/index.tsx
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/utils/backup/index.ts
  packages/suite/src/views/backup/index.tsx
  packages/suite/src/views/onboarding/steps/Backup/Container.ts
  packages/suite/src/views/onboarding/steps/Backup/index.tsx
Labels: ready to review

#1202 firmware update improvements
  packages/integration-tests/projects/suite-web/support/utils/selectors.ts
  packages/integration-tests/projects/suite-web/tests/firmware/firmware.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/device.test.ts
  packages/suite-data/files/images/firmware/firmware-init-1.svg
  packages/suite-data/files/images/firmware/firmware-init-2.svg
  packages/suite-data/files/images/firmware/firmware-success-1.svg
  packages/suite-data/files/images/firmware/firmware-success-2.svg
  packages/suite/src/components/firmware/index.tsx
  packages/suite/src/components/suite/Notifications/UpdateFirmware.tsx
  packages/suite/src/middlewares/firmware/firmwareMiddleware.ts
  packages/suite/src/views/firmware/index.tsx
  packages/suite/src/views/onboarding/index.tsx
  packages/suite/src/views/onboarding/steps/Firmware/index.tsx
Labels: ready to review

#1214 use url constants, extend urls health check
  packages/suite/src/components/wallet/AccountException/FirmwareUnsupported.tsx
  packages/suite/src/config/suite/supportedBrowsers.ts
  packages/suite/src/constants/suite/urls.ts
  packages/suite/test/health/urls.test.ts
Labels: ready to review

#1183 Recovery e2e test
  packages/integration-tests/.gitignore
  packages/integration-tests/projects/suite-web/plugins/index.js
  packages/integration-tests/projects/suite-web/plugins/python/common/__init__.py
  packages/integration-tests/projects/suite-web/plugins/python/common/buttons.py
  packages/integration-tests/projects/suite-web/plugins/python/emulator.py
  packages/integration-tests/projects/suite-web/plugins/python/main.py
  packages/integration-tests/projects/suite-web/tests/onboarding/create-path.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/recovery-path.test.ts
  packages/suite-native/.gitignore
  packages/suite/src/views/onboarding/steps/Final/index.tsx
  packages/suite/src/views/onboarding/steps/Pin/index.tsx
  packages/suite/src/views/onboarding/steps/Recovery/index.tsx
Labels: ready to review

#1198 Review tx modal + refactor + estimated time
  packages/suite-desktop/pages/wallet/index.tsx
  packages/suite-web/pages/wallet/index.tsx
  packages/suite/src/actions/suite/modalActions.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/wallet/send/sendFormActions.ts
  packages/suite/src/components/suite/modals/ReviewTransaction/Container.ts
  packages/suite/src/components/suite/modals/ReviewTransaction/index.tsx
  packages/suite/src/components/suite/modals/confirm/SignTx/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/types/wallet/index.ts
  packages/suite/src/views/wallet/send/components/Add/components/NetworkTypeBitcoin/index.tsx
  packages/suite/src/views/wallet/send/components/Add/index.tsx
  packages/suite/src/views/wallet/send/components/Address/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormBitcoin/components/Locktime/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormBitcoin/components/ReplaceByFee/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormBitcoin/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormEthereum/components/Data/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormEthereum/components/GasLimit/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormEthereum/components/GasPrice/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormEthereum/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormRipple/components/DestinationTag/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/AdvancedFormRipple/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/Fee/components/CustomFee/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/Fee/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/Layout/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/components/TransactionInfo/index.tsx
  packages/suite/src/views/wallet/send/components/AdvancedForm/index.tsx
  packages/suite/src/views/wallet/send/components/Amount/components/Fiat/index.tsx
  packages/suite/src/views/wallet/send/components/ButtonToggleAdditional/index.tsx
  packages/suite/src/views/wallet/send/components/Clear/index.tsx
  packages/suite/src/views/wallet/send/components/EstimatedMiningTime/index.tsx
  packages/suite/src/views/wallet/send/components/ReviewButtonSection/Container.ts
  packages/suite/src/views/wallet/send/components/ReviewButtonSection/index.tsx
  packages/suite/src/views/wallet/send/index.tsx
  packages/suite/src/views/wallet/transactions/Container.ts
  packages/suite/src/views/wallet/transactions/index.tsx
Labels: ready to review

#1209 add close button, add pin mismatch modal
  packages/suite-data/files/videos/suite/pin-mismatch.mp4
  packages/suite/src/actions/settings/deviceSettingsActions.ts
  packages/suite/src/actions/suite/modalActions.ts
  packages/suite/src/components/suite/modals/Pin/index.tsx
  packages/suite/src/components/suite/modals/PinMismatch/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/support/messages.ts
Labels: ready to review

#1213 Nitpick fixes
  packages/integration-tests/projects/suite-web/tests/onboarding/unexpected-states.test.ts
  packages/suite/src/actions/onboarding/__fixtures__/onboardingActions.ts
  packages/suite/src/actions/onboarding/__tests__/onboardingActions.test.ts
  packages/suite/src/actions/onboarding/connectActions.ts
  packages/suite/src/actions/onboarding/onboardingActions.ts
  packages/suite/src/actions/recovery/recoveryActions.ts
  packages/suite/src/actions/settings/deviceSettingsActions.ts
  packages/suite/src/components/onboarding/UnexpectedState/components/DeviceIsUsedHere.tsx
  packages/suite/src/components/onboarding/UnexpectedState/components/IsNotNewDevice.tsx
  packages/suite/src/components/onboarding/UnexpectedState/components/IsSameDevice.tsx
  packages/suite/src/components/onboarding/UnexpectedState/index.tsx
  packages/suite/src/components/onboarding/Wrapper/StepBodyWrapper.tsx
  packages/suite/src/components/onboarding/Wrapper/StepWrapper.tsx
  packages/suite/src/components/suite/ProgressBar/index.tsx
  packages/suite/src/constants/onboarding/steps.ts
  packages/suite/src/reducers/onboarding/__tests__/onboardingReducer.test.ts
  packages/suite/src/reducers/onboarding/onboardingReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/onboarding/index.ts
  packages/suite/src/types/onboarding/steps.ts
  packages/suite/src/utils/onboarding/__tests__/rules.test.ts
  packages/suite/src/utils/onboarding/rules.ts
  packages/suite/src/views/onboarding/index.tsx
  packages/suite/src/views/onboarding/steps/Backup/Container.ts
  packages/suite/src/views/onboarding/steps/Firmware/Container.ts
  packages/suite/src/views/onboarding/steps/Pin/Container.ts
  packages/suite/src/views/onboarding/steps/Pin/index.tsx
  packages/suite/src/views/onboarding/steps/Shamir/Container.ts
  packages/suite/src/views/onboarding/steps/Shamir/index.tsx
Labels: ready to review

#1210 finish device settings
  packages/suite/src/views/settings/device/index.tsx
Labels: Product!, ready to review

#1220 Fix/dashboard minor fixes, passphrase modal visuals and handling submitting with enter
  packages/suite/src/components/dashboard/AssetsCard/components/Asset/index.tsx
  packages/suite/src/components/dashboard/AssetsCard/index.tsx
  packages/suite/src/components/dashboard/PortfolioCard/components/EmptyWallet/index.tsx
  packages/suite/src/components/dashboard/PortfolioCard/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/index.tsx
  packages/suite/src/views/dashboard/index.tsx
Labels: ready to review

#1206 Add account selector for receive
  packages/suite-desktop/pages/wallet/receive/index.tsx
  packages/suite-web/pages/wallet/receive/index.tsx
  packages/suite/src/components/wallet/AccountSelector/index.tsx
  packages/suite/src/views/wallet/receive/Container.ts
  packages/suite/src/views/wallet/receive/components/FreshAddress/index.tsx
  packages/suite/src/views/wallet/receive/components/Header/index.tsx
  packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx
  packages/suite/src/views/wallet/receive/index.tsx
Labels: ready to review

#1224 blockchain-link v1.0.7
  packages/blockchain-link/.npmignore
  packages/blockchain-link/CHANGELOG.md
  packages/blockchain-link/package.json
  packages/blockchain-link/src/workers/ripple/index.ts
  packages/blockchain-link/tests/unit/fixtures/getInfo.ts
  packages/blockchain-link/tests/websocket/fixtures/ripple.json
  packages/integration-tests/package.json
  packages/suite-data/package.json
  packages/suite-native/package.json
  yarn.lock
Labels: ready to review

#1227 fix for macos close
  packages/suite-desktop/src-electron/electron.ts
Labels: ready to review

#1212 log in modal
  packages/integration-tests/projects/suite-web/support/utils/shortcuts.ts
  packages/integration-tests/projects/suite-web/tests/settings/device.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/log.test.ts
  packages/suite/src/actions/suite/constants/logConstants.ts
  packages/suite/src/actions/suite/logActions.ts
  packages/suite/src/components/settings/Menu/index.tsx
  packages/suite/src/components/suite/Log/index.tsx
  packages/suite/src/components/suite/ToastNotification/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/components/suite/modals/Log/index.tsx
  packages/suite/src/components/suite/modals/confirm/Address/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/reducers/suite/logReducer.ts
  packages/suite/src/reducers/suite/notificationReducer.ts
  packages/suite/src/support/messages.ts
Labels: ready to review

#1221 Send - clear, remove and recipient index
  packages/components-v2/src/components/Icon/icons.ts
  packages/components-v2/src/images/icons/clear.svg
  packages/suite/src/views/wallet/send/components/Clear/index.tsx
  packages/suite/src/views/wallet/send/components/OutputHeader/components/Remove/index.tsx
  packages/suite/src/views/wallet/send/components/OutputHeader/index.tsx
  packages/suite/src/views/wallet/send/index.tsx
Labels: ready to review

#1151 Fix icons
  packages/components-v2/src/components/inputs/Input/index.tsx
  packages/components-v2/src/config/variables.ts
  packages/components-v2/src/images/icons/back.svg
  packages/components-v2/src/images/icons/external_link.svg
  packages/components-v2/src/images/icons/hide.svg
  packages/components-v2/src/images/icons/show.svg
  packages/components-v2/src/support/types/index.ts
  packages/integration-tests/projects/components-storybook-v2/snapshots/Icons.test.js/Icons -- icon-back.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Icons.test.js/Icons -- icon-hide.snap.png
  packages/integration-tests/projects/components-storybook-v2/snapshots/Icons.test.js/Icons -- icon-show.snap.png
  packages/integration-tests/projects/components-storybook-v2/tests/Icons.test.js
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
Labels: ready to review

#1229 Fix/focus lock
  packages/suite/src/components/suite/Preloader/index.tsx
  packages/suite/src/components/suite/modals/Log/index.tsx
  packages/suite/src/components/suite/modals/confirm/Address/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/utils/suite/dom.ts
Labels: ready to review

#1235 Feature/bridge new design
  packages/components-v2/src/images/icons/sign.svg
  packages/suite-data/files/images/suite/t-bridge-check.svg
  packages/suite/src/support/messages.ts
  packages/suite/src/views/suite/bridge/index.tsx
Labels: ready to review

#1237 Use translation in send address input
  packages/suite/src/views/wallet/send/components/Address/Container.ts
  packages/suite/src/views/wallet/send/components/Address/index.tsx
Labels: ready to review

#1223 Prevent to send less than 20 XRP to empty account
  packages/suite/src/actions/wallet/constants/sendFormConstants.ts
  packages/suite/src/actions/wallet/send/sendFormActions.ts
  packages/suite/src/actions/wallet/send/sendFormBitcoinActions.ts
  packages/suite/src/actions/wallet/send/sendFormRippleActions.ts
  packages/suite/src/constants/wallet/sendForm.ts
  packages/suite/src/reducers/wallet/sendFormReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/wallet/sendForm/actions.ts
  packages/suite/src/types/wallet/sendForm/output.ts
  packages/suite/src/utils/wallet/__fixtures__/sendFormFixtures.ts
  packages/suite/src/views/wallet/send/components/Address/index.tsx
  packages/suite/src/views/wallet/send/components/Amount/index.tsx
Labels: ready to review

#1238 Remove old notifications from storybook and components
  packages/components-storybook-v2/.storybook/config.js
  packages/components-storybook-v2/src/stories/notifications/all.tsx
  packages/components-storybook-v2/src/stories/notifications/notification.tsx
  packages/components-v2/src/components/Notification/index.tsx
  packages/components-v2/src/index.ts
Labels: ready to review

#1228 Discreet mode - placeholders
  packages/suite/src/components/dashboard/AssetsCard/components/Asset/index.tsx
  packages/suite/src/components/dashboard/PortfolioCard/index.tsx
  packages/suite/src/components/dashboard/SecurityFeatures/index.tsx
  packages/suite/src/components/suite/HiddenPlaceholder/Container.ts
  packages/suite/src/components/suite/HiddenPlaceholder/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/BasicDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/FiatDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/IODetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/index.tsx
  packages/suite/src/components/wallet/AccountSelector/index.tsx
  packages/suite/src/components/wallet/Menu/components/AccountItem/index.tsx
  packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx
  packages/suite/src/views/wallet/send/components/Address/index.tsx
  packages/suite/src/views/wallet/transactions/components/PricePanel/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionItem/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx
Labels: ready to review

#1239 Toast with CTA and Translations
  packages/suite-desktop/pages/_app.tsx
  packages/suite-web/pages/_app.tsx
  packages/suite/src/actions/suite/__tests__/notificationActions.test.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/actions/wallet/blockchainActions.ts
  packages/suite/src/actions/wallet/send/sendFormBitcoinActions.ts
  packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts
  packages/suite/src/actions/wallet/send/sendFormRippleActions.ts
  packages/suite/src/components/suite/ToastNotification/components/Toast.tsx
  packages/suite/src/components/suite/ToastNotification/index.tsx
  packages/suite/src/components/suite/modals/Log/index.tsx
  packages/suite/src/components/suite/modals/confirm/Address/index.tsx
  packages/suite/src/components/suite/modals/confirm/Xpub/index.tsx
  packages/suite/src/middlewares/suite/toastMiddleware.ts
  packages/suite/src/reducers/store.ts
  packages/suite/src/reducers/suite/notificationReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/support/suite/styles/notifications.ts
  packages/suite/src/types/utils/index.ts
Labels: ready to review

#1242 Feature/notifications
  NOTES.md
  packages/components/src/components/Icon/icons.ts
  packages/components/src/images/icons/notifications.svg
  packages/suite-data/files/images/suite/uni-empty-page.svg
  packages/suite-desktop/pages/notifications/index.tsx
  packages/suite-web/pages/notifications/index.tsx
  packages/suite/src/actions/backup/__tests__/backupActions.test.ts
  packages/suite/src/actions/backup/backupActions.ts
  packages/suite/src/actions/settings/__fixtures__/deviceSettings.ts
  packages/suite/src/actions/settings/deviceSettingsActions.ts
  packages/suite/src/actions/suite/__fixtures__/suiteActions.ts
  packages/suite/src/actions/suite/__tests__/notificationActions.test.ts
  packages/suite/src/actions/suite/constants/notificationConstants.ts
  packages/suite/src/actions/suite/notificationActions.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/actions/wallet/__fixtures__/receiveActions.ts
  packages/suite/src/actions/wallet/__tests__/discoveryActions.test.ts
  packages/suite/src/actions/wallet/blockchainActions.ts
  packages/suite/src/actions/wallet/discoveryActions.ts
  packages/suite/src/actions/wallet/receiveActions.ts
  packages/suite/src/actions/wallet/send/sendFormBitcoinActions.ts
  packages/suite/src/actions/wallet/send/sendFormEthereumActions.ts
  packages/suite/src/actions/wallet/send/sendFormRippleActions.ts
  packages/suite/src/actions/wallet/signVerifyActions.ts
  packages/suite/src/components/suite/Menu/components/BottomMenu/index.tsx
  packages/suite/src/components/suite/ToastNotification/components/Toast.tsx
  packages/suite/src/components/suite/ToastNotification/index.tsx
  packages/suite/src/components/suite/modals/Log/index.tsx
  packages/suite/src/components/suite/modals/confirm/Address/index.tsx
  packages/suite/src/components/suite/modals/confirm/Xpub/Container.tsx
  packages/suite/src/constants/suite/menu.ts
  packages/suite/src/constants/suite/routes.ts
  packages/suite/src/middlewares/suite/eventsMiddleware.ts
  packages/suite/src/middlewares/suite/index.ts
  packages/suite/src/middlewares/suite/toastMiddleware.ts
  packages/suite/src/reducers/suite/notificationReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/suite/notifications.ts
  packages/suite/src/utils/suite/storage.ts
  packages/suite/src/views/suite/notifications/Container.tsx
  packages/suite/src/views/suite/notifications/index.tsx
  packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx
Labels: ready to review

#1246 fix styled components SSR
  packages/suite-desktop/pages/_document.tsx
  packages/suite-web/pages/_document.tsx
Labels: ready to review

#1207 external wallet links
  packages/components/src/components/Link/index.tsx
  packages/suite/src/components/settings/Menu/index.tsx
  packages/suite/src/components/settings/SettingsLayout/index.tsx
  packages/suite/src/components/settings/index.tsx
  packages/suite/src/components/suite/Link/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/debug/index.tsx
  packages/suite/src/views/settings/device/index.tsx
  packages/suite/src/views/settings/index.tsx
  packages/suite/src/views/settings/wallet/index.tsx
Labels: ready to review

#1181 fix disable webusb and tests
  packages/integration-tests/projects/suite-web/tests/onboarding/transport.test.ts
  packages/suite/src/views/onboarding/steps/Pair/index.tsx
Labels: ready to review

#1249 Fix tooltip positon and props
  packages/components/src/components/Tooltip/index.tsx
  packages/components/src/components/Tooltip/tippy.style.ts
  packages/suite/src/components/suite/Menu/components/BottomMenu/index.tsx
  packages/suite/src/support/messages.ts
Labels: ready to review

#1248 Blockchain actions cleanup
  packages/suite/src/actions/wallet/accountActions.ts
  packages/suite/src/actions/wallet/blockchainActions.ts
  packages/suite/src/reducers/wallet/transactionReducer.ts
  packages/suite/src/utils/wallet/accountUtils.ts
Labels: ready to review

#1250 Feature/labeling tx
  packages/suite/src/components/suite/Labeling/components/Wallet/Container.tsx
  packages/suite/src/components/suite/Labeling/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/WalletInstance/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/views/wallet/send/components/Address/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionItem/index.tsx
Labels: ready to review

#1253 fix external link icon
  packages/suite/src/components/suite/Link/index.tsx
Labels: ready to review

#1255 rework suite/link to suite/external-link
  packages/suite/src/components/suite/ExternalLink/index.tsx
  packages/suite/src/components/suite/Link/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/components/suite/modals/AddAccount/index.tsx
  packages/suite/src/components/wallet/Menu/components/AccountItem/Container.ts
  packages/suite/src/components/wallet/Menu/components/AccountItem/index.tsx
  packages/suite/src/utils/suite/__tests__/router.test.ts
  packages/suite/src/utils/suite/router.ts
  packages/suite/src/views/settings/wallet/index.tsx
  packages/suite/src/views/suite/error/index.tsx
Labels: ready to review

#1218 styling fixes
  packages/suite/src/components/onboarding/Wrapper/ControlsWrapper.tsx
  packages/suite/src/components/onboarding/Wrapper/OptionsWrapper.tsx
  packages/suite/src/components/onboarding/Wrapper/StepBodyWrapper.tsx
  packages/suite/src/components/onboarding/Wrapper/StepFooterWrapper.tsx
  packages/suite/src/components/onboarding/Wrapper/StepWrapper.tsx
  packages/suite/src/components/suite/ModalWrapper/index.tsx
  packages/suite/src/views/onboarding/index.tsx
  packages/suite/src/views/settings/device/index.tsx
Labels: ready to review

#1241 clear timeout in TopMenu component
  packages/suite/src/components/suite/Menu/components/TopMenu/index.tsx
Labels: ready to review

#1262 add wipe device dialog
  packages/integration-tests/projects/suite-web/tests/settings/device.test.ts
  packages/suite/src/actions/suite/modalActions.ts
  packages/suite/src/components/backup/AfterBackupCheckboxes.tsx
  packages/suite/src/components/backup/PreBackupCheckboxes.tsx
  packages/suite/src/components/backup/index.ts
  packages/suite/src/components/onboarding/UnexpectedState/components/IsNotNewDevice.tsx
  packages/suite/src/components/recovery/Error.tsx
  packages/suite/src/components/suite/CheckItem/index.tsx
  packages/suite/src/components/suite/images/UniErrorImg/index.tsx
  packages/suite/src/components/suite/images/UniWarningImg/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/components/suite/modals/BackgroundGallery/index.tsx
  packages/suite/src/components/suite/modals/WipeDevice/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/components/wallet/AccountException/AccountNotEnabled.tsx
  packages/suite/src/components/wallet/AccountException/AccountNotExists.tsx
  packages/suite/src/components/wallet/AccountException/AccountNotLoaded.tsx
  packages/suite/src/components/wallet/AccountException/AuthFailed.tsx
  packages/suite/src/components/wallet/AccountException/DiscoveryEmpty.tsx
  packages/suite/src/components/wallet/AccountException/DiscoveryFailed.tsx
  packages/suite/src/components/wallet/AccountException/components/Wrapper.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/backup/index.tsx
  packages/suite/src/views/firmware/index.tsx
  packages/suite/src/views/settings/device/Container.ts
  packages/suite/src/views/settings/device/index.tsx
Labels: ready to review

#1258 add activate/deactivate button
  packages/integration-tests/projects/suite-web/tests/wallet/discovery.test.ts
  packages/suite/src/actions/settings/walletSettingsActions.ts
  packages/suite/src/actions/wallet/__fixtures__/settingsActions.ts
  packages/suite/src/views/settings/wallet/index.tsx
Labels: ready to review

#1263 fix NoTransactions component
  packages/suite/src/components/wallet/AccountAnnouncement/index.tsx
  packages/suite/src/views/wallet/transactions/Container.ts
  packages/suite/src/views/wallet/transactions/components/NoTransactions/index.tsx
  packages/suite/src/views/wallet/transactions/index.tsx
Labels: ready to review
