Repository trezor/trezor-suite, pull requests merged in 2021-06, with the labels that each got.

#3766 fix(suite): edit settings layout
  packages/suite/src/components/settings/SettingsLayout/index.tsx
  packages/suite/src/components/settings/SettingsMenu/index.tsx
  packages/suite/src/components/suite/Settings/components/TextColumn.tsx
Labels: READY TO MERGE, READY TO REVIEW

#3809 fix: incorrect device features unlocked type
  packages/suite/src/reducers/suite/deviceReducer.ts
  patches/trezor-connect+8.1.28-beta.1.patch
Labels: READY TO REVIEW

#3773 fix(invity): Sell/Exchange with zero balance
  packages/suite-data/files/translations/en.json
  packages/suite/src/components/wallet/CoinMarketFractionButtons/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/Buttons/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Inputs/Buttons/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Inputs/index.tsx
Labels: READY TO REVIEW

#3816 fix(suite): remove extra hidden overflows to fix discreet mode
  packages/suite/src/views/wallet/tokens/components/TokenList/index.tsx
Labels: READY TO REVIEW

#3791 fix(suite): update of btc-only fw to btc-only fw
  packages/suite/src/actions/firmware/constants/firmware.ts
  packages/suite/src/actions/firmware/firmwareActions.ts
  packages/suite/src/middlewares/firmware/firmwareMiddleware.ts
  packages/suite/src/reducers/firmware/firmwareReducer.ts
Labels: READY TO REVIEW

#3801 feat(fwUpdate): wait for reboot instead of instructiong to unplug for…
  packages/suite/src/actions/firmware/firmwareActions.ts
Labels: READY TO REVIEW

#3815 feat(guide): Learn and Discover (Suite Guide) + Feedback submission
  docs/specs/bug_and_feedback_submission.md
  packages/components/src/components/Icon/icons.ts
  packages/components/src/components/Modal/index.tsx
  packages/components/src/components/form/Input/index.tsx
  packages/components/src/components/form/Select/index.tsx
  packages/components/src/components/form/Textarea/index.tsx
  packages/components/src/components/logos/TrezorLogo/logos.ts
  packages/components/src/components/logos/index.stories.tsx
  packages/components/src/config/variables.ts
  packages/components/src/images/icons/arrow_left_long.svg
  packages/components/src/images/icons/article.svg
  packages/components/src/images/icons/attachment.svg
  packages/components/src/images/trezor_logo_suite_square.svg
  packages/components/src/support/types/index.ts
  packages/suite-data/files/guide/en/trezor-suite/buy-sell-and-trade.md
  packages/suite-data/files/guide/en/trezor-suite/passphrase.md
  packages/suite-data/files/guide/en/trezor-suite/receive.md
  packages/suite-data/files/guide/en/trezor-suite/send.md
  packages/suite-data/files/guide/en/trezor-suite/suite-guide.md
  packages/suite-data/files/images/suite/3d/coins.png
  packages/suite-data/files/images/suite/3d/recovery.png
  packages/suite-data/files/images/suite/3d/understand.png
  packages/suite-data/files/images/suite/lamp.png
  packages/suite-desktop/next.config.js
  packages/suite-desktop/package.json
  packages/suite-web/next.config.js
  packages/suite-web/package.json
  packages/suite/src/actions/suite/constants/guideConstants.ts
  packages/suite/src/actions/suite/constants/index.ts
  packages/suite/src/actions/suite/guideActions.ts
  packages/suite/src/components/guide/Content.tsx
  packages/suite/src/components/guide/GuideButton.tsx
  packages/suite/src/components/guide/GuidePanel.tsx
  packages/suite/src/components/guide/Header.tsx
  packages/suite/src/components/guide/ViewWrapper.tsx
  packages/suite/src/components/guide/index.tsx
  packages/suite/src/components/suite/BetaBadge/index.tsx
  packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/SettingsDropdown/index.tsx
  packages/suite/src/components/suite/NavigationBar/index.tsx
  packages/suite/src/components/suite/SuiteLayout/index.tsx
  packages/suite/src/components/suite/hocNotification/index.tsx
  packages/suite/src/reducers/suite/guideReducer.ts
  packages/suite/src/reducers/suite/index.ts
  packages/suite/src/reducers/suite/notificationReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/suite/guide.tsx
  packages/suite/src/types/suite/index.ts
  packages/suite/src/views/guide/Feedback.tsx
  packages/suite/src/views/guide/FeedbackTypeSelection.tsx
  packages/suite/src/views/guide/GuideArticle.tsx
  packages/suite/src/views/guide/GuideDefault.tsx
  packages/suite/src/views/guide/index.tsx
  tsconfig.json
  yarn.lock
Labels: READY TO REVIEW

#3835 feat(invity): Update Trezor Suite Payment Methods
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW, Release

#3837 fix(suite): btc-only fw update in onboarding; btc-only tag in fw modals
  packages/suite/src/components/firmware/NoNewFirmware.tsx
  packages/suite/src/components/firmware/OnboardingInitial.tsx
  packages/suite/src/middlewares/firmware/firmwareMiddleware.ts
Labels: READY TO REVIEW, Release

#3832 fix(components): remove redunant prop from RadioButton component
  packages/components/src/components/form/RadioButton/index.stories.tsx
  packages/components/src/components/form/RadioButton/index.tsx
  packages/components/src/components/form/index.stories.tsx
  packages/integration-tests/projects/suite-web/tests/settings/safety-checks.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/safety-checks-warning.test.ts
  packages/suite/src/components/suite/modals/SafetyChecks/index.tsx
Labels: READY TO REVIEW

#3854 fix(guide): Suite Guide icon updated
  packages/suite-data/files/images/suite/lamp.png
Labels: READY TO REVIEW

#3861 fix(guide): links in Suite Guide category
  packages/suite-data/files/guide/en/trezor-suite/suite-guide.md
Labels: READY TO REVIEW

#3857 feat(invity): Update T&Cs: Invity
  packages/suite/src/components/wallet/CoinmarketFooter/index.tsx
  packages/suite/src/constants/suite/urls.ts
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#3860 fix: ethereum gasPrice and estimated gasLimit
  packages/suite/src/utils/wallet/sendFormUtils.ts
Labels: READY TO REVIEW

#3844 fix: metadata for multiple devices
  packages/integration-tests/projects/suite-web/tests/metadata/wallet-metadata.test.ts
  packages/suite/src/components/suite/SwitchDevice/components/WalletInstance/index.tsx
Labels: READY TO REVIEW

#3879 Send form improvements
  packages/suite/src/components/suite/modals/ReviewTransaction/components/OutputList.tsx
  packages/suite/src/components/suite/modals/ReviewTransaction/index.tsx
Labels: READY TO REVIEW

#3834 fix(invity): refactoring Invity API data load
  packages/suite/src/actions/wallet/coinmarket/coinmarketCommonActions.ts
  packages/suite/src/actions/wallet/constants/coinmarketCommonConstants.ts
  packages/suite/src/constants/wallet/coinmarket/metadata.ts
  packages/suite/src/hooks/wallet/useCoinmarket.ts
  packages/suite/src/hooks/wallet/useCoinmarketBuyForm.ts
  packages/suite/src/hooks/wallet/useCoinmarketExchangeForm.ts
  packages/suite/src/hooks/wallet/useCoinmarketSellForm.ts
  packages/suite/src/hooks/wallet/useCoinmarketSellOffers.ts
  packages/suite/src/hooks/wallet/useCoinmarketSpend.ts
  packages/suite/src/middlewares/wallet/coinmarketMiddleware.ts
  packages/suite/src/middlewares/wallet/index.ts
  packages/suite/src/reducers/wallet/coinmarketReducer.ts
  packages/suite/src/services/suite/invityAPI.ts
Labels: READY TO REVIEW

#3903 fix(send): do not reduce account balance if replacement tx have decreased output
  packages/suite/src/actions/wallet/sendFormActions.ts
  packages/suite/src/actions/wallet/transactionActions.ts
  packages/suite/src/components/suite/modals/ReviewTransaction/index.tsx
  packages/suite/src/types/wallet/sendForm.ts
  packages/suite/src/utils/wallet/accountUtils.ts
Labels: READY TO REVIEW, Release

#3909 fix(send): ReplaceTransaction current fee fiat calculation
  packages/suite/src/components/suite/modals/TransactionDetail/components/ChangeFee/components/DecreasedOutputs/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/ChangeFee/index.tsx
Labels: READY TO REVIEW, Release

#3842 feat: do not 'disconnect' metadata provider when disabling metadata
  packages/integration-tests/projects/suite-web/tests/metadata/remembered-device.test.ts
  packages/suite/src/reducers/suite/metadataReducer.ts
Labels: READY TO REVIEW

#3930 Fix/3915 crash on firmware required suite initialized
  packages/suite/src/components/firmware/FirmwareInitial.tsx
  packages/suite/src/components/firmware/FirmwareInstallation.tsx
  packages/suite/src/views/firmware/index.tsx
  packages/suite/src/views/onboarding/steps/Firmware/index.tsx
Labels: READY TO REVIEW

#3838 feat(desktop): maximize window with double click
  packages/suite-desktop/src-electron/modules/window-controls.ts
  packages/suite-desktop/src-electron/preload.ts
  packages/suite-desktop/src/support/DesktopTitlebar.tsx
  packages/suite/global.d.ts
Labels: READY TO REVIEW

#3931 fix(onboarding): huge icon when backup fails
  packages/suite/src/views/onboarding/steps/Backup/index.tsx
Labels: READY TO REVIEW

#3939 feat(autoupdate): #3797 Remove autoupdate cancel button
  packages/suite-desktop/src/support/DesktopUpdater/Downloading.tsx
Labels: READY TO REVIEW

#3954 feat(analytics): add timestamp to every event sent
  docs/misc/analytics.md
  packages/integration-tests/projects/suite-web/tests/suite/analytics.test.ts
  packages/suite/src/actions/suite/__tests__/analyticsActions.test.ts
  packages/suite/src/utils/suite/__fixtures__/analytics.ts
  packages/suite/src/utils/suite/__tests__/analytics.test.ts
  packages/suite/src/utils/suite/analytics.ts
Labels: READY TO REVIEW
