Repository trezor/trezor-suite, pull requests merged in 2021-12, with the labels that each got.

#4590 fix(suite): custom backend not stored in indexeddb
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
Labels: READY TO REVIEW

#4600 feat(invity): add USDC to buy crypto tokens
  packages/suite/src/utils/wallet/coinmarket/__tests__/buyUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/buyUtils.ts
Labels: +Invity, release, READY TO MERGE

#4599 chore: trezor-connect@8.2.3-beta.5
  packages/suite/package.json
  yarn.lock
Labels: READY TO REVIEW, release

#4598 fix(icons): update universal success and error icons
  packages/integration-tests/projects/suite-web/snapshots/settings/coins.test.ts/coin-settings-disabled-all-dashboard.snap.png
  packages/suite-data/files/images/svg/empty-dashboard.svg
  packages/suite-data/files/images/svg/hologram-warning.svg
  packages/suite-data/files/images/svg/uni-error.svg
  packages/suite-data/files/images/svg/uni-success.svg
  packages/suite/src/components/firmware/Button.tsx
  packages/suite/src/components/firmware/Img.tsx
  packages/suite/src/components/firmware/index.tsx
  packages/suite/src/components/recovery/Error.tsx
  packages/suite/src/components/recovery/index.tsx
  packages/suite/src/components/suite/images/Image/index.tsx
  packages/suite/src/components/suite/modals/PinMismatch/index.tsx
  packages/suite/src/components/suite/modals/confirm/Address/components/DeviceDisconnected.tsx
  packages/suite/src/views/backup/index.tsx
  packages/suite/src/views/dashboard/components/PortfolioCard/components/EmptyWallet/index.tsx
  packages/suite/src/views/dashboard/components/PortfolioCard/components/Exception/index.tsx
  packages/suite/src/views/dashboard/components/PortfolioCard/index.tsx
  packages/suite/src/views/recovery/index.tsx
Labels: READY TO REVIEW, release

#4602 feat(connect-common): add firmware binaries 1.10.4/2.4.3
  packages/connect-common/files/firmware/1/releases.json
  packages/connect-common/files/firmware/1/trezor-1.10.3-bitcoinonly.bin
  packages/connect-common/files/firmware/1/trezor-1.10.3.bin
  packages/connect-common/files/firmware/1/trezor-1.10.4-bitcoinonly.bin
  packages/connect-common/files/firmware/1/trezor-1.10.4.bin
  packages/connect-common/files/firmware/2/releases.json
  packages/connect-common/files/firmware/2/trezor-2.4.2-bitcoinonly.bin
  packages/connect-common/files/firmware/2/trezor-2.4.2.bin
  packages/connect-common/files/firmware/2/trezor-2.4.3-bitcoinonly.bin
  packages/connect-common/files/firmware/2/trezor-2.4.3.bin
Labels: READY TO REVIEW, release

#4596 chore(e2e): optimize e2e metadata tests
  packages/integration-tests/projects/suite-web/tests/metadata/address-metadata.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/output-labeling.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/wallet-metadata.test.ts
Labels: READY TO REVIEW

#4607 connect 8.2.3-beta.6
  packages/connect-common/package.json
  packages/suite/package.json
  yarn.lock
Labels: release

#4605 chore(guide): update Suite Guide
  packages/suite-data/src/guide/constants.ts
Labels: READY TO REVIEW, release

#4608 fix(suite): update recharts lib to fix <path> attribute error
  packages/suite/package.json
  yarn.lock
Labels: READY TO REVIEW, release

#4611 chore(guide): update Suite Guide
  packages/suite-data/src/guide/constants.ts
Labels: READY TO REVIEW, release, guide

#4613 chore(e2e): adjust expected number of metadata requests
  packages/integration-tests/projects/suite-web/tests/metadata/account-metadata.test.ts
Labels: READY TO REVIEW

#4597 refactor(suite): replace react-redux binding with hooks
  packages/suite-native/src/components/suite/Layout/index.tsx
  packages/suite-native/src/components/suite/Preloader/index.tsx
  packages/suite-native/src/views/dashboard/index.tsx
  packages/suite-native/src/views/suite/backup/index.tsx
  packages/suite-native/src/views/suite/firmware/index.tsx
  packages/suite-native/src/views/suite/onboarding/components/InitialRun/index.tsx
  packages/suite-native/src/views/suite/onboarding/index.tsx
  packages/suite-native/src/views/suite/switch-device/index.tsx
  packages/suite-native/src/views/wallet/index.tsx
  packages/suite/src/components/backup/AfterBackupCheckboxes.tsx
  packages/suite/src/components/backup/PreBackupCheckboxes.tsx
  packages/suite/src/components/suite/DeviceInvalidModeLayout/index.tsx
  packages/suite/src/components/suite/SuiteLayout/index.tsx
  packages/suite/src/components/suite/modals/Log/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/index.tsx
  packages/suite/src/components/suite/modals/PassphraseOnDevice/index.tsx
  packages/suite/src/components/suite/modals/PassphraseSource/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/components/wallet/AccountMode/BackendDisconnected.tsx
  packages/suite/src/components/wallet/AccountsMenu/index.tsx
  packages/suite/src/views/backup/index.tsx
  packages/suite/src/views/dashboard/components/PortfolioCard/components/Exception/index.tsx
  packages/suite/src/views/dashboard/components/PortfolioCard/index.tsx
  packages/suite/src/views/recovery/index.tsx
  packages/suite/src/views/suite/bridge/index.tsx
  packages/suite/src/views/suite/device-bootloader/index.tsx
  packages/suite/src/views/suite/device-connect/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/detail/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/offers/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/SelectedOffer/components/VerifyAddress/ReceiveOptions/index.tsx
Labels: READY TO REVIEW

#4556 chore: find duplicates in translations
  ci/schedules.yml
  packages/suite-data/scripts/list-duplicates.ts
  packages/suite-web/package.json
  packages/suite/package.json
  yarn.lock
Labels: READY TO REVIEW

#4623 fix(invity): dex message fix
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/lol.json
  packages/suite/src/support/messages.ts
Labels: bug, READY TO REVIEW, +Invity

#4636 chore: upgrade cross-fetch
  packages/rollout/package.json
  yarn.lock
Labels: READY TO REVIEW

#4637 chore: rollout 1.2.1
  packages/rollout/CHANGELOG.md
  packages/rollout/package.json
Labels: READY TO REVIEW

#4638 chore: add changelog for @trezor/transport
  packages/transport/CHANGELOG.md
Labels: READY TO REVIEW

#4639 Revert "fix: add coingecko to allowed domains"
  packages/suite-desktop/src-electron/config.ts
Labels: READY TO REVIEW

#4641 fix(native): add missing intl dependency
  packages/suite-native/package.json
  yarn.lock
Labels: READY TO REVIEW

#4614 chore(deps): update cypress 9.1.1
  docker/docker-compose.suite-ci.yml
  docker/test-runner/Dockerfile
  packages/integration-tests/package.json
  packages/integration-tests/projects/suite-web/plugins/index.js
  yarn.lock
Labels: READY TO REVIEW

#4663 chore: connect 8.2.5-beta.1
  packages/suite/package.json
  yarn.lock
Labels: READY TO REVIEW

#4667 chore: fix missing @trezor/transport in native build
  packages/connect-iframe/package.json
Labels: READY TO REVIEW
