Repository trezor/trezor-suite, pull requests merged in 2021-05, with the labels that each got.

#3687 fix(suite): set useEmptyPassphrase to false after enabling passphrase…
  packages/suite/src/actions/recovery/recoveryActions.ts
  packages/suite/src/actions/settings/deviceSettingsActions.ts
Labels: READY TO REVIEW

#3699 fix(desktop): #3654 Clear desktop storage on app reset
  packages/suite-desktop/src-electron/index.d.ts
  packages/suite-desktop/src-electron/libs/constants.ts
  packages/suite-desktop/src-electron/libs/store.ts
  packages/suite-desktop/src-electron/modules/store.ts
  packages/suite-desktop/src-electron/preload.ts
  packages/suite/global.d.ts
  packages/suite/src/views/settings/index.tsx
Labels: READY TO REVIEW

#3681 Feature/safety checks warning
  packages/integration-tests/projects/suite-web/tests/suite/safety-checks-warning.test.ts
  packages/suite/src/components/suite/Banners/SafetyChecks.tsx
  packages/suite/src/components/suite/Banners/index.tsx
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW, Release

#3701 feat(invity): Implement WAITING_FOR_USER Buy status
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/Status/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/wallet/coinmarket/buyUtils.ts
  packages/suite/src/views/wallet/coinmarket/buy/detail/Detail/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/detail/components/WaitingForUser/index.tsx
Labels: READY TO REVIEW, Release

#3705 fix(dashboard): asset card in dark mode
  packages/suite/src/actions/suite/__fixtures__/suiteActions.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/views/dashboard/components/AssetsCard/components/AssetGrid/index.tsx
  packages/suite/src/views/dashboard/components/AssetsCard/index.tsx
Labels: READY TO REVIEW, Release

#3708 fix(suite): windows and linux desktop build (SSR)
  packages/suite/src/utils/suite/env.ts
Labels: Release

#3710 fix(desktop): workaround for black screen after closing fullscreen window on MacOS
  packages/suite-desktop/src-electron/modules/window-controls.ts
Labels: READY TO REVIEW

#3740 fix(invity): Exchange - Receiving address tooltip wording
  packages/suite-data/files/translations/en.json
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/SelectedOffer/components/VerifyAddress/index.tsx
Labels: READY TO REVIEW

#3768 fix: change suite-web dev server port
  packages/suite-web/package.json
  packages/suite-web/scripts/httpsServer.js
Labels: READY TO REVIEW

#3789 chore(suite): react-hook-form update
  packages/suite/package.json
  yarn.lock
Labels: READY TO REVIEW

#3780 fix(invity): Sell Crypto: functionality of the button "Get this Offer"
  packages/suite/src/hooks/wallet/useCoinmarketSellOffers.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/wallet/coinmarketSellOffers.ts
  packages/suite/src/views/wallet/coinmarket/sell/offers/Offers/List/Quote/index.tsx
Labels: READY TO REVIEW

#3788 fix(invity): Pending buy - double transaction ID
  packages/suite/src/views/wallet/coinmarket/buy/detail/Detail/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/detail/components/PaymentFailed/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/detail/components/WaitingForUser/index.tsx
Labels: READY TO REVIEW

#3794 feat(navigation): Updated Settings menu and Tor
  packages/components/src/components/Dropdown/index.stories.tsx
  packages/components/src/components/Dropdown/index.tsx
  packages/components/src/components/Icon/icons.ts
  packages/components/src/config/colors.ts
  packages/components/src/config/variables.ts
  packages/components/src/images/icons/app.svg
  packages/components/src/images/icons/arrow_right_long.svg
  packages/components/src/images/icons/coin.svg
  packages/components/src/images/icons/device.svg
  packages/components/src/images/icons/lightbulb.svg
  packages/integration-tests/projects/suite-web/tests/metadata/dropbox-api-errors.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/remembered-device.test.ts
  packages/integration-tests/projects/suite-web/tests/metadata/switching-providers.test.ts
  packages/suite/package.json
  packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem/index.tsx
  packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/NotificationsDropdown/index.tsx
  packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/SettingsDropdown/index.tsx
  packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/TooltipContentTor/index.tsx
  packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/TorDropdown/index.tsx
  packages/suite/src/components/suite/NavigationBar/components/NavigationActions/index.tsx
  packages/suite/src/components/suite/TransactionsGraph/components/RangeSelector/index.tsx
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#3814 chore(sentry): lower sampling rate
  packages/suite/src/config/suite/sentry.ts
Labels: READY TO REVIEW
