Repository trezor/trezor-suite, pull requests merged in 2021-02, with the labels that each got.

#3286 feat: more data analytics
  docs/misc/analytics.md
  packages/suite/src/actions/suite/__tests__/analyticsActions.test.ts
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/components/suite/modals/AddToken/index.tsx
  packages/suite/src/components/suite/modals/ReviewTransaction/index.tsx
  packages/suite/src/middlewares/suite/analyticsMiddleware.ts
  packages/suite/src/views/wallet/transactions/components/AccountEmpty/index.tsx
Labels: READY TO REVIEW, Release

#3319 fix: enable generation of source maps
  packages/suite-desktop/next.config.js
  packages/suite-web/next.config.js
Labels: READY TO REVIEW, Release

#3318 feat: add Carlos background for T1 and TT
  packages/suite-data/files/images/png/homescreens/t1/carlos.png
  packages/suite-data/files/images/png/homescreens/t2/carlos.png
  packages/suite/src/constants/suite/homescreens.ts
Labels: Release

#3324 chore: sync intl
  packages/suite-data/files/translations/en.json
Labels: READY TO REVIEW, Release

#3328 fix(transactions): pdf formatting and info
  packages/suite/src/actions/wallet/transactionActions.ts
  packages/suite/src/constants/suite/b64images.ts
  packages/suite/src/utils/wallet/exportTransactions.ts
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/Actions/components/ExportAction/index.tsx
Labels: READY TO REVIEW, Release

#3334 fix(transactions): update logo in export pdf
  packages/suite/src/constants/suite/b64images.ts
  packages/suite/src/utils/wallet/exportTransactions.ts
Labels: READY TO REVIEW

#3346 fix(suite): don't reset coin filter when adding account that belongs …
  packages/suite/src/components/suite/modals/AddAccount/components/AddAccountButton.tsx
Labels: READY TO REVIEW

#3345 fix(intl): plural form when there are multiple pending txs in the list
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/DayHeader/index.tsx
Labels: READY TO REVIEW

#3338 fix(suite): gas price overflow
  packages/suite/src/components/suite/modals/ReviewTransaction/components/Summary.tsx
Labels: READY TO REVIEW, Release

#3339 show RBF status for confirmed tx, remove RBF ON/OFF
  packages/suite/src/components/suite/modals/TransactionDetail/components/BasicDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/index.tsx
  packages/suite/src/utils/wallet/transactionUtils.ts
Labels: READY TO REVIEW, Release

#3343 fix: review modal for erc20 tokens
  packages/suite/src/components/suite/modals/ReviewTransaction/components/Summary.tsx
Labels: READY TO REVIEW, Release

#3302 fix(suite): make whole transaction heading row clickable
  packages/suite/src/components/wallet/TransactionItem/components/TransactionHeading/index.tsx
Labels: READY TO REVIEW

#3353 fix(suite-data): update tor binaries
  packages/suite-data/files/bin/tor/linux-x64/tor
  packages/suite-data/files/bin/tor/mac-x64/libevent-2.1.7.dylib
  packages/suite-data/files/bin/tor/mac-x64/tor
  packages/suite-data/files/bin/tor/win-x64/tor.exe
Labels: READY TO REVIEW, Release

#3349 Fix: feerate
  packages/suite/src/actions/wallet/send/sendFormBitcoinActions.ts
  packages/suite/src/components/suite/modals/TransactionDetail/components/ChangeFee/index.tsx
  packages/suite/src/components/wallet/Fees/components/FeeDetails.tsx
  packages/suite/src/hooks/wallet/form/useFees.ts
  packages/suite/src/hooks/wallet/useRbfForm.ts
  packages/suite/src/hooks/wallet/useSendForm.ts
  packages/suite/src/utils/wallet/transactionUtils.ts
Labels: READY TO REVIEW, Release

#3354 fix: auth only if device is not locked
  packages/suite/src/middlewares/wallet/discoveryMiddleware.ts
Labels: READY TO REVIEW, Release

#3356 chore(intl): consistency (Fee Level -> Fee rate)
  packages/suite/src/components/suite/modals/ReviewTransaction/components/Summary.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/BasicDetails/index.tsx
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#3357 fix(suite): review modal delivery time displays '0'
  packages/suite/src/components/suite/modals/ReviewTransaction/components/Summary.tsx
Labels: READY TO REVIEW

#3358 fix: Fee copy
  packages/suite/src/components/wallet/Fees/components/EstimatedMiningTime.tsx
  packages/suite/src/components/wallet/Fees/components/FeeCustom.tsx
  packages/suite/src/components/wallet/Fees/components/FeeDetails.tsx
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW, Release

#3290 Desktop: Disable auto updater if APPIMAGE is not set
  docs/packages/suite-desktop.md
  packages/suite-desktop/src-electron/__tests__/logger.test.ts
  packages/suite-desktop/src-electron/app.ts
  packages/suite-desktop/src-electron/config.ts
  packages/suite-desktop/src-electron/index.d.ts
  packages/suite-desktop/src-electron/libs/constants.ts
  packages/suite-desktop/src-electron/libs/http-receiver.ts
  packages/suite-desktop/src-electron/libs/info.ts
  packages/suite-desktop/src-electron/libs/logger.ts
  packages/suite-desktop/src-electron/libs/modules.ts
  packages/suite-desktop/src-electron/libs/processes/BaseProcess.ts
  packages/suite-desktop/src-electron/modules/analytics.ts
  packages/suite-desktop/src-electron/modules/auto-updater.ts
  packages/suite-desktop/src-electron/modules/bridge.ts
  packages/suite-desktop/src-electron/modules/event-logging/process.ts
  packages/suite-desktop/src-electron/modules/file-protocol.ts
  packages/suite-desktop/src-electron/modules/http-receiver.ts
  packages/suite-desktop/src-electron/modules/menu.ts
  packages/suite-desktop/src-electron/modules/metadata.ts
  packages/suite-desktop/src-electron/modules/tor.ts
  packages/suite-desktop/src-electron/preload.ts
  packages/suite-desktop/src-electron/tsconfig.json
  packages/suite-desktop/src/support/DesktopUpdater.tsx
  packages/suite/src/actions/suite/constants/desktopUpdateConstants.ts
  packages/suite/src/actions/suite/desktopUpdateActions.ts
  packages/suite/src/config/suite/features.ts
  packages/suite/src/reducers/suite/desktopUpdateReducer.ts
  packages/suite/src/views/settings/index.tsx
  tsconfig.json
Labels: READY TO REVIEW

#3315 chore(desktop): update electron to 11.2.1
  packages/suite-desktop/package.json
  yarn.lock
Labels: READY TO REVIEW

#3369 chore(suite): Custom FormattedDate component
  packages/suite-desktop/src/support/DesktopUpdater/Available.tsx
  packages/suite/src/components/suite/FormattedDate/index.tsx
  packages/suite/src/components/suite/Notifications/components/NotificationList/index.tsx
  packages/suite/src/components/suite/TransactionsGraph/components/CustomTooltipBase/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/AmountDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/BasicDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/ChangeFee/components/AffectedTransactions/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/BuyTransaction/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/ExchangeTransaction/index.tsx
  packages/suite/src/components/wallet/TransactionItem/components/TransactionTimestamp/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionSummary/components/SummaryCards/index.tsx
Labels: READY TO REVIEW

#3367 fix(suite): fiat rates error handling
  packages/suite/src/config/suite/sentry.ts
  packages/suite/src/services/coingecko.ts
Labels: READY TO REVIEW

#3400 fix(storage): Check if IDB is supported before db operation
  CHANGELOG.md
  packages/suite-storage/src/native/index.ts
  packages/suite-storage/src/web/index.ts
  packages/suite/src/actions/suite/__tests__/storageActions.test.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/support/tests/setupJest.ts
Labels: READY TO REVIEW

#3386 fix(desktop): add cooldown delay to process restart when exitting
  packages/suite-desktop/src-electron/libs/processes/BaseProcess.ts
Labels: READY TO REVIEW, no Changelog

#3387 fix(transactions): search optimization and incorrect pagination display for coin
  CHANGELOG.md
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/Actions/components/SearchAction/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx
Labels: READY TO REVIEW

#3410 updated Info
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: READY TO REVIEW

#3404 fix(suite-desktop): discovery progress bar not visible
  CHANGELOG.md
  packages/suite/src/components/wallet/DiscoveryProgress/index.tsx
Labels: READY TO REVIEW

#3418 fix(send): ETH erc20 estimated gas limit
  packages/suite/src/utils/wallet/sendFormUtils.ts
Labels: READY TO REVIEW

#3419 fix(suite-landing): text overflow in feature box
  packages/suite-web-landing/components/Feature/index.tsx
Labels: READY TO REVIEW

#3426 nix: increase node memory
  shell.nix
Labels: READY TO REVIEW

#3401 fix(fiatRates): use contract address to distinguish tokens with same symbol
  CHANGELOG.md
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/wallet/constants/fiatRatesConstants.ts
  packages/suite/src/actions/wallet/fiatRatesActions.ts
  packages/suite/src/components/suite/FiatValue/Container.ts
  packages/suite/src/components/suite/FiatValue/index.tsx
  packages/suite/src/config/suite/fiat.ts
  packages/suite/src/middlewares/wallet/fiatRatesMiddleware.ts
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/reducers/wallet/fiatRatesReducer.ts
  packages/suite/src/services/coingecko.ts
  packages/suite/src/storage/CHANGELOG.md
  packages/suite/src/storage/index.ts
  packages/suite/src/storage/migrations/index.ts
  packages/suite/src/types/wallet/fiatRates.ts
  packages/suite/src/types/wallet/index.ts
  packages/suite/src/views/wallet/transactions/components/TokenList/index.tsx
Labels: READY TO REVIEW

#3449 fix(suite-web): disallow Google Chrome to offer the page translation
  packages/suite-web/pages/_document.tsx
Labels: READY TO REVIEW

#3467 fix(suite-desktop): enforce single instance policy
  packages/suite-desktop/src-electron/app.ts
Labels: READY TO REVIEW

#3408 chore(copy): inform user that xrp is supported only on TT
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/coins/components/CoinsGroup/index.tsx
Labels: READY TO REVIEW

#3447 fix(send): reset send context on account change
  packages/suite/src/hooks/wallet/useSendForm.ts
Labels: READY TO REVIEW

#3444 feat(suite): hide graph and security steps
  packages/suite/src/actions/suite/__fixtures__/suiteActions.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/dashboard/components/PortfolioCard/components/Header/index.tsx
  packages/suite/src/views/dashboard/components/PortfolioCard/index.tsx
  packages/suite/src/views/dashboard/components/SecurityFeatures/index.tsx
Labels: READY TO REVIEW

#3416 chore(suite): format tx.details and refactor transaction details modal
  packages/suite/src/actions/wallet/__fixtures__/blockchainActions.ts
  packages/suite/src/actions/wallet/__tests__/transactionActions.test.ts
  packages/suite/src/components/suite/modals/TransactionDetail/components/AdvancedDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/AmountDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/BasicDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/IODetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/index.tsx
  packages/suite/src/storage/CHANGELOG.md
  packages/suite/src/storage/index.ts
  packages/suite/src/storage/migrations/index.ts
  packages/suite/src/support/tests/setupJest.ts
  packages/suite/src/utils/wallet/__fixtures__/transactionUtils.ts
  packages/suite/src/utils/wallet/transactionUtils.ts
Labels: READY TO REVIEW

#3462 fix(suite): handle blocked db upgrade
  CHANGELOG.md
  packages/suite-data/files/translations/en.json
  packages/suite-storage/src/native/index.ts
  packages/suite-storage/src/web/index.ts
  packages/suite/src/actions/suite/constants/suiteConstants.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/components/suite/Preloader/components/DatabaseUpgradeModal/index.tsx
  packages/suite/src/components/suite/Preloader/components/InitialLoading/index.tsx
  packages/suite/src/components/suite/Preloader/index.tsx
  packages/suite/src/config/suite/sentry.ts
  packages/suite/src/middlewares/suite/suiteMiddleware.ts
  packages/suite/src/reducers/suite/storageReducer.ts
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#3453 fix(suite): include tokens in getAccountFiatBalance
  CHANGELOG.md
  packages/suite/src/utils/wallet/accountUtils.ts
Labels: READY TO REVIEW

#3473 fix(analytics): correctly fire suite-ready event even if we don't hav…
  packages/suite/src/middlewares/suite/analyticsMiddleware.ts
Labels: READY TO REVIEW

#3481 fix(suite): specify img width to prevent img expansion
  packages/suite/src/components/suite/images/ConnectDeviceImage/index.tsx
  packages/suite/src/components/suite/modals/WipeDevice/index.tsx
  packages/suite/src/views/backup/index.tsx
  packages/suite/src/views/onboarding/unexpected-states/components/IsNotNewDevice.tsx
  packages/suite/src/views/onboarding/unexpected-states/components/Reconnect.tsx
  packages/suite/src/views/suite/device-connect/index.tsx
Labels: READY TO REVIEW

#3476 design: Dropdown dark background adjusted
  packages/components/src/components/Dropdown/index.tsx
Labels: READY TO REVIEW
