Repository trezor/trezor-suite, pull requests merged in 2021-10, with the labels that each got.

#4234 fix(suite): fix firmware version & changelog UI
  packages/suite/src/components/firmware/FirmwareOffer.tsx
  packages/suite/src/utils/suite/__fixtures__/device.ts
  packages/suite/src/utils/suite/__tests__/device.test.ts
  packages/suite/src/utils/suite/device.ts
Labels: READY TO REVIEW

#4320 fix(blockchain-link): revert adding peer dependencies
  package.json
  packages/blockchain-link/webpack/workers.node.babel.js
  yarn.lock
Labels: READY TO REVIEW

#4266 fix(suite): fix graph tooltip z-index
  packages/suite/src/components/suite/TransactionsGraph/index.tsx
Labels: READY TO REVIEW, Release

#4325 fix: backport-en messages.ts instead of rawMessages
  packages/suite-data/scripts/backport-en.ts
  packages/suite/package.json
  packages/suite/src/support/messages.ts
  packages/suite/src/support/rawMessages.ts
Labels: READY TO REVIEW

#4329 feat(uri-protocol): allow bitcoin: without specific amount
  docs/features/protocols/coin_handler.md
  packages/suite/src/actions/suite/__tests__/protocolActions.test.ts
  packages/suite/src/actions/suite/protocolActions.ts
  packages/suite/src/components/suite/hocNotification/components/withCoinProtocolScheme.tsx
  packages/suite/src/hooks/wallet/useSendForm.ts
  packages/suite/src/reducers/suite/notificationReducer.ts
  packages/suite/src/reducers/suite/protocolReducer.ts
  packages/suite/src/support/suite/Protocol.tsx
  packages/suite/src/utils/suite/__tests__/parseUri.test.ts
  packages/suite/src/utils/suite/parseUri.ts
Labels: READY TO REVIEW, Release

#4326 feat: new translations
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/ro.json
Labels: READY TO REVIEW, Release

#4328 update available languages
  packages/suite/src/config/suite/languages.ts
Labels: READY TO REVIEW, Release

#4331 fix(e2e) Add passphrase to get new account
  packages/integration-tests/projects/suite-web/tests/suite/new-account-message.test.ts
Labels: READY TO REVIEW

#4330 fix: don't console.error MISSING_TRANSLATION errors
  packages/suite/src/support/suite/ConnectedIntlProvider.tsx
Labels: READY TO REVIEW, Release

#4343 fix(suite): check ref for field to avoid error
  packages/suite/src/hooks/wallet/sign-verify/useSignVerifyForm.ts
Labels: Bug, READY TO REVIEW, Release
