Repository trezor/trezor-suite, pull requests merged in 2021-04, with the labels that each got.

#3593 docs: add info on how to run cypress on macOS
  docs/tests/e2e-web.md
Labels: READY TO REVIEW

#3595 fix(translations): corrections and minor nitpicks
  packages/suite-data/files/translations/en.json
Labels: Release

#3581 fix(invity): Spend - transaction not shown in Trade tab history
  packages/suite-data/files/translations/en.json
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/wallet/__tests__/coinmarketSpendActions.test.ts
  packages/suite/src/actions/wallet/coinmarketBuyActions.ts
  packages/suite/src/actions/wallet/coinmarketExchangeActions.ts
  packages/suite/src/actions/wallet/coinmarketSellActions.ts
  packages/suite/src/actions/wallet/coinmarketSpendActions.ts
  packages/suite/src/actions/wallet/constants/coinmarketBuyConstants.ts
  packages/suite/src/actions/wallet/constants/coinmarketCommonConstants.ts
  packages/suite/src/actions/wallet/constants/coinmarketExchangeConstants.ts
  packages/suite/src/components/wallet/CoinmarketBuyOfferInfo/index.tsx
  packages/suite/src/components/wallet/CoinmarketExchangeOfferInfo/index.tsx
  packages/suite/src/components/wallet/CoinmarketExchangeProviderInfo/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/BuyTransaction/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/ExchangeTransaction/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/SpendTransaction/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/Status/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/index.tsx
  packages/suite/src/components/wallet/CoinmarketProviderInfo/index.tsx
  packages/suite/src/components/wallet/index.tsx
  packages/suite/src/hooks/wallet/useCoinmarket.ts
  packages/suite/src/hooks/wallet/useCoinmarketBuyDetail.ts
  packages/suite/src/hooks/wallet/useCoinmarketExchangeDetail.ts
  packages/suite/src/hooks/wallet/useCoinmarketSpend.ts
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/reducers/wallet/__tests__/coinmarketReducer.test.ts
  packages/suite/src/reducers/wallet/coinmarketReducer.ts
  packages/suite/src/storage/definitions.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/wallet/coinmarketBuyDetail.ts
  packages/suite/src/types/wallet/coinmarketCommonTypes.ts
  packages/suite/src/types/wallet/coinmarketExchangeDetail.ts
  packages/suite/src/types/wallet/index.ts
  packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/List/Quote/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/List/Quote/index.tsx
Labels: READY TO REVIEW

#3600 chore(intl): sync crowdin
  packages/suite-data/files/translations/en.json
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#3509 fix(transactions): search on multiple outputs
  packages/suite/src/utils/wallet/transactionUtils.ts
Labels: READY TO REVIEW, Release

#3601 fix(tor): news/blog links properly update to tor links
  packages/suite/src/views/dashboard/components/NewsFeed/index.tsx
Labels: READY TO REVIEW, Release

#3604 fix(suite): missing space between the device name and an account name when sending tx
  packages/suite/src/components/suite/Labeling/components/Account/index.tsx
Labels: READY TO REVIEW

#3602 fix(tor): kill tor process on app close
  packages/suite-desktop/src-electron/modules/tor.ts
Labels: READY TO REVIEW, Release

#3605 fix(suite): formatting of token amount in transaction confirm dialog
  packages/suite/src/components/suite/modals/ReviewTransaction/components/Summary.tsx
Labels: READY TO REVIEW

#3606 fix(onboarding): add webusb pairing option after device is restarted …
  packages/suite/src/components/firmware/FirmwareProgress.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/firmware/index.ts
Labels: READY TO REVIEW

#3537 feat(suite-desktop): add renderer crash recovery system
  packages/suite-desktop/src-electron/libs/constants.ts
  packages/suite-desktop/src-electron/modules/crash-recover.ts
  packages/suite-desktop/src-electron/modules/event-logging/contents.ts
Labels: READY TO REVIEW

#3611 fix(invity): exchange crypto switch of fee level does not update amount
  packages/suite/src/hooks/wallet/form/useFees.ts
  packages/suite/src/hooks/wallet/useCoinmarketExchangeForm.ts
Labels: +Invity, READY TO REVIEW, Release

#3632 fix(auto-updater): skipped updates return now correct update to UI
  packages/suite-desktop/src-electron/modules/auto-updater.ts
Labels: READY TO REVIEW

#3642 fix(desktop): incorrect reset for auto-updater manual check flag
  packages/suite-desktop/src-electron/modules/auto-updater.ts
Labels: READY TO REVIEW

#3638 fix(send): bech32 address validation function
  packages/suite/src/utils/wallet/__tests__/validation.test.ts
  packages/suite/src/utils/wallet/validation.ts
Labels: READY TO REVIEW

#3637 chore: update trezor-connect@8.1.26
  packages/suite-data/files/connect/data/firmware/2/releases.json
  packages/suite-data/files/connect/data/messages/messages.json
  packages/suite-data/files/connect/iframe.html
  packages/suite-data/files/connect/js/iframe.66b893e57a1ae1dd871e.js
  packages/suite-data/files/connect/js/iframe.8971db8994d47a835970.js
  packages/suite-data/files/connect/workers/ripple-worker.5c4760bb43dccf440277.js
  packages/suite-data/files/connect/workers/ripple-worker.e8db46d6b3e15892b80e.js
  packages/suite/package.json
  patches/trezor-connect+8.1.25-extended.patch
  yarn.lock
Labels: READY TO REVIEW

#3646 feat(desktop): add mock for modules
  docs/packages/suite-desktop.md
  packages/suite-desktop/package.json
  packages/suite-desktop/scripts/build.js
  packages/suite-desktop/src-electron/libs/constants.ts
  packages/suite-desktop/src-electron/mocks/electron-updater.ts
  packages/suite-desktop/src-electron/modules/auto-updater.ts
Labels: READY TO REVIEW

#3674 fix(news-api): return proper error statusCode, change user agent
  packages/news-api/src/config.ts
  packages/news-api/src/index.ts
  packages/news-api/src/server.ts
Labels: READY TO REVIEW

#3673 fix(send): do not show "data" in case of ERC20 tx replacement
  packages/suite/src/components/suite/modals/ReviewTransaction/index.tsx
Labels: READY TO REVIEW

#3676 fix(news-api): convert limit param to integer
  packages/news-api/src/index.ts
  packages/news-api/src/server.ts
Labels: READY TO REVIEW

#3680 fix(accounts): account scroll window glitch
  packages/suite/src/components/wallet/AccountsMenu/components/AnimationWrapper/index.tsx
Labels: READY TO REVIEW

#3563 feat(tooltips): UI/UX improved, CSS refactored, rich content support
  CHANGELOG.md
  packages/components/package.json
  packages/components/src/components/Tooltip/all.stories.tsx
  packages/components/src/components/Tooltip/index.stories.tsx
  packages/components/src/components/Tooltip/index.tsx
  packages/components/src/components/Tooltip/tippy.style.ts
  packages/components/src/index.ts
  packages/components/src/support/Story.tsx
  packages/suite-web-landing/support/styles.ts
  packages/suite/src/components/suite/NoRatesTooltip/index.tsx
  packages/suite/src/components/suite/QuestionTooltip/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/AddWalletButton/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/ColHeader/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/WalletInstance/index.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/AddAccountButton.tsx
  packages/suite/src/components/suite/modals/AddToken/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/support/suite/styles/global.ts
  packages/suite/src/views/dashboard/components/PortfolioCard/index.tsx
  packages/suite/src/views/wallet/send/components/Options/components/BitcoinOptions/index.tsx
  packages/suite/src/views/wallet/send/components/Options/components/EthereumOptions/index.tsx
  packages/suite/src/views/wallet/send/components/Options/components/RippleOptions/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/OpReturn/index.tsx
  packages/suite/src/views/wallet/send/components/Raw/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/Actions/components/SearchAction/index.tsx
  yarn.lock
Labels: READY TO REVIEW
