Repository trezor/trezor-suite, pull requests merged in 2021-08, with the labels that each got.

#4089 fix(suite): adjust z-index
  packages/components/src/components/Dropdown/index.tsx
  packages/suite/src/components/suite/AppNavigation/index.tsx
  packages/suite/src/components/suite/AppNavigationPanel/components/AppNavigationPanelInner.tsx
Labels: READY TO REVIEW

#4078 feat: add es.json
  packages/suite-data/files/translations/es.json
  packages/suite/src/config/suite/languages.ts
  packages/suite/src/views/settings/index.tsx
Labels: READY TO REVIEW

#4083 feat(suite): #4061 set language for translation
  packages/suite-native/src/actions/settings/languageActions.ts
  packages/suite/src/actions/settings/languageActions.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/components/suite/Translation/components/HelperTooltip/index.tsx
  packages/suite/src/config/suite/languages.ts
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/utils/suite/l10n.ts
  packages/suite/src/views/settings/debug/index.tsx
  packages/suite/src/views/settings/index.tsx
Labels: Release

#3867 feat: add metadata labels in exports
  packages/suite/src/actions/wallet/transactionActions.ts
  packages/suite/src/utils/wallet/exportTransactions.ts
Labels: READY TO REVIEW, Release

#4098 feat(suite): navigation hover states
  packages/components/src/components/HoverAnimation/index.tsx
  packages/components/src/components/buttons/Button/index.tsx
  packages/components/src/config/colors.ts
  packages/components/src/index.ts
  packages/suite/src/components/suite/AppNavigation/index.tsx
  packages/suite/src/components/suite/NavigationBar/components/MainNavigation/index.tsx
  packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem/index.tsx
  packages/suite/src/components/suite/NavigationBar/index.tsx
  packages/suite/src/components/suite/Settings/components/TextColumn.tsx
  packages/suite/src/views/wallet/details/index.tsx
Labels: READY TO MERGE, Release

#4097 fix(suite): adjust z-index
  packages/suite/src/components/suite/AppNavigation/index.tsx
  packages/suite/src/components/wallet/AccountsMenu/index.tsx
Labels: READY TO MERGE, READY TO REVIEW, Release

#4105 feat(suite): use current backend url if connected/defined
  packages/suite/src/components/suite/modals/TransactionDetail/components/AdvancedDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/BasicDetails/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/ChainedTxs/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/index.tsx
  packages/suite/src/reducers/wallet/blockchainReducer.ts
  packages/suite/src/utils/wallet/transactionUtils.ts
Labels: Feature request, READY TO REVIEW

#4117 fix(suite): webpack hot module dev settings for Firefox
  packages/suite-build/configs/dev.webpack.config.ts
Labels: READY TO REVIEW, Release

#4113 fix(suite): fixed header when reboot automatically
  packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx
  packages/suite/src/support/messages.ts
Labels: Release

#4125 chore: sync es.json
  packages/suite-data/files/translations/es.json
Labels: READY TO REVIEW, Release

#4126 chore: sync en.json
  packages/suite-data/files/translations/en.json
Labels: READY TO REVIEW, Release

#4109 fix(suite): do not update passphrase mode on passphrase confirmation
  packages/suite/src/actions/suite/modalActions.ts
Labels: READY TO REVIEW

#4131 feat(suite): #4130 add more translation languages
  packages/suite/src/config/suite/languages.ts
Labels: Release

#4155 fix(suite): do not offer intermediary FW for Model T
  packages/rollout/src/index.ts
  packages/suite/src/actions/firmware/firmwareActions.ts
  packages/suite/src/utils/suite/device.ts
Labels: READY TO REVIEW

#4151 feat(suite): change DeviceStatus__OuterCircle color
  packages/components/src/config/colors.ts
Labels: READY TO REVIEW

#4140 fix(invity): Trade/Exchange - Crypto input text validation
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Inputs/index.tsx
Labels: READY TO REVIEW

#4164 fix(suite): fix intermediary FW installation loop
  packages/suite/src/reducers/firmware/firmwareReducer.ts
Labels: READY TO REVIEW

#4163 chore: make TR_PENDING_TX_HEADING key more flexible
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#4136 feat(invity): coinmarket input validity state improvement
  packages/components/src/components/form/Select/index.tsx
  packages/suite/src/hooks/wallet/useCoinmarketSellForm.ts
  packages/suite/src/types/wallet/coinmarketSellForm.ts
  packages/suite/src/views/wallet/coinmarket/buy/components/BuyForm/Inputs/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/FiatInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/ReceiveCryptoSelect/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Inputs/CryptoInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Inputs/FiatInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Inputs/index.tsx
Labels: READY TO REVIEW

#4198 fix(suite): Pin request code detection
  packages/suite/src/components/suite/PinMatrix/index.tsx
  packages/suite/src/components/suite/modals/Pin/index.tsx
Labels: READY TO REVIEW, Release

#4197 fix(invity): coinmarket load invity data if doesn't exist
  packages/suite/src/hooks/wallet/useCoinmarketBuyForm.ts
  packages/suite/src/hooks/wallet/useCoinmarketExchangeForm.ts
  packages/suite/src/hooks/wallet/useCoinmarketSellForm.ts
  packages/suite/src/hooks/wallet/useCoinmarketSpend.ts
Labels: READY TO REVIEW

#4088 fix(bridge): do not log error when bridge is not running
  packages/suite-desktop/src-electron/libs/processes/BridgeProcess.ts
Labels: READY TO REVIEW

#4187 fix explorer url generation
  packages/suite/src/reducers/wallet/blockchainReducer.ts
Labels: Release, READY TO MERGE
