Repository trezor/trezor-suite, pull requests merged in 2021-07, with the labels that each got.

#3953 Fix/feedback empty inputs
  packages/suite/src/views/guide/Feedback.tsx
Labels: READY TO REVIEW, Release

#3959 fix(suite landing page): change feedback url
  packages/suite-web-landing/components/Layout/index.tsx
Labels: READY TO MERGE, READY TO REVIEW, Release

#3963 fix(send): Ethereum address checksum validation
  packages/suite-data/files/translations/en.json
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/send/components/Outputs/components/Address/components/Convert/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Address/index.tsx
Labels: READY TO REVIEW, Release

#3980 fix(suite): redact Toast notification error
  packages/suite-data/files/translations/en.json
  packages/suite/src/middlewares/suite/toastMiddleware.ts
  packages/suite/src/reducers/suite/notificationReducer.ts
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW, Release

#3984 chore: sync with crowdin
  packages/suite-data/files/translations/en.json
Labels: READY TO REVIEW, Release

#3985 fix(suite): #3983 Guide icon changed to 2D style
  packages/suite-data/files/images/suite/lamp.png
  packages/suite-data/files/images/suite/lightbulb.svg
  packages/suite/src/components/guide/GuideButton.tsx
Labels: READY TO REVIEW, Release

#3956 Fix/3911 intermediary for older devices quick
  packages/suite/src/components/firmware/FirmwareInitial.tsx
  packages/suite/src/components/firmware/FirmwareInstallation.tsx
  packages/suite/src/utils/suite/device.ts
Labels: READY TO REVIEW, Release

#3961 fix(suite): fix logic of description selection
  packages/suite/src/components/firmware/FirmwareInitial.tsx
Labels: READY TO REVIEW, Release

#3916 Fix font properties
  packages/integration-tests/projects/suite-web/snapshots/backup/t2-success.test.ts/backup-confirm-security-screen.snap.png
  packages/integration-tests/projects/suite-web/snapshots/browser/edge.test.ts/browser is not supported at all.snap.png
  packages/integration-tests/projects/suite-web/snapshots/browser/iphone-chrome.test.ts/no webusb support.snap.png
  packages/integration-tests/projects/suite-web/snapshots/browser/outdated-chrome.test.ts/chrome is supported but outdated.snap.png
  packages/integration-tests/projects/suite-web/snapshots/browser/outdated-firefox.test.ts/firefox is supported but outdated.snap.png
  packages/integration-tests/projects/suite-web/snapshots/firmware/firmware.test.ts/check-seed.snap.png
  packages/integration-tests/projects/suite-web/snapshots/firmware/firmware.test.ts/outdated notification banner.snap.png
  packages/integration-tests/projects/suite-web/snapshots/onboarding/firmware-update.test.ts/firmware-confirm fingerprint.snap.png
  packages/integration-tests/projects/suite-web/snapshots/settings/log.test.ts/Log -- open log modal.snap.png
  packages/integration-tests/projects/suite-web/snapshots/settings/log.test.ts/Log -- there is a dropdown menu in settings that opens modal with application logs.snap.png
  packages/integration-tests/projects/suite-web/snapshots/settings/log.test.ts/dropdown expanded.snap.png
  packages/integration-tests/projects/suite-web/snapshots/settings/t1-device-settings.test.ts/Device settings -- t1 - pin mismatch.snap.png
  packages/integration-tests/projects/suite-web/snapshots/settings/t1-device-settings.test.ts/T1 - Device settings -- pin mismatch.snap.png
  packages/integration-tests/projects/suite-web/snapshots/suite/bridge.test.ts/bridge modal.snap.png
  packages/integration-tests/projects/suite-web/snapshots/suite/bridge.test.ts/udev rules modal.snap.png
  packages/integration-tests/projects/suite-web/snapshots/suite/connecting-devices.test.ts/seedless.snap.png
  packages/integration-tests/projects/suite-web/snapshots/suite/connecting-devices.test.ts/unreadable.snap.png
  packages/integration-tests/projects/suite-web/snapshots/suite/version-page.test.ts/There is a hidden route (not accessible in UI) -- version.snap.png
  packages/suite/src/components/suite/AppNavigation/index.tsx
  packages/suite/src/components/suite/AppNavigationPanel/index.tsx
  packages/suite/src/components/suite/Settings/components/ActionColumn.tsx
  packages/suite/src/components/suite/Settings/components/Section.tsx
  packages/suite/src/components/suite/Settings/components/TextColumn.tsx
  packages/suite/src/constants/suite/layout.ts
Labels: Release

#3979 fix(suite): distinguish Unreadable device in PrerequisitesGuide
  packages/suite/src/components/suite/Preloader/__tests__/Preloader.test.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceConnect.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceUnreadable.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/index.tsx
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW, Release

#3946 chore: autoupdate finetuning
  packages/suite-desktop/src-electron/index.d.ts
  packages/suite-desktop/src-electron/modules/auto-updater.ts
  packages/suite-desktop/src-electron/preload.ts
  packages/suite-desktop/src/support/DesktopUpdater.tsx
  packages/suite/src/actions/suite/desktopUpdateActions.ts
  packages/suite/src/components/suite/hocNotification/index.tsx
  packages/suite/src/reducers/suite/notificationReducer.ts
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW, Release

#3996 chore: Sync with Crowdin
  packages/suite-data/files/translations/en.json
Labels: READY TO REVIEW, Release

#3997 fix: align index and start page of suite website
  packages/suite-data/files/translations/en.json
Labels: READY TO REVIEW, Release

#3974 chore: #3202 bump electron-updater package
  patches/electron-updater+4.3.5.patch
  yarn.lock
Labels: READY TO REVIEW

#3998 fix: after update notification only for the first run of the new version
  packages/suite-desktop/src-electron/index.d.ts
  packages/suite-desktop/src-electron/modules/auto-updater.ts
Labels: READY TO REVIEW, Release

#4005 feat(translations): Sync with Crowdin
  packages/suite-data/files/translations/en.json
Labels: READY TO REVIEW, Release

#4012 feat(guide): Update GitBook revision
  packages/suite-data/src/guide/constants.ts
Labels: READY TO REVIEW, Release

#4017 fix(suite): #4011 paths to onboarding videos fixed
  packages/suite/src/components/onboarding/DeviceAnimation/index.tsx
Labels: Bug, High priority, Release

#4015 fix(suite): 3925 stop firing FiatRatesFetchError completely
  packages/suite/src/config/suite/sentry.ts
  packages/suite/src/services/coingecko.ts
Labels: READY TO REVIEW

#4025 chore: rebuild trezor-connect@8.1.29-beta.3
  packages/suite-data/files/connect/iframe.html
  packages/suite-data/files/connect/js/iframe.81af7ed3a8f57d21df77.js
Labels: Release

#4028 feat(guide): Update GitBook revision
  packages/suite-data/src/guide/constants.ts
Labels: Release

#4026 fix(landing-page): use absolute path to make it work on both /index and /start pages
  packages/suite-web-landing/components/Download/index.tsx
  packages/suite-web-landing/components/Layout/index.tsx
  packages/suite-web-landing/pages/index.tsx
  packages/suite-web-landing/pages/start.tsx
Labels: Release

#4033 fix(e2e): skip user-env websocket connection if already connected
  packages/integration-tests/projects/suite-web/plugins/websocket-client.js
Labels: READY TO REVIEW

#3935 docs: Improve blockchain-link README
  packages/blockchain-link/README.md
  packages/blockchain-link/src/index.ts
Labels: READY TO REVIEW

#4030 chore(docs): how to add new analytics event
  docs/misc/analytics.md
Labels: READY TO REVIEW

#4050 fix(suite): failing preloader udev test on macOS
  packages/suite/src/components/suite/Preloader/__tests__/Preloader.test.tsx
Labels: READY TO REVIEW

#4056 fix(suite): 3724 Add Account modal: handle empty arrays of inactive coins
  packages/suite/src/components/suite/modals/AddAccount/components/EnableNetwork.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/MoreCoins.tsx
  packages/suite/src/components/suite/modals/AddAccount/index.tsx
Labels: READY TO REVIEW

#4018 fix(suite): prevent error Cannot read property blockHeight of undefined
  packages/suite/src/utils/wallet/transactionUtils.ts
Labels: READY TO REVIEW

#4081 chore(suite-data): update tor binaries
  packages/suite-data/files/bin/tor/linux-x64/libcrypto.so.1.1
  packages/suite-data/files/bin/tor/linux-x64/libevent-2.1.so.7
  packages/suite-data/files/bin/tor/linux-x64/libssl.so.1.1
  packages/suite-data/files/bin/tor/linux-x64/tor
  packages/suite-data/files/bin/tor/mac-x64/libevent-2.1.7.dylib
  packages/suite-data/files/bin/tor/mac-x64/tor
  packages/suite-data/files/bin/tor/win-x64/libcrypto-1_1-x64.dll
  packages/suite-data/files/bin/tor/win-x64/libevent-2-1-7.dll
  packages/suite-data/files/bin/tor/win-x64/libevent_core-2-1-7.dll
  packages/suite-data/files/bin/tor/win-x64/libevent_extra-2-1-7.dll
  packages/suite-data/files/bin/tor/win-x64/libgcc_s_seh-1.dll
  packages/suite-data/files/bin/tor/win-x64/libssl-1_1-x64.dll
  packages/suite-data/files/bin/tor/win-x64/libssp-0.dll
  packages/suite-data/files/bin/tor/win-x64/libwinpthread-1.dll
  packages/suite-data/files/bin/tor/win-x64/tor.exe
  packages/suite-data/files/bin/tor/win-x64/zlib1.dll
Labels: Release
