Repository trezor/trezor-suite, pull requests merged in 2021-09, with the labels that each got.

#4203 fix(onboarding): fix recovery persistence
  packages/integration-tests/projects/suite-web/tests/onboarding/t2-recovery-persistence.test.ts
  packages/suite/src/actions/suite/__tests__/analyticsActions.test.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/middlewares/recovery/recoveryMiddleware.ts
  packages/suite/src/reducers/suite/analyticsReducer.ts
  packages/suite/src/views/onboarding/steps/Welcome/components/PreOnboardingSetup/DataAnalytics.tsx
Labels: READY TO REVIEW, Release

#4213 fix(suite): allow to exit Crowdin if not logged
  packages/suite-web/src/static/index.html
Labels: Bug, Release

#4219 fix(suite,landing): fix resolution of static path
  packages/suite/src/utils/suite/__tests__/build.test.ts
  packages/suite/src/utils/suite/build.ts
Labels: READY TO REVIEW, Release

#4229 chore(docs): update info how to add new FW binaries
  docs/releases/adding-new-firmwares.md
Labels: READY TO REVIEW

#4204 feat(invity): successful sell trade fixed rate message
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/sell/detail/components/PaymentSuccessful/index.tsx
Labels: READY TO REVIEW

#4235 fix(rbf): exclude utxo generated by tx to be replaced
  packages/suite/src/hooks/wallet/__fixtures__/useRbfForm.ts
  packages/suite/src/hooks/wallet/useRbfForm.ts
Labels: READY TO REVIEW

#4253 feat(invity): coinmarket: sort fraction buttons by ascending value
  packages/suite/src/components/wallet/CoinMarketFractionButtons/index.tsx
Labels: READY TO REVIEW

#4086 chore: backport en.json
  packages/suite-data/scripts/backport-en.ts
  packages/suite/package.json
  packages/suite/src/support/messages.ts
  packages/suite/src/support/rawMessages.ts
Labels: READY TO REVIEW

#4256 chore: update cypress version to 8.3.0
  docker/docker-compose.suite-ci.yml
  docker/test-runner/Dockerfile
  packages/integration-tests/package.json
  packages/integration-tests/projects/suite-web/support/commands.ts
  packages/integration-tests/projects/suite-web/tests/metadata/wallet-metadata.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t1-create-wallet.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/analytics.test.ts
  yarn.lock
Labels: READY TO REVIEW

#4263 chore(connect-common): add missing firmware binary 2.1.1
  docs/releases/adding-new-firmwares.md
  packages/connect-common/files/firmware/2/trezor-2.1.1.bin
Labels: READY TO REVIEW, Release

#4260 fix: align rotation buttons
  packages/suite/src/views/settings/device/index.tsx
Labels: READY TO REVIEW

#4211 feat(invity): coinmarket UI loading state improvement
  packages/suite/src/views/wallet/coinmarket/buy/components/BuyForm/Footer/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/components/BuyForm/Inputs/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/components/BuyForm/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Footer/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/index.tsx
  packages/suite/src/views/wallet/coinmarket/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Footer/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Inputs/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/index.tsx
  packages/suite/src/views/wallet/coinmarket/skeleton/index.tsx
  packages/suite/src/views/wallet/coinmarket/spend/components/Spend/index.tsx
Labels: READY TO REVIEW

#4284 feat(msg-system): inform users about broken autoupdater on 21.9.1
  packages/suite-data/src/message-system/config/config.v1.json
Labels: READY TO REVIEW, HIGH

#4290 tests(suite): fix failing unit tests
  packages/suite/src/actions/suite/__tests__/storageActions.test.ts
  packages/suite/src/hooks/wallet/__tests__/useRbfForm.test.tsx
  packages/suite/src/support/tests/hooksHelper.tsx
Labels: READY TO REVIEW

#4265 test(e2e): add export transactions test
  packages/integration-tests/projects/suite-web/cypress.json
  packages/integration-tests/projects/suite-web/plugins/index.js
  packages/integration-tests/projects/suite-web/run_tests.js
  packages/integration-tests/projects/suite-web/tests/wallet/export-transactions.test.ts
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/Actions/components/ExportAction/index.tsx
Labels: READY TO REVIEW

#4294 chore: update e2e dependencies
  packages/integration-tests/package.json
  yarn.lock
Labels: READY TO REVIEW

#4269 fix(add wallet tooltip): show tooltip if device disconnected
  packages/components/src/components/Tooltip/TooltipConditional.tsx
  packages/components/src/components/Tooltip/index.tsx
  packages/components/src/index.ts
  packages/suite/src/components/suite/CoinsGroup/CoinsList.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/AddWalletButton/index.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/AddAccountButton.tsx
Labels: READY TO MERGE

#4298 experiment with github actions
  .github/workflows/validation.yml
  ci/build.yml
  docker/docker-compose.suite-ci.yml
Labels: READY TO REVIEW

#4293 chore: introduce bounty e2e group
  ci/test.yml
  packages/integration-tests/projects/suite-web/tests/onboarding/t1-recovery-advanced.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/t1-device-settings.test.ts
Labels: READY TO REVIEW

#4310 fix(suite-desktop): buffer overload of spawned process (bridge, tor)
  packages/suite-desktop/src-electron/libs/processes/BaseProcess.ts
Labels: READY TO REVIEW

#4311 chore(suite-build): remove blazingly "fast" builds using RAM disk
  docker/docker-compose.suite-base.yml
  packages/suite-build/configs/dev.webpack.config.ts
Labels: READY TO REVIEW
