Repository trezor/trezor-suite, pull requests merged in 2022-08, with the labels that each got.

#5886 feat(mobile): Add system option to theme picker
  suite-native/app/ios/Podfile.lock
  suite-native/module-settings/src/components/ColorSchemePicker.tsx
  suite-native/module-settings/src/components/ColorSchemePickerItem.tsx
Labels: mobile-app

#5745 test(e2e): sign and verify Ethereum
  packages/integration-tests/projects/suite-web/tests/wallet/sign-and-verify-eth.test.ts
Labels: e2e

#5906 fix(suite): display wallet label in WalletLabeling
  packages/suite/src/components/suite/Labeling/components/WalletLabeling.tsx
  packages/suite/src/components/suite/NavigationBar/components/DeviceSelector/index.tsx
Labels: bug, labelling

#5901 fix(suite): display validation status during fw installation
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/firmware/index.ts
  packages/suite/src/views/firmware/index.tsx
  packages/suite/src/views/onboarding/steps/Firmware/index.tsx
Labels: bug, onboarding

#5908 Crowdin translations update
  packages/suite-data/files/translations/af.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/uk.json
Labels: release, translations

#5910 feat(coinmarket): new payment methods (Pix and Pay4Fun)
  packages/suite/src/support/messages.ts
Labels: READY FOR REVIEW, +Invity

#5913 fix(sentry): get back config utils to sentry config to prevent window reference error
  packages/suite/src/config/suite/sentry.ts
  packages/suite/src/utils/suite/sentry.ts
Labels: release

#5746 test(e2e): fixup of Sign and Verify Bitcoin
  packages/integration-tests/projects/suite-web/tests/wallet/sign-and-verify.test.ts
Labels: e2e

#5916 Feat: Graph improvements
  suite-native/home-graph/package.json
  suite-native/home-graph/src/components/PortfolioGraph.tsx
  suite-native/home-graph/src/components/TimeSwitchItem.tsx
  suite-native/home-graph/src/index.ts
  suite-native/home-graph/tsconfig.json
  suite-native/module-home/src/screens/HomeScreen.tsx
Labels: mobile-app

#5934 fix(suite): Fix balance styling
  packages/suite/src/components/suite/AmountUnitSwitchWrapper.tsx
  packages/suite/src/components/suite/AppNavigationPanel.tsx
Labels: release

#5922 feat(guide): update articles
  packages/suite-data/src/guide/constants.ts
Labels: release

#5921 Crowdin translations update
  packages/suite-data/files/translations/af.json
  packages/suite-data/files/translations/en.json
Labels: release, translations

#5914 fix(docs): fix link URLs
  docs/SUMMARY.md
  docs/packages/connect/events.md
  docs/packages/connect/methods/commonParams.md
  docs/packages/suite-desktop.md
  docs/specs/guide.md
  docs/tests/e2e-connect-popup.md
Labels: documentation

#5940 fix(suite): fix missing tooltip in graph in account section
  packages/suite/src/components/suite/TransactionsGraph/components/CustomTooltipAccount.tsx
Labels: release

#5945 fix(suite): fix the amount units selector being empty
  packages/suite/src/storage/CHANGELOG.md
  packages/suite/src/storage/index.ts
  packages/suite/src/storage/migrations/index.ts
Labels: release

#5946 chore: Move cardano wallet utils back to suite
  packages/suite/src/actions/wallet/coinmarket/coinmarketCommonActions.ts
  packages/suite/src/actions/wallet/discoveryActions.ts
  packages/suite/src/actions/wallet/receiveActions.ts
  packages/suite/src/actions/wallet/send/sendFormCardanoActions.ts
  packages/suite/src/actions/wallet/sendFormActions.ts
  packages/suite/src/components/suite/modals/ReviewTransaction/index.tsx
  packages/suite/src/hooks/wallet/useCardanoStaking.ts
  packages/suite/src/utils/wallet/__fixtures__/cardanoUtils.ts
  packages/suite/src/utils/wallet/__tests__/cardanoUtils.test.ts
  packages/suite/src/utils/wallet/cardanoUtils.ts
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/TokenSelect/index.tsx
  suite-common/wallet-utils/jest.config.js
  suite-common/wallet-utils/libMock.ts
  suite-common/wallet-utils/package.json
  suite-common/wallet-utils/src/index.ts
Labels: mobile-app

#5899 fix(suite): initialRun not completed by going to settings
  packages/integration-tests/projects/suite-web/tests/onboarding/analytics-consent.test.ts
  packages/suite/src/components/settings/SettingsMenu.tsx
  packages/suite/src/components/suite/SuiteLayout/index.tsx
  packages/suite/src/hooks/suite/useOnboarding.ts
  packages/suite/src/middlewares/onboarding/__tests__/onboardingMiddleware.test.ts
  packages/suite/src/middlewares/onboarding/onboardingMiddleware.ts
  packages/suite/src/middlewares/suite/routerMiddleware.ts
  packages/suite/src/views/onboarding/steps/Final/index.tsx
  packages/suite/src/views/onboarding/steps/Welcome/components/PreOnboardingSetup/DataAnalytics.tsx
  packages/suite/src/views/onboarding/steps/Welcome/components/PreOnboardingSetup/SecurityCheck.tsx
Labels: release

#5953 feat(suite): Enable amount unit switching only in debug mode
  packages/integration-tests/projects/suite-web/tests/wallet/bitcoin-send-form.test.ts
  packages/suite/src/components/suite/AmountUnitSwitchWrapper.tsx
  packages/suite/src/views/settings/general/SettingsGeneral.tsx
Labels: release

#5968 feat(suite): change button wording in FirmwareTypeSuggestion
  packages/suite/src/support/messages.ts
Labels: settings

#5902 feat(suite): format crypto amounts based on app locale
  packages/suite/src/components/suite/FormattedCryptoAmount.tsx
  packages/suite/src/components/wallet/CoinBalance/index.tsx
  packages/suite/src/utils/wallet/__tests__/formatCurrencyAmount.test.ts
  packages/suite/src/utils/wallet/formatCurrencyAmount.ts
  suite-common/wallet-utils/src/__tests__/balanceUtils.test.ts
  suite-common/wallet-utils/src/__tests__/localizeNumber.ts
  suite-common/wallet-utils/src/balanceUtils.ts
  suite-common/wallet-utils/src/index.ts
  suite-common/wallet-utils/src/localizeNumber.ts
Labels: feature

#5760 feat(suite-common): common connect for suite and suite-native
  packages/suite/package.json
  packages/suite/src/actions/backup/__tests__/backupActions.test.ts
  packages/suite/src/actions/suite/__tests__/initAction.test.ts
  packages/suite/src/actions/suite/__tests__/suiteActions.test.ts
  packages/suite/src/actions/suite/__tests__/trezorConnectActions.test.ts
  packages/suite/src/actions/suite/initAction.ts
  packages/suite/src/actions/suite/trezorConnectActions.ts
  packages/suite/src/actions/wallet/__fixtures__/receiveActions.ts
  packages/suite/src/actions/wallet/__tests__/receiveActions.test.ts
  packages/suite/src/middlewares/suite/__tests__/buttonRequestMiddleware.test.ts
  packages/suite/src/reducers/suite/deviceReducer.ts
  packages/suite/src/reducers/wallet/settingsReducer.ts
  packages/suite/src/utils/suite/storage.ts
  packages/suite/tsconfig.json
  suite-common/connect-init/jest.config.js
  suite-common/connect-init/package.json
  suite-common/connect-init/redux.d.ts
  suite-common/connect-init/src/__tests__/trezorConnectActions.test.ts
  suite-common/connect-init/src/cardanoConnectPatch.ts
  suite-common/connect-init/src/index.ts
  suite-common/connect-init/src/slice.ts
  suite-common/connect-init/tsconfig.json
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  suite-native/app/tsconfig.json
  yarn.lock
Labels: mobile-app

#5980 feat(guide): update articles
  packages/suite-data/src/guide/constants.ts
Labels: release

#6000 ref(suite-common): Add settings to common
  packages/suite/src/config/suite/settings.ts
  suite-common/suite-config/src/index.ts
  suite-common/suite-config/src/settings.ts
Labels: mobile-app

#5768 connect-popup refactor [1/3]
  packages/components/package.json
  packages/connect-popup/package.json
  packages/connect-popup/src/index.tsx
  packages/connect-popup/src/static/popup.html
  packages/connect-popup/src/view/common.tsx
  packages/connect-popup/src/view/firmwareNotCompatible.ts
  packages/connect-popup/src/view/firmwareNotSupported.ts
  packages/connect-popup/src/view/firmwareRequiredUpdate.ts
  packages/connect-popup/src/view/react/StylesSheetWrapper.tsx
  packages/connect-popup/tsconfig.json
  packages/connect-popup/webpack/prod.webpack.config.ts
  packages/connect-ui/global.d.ts
  packages/connect-ui/package.json
  packages/connect-ui/src/components/ThemeWrapper.tsx
  packages/connect-ui/src/components/View.tsx
  packages/connect-ui/src/images/man_with_laptop.svg
  packages/connect-ui/src/index.ts
  packages/connect-ui/src/views/Transport.tsx
  packages/connect-ui/tsconfig.json
Labels: READY FOR REVIEW, connect, connect-popup

#6018 fix(suite): improve label expansion
  packages/suite/src/components/suite/Labeling/components/Metadata/index.tsx
  packages/suite/src/components/suite/Labeling/index.tsx
Labels: labelling

#6052 Deleted specs section from docs and specs links from SUMMARY.md
  docs/SUMMARY.md
  docs/specs/bug_and_feedback_submission.md
  docs/specs/guide.md
  docs/specs/index.md
Labels: documentation

#6040 chore(suite): code cleanup
  packages/suite-web-landing/components/FromMytrezorBanner/index.tsx
  packages/suite/src/components/onboarding/Box.tsx
  packages/suite/src/components/onboarding/ConnectDevicePromptManager/components/NoDeviceDetected.tsx
  packages/suite/src/components/onboarding/ConnectDevicePromptManager/components/NoTransport.tsx
  packages/suite/src/components/onboarding/ConnectDevicePromptManager/components/UnexpectedDeviceState.tsx
  packages/suite/src/components/onboarding/ConnectDevicePromptManager/index.tsx
  packages/suite/src/components/onboarding/index.ts
  packages/suite/src/components/suite/CollapsibleBox.tsx
  packages/suite/src/components/suite/ConnectDevicePrompt.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceAcquire.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceBootloader.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceConnect.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceDisconnectRequired.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceInitialize.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceNoFirmware.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceRecoveryMode.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceSeedless.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceUnknown.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceUnreadable.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceUpdateRequired.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/components/Transport.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/index.tsx
  packages/suite/src/components/suite/TroubleshootingTips/index.tsx
  packages/suite/src/components/suite/index.tsx
Labels: code

#6066 fix(docs): add path.md to SUMMARY.md, unify heading types
  docs/SUMMARY.md
  docs/packages/connect/dependencies.md
  docs/packages/connect/events.md
  docs/packages/connect/index.md
  docs/packages/connect/methods.md
  docs/packages/connect/methods/commonParams.md
  docs/packages/connect/methods/getPublicKey.md
  docs/packages/connect/path.md
Labels: documentation

#6078 Fix/connect methods docs
  docs/packages/connect/methods/authorizeCoinJoin.md
  docs/packages/connect/methods/binanceGetAddress.md
  docs/packages/connect/methods/binanceGetPublicKey.md
  docs/packages/connect/methods/binanceSignTransaction.md
  docs/packages/connect/methods/cardanoGetAddress.md
  docs/packages/connect/methods/cardanoGetNativeScriptHash.md
  docs/packages/connect/methods/cardanoGetPublicKey.md
  docs/packages/connect/methods/cardanoSignTransaction.md
  docs/packages/connect/methods/cipherKeyValue.md
  docs/packages/connect/methods/composeTransaction.md
  docs/packages/connect/methods/eosGetPublicKey.md
  docs/packages/connect/methods/eosSignTransaction.md
  docs/packages/connect/methods/ethereumGetAddress.md
  docs/packages/connect/methods/ethereumSignMessage.md
  docs/packages/connect/methods/ethereumSignTransaction.md
  docs/packages/connect/methods/ethereumSignTypedData.md
  docs/packages/connect/methods/ethereumVerifyMessage.md
  docs/packages/connect/methods/firmwareUpdate.md
  docs/packages/connect/methods/getAccountInfo.md
  docs/packages/connect/methods/getAddress.md
  docs/packages/connect/methods/getCoinInfo.md
  docs/packages/connect/methods/getCurrentFiatRates.md
  docs/packages/connect/methods/getDeviceState.md
  docs/packages/connect/methods/getFirmwareHash.md
  docs/packages/connect/methods/getOwnershipId.md
  docs/packages/connect/methods/getOwnershipProof.md
  docs/packages/connect/methods/getPublicKey.md
  docs/packages/connect/methods/nemGetAddress.md
  docs/packages/connect/methods/nemSignTransaction.md
  docs/packages/connect/methods/pushTransaction.md
  docs/packages/connect/methods/requestLogin.md
  docs/packages/connect/methods/resetDevice.md
  docs/packages/connect/methods/rippleGetAddress.md
  docs/packages/connect/methods/rippleSignTransaction.md
  docs/packages/connect/methods/signMessage.md
  docs/packages/connect/methods/signTransaction.md
  docs/packages/connect/methods/stellarGetAddress.md
  docs/packages/connect/methods/stellarSignTransaction.md
  docs/packages/connect/methods/tezosGetAddress.md
  docs/packages/connect/methods/tezosGetPublicKey.md
  docs/packages/connect/methods/tezosSignTransaction.md
  docs/packages/connect/methods/verifyMessage.md
  docs/packages/connect/methods/wipeDevice.md
Labels: connect, documentation

#6047 fix(suite-common): remove sort from getAccountTransactions
  suite-common/wallet-utils/src/transactionUtils.ts
Labels: bug, transactions

#6080 [at] extending the db migration test
  packages/integration-tests/projects/suite-web/tests/suite/database-migration.test.ts
Labels: e2e

#6092 feat(mobile): Add screen padding customization
  suite-native/module-home/src/screens/HomeScreen.tsx
  suite-native/module-onboarding/src/screens/OnboardingAssets.tsx
  suite-native/module-onboarding/src/screens/OnboardingXpubScan.tsx
  suite-native/module-settings/src/components/DeviceActionButtons.tsx
  suite-native/module-settings/src/screens/DemoScreen.tsx
  suite-native/module-settings/src/screens/SettingsLocalisationScreen.tsx
  suite-native/module-settings/src/screens/SettingsScreen.tsx
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/src/components/ScreenHeader.tsx
Labels: mobile-app

#6090 feat: improve tab bar hit slope
  suite-native/navigation/src/ActionTabBarItem.tsx
  suite-native/navigation/src/components/TabBar.tsx
  suite-native/navigation/src/components/TabBarItem.tsx
Labels: mobile-app

#6133 chore(suite): export areSatsUsed fom useBitcoinAmountUnit
  packages/suite/src/hooks/wallet/useBitcoinAmountUnit.ts
  packages/suite/src/hooks/wallet/useSendForm.ts
  packages/suite/src/hooks/wallet/useSendFormFields.ts
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx
Labels: code, bitcoin

#6079 feat: display coinmarket info notes as tags
  packages/suite/src/components/wallet/CoinmarketTag/index.tsx
  packages/suite/src/components/wallet/index.tsx
  packages/suite/src/utils/wallet/coinmarket/__tests__/coinmarketUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/coinmarketUtils.ts
  packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/List/Quote/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/List/Quote/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/offers/Offers/List/Quote/index.tsx
  patches/@types+invity-api+1.0.6.patch
Labels: +Invity, READY FOR MERGE

#6157 fix(suite): rephrase dust limit validation message
  packages/suite/src/support/messages.ts
Labels: send, copy

#6021 e2e - firmware update
  ci/test.yml
  docker/docker-compose.suite-ci.yml
  docker/docker-compose.suite-test.yml
  packages/integration-tests/process-har.ts
  packages/integration-tests/projects/suite-web/fixtures/fw-update-on-bl-2.0.3-to-fw-2.5.1.js
  packages/integration-tests/projects/suite-web/fixtures/testFirmware.bin
  packages/integration-tests/projects/suite-web/fixtures/trezor-2.5.1.bin
  packages/integration-tests/projects/suite-web/plugins/bridge.js
  packages/integration-tests/projects/suite-web/plugins/index.js
  packages/integration-tests/projects/suite-web/support/commands.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/firmware-update.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/custom-firmware.test.ts
Labels: e2e
