Repository trezor/trezor-suite, pull requests merged in 2022-02, with the labels that each got.

#4545 fix: wipe device webusb workaround
  packages/suite/src/actions/settings/__fixtures__/deviceSettings.ts
  packages/suite/src/actions/settings/__tests__/deviceSettingsActions.test.ts
  packages/suite/src/actions/settings/deviceSettingsActions.ts
  packages/suite/src/actions/suite/constants/suiteConstants.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/components/suite/PrerequisitesGuide/components/DeviceDisconnectRequired.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/index.tsx
  packages/suite/src/components/suite/modals/DisconnectDevice/index.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/utils/suite/prerequisites.ts
Labels: READY TO REVIEW

#4839 fix(win): start signing DLL binaries to satisfy AppLocker policy
  packages/suite-desktop/package.json
Labels: READY TO REVIEW

#4826 fix(suite): jumping of navbar in settings when opening modal
  packages/suite/src/components/suite/AppNavigation/index.tsx
Labels: READY TO REVIEW, release

#4844 fix: webusb regression
  packages/transport/src/lowlevel/sharedConnectionWorker.ts
  packages/transport/src/lowlevel/withSharedConnections.ts
  packages/transport/src/utils/defered.ts
Labels: READY TO REVIEW, release

#4870 chore: move version utils to @trezor/utils
  packages/rollout/integration/fresh-devices.ts
  packages/rollout/package.json
  packages/rollout/src/index.ts
  packages/rollout/src/utils/releases.ts
  packages/rollout/src/utils/version.ts
  packages/utils/src/index.ts
  packages/utils/src/versionUtils.ts
  packages/utils/tests/version.test.ts
Labels: READY TO REVIEW

#4898 chore(ci): fix rollout nightly job
  ci/test.yml
  packages/rollout/jest.config.integration.js
Labels: READY TO REVIEW

#4897 chore: remove semver-compare util from transport
  packages/transport/package.json
  packages/transport/src/bridge/v2.ts
  packages/transport/src/utils/semver-compare.ts
Labels: READY TO REVIEW

#4906 fix(suite): set max qr height
  packages/suite/src/components/suite/QrCode/index.tsx
  packages/suite/src/components/suite/modals/confirm/Address/index.tsx
  packages/suite/src/components/suite/modals/confirm/Xpub/index.tsx
Labels: release, HIGH

#4908 chore: crowdin sync
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/da.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/el.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fi.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/he.json
  packages/suite-data/files/translations/hi.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/id.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/jv.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/no.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sr.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/vi.json
  packages/suite-data/files/translations/zh.json
Labels: release, translations

#4912 Chore/pull requests project automation
  .github/workflows/project-automation.yml
Labels: READY TO REVIEW

#4927 chore: update cypress to 9.4.1
  docker/docker-compose.suite-ci.yml
  docker/test-runner/Dockerfile
  packages/integration-tests/package.json
  yarn.lock
Labels: READY TO REVIEW

#4920 refactor: Import react-select from @trezor/components
  packages/suite/package.json
Labels: READY TO REVIEW

#4919 feat: Update the zcash logo color to match the official logo
  packages/components/src/images/coins/zec.svg
Labels: READY TO REVIEW

#4923 chore: remove unused messages from messages.ts
  packages/suite/src/support/messages.ts
Labels: translations

#4937 Ci tuning
  ci/test.yml
  packages/integration-tests/projects/connect-explorer/tests/fixtures.js
  packages/integration-tests/projects/suite-web/tests/wallet/sign-and-verify.test.ts
Labels: READY TO REVIEW

#4958 fix(auto-update): fix auto-update on mac by upgrading electron dependencies
  packages/suite-desktop/package.json
  yarn.lock
Labels: READY TO REVIEW, release

#4956 feat(ci): automation for updating crowdin translations
  .github/workflows/crowdin_sync.yml
Labels: ci

#4966 feat(message-system): inform mac EAP users about broken autoupdater on 22.2.1 and 22.2.2
  packages/suite-data/src/message-system/config/config.v1.json
Labels: READY TO REVIEW

#4848 chore: utility ci scripts
  .gitlab-ci.yml
  ci/schedules.yml
  ci/scripts/find_duplicates.sh
  ci/utils.yml
  packages/suite-data/scripts/find-unused.sh
  packages/suite-data/scripts/list-duplicates.ts
  packages/suite-data/scripts/list-unused.ts
  packages/suite-data/test/test-same-svgs.ts
  packages/suite/package.json
  packages/suite/test/health/urls.test.ts
Labels: READY TO REVIEW

#4969 chore: remove beta from languages
  packages/suite/src/config/suite/languages.ts
Labels: READY TO REVIEW

#4953 popup emu screenshots
  ci/test.yml
  docker/docker-compose.connect-explorer-test.yml
  packages/integration-tests/projects/connect-explorer/playwright.config.ts
  packages/integration-tests/projects/connect-explorer/support/buildOverview.js
  packages/integration-tests/projects/connect-explorer/tests/fixtures.js
  packages/integration-tests/projects/connect-explorer/tests/popup.test.js
Labels: READY TO REVIEW

#4984 chore: update cross-fetch
  packages/rollout/package.json
  yarn.lock
Labels: READY TO REVIEW

#4972 Crowdin translations update
  packages/suite-data/files/translations/af.json
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/uk.json
Labels: translations

#4990 chore: remove unused messages
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#5002 chore: connect 8.2.8-beta.1
  packages/connect-explorer/package.json
  packages/suite-desktop/package.json
  packages/suite/package.json
  yarn.lock
Labels: READY TO REVIEW

#4983 Fix/signing electron win electron builder approach org
  docs/releases/signing-binaries-win.md
  patches/app-builder-lib+22.14.5.patch
Labels: IN PROGRESS, Windows

#4987 feat(ci): change to darwin_arm runner for codesign
  ci/build.yml
  ci/prebuild.yml
Labels: ci

#5000 feat: enable cardano testnet
  packages/suite/src/config/wallet/networks.ts
  packages/suite/src/utils/wallet/cardanoUtils.ts
Labels: release

#5010 feat(invity): enable exchange and sell for Cardano
  packages/suite/src/components/wallet/CoinmarketLayout/components/Navigation/index.tsx
  packages/suite/src/utils/wallet/coinmarket/coinmarketUtils.ts
Labels: READY TO REVIEW, +Invity, release

#4980 feat(invity): sell crypto alternative flow
  packages/suite-desktop/src-electron/libs/buy.ts
  packages/suite-desktop/src-electron/libs/sell.ts
  packages/suite-desktop/src-electron/modules/http-receiver.ts
  packages/suite/package.json
  packages/suite/src/actions/wallet/coinmarketSellActions.ts
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/SellTransaction/index.tsx
  packages/suite/src/hooks/wallet/useCoinmarket.ts
  packages/suite/src/hooks/wallet/useCoinmarketRedirect.ts
  packages/suite/src/hooks/wallet/useCoinmarketSellForm.ts
  packages/suite/src/hooks/wallet/useCoinmarketSellOffers.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/wallet/coinmarketSellOffers.ts
  packages/suite/src/utils/wallet/coinmarket/__tests__/sellUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/sellUtils.ts
  packages/suite/src/views/settings/debug/InvityApi.tsx
  packages/suite/src/views/wallet/coinmarket/redirect/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/offers/Offers/List/Quote/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/offers/Offers/SelectedOffer/components/SendTransaction/index.tsx
  yarn.lock
Labels: +Invity, release, READY TO MERGE

#5015 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/ru.json
Labels: translations

#5011 feat(electrum): enable electrum for everyone
  packages/suite/src/components/suite/modals/AdvancedCoinSettings/components/BackendTypeSelect.tsx
Labels: READY TO REVIEW, release

#5017 chore: backport-en.json
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW, translations
