Repository trezor/trezor-suite, pull requests merged in 2022-01, with the labels that each got.

#4678 fix: unify link components ExternalLink
  packages/suite/src/components/settings/SettingsMenu/index.tsx
  packages/suite/src/components/suite/ExternalLink/index.tsx
  packages/suite/src/components/suite/index.tsx
  packages/suite/src/components/suite/modals/AddAccount/components/AccountTypeDescription.tsx
  packages/suite/src/components/suite/modals/QrScanner/index.tsx
  packages/suite/src/views/backup/index.tsx
  packages/suite/src/views/recovery/index.tsx
Labels: READY TO REVIEW

#4675 fix(suite): do not autofocus on passhprase on Android to prevent scroll and keyboard opened
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
Labels: READY TO REVIEW, low hanging fruit

#4575 feat: mytrezor wallet deprecation banner
  packages/suite-web-landing/components/FromMytrezorBanner/index.tsx
  packages/suite-web-landing/components/Layout/index.tsx
  packages/suite-web-landing/pages/index.tsx
  packages/suite/src/components/suite/CollapsibleBox/index.tsx
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#4701 trezor-connect: 8.2.5-beta.2
  packages/suite/package.json
  packages/suite/src/components/suite/modals/ReviewTransaction/index.tsx
  packages/suite/src/components/suite/modals/TransactionDetail/components/ChangeFee/components/DecreasedOutputs/index.tsx
  packages/suite/src/utils/wallet/accountUtils.ts
  packages/suite/src/views/wallet/receive/components/UsedAddresses/index.tsx
  yarn.lock
Labels: READY TO REVIEW

#4593 fix(suite): open safety-checks modal from banner
  packages/suite/src/components/suite/Banners/SafetyChecks.tsx
  packages/suite/src/components/suite/modals/SafetyChecks/index.tsx
Labels: READY TO REVIEW

#4696 Feat: metadata labeling in send form
  packages/suite/src/actions/suite/metadataActions.ts
  packages/suite/src/actions/wallet/sendFormActions.ts
  packages/suite/src/components/suite/Labeling/components/Metadata/definitions.ts
  packages/suite/src/components/suite/Labeling/components/Metadata/index.tsx
  packages/suite/src/components/suite/Labeling/components/Metadata/withEditable.tsx
  packages/suite/src/constants/wallet/sendForm.ts
  packages/suite/src/hooks/wallet/__tests__/useSendForm.test.tsx
  packages/suite/src/hooks/wallet/useSendForm.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/wallet/sendForm.ts
  packages/suite/src/views/wallet/send/components/Outputs/components/Address/components/AddLabel/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Address/index.tsx
  packages/suite/src/views/wallet/send/index.tsx
Labels: READY TO REVIEW, release

#4712 fix(suite-native): add missing package to metro.config
  packages/suite-native/metro.config.js
Labels: READY TO REVIEW

#4714 fix: proper blockchain-link version
  packages/blockchain-link/CHANGELOG.md
  packages/blockchain-link/package.json
Labels: READY TO REVIEW, release

#4717 chore: connect 8.2.5-beta.3
  packages/suite/package.json
  yarn.lock
Labels: READY TO REVIEW, release

#4719 feat(guide): update articles
  packages/suite-data/src/guide/constants.ts
Labels: READY TO REVIEW, release

#4718 fix: disappearing of outpus when removing
  packages/suite/src/config/suite/animation.ts
Labels: READY TO REVIEW, release

#4722 chore: translations minor changes
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ru.json
Labels: release

#4724 fix: regtest only available in debug mode
  packages/integration-tests/projects/suite-web/support/commands.ts
  packages/integration-tests/projects/suite-web/support/utils/shortcuts.ts
  packages/integration-tests/projects/suite-web/tests/wallet/coin-balance.test.ts
  packages/suite/src/components/settings/SettingsMenu/index.tsx
  packages/suite/src/components/suite/modals/AddAccount/index.tsx
  packages/suite/src/views/onboarding/steps/BasicSettings/index.tsx
  packages/suite/src/views/settings/coins/index.tsx
Labels: READY TO REVIEW, release

#4733 fix(suite): fix suite stucked in bootloader mode
  packages/suite/src/middlewares/suite/redirectMiddleware.ts
Labels: READY TO REVIEW, release

#4740 fix(custom-firmware): connect your device prompt breaks layout
  packages/suite/src/components/firmware/SelectCustomFirmware.tsx
  packages/suite/src/views/firmware/FirmwareCustom.tsx
Labels: READY TO REVIEW, release

#4743 fix(toast): above guide when modal open
  packages/components/src/config/variables.ts
  packages/suite/src/components/suite/ToastContainer/index.tsx
Labels: READY TO REVIEW, release

#4745 chore: update cypress to 9.2.1
  docker/docker-compose.suite-ci.yml
  docker/test-runner/Dockerfile
  packages/integration-tests/package.json
  yarn.lock
Labels: READY TO REVIEW

#4742 ci: optimize gitlab ci using matrixes
  ci/test.yml
Labels: READY TO REVIEW

#4759 chore: add translations from crowdin
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sv.json
Labels: READY TO REVIEW

#4620 test: transport e2e
  ci/test.yml
  docker/docker-compose.transport-test.yml
  docker/docker-transport-test.sh
  docker/wait-for-env.sh
  packages/integration-tests/package.json
  packages/integration-tests/projects/suite-web/plugins/index.js
  packages/integration-tests/projects/suite-web/run_tests.js
  packages/integration-tests/projects/transport/common.setup.js
  packages/integration-tests/projects/transport/jest.config.js
  packages/integration-tests/projects/transport/tests/bridge.integration.js
  packages/integration-tests/websocket-client.js
  packages/transport/jest.config.e2e.js
Labels: READY TO REVIEW

#4547 feat: wipe locally saved data from debug settings
  packages/suite-desktop/src-electron/libs/constants.ts
  packages/suite-desktop/src-electron/libs/user-data.ts
  packages/suite-desktop/src-electron/modules/user-data.ts
  packages/suite-desktop/src-electron/preload.ts
  packages/suite/global.d.ts
  packages/suite/src/views/settings/debug/index.tsx
Labels: READY TO REVIEW, design

#4776 ci: unify blockchain-link test with others
  ci/test.yml
Labels: READY TO REVIEW

#4777 chore: backport english translations to messages.ts
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW, translations

#4778 chore: backport en.json to messages.ts
  packages/suite-data/files/translations/en.json
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW, translations

#4774 docs: update suite-desktop README
  docs/misc/notes.md
  docs/packages/suite-desktop.md
  packages/suite-desktop/README.md
Labels: READY TO REVIEW

#4760 chore(code): Deduplicate modules, reduce node_modules size by 50%
  packages/blockchain-link/package.json
  packages/suite-desktop/src-electron/app.ts
  yarn.lock
Labels: READY TO REVIEW

#4594 desktop e2e
  ci/test.yml
  docker/docker-compose.suite-desktop-ci.yml
  docker/docker-compose.suite-desktop-test.yml
  docker/docker-suite-desktop-test.sh
  packages/integration-tests/package.json
  packages/integration-tests/projects/suite-desktop/playwright.config.ts
  packages/integration-tests/projects/suite-desktop/tests/first.spec.ts
  packages/suite/src/components/suite/WelcomeLayout/index.tsx
  yarn.lock
Labels: READY TO REVIEW

#4782 chore: update trezor-connect with blockchain-link@2.0
  packages/connect-iframe/package.json
  packages/suite/package.json
  yarn.lock
Labels: READY TO REVIEW

#4785 chore: remove yarn.lock in transport package
  packages/transport/yarn.lock
Labels: READY TO REVIEW

#4780 Cypress improvements
  ci/scripts/check-vulnerabilities.js
  ci/test.yml
  docker/docker-compose.suite-ci.yml
  docker/docker-compose.suite-test.yml
  docker/test-runner/Dockerfile
  packages/integration-tests/package.json
  packages/integration-tests/projects/suite-web/run_tests.js
  packages/integration-tests/projects/suite-web/snapshots/suite/guide.test.ts/Test Guide -- in onboarding with device.snap.png
  packages/integration-tests/projects/suite-web/snapshots/suite/prerequisites.test.ts/device-bootloader.snap.png
  packages/integration-tests/projects/suite-web/snapshots/suite/prerequisites.test.ts/device-disconnected.snap.png
  packages/integration-tests/projects/suite-web/snapshots/suite/prerequisites.test.ts/device-seedless.snap.png
  packages/integration-tests/projects/suite-web/snapshots/suite/prerequisites.test.ts/device-unacquired.snap.png
  packages/integration-tests/projects/suite-web/snapshots/suite/prerequisites.test.ts/device-unknown.snap.png
  packages/integration-tests/projects/suite-web/snapshots/suite/prerequisites.test.ts/device-unreadable.snap.png
  packages/integration-tests/projects/suite-web/tests/suite/guide.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/prerequisites.test.ts
  packages/integration-tests/tsconfig.json
  packages/suite/src/components/guide/GuideCategories.tsx
  packages/suite/src/components/guide/GuideSearch.tsx
  packages/suite/src/components/guide/Header.tsx
  packages/suite/src/components/guide/HeaderBreadcrumb.tsx
  packages/suite/src/views/guide/Feedback.tsx
  packages/suite/src/views/guide/GuideCategory.tsx
  packages/suite/src/views/guide/SupportFeedbackSelection.tsx
  yarn.lock
Labels: READY TO REVIEW

#4711 upgrade dependencies
  packages/blockchain-link/tests/unit/workers.ts
  packages/blockchain-link/tests/websocket/index.ts
  packages/components/package.json
  packages/integration-tests/package.json
  packages/news-api/package.json
  packages/suite-build/configs/base.webpack.config.ts
  packages/suite-desktop/package.json
  packages/suite-native/metro.config.js
  packages/suite-native/package.json
  packages/suite-web-landing/package.json
  packages/suite-web/package.json
  packages/suite/package.json
  patches/redux-thunk+2.3.0.patch
  patches/redux-thunk+2.4.1.patch
  yarn.lock
Labels: READY TO REVIEW

#4812 chore: update webpack-cli
  packages/blockchain-link/package.json
  packages/connect-iframe/package.json
  packages/suite-data/package.json
  yarn.lock
Labels: READY TO REVIEW

#4816 feat(translations): Sync with Crowdin
  packages/suite-data/files/translations/af.json
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/da.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/el.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fi.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/he.json
  packages/suite-data/files/translations/hi.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/id.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/jv.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/no.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sr.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/vi.json
  packages/suite-data/files/translations/zh.json
Labels: READY TO REVIEW, translations

#4821 fix: storybook build
  packages/components/.storybook/main.js
  packages/components/package.json
  yarn.lock
Labels: READY TO REVIEW

#4829 fix: missing desktop icon
  packages/suite-desktop/src-electron/app.ts
Labels: READY TO REVIEW

#4725 feat(homescreen): enable custom homescreen upload even on model one
  packages/suite/src/components/suite/HomescreenGallery/index.tsx
  packages/suite/src/components/suite/Settings/components/TextColumn.tsx
  packages/suite/src/constants/suite/urls.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/suite/__tests__/homescreen.test.ts
  packages/suite/src/utils/suite/homescreen.ts
  packages/suite/src/views/settings/device/BackupFailed.tsx
  packages/suite/src/views/settings/device/BackupRecoverySeed.tsx
  packages/suite/src/views/settings/device/CheckRecoverySeed.tsx
  packages/suite/src/views/settings/device/CustomFirmware.tsx
  packages/suite/src/views/settings/device/Homescreen.tsx
  packages/suite/src/views/settings/device/Passphrase.tsx
  packages/suite/src/views/settings/index.tsx
  packages/suite/src/views/wallet/details/index.tsx
Labels: READY TO REVIEW, product, release, HIGH
