Repository trezor/trezor-suite, pull requests merged in 2022-05, with the labels that each got.

#5291 chore(message-system): config sequence 12
  packages/suite-data/src/message-system/config/config.v1.json
Labels: READY FOR REVIEW

#5310 chore(message-system): sequence 13
  packages/suite-data/src/message-system/config/config.v1.json
Labels: READY FOR REVIEW

#5364 fix: incorrect select blur behavior
  packages/components/src/components/form/Select/index.tsx
Labels: READY FOR MERGE

#5395 chore(connect): enums in arrays as strings
  packages/connect/src/utils/__tests__/deviceFeaturesUtils.test.ts
  packages/connect/src/utils/deviceFeaturesUtils.ts
  packages/transport/src/lowlevel/protobuf/decode.ts
  packages/transport/tests/encode-decode.test.js
Labels: READY FOR REVIEW

#5370 feat: Implement num pad button
  packages/atoms/src/Button.tsx
  packages/atoms/src/NumPadButton.tsx
  packages/atoms/src/index.ts
  packages/suite-native/ios/Podfile.lock
  packages/suite-native/src/screens/Home.tsx
  packages/theme/src/borders.ts
  packages/theme/src/fontWeights.ts
  packages/theme/src/prepareTheme.ts
Labels: mobile-app

#5436 fix(connect): return taproot descriptor (xpub) from getPublicKey method
  packages/connect/src/device/DeviceCommands.ts
  packages/integration-tests/projects/connect/__fixtures__/getPublicKey.ts
Labels: READY FOR REVIEW

#5434 fix(connect): improve connect logs (debug)
  packages/connect-web/src/index.ts
  packages/connect/src/core/index.ts
  packages/connect/src/device/DescriptorStream.ts
  packages/connect/src/device/Device.ts
  packages/connect/src/device/DeviceCommands.ts
  packages/connect/src/device/DeviceList.ts
  packages/connect/src/index.ts
  packages/connect/src/utils/debug.ts
  packages/connect/src/utils/interactionTimeout.ts
Labels: READY FOR REVIEW

#5427 Feat(native): Hint component
  packages/atoms/src/Hint.tsx
  packages/atoms/src/Icon/Icon.tsx
  packages/atoms/src/index.ts
  packages/suite-native/src/screens/Home.tsx
Labels: mobile-app

#5451 feat(message-system): update config
  packages/suite-data/src/message-system/config/config.v1.json
Labels: READY FOR REVIEW

#5444 feat(atom): Add RadioButton component to RN app
  packages/atoms/src/Button.tsx
  packages/atoms/src/Radio.tsx
  packages/atoms/src/index.ts
  packages/suite-native/src/screens/Home.tsx
Labels: mobile-app

#5433 feat: Input component
  packages/atoms/src/SearchInput.tsx
  packages/atoms/src/index.ts
  packages/suite-native/ios/Podfile.lock
  packages/suite-native/src/screens/Home.tsx
Labels: mobile-app

#5477 test/changeDeviceName
  packages/integration-tests/projects/suite-web/tests/settings/t2-device-settings.test.ts
Labels: e2e

#5426 chore(connect): remove non-streamed signing from cardano
  docs/packages/connect/dependencies.md
  packages/connect/CHANGELOG.md
  packages/connect/package.json
  packages/connect/src/api/cardano/cardanoSignTxLegacy.ts
  packages/connect/src/api/cardanoSignTransaction.ts
  packages/connect/src/data/config.ts
  packages/integration-tests/projects/connect/__fixtures__/cardanoSignTransaction.ts
  yarn.lock
Labels: READY FOR REVIEW

#5466 Docs
  docs/SUMMARY.md
  docs/packages/connect/methods/cipherKeyValue.md
  docs/packages/connect/methods/ethereumGetAddress.md
  docs/packages/connect/methods/ethereumSignMessage.md
  docs/packages/connect/methods/ethereumSignTransaction.md
  docs/packages/connect/methods/ethereumVerifyMessage.md
  docs/packages/connect/methods/getAccountInfo.md
  docs/packages/connect/methods/getAddress.md
  docs/packages/connect/methods/getPublicKey.md
  docs/packages/connect/methods/nemGetAddress.md
  docs/packages/connect/methods/nemSignTransaction.md
  docs/packages/connect/methods/pushTransaction.md
  docs/packages/connect/methods/requestLogin.md
  docs/packages/connect/methods/signMessage.md
  docs/packages/connect/methods/verifyMessage.md
Labels: READY FOR REVIEW

#5471 feat: Implement custom switch button
  packages/atoms/src/Switch.tsx
  packages/atoms/src/index.ts
  packages/suite-native/src/screens/Home.tsx
Labels: mobile-app

#5455 feat: Add react navigation
  packages/atoms/package.json
  packages/suite-native-navigation-root/jest.config.js
  packages/suite-native-navigation-root/package.json
  packages/suite-native-navigation-root/src/dummyScreens/AccountsScreen.tsx
  packages/suite-native-navigation-root/src/dummyScreens/ActionScreen.tsx
  packages/suite-native-navigation-root/src/dummyScreens/DemoScreen.tsx
  packages/suite-native-navigation-root/src/dummyScreens/HomeScreen.tsx
  packages/suite-native-navigation-root/src/dummyScreens/PricesScreen.tsx
  packages/suite-native-navigation-root/src/index.ts
  packages/suite-native-navigation-root/src/navigation/RootTabNavigator.tsx
  packages/suite-native-navigation-root/src/navigation/navigationMap.d.ts
  packages/suite-native-navigation-root/src/navigation/routes.ts
  packages/suite-native-navigation-root/tsconfig.json
  packages/suite-native-navigation/jest.config.js
  packages/suite-native-navigation/package.json
  packages/suite-native-navigation/src/TabBar.tsx
  packages/suite-native-navigation/src/TabBarItem.tsx
  packages/suite-native-navigation/src/index.ts
  packages/suite-native-navigation/src/types.tsx
  packages/suite-native-navigation/tsconfig.json
  packages/suite-native-settings/jest.config.js
  packages/suite-native-settings/package.json
  packages/suite-native-settings/src/index.ts
  packages/suite-native-settings/src/navigation/SettingsStackNavigator.tsx
  packages/suite-native-settings/src/navigation/routes.ts
  packages/suite-native-settings/src/screens/SettingsDetailScreen.tsx
  packages/suite-native-settings/src/screens/SettingsScreen.tsx
  packages/suite-native-settings/tsconfig.json
  packages/suite-native/android/app/src/main/java/com/trezorsuite/MainActivity.java
  packages/suite-native/index.js
  packages/suite-native/ios/Podfile.lock
  packages/suite-native/package.json
  packages/suite-native/src/App.tsx
  packages/suite-native/tsconfig.json
  packages/transport-native/ios/TrezorTransportNative.m
  yarn.lock
Labels: mobile-app

#5494 chore: remove unused messages
  packages/suite/src/support/messages.ts
Labels: READY FOR REVIEW

#5488 feat(atom) add checkbox RN component
  packages/atoms/src/CheckBox.tsx
  packages/atoms/src/index.ts
  packages/suite-native-navigation-root/src/dummyScreens/DemoScreen.tsx
Labels: mobile-app

#5482 feat(atom) Add ListItem and SelectableListItem RN components
  packages/atoms/src/ListItem/ListItem.tsx
  packages/atoms/src/ListItem/ListItemIcon.tsx
  packages/atoms/src/ListItem/ListItemText.tsx
  packages/atoms/src/ListItem/SelectableListItem.tsx
  packages/atoms/src/ListItem/listItemTypes.ts
  packages/atoms/src/Radio.tsx
  packages/atoms/src/index.ts
  packages/suite-native-navigation-root/src/dummyScreens/DemoScreen.tsx
Labels: mobile-app

#5518 discreet-mode
  packages/integration-tests/projects/suite-web/tests/dashboard/discreet-mode.test.ts
Labels: e2e

#5300 suite-test:assets-test
  packages/integration-tests/projects/suite-web/tests/dashboard/assets.test.ts
Labels: e2e

#5284 suite tests: report-bug-form
  packages/integration-tests/projects/suite-web/tests/suite/bug-report-form.test.ts
  packages/suite/src/components/guide/Feedback.tsx
Labels: e2e

#5522 feat(e2e): removing obsolete tests
  packages/integration-tests/projects/suite-web/tests/settings/t1-device-settings.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/t2-device-settings.test.ts
Labels: e2e

#5507 feat(uri-handler): support other bitcoin-like coins in desktop app
  docs/features/protocols/coin-handler.md
  packages/suite-desktop/package.json
  packages/suite/src/components/suite/NotificationRenderer/index.tsx
  packages/suite/src/constants/suite/protocol.ts
  packages/suite/src/reducers/suite/notificationReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/support/suite/Protocol.tsx
  packages/suite/src/utils/suite/__fixtures__/parseUri.ts
  packages/suite/src/utils/suite/__fixtures__/protocol.ts
  packages/suite/src/utils/suite/__tests__/parseUri.test.ts
  packages/suite/src/utils/suite/__tests__/protocol.test.ts
  packages/suite/src/utils/suite/parseUri.ts
  packages/suite/src/utils/suite/protocol.ts
  packages/suite/src/views/wallet/send/components/Outputs/components/Address/index.tsx
Labels: READY FOR MERGE

#5484 Cardano staking dot refactor
  packages/suite/src/actions/wallet/cardanoStakingActions.ts
  packages/suite/src/actions/wallet/constants/cardanoStakingConstants.ts
  packages/suite/src/components/wallet/AccountTopPanel/components/AccountNavigation/index.tsx
  packages/suite/src/hooks/wallet/useCardanoStaking.ts
  packages/suite/src/middlewares/wallet/blockchainMiddleware.ts
  packages/suite/src/reducers/wallet/__tests__/cardanoStakingReducer.test.ts
  packages/suite/src/reducers/wallet/cardanoStakingReducer.ts
  packages/suite/src/types/wallet/cardanoStaking.ts
  packages/suite/src/utils/suite/__tests__/anchor.test.ts
  packages/suite/src/utils/suite/__tests__/tor.test.ts
  packages/suite/src/utils/wallet/__fixtures__/cardanoUtils.ts
  packages/suite/src/utils/wallet/__tests__/cardanoUtils.test.ts
  packages/suite/src/utils/wallet/cardanoUtils.ts
Labels: READY FOR MERGE

#5493 feat: Modal
  packages/atoms/src/Button.tsx
  packages/atoms/src/CheckBox.tsx
  packages/atoms/src/Chip.tsx
  packages/atoms/src/Modal/BottomModal.tsx
  packages/atoms/src/Modal/BottomModalContainer.tsx
  packages/atoms/src/Radio.tsx
  packages/atoms/src/SearchInput.tsx
  packages/atoms/src/index.ts
  packages/suite-native-navigation-root/src/dummyScreens/DemoScreen.tsx
  packages/suite-native-navigation/src/TabBar.tsx
  packages/suite-native/ios/TrezorSuite.xcodeproj/project.pbxproj
  packages/theme/src/borders.ts
Labels: mobile-app
