Repository trezor/trezor-suite, pull requests merged in 2022-06, with the labels that each got.

#5524 feat(e2e): portfolio check test
  packages/integration-tests/projects/suite-web/tests/dashboard/portfolio-check.test.ts
  packages/suite/src/components/suite/TransactionsGraph/components/CustomTooltipBase/index.tsx
Labels: e2e

#5550 feat(e2e): t1 homescreen change
  packages/integration-tests/projects/suite-web/tests/settings/t1-device-settings.test.ts
Labels: e2e

#5552 chore: rename atoms package
  packages/suite-native-atoms/README.md
  packages/suite-native-atoms/jest.config.js
  packages/suite-native-atoms/package.json
  packages/suite-native-atoms/src/Box.tsx
  packages/suite-native-atoms/src/Button.tsx
  packages/suite-native-atoms/src/CheckBox.tsx
  packages/suite-native-atoms/src/Chip.tsx
  packages/suite-native-atoms/src/Hint.tsx
  packages/suite-native-atoms/src/ListItem/ListItem.tsx
  packages/suite-native-atoms/src/ListItem/ListItemIcon.tsx
  packages/suite-native-atoms/src/ListItem/ListItemText.tsx
  packages/suite-native-atoms/src/ListItem/SelectableListItem.tsx
  packages/suite-native-atoms/src/ListItem/listItemTypes.ts
  packages/suite-native-atoms/src/Modal/BottomModal.tsx
  packages/suite-native-atoms/src/Modal/BottomModalContainer.tsx
  packages/suite-native-atoms/src/NumPadButton.tsx
  packages/suite-native-atoms/src/Radio.tsx
  packages/suite-native-atoms/src/SearchInput.tsx
  packages/suite-native-atoms/src/Switch.tsx
  packages/suite-native-atoms/src/Text.tsx
  packages/suite-native-atoms/src/index.ts
  packages/suite-native-atoms/tsconfig.json
  packages/suite-native-navigation-root/package.json
  packages/suite-native-navigation-root/src/dummyScreens/AccountsScreen.tsx
  packages/suite-native-navigation-root/src/dummyScreens/ActionScreen.tsx
  packages/suite-native-navigation-root/src/dummyScreens/DemoScreen.tsx
  packages/suite-native-navigation-root/src/dummyScreens/HomeScreen.tsx
  packages/suite-native-navigation-root/src/dummyScreens/PricesScreen.tsx
  packages/suite-native-navigation-root/tsconfig.json
  packages/suite-native-navigation/package.json
  packages/suite-native-navigation/tsconfig.json
  packages/suite-native-settings/package.json
  packages/suite-native-settings/src/screens/SettingsDetailScreen.tsx
  packages/suite-native-settings/src/screens/SettingsScreen.tsx
  packages/suite-native-settings/tsconfig.json
  packages/suite-native/ios/Podfile.lock
  packages/suite-native/package.json
  packages/suite-native/tsconfig.json
Labels: mobile-app

#5555 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/da.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#5560 Crowdin translations update
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/he.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/zh.json
Labels: translations

#5559 chore(connect): add "amountUnit" field to signTransaction method
  docs/packages/connect/methods/signTransaction.md
  packages/connect/src/api/signTransaction.ts
  packages/connect/src/data/config.ts
  packages/connect/src/types/api/signTransaction.ts
  packages/connect/src/utils/__tests__/deviceFeaturesUtils.test.ts
Labels: READY FOR REVIEW

#5546 feat: RN animations - switch
  packages/suite-native-atoms/package.json
  packages/suite-native-atoms/src/Switch.tsx
  packages/suite-native/babel.config.js
  packages/suite-native/ios/Podfile.lock
  packages/suite-native/package.json
  yarn.lock
Labels: mobile-app

#5530 feat: Implement tip toast
  packages/icons/src/components/Icon.tsx
  packages/suite-native-atoms/src/Button/Button.tsx
  packages/suite-native-atoms/src/Button/IconButton.tsx
  packages/suite-native-atoms/src/Chip.tsx
  packages/suite-native-atoms/src/ListItem/ListItem.tsx
  packages/suite-native-atoms/src/ListItem/ListItemIcon.tsx
  packages/suite-native-atoms/src/Modal/BottomModal.tsx
  packages/suite-native-atoms/src/SearchInput.tsx
  packages/suite-native-atoms/src/TipToast.tsx
  packages/suite-native-atoms/src/index.ts
  packages/suite-native-navigation-root/src/dummyScreens/DemoScreen.tsx
  packages/suite-native-navigation-root/src/navigation/RootTabNavigator.tsx
  packages/suite-native-settings/src/screens/SettingsScreen.tsx
  packages/theme/src/spacings.ts
Labels: mobile-app

#5528 test(e2e): btc custom blockbook discovery
  packages/integration-tests/projects/suite-web/tests/wallet/custom-blockbook-discovery.test.ts
Labels: e2e

#5573 feat(ci): add deploy and release jobs to npm for connect
  .github/workflows/connect-version_check.yml
  ci/npm-deploy.yml
  ci/scripts/check-beta-version.sh
  ci/scripts/check-version.js
Labels: ci

#5587 Test/ltc custom blockbook discovery
  packages/integration-tests/projects/suite-web/tests/wallet/custom-blockbook-discovery.test.ts
Labels: e2e

#5610 fix: update public packages homepage
  packages/blockchain-link/package.json
  packages/connect-common/package.json
  packages/connect-plugin-ethereum/package.json
  packages/connect-web/package.json
  packages/connect/package.json
  packages/suite-desktop-api/package.json
  packages/transport-native/package.json
  packages/utils/package.json
  packages/utxo-lib/package.json
Labels: READY FOR REVIEW

#5616 chore: clean unused messages
  packages/suite/src/support/messages.ts
Labels: READY FOR REVIEW

#5583 feat: Input
  packages/suite-native-atoms/src/Hint.tsx
  packages/suite-native-atoms/src/Input/Input.tsx
  packages/suite-native-atoms/src/Input/InputWrapper.tsx
  packages/suite-native-atoms/src/Input/SearchInput.tsx
  packages/suite-native-atoms/src/VStack.tsx
  packages/suite-native-atoms/src/index.ts
  packages/suite-native-navigation-root/src/dummyScreens/DemoScreen.tsx
  packages/theme/src/spacings.ts
Labels: mobile-app

#5640 chore: connect-plugin-stellar package.json
  packages/connect-plugin-stellar/package.json
Labels: READY FOR REVIEW

#5642 fix(suite): remove prop from the DOM element to prevent warning
  packages/suite/src/components/wallet/TransactionItem/index.tsx
Labels: low hanging fruit

#5637 fix(translations): duplicated ids
  packages/suite/src/support/messages.ts
Labels: READY FOR REVIEW

#5648 fix(intl): backport-en script
  packages/suite-data/src/translations/backport-en.ts
Labels: READY FOR REVIEW

#5652 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/zh.json
Labels: release, translations

#5638 clean duplicated images
  packages/suite-data/files/images/meta/meta.png
  packages/suite-data/files/images/suite/3d/coins.png
  packages/suite-data/files/images/suite/3d/recovery.png
  packages/suite-data/files/images/suite/3d/understand.png
  packages/suite/src/components/guide/SupportFeedbackSelection.tsx
  packages/suite/src/components/suite/Metadata/index.tsx
Labels: READY FOR REVIEW

#5663 test(e2e): toast notification rendering
  packages/integration-tests/projects/suite-web/tests/settings/notification.toast.test.ts
Labels: e2e

#5660 feat(atom): RN - add floating label animation for TextInput
  packages/suite-native-atoms/src/Input/Input.tsx
  packages/suite-native-atoms/src/Input/InputWrapper.tsx
  packages/suite-native-atoms/src/Input/SearchInput.tsx
  packages/suite-native-navigation-root/src/dummyScreens/DemoScreen.tsx
  packages/suite-native/ios/Podfile.lock
Labels: mobile-app

#5617 feat(suite-native): Settings UI
  packages/icons/assets/icons/eject.svg
  packages/icons/src/icons.ts
  packages/suite-native-atoms/src/Box.tsx
  packages/suite-native-atoms/src/Button/TileButton.tsx
  packages/suite-native-atoms/src/ListItem/ListItem.tsx
  packages/suite-native-atoms/src/index.ts
  packages/suite-native-home/jest.config.js
  packages/suite-native-home/package.json
  packages/suite-native-home/src/index.ts
  packages/suite-native-home/src/navigation/HomeStackNavigator.tsx
  packages/suite-native-home/src/navigation/routes.ts
  packages/suite-native-home/src/screens/HomeDemoScreen.tsx
  packages/suite-native-home/src/screens/HomeScreen.tsx
  packages/suite-native-home/tsconfig.json
  packages/suite-native-navigation-root/src/dummyScreens/HomeScreen.tsx
  packages/suite-native-navigation-root/src/navigation/RootTabNavigator.tsx
  packages/suite-native-navigation-root/src/navigation/routes.ts
  packages/suite-native-navigation/src/components/Screen.tsx
  packages/suite-native-navigation/src/components/ScreenHeader.tsx
  packages/suite-native-navigation/src/components/TabBar.tsx
  packages/suite-native-navigation/src/components/TabBarItem.tsx
  packages/suite-native-navigation/src/config.ts
  packages/suite-native-navigation/src/index.ts
  packages/suite-native-settings/src/components/ApplicationSettings.tsx
  packages/suite-native-settings/src/components/CoinsSettings.tsx
  packages/suite-native-settings/src/components/DeviceActionButtons.tsx
  packages/suite-native-settings/src/components/DeviceSettings.tsx
  packages/suite-native-settings/src/components/SettingsSection.tsx
  packages/suite-native-settings/src/components/SettingsSectionItem.tsx
  packages/suite-native-settings/src/navigation/SettingsStackNavigator.tsx
  packages/suite-native-settings/src/navigation/routes.ts
  packages/suite-native-settings/src/screens/SettingsAdvancedScreen.tsx
  packages/suite-native-settings/src/screens/SettingsDetailScreen.tsx
  packages/suite-native-settings/src/screens/SettingsLabelingScreen.tsx
  packages/suite-native-settings/src/screens/SettingsLocalisationScreen.tsx
  packages/suite-native-settings/src/screens/SettingsScreen.tsx
  packages/theme/src/spacings.ts
Labels: mobile-app

#5572 test(e2e): check-xpub-VTC
  packages/integration-tests/projects/suite-web/tests/wallet/check-xpub-vtc.test.ts
Labels: e2e

#5665 chore(connect): remove webusb dead code
  packages/connect-web/src/index.ts
  packages/connect-web/src/webusb/button.ts
  packages/connect-web/src/webusb/index.ts
Labels: READY FOR MERGE

#5641 chore: update connect-examples
  packages/connect-examples/.gitignore
  packages/connect-examples/README.md
  packages/connect-examples/browser-inline-script/README.md
  packages/connect-examples/browser-inline-script/index.html
  packages/connect-examples/electron-main-process/package.json
  packages/connect-examples/electron-main-process/yarn.lock
  packages/connect-examples/electron-renderer-with-assets/package.json
  packages/connect-examples/electron-renderer-with-assets/src/electron.js
  packages/connect-examples/electron-renderer-with-assets/webpack/config.dev.js
  packages/connect-examples/electron-renderer-with-assets/webpack/config.prod.js
  packages/connect-examples/electron-renderer-with-assets/yarn.lock
  packages/connect-examples/electron-renderer-with-popup/README.md
  packages/connect-examples/electron-renderer-with-popup/yarn.lock
  packages/connect-examples/node/README.md
  packages/connect-examples/node/package.json
  packages/connect-examples/webextension/README.md
  packages/connect-examples/webextension/README_2.md
  packages/connect-examples/webextension/manifest-firefox.json
  packages/connect-examples/webextension/manifest.json
  packages/connect-examples/webextension/package.json
  packages/connect-examples/webextension/trezor-usb-permissions.html
  packages/connect-examples/webextension/update.js
  packages/connect-examples/webextension/vendor/trezor-connect.js
  packages/connect-examples/webextension/vendor/trezor-content-script.js
  packages/connect-examples/webextension/vendor/trezor-usb-permissions.js
  packages/connect-examples/webextension/yarn.lock
  packages/connect/README.md
Labels: READY FOR REVIEW

#5688 fix(dependabot): update playwright lib to fix security issue
  packages/integration-tests/package.json
  yarn.lock
Labels: dependencies

#5690 chore: move RN gitignore to root
  .gitignore
  .prettierignore
  suite-native/app/.gitignore
Labels: mobile-app

#5678 Feat: Tab bar
  packages/icons/assets/icons/actionHorizontal.svg
  packages/icons/assets/icons/discover.svg
  packages/icons/assets/icons/home.svg
  packages/icons/assets/icons/trezorT.svg
  packages/icons/src/icons.ts
  suite-native/navigation-root/src/navigation/routes.ts
  suite-native/navigation/src/ActionTabBarItem.tsx
  suite-native/navigation/src/components/ActionTabBarItem.tsx
  suite-native/navigation/src/components/TabBar.tsx
  suite-native/navigation/src/components/TabBarItem.tsx
  suite-native/navigation/src/types.tsx
Labels: mobile-app

#5692 fix: fix relative paths for RN in gitignore
  .gitignore
  packages/transport-native/.gitignore
Labels: mobile-app

#5686 chore(suite-native): packages renaming, remove navigation-root
  .gitignore
  .prettierignore
  packages/components/package.json
  packages/suite/package.json
  suite-native/app/.eslintrc.js
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  suite-native/app/src/dummyScreens/AccountsScreen.tsx
  suite-native/app/src/dummyScreens/ActionScreen.tsx
  suite-native/app/src/dummyScreens/PricesScreen.tsx
  suite-native/app/src/navigation/RootTabNavigator.tsx
  suite-native/app/src/navigation/navigationMap.d.ts
  suite-native/app/src/navigation/routes.ts
  suite-native/app/tsconfig.json
  suite-native/module-home/package.json
  suite-native/module-settings/package.json
  suite-native/navigation-root/jest.config.js
  suite-native/navigation-root/package.json
  suite-native/navigation-root/src/index.ts
  suite-native/navigation-root/tsconfig.json
  suite-native/navigation/src/components/TabBar.tsx
  suite-native/navigation/src/types.tsx
Labels: mobile-app

#5691 test(e2e): custom-firmware
  docker/docker-compose.suite-ci.yml
  docker/test-runner/Dockerfile
  docker/wait-for-env.sh
  packages/integration-tests/package.json
  packages/integration-tests/projects/suite-web/fixtures/testFirmware.bin
  packages/integration-tests/projects/suite-web/run_tests.js
  packages/integration-tests/projects/suite-web/support/index.ts
  packages/integration-tests/projects/suite-web/tests/settings/custom-firmware.test.ts
  yarn.lock
Labels: e2e

#5700 fix(atom): Fix floating label animation in text input
  suite-native/atoms/src/Input/Input.tsx
Labels: mobile-app

#5680 feat(suite-native): Create device settings screen
  suite-native/module-settings/src/components/DeviceSettings.tsx
  suite-native/module-settings/src/navigation/SettingsStackNavigator.tsx
  suite-native/module-settings/src/navigation/routes.ts
  suite-native/module-settings/src/screens/SettingsCustomizationScreen.tsx
  suite-native/module-settings/src/screens/SettingsDangerAreaScreen.tsx
  suite-native/module-settings/src/screens/SettingsSecurityScreen.tsx
Labels: mobile-app

#5703 test(e2e): import btc csv
  packages/integration-tests/projects/suite-web/fixtures/btcTest.csv
  packages/integration-tests/projects/suite-web/plugins/index.js
  packages/integration-tests/projects/suite-web/tests/wallet/import-btc-csv.test.ts
Labels: e2e

#5706 fix(ios): Set correct bundle id and provisioning for develop scheme
  suite-native/app/ios/TrezorSuite.xcodeproj/project.pbxproj
  suite-native/app/ios/TrezorSuite/Info.plist
Labels: mobile-app

#5719 vd/fix suite native ci
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
Labels: mobile-app

#5721 fix(ci): set same ruby version for workflow as is in the gemfile
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
Labels: mobile-app

#5723 feat(ios): Prepare iOS fastlane for CI build
  .gitignore
  suite-native/app/android/fastlane/Fastfile
  suite-native/app/fastlane/Appfile
  suite-native/app/fastlane/Fastfile
  suite-native/app/ios/fastlane/Fastfile
Labels: mobile-app

#5717 test(e2e):look-up-account
  packages/integration-tests/projects/suite-web/tests/wallet/look-up-an-account.test.ts
Labels: e2e
