Repository trezor/trezor-suite, pull requests merged in 2022-11, with the labels that each got.

#6734 feat(suite): add trezor coinjoin terms url
  packages/suite/src/views/wallet/anonymize/components/CoinjoinSetupStrategies.tsx
  packages/urls/src/urls.ts
Labels: bitcoin

#6743 fix(suite): add fallback value for lowestAnonymity
  packages/suite/src/utils/wallet/coinjoinUtils.ts
Labels: bug

#6744 Loading fix in AddCoinJoinAccountButton
  packages/suite/src/components/suite/modals/AddAccount/components/AddCoinJoinAccountButton.tsx
Labels: bug, account

#6749 fix: graph overflow + app portrait only
  suite-native/app/android/app/src/main/AndroidManifest.xml
  suite-native/app/ios/Podfile.lock
  suite-native/app/ios/TrezorSuite/Info.plist
  suite-native/graph/src/components/Graph.tsx
Labels: mobile-app

#6753 chore(suite-native): Remove button discover assets
  suite-native/module-accounts/src/screens/AccountsScreen.tsx
Labels: mobile-app

#6758 feat(ios): Add changelog for testflight testers
  suite-native/app/ios/Podfile.lock
  suite-native/app/ios/fastlane/Fastfile
Labels: mobile-app

#6754 chore(suite-native): Remove import another assets in onboarding
  suite-native/module-accounts-import/src/components/AccountImportDetail.tsx
Labels: mobile-app

#6761 chore: remove graph empty point
  suite-native/graph/src/components/Graph.tsx
Labels: mobile-app

#6721 feat(suite-native): Add already imported account section
  suite-common/wallet-core/package.json
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/components/AccountAlreadyImported.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummary.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummarySection.tsx
  suite-native/module-accounts-import/src/screens/AccountsImportScreen.tsx
  suite-native/module-accounts-import/tsconfig.json
  suite-native/navigation/src/types.tsx
  yarn.lock
Labels: mobile-app

#6774 test: fix e2e in transport
  packages/transport/e2e/jest.config.ts
  packages/transport/e2e/run.ts
  packages/transport/package.json
  yarn.lock
Labels: e2e

#6763 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#6776 chore(suite-native): Add comments for navigation type refactors
  suite-native/module-accounts-import/src/components/AccountAlreadyImported.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
Labels: mobile-app

#6777 Feat/remove asset during onboarding
  packages/icons/assets/icons/trash.svg
  packages/icons/src/icons.ts
  suite-native/module-accounts-import/src/components/AccountImportOverview.tsx
Labels: mobile-app

#6789 feat(graph): Add better error messages
  suite-common/wallet-graph/src/graphReducer.ts
  suite-common/wallet-graph/src/graphUtils.ts
  suite-native/app/ios/Podfile.lock
  suite-native/graph/src/components/Graph.tsx
  suite-native/module-accounts/src/components/AccountDetailHeader.tsx
  suite-native/module-home/src/components/PortfolioGraph.tsx
Labels: mobile-app

#6795 feat(graph): Add graph error component
  suite-native/graph/src/components/GraphError.tsx
  suite-native/module-accounts/src/components/AccountDetailHeader.tsx
  suite-native/module-home/src/components/PortfolioGraph.tsx
Labels: mobile-app

#6773 feat(suite): access allowedInputAmounts from coinjoin status
  packages/coinjoin/src/client/Status.ts
  packages/coinjoin/src/constants.ts
  packages/coinjoin/src/types/client.ts
  packages/coinjoin/src/utils/roundUtils.ts
  packages/coinjoin/tests/client/Status.test.ts
  packages/suite/src/components/wallet/CoinControl/UtxoSelection.tsx
  packages/suite/src/reducers/wallet/coinjoinReducer.ts
  packages/suite/src/services/coinjoin/config.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/wallet/coinjoinUtils.ts
Labels: bitcoin

#6793 feat(suite-native): Add debug info component
  suite-native/app/android/fastlane/Fastfile
  suite-native/app/fastlane/Fastfile
  suite-native/app/ios/fastlane/Fastfile
  suite-native/config/src/debugUtils.ts
  suite-native/config/src/environment.ts
  suite-native/config/src/index.ts
  suite-native/module-dev-utils/src/components/BuildInfo.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
Labels: mobile-app

#6797 fix(fastlane): Fix no implicit conversion of Integer into String
  suite-native/app/android/fastlane/Fastfile
  suite-native/app/ios/fastlane/Fastfile
Labels: mobile-app

#6801 fix(graph): Add zero fiat rates fallback for coins without ticker config
  suite-common/wallet-graph/src/graphUtils.ts
  suite-native/module-home/src/components/PortfolioGraph.tsx
Labels: mobile-app

#6380 test(invity): Integration Test Exchange
  packages/suite-web/e2e/fixtures/invity/buy/list.json
  packages/suite-web/e2e/fixtures/invity/buy/quotes.json
  packages/suite-web/e2e/fixtures/invity/buy/trade.json
  packages/suite-web/e2e/fixtures/invity/exchange/coins.json
  packages/suite-web/e2e/fixtures/invity/exchange/list.json
  packages/suite-web/e2e/fixtures/invity/exchange/quotes.json
  packages/suite-web/e2e/fixtures/invity/exchange/trade.json
  packages/suite-web/e2e/fixtures/invity/exchange/watch.json
  packages/suite-web/e2e/support/commands.ts
  packages/suite-web/e2e/support/utils/fixtures.ts
  packages/suite-web/e2e/support/utils/intercept-invity-api.ts
  packages/suite-web/e2e/tests/coinmarket/exchange.test.ts
  packages/suite/src/components/suite/modals/ReviewTransaction/components/OutputList.tsx
  packages/suite/src/components/suite/modals/confirm/CoinmarketBuyTerms/index.tsx
  packages/suite/src/components/suite/modals/confirm/CoinmarketExchangeTerms/index.tsx
  packages/suite/src/components/wallet/CoinmarketExchangeOfferInfo/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/Navigation/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Footer/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/FiatInput/FiatSelect/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/FiatInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/ReceiveCryptoSelect/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoInput/SendCryptoSelect/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/detail/components/PaymentSuccessful/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/List/Quote/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/SelectedOffer/components/SendTransaction/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/SelectedOffer/components/VerifyAddress/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/SelectedOffer/index.tsx
Labels: +Invity, e2e

#6822 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: release, translations

#6778 Refactor/home screen
  suite-native/app/ios/Podfile.lock
  suite-native/app/src/navigation/AppTabNavigator.tsx
  suite-native/app/src/navigation/dummyScreens/PricesScreen.tsx
  suite-native/app/src/navigation/routes.ts
  suite-native/assets/src/components/Assets.tsx
  suite-native/atoms/src/Button/Button.tsx
  suite-native/atoms/src/DashboardSection.tsx
  suite-native/graph/src/components/TimeSwitchItem.tsx
  suite-native/module-home/src/components/DashboardHeader.tsx
  suite-native/module-home/src/components/PortfolioGraphHeader.tsx
  suite-native/module-home/src/screens/HomeScreen.tsx
  suite-native/navigation/src/components/TabBar.tsx
  suite-native/navigation/src/components/TabBarItem.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
Labels: mobile-app

#6807 fix(graph): Btc test break portfolio graph
  suite-common/wallet-graph/src/graphThunks.ts
  suite-common/wallet-graph/src/graphUtils.ts
  suite-native/app/src/App.tsx
Labels: mobile-app

#6862 fix(suite): fix utxos displayed per page in coin control
  packages/suite/src/views/wallet/send/components/Options/components/BitcoinOptions/components/CoinControl.tsx
Labels: bug

#6737 Test/coinjoin final 2
  ci/test.yml
  docker/docker-suite-desktop-test.sh
  packages/suite-desktop/e2e/playwright.config.ts
  packages/suite-desktop/e2e/support/common.ts
  packages/suite-desktop/e2e/tests/coinjoin.test.ts
Labels: e2e

#6868 test(suite-web): remove portfolio-check test
  packages/suite-web/e2e/tests/dashboard/portfolio-check.test.ts
Labels: e2e

#6866 fix(suite-native): Adding missing crypto sign balances
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/app/ios/Podfile.lock
  suite-native/module-accounts-import/src/components/AccountImportOverview.tsx
Labels: mobile-app

#6882 chore(suite-native): Remove icons
  suite-native/module-home/src/components/DashboardHeader.tsx
Labels: mobile-app

#6888 refactor(suite-native): Refactor crypto amount formatter to use symbol
  packages/suite/src/components/suite/FormattedCryptoAmount.tsx
  suite-common/formatters/README.md
  suite-common/formatters/src/formatters/prepareCryptoAmountFormatter.ts
  suite-native/accounts/src/components/AccountBalance.tsx
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/module-accounts-import/src/components/AccountImportOverview.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx
  suite-native/transactions/src/screens/TransactionDetailScreen.tsx
Labels: mobile-app

#6897 feat(coinjoin): rename coinjoin account type
  packages/suite-desktop/e2e/tests/coinjoin.test.ts
  suite-common/wallet-config/src/networksConfig.ts
Labels: low hanging fruit

#6893 Fix change address detection
  packages/suite/src/components/wallet/CoinControl/UtxoSelection.tsx
Labels: bug

#6919 fix(suite): fix joint transaction icon
  packages/suite/src/components/wallet/TransactionItem/components/TransactionTypeIcon.tsx
Labels: UI

#6948 chore: exit tests properly
  packages/connect/e2e/run.ts
  packages/transport/e2e/run.ts
Labels: ci

#6951 refactor(suite-native): Use icons screen in app
  suite-native/module-accounts-import/src/components/AccountImportHeader.tsx
  suite-native/module-accounts/src/components/AccountDetailScreenHeader.tsx
  suite-native/module-settings/src/screens/SettingsCustomizationScreen.tsx
  suite-native/navigation/src/components/ScreenHeader.tsx
Labels: mobile-app

#6946 chore(mobile): update Skia
  packages/icons/package.json
  packages/icons/src/components/Icon.tsx
  suite-native/app/package.json
  suite-native/graph/package.json
  yarn.lock
Labels: mobile-app

#6929 Update excludedUtxos on every account update in send form
  packages/suite/src/actions/wallet/send/sendFormBitcoinActions.ts
  packages/suite/src/hooks/wallet/useSendForm.ts
  packages/suite/src/hooks/wallet/useSendFormCompose.ts
  suite-common/test-utils/src/mocks.ts
  suite-common/wallet-utils/src/__tests__/sendFormUtils.test.ts
  suite-common/wallet-utils/src/sendFormUtils.ts
Labels: bug, send

#6965 Tag UTXOs in pending transaction in coin control
  packages/components/src/components/Icon/icons.ts
  packages/components/src/images/icons/clock.svg
  packages/components/src/images/icons/clock_active.svg
  packages/suite/src/components/wallet/CoinControl/UtxoSelection.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/Status/index.tsx
  packages/suite/src/components/wallet/TransactionItem/components/TransactionTypeIcon.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/onboarding/steps/Welcome/components/PreOnboardingSetup/SecurityCheck.tsx
Labels: feature, send

#6996 fix: missing symbol in erc tokens list if name matches symbol
  packages/suite/src/views/wallet/tokens/components/TokenList.tsx
Labels: ERC20

#7021 fix(suite-native): unify navigation versions
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  yarn.lock
Labels: mobile-app

#6962 feat(suite-native): Enable more coins for mobile app
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/app/src/App.tsx
  suite-native/config/src/enabledNetworks.ts
  suite-native/module-accounts-import/src/components/DevXpub.tsx
  suite-native/module-accounts-import/src/components/XpubImportSection.tsx
  suite-native/module-accounts-import/src/components/XpubScanHeader.tsx
  suite-native/module-accounts-import/src/screens/AccountsImportScreen.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-accounts/src/screens/AccountsScreen.tsx
Labels: mobile-app

#7040 fix(mobile): submit button is always visible for submit xpub
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
Labels: mobile-app

#7053 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/he.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#7056 chore(mobile): use expo camera instead of vision-camera
  suite-native/app/android/app/build.gradle
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/screens/ScanQRCodeModalScreen.tsx
  suite-native/module-accounts-import/tsconfig.json
  suite-native/qr-code-scanner/package.json
  suite-native/qr-code-scanner/src/components/CameraPermissionError.tsx
  suite-native/qr-code-scanner/src/components/QRCodeScanner.tsx
  suite-native/qr-code-scanner/src/hooks/useCameraPermission.ts
  suite-native/qr-code-scanner/src/index.ts
  suite-native/qr-code-scanner/tsconfig.json
  yarn.lock
Labels: mobile-app
