Repository trezor/trezor-suite, pull requests merged in 2022-10, with the labels that each got.

#6382 chore(e2e): refactor add accounts test
  packages/integration-tests/projects/suite-web/support/pageObjects/accountsObject.ts
  packages/integration-tests/projects/suite-web/support/pageObjects/settingsCryptoObject.ts
  packages/integration-tests/projects/suite-web/support/pageObjects/topBarObject.ts
  packages/integration-tests/projects/suite-web/tests/wallet/add-account-types.test.ts
  packages/suite/src/components/wallet/AccountsMenu/AccountSearchBox.tsx
Labels: e2e

#6467 feat(suite-guide): update suite guide version
  packages/suite-data/src/guide/constants.ts
Labels: release

#6453 feat(suite): add anonymitySet to Account.addresses
  packages/suite/src/services/coinjoin/coinjoinBackend.ts
  suite-common/wallet-types/src/account.ts
Labels: READY FOR REVIEW

#6329 feat(connect): ~~add versionChannel init option~~ connectSrc test
  ci/test.yml
  packages/connect-web/e2e/playwright.config.ts
  packages/connect-web/e2e/tests/init.test.ts
  packages/connect-web/package.json
  yarn.lock
Labels: connect

#6468 Fix `getAccountBalanceHistory` for joint txs with electrum backend
  packages/blockchain-link/src/workers/electrum/methods/getAccountBalanceHistory.ts
Labels: release

#6469 fix(suite): align text
  packages/suite/src/views/recovery/index.tsx
Labels: bug, release

#6472 fix(suite): fix send review modal ui
  packages/suite/src/components/suite/modals/ReviewTransaction/components/OutputList.tsx
  packages/suite/src/components/suite/modals/ReviewTransaction/index.tsx
Labels: UI

#6443 feat(connect): add setBusy method
  .github/workflows/connect-test.yml
  ci/test.yml
  docs/packages/connect/methods/setBusy.md
  packages/connect/e2e/tests/device/setBusy.test.ts
  packages/connect/src/api/index.ts
  packages/connect/src/api/setBusy.ts
  packages/connect/src/factory.ts
  packages/connect/src/types/api/index.ts
  packages/connect/src/types/api/setBusy.ts
Labels: READY FOR REVIEW

#6479 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ja.json
  packages/suite/src/support/messages.ts
Labels: translations

#6455 feat(coinjoin): add http module
  packages/coinjoin/src/utils/http.ts
  packages/coinjoin/tests/mocks/server.ts
  packages/coinjoin/tests/utils/http.test.ts
Labels: READY FOR REVIEW

#6471 Unable to reset backend to default fix
  packages/suite/src/actions/wallet/selectedAccountActions.ts
  packages/suite/src/hooks/settings/backends/useBackendsForm.ts
  suite-common/wallet-core/src/blockchain/blockchainActions.ts
  suite-common/wallet-core/src/blockchain/blockchainReducer.ts
Labels: release

#6487 Fix daily sum with joint transactions
  suite-common/wallet-utils/src/transactionUtils.ts
Labels: release

#6488 fix(suite): fix inconsistent state when user switch wallets with default accounts closed
  packages/suite/src/components/wallet/AccountsMenu/AccountGroup.tsx
  packages/suite/src/components/wallet/AccountsMenu/index.tsx
Labels: release

#6502 fix(invity): disable the Go to provider button while waiting for BE response
  packages/suite/src/hooks/wallet/useCoinmarketP2pOffers.ts
  packages/suite/src/types/wallet/coinmarketP2pOffers.ts
  packages/suite/src/views/wallet/coinmarket/p2p/offers/SelectedOffer/GetStartedStep.tsx
  packages/suite/src/views/wallet/coinmarket/p2p/offers/SelectedOffer/ReceivingAddressStep.tsx
Labels: +Invity, release

#6503 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/he.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#6490 feat(components): add TooltipButton
  packages/components/src/components/buttons/TooltipButton.tsx/index.stories.tsx
  packages/components/src/components/buttons/TooltipButton.tsx/index.tsx
  packages/components/src/index.ts
  packages/suite/src/components/suite/modals/AddAccount/components/AddButton.tsx
Labels: components

#6505 chore(suite-native): Add missing coin icons to match NetworkSymbol an…
  packages/icons/assets/cryptoIcons/ada.svg
  packages/icons/assets/cryptoIcons/nmc.svg
  packages/icons/assets/cryptoIcons/regtest.svg
  packages/icons/assets/cryptoIcons/tada.svg
  packages/icons/src/icons.ts
  suite-native/module-accounts-import/src/components/AccountImportOverview.tsx
Labels: mobile-app

#6499 feat(suite-native): Empty state for transaction list
  suite-native/app/ios/TrezorSuite.xcodeproj/project.pbxproj
  suite-native/app/package.json
  suite-native/atoms/package.json
  suite-native/module-graph/package.json
  suite-native/test-utils/package.json
  suite-native/transactions/src/components/TransactionsList/TransactionList.tsx
  yarn.lock
Labels: mobile-app

#6517 feat(suite-native): Integrate fiat currencies into app
  suite-common/formatters/src/formatters/prepareFiatAmountFormatter.ts
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AccountBalance.tsx
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/accounts/tsconfig.json
  suite-native/atoms/src/AssetItem.tsx
  suite-native/module-graph/package.json
  suite-native/module-graph/src/components/PortfolioGraph.tsx
  suite-native/module-graph/tsconfig.json
  suite-native/module-home/package.json
  suite-native/module-home/src/components/Assets.tsx
  suite-native/module-home/tsconfig.json
  yarn.lock
Labels: mobile-app

#6530 chore(suite-native): Use fiat currency but allow different value
  suite-common/formatters/package.json
  suite-common/formatters/src/formatters/prepareFiatAmountFormatter.ts
  suite-common/formatters/src/types.ts
  suite-common/formatters/tsconfig.json
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AccountBalance.tsx
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/accounts/tsconfig.json
  suite-native/app/src/hooks/useFormattersConfig.ts
  suite-native/atoms/src/AssetItem.tsx
  suite-native/module-graph/package.json
  suite-native/module-graph/src/components/PortfolioGraph.tsx
  suite-native/module-graph/tsconfig.json
  suite-native/module-home/src/components/Assets.tsx
  suite-native/module-settings/src/slice.ts
  yarn.lock
Labels: mobile-app

#6495 chore(invity): unify formatting of fiat and crypto amounts
  packages/suite/src/components/wallet/CoinmarketBuyOfferInfo/index.tsx
  packages/suite/src/components/wallet/CoinmarketSellOfferInfo/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/List/Quote/index.tsx
  packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/List/index.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketCryptoAmount.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketFiatAmount.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/List/Quote/index.tsx
  packages/suite/src/views/wallet/coinmarket/p2p/offers/List/Quote.tsx
  packages/suite/src/views/wallet/coinmarket/p2p/offers/List/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/offers/Offers/List/Quote/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/offers/Offers/List/index.tsx
Labels: +Invity

#6513 test(e2e): xpub test refactor
  packages/integration-tests/projects/suite-web/support/pageObjects/accountsObject.ts
  packages/integration-tests/projects/suite-web/tests/wallet/check-coins-xpub.test.ts
  packages/integration-tests/projects/suite-web/tests/wallet/check-xpub-ada.test.ts
  packages/integration-tests/projects/suite-web/tests/wallet/check-xpub-btc.test.ts
  packages/integration-tests/projects/suite-web/tests/wallet/check-xpub-ltc.test.ts
  packages/integration-tests/projects/suite-web/tests/wallet/check-xpub-vtc.test.ts
  packages/suite/src/components/suite/modals/AddAccount/components/MoreCoins.tsx
Labels: e2e

#6508 feat(suite): Coinjoin account info selector
  packages/suite/src/components/wallet/CoinjoinSummary/BalancePrivacyBreakdown.tsx
  packages/suite/src/components/wallet/CoinjoinSummary/BalanceSection.tsx
  packages/suite/src/components/wallet/PrivacyAccount/AnonymityIndicator.tsx
  packages/suite/src/components/wallet/PrivacyAccount/CryptoAmountWithHeader.tsx
  packages/suite/src/reducers/wallet/coinjoinReducer.ts
  packages/suite/src/reducers/wallet/selectedAccountReducer.ts
  packages/suite/src/utils/wallet/__tests__/coinjoinUtils.test.ts
  packages/suite/src/utils/wallet/coinjoinUtils.ts
Labels: code

#6540 feat(suite): add Buy button to Portfolio dashboard
  packages/suite/src/support/messages.ts
  packages/suite/src/views/dashboard/components/PortfolioCard/components/Header.tsx
  packages/suite/src/views/dashboard/components/PortfolioCard/index.tsx
Labels: +Invity

#6559 fix(suite): make account group collapsible even if it has account with balance
  packages/suite/src/components/wallet/AccountsMenu/AccountGroup.tsx
Labels: release

#6543 fix(suite): fix application log modal scroll
  packages/suite/src/components/suite/modals/ApplicationLog.tsx
Labels: UI

#6549 refactor(suite-native): Style xpub screen according to design
  packages/theme/src/types.ts
  suite-native/atoms/src/Chip.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
Labels: mobile-app

#6570 Crowdin translations update
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/ru.json
Labels: translations

#6592 Fix transaction list styles
  suite-native/module-accounts/package.json
  suite-native/module-accounts/src/components/AccountDetailHeader.tsx
  suite-native/module-accounts/tsconfig.json
  suite-native/transactions/src/components/TransactionsList/TransactionList.tsx
  yarn.lock
Labels: mobile-app

#6607 fix(suite-native): React redux version mismatch
  suite-native/module-send-receive/package.json
  yarn.lock
Labels: mobile-app

#6608 fix(trezor-suite): Deduplicate metro bundler
  package.json
  yarn.lock
Labels: mobile-app

#6593 fix(suite-native): Pending transactions
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  suite-native/app/tsconfig.json
  suite-native/config/package.json
  suite-native/config/src/enabledNetworks.ts
  suite-native/config/src/index.ts
  suite-native/config/tsconfig.json
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/state/package.json
  suite-native/state/src/extraDependencies.ts
  suite-native/state/tsconfig.json
  yarn.lock
Labels: mobile-app

#6623 E2e fixes
  packages/suite-web/e2e/cypress.config.ts
  packages/suite-web/e2e/support/commands.ts
  packages/suite-web/e2e/tests/wallet/coin-balance.test.ts
Labels: e2e

#6638 fix(coinmarket): fix handling in progress states of savings flow
  packages/suite/src/actions/wallet/pollingActions.ts
  packages/suite/src/constants/wallet/coinmarket/savings.ts
  packages/suite/src/hooks/wallet/useCoinmarketSavingsSetup.ts
  packages/suite/src/hooks/wallet/useCoinmarketSavingsSetupContinue.ts
  packages/suite/src/hooks/wallet/useCoinmarketSavingsSetupWaiting.ts
  packages/suite/src/middlewares/wallet/coinmarketSavingsMiddleware.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/savings/setup/components/AllFeesIncluded.tsx
  packages/suite/src/views/wallet/coinmarket/savings/setup/continue/index.tsx
  packages/suite/src/views/wallet/coinmarket/savings/setup/index.tsx
Labels: READY FOR REVIEW, +Invity

#6644 CoinJoin - multiple CJ accounts interference fix
  packages/coinjoin/src/backend/CoinjoinBackend.ts
  packages/suite/src/actions/wallet/coinjoinAccountActions.ts
  packages/suite/src/components/wallet/WalletLayout/index.tsx
Labels: bug

#6669 feat(suite-native): Add keyboard aware scrollview
  suite-native/navigation/package.json
  suite-native/navigation/src/components/ScreenContent.tsx
  yarn.lock
Labels: mobile-app

#6670 chore(suite-native): Fix local build problems
  suite-native/app/ios/Podfile
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  yarn.lock
Labels: mobile-app

#6680 fix(suite-native): ios build
  suite-native/app/ios/Podfile
  suite-native/app/ios/Podfile.lock
Labels: mobile-app

#6679 Feat/remove settings sections
  suite-native/module-dev-utils/package.json
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-dev-utils/tsconfig.json
  suite-native/module-settings/src/components/ApplicationSettings.tsx
  suite-native/module-settings/src/components/DeviceSettings.tsx
  suite-native/module-settings/src/index.ts
  suite-native/module-settings/src/navigation/SettingsStackNavigator.tsx
  suite-native/module-settings/src/screens/SettingsLabelingScreen.tsx
  suite-native/module-settings/src/screens/SettingsScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile-app

#6585 feat(suite-native): Process account balance history data to graph points
  suite-common/test-utils/src/extraDependenciesMock.ts
  suite-common/wallet-graph/package.json
  suite-common/wallet-graph/src/__fixtures__/accountBalanceHistory.ts
  suite-common/wallet-graph/src/__fixtures__/graphPoints.ts
  suite-common/wallet-graph/src/__fixtures__/timeFrameItems.ts
  suite-common/wallet-graph/src/__tests__/graph.test.ts
  suite-common/wallet-graph/src/config.ts
  suite-common/wallet-graph/src/constants.ts
  suite-common/wallet-graph/src/graphActions.ts
  suite-common/wallet-graph/src/graphReducer.ts
  suite-common/wallet-graph/src/graphThunks.ts
  suite-common/wallet-graph/src/graphUtils.ts
  suite-common/wallet-graph/src/index.ts
  suite-common/wallet-graph/src/types.ts
  suite-common/wallet-graph/tsconfig.json
  suite-common/wallet-utils/package.json
  suite-common/wallet-utils/src/accountUtils.ts
  suite-native/accounts/src/components/AccountBalance.tsx
  suite-native/app/ios/Podfile.lock
  suite-native/graph/src/components/AxisLabel.tsx
  suite-native/graph/src/components/Graph.tsx
  suite-native/module-accounts/package.json
  suite-native/module-accounts/src/components/AccountDetailHeader.tsx
  suite-native/module-accounts/tsconfig.json
  suite-native/module-home/package.json
  suite-native/module-home/src/components/PortfolioGraph.tsx
  suite-native/module-home/tsconfig.json
  suite-native/state/src/reducers.ts
  yarn.lock
Labels: mobile-app

#6678 feat(suite-guide): update suite guide version
  packages/suite-data/src/guide/constants.ts
Labels: guide

#6695 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite/src/support/messages.ts
Labels: translations

#6705 feat(analytics): queue
  packages/analytics/src/analytics.ts
  packages/analytics/src/tests/analytics.test.ts
  packages/analytics/src/types.ts
Labels: data

#6591 feat(suite-native): Redesign onboarding
  packages/icons/assets/icons/qrCodeImport.svg
  packages/icons/src/components/Icon.tsx
  packages/icons/src/icons.ts
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AccountBalance.tsx
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/accounts/tsconfig.json
  suite-native/app/ios/Podfile.lock
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/assets/src/components/Assets.tsx
  suite-native/atoms/src/Button/Button.tsx
  suite-native/atoms/src/Button/IconButton.tsx
  suite-native/atoms/src/Divider.tsx
  suite-native/atoms/src/StepsProgressBar.tsx
  suite-native/atoms/src/TextDivider.tsx
  suite-native/atoms/src/index.ts
  suite-native/forms/src/fields/TextInputField.tsx
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/components/AccountImportDetail.tsx
  suite-native/module-accounts-import/src/components/AccountImportHeader.tsx
  suite-native/module-accounts-import/src/components/AccountImportLoader.tsx
  suite-native/module-accounts-import/src/components/AccountImportOverview.tsx
  suite-native/module-accounts-import/src/components/Camera.tsx
  suite-native/module-accounts-import/src/components/XpubImportSection.tsx
  suite-native/module-accounts-import/src/components/XpubScanHeader.tsx
  suite-native/module-accounts-import/src/navigation/AccountsImportStackNavigator.tsx
  suite-native/module-accounts-import/src/screens/AccountsImportScreen.tsx
  suite-native/module-accounts-import/src/screens/ScanQRCodeModalScreen.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-accounts-import/tsconfig.json
  suite-native/module-onboarding/src/screens/OnboardingIntroScreen.tsx
  suite-native/module-settings/src/components/ApplicationSettings.tsx
  suite-native/module-settings/src/components/DeviceSettings.tsx
  suite-native/module-settings/src/screens/SettingsAdvancedScreen.tsx
  suite-native/module-settings/src/screens/SettingsDangerAreaScreen.tsx
  suite-native/module-settings/src/screens/SettingsScreen.tsx
  suite-native/module-settings/src/screens/SettingsSecurityScreen.tsx
  suite-native/navigation/src/components/ScreenContent.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/navigation/src/types.tsx
  yarn.lock
Labels: mobile-app
