Repository trezor/trezor-suite, pull requests merged in 2022-04, with the labels that each got.

#5209 feat(guide): update articles
  packages/suite-data/src/guide/constants.ts
Labels: guide

#5224 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#5226 feat(autoupdate): enable to set custom autoupdate provider by URL for easier testing
  docs/packages/suite-desktop.md
  packages/suite-desktop/src-electron/modules/auto-updater.ts
Labels: release

#5222 Feat/cardano withdrawal deposit UI
  packages/suite/src/components/suite/modals/TransactionDetail/components/AmountDetails/index.tsx
  packages/suite/src/components/wallet/TransactionItem/components/Target/index.tsx
  packages/suite/src/components/wallet/TransactionItem/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/wallet/transactionUtils.ts
Labels: READY TO REVIEW, release

#5225 fix: sign message validation
  packages/suite/src/hooks/wallet/sign-verify/useSignVerifyForm.ts
  packages/validation/src/config.ts
Labels: READY TO REVIEW, release

#5248 feat(guide): update articles
  packages/suite-data/src/guide/constants.ts
Labels: release, guide

#5256 fix: tooltips above guide on mobile
  packages/components/src/components/Tooltip/index.tsx
  packages/components/src/config/variables.ts
  packages/integration-tests/projects/suite-web/tests/suite/tooltip.test.ts
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/components/ColHeader/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/DeviceItem/index.tsx
  packages/suite/src/components/suite/modals/Passphrase/components/PassphraseTypeCard/index.tsx
  packages/suite/src/views/guide/OpenGuideFromTooltip.tsx
  packages/suite/src/views/wallet/send/components/Options/components/BitcoinOptions/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/OpReturn/index.tsx
  packages/suite/src/views/wallet/send/components/Raw.tsx
Labels: READY TO MERGE

#5264 fix(browser-detection): scroll-y in small browser window
  packages/suite-data/src/browser-detection/styles.css
Labels: READY FOR REVIEW

#5223 tests(e2e): disable messaging system
  packages/integration-tests/projects/suite-web/support/commands.ts
  packages/integration-tests/projects/suite-web/tests/backup/t2-fail.test.ts
  packages/integration-tests/projects/suite-web/tests/backup/t2-misc.test.ts
  packages/integration-tests/projects/suite-web/tests/backup/t2-success.test.ts
  packages/integration-tests/projects/suite-web/tests/firmware/firmware.test.ts
  packages/integration-tests/projects/suite-web/tests/onboarding/t2-create-wallet.test.ts
  packages/integration-tests/projects/suite-web/tests/settings/t2-device-settings.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/guide.test.ts
  packages/integration-tests/projects/suite-web/tests/suite/safety-checks-warning.test.ts
  packages/integration-tests/projects/suite-web/tests/wallet/sign-and-verify.test.ts
Labels: READY FOR REVIEW

#5275 fix(browser-detection): do not use browser-detection styles in app
  packages/suite-data/browser-detection.webpack.ts
  packages/suite-data/src/browser-detection/index.ts
Labels: READY FOR REVIEW

#5265 fix: show guide in the firmware modal, refactor modal header
  packages/components/src/components/Modal/index.stories.tsx
  packages/components/src/components/Modal/index.tsx
  packages/suite/src/components/suite/Modal/RawRenderer.tsx
  packages/suite/src/components/suite/Modal/index.tsx
  packages/suite/src/components/suite/modals/PassphraseOnDevice/index.tsx
  packages/suite/src/components/suite/modals/PassphraseSource/index.tsx
  packages/suite/src/components/suite/modals/ReviewTransaction/index.tsx
  packages/suite/src/components/suite/modals/confirm/Action/index.tsx
  packages/suite/src/components/suite/modals/confirm/Address/index.tsx
  packages/suite/src/components/suite/modals/confirm/Fingerprint/index.tsx
  packages/suite/src/views/firmware/FirmwareCustom.tsx
  packages/suite/src/views/firmware/index.tsx
Labels: READY FOR REVIEW

#5276 chore: remove "_old" references from config files
  .gitignore
  .prettierignore
  packages/blockchain-link/.gitignore
  packages/blockchain-link/jest.config.unit.js
  packages/news-api/tsconfig.json
Labels: READY FOR REVIEW

#5278 fix(blockchain-link): missing ADA types
  packages/blockchain-link/CHANGELOG.md
  packages/blockchain-link/src/types/common.ts
Labels: READY FOR REVIEW

#5277 fix(integration-tests): adapt to tenv changes, fix flaky test
  packages/integration-tests/projects/connect-explorer/tests/fixtures.js
  packages/integration-tests/projects/suite-web/plugins/index.js
Labels: READY FOR REVIEW

#5281 feat(guide): add images to articles
  packages/suite-data/src/guide/constants.ts
Labels: guide

#5259 feat(theme): Add styling + theme package
  .gitignore
  .prettierignore
  .vscode/styles.code-snippets
  package.json
  packages/styles/README.md
  packages/styles/jest.config.js
  packages/styles/package.json
  packages/styles/src/StylesProvider.tsx
  packages/styles/src/breakpoints.test.ts
  packages/styles/src/breakpoints.ts
  packages/styles/src/contexts.tsx
  packages/styles/src/createRenderer.native.ts
  packages/styles/src/createRenderer.ts
  packages/styles/src/index.ts
  packages/styles/src/mediaQueries.ts
  packages/styles/src/mergeStyleObjects.ts
  packages/styles/src/mergeStyles.ts
  packages/styles/src/plugins/responsiveValues.test.ts
  packages/styles/src/plugins/responsiveValues.ts
  packages/styles/src/plugins/typedSelectors.test.ts
  packages/styles/src/plugins/typedSelectors.ts
  packages/styles/src/prepareStyle.ts
  packages/styles/src/processStyles.ts
  packages/styles/src/types.ts
  packages/styles/src/useDirection.ts
  packages/styles/src/useStyles.ts
  packages/styles/src/utils.test.ts
  packages/styles/src/utils.ts
  packages/styles/tsconfig.json
  packages/theme/README.md
  packages/theme/package.json
  packages/theme/src/borders.ts
  packages/theme/src/boxShadows.ts
  packages/theme/src/colors.ts
  packages/theme/src/fontFamilies.ts
  packages/theme/src/index.ts
  packages/theme/src/prepareTheme.ts
  packages/theme/src/sizes.ts
  packages/theme/src/spacings.ts
  packages/theme/src/typography.ts
  packages/theme/src/zIndices.ts
  packages/theme/tsconfig.json
  yarn.lock
Labels: READY FOR REVIEW
