Repository trezor/trezor-suite, pull requests merged in 2022-03, with the labels that each got.

#5024 chore: trezor-connect 8.2.8-beta.2
  packages/connect-explorer/package.json
  packages/suite-desktop/package.json
  packages/suite/package.json
  packages/suite/src/actions/wallet/discoveryActions.ts
  yarn.lock
Labels: READY TO REVIEW, release

#5026 fix(analytics): enrich onboarding analytics
  docs/misc/analytics.md
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/components/firmware/FirmwareInitial.tsx
  packages/suite/src/middlewares/recovery/recoveryMiddleware.ts
  packages/suite/src/types/onboarding/index.ts
  packages/suite/src/views/onboarding/steps/CreateOrRecover/index.tsx
  packages/suite/src/views/onboarding/steps/ResetDevice/index.tsx
Labels: READY TO REVIEW, release

#5028 fix(language): activate Japanese
  packages/suite/src/config/suite/languages.ts
Labels: READY TO REVIEW, release

#5033 fix(blockchain-link): set proxyAgent protocol to satisfy sentry wrapper
  packages/blockchain-link/src/workers/base.ts
Labels: READY TO REVIEW

#4971 fix: make coins device-agnostic when bootloader mode
  packages/suite/src/components/suite/CoinsGroup/CoinsList.tsx
Labels: READY TO REVIEW

#5044 chore: add missing params to cardano in connect-explorer
  packages/connect-explorer/src/js/data/methods/cardano/getAccountInfo.ts
Labels: READY TO REVIEW

#5048 fix: Fix the sentry-electron IPC error when Sentry is disabled in dev mode
  packages/suite-desktop/src-electron/app.ts
  packages/suite-desktop/src-electron/preload.ts
  packages/suite-desktop/src/index.tsx
  packages/suite/src/config/suite/sentry.ts
Labels: READY TO REVIEW

#5051 chore: remove unused translation string
  packages/suite/src/support/messages.ts
Labels: READY TO REVIEW

#5064 Crowdin translations update
  packages/suite-data/files/translations/af.json
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/da.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/el.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fi.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/he.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/no.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/zh.json
Labels: translations

#5079 fix: prevent rendering of staking component for non-cardano accounts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/staking/index.tsx
Labels: release

#5004 test(suite-web): cardano
  packages/integration-tests/projects/suite-web/snapshots/wallet/cardano.test.ts/cardano-account-details.snap.png
  packages/integration-tests/projects/suite-web/snapshots/wallet/cardano.test.ts/cardano-advanced-settings.snap.png
  packages/integration-tests/projects/suite-web/snapshots/wallet/cardano.test.ts/cardano-receive.snap.png
  packages/integration-tests/projects/suite-web/snapshots/wallet/cardano.test.ts/cardano-show-xpub.snap.png
  packages/integration-tests/projects/suite-web/snapshots/wallet/cardano.test.ts/cardano-tokens.snap.png
  packages/integration-tests/projects/suite-web/tests/wallet/cardano.test.ts
  packages/suite/src/components/suite/AccountFormCloseButton/index.tsx
  packages/suite/src/components/suite/SuiteLayout/index.tsx
Labels: READY TO REVIEW

#5085 Crowdin translations update
  packages/suite/src/support/messages.ts
Labels: translations

#5110 fix(suite): endless fetching of txs if txs length is a multiple of 25
  packages/suite/src/actions/wallet/transactionActions.ts
  packages/suite/src/views/wallet/transactions/components/TransactionList/index.tsx
Labels: READY TO REVIEW

#5093 fix(blockchain-link): throttle block events
  packages/blockchain-link/src/index.ts
  packages/blockchain-link/src/types/common.ts
  packages/blockchain-link/tests/unit/fixtures/notifications-blockbook.ts
  packages/blockchain-link/tests/unit/fixtures/notifications-blockfrost.ts
  packages/blockchain-link/tests/unit/fixtures/notifications-ripple.ts
  packages/blockchain-link/tests/unit/notifications.ts
Labels: READY TO REVIEW

#5077 feat: add missing methods to connect-explorer
  packages/connect-explorer/src/js/data/menu.ts
  packages/connect-explorer/src/js/data/methods/bitcoin/getPublicKey.ts
  packages/connect-explorer/src/js/data/methods/cardano/common.ts
  packages/connect-explorer/src/js/data/methods/cardano/getAccountInfo.ts
  packages/connect-explorer/src/js/data/methods/cardano/getAddress.ts
  packages/connect-explorer/src/js/data/methods/cardano/getNativeScriptHash.ts
  packages/connect-explorer/src/js/data/methods/cardano/getPublicKey.ts
  packages/connect-explorer/src/js/data/methods/cardano/index.ts
  packages/connect-explorer/src/js/data/methods/cardano/signTransaction.ts
  packages/connect-explorer/src/js/data/methods/ethereum/index.ts
  packages/connect-explorer/src/js/data/methods/ethereum/signTypedData.ts
Labels: READY TO REVIEW

#5120 chore(webpack): ignore "require in generated wasm module" warning from cardano-serialization-lib
  packages/suite-build/configs/base.webpack.config.ts
Labels: READY TO MERGE

#5124 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite/src/support/messages.ts
Labels: translations

#5166 test(e2e): review tx modal more screenshots
  packages/integration-tests/projects/suite-web/snapshots/wallet/review-transaction.test.ts/tada-confirm-address.snap.png
  packages/integration-tests/projects/suite-web/snapshots/wallet/review-transaction.test.ts/trop-confirm-address.snap.png
  packages/integration-tests/projects/suite-web/snapshots/wallet/review-transaction.test.ts/trop-token-confirm-address.snap.png
  packages/integration-tests/projects/suite-web/tests/wallet/review-transaction.test.ts
Labels: READY TO REVIEW

#5170 chore: update npm ignore
  packages/blockchain-link/.npmignore
  packages/rollout/.npmignore
  packages/transport/.npmignore
Labels: READY TO REVIEW

#5163 chore(ci): check branch name for '@' and '#'
  ci/environment.yml
  ci/scripts/check_branch_name.sh
Labels: READY TO MERGE

#5179 docs(transport): update protobuf related docs
  packages/transport/README.md
Labels: READY TO REVIEW

#5177 chore: update codeowners
  CODEOWNERS
Labels: READY TO MERGE

#5178 release: transport 1.1.2
  packages/connect-iframe/package.json
  packages/transport/CHANGELOG.md
  packages/transport/package.json
Labels: READY TO REVIEW

#5191 test(e2e): connect-explorer manual
  ci/build.yml
  ci/deploy.yml
Labels: READY TO REVIEW

#4957 feat: Add Yup, implement a Yup schema for the SignVerify form
  packages/suite/package.json
  packages/suite/src/components/wallet/InputError/index.tsx
  packages/suite/src/hooks/suite/useTranslation.ts
  packages/suite/src/hooks/wallet/sign-verify/useSignVerifyForm.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/utils/index.ts
  packages/suite/src/utils/wallet/__tests__/ethUtils.test.ts
  packages/suite/src/utils/wallet/ethUtils.ts
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Inputs/CryptoInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Inputs/FiatInput/index.tsx
  packages/suite/src/views/wallet/sign-verify/components/SignAddressInput.tsx
  packages/suite/src/views/wallet/sign-verify/index.tsx
  packages/suite/tsconfig.json
  packages/utils/src/index.ts
  packages/utils/src/isHex.ts
  packages/utils/tests/isAscii.test.ts
  packages/utils/tests/isHex.test.ts
  packages/validation/package.json
  packages/validation/src/config.ts
  packages/validation/src/index.ts
  packages/validation/src/types.ts
  packages/validation/tsconfig.json
  yarn.lock
Labels: READY TO REVIEW
