Repository trezor/trezor-suite, pull requests merged in 2022-07, with the labels that each got.

#5574 test(e2e): check-xpub-ADA
  packages/integration-tests/projects/suite-web/tests/wallet/check-xpub-ada.test.ts
Labels: e2e

#5725 fix(ci): suite-native develop workflow fix path to credential files
  .github/workflows/suite-native_develop_ci.yml
Labels: mobile-app

#5743 Fix/5675 select width
  packages/components/src/components/form/Select/index.tsx
Labels: bug, components

#5715 feat(atom): Bottom sheet modal animation
  suite-native/app/android/app/proguard-rules.pro
  suite-native/app/android/gradle.properties
  suite-native/app/ios/Podfile
  suite-native/app/ios/Podfile.lock
  suite-native/app/src/App.tsx
  suite-native/atoms/package.json
  suite-native/atoms/src/Modal/BottomModal.tsx
  suite-native/atoms/src/Modal/BottomModalContainer.tsx
  suite-native/atoms/src/Modal/useBottomModalAnimation.ts
  suite-native/atoms/src/Select/Select.tsx
  suite-native/module-home/src/screens/HomeDemoScreen.tsx
Labels: mobile-app

#5755 fix(auto-update): fix import of openpgp that was undefined after upgrade
  packages/suite-desktop/src-electron/libs/update-checker.ts
Labels: release

#5724 feat(ci): Add github action workflow for develop ios build
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
  suite-native/app/ios/fastlane/Fastfile
Labels: blocked, mobile-app

#5742 desktop tests - app spawns bundled bridge
  docker/docker-compose.suite-desktop-ci.yml
  docker/docker-compose.suite-desktop-test.yml
  packages/integration-tests/package.json
  packages/integration-tests/projects/suite-desktop/playwright.config.ts
  packages/integration-tests/projects/suite-desktop/tests/first.spec.ts
  packages/integration-tests/projects/suite-desktop/tests/spawn-bridge.test.js
  packages/suite-desktop/src-electron/libs/processes/BridgeProcess.ts
  packages/suite-desktop/src-electron/modules/bridge.ts
Labels: e2e

#5766 fix(ci): Build libs before Android build
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
Labels: mobile-app

#5767 chore(suite): add oauth description and clean up last migration
  README.md
  packages/suite/src/storage/CHANGELOG.md
  packages/suite/src/storage/migrations/index.ts
Labels: labelling

#5769 fix(auto-update): patch GitHub provider for electron-updater to make it backward compatible with pre-release without channels
  patches/electron-updater+5.0.5.patch
Labels: release

#5774 fix(suite): change auth server url
  packages/suite/src/actions/suite/constants/metadataConstants.ts
Labels: labelling, release

#5775 fix(suite): registerProtocolHandler in old browsers
  packages/suite/src/support/suite/Protocol.tsx
Labels: release

#5773 test(connect): add missing binance legacy results
  packages/integration-tests/projects/connect/__fixtures__/binanceGetAddress.ts
  packages/integration-tests/projects/connect/__fixtures__/binanceGetPublicKey.ts
Labels: connect

#5779 fix(ci) build libs for RN project
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
Labels: mobile-app

#5780 test(connect-popup): fix cardano sign test with latest fw
  packages/integration-tests/projects/connect-popup/tests/__fixtures__/methods.js
Labels: READY FOR REVIEW, READY FOR MERGE

#5783 feat(suite-native): Transaction Item
  suite-native/atoms/package.json
  suite-native/atoms/src/TransactionItem.tsx
  suite-native/atoms/src/index.ts
  suite-native/atoms/tsconfig.json
  suite-native/module-home/src/screens/HomeDemoScreen.tsx
  suite-native/module-home/src/screens/HomeScreen.tsx
Labels: mobile-app

#5785 Fix/transaction utils
  packages/suite/src/actions/suite/__tests__/storageActions.test.ts
  packages/suite/src/actions/wallet/__fixtures__/blockchainActions.ts
  packages/suite/src/actions/wallet/__tests__/transactionActions.test.ts
  packages/suite/src/actions/wallet/accountActions.ts
  packages/suite/src/actions/wallet/cardanoStakingActions.ts
  packages/suite/src/actions/wallet/fiatRatesActions.ts
  packages/suite/src/actions/wallet/transactionActions.ts
  packages/suite/src/components/suite/NotificationRenderer/renderers/TransactionRenderer.tsx
  packages/suite/src/reducers/wallet/transactionReducer.ts
  packages/suite/src/utils/wallet/__fixtures__/accountUtils.ts
  packages/suite/src/utils/wallet/__fixtures__/transactionUtils.ts
  packages/suite/src/utils/wallet/__tests__/accountUtils.test.ts
  packages/suite/src/utils/wallet/__tests__/transactionUtils.test.ts
  packages/suite/src/utils/wallet/accountUtils.ts
  packages/suite/src/utils/wallet/transactionUtils.ts
  packages/suite/src/views/wallet/receive/index.tsx
  packages/suite/src/views/wallet/transactions/index.tsx
Labels: READY FOR REVIEW

#5786 fix(suite): regtest segwit addresses support
  packages/suite/src/utils/wallet/validation.ts
  patches/trezor-address-validator+0.4.2.patch
Labels: READY FOR REVIEW

#5804 fix(suite): error on favicon change on os theme change
  packages/suite-web/src/static/index.html
Labels: Team Desktop

#5813 chore(ci): adjust yarn install on suite-native workflow
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
Labels: mobile-app

#5827 fix(ci): decode step option fix for suite-native workflow
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
Labels: mobile-app

#5826 chore(suite): Ban restricted imports
  .eslintrc.js
Labels: code, mobile-app

#5818 feat(suite-native): Dashboard UI
  packages/icons/assets/icons/chevronUp.svg
  packages/icons/assets/icons/eyeSlash.svg
  packages/icons/src/icons.ts
  suite-native/atoms/src/Card.tsx
  suite-native/atoms/src/ProgressBar.tsx
  suite-native/atoms/src/Select/Select.tsx
  suite-native/atoms/src/Sheet/BottomSheet.tsx
  suite-native/atoms/src/Sheet/BottomSheetContainer.tsx
  suite-native/atoms/src/Sheet/useBottomSheetAnimation.ts
  suite-native/atoms/src/index.ts
  suite-native/module-home/src/components/Assets.tsx
  suite-native/module-home/src/components/DashboardHeader.tsx
  suite-native/module-home/src/components/DashboardHeaderDeviceChip.tsx
  suite-native/module-home/src/components/DashboardSection.tsx
  suite-native/module-home/src/components/PortfolioGraph.tsx
  suite-native/module-home/src/components/Transactions.tsx
  suite-native/module-home/src/navigation/HomeStackNavigator.tsx
  suite-native/module-home/src/navigation/routes.ts
  suite-native/module-home/src/screens/HomeScreen.tsx
  suite-native/module-settings/src/navigation/SettingsStackNavigator.tsx
  suite-native/module-settings/src/navigation/routes.ts
  suite-native/module-settings/src/screens/DemoScreen.tsx
  suite-native/module-settings/src/screens/SettingsScreen.tsx
  suite-native/navigation/src/components/Screen.tsx
Labels: mobile-app

#5835 feat: splash screen to a React Native app
  suite-native/app/android/app/build.gradle
  suite-native/app/android/app/src/dev/res/mipmap-anydpi-v26/ic_launcher.xml
  suite-native/app/android/app/src/dev/res/mipmap-anydpi-v26/ic_launcher_round.xml
  suite-native/app/android/app/src/firebaseDevelop/res/mipmap-anydpi-v26/ic_launcher.xml
  suite-native/app/android/app/src/firebaseDevelop/res/mipmap-anydpi-v26/ic_launcher_round.xml
  suite-native/app/android/app/src/firebaseStaging/res/mipmap-anydpi-v26/ic_launcher.xml
  suite-native/app/android/app/src/firebaseStaging/res/mipmap-anydpi-v26/ic_launcher_round.xml
  suite-native/app/android/app/src/main/AndroidManifest.xml
  suite-native/app/android/app/src/main/java/io/trezor/suite/MainActivity.java
  suite-native/app/android/app/src/main/res/drawable/background_splash.xml
  suite-native/app/android/app/src/main/res/drawable/ic_launcher_foreground.xml
  suite-native/app/android/app/src/main/res/drawable/splash_icon.xml
  suite-native/app/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  suite-native/app/android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  suite-native/app/android/app/src/main/res/values/colors.xml
  suite-native/app/android/app/src/main/res/values/ic_launcher_background.xml
  suite-native/app/android/app/src/main/res/values/styles.xml
  suite-native/app/files/splash_icon.svg
  suite-native/app/ios/Podfile.lock
  suite-native/app/ios/TrezorSuite/Images.xcassets/Splash.imageset/Contents.json
  suite-native/app/ios/TrezorSuite/Images.xcassets/Splash.imageset/splash_icon.png
  suite-native/app/ios/TrezorSuite/Images.xcassets/Splash.imageset/splash_icon@2x.png
  suite-native/app/ios/TrezorSuite/Images.xcassets/Splash.imageset/splash_icon@3x.png
  suite-native/app/ios/TrezorSuite/LaunchScreen.storyboard
Labels: mobile-app

#5836 fix(fw-update): be more defensive against false positives
  packages/suite/src/actions/firmware/firmwareActions.ts
  packages/suite/src/middlewares/suite/__tests__/firmwareMiddleware.test.ts
Labels: release

#5839 feat(native): Integrate with react native splash screen lib
  suite-native/app/android/app/src/main/java/io/trezor/suite/MainActivity.java
  suite-native/app/android/app/src/main/java/io/trezor/suite/MainApplication.java
  suite-native/app/android/app/src/main/res/drawable/background_splash.xml
  suite-native/app/android/app/src/main/res/layout/launch_screen.xml
  suite-native/app/android/app/src/main/res/values/colors.xml
  suite-native/app/android/app/src/main/res/values/styles.xml
  suite-native/app/ios/Podfile.lock
  suite-native/app/ios/TrezorSuite/AppDelegate.mm
  suite-native/app/ios/TrezorSuite/Info.plist
  suite-native/app/ios/TrezorSuite/LaunchScreen.storyboard
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  yarn.lock
Labels: mobile-app

#5840 fix(component): use transient props on ActionItem
  packages/components/src/components/Icon/index.tsx
  packages/suite/src/components/suite/NavigationBar/components/NavigationActions/components/ActionItem.tsx
Labels: code

#5843 test(e2e): reoranize test groups
  packages/integration-tests/projects/suite-web/tests/wallet/check-xpub-ada.test.ts
  packages/integration-tests/projects/suite-web/tests/wallet/check-xpub-btc.test.ts
  packages/integration-tests/projects/suite-web/tests/wallet/check-xpub-ltc.test.ts
  packages/integration-tests/projects/suite-web/tests/wallet/check-xpub-vtc.test.ts
  packages/integration-tests/projects/suite-web/tests/wallet/custom-blockbook-discovery.test.ts
  packages/integration-tests/projects/suite-web/tests/wallet/look-up-an-account.test.ts
  packages/integration-tests/projects/suite-web/tests/wallet/overview-and-transactions.test.ts
Labels: READY FOR REVIEW

#5863 feat(native): color scheme picker
  packages/theme/src/colors.ts
  suite-native/app/src/StylesProvider.tsx
  suite-native/app/src/navigation/RootTabNavigator.tsx
  suite-native/atoms/src/Input/SearchInput.tsx
  suite-native/module-settings/src/components/ColorSchemePicker.tsx
  suite-native/module-settings/src/components/ColorSchemePickerItem.tsx
  suite-native/module-settings/src/index.ts
  suite-native/module-settings/src/screens/SettingsCustomizationScreen.tsx
  suite-native/module-settings/src/screens/SettingsLocalisationScreen.tsx
  suite-native/module-settings/src/slice.ts
Labels: mobile-app
