Repository trezor/trezor-suite, pull requests merged in 2023-12, with the labels that each got.

#10141 fix(suite-native): unacquired device copy
  suite-native/device/src/components/UnacquiredDeviceModalAppendix.tsx
  suite-native/device/src/hooks/useDetectDeviceError.tsx
  suite-native/intl/src/en.ts
Labels: mobile-app

#10168 fix(suite-native): add top offset to messages only if they exist
  suite-native/message-system/src/components/MessageSystemBannerRenderer.tsx
Labels: mobile-app

#10154 Fix/multiple discovery runs
  suite-native/device-mutex/src/DeviceAccessMutex.ts
  suite-native/device-mutex/src/constants.ts
  suite-native/device-mutex/src/requestDeviceAccess.ts
  suite-native/device-mutex/src/tests/DeviceAccessMutex.test.ts
  suite-native/device-mutex/src/types.ts
  suite-native/device/package.json
  suite-native/device/src/deviceThunks.ts
  suite-native/device/src/middlewares/deviceMiddleware.ts
  suite-native/device/tsconfig.json
  suite-native/discovery/src/discoveryMiddleware.ts
  suite-native/discovery/src/discoveryThunks.ts
  yarn.lock
Labels: mobile-app

#10185 fix(suite-native): chunkify for ada
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-native/device/src/deviceThunks.ts
Labels: mobile-app

#10193 feat(suite-native): connect trezor animation (#10192)
  suite-native/device/package.json
  suite-native/device/src/assets/connectDeviceLottie.json
  suite-native/device/src/components/ConnectDeviceAnimation.tsx
  suite-native/device/src/index.ts
  suite-native/device/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-connect-device/src/assets/connectedTrezor.png
  suite-native/module-connect-device/src/screens/ConnectAndUnlockDeviceScreen.tsx
  suite-native/module-onboarding/package.json
  suite-native/module-onboarding/src/assets/trezorT.png
  suite-native/module-onboarding/src/assets/trezorT@2x.png
  suite-native/module-onboarding/src/assets/trezorT@3x.png
  suite-native/module-onboarding/src/screens/ConnectTrezorScreen.tsx
  suite-native/module-onboarding/tsconfig.json
  yarn.lock
Labels: mobile-app

#10195 fix(suite-native): receive screen missing letter
  suite-native/receive/src/components/DeviceScreenContent.tsx
Labels: mobile-app

#10206 fix(suite-native): receive screen missing letter (#10195)
  suite-native/receive/src/components/DeviceScreenContent.tsx
Labels: mobile-app

#10199 feat(analytics): track account nav buttons
  packages/suite-analytics/src/constants.ts
  packages/suite-analytics/src/types/events.ts
  packages/suite/src/components/wallet/WalletLayout/AccountTopPanel/AccountNavigation.tsx
Labels: release

#10208 Spanish as official language
  packages/suite/src/config/suite/languages.ts
Labels: release

#10210 Fix promo banner Shop now
  packages/suite/src/views/dashboard/components/T2B1PromoBanner.tsx
Labels: release

#10213 fix(suite): T2B1 promo banner focus button colors
  packages/suite/src/views/dashboard/components/T2B1PromoBanner.tsx
Labels: release

#10212 perf(suite-native): discovery batch size decreased
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile-app

#10216 Bump beta version to 24.1.0
  packages/suite/package.json
Labels: deployment

#10157 feat(graph): Transaction Cache Engine for XRP (in-memory only)
  jest.config.base.js
  package.json
  suite-common/graph/package.json
  suite-common/graph/src/graphBalanceEvents.ts
  suite-common/graph/src/graphDataFetching.ts
  suite-common/graph/tsconfig.json
  suite-common/transaction-cache-engine/package.json
  suite-common/transaction-cache-engine/src/MemoryStorage.ts
  suite-common/transaction-cache-engine/src/TransactionCacheEngine.ts
  suite-common/transaction-cache-engine/src/index.ts
  suite-common/transaction-cache-engine/src/tests/TransactionCacheEngine.test.ts
  suite-common/transaction-cache-engine/src/tests/__fixtures__/btc.ts
  suite-common/transaction-cache-engine/src/tests/__fixtures__/index.ts
  suite-common/transaction-cache-engine/src/tests/__fixtures__/xrp.ts
  suite-common/transaction-cache-engine/src/types.ts
  suite-common/transaction-cache-engine/src/utils/asyncUtils.ts
  suite-common/transaction-cache-engine/src/utils/balanceHistory.ts
  suite-common/transaction-cache-engine/src/utils/tests/asyncUtils.test.ts
  suite-common/transaction-cache-engine/tsconfig.json
  suite-common/wallet-config/src/networksConfig.ts
  suite-native/accounts/package.json
  suite-native/accounts/src/index.ts
  suite-native/accounts/src/transactionCacheMiddleware.ts
  suite-native/accounts/src/useTransactionCache.ts
  suite-native/accounts/tsconfig.json
  suite-native/app/babel.config.js
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  suite-native/app/tsconfig.json
  suite-native/config/src/supportedNetworks.ts
  suite-native/module-accounts-import/src/components/DevXpub.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/state/package.json
  suite-native/state/src/store.ts
  suite-native/state/tsconfig.json
  yarn.lock
Labels: mobile-app

#10218 chore(mobile): improve skeleton loader
  suite-native/atoms/src/Skeleton/BoxSkeleton.tsx
Labels: mobile-app

#10227 chore(mobile): update mmkv
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  suite-native/storage/package.json
  yarn.lock
Labels: mobile-app

#10230 chore(mobile): remove brigtness increase for QR codes
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  suite-native/qr-code/package.json
  suite-native/qr-code/src/components/QRCode.tsx
  yarn.lock
Labels: mobile-app

#10232 chore(mobile): graph use Reanimated everywhere
  suite-native/react-native-graph/src/AnimatedLineGraph.tsx
Labels: mobile-app

#10233 chore(suite-native): react native versions
  suite-native/alerts/package.json
  suite-native/biometrics/package.json
  suite-native/link/package.json
  suite-native/module-onboarding/package.json
  suite-native/state/package.json
  yarn.lock
Labels: mobile-app

#10231 Feat/use empty passphrase
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-common/wallet-core/src/discovery/discoveryThunks.ts
  suite-native/app/src/App.tsx
  suite-native/device/src/middlewares/deviceMiddleware.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/discovery/src/utils.ts
Labels: mobile-app

#10235 fix(components): fix Button style
  packages/components/src/components/buttons/Button/Button.tsx
  packages/components/src/components/form/InputStyles.ts
Labels: UI

#10184 fix(suite-native): use correct message config on mobile
  packages/env-utils/src/envUtils.native.ts
  packages/env-utils/src/envUtils.ts
  packages/env-utils/src/index.ts
  packages/env-utils/src/types.ts
  suite-common/message-system/src/messageSystemConstants.ts
  suite-common/message-system/src/messageSystemThunks.ts
  suite-native/app/.env.debug
  suite-native/app/.env.develop
  suite-native/app/.env.production
  suite-native/app/.env.staging
  suite-native/app/fastlane/Fastfile
  suite-native/app/ios/Podfile.lock
  suite-native/app/ios/TrezorSuite/Info.plist
  suite-native/message-system/src/components/FeatureMessageScreen.tsx
Labels: mobile-app, message-system

#10204 feat(suite-native): updated images
  suite-native/app/ios/Podfile.lock
  suite-native/atoms/package.json
  suite-native/atoms/src/Image.tsx
  suite-native/module-connect-device/src/assets/connectDeviceScreenBackground.png
  suite-native/module-connect-device/src/components/ConnectDeviceSreenView.tsx
  suite-native/module-connect-device/src/screens/ConnectingDeviceScreen.tsx
  suite-native/module-connect-device/src/screens/PinMatrixScreen.tsx
  suite-native/module-home/src/assets/connectTrezor.svg
  suite-native/module-home/src/assets/darkConnectTrezor.svg
  suite-native/module-home/src/components/EmptyPortfolioCrossroads.tsx
  suite-native/module-home/src/components/EmptyPortfolioTrackerState.tsx
  suite-native/receive/assets/check.png
  suite-native/receive/assets/check@2x.png
  suite-native/receive/assets/check@3x.png
  suite-native/receive/assets/darkCheck.png
  suite-native/receive/assets/darkCheck@2x.png
  suite-native/receive/assets/darkCheck@3x.png
  suite-native/receive/assets/darkTrezorTruth.png
  suite-native/receive/assets/darkTrezorTruth@2x.png
  suite-native/receive/assets/darkTrezorTruth@3x.png
  suite-native/receive/assets/trezorTruth.png
  suite-native/receive/assets/trezorTruth@2x.png
  suite-native/receive/assets/trezorTruth@3x.png
  suite-native/receive/src/components/VerificationWalkthroughBottomSheet.tsx
  yarn.lock
Labels: mobile-app

#10265 fix(suite-native): broken layout on android
  suite-native/module-connect-device/src/screens/ConnectingDeviceScreen.tsx
Labels: mobile-app

#10238 feat(suite-native): retrieving balances takes longer
  suite-native/atoms/src/Loader.tsx
  suite-native/discovery/package.json
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/discovery/src/index.ts
  suite-native/discovery/src/useIsDiscoveryDurationTooLong.tsx
  suite-native/graph/src/components/Graph.tsx
  suite-native/intl/src/en.ts
  suite-native/module-home/package.json
  suite-native/module-home/src/components/PortfolioGraph.tsx
  suite-native/module-home/tsconfig.json
  yarn.lock
Labels: mobile-app

#10264 fix(mobile): device is correctly disconnected
  packages/react-native-usb/src/index.ts
Labels: mobile-app

#10250 fix(suite-native): receive cancel
  suite-native/navigation/src/components/GoBackIcon.tsx
  suite-native/receive/src/components/ReceiveAccount.tsx
  suite-native/receive/src/hooks/receiveSelectors.ts
  suite-native/receive/src/hooks/useAccountReceiveAddress.tsx
  suite-native/receive/src/screens/ReceiveModalScreen.tsx
Labels: mobile-app

#10273 chore(suite-native): bump discovery duration treshold
  suite-native/discovery/src/useIsDiscoveryDurationTooLong.tsx
Labels: mobile-app

#10263 Update FW binaries to 2.6.4
  docs/releases/adding-new-firmwares.md
  packages/connect-common/files/firmware/t2b1/releases.json
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.6.3-bitcoinonly.bin
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.6.3.bin
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.6.4-bitcoinonly.bin
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.6.4.bin
  packages/connect-common/files/firmware/t2t1/releases.json
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.6.3-bitcoinonly.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.6.3.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.6.4-bitcoinonly.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.6.4.bin
Labels: release

#10289 Crowdin translations update
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#10270 fix(suite-native): token label receive
  suite-native/receive/src/screens/ReceiveModalScreen.tsx
Labels: mobile-app

#10271 fix(suite-native): display empty home screen
  suite-native/device/src/selectors.ts
Labels: mobile-app

#10257 feat(suite-native): updated copy
  suite-native/intl/src/en.ts
  suite-native/module-onboarding/src/screens/AnalyticsConsentScreen.tsx
  suite-native/module-settings/package.json
  suite-native/module-settings/src/components/FAQInfoPanel.tsx
  suite-native/module-settings/tsconfig.json
  yarn.lock
Labels: mobile-app

#10296 chore(suite-native): improve empty homescreen
  suite-native/device/src/selectors.ts
Labels: mobile-app

#10262 fix(suite): fix sidebar styles
  packages/components/src/components/Dropdown/Dropdown.tsx
  packages/suite/src/components/suite/Preloader/SuiteLayout/Sidebar/NavigationItem.tsx
  packages/suite/src/components/suite/Preloader/SuiteLayout/Sidebar/NotificationDropdown.tsx
  packages/suite/src/components/suite/labeling/MetadataLabeling/withDropdown.tsx
  suite-common/icons/src/webComponents/Icon.web.tsx
Labels: components, UI

#10297 chore(ci): remove never-functional bot intended to move PR To be reviewed automatically
  .github/workflows/bot-pr-ready-for-review.yml
Labels: low hanging fruit

#10241 Chore(Native) supported networks
  suite-native/config/package.json
  suite-native/config/src/supportedNetworks.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/module-accounts-import/src/components/SelectableNetworkList.tsx
  yarn.lock
Labels: mobile-app

#10299 chore(suite-native): reset balance on unmount
  suite-native/module-home/src/components/PortfolioGraphHeader.tsx
Labels: mobile-app

#10300 fix(suite-native): improve interval type
  suite-native/discovery/src/useIsDiscoveryDurationTooLong.tsx
Labels: mobile-app

#10298 fix(suite-native): allow portfolio to sync accounts of connected device
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/module-accounts-import/src/components/AccountImportSummary.tsx
  suite-native/notifications/src/components/TransactionNotification.tsx
Labels: mobile-app

#10310 fix(mobile): fix XRP detail compare tab
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailValuesSheet.tsx
Labels: mobile-app

#10324 Fix/image imports
  suite-native/module-home/src/screens/HomeScreen/components/EmptyPortfolioCrossroads.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyPortfolioTrackerState.tsx
Labels: mobile-app

#10301 feat(suite-native): device module slide vertically
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/device/src/hooks/useAuthorizeDevice.ts
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/device/src/screens/DeviceInfoModalScreen.tsx
  suite-native/module-connect-device/src/components/ConnectDeviceScreenHeader.tsx
Labels: mobile-app

#10345 fix(suite-native): useEmptyPassphrase
  suite-native/app/src/App.tsx
Labels: mobile-app

#10336 feat(suite-native): device manager animation
  suite-native/device-manager/package.json
  suite-native/device-manager/src/components/DeviceManagerModal.tsx
  yarn.lock
Labels: mobile-app

#10337 chore(suite-native): increase interval duration
  suite-native/discovery/src/useIsDiscoveryDurationTooLong.tsx
Labels: mobile-app

#10349 chore(mobile): faster optimalized discovery
  suite-common/wallet-core/src/discovery/discoveryThunks.ts
  suite-common/wallet-types/src/discovery.ts
  suite-native/config/src/supportedNetworks.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/discovery/src/utils.ts
  suite-native/fiat-rates/src/fiatRatesConst.ts
  suite-native/logger/package.json
  suite-native/logger/src/index.ts
  suite-native/logger/src/logsMiddleware.ts
  suite-native/logger/tsconfig.json
  suite-native/module-dev-utils/src/components/CopyLogsButton.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/state/package.json
  suite-native/state/src/store.ts
  suite-native/state/tsconfig.json
  yarn.lock
Labels: mobile-app

#10338 chore(suite-native): add account type
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/accounts/constants.ts
Labels: mobile-app

#10368 chore(mobile): faster text component
  suite-native/atoms/src/Text.tsx
  suite-native/graph/src/components/GraphError.tsx
Labels: mobile-app

#10369 chore(mobile): discovery animation
  suite-native/assets/package.json
  suite-native/assets/src/components/Assets.tsx
  suite-native/assets/src/components/DiscoveryAssetsLoader.tsx
  yarn.lock
Labels: mobile-app

#10372 fix(suite-native): better receive response types
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-native/receive/package.json
  suite-native/receive/src/hooks/useAccountReceiveAddress.tsx
  suite-native/receive/tsconfig.json
  yarn.lock
Labels: mobile-app

#10353 fix(suite): bitcoincash prefix
  packages/suite/src/components/suite/DeviceDisplay.tsx
Labels: release

#10346 feat(docs): update images in connect explorer
  docs/packages/connect/index.md
  docs/packages/connect/schema-connect-web.jpg
  docs/packages/connect/schema-connect-web.png
  docs/packages/connect/schema-connect-webextension.jpg
  docs/packages/connect/schema-connect-webextension.png
  docs/packages/connect/schema-connect.jpg
  docs/packages/connect/schema-connect.png
Labels: documentation

#10373 fix(suite-native): key warning in assets
  suite-native/assets/src/components/Assets.tsx
Labels: mobile-app

#10381 chore(env): different fetch interval for messages in suite and mobile
  suite-common/message-system/src/messageSystemConstants.ts
  suite-common/message-system/src/messageSystemThunks.ts
  suite-native/app/ios/Podfile.lock
Labels: mobile-app, message-system

#10384 feat(docs): update images in connect explorer
  docs/packages/connect/index.md
  docs/packages/connect/schema-connect-web.jpg
  docs/packages/connect/schema-connect-web.png
  docs/packages/connect/schema-connect-webextension.jpg
  docs/packages/connect/schema-connect-webextension.png
  docs/packages/connect/schema-connect.jpg
  docs/packages/connect/schema-connect.png
Labels: documentation

#10388 fix(suite-native): receive flow
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/receive/src/hooks/useAccountReceiveAddress.tsx
Labels: mobile-app

#10370 Feat(suite-native) receive animations
  suite-native/intl/src/en.ts
  suite-native/qr-code/src/components/AddressQRCode.tsx
  suite-native/qr-code/src/components/QRCode.tsx
  suite-native/qr-code/src/index.ts
  suite-native/receive/assets/confirmOnTrezor.png
  suite-native/receive/assets/confirmOnTrezor@2x.png
  suite-native/receive/assets/confirmOnTrezor@3x.png
  suite-native/receive/src/components/ConfirmOnTrezorImage.tsx
  suite-native/receive/src/components/DevicePaginationButton.tsx
  suite-native/receive/src/components/DeviceScreen/DeviceScreenContent.tsx
  suite-native/receive/src/components/DeviceScreen/DeviceScreenLoading.tsx
  suite-native/receive/src/components/DeviceScreen/DeviceScreenPagination.tsx
  suite-native/receive/src/components/ReceiveAccount.tsx
  suite-native/receive/src/components/ReceiveAddressCard.tsx
  suite-native/receive/src/components/ReceiveAddressCard/ReceiveAddressCard.tsx
  suite-native/receive/src/components/ReceiveAddressCard/useReceiveAddressCardAnimations.tsx
  suite-native/receive/src/components/UnverifiedAddress/UnverifiedAddress.tsx
  suite-native/receive/src/components/UnverifiedAddress/UnverifiedAddressDevice.tsx
  suite-native/receive/src/components/UnverifiedAddress/UnverifiedAddressDeviceHint.tsx
  suite-native/receive/src/components/UnverifiedAddress/UnverifiedAddressWarning.tsx
  suite-native/receive/src/components/UnverifiedAddress/useUnverifiedAddressDeviceAnimations.tsx
  suite-native/receive/src/hooks/useReceiveProgressSteps.tsx
Labels: mobile-app

#10371 chore(mobile): graph visual refactor
  suite-common/icons/package.json
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  suite-native/app/src/snow/Snow.tsx
  suite-native/app/src/snow/Snowflake.tsx
  suite-native/atoms/package.json
  suite-native/graph/package.json
  suite-native/graph/src/components/AxisLabel.tsx
  suite-native/graph/src/components/Graph.tsx
  suite-native/graph/src/components/GraphError.tsx
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-management/src/components/AccountDetailGraphHeader.tsx
  suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraphHeader.tsx
  suite-native/react-native-graph/package.json
  suite-native/react-native-graph/src/AnimatedLineGraph.tsx
  suite-native/react-native-graph/src/BlurOverlay.tsx
  suite-native/react-native-graph/src/LineGraphProps.ts
  suite-native/react-native-graph/src/LoadingLine.tsx
  suite-native/react-native-graph/src/SelectionDot.tsx
  suite-native/receive/package.json
  suite-native/transactions/package.json
  yarn.lock
Labels: mobile-app

#10411 fix(suite-native): remove animation of receive hint
  suite-native/receive/src/components/UnverifiedAddress/UnverifiedAddressDevice.tsx
  suite-native/receive/src/components/UnverifiedAddress/useUnverifiedAddressDeviceAnimations.tsx
Labels: mobile-app

#10413 Chore/revert receive animation
  suite-native/app/ios/Podfile.lock
  suite-native/intl/src/en.ts
  suite-native/qr-code/src/components/AddressQRCode.tsx
  suite-native/qr-code/src/components/QRCode.tsx
  suite-native/qr-code/src/index.ts
  suite-native/receive/assets/confirmOnTrezor.png
  suite-native/receive/assets/confirmOnTrezor@2x.png
  suite-native/receive/assets/confirmOnTrezor@3x.png
  suite-native/receive/src/components/ConfirmOnTrezorImage.tsx
  suite-native/receive/src/components/DevicePaginationButton.tsx
  suite-native/receive/src/components/DeviceScreen/DeviceScreenLoading.tsx
  suite-native/receive/src/components/DeviceScreenContent.tsx
  suite-native/receive/src/components/DeviceScreenPagination.tsx
  suite-native/receive/src/components/ReceiveAccount.tsx
  suite-native/receive/src/components/ReceiveAddressCard.tsx
  suite-native/receive/src/components/ReceiveAddressCard/ReceiveAddressCard.tsx
  suite-native/receive/src/components/ReceiveAddressCard/useReceiveAddressCardAnimations.tsx
  suite-native/receive/src/components/UnverifiedAddress.tsx
  suite-native/receive/src/components/UnverifiedAddress/useUnverifiedAddressDeviceAnimations.tsx
  suite-native/receive/src/components/UnverifiedAddressDevice.tsx
  suite-native/receive/src/components/UnverifiedAddressDeviceHint.tsx
  suite-native/receive/src/components/UnverifiedAddressWarning.tsx
  suite-native/receive/src/hooks/useReceiveProgressSteps.tsx
Labels: mobile-app

#10414 Chore/receive image btc cash
  suite-native/receive/assets/confirmOnTrezor.png
  suite-native/receive/assets/confirmOnTrezor@2x.png
  suite-native/receive/assets/confirmOnTrezor@3x.png
  suite-native/receive/src/components/ConfirmOnTrezorImage.tsx
  suite-native/receive/src/components/DeviceScreenContent.tsx
Labels: mobile-app
