Repository trezor/trezor-suite, pull requests merged in 2023-04, with the labels that each got.

#7971 chore(suite-native): upgrade RN
  package.json
  packages/env-utils/package.json
  packages/icons/package.json
  packages/styles/package.json
  packages/transport-native/package.json
  suite-native/accounts/package.json
  suite-native/app/Gemfile
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  suite-native/assets/package.json
  suite-native/atoms/package.json
  suite-native/graph/package.json
  suite-native/helpers/package.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts/package.json
  suite-native/module-dev-utils/package.json
  suite-native/module-home/package.json
  suite-native/module-send-receive/package.json
  suite-native/module-settings/package.json
  suite-native/navigation/package.json
  suite-native/notifications/package.json
  suite-native/qr-code/package.json
  suite-native/react-native-graph/package.json
  suite-native/storage/package.json
  suite-native/theme/package.json
  suite-native/transactions/package.json
  suite-native/video-assets/package.json
  yarn.lock
Labels: dependencies, mobile-app

#7978 update suite guide revision
  packages/suite-data/src/guide/constants.ts
Labels: release, guide

#7979 fix(coinjoin): ending Round when not signed
  packages/coinjoin/src/client/CoinjoinRound.ts
  packages/coinjoin/src/client/round/endedRound.ts
  packages/coinjoin/src/client/round/transactionSigning.ts
  packages/coinjoin/tests/client/CoinjoinRound.test.ts
  packages/coinjoin/tests/client/endedRound.test.ts
Labels: release

#7983 fix(suite-native): camera permissions
  suite-native/app/ios/TrezorSuite/Info.plist
Labels: mobile-app

#7987 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite/src/support/messages.ts
Labels: translations

#7982 fix(suite-native): discreet mode for account list
  suite-native/atoms/src/DiscreetText.tsx
Labels: bug, mobile-app

#7988 Crowdin translations update
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/da.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/el.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fi.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/he.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#7887 Feat/token detail screen
  suite-native/accounts/src/components/AccountListItemInteractive.tsx
  suite-native/accounts/src/components/AccountsList.tsx
  suite-native/accounts/src/components/AccountsListGroup.tsx
  suite-native/accounts/src/components/TokenList.tsx
  suite-native/accounts/src/components/TokenListItem.tsx
  suite-native/ethereum-tokens/package.json
  suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts
  suite-native/ethereum-tokens/src/types.ts
  suite-native/ethereum-tokens/src/utils.ts
  suite-native/ethereum-tokens/tsconfig.json
  suite-native/formatters/package.json
  suite-native/formatters/src/components/EthereumTokenAmountFormatter.tsx
  suite-native/formatters/src/components/EthereumTokenToFiatAmountFormatter.tsx
  suite-native/formatters/src/index.ts
  suite-native/formatters/src/utils.ts
  suite-native/module-accounts-import/src/components/AccountImportEthereumTokens.tsx
  suite-native/module-accounts-import/src/components/EthereumTokenInfo.tsx
  suite-native/module-accounts/package.json
  suite-native/module-accounts/src/components/AccountDetailScreenHeader.tsx
  suite-native/module-accounts/src/components/TransactionListHeader.tsx
  suite-native/module-accounts/src/screens/AccountDetailScreen.tsx
  suite-native/module-accounts/src/screens/AccountSettingsScreen.tsx
  suite-native/module-accounts/src/screens/AccountsScreen.tsx
  suite-native/module-accounts/tsconfig.json
  suite-native/navigation/package.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/navigation/tsconfig.json
  suite-native/notifications/src/components/TransactionNotification.tsx
  suite-native/transactions/package.json
  suite-native/transactions/src/components/TransactionsList/TokenTransferListItem.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionIcon.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionList.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
  suite-native/transactions/tsconfig.json
  yarn.lock
Labels: ERC20, mobile-app

#7994 fix(suite-desktop): use hardcoded app id in notarize
  packages/suite-desktop/scripts/notarize.ts
Labels: release

#7962 feat(suite-native): add dev button for prod as well
  suite-native/module-dev-utils/src/components/CopyLogsButton.tsx
  suite-native/module-dev-utils/src/components/Logs.tsx
  suite-native/module-dev-utils/src/components/ProductionDevInfo.tsx
  suite-native/module-dev-utils/src/components/RenderingUtils.tsx
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/module-settings/package.json
  suite-native/module-settings/src/components/ApplicationSettings.tsx
  suite-native/module-settings/src/components/ColorSchemePickerItem.tsx
  suite-native/module-settings/src/components/ProductionDebug.tsx
  suite-native/module-settings/src/screens/SettingsAboutUsScreen.tsx
  suite-native/module-settings/tsconfig.json
  yarn.lock
Labels: mobile-app

#8014 fix(suite-native): privacy policy link
  suite-native/module-settings/src/screens/SettingsAboutUsScreen.tsx
Labels: mobile-app

#7992 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/ru.json
Labels: translations

#8010 fix(suite-native): bottom sheet pan gesture close
  suite-native/app/ios/Podfile.lock
  suite-native/atoms/src/Sheet/BottomSheet.tsx
  suite-native/atoms/src/Sheet/useBottomSheetAnimation.ts
Labels: mobile-app

#8011 feat(suite-native): copy to clipboard toast displayed on android
  suite-native/helpers/src/hooks/useCopyToClipboard.ts
Labels: mobile-app

#8018 fix(suite-native): camera access alert hiden on undetermined status
  suite-native/qr-code/src/components/CameraPermissionError.tsx
  suite-native/qr-code/src/components/QRCodeScanner.tsx
Labels: mobile-app

#7975 feat(suite-native): multiple addresses displayed in transaction detail
  suite-common/wallet-core/src/transactions/transactionsReducer.ts
  suite-common/wallet-core/src/transactions/transactionsThunks.ts
  suite-native/formatters/package.json
  suite-native/formatters/src/components/SignValueFormatter.tsx
  suite-native/formatters/src/index.ts
  suite-native/formatters/tsconfig.json
  suite-native/transactions/package.json
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailAddressesSection.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailAddressesSheet.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailStatusSection.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailSummary.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
  suite-native/transactions/src/index.ts
  suite-native/transactions/src/selectors.ts
  suite-native/transactions/src/tests/fixtures/transactions.ts
  suite-native/transactions/src/tests/utils.test.ts
  suite-native/transactions/src/utils.ts
  suite-native/transactions/tsconfig.json
  yarn.lock
Labels: transactions, mobile-app

#8039 feat(suite-native): copy polishment
  suite-native/app/src/navigation/routes.ts
  suite-native/module-accounts-import/src/components/XpubHint.tsx
  suite-native/module-accounts-import/src/screens/AccountImportLoadingScreen.tsx
  suite-native/module-accounts-import/src/useShowImportError.ts
  suite-native/module-accounts/src/components/AccountRenameButton.tsx
  suite-native/module-accounts/src/components/AccountRenameForm.tsx
  suite-native/module-accounts/src/components/AccountsScreenHeader.tsx
  suite-native/module-home/src/components/DashboardHeader.tsx
  suite-native/module-home/src/screens/HomeScreen.tsx
  suite-native/module-send-receive/src/components/ReceiveTextHint.tsx
  suite-native/navigation/src/types.tsx
Labels: mobile-app

#8033 UI overflow glitches
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/accounts/src/components/TokenListItem.tsx
  suite-native/atoms/src/Button/IconButton.tsx
  suite-native/atoms/src/DiscreetText.tsx
  suite-native/atoms/src/TextDivider.tsx
  suite-native/formatters/package.json
  suite-native/formatters/src/components/AccountAddressFormatter.tsx
  suite-native/formatters/src/components/EthereumTokenAmountFormatter.tsx
  suite-native/formatters/src/components/EthereumTokenToFiatAmountFormatter.tsx
  suite-native/formatters/tsconfig.json
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-accounts/src/components/AccountDetailGraphHeader.tsx
  suite-native/module-accounts/src/components/AccountDetailScreenHeader.tsx
  suite-native/module-accounts/src/screens/AccountDetailScreen.tsx
  suite-native/module-accounts/src/screens/AccountSettingsScreen.tsx
  suite-native/module-accounts/src/screens/AccountsScreen.tsx
  suite-native/module-home/src/components/PortfolioGraphHeader.tsx
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/src/components/ScreenHeader.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailAddressesSection.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx
  suite-native/transactions/src/components/TransactionsList/TokenTransferListItem.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListGroupTitle.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
  yarn.lock
Labels: mobile-app

#8041 Feat/persistent discreet mode
  suite-native/atoms/package.json
  suite-native/atoms/src/DiscreetText.tsx
  suite-native/atoms/tsconfig.json
  yarn.lock
Labels: mobile-app

#7949 Feat/account types
  packages/utxo-lib/src/derivation.ts
  packages/utxo-lib/src/index.ts
  suite-common/wallet-config/src/networksConfig.ts
  suite-common/wallet-core/src/accounts/accountsActions.ts
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/accounts/constants.ts
  suite-common/wallet-types/src/account.ts
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/accounts/src/components/TokenListItem.tsx
  suite-native/atoms/src/Badge.tsx
  suite-native/atoms/src/index.ts
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/accountsImportThunks.ts
  suite-native/module-accounts-import/src/constants.ts
  suite-native/module-accounts-import/tsconfig.json
  suite-native/module-accounts/src/screens/AccountSettingsScreen.tsx
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  yarn.lock
Labels: account, mobile-app

#7889 feat(suite-native): init onboarding stack
  jest.config.native.js
  packages/icons/assets/icons/bugBeetle.svg
  packages/icons/src/icons.ts
  suite-native/app/package.json
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/app/tsconfig.json
  suite-native/atoms/src/AlertBox.tsx
  suite-native/atoms/src/Image.tsx
  suite-native/atoms/src/index.ts
  suite-native/link/src/components/Link.tsx
  suite-native/logger/src/logsMiddleware.ts
  suite-native/module-accounts-import/src/components/AccountImportHeader.tsx
  suite-native/module-accounts-import/src/components/AccountImportLoader.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-onboarding/package.json
  suite-native/module-onboarding/redux.d.ts
  suite-native/module-onboarding/src/assets/dashboard.png
  suite-native/module-onboarding/src/assets/dashboard@2x.png
  suite-native/module-onboarding/src/assets/dashboard@3x.png
  suite-native/module-onboarding/src/assets/rectangles.png
  suite-native/module-onboarding/src/assets/rectangles@2x.png
  suite-native/module-onboarding/src/assets/rectangles@3x.png
  suite-native/module-onboarding/src/components/AnalyticsInfoRow.tsx
  suite-native/module-onboarding/src/components/CoinsSvg.tsx
  suite-native/module-onboarding/src/components/GraphSvg.tsx
  suite-native/module-onboarding/src/components/OnboardingFooter.tsx
  suite-native/module-onboarding/src/components/OnboardingScreen.tsx
  suite-native/module-onboarding/src/components/OnboardingScreenHeader.tsx
  suite-native/module-onboarding/src/index.ts
  suite-native/module-onboarding/src/navigation/OnboardingStackNavigator.tsx
  suite-native/module-onboarding/src/screens/AnalyticsConsentScreen.tsx
  suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx
  suite-native/module-onboarding/src/screens/GetStartedScreen.tsx
  suite-native/module-onboarding/src/screens/TrackBalancesScreen.tsx
  suite-native/module-onboarding/src/screens/WelcomeScreen.tsx
  suite-native/module-onboarding/tsconfig.json
  suite-native/module-settings/src/slice.ts
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/test-utils/src/setupReactReanimatedMock.js
  yarn.lock
Labels: mobile-app

#8045 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/ja.json
  packages/suite/src/support/messages.ts
Labels: translations

#8055 fix(mobile): rates are correctly fetched when currency is changed
  suite-common/redux-utils/src/extraDependenciesType.ts
  suite-native/app/src/initActions.ts
  suite-native/fiat-rates/src/fiatRatesMiddleware.ts
  suite-native/fiat-rates/src/fiatRatesReducer.ts
  suite-native/fiat-rates/src/fiatRatesThunks.ts
  suite-native/module-accounts-import/src/screens/AccountImportLoadingScreen.tsx
  suite-native/module-settings/src/components/CurrencySelector.tsx
  suite-native/module-settings/src/slice.ts
  suite-native/state/src/extraDependencies.ts
Labels: mobile-app

#8064 chore(suite-native): dark mode images
  suite-native/module-onboarding/package.json
  suite-native/module-onboarding/src/assets/darkDashboard.png
  suite-native/module-onboarding/src/assets/darkDashboard@2x.png
  suite-native/module-onboarding/src/assets/darkDashboard@3x.png
  suite-native/module-onboarding/src/assets/darkRectangles.png
  suite-native/module-onboarding/src/assets/darkRectangles@2x.png
  suite-native/module-onboarding/src/assets/darkRectangles@3x.png
  suite-native/module-onboarding/src/assets/dashboard.png
  suite-native/module-onboarding/src/assets/dashboard@2x.png
  suite-native/module-onboarding/src/assets/dashboard@3x.png
  suite-native/module-onboarding/src/screens/GetStartedScreen.tsx
  suite-native/module-onboarding/src/screens/WelcomeScreen.tsx
  suite-native/module-onboarding/tsconfig.json
  yarn.lock
Labels: mobile-app

#8063 fix(suite-native): navigation in onboarding
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/app/ios/Podfile.lock
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/logger/src/logsMiddleware.ts
  suite-native/module-accounts-import/src/components/AccountImportHeader.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-settings/src/slice.ts
Labels: mobile-app

#8074 test(connet-popup): adapt remaining fixtures to fw 2.6.0
  ci/test.yml
  packages/connect-popup/e2e/playwright.config.ts
  packages/connect-popup/e2e/tests/__fixtures__/methods.ts
Labels: e2e

#8086 feat(suite-native): divider on import footer
  suite-native/module-accounts-import/src/components/XpubHint.tsx
Labels: mobile-app

#8115 fix(suite): fix use rbf modal not working when displaying in sats is enabled
  packages/suite/src/components/suite/modals/TransactionDetail/components/ChangeFee/index.tsx
  packages/suite/src/hooks/wallet/useRbfForm.ts
Labels: release

#8085 Fix/android navbar
  suite-native/app/package.json
  suite-native/atoms/src/Sheet/BottomSheetContainer.tsx
  suite-native/atoms/src/Sheet/useBottomSheetAnimation.ts
  suite-native/navigation/package.json
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/src/components/TabBar.tsx
  suite-native/navigation/src/components/TabBarItem.tsx
  yarn.lock
Labels: mobile-app

#8128 fix(suite-native): label offset
  suite-native/graph/src/components/AxisLabel.tsx
Labels: mobile-app

#8127 feat(message-system, coinjoin): coinjoin banner, fw 2.6.0 requirement
  packages/message-system/src/config/config.v1.json
Labels: message-system

#8118 fix(suite-native): fix navigation redirects
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
Labels: mobile-app

#8043 Fix/testnet account fixes
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/module-accounts/src/components/AccountDetailCryptoValue.tsx
  suite-native/module-accounts/src/components/AccountDetailGraphHeader.tsx
  suite-native/module-accounts/src/components/TransactionListHeader.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx
Labels: mobile-app

#8088 Feat/faq polishing
  packages/icons/assets/icons/minusCircle.svg
  packages/icons/src/icons.ts
  suite-native/atoms/src/AccordionItem.tsx
  suite-native/link/package.json
  suite-native/link/src/components/Link.tsx
  suite-native/link/tsconfig.json
  suite-native/module-onboarding/src/components/OnboardingFooter.tsx
  suite-native/module-onboarding/src/screens/AnalyticsConsentScreen.tsx
  suite-native/module-send-receive/src/components/ReceiveTextHint.tsx
  suite-native/module-settings/src/components/FAQInfoPanel.tsx
  yarn.lock
Labels: mobile-app

#8135 chore(suite-native): remove cardano and ripple
  suite-native/config/src/enabledNetworks.ts
Labels: mobile-app

#8068 feat(suite-native): analytic events
  suite-common/suite-constants/src/units.ts
  suite-native/analytics/package.json
  suite-native/analytics/src/analytics.ts
  suite-native/analytics/src/analyticsThunks.ts
  suite-native/analytics/src/constants.ts
  suite-native/analytics/src/events.ts
  suite-native/analytics/tsconfig.json
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  suite-native/app/src/hooks/useReportAppInitToAnalytics.ts
  suite-native/app/tsconfig.json
  suite-native/atoms/package.json
  suite-native/atoms/src/DiscreetText.tsx
  suite-native/atoms/tsconfig.json
  suite-native/graph/package.json
  suite-native/graph/src/components/TimeSwitch.tsx
  suite-native/graph/src/hooks.ts
  suite-native/graph/tsconfig.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-import/tsconfig.json
  suite-native/module-accounts/package.json
  suite-native/module-accounts/src/screens/AccountDetailScreen.tsx
  suite-native/module-accounts/tsconfig.json
  suite-native/module-onboarding/package.json
  suite-native/module-onboarding/src/components/OnboardingFooter.tsx
  suite-native/module-onboarding/src/screens/AnalyticsConsentScreen.tsx
  suite-native/module-onboarding/tsconfig.json
  suite-native/module-send-receive/package.json
  suite-native/module-send-receive/src/screens/ReceiveScreen.tsx
  suite-native/module-send-receive/tsconfig.json
  suite-native/module-settings/package.json
  suite-native/module-settings/src/components/CryptoUnitsSelector.tsx
  suite-native/module-settings/src/components/CurrencySelector.tsx
  suite-native/module-settings/src/screens/SettingsPrivacyAndSecurity.tsx
  suite-native/module-settings/tsconfig.json
  suite-native/navigation/package.json
  suite-native/navigation/src/components/NavigationContainerWithAnalytics.tsx
  suite-native/navigation/src/index.ts
  suite-native/navigation/src/routes.ts
  suite-native/navigation/tsconfig.json
  suite-native/theme/package.json
  suite-native/theme/src/useUserColorScheme.ts
  suite-native/theme/tsconfig.json
  suite-native/transactions/package.json
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailSheets.tsx
  suite-native/transactions/src/screens/TransactionDetailScreen.tsx
  suite-native/transactions/tsconfig.json
  yarn.lock
Labels: mobile-app

#8133 fix(mobile): fix fetching of transactions fiat rates
  suite-native/app/ios/Podfile.lock
  suite-native/app/src/initActions.ts
  suite-native/fiat-rates/src/fiatRatesMiddleware.ts
  suite-native/fiat-rates/src/fiatRatesSelectors.ts
  suite-native/fiat-rates/src/fiatRatesThunks.ts
Labels: mobile-app

#8136 feat(suite-native): token account detail screen headers
  suite-native/accounts/src/components/TokenListItem.tsx
  suite-native/atoms/src/Badge.tsx
  suite-native/atoms/src/StepsProgressBar.tsx
  suite-native/formatters/src/components/EthereumTokenAmountFormatter.tsx
  suite-native/formatters/src/components/EthereumTokenToFiatAmountFormatter.tsx
  suite-native/module-accounts-import/src/components/AccountImportHeader.tsx
  suite-native/module-accounts-import/src/screens/ScanQRCodeModalScreen.tsx
  suite-native/module-accounts/src/components/AccountDetailGraph.tsx
  suite-native/module-accounts/src/components/AccountDetailScreenHeader.tsx
  suite-native/module-accounts/src/components/AccountDetailTokenHeader.tsx
  suite-native/module-accounts/src/components/AccountsScreenHeader.tsx
  suite-native/module-accounts/src/components/TokenAccountDetailScreenHeader.tsx
  suite-native/module-accounts/src/components/TransactionListHeader.tsx
  suite-native/module-accounts/src/screens/AccountDetailScreen.tsx
  suite-native/module-accounts/src/screens/AccountSettingsScreen.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/module-send-receive/src/screens/ReceiveAccountsScreen.tsx
  suite-native/module-send-receive/src/screens/ReceiveScreen.tsx
  suite-native/module-settings/src/components/ApplicationSettings.tsx
  suite-native/module-settings/src/navigation/SettingsStackNavigator.tsx
  suite-native/module-settings/src/screens/SettingsAboutUsScreen.tsx
  suite-native/module-settings/src/screens/SettingsCustomizationScreen.tsx
  suite-native/module-settings/src/screens/SettingsFAQScreen.tsx
  suite-native/module-settings/src/screens/SettingsLocalizationScreen.tsx
  suite-native/module-settings/src/screens/SettingsPrivacyAndSecurity.tsx
  suite-native/navigation/src/components/ScreenHeader.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/transactions/src/components/TransactionsList/TokenTransferListItem.tsx
Labels: mobile-app

#8147 fix(log): fix redacting coinjoin round id stopped following
  packages/coinjoin/src/client/Status.ts
Labels: low hanging fruit

#8148 chore(message-system): report also message system sequence number to see if it is a problem
  packages/suite/src/actions/suite/messageSystemActions.ts
Labels: low hanging fruit

#8153 chore(mobile): show error if storage is corrupted
  suite-native/app/ios/Podfile.lock
  suite-native/state/src/reducers.ts
  suite-native/storage/package.json
  suite-native/storage/src/storage.ts
  suite-native/storage/src/typedPersistReducer.ts
  yarn.lock
Labels: mobile-app

#8155 feat(suite-native): transaction detail include tokens
  suite-native/ethereum-tokens/package.json
  suite-native/ethereum-tokens/src/components/CoinIcon.tsx
  suite-native/ethereum-tokens/src/index.ts
  suite-native/ethereum-tokens/src/utils.ts
  suite-native/formatters/src/components/EthereumTokenToFiatAmountFormatter.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/transactions/src/components/TransactionDetail/NetworkTransactionDetailSummary.tsx
  suite-native/transactions/src/components/TransactionDetail/TokenTransactionDetailSummary.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailAddressesSection.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailIncludedCoins.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailListItem.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailSummary.tsx
  suite-native/transactions/src/components/TransactionsList/TokenTransferListItem.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionIcon.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
  suite-native/transactions/src/screens/TransactionDetailScreen.tsx
  yarn.lock
Labels: mobile-app

#8142 fix(suite-native): show tokens with fiat rates
  suite-common/wallet-utils/src/accountUtils.ts
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/accounts/src/components/AccountListItemInteractive.tsx
  suite-native/accounts/src/components/TokenList.tsx
  suite-native/accounts/src/components/TokenListItem.tsx
  suite-native/accounts/tsconfig.json
  suite-native/analytics/package.json
  suite-native/analytics/src/events.ts
  suite-native/analytics/tsconfig.json
  suite-native/atoms/package.json
  suite-native/atoms/src/DiscreetText.tsx
  suite-native/atoms/tsconfig.json
  suite-native/ethereum-tokens/package.json
  suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts
  suite-native/ethereum-tokens/src/types.ts
  suite-native/ethereum-tokens/src/utils.ts
  suite-native/ethereum-tokens/tsconfig.json
  suite-native/fiat-rates/src/index.ts
  suite-native/module-accounts-import/src/components/AccountImportEthereumTokens.tsx
  suite-native/module-accounts-import/src/components/AccountImportOverviewCard.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-import/src/components/EthereumTokenInfo.tsx
  suite-native/module-settings/src/screens/SettingsPrivacyAndSecurity.tsx
  suite-native/navigation/package.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/tsconfig.json
  suite-native/transactions/src/screens/TransactionDetailScreen.tsx
  yarn.lock
Labels: mobile-app

#8169 Feat/eth detail with tokens
  suite-native/accounts/src/components/TokenList.tsx
  suite-native/accounts/src/components/TokenListItem.tsx
  suite-native/atoms/src/AlertBox.tsx
  suite-native/atoms/src/Toggle.tsx
  suite-native/atoms/src/index.ts
  suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts
  suite-native/ethereum-tokens/src/types.ts
  suite-native/ethereum-tokens/src/utils.ts
  suite-native/fiat-rates/src/utils.ts
  suite-native/module-accounts-import/src/components/EthereumTokenInfo.tsx
  suite-native/module-accounts/package.json
  suite-native/module-accounts/src/components/IncludeTokensToggle.tsx
  suite-native/module-accounts/src/components/TransactionListHeader.tsx
  suite-native/module-accounts/src/screens/AccountDetailScreen.tsx
  suite-native/module-accounts/tsconfig.json
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailIncludedCoins.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailListItem.tsx
  suite-native/transactions/src/components/TransactionsList/TokenTransferListItem.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionList.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
  yarn.lock
Labels: mobile-app

#8178 fix(suite-native): token fiat rates formatter
  suite-native/formatters/src/components/EthereumTokenToFiatAmountFormatter.tsx
Labels: mobile-app

#8179 fix(suite-native): toggle dark mode colors
  suite-native/atoms/src/Toggle.tsx
Labels: mobile-app

#8192 chore(mobile): graph animations on UI thread
  suite-native/graph/src/components/Graph.tsx
  suite-native/graph/src/components/SelectionDotWithLine.tsx
  suite-native/react-native-graph/src/AnimatedLineGraph.tsx
  suite-native/react-native-graph/src/GetYForX.ts
  suite-native/react-native-graph/src/LineGraphProps.ts
Labels: mobile-app

#8196 fix(suite-native): analytics app version
  suite-native/analytics/src/analytics.ts
Labels: mobile-app

#8206 fix(suite-native): eth detail token fixes
  suite-native/accounts/src/components/TokenList.tsx
  suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts
  suite-native/module-accounts/src/screens/AccountDetailScreen.tsx
Labels: mobile-app

#8209 fix(suite-native): include tokens copy
  suite-native/module-accounts/src/components/IncludeTokensToggle.tsx
Labels: mobile-app

#8211 fix(suite-native): button width
  suite-native/transactions/src/components/TransactionsEmptyState.tsx
Labels: mobile-app

#8217 chore(suite-native): margin above balance
  suite-native/module-home/src/components/PortfolioGraphHeader.tsx
Labels: mobile-app

#8215 Feat/assets
  suite-native/accounts/src/index.ts
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/assets/package.json
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/assets/src/components/Assets.tsx
  suite-native/assets/tsconfig.json
  suite-native/module-accounts/src/components/AccountDetailScreenHeader.tsx
  suite-native/module-accounts/src/index.ts
  suite-native/module-accounts/src/navigation/AccountsStackNavigator.tsx
  suite-native/module-accounts/src/screens/AccountDetailScreen.tsx
  suite-native/module-accounts/src/screens/AccountsScreen.tsx
  suite-native/module-home/src/components/DashboardNavigationButtons.tsx
  suite-native/module-home/src/screens/HomeScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
  yarn.lock
Labels: mobile-app

#8210 fix(mobile): reset app storage button
  suite-native/storage/src/storage.ts
Labels: mobile-app

#8183 fix(suite-native): crypto amount formatter optional ellipsis
  suite-common/formatters/src/formatters/prepareCryptoAmountFormatter.ts
  suite-common/formatters/src/formatters/tests/prepareCryptoAmountFormatter.test.ts
  suite-native/formatters/src/components/CryptoAmountFormatter.tsx
Labels: mobile-app

#8219 fix(mobile): fix import loading animation size on Android
  suite-native/module-accounts-import/src/components/AccountImportLoader.tsx
Labels: mobile-app

#8231 fix(suite-native): crypto amount formatter decimals
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/formatters/src/components/CryptoAmountFormatter.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx
Labels: mobile-app

#8230 fix(suite-native): navigation
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/assets/src/components/Assets.tsx
  suite-native/module-accounts/src/components/AccountDetailScreenHeader.tsx
  suite-native/module-accounts/src/components/AccountSettingsButtons.tsx
  suite-native/module-accounts/src/index.ts
  suite-native/module-accounts/src/screens/AccountDetailScreen.tsx
  suite-native/module-accounts/src/screens/AccountSettingsScreen.tsx
  suite-native/module-accounts/src/screens/AccountsScreen.tsx
  suite-native/module-home/package.json
  suite-native/module-home/src/navigation/HomeStackNavigator.tsx
  suite-native/module-home/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
  yarn.lock
Labels: mobile-app

#8232 chore(mobile): restrict test id props to prevent mistakes
  suite-native/atoms/src/Box.tsx
  suite-native/atoms/src/Button/Button.tsx
  suite-native/atoms/src/Text.tsx
  suite-native/atoms/src/types.ts
Labels: mobile-app

#8233 chore(suite-native): remove duplicate button
  suite-native/module-accounts/src/components/TransactionListHeader.tsx
Labels: mobile-app

#8203 chore(mobile): Improve Sentry to be production ready
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  suite-native/app/src/SentryProvider.tsx
  suite-native/app/tsconfig.json
  suite-native/config/src/environment.ts
  suite-native/module-dev-utils/package.json
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  yarn.lock
Labels: mobile-app

#8236 chore(suite-native): update fastlane
  suite-native/app/Gemfile.lock
Labels: mobile-app

#8235 fix(suite-native): cropped last transaction
  suite-native/module-accounts/src/screens/AccountDetailScreen.tsx
  suite-native/navigation/src/components/ScreenContent.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionList.tsx
Labels: mobile-app

#8240 chore(suite-native): app version
  suite-native/app/package.json
Labels: mobile-app

#8228 chore(e2e): adding data-testid attributes
  suite-native/module-accounts-import/src/components/AccountImportOverview.tsx
  suite-native/module-accounts-import/src/components/AccountImportOverviewCard.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummarySection.tsx
  suite-native/module-accounts-import/src/components/DevXpub.tsx
  suite-native/module-accounts-import/src/components/SelectableNetworkItem.tsx
  suite-native/module-accounts-import/src/components/SelectableNetworkList.tsx
  suite-native/module-accounts-import/src/components/XpubHint.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-home/src/components/DashboardNavigationButtons.tsx
  suite-native/module-onboarding/src/components/OnboardingFooter.tsx
  suite-native/module-onboarding/src/screens/AnalyticsConsentScreen.tsx
Labels: e2e

#8255 feat(suite-native): joined transaction icon
  packages/icons/assets/icons/shuffle.svg
  packages/icons/src/icons.ts
  suite-native/transactions/src/components/TransactionsList/TransactionIcon.tsx
Labels: mobile-app

#8257 feat(suite-native): pending transaction animated icon
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
Labels: mobile-app

#8264 Feat/pictograms (#8254)
  packages/icons/assets/icons/noConnection.svg
  packages/icons/assets/icons/stack.svg
  packages/icons/assets/icons/syncedCoin.svg
  packages/icons/assets/icons/warningCircleLight.svg
  packages/icons/assets/icons/warningTriangleLight.svg
  packages/icons/src/icons.ts
  suite-native/alerts/package.json
  suite-native/alerts/src/alertsAtoms.ts
  suite-native/alerts/src/components/AlertSheet.tsx
  suite-native/alerts/tsconfig.json
  suite-native/atoms/src/Pictogram.tsx
  suite-native/atoms/src/index.ts
  suite-native/module-accounts-import/src/components/AccountAlreadyImported.tsx
  suite-native/module-accounts-import/src/components/AccountImportHeader.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummary.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummarySection.tsx
  suite-native/module-accounts-import/src/useShowImportError.ts
  suite-native/module-send-receive/src/components/ReceiveTextHint.tsx
  suite-native/qr-code/src/components/XpubQRCodeWarningOverlay.tsx
  suite-native/transactions/src/assets/blockLayer.png
  suite-native/transactions/src/components/TransactionsEmptyState.tsx
  yarn.lock
Labels: mobile-app

#8266 [release] Fix/perf issue assets
  suite-common/wallet-core/src/accounts/accountsReducer.ts
Labels: mobile-app

#8267 fix: homescreen assets perf issues
  suite-common/wallet-core/src/accounts/accountsReducer.ts
Labels: mobile-app

#8281 feat(suite-native): github link replaced
  suite-native/module-settings/src/components/AboutUsBanners.tsx
Labels: mobile-app

#8280 feat(suite-native): pending transaction titles
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
Labels: mobile-app

#8276 feat(suite-native): color tokens adjustment
  packages/theme/designColors.json
  packages/theme/src/colors.ts
Labels: mobile-app

#8274 feat(suite-native): token values sheet hidden
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailSheets.tsx
  suite-native/transactions/src/screens/TransactionDetailScreen.tsx
Labels: mobile-app

#8279 feat(suite-native): transaction icons added
  packages/icons/assets/icons/arrowURightDown.svg
  packages/icons/src/icons.ts
  suite-native/transactions/src/components/TransactionsList/TransactionIcon.tsx
Labels: mobile-app

#8291 chore(suite-native): add sentry button to prod
  suite-native/module-dev-utils/src/components/ProductionDevInfo.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
Labels: mobile-app

#8293 chore(message-system): prolongs too strict fetch timeout for message-system
  packages/suite/src/actions/suite/constants/messageSystemConstants.ts
Labels: low hanging fruit, message-system
