Repository trezor/trezor-suite, pull requests merged in 2023-08, with the labels that each got.

#9085 Bump CRX version in Tor update script and update Tor binaries
  packages/suite-data/files/bin/tor/linux-arm64/tor
  packages/suite-data/files/bin/tor/linux-x64/tor
  packages/suite-data/files/bin/tor/mac-arm64/tor
  packages/suite-data/files/bin/tor/mac-x64/tor
  packages/suite-data/files/bin/tor/update.sh
  packages/suite-data/files/bin/tor/win-x64/tor.exe
Labels: release, tor

#9081 chore(suite): migrate notarization from altool to notarytool
  packages/suite-desktop-core/scripts/notarize.ts
Labels: deployment

#9082 chore(suite): sentry tree shaking
  packages/suite-build/configs/base.webpack.config.ts
Labels: sentry

#9091 Bump beta version to 23.9.0
  packages/suite/package.json
Labels: deployment

#9094 fix(suite-desktop): enable to pass apple team Id to notarization
  packages/suite-desktop-core/scripts/notarize.ts
Labels: release

#9095 fix(suite): prevent from immediate stop coinjoin when session is in critical phase
  packages/suite/src/actions/wallet/coinjoinAccountActions.ts
  packages/suite/src/components/wallet/CoinjoinSummary/CoinjoinStatusWheel/ProgressContent.tsx
  packages/suite/src/components/wallet/CoinjoinSummary/CoinjoinStatusWheel/ProgressWheel.tsx
  packages/suite/src/reducers/wallet/coinjoinReducer.ts
  packages/suite/src/support/messages.ts
Labels: release, coinjoin

#9099 chore(sentry): bump default value for max value length to see the whole errors
  suite-common/sentry/src/index.ts
Labels: release, sentry, low hanging fruit

#9098 feat(suite-native): filterable accounts list
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AccountsList.tsx
  suite-native/accounts/src/components/AccountsListGroup.tsx
  suite-native/accounts/src/selectors.ts
  suite-native/accounts/src/tests/selectors.test.ts
  suite-native/assets/package.json
  suite-native/assets/src/components/Assets.tsx
  suite-native/assets/src/components/NetworkAssetsBottomSheet.tsx
  suite-native/atoms/src/Input/Input.tsx
  suite-native/module-accounts-import/src/components/XpubHint.tsx
  suite-native/module-accounts/src/components/AccountsScreenHeader.tsx
  suite-native/module-accounts/src/components/AccountsSearchForm.tsx
  suite-native/module-accounts/src/screens/AccountsScreen.tsx
  suite-native/navigation/src/components/ScreenHeader.tsx
  suite-native/receive/src/components/ReceiveTextHint.tsx
  yarn.lock
Labels: mobile-app

#9112 chore(ci): optimize repository fetching in gitlab CI
  .gitlab-ci.yml
  ci/releases.yml
Labels: ci, code

#8947 chore(suite-native): account label migrations
  suite-native/state/src/reducers.ts
  suite-native/storage/src/index.ts
  suite-native/storage/src/migrations/account/v2.ts
  suite-native/storage/src/tests/migrations/accountV2.test.ts
  suite-native/storage/src/typedPersistReducer.ts
Labels: mobile-app

#9118 feat(suite-native): internal notifications enabled
  suite-native/app/src/App.tsx
  suite-native/notifications/src/components/Notification.tsx
Labels: mobile-app

#9124 chore(suite-native): bump app version
  suite-native/app/package.json
Labels: mobile-app

#9127 fix(suite-native): graph event extremes offset
  suite-common/graph/src/hooks.ts
Labels: mobile-app

#9142 chore(suite): improve filter function
  packages/suite/src/support/tests/configureStore.tsx
Labels: mobile-app, monorepo

#9148 chore(suite-native): add payload to account logs
  suite-common/logger/src/logsMiddleware.ts
  suite-native/logger/src/logsMiddleware.ts
Labels: mobile-app

#9154 fix(suite-native): long screen header cropped
  suite-native/navigation/src/components/ScreenHeader.tsx
Labels: mobile-app

#9147 fix(suite-native): searchable accounts
  jest.config.native.js
  package.json
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AccountsList.tsx
  suite-native/accounts/src/components/AccountsSearchForm.tsx
  suite-native/accounts/src/components/SearchableAccountsListScreenHeader.tsx
  suite-native/accounts/src/index.ts
  suite-native/accounts/src/selectors.ts
  suite-native/atoms/src/Input/SearchInput.tsx
  suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts
  suite-native/module-accounts/src/components/AccountsSearchForm.tsx
  suite-native/module-accounts/src/screens/AccountsScreen.tsx
  suite-native/module-receive/src/screens/ReceiveAccountsScreen.tsx
  suite-native/navigation/src/components/Screen.tsx
  yarn.lock
Labels: mobile-app

#9153 fix(suite-native): tokens without fiat rates glitch
  suite-native/accounts/src/components/AccountListItemInteractive.tsx
  suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts
  suite-native/module-accounts-import/src/components/AccountImportEthereumTokens.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
Labels: mobile-app

#9116 fix(coinjoin): CoinjoinBackend checkpoint(s) read-only
  packages/coinjoin/src/backend/scanAccount.ts
Labels: coinjoin

#9023 chore(suite-desktop): refactor discovery util functions
  packages/suite/src/actions/suite/__tests__/storageActions.test.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/actions/wallet/__tests__/discoveryActions.test.ts
  packages/suite/src/actions/wallet/discoveryActions.ts
  packages/suite/src/components/wallet/AccountException/AccountNotLoaded.tsx
  packages/suite/src/components/wallet/AccountException/DiscoveryFailed.tsx
  packages/suite/src/middlewares/wallet/discoveryMiddleware.ts
  packages/suite/src/middlewares/wallet/index.ts
  packages/suite/src/reducers/suite/deviceReducer.ts
  packages/suite/src/support/extraDependencies.ts
  packages/suite/src/types/wallet/index.ts
  packages/suite/src/views/dashboard/components/PortfolioCard/components/Exception.tsx
  suite-common/redux-utils/src/createMiddleware.ts
  suite-common/redux-utils/src/extraDependenciesType.ts
  suite-common/test-utils/src/extraDependenciesMock.ts
Labels: mobile-app, monorepo

#9168 chore(suite-desktop): discovery thunks
  packages/suite/src/actions/suite/__tests__/storageActions.test.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/wallet/__tests__/discoveryActions.test.ts
  packages/suite/src/actions/wallet/discoveryActions.ts
  packages/suite/src/actions/wallet/discoveryThunks.ts
  packages/suite/src/components/wallet/AccountException/AccountNotLoaded.tsx
  packages/suite/src/components/wallet/AccountException/DiscoveryFailed.tsx
  packages/suite/src/middlewares/wallet/discoveryMiddleware.ts
  packages/suite/src/reducers/wallet/discoveryReducer.ts
  packages/suite/src/types/wallet/index.ts
  packages/suite/src/utils/suite/storage.ts
  packages/suite/src/views/dashboard/components/PortfolioCard/components/Exception.tsx
  suite-common/wallet-types/src/discovery.ts
Labels: mobile-app

#9173 fix: connect Blockchain.estimateFee cache
  packages/connect/src/backend/Blockchain.ts
  packages/connect/src/backend/__tests__/Blockchain.test.ts
Labels: connect

#9169 Chore/discovery to common
  packages/suite/jest.config.js
  packages/suite/src/actions/suite/__fixtures__/suiteActions.ts
  packages/suite/src/actions/suite/__tests__/storageActions.test.ts
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/wallet/__tests__/discoveryActions.test.ts
  packages/suite/src/actions/wallet/selectedAccountActions.ts
  packages/suite/src/components/suite/SwitchDevice/components/WalletInstance.tsx
  packages/suite/src/components/wallet/AccountException/AccountNotLoaded.tsx
  packages/suite/src/components/wallet/AccountException/DiscoveryFailed.tsx
  packages/suite/src/hooks/suite/__fixtures__/useDiscovery.ts
  packages/suite/src/hooks/suite/__tests__/useDiscovery.test.tsx
  packages/suite/src/hooks/suite/useDiscovery.ts
  packages/suite/src/middlewares/suite/analyticsMiddleware.ts
  packages/suite/src/middlewares/suite/logsMiddleware.ts
  packages/suite/src/middlewares/suite/sentryMiddleware.ts
  packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts
  packages/suite/src/middlewares/wallet/discoveryMiddleware.ts
  packages/suite/src/middlewares/wallet/graphMiddleware.ts
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/reducers/wallet/index.ts
  packages/suite/src/support/extraDependencies.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/types/wallet/index.ts
  packages/suite/src/utils/suite/__tests__/logsUtils.test.ts
  packages/suite/src/utils/suite/logsUtils.ts
  packages/suite/src/views/dashboard/components/PortfolioCard/components/Exception.tsx
  suite-common/wallet-core/package.json
  suite-common/wallet-core/src/discovery/discoveryActions.ts
  suite-common/wallet-core/src/discovery/discoveryReducer.ts
  suite-common/wallet-core/src/discovery/discoveryThunks.ts
  suite-common/wallet-core/src/index.ts
  suite-common/wallet-core/tsconfig.json
  yarn.lock
Labels: monorepo

#9141 Refactor/firmware thunks
  packages/suite/src/actions/firmware/__tests__/firmwareActions.test.ts
  packages/suite/src/actions/firmware/firmwareActions.ts
  packages/suite/src/actions/firmware/firmwareThunks.ts
  packages/suite/src/actions/suite/__tests__/initAction.test.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/components/firmware/FirmwareInitial.tsx
  packages/suite/src/components/firmware/FirmwareOffer.tsx
  packages/suite/src/hooks/firmware/useRebootRequest.ts
  packages/suite/src/hooks/suite/useFirmware.ts
  packages/suite/src/middlewares/firmware/firmwareMiddleware.ts
  packages/suite/src/middlewares/firmware/index.ts
  packages/suite/src/middlewares/suite/__tests__/firmwareMiddleware.test.ts
  packages/suite/src/middlewares/suite/__tests__/suiteMiddleware.test.ts
  packages/suite/src/middlewares/suite/suiteMiddleware.ts
  packages/suite/src/reducers/desktop/index.ts
  packages/suite/src/reducers/firmware/firmwareReducer.ts
  packages/suite/src/reducers/suite/routerReducer.ts
  packages/suite/src/support/extraDependencies.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/views/dashboard/components/PortfolioCard/components/Exception.tsx
  suite-common/redux-utils/src/extraDependenciesType.ts
  suite-common/suite-types/src/firmware.ts
  suite-common/suite-types/src/index.ts
  suite-common/test-utils/src/extraDependenciesMock.ts
Labels: monorepo

#9177 chore(suite-common): firmware dir
  packages/suite/jest.config.js
  packages/suite/src/actions/firmware/__fixtures__/firmwareActions.ts
  packages/suite/src/actions/firmware/__tests__/firmwareActions.test.ts
  packages/suite/src/actions/firmware/firmwareActions.ts
  packages/suite/src/actions/suite/__tests__/suiteActions.test.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/hooks/firmware/useRebootRequest.ts
  packages/suite/src/hooks/suite/useFirmware.ts
  packages/suite/src/middlewares/firmware/firmwareMiddleware.ts
  packages/suite/src/middlewares/onboarding/onboardingMiddleware.ts
  packages/suite/src/middlewares/suite/__tests__/firmwareMiddleware.test.ts
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/reducers/firmware/index.ts
  packages/suite/src/reducers/store.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/views/settings/debug/Devkit.tsx
  suite-common/wallet-core/package.json
  suite-common/wallet-core/src/discovery/discoveryActions.ts
  suite-common/wallet-core/src/discovery/discoveryThunks.ts
  suite-common/wallet-core/src/firmware/firmwareActions.ts
  suite-common/wallet-core/src/firmware/firmwareReducer.ts
  suite-common/wallet-core/src/firmware/firmwareThunks.ts
  suite-common/wallet-core/src/index.ts
  suite-common/wallet-core/tsconfig.json
  yarn.lock
Labels: monorepo

#9161 fix(suite-native): graph event normalization
  suite-common/graph/src/hooks.ts
Labels: mobile-app

#9175 Fix/connect smart feelevels
  packages/connect/src/api/bitcoin/Fees.ts
  packages/connect/src/api/bitcoin/__tests__/Fees.test.ts
Labels: send, connect

#9199 feat(coinmarket): Add tracking event on buy buttons on Dashboard
  packages/suite-analytics/src/constants.ts
  packages/suite-analytics/src/types/events.ts
  packages/suite/src/components/wallet/CoinmarketBuyButton.tsx
Labels: +Invity

#9221 Crowdin translations update
  packages/suite-data/files/translations/af.json
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/da.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/el.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fi.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/he.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/id.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/no.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#9166 feat: add a gh action for automatically rebasing the suite e branch
  .github/workflows/bot-rebase-suite-e.yml
Labels: ci

#9234 fix(suite-native): bottom sheet grabber
  suite-native/atoms/src/Sheet/BottomSheetHeader.tsx
Labels: mobile-app, UI

#9240 Chore/analytics not initialized
  packages/analytics/src/analytics.ts
Labels: data, sentry, low hanging fruit

#9105 Feat/message system UI
  suite-common/icons/assets/icons/warningOctagon.svg
  suite-common/icons/src/icons.ts
  suite-common/message-system/src/messageSystemSelectors.ts
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  suite-native/app/tsconfig.json
  suite-native/atoms/src/AlertBox.tsx
  suite-native/atoms/src/RoundedIcon.tsx
  suite-native/link/package.json
  suite-native/link/src/components/Link.tsx
  suite-native/link/tsconfig.json
  suite-native/message-system/package.json
  suite-native/message-system/src/components/MessageBanner.tsx
  suite-native/message-system/src/components/MessageSystemRenderer.tsx
  suite-native/message-system/src/index.ts
  suite-native/message-system/tsconfig.json
  suite-native/navigation/package.json
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/tsconfig.json
  suite-native/transactions/src/components/TransactionsList/TransactionIcon.tsx
  yarn.lock
Labels: mobile-app

#9261 fix(suite): fix the suite-e rebase bot
  .github/workflows/bot-rebase-suite-e.yml
Labels: ci

#9230 fix(suite-native): inputs polishing
  suite-native/atoms/src/Input/Input.tsx
  suite-native/atoms/src/Input/SearchInput.tsx
  suite-native/atoms/src/Sheet/BottomSheet.tsx
  suite-native/forms/src/fields/TextInputField.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-accounts/src/components/AccountRenameForm.tsx
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/src/components/ScreenContent.tsx
Labels: mobile-app, UI

#9263 fix(coinmarket): Confirm on Trezor button does nothing after address change
  packages/suite/src/views/wallet/coinmarket/common/AddressOptions.tsx
Labels: bug, READY FOR REVIEW, +Invity

#9281 Disable "Reveal address" buttons for used addresses during discovery
  packages/suite/src/views/wallet/receive/components/UsedAddresses.tsx
Labels: bug, receive, UI

#9271 fix(suite-native): navigation receive icon
  suite-common/icons/assets/icons/arrowDownLight.svg
  suite-common/icons/src/icons.ts
  suite-native/app/src/navigation/routes.ts
Labels: mobile-app, UI

#9269 feat(suite-native): account list placeholder component
  suite-common/icons/assets/icons/searchLight.svg
  suite-common/icons/src/icons.ts
  suite-native/accounts/src/components/AccountListPlaceholder.tsx
  suite-native/accounts/src/components/AccountsList.tsx
  suite-native/atoms/src/Pictogram.tsx
Labels: mobile-app, UI

#9273 feat(components): spinner
  packages/components/src/components/buttons/Button/Button.tsx
  packages/components/src/components/buttons/IconButton/IconButton.tsx
  packages/components/src/components/buttons/TextButton/TextButton.tsx
  packages/components/src/components/loaders/Spinner/Spinner.stories.tsx
  packages/components/src/components/loaders/Spinner/Spinner.tsx
  packages/components/src/components/loaders/Spinner/animationData/refresh-spinner-end-success.json
  packages/components/src/components/loaders/Spinner/animationData/refresh-spinner-end-warning.json
  packages/components/src/components/loaders/Spinner/animationData/refresh-spinner-middle.json
  packages/components/src/components/loaders/Spinner/animationData/refresh-spinner-start.json
  packages/components/src/config/animations.ts
  packages/components/tsconfig.json
  packages/suite/src/components/suite/modals/CriticalCoinjoinPhase/PhaseProgress.tsx
  packages/suite/src/components/wallet/CoinControl/UtxoSelection.tsx
  packages/suite/src/components/wallet/CoinjoinSummary/CoinjoinStatusWheel/ProgressContent.tsx
  packages/suite/src/views/suite/bridge/index.tsx
Labels: components, UI

#9295 fix(suite): fix the suite-e rebase bot
  .github/workflows/bot-rebase-suite-e.yml
Labels: ci

#9162 Feat(coinmarket): edit quote payment methods to accept even not speci…
  packages/suite/package.json
  packages/suite/src/components/wallet/CoinmarketBuyOfferInfo/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/BuyTransaction/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/SavingsTransaction/index.tsx
  packages/suite/src/components/wallet/CoinmarketLayout/components/AccountTransactions/components/SellTransaction/index.tsx
  packages/suite/src/components/wallet/CoinmarketPaymentType/index.tsx
  packages/suite/src/components/wallet/CoinmarketSellOfferInfo/index.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/List/Quote/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/offers/Offers/List/Quote/index.tsx
  yarn.lock
Labels: +Invity

#9264 fix(coinmarket): Include destinationTag for recomposeAndSign call in sell
  packages/suite/src/hooks/wallet/useCoinmarketSellOffers.ts
Labels: bug, READY FOR REVIEW, +Invity

#9300 fix(suite): destructuring error
  packages/suite/src/actions/wallet/__fixtures__/coinjoinClientActions.ts
  suite-common/fiat-services/src/coingecko.ts
Labels: code
