Repository trezor/trezor-suite, pull requests merged in 2023-02, with the labels that each got.

#7489 chore(suite-native): Add support for all tx type
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemIcon.tsx
Labels: mobile-app

#7515 fix(ci): fix getting private/public JWS keys for message-system during builds
  packages/message-system/src/scripts/sign-config.ts
  packages/suite-build/configs/base.webpack.config.ts
  packages/suite-build/utils/codesign.ts
  packages/suite-build/utils/env.ts
Labels: release

#7533 fix(suite): reactivate RBF for ethereum
  suite-common/wallet-config/src/networksConfig.ts
  suite-common/wallet-utils/src/__tests__/accountUtils.test.ts
  suite-native/assets/src/tests/fixtures/assets.ts
Labels: bug, release, low hanging fruit

#7547 chore(coinjoin): temporary disable skipping rounds for testing
  packages/suite/src/services/coinjoin/config.ts
Labels: release, low hanging fruit

#7530 feat(suite): update info note & badge text parsing according to the new format
  packages/suite/src/components/wallet/CoinmarketTag/index.tsx
  packages/suite/src/utils/wallet/coinmarket/__tests__/coinmarketUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/coinmarketUtils.ts
Labels: +Invity

#7545 Remove fast fee rate median
  packages/coinjoin/README.md
  packages/coinjoin/src/constants.ts
  packages/coinjoin/src/types/client.ts
  packages/coinjoin/src/utils/roundUtils.ts
  packages/coinjoin/tests/fixtures/round.fixture.ts
  packages/coinjoin/tests/utils/roundUtils.test.ts
  packages/suite/src/actions/wallet/__tests__/coinjoinAccountActions.test.ts
  packages/suite/src/reducers/wallet/coinjoinReducer.ts
  packages/suite/src/services/coinjoin/config.ts
  packages/suite/src/utils/wallet/coinjoinUtils.ts
  packages/suite/src/views/wallet/anonymize/components/CoinjoinConfirmation.tsx
Labels: code, coinjoin

#7564 fix(suite-native): transaction detail values
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailValuesSheet.tsx
Labels: mobile-app

#7529 fix(suite-native): transaction list item layout
  suite-common/wallet-core/src/transactions/transactionsReducer.ts
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx
Labels: bug, account, mobile-app

#7359 feat(suite-native): Add logs package to common
  packages/suite/package.json
  packages/suite/src/actions/suite/__tests__/logsActions.test.ts
  packages/suite/src/actions/suite/constants/index.ts
  packages/suite/src/actions/suite/constants/logsConstants.ts
  packages/suite/src/actions/suite/logsActions.ts
  packages/suite/src/components/suite/modals/ApplicationLog.tsx
  packages/suite/src/middlewares/suite/index.ts
  packages/suite/src/middlewares/suite/logsMiddleware.ts
  packages/suite/src/reducers/store.ts
  packages/suite/src/reducers/suite/index.ts
  packages/suite/src/reducers/suite/logsReducer.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/utils/suite/logsUtils.ts
  packages/suite/src/utils/suite/sentry.ts
  packages/suite/tsconfig.json
  suite-common/logger/package.json
  suite-common/logger/src/index.ts
  suite-common/logger/src/logsMiddleware.ts
  suite-common/logger/src/logsSlice.ts
  suite-common/logger/tsconfig.json
  suite-native/logger/package.json
  suite-native/logger/src/index.ts
  suite-native/logger/src/logsMiddleware.ts
  suite-native/logger/tsconfig.json
  suite-native/state/package.json
  suite-native/state/src/reducers.ts
  suite-native/state/src/store.ts
  suite-native/state/tsconfig.json
  yarn.lock
Labels: mobile-app

#7565 feat(suite-native): address formatter
  suite-native/atoms/src/Text.tsx
  suite-native/formatters/package.json
  suite-native/formatters/src/components/AccountAddressFormatter.tsx
  suite-native/formatters/src/components/CryptoToFiatAmountFormatter.tsx
  suite-native/formatters/src/components/TransactionIdFormatter.tsx
  suite-native/formatters/src/index.ts
  suite-native/formatters/src/types.ts
  suite-native/formatters/tsconfig.json
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailInputsSheet.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailParametersSheet.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailSummary.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx
  yarn.lock
Labels: mobile-app

#7579 feat(suite-native): show logs
  suite-native/module-dev-utils/package.json
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/module-dev-utils/tsconfig.json
  yarn.lock
Labels: mobile-app

#7506 fix(suite-native): Date ordering
  suite-common/formatters/src/FormatterProvider.tsx
  suite-common/formatters/src/formatters/prepareDateFormatter.ts
  suite-common/formatters/src/formatters/prepareDateTimeFormatter.ts
  suite-common/formatters/src/formatters/prepareMonthNameFormatter.ts
  suite-common/wallet-utils/src/__tests__/transactionUtils.test.ts
  suite-common/wallet-utils/src/transactionUtils.ts
  suite-native/transactions/src/components/TransactionsList/TransactionList.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListGroupTitle.tsx
Labels: mobile-app

#7590 chore(suite-native): move copy above logs
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
Labels: mobile-app

#7518 Refactor/button components
  suite-native/assets/src/components/Assets.tsx
  suite-native/atoms/src/Button/Button.tsx
  suite-native/atoms/src/Button/IconButton.tsx
  suite-native/atoms/src/Button/useButtonPressAnimatedStyle.ts
  suite-native/atoms/src/Sheet/BottomSheetHeader.tsx
  suite-native/module-accounts-import/src/components/AccountAlreadyImported.tsx
  suite-native/module-accounts-import/src/components/AccountImportHeader.tsx
  suite-native/module-accounts-import/src/components/AccountImportOverview.tsx
  suite-native/module-accounts-import/src/components/DevXpub.tsx
  suite-native/module-accounts-import/src/components/SelectableNetworkItem.tsx
  suite-native/module-accounts/src/components/AccountDetailScreenHeader.tsx
  suite-native/module-accounts/src/components/AccountsScreenHeader.tsx
  suite-native/module-accounts/src/components/TransactionListHeader.tsx
  suite-native/module-accounts/src/screens/AccountSettingsScreen.tsx
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-home/src/components/DashboardHeader.tsx
  suite-native/module-send-receive/src/components/ReceiveTextHint.tsx
  suite-native/navigation/src/components/ScreenHeader.tsx
  suite-native/qr-code/src/components/QRCode.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailParametersSheet.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailSheet.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailSummary.tsx
  suite-native/transactions/src/components/TransactionsEmptyState.tsx
  suite-native/transactions/src/screens/TransactionDetailScreen.tsx
Labels: components, mobile-app

#7563 Feat/xpub loading screen
  suite-native/atoms/src/Loader.tsx
  suite-native/atoms/src/index.ts
  suite-native/graph/src/components/Graph.tsx
  suite-native/module-accounts-import/src/assets/globe.png
  suite-native/module-accounts-import/src/components/AccountAlreadyImported.tsx
  suite-native/module-accounts-import/src/components/AccountImportHeader.tsx
  suite-native/module-accounts-import/src/components/AccountImportLoader.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummary.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-import/src/navigation/AccountsImportStackNavigator.tsx
  suite-native/module-accounts-import/src/screens/AccountImportLoadingScreen.tsx
  suite-native/module-accounts-import/src/screens/AccountImportSummaryScreen.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/navigation/package.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/navigation/tsconfig.json
  suite-native/qr-code/src/components/QRCodeScanner.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionList.tsx
  yarn.lock
Labels: onboarding, mobile-app

#7598 feat(suite-native): graph selection dot with line
  suite-native/graph/src/components/Graph.tsx
  suite-native/graph/src/components/SelectionDotWithLine.tsx
Labels: graph, mobile-app

#7586 feat(suite-native): percentage difference formatter
  suite-native/formatters/src/components/PercentageDifferenceFormatter.tsx
  suite-native/formatters/src/index.ts
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailValuesSheet.tsx
Labels: mobile-app

#7604 fix(suite-native): graph selection line always visible
  suite-native/graph/src/components/SelectionDotWithLine.tsx
Labels: bug, graph, mobile-app

#7621 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#7492 feat(suite-native): fiat rates hidden for testnet coins
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/assets/package.json
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/assets/tsconfig.json
  suite-native/atoms/src/DiscreetText.tsx
  suite-native/atoms/src/Text.tsx
  suite-native/formatters/package.json
  suite-native/formatters/src/components/CryptoAmountFormatter.tsx
  suite-native/formatters/src/components/CryptoToFiatAmountFormatter.tsx
  suite-native/formatters/src/components/FiatAmountFormatter.tsx
  suite-native/formatters/src/index.ts
  suite-native/formatters/tsconfig.json
  suite-native/graph/package.json
  suite-native/graph/src/components/AxisLabel.tsx
  suite-native/graph/tsconfig.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/components/AccountImportOverview.tsx
  suite-native/module-accounts-import/tsconfig.json
  suite-native/module-accounts/package.json
  suite-native/module-accounts/src/components/AccountBalance.tsx
  suite-native/module-accounts/src/components/TransactionListHeader.tsx
  suite-native/module-accounts/tsconfig.json
  suite-native/module-home/package.json
  suite-native/module-home/src/components/PortfolioGraphHeader.tsx
  suite-native/module-home/tsconfig.json
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailInputsSheet.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailSheet.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailSheets.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx
  yarn.lock
Labels: mobile-app

#7651 fix(suite-native): video layout
  suite-native/video-assets/src/components/Video.tsx
Labels: bug, mobile-app

#7650 chore(suite-native): remove unused dependencies
  suite-native/assets/package.json
  suite-native/assets/tsconfig.json
  suite-native/atoms/package.json
  suite-native/atoms/tsconfig.json
  suite-native/forms/package.json
  suite-native/graph/package.json
  suite-native/graph/tsconfig.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/tsconfig.json
  suite-native/module-accounts/package.json
  suite-native/module-accounts/tsconfig.json
  suite-native/module-devices/package.json
  suite-native/module-home/package.json
  suite-native/module-home/tsconfig.json
  suite-native/module-send-receive/package.json
  suite-native/module-send-receive/tsconfig.json
  suite-native/module-settings/package.json
  suite-native/module-settings/tsconfig.json
  suite-native/navigation/package.json
  suite-native/state/package.json
  suite-native/state/tsconfig.json
  suite-native/test-utils/package.json
  suite-native/video-assets/package.json
  yarn.lock
Labels: mobile-app

#7654 fix(suite-native): update RN version
  suite-native/video-assets/package.json
  yarn.lock
Labels: mobile-app

#7687 refactor(suite-native): print mocked values of extra dependencies onl…
  suite-common/test-utils/src/extraDependenciesMock.ts
Labels: mobile-app

#7683 fix(translations): fix duplicated id for TR_CHECK_RECOVERY_SEED_DESC_TR translation key
  packages/suite/src/support/messages.ts
Labels: copy, low hanging fruit

#7684 feat(message-system, coinjoin): increase the roundsFailRateBuffer and disable coinjoin for Suite below 23.2.2
  packages/message-system/src/config/config.v1.json
Labels: message-system

#7636 Feat/rename account
  packages/icons/assets/icons/pencil.svg
  packages/icons/src/icons.ts
  suite-common/wallet-core/src/accounts/accountsActions.ts
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/accounts/package.json
  suite-native/accounts/src/index.ts
  suite-native/accounts/src/useAccountLabelForm.ts
  suite-native/accounts/tsconfig.json
  suite-native/atoms/src/Button/Button.tsx
  suite-native/atoms/src/Button/IconButton.tsx
  suite-native/atoms/src/Button/useButtonPressAnimatedStyle.ts
  suite-native/atoms/src/Sheet/useBottomSheetAnimation.ts
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts/package.json
  suite-native/module-accounts/src/components/AccountDetailScreenHeader.tsx
  suite-native/module-accounts/src/components/AccountRenameButton.tsx
  suite-native/module-accounts/src/components/AccountRenameForm.tsx
  suite-native/module-accounts/src/screens/AccountDetailScreen.tsx
  suite-native/module-accounts/src/screens/AccountSettingsScreen.tsx
  suite-native/module-accounts/tsconfig.json
  suite-native/navigation/src/components/ScreenHeader.tsx
  yarn.lock
Labels: account, mobile-app

#7681 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#7675 fix(suite-native): where is my xpub button always visible
  suite-native/module-accounts-import/src/components/XpubHint.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/src/components/ScreenContent.tsx
Labels: mobile-app

#7696 fix(suite-native): ios build
  suite-native/app/package.json
Labels: mobile-app

#7702 chore(mobile): use native stack for navigation
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/navigation/AccountsImportStackNavigator.tsx
  suite-native/module-accounts/package.json
  suite-native/module-accounts/src/navigation/AccountsStackNavigator.tsx
  suite-native/module-dev-utils/package.json
  suite-native/module-dev-utils/src/navigation/DevUtilsStackNavigator.tsx
  suite-native/module-home/package.json
  suite-native/module-home/src/navigation/HomeStackNavigator.tsx
  suite-native/module-settings/package.json
  suite-native/module-settings/src/navigation/SettingsStackNavigator.tsx
  suite-native/navigation/package.json
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/src/config.ts
  suite-native/navigation/src/types.tsx
  yarn.lock
Labels: mobile-app

#7720 chore(coinjoin): update affiliateRequest format
  packages/coinjoin/src/client/round/transactionSigning.ts
  packages/coinjoin/src/utils/roundUtils.ts
  packages/coinjoin/tests/client/transactionSigning.test.ts
  packages/coinjoin/tests/utils/roundUtils.test.ts
Labels: release, coinjoin

#7725 feat(coinjoin): allow coinjoin account outside debug mode
  packages/suite/src/components/suite/modals/AddAccount/index.tsx
Labels: release, coinjoin

#7726 Removed terms duplicate
  packages/suite/src/views/wallet/anonymize/components/CoinjoinConfirmation.tsx
  packages/urls/src/urls.ts
Labels: low hanging fruit, coinjoin

#7732 chore(suite): bump beta version to 23.4.0
  packages/suite/package.json
Labels: low hanging fruit

#7733 Report network ('btc' | 'test' | 'regtest') to sentry together with coinjoin error
  packages/suite-desktop/src/modules/coinjoin.ts
  suite-common/sentry/src/index.ts
Labels: release, low hanging fruit, coinjoin
