Repository trezor/trezor-suite, pull requests merged in 2023-11, with the labels that each got.

#9811 Commit only package.json changes when updating version with the release script
  scripts/prepare-release.sh
Labels: deployment

#9812 feat(coinmarket): simplify Trade box
  packages/suite/src/components/suite/OverflowItems.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/transactions/TradeBox/TradeBoxMenu.tsx
Labels: +Invity

#9814 fix(suite-native): update QR screen brightness on going to bg
  suite-native/qr-code/src/components/QRCode.tsx
Labels: mobile-app

#9804 chore(suite): bump beta version to 23.12.0
  packages/suite/package.json
Labels: deployment

#9824 fix(suite-native): correct percentage on value gain
  suite-native/formatters/src/components/PercentageDifferenceFormatter.tsx
Labels: mobile-app

#9806 feat(suite-native): localized number for crypto amount formatter
  suite-native/formatters/src/components/CryptoAmountFormatter.tsx
  suite-native/formatters/src/utils.ts
Labels: mobile-app

#9825 test(suite): sendform regetest test
  packages/suite-web/e2e/tests/wallet/send-form-regtest.test.ts
Labels: e2e

#9798 feat(suite-native): updated AlertBox visual with versions
  suite-common/icons/assets/icons/checkCircle.svg
  suite-common/icons/src/icons.ts
  suite-native/app/ios/Podfile.lock
  suite-native/atoms/package.json
  suite-native/atoms/src/AlertBox.tsx
  suite-native/atoms/src/Card/Card.tsx
  suite-native/module-accounts-management/src/components/IncludeTokensToggle.tsx
  suite-native/module-dev-utils/package.json
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-dev-utils/tsconfig.json
  suite-native/module-home/src/components/EmptyPortfolioTrackerState.tsx
  suite-native/receive/src/components/ReceiveAccount.tsx
  yarn.lock
Labels: mobile-app

#9767 feat(suite-native): mark possible address poisoning txns (#7400)
  suite-common/wallet-core/src/transactions/transactionsReducer.ts
  suite-native/atoms/src/Badge.tsx
  suite-native/intl/src/en.ts
  suite-native/transactions/package.json
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
  suite-native/transactions/tsconfig.json
  yarn.lock
Labels: mobile-app

#9829 Fix/device/auth without passphrase
  packages/suite/src/views/dashboard/components/PortfolioCard/components/Exception.tsx
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-native/device/src/middlewares/deviceMiddleware.ts
Labels: mobile-app

#9838 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#9841 feat(connect-common): add T2T1 & T2B1 firmware binaries 2.6.3 bootloader 2.1.4
  packages/connect-common/files/devkit/firmware/t2b1/trezor-t2b1-2.6.2-bitcoinonly.bin
  packages/connect-common/files/devkit/firmware/t2b1/trezor-t2b1-2.6.2.bin
  packages/connect-common/files/firmware/t2b1/releases.json
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.6.2-bitcoinonly.bin
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.6.2.bin
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.6.3-bitcoinonly.bin
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.6.3.bin
  packages/connect-common/files/firmware/t2t1/releases.json
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.6.0-bitcoinonly.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.6.0.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.6.3-bitcoinonly.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.6.3.bin
Labels: release

#9843 fix(suite): disable reboot to bootloader with WebUSB
  packages/suite/src/hooks/firmware/useRebootRequest.ts
Labels: release

#9840 Fix/device selection
  suite-common/wallet-core/src/device/deviceConstants.ts
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-native/app/ios/Podfile.lock
  suite-native/device/package.json
  suite-native/device/src/middlewares/deviceMiddleware.ts
  suite-native/device/tsconfig.json
  suite-native/feature-flags/package.json
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/feature-flags/src/index.ts
  suite-native/feature-flags/src/useIsUsbDeviceConnectFeatureEnabled.tsx
  suite-native/feature-flags/tsconfig.json
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  suite-native/module-home/src/components/EmptyHomeRenderer.tsx
  suite-native/module-onboarding/src/components/OnboardingScreenHeader.tsx
  suite-native/module-onboarding/src/screens/WelcomeScreen.tsx
  suite-native/state/package.json
  suite-native/state/src/reducers.ts
  suite-native/state/tsconfig.json
  yarn.lock
Labels: mobile-app

#9848 refactor(suite-native): utilize getDescriptors connect method
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/discovery/src/utils.ts
Labels: mobile-app

#9849 chore(suite-native): bump native version
  suite-native/app/package.json
Labels: mobile-app

#9868 fix(suite-native): make thousands formatting work on all cases
  suite-native/formatters/src/components/CryptoAmountFormatter.tsx
Labels: mobile-app

#9876 fix(suite): set sequence to undefined for final transactions
  packages/suite/src/actions/wallet/send/sendFormBitcoinActions.ts
Labels: bug, release

#9830 fix(suite-native): fix not rendering text on android search in portfolio
  suite-native/accounts/src/components/AccountsSearchForm.tsx
  suite-native/atoms/src/Input/SearchInput.tsx
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
Labels: mobile-app

#9878 fix(suite-native): infinite discovery loop
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile-app

#9844 Feat/verify receive address
  packages/suite/jest.config.js
  packages/suite/src/actions/wallet/__fixtures__/receiveActions.ts
  packages/suite/src/actions/wallet/__tests__/receiveActions.test.ts
  packages/suite/src/actions/wallet/coinmarket/coinmarketCommonActions.ts
  packages/suite/src/actions/wallet/receiveActions.ts
  packages/suite/src/actions/wallet/send/sendFormCardanoActions.ts
  packages/suite/src/actions/wallet/sendFormActions.ts
  packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModal.tsx
  packages/suite/src/hooks/wallet/useCardanoStaking.ts
  packages/suite/src/utils/wallet/cardanoUtils.ts
  packages/suite/src/utils/wallet/reviewTransactionUtils.ts
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/TokenSelect.tsx
  packages/theme/fonts/RobotoMono-Regular.ttf
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-common/wallet-core/src/discovery/discoveryThunks.ts
  suite-common/wallet-utils/src/__fixtures__/cardanoUtils.ts
  suite-common/wallet-utils/src/__tests__/cardanoUtils.test.ts
  suite-common/wallet-utils/src/cardanoUtils.ts
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/config/src/supportedNetworks.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts
  suite-native/helpers/package.json
  suite-native/helpers/src/index.ts
  suite-native/helpers/src/splitAddressToChunks.ts
  suite-native/helpers/src/tests/splitAddressToChunks.test.ts
  suite-native/intl/src/en.ts
  suite-native/module-receive/src/navigation/ReceiveStackNavigator.tsx
  suite-native/module-receive/src/screens/ReceiveScreen.tsx
  suite-native/qr-code/package.json
  suite-native/qr-code/src/components/AddressQRCode.tsx
  suite-native/qr-code/tsconfig.json
  suite-native/receive/assets/confirmOnTrezor.png
  suite-native/receive/package.json
  suite-native/receive/src/components/ConfirmOnTrezorImage.tsx
  suite-native/receive/src/components/ReceiveAccount.tsx
  suite-native/receive/src/components/ReceiveAccountDetailsCard.tsx
  suite-native/receive/src/components/ReceiveAddress.tsx
  suite-native/receive/src/components/ReceiveAddressCard.tsx
  suite-native/receive/src/components/ReceiveTextHint.tsx
  suite-native/receive/src/components/ShowAddressButtons.tsx
  suite-native/receive/src/components/UnverifiedAddress.tsx
  suite-native/receive/src/components/UnverifiedAddressDevice.tsx
  suite-native/receive/src/components/UnverifiedAddressDeviceHint.tsx
  suite-native/receive/src/components/UnverifiedAddressWarning.tsx
  suite-native/receive/src/hooks/useAccountReceiveAddress.tsx
  suite-native/receive/src/index.ts
  suite-native/receive/src/redux.d.ts
  suite-native/receive/src/screens/ReceiveModal.tsx
  suite-native/receive/src/screens/ReceiveModalScreen.tsx
  suite-native/receive/tsconfig.json
  yarn.lock
Labels: mobile-app

#9882 Fix/discovery improvements
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-common/wallet-core/src/discovery/discoveryThunks.ts
  suite-native/discovery/src/discoveryMiddleware.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/discovery/src/utils.ts
Labels: mobile-app

#9877 feat(suite-common): add optional title to messages
  docs/features/message-system.md
  suite-common/message-system/schema/config.schema.v1.json
  suite-common/message-system/src/messageSystemTypes.ts
  suite-common/suite-types/src/messageSystem.ts
Labels: message-system

#9930 fix(suite-native): empty state tab bar
  suite-native/navigation/src/components/TabBar.tsx
Labels: mobile-app

#9893 chore(suite-native): manage device
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/atoms/src/Button/IconButton.tsx
  suite-native/device-manager/package.json
  suite-native/device-manager/src/components/DeviceControlButtons.tsx
  suite-native/device-manager/src/components/DeviceItem.tsx
  suite-native/device-manager/src/components/DeviceManager.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/device-manager/src/components/DeviceManagerModal.tsx
  suite-native/device-manager/src/components/DeviceSwitch.tsx
  suite-native/device-manager/src/components/PortfolioTrackerDeviceManagerContent.tsx
  suite-native/device-manager/tsconfig.json
  suite-native/device/package.json
  suite-native/device/src/assets/t1.png
  suite-native/device/src/assets/ts3.png
  suite-native/device/src/assets/tt.png
  suite-native/device/src/index.ts
  suite-native/device/src/screens/DeviceInfoModalScreen.tsx
  suite-native/device/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile-app

#9899 feat(suite-native): feature messages and killswitch handling
  suite-native/app/.env.production
  suite-native/app/fastlane/Fastfile
  suite-native/app/src/App.tsx
  suite-native/app/src/initActions.ts
  suite-native/atoms/src/Pictogram.tsx
  suite-native/intl/src/en.ts
  suite-native/message-system/package.json
  suite-native/message-system/src/components/MessageScreen.tsx
  suite-native/message-system/src/components/MessageSystemRenderer.tsx
  suite-native/message-system/tsconfig.json
  yarn.lock
Labels: mobile-app

#9952 fix(suite-native): correct brightness on iphone when leaving app
  suite-native/qr-code/src/components/QRCode.tsx
Labels: mobile-app

#9934 Feat/verify address modals
  suite-native/atoms/src/AlertBox.tsx
  suite-native/atoms/src/BulletListItem.tsx
  suite-native/atoms/src/Card/Card.tsx
  suite-native/atoms/src/Sheet/BottomSheet.tsx
  suite-native/atoms/src/Sheet/BottomSheetHeader.tsx
  suite-native/atoms/src/index.ts
  suite-native/intl/src/en.ts
  suite-native/module-home/src/components/BiometricsBottomSheet.tsx
  suite-native/module-home/src/components/EmptyPortfolioTrackerState.tsx
  suite-native/receive/package.json
  suite-native/receive/src/components/AddressMismatchBottomSheet.tsx
  suite-native/receive/src/components/ConfirmOnTrezorBottomSheet.tsx
  suite-native/receive/src/components/ConfirmOnTrezorImage.tsx
  suite-native/receive/src/components/ReceiveAccount.tsx
  suite-native/receive/src/components/ReceiveAddressBottomSheetHeader.tsx
  suite-native/receive/src/components/ReceiveAddressCard.tsx
  suite-native/receive/src/components/ShowAddressButtons.tsx
  suite-native/receive/src/components/UnverifiedAddressDeviceHint.tsx
  suite-native/receive/src/components/VerificationWalkthroughBottomSheet.tsx
  suite-native/receive/tsconfig.json
  yarn.lock
Labels: mobile-app

#9940 Testing stages
  .gitlab-ci.yml
  ci/test.yml
Labels: e2e

#9967 fix(suite-native): address walkthrough reset
  suite-native/receive/src/components/VerificationWalkthroughBottomSheet.tsx
Labels: mobile-app

#9937 fix(suite-native): rerendering of dashboard
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/accounts/src/components/AccountsListGroup.tsx
  suite-native/assets/package.json
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/assets/src/components/Assets.tsx
  suite-native/assets/src/components/NetworkAssetsBottomSheet.tsx
  suite-native/atoms/src/Skeleton/ListItemSkeleton.tsx
  yarn.lock
Labels: mobile-app

#9966 fix(suite-native): receive from tabbar navigation
  suite-native/module-receive/src/screens/ReceiveAccountsScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
Labels: mobile-app

#9905 Device Firmware warnings
  suite-native/alerts/src/alertsAtoms.ts
  suite-native/alerts/src/components/AlertSheet.tsx
  suite-native/app/ios/Podfile.lock
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/device/package.json
  suite-native/device/src/hooks/useDeviceConnect.tsx
  suite-native/device/src/index.ts
  suite-native/device/src/utils.ts
  suite-native/device/tsconfig.json
  suite-native/discovery/package.json
  suite-native/discovery/src/discoveryMiddleware.ts
  suite-native/discovery/tsconfig.json
  suite-native/helpers/package.json
  suite-native/helpers/src/utils.ts
  suite-native/helpers/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-connect-device/src/screens/ConnectAndUnlockDeviceScreen.tsx
  suite-native/module-home/package.json
  suite-native/module-home/src/components/EmptyPortfolioCrossroads.tsx
  suite-native/module-home/tsconfig.json
  yarn.lock
Labels: mobile-app

#9974 chore(github): fix link to support in github template
  .github/ISSUE_TEMPLATE/config.yml
Labels: low hanging fruit

#9981 fix(suite-native): card alert gap
  suite-native/atoms/src/Card/Card.tsx
Labels: mobile-app

#9978 fix(connect-ui): fix analytics z index in connect ui
  packages/components/src/components/DataAnalytics.tsx
  packages/connect-ui/src/components/AnalyticsConsentWrapper.tsx
  packages/connect-ui/src/components/BottomRightFloatingBar.tsx
Labels: connect-popup

#9979 feat(suite-native): device info detail
  packages/device-utils/src/firmwareUtils.ts
  suite-common/wallet-core/src/device/deviceActions.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/device-manager/src/components/DeviceControlButtons.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/device/package.json
  suite-native/device/src/components/HowToUpdateBottomSheet.tsx
  suite-native/device/src/hooks/useDeviceConnect.tsx
  suite-native/device/src/middlewares/deviceMiddleware.ts
  suite-native/device/src/screens/DeviceInfoModalScreen.tsx
  suite-native/device/src/utils.ts
  suite-native/device/tsconfig.json
  suite-native/discovery/package.json
  suite-native/discovery/src/discoveryMiddleware.ts
  suite-native/discovery/tsconfig.json
  suite-native/intl/src/en.ts
  yarn.lock
Labels: mobile-app

#9987 feat(suite-native): native device access mutex
  suite-native/device-mutex/package.json
  suite-native/device-mutex/src/DeviceAccessMutex.ts
  suite-native/device-mutex/src/index.ts
  suite-native/device-mutex/src/requestDeviceAccess.ts
  suite-native/device-mutex/src/tests/DeviceAccessMutex.test.ts
  suite-native/device-mutex/tsconfig.json
  suite-native/discovery/package.json
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/discovery/src/utils.ts
  suite-native/discovery/tsconfig.json
  suite-native/receive/package.json
  suite-native/receive/src/hooks/useAccountReceiveAddress.tsx
  suite-native/receive/tsconfig.json
  yarn.lock
Labels: mobile-app

#10012 fix(components): fix tooltip not unmounting onMouseLeave
  packages/components/src/components/Tooltip/Tooltip.tsx
Labels: bug

#10029 fix(suite-native): receive sheets hidden for portfolio tracker
  suite-native/receive/src/components/ShowAddressButtons.tsx
Labels: mobile-app

#10031 feat(suite-native): wipe disconnected device data
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-common/wallet-core/src/discovery/discoveryReducer.ts
  suite-common/wallet-core/src/discovery/discoveryThunks.ts
  suite-native/app/src/initActions.ts
  suite-native/device/package.json
  suite-native/device/src/deviceThunks.ts
  suite-native/device/src/index.ts
  suite-native/device/src/middlewares/deviceMiddleware.ts
  suite-native/device/tsconfig.json
  yarn.lock
Labels: mobile-app

#10020 fix(suite-native): device manager UI bugs
  suite-common/icons/assets/icons/trezorConnectedDark.svg
  suite-common/icons/assets/icons/trezorConnectedLight.svg
  suite-common/icons/src/components/Icon.tsx
  suite-common/icons/src/icons.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/device-manager/package.json
  suite-native/device-manager/src/components/DeviceControlButtons.tsx
  suite-native/device-manager/src/components/DeviceItem.tsx
  suite-native/device-manager/src/components/DeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/device-manager/src/components/DeviceManagerModal.tsx
  suite-native/device-manager/src/components/DeviceSwitch.tsx
  suite-native/device-manager/src/components/PortfolioTrackerDeviceManagerContent.tsx
  suite-native/device-manager/tsconfig.json
  suite-native/intl/src/en.ts
  yarn.lock
Labels: mobile-app

#10030 feat(suite-native): all assets displayed in dashboard
  suite-native/assets/src/components/Assets.tsx
  suite-native/assets/src/components/DiscoveryAssetsLoader.tsx
  suite-native/graph/package.json
  suite-native/graph/src/components/Graph.tsx
  suite-native/graph/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-home/src/components/PortfolioContent.tsx
  suite-native/module-home/src/constants.ts
  yarn.lock
Labels: mobile-app

#9990 Feat/device address per model
  packages/theme/fonts/PixelOperatorMono8-Regular.ttf
  suite-common/icons/src/components/Icon.tsx
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-native/receive/assets/addressPaginationPrefixT2B1.svg
  suite-native/receive/assets/addressPaginationPrefixT2T1.svg
  suite-native/receive/assets/addressPaginationSuffixT2B1.svg
  suite-native/receive/assets/addressPaginationSuffixT2T1.svg
  suite-native/receive/assets/pager1T2B1.svg
  suite-native/receive/assets/pager1T2T1.svg
  suite-native/receive/assets/pager2T2B1.svg
  suite-native/receive/assets/pager2T2T1.svg
  suite-native/receive/package.json
  suite-native/receive/src/components/DevicePaginationButton.tsx
  suite-native/receive/src/components/DeviceScreenContent.tsx
  suite-native/receive/src/components/DeviceScreenPagination.tsx
  suite-native/receive/src/components/ReceiveAddressCard.tsx
  suite-native/receive/src/components/UnverifiedAddress.tsx
  suite-native/receive/src/components/UnverifiedAddressDevice.tsx
  suite-native/receive/src/constants.ts
  suite-native/receive/src/types.ts
  suite-native/receive/src/utils.ts
  suite-native/receive/tsconfig.json
  yarn.lock
Labels: mobile-app

#10045 fix(mobile): fix crash when click on asset item
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/assets/src/components/AssetItem.tsx
Labels: mobile-app

#10061 Fix/discovery fixes
  suite-native/discovery/src/discoveryMiddleware.ts
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile-app

#10063 Fix/device redirect fixes
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/device-manager/src/components/DeviceControlButtons.tsx
  suite-native/device-manager/src/components/DeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/device-manager/src/components/DeviceSwitch.tsx
  suite-native/device/src/hooks/useDeviceConnect.tsx
  suite-native/intl/src/en.ts
  suite-native/module-home/src/components/EmptyHomeRenderer.tsx
Labels: mobile-app

#10064 Fix/device manager ios fixes
  suite-common/icons/assets/icons/link.svg
  suite-common/icons/src/icons.ts
  suite-native/app/ios/Podfile.lock
  suite-native/atoms/src/ScreenHeaderWrapper.tsx
  suite-native/device-manager/package.json
  suite-native/device-manager/src/components/DeviceSwitch.tsx
  suite-native/device-manager/src/components/PortfolioTrackerDeviceManagerContent.tsx
  suite-native/device-manager/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/message-system/src/components/MessageSystemRenderer.tsx
  yarn.lock
Labels: mobile-app

#10068 feat(suite-native): receive subheader icon added
  suite-native/receive/src/screens/ReceiveModalScreen.tsx
Labels: mobile-app

#10075 ref(suite-native): remove subheader / header from layers
  suite-native/accounts/src/components/SearchableAccountsListScreenHeader.tsx
  suite-native/app/ios/Podfile.lock
  suite-native/module-accounts-import/src/screens/AccountImportLoadingScreen.tsx
  suite-native/module-accounts-import/src/screens/AccountImportSummaryScreen.tsx
  suite-native/module-accounts-import/src/screens/ScanQRCodeModalScreen.tsx
  suite-native/module-accounts-import/src/screens/SelectNetworkScreen.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-accounts-management/src/screens/AccountDetailScreen.tsx
  suite-native/module-accounts-management/src/screens/AccountSettingsScreen.tsx
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/module-settings/src/screens/SettingsAboutUsScreen.tsx
  suite-native/module-settings/src/screens/SettingsCustomizationScreen.tsx
  suite-native/module-settings/src/screens/SettingsFAQScreen.tsx
  suite-native/module-settings/src/screens/SettingsLocalizationScreen.tsx
  suite-native/module-settings/src/screens/SettingsPrivacyAndSecurity.tsx
  suite-native/module-settings/src/screens/SettingsScreen.tsx
  suite-native/navigation/src/components/ScreenSubHeader.tsx
  suite-native/receive/src/screens/ReceiveModalScreen.tsx
  suite-native/transactions/src/screens/TransactionDetailScreen.tsx
Labels: mobile-app

#10077 fix(suite-native): tab bar display rules
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/module-home/src/components/EmptyHomeRenderer.tsx
  suite-native/navigation/src/components/TabBar.tsx
Labels: mobile-app

#10078 Fix/sync coins button dashboard
  suite-native/intl/src/en.ts
  suite-native/module-home/src/components/DashboardNavigationButtons.tsx
  suite-native/module-home/src/components/PortfolioContent.tsx
Labels: mobile-app

#10090 fix(suite-native): feature flag in crossroads condition
  suite-native/module-home/src/components/EmptyHomeRenderer.tsx
Labels: mobile-app

#10097 fix(e2e): outputlabeling test
  packages/suite-web/e2e/tests/metadata/output-labeling.test.ts
Labels: e2e

#10082 fix(suite): fix the eject icon
  packages/components/src/images/icons/eject.svg
Labels: UI

#10102 Fix/message system renderer
  suite-native/app/src/App.tsx
  suite-native/message-system/src/components/FeatureMessageScreen.tsx
  suite-native/message-system/src/components/MessageSystemBannerRenderer.tsx
  suite-native/message-system/src/components/MessageSystemRenderer.tsx
  suite-native/message-system/src/index.ts
Labels: mobile-app

#10111 fix(suite-native): device label instead device name
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/device/src/screens/DeviceInfoModalScreen.tsx
Labels: mobile-app

#10081 fix(suite): fix modal header incorrectly being rendered when there ar…
  packages/suite/src/components/suite/modals/Modal/DefaultRenderer.tsx
Labels: UI

#10117 feat(suite-native): add missing model name
  suite-native/device/src/screens/DeviceInfoModalScreen.tsx
Labels: mobile-app

#10109 fix(suite-native): connecting screen redirects
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/device/src/hooks/useAuthorizeDevice.ts
  suite-native/device/src/hooks/useDetectDeviceError.tsx
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/device/src/index.ts
  suite-native/device/src/selectors.ts
  suite-native/module-connect-device/src/screens/ConnectingDeviceScreen.tsx
  suite-native/module-home/package.json
  suite-native/module-home/src/components/EmptyHomeRenderer.tsx
  suite-native/module-home/tsconfig.json
  yarn.lock
Labels: mobile-app

#10124 fix(suite-native): ADA xpub is not displayed as receive address
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/module-accounts-import/src/screens/AccountImportLoadingScreen.tsx
Labels: mobile-app

#10093 feat(coinmarket): Hide exchange section for bitcoin only device
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayout/CoinmarketLayoutNavigation.tsx
  packages/suite/src/views/wallet/transactions/TradeBox/TradeBoxMenu.tsx
Labels: +Invity
