Repository trezor/trezor-suite, pull requests merged in 2023-10, with the labels that each got.

#9539 fix(coinmarket): Fix address label not showing in dropdown
  packages/suite/src/views/wallet/coinmarket/common/AddressOptions.tsx
Labels: +Invity

#9511 chore(suite-native): Connect device
  packages/suite/src/reducers/wallet/coinjoinReducer.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/app/ios/Podfile.lock
  suite-native/intl/src/en.ts
  suite-native/module-connect-device/package.json
  suite-native/module-connect-device/src/components/ConnectDeviceBackground.tsx
  suite-native/module-connect-device/src/components/PinForm.tsx
  suite-native/module-connect-device/src/components/PinFormProgress.tsx
  suite-native/module-connect-device/src/components/PinFromControlButtons.tsx
  suite-native/module-connect-device/src/navigation/ConnectDeviceStackNavigator.tsx
  suite-native/module-connect-device/src/screens/ConnectAndUnlockDeviceScreen.tsx
  suite-native/module-connect-device/src/screens/ConnectDeviceCrossroadsScreen.tsx
  suite-native/module-connect-device/src/screens/ConnectingDeviceScreen.tsx
  suite-native/module-connect-device/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile-app

#9607 fix(components): clean focus style
  packages/components/src/components/Badge/Badge.tsx
  packages/components/src/components/buttons/Button/Button.tsx
  packages/components/src/components/buttons/TextButton/TextButton.tsx
  packages/components/src/components/buttons/buttonStyleUtils.ts
  packages/components/src/components/form/Switch/Switch.tsx
  packages/components/src/utils/utils.ts
Labels: code

#9576 Chore/connect t1 with pin
  packages/connect/src/core/index.ts
  packages/suite/jest.config.js
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/PinModal.tsx
  packages/suite/src/middlewares/suite/buttonRequestMiddleware.ts
  suite-common/wallet-core/src/device/deviceActions.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/alerts/src/alertsAtoms.ts
  suite-native/alerts/src/components/AlertSheet.tsx
  suite-native/device/package.json
  suite-native/device/src/hooks/useConnectDevice.tsx
  suite-native/device/src/index.ts
  suite-native/device/src/middlewares/buttonRequestMiddleware.ts
  suite-native/device/src/middlewares/deviceMiddleware.ts
  suite-native/device/tsconfig.json
  suite-native/forms/src/Form.tsx
  suite-native/intl/src/en.ts
  suite-native/module-connect-device/package.json
  suite-native/module-connect-device/src/components/PinForm.tsx
  suite-native/module-connect-device/src/components/PinFormControlButtons.tsx
  suite-native/module-connect-device/src/components/PinFormProgress.tsx
  suite-native/module-connect-device/src/components/PinFromControlButtons.tsx
  suite-native/module-connect-device/src/screens/ConnectDeviceCrossroadsScreen.tsx
  suite-native/module-connect-device/tsconfig.json
  yarn.lock
Labels: mobile-app

#9615 chore(README): get back git lfs install as it is required for fresh git lfs installation
  README.md
Labels: documentation

#9621 chore(sentry): reduct device session_id because it is not useful
  docs/analytics/sentry.md
  packages/suite/src/utils/suite/__tests__/logsUtils.test.ts
  packages/suite/src/utils/suite/logsUtils.ts
Labels: sentry, low hanging fruit

#9542 feat(solana) hide transaction summary for solana
  packages/suite/src/actions/wallet/graphActions.ts
  packages/suite/src/views/wallet/transactions/Transactions.tsx
Labels: solana

#9541 feat(solana) subscribe to solana account
  packages/blockchain-link-types/src/common.ts
  packages/blockchain-link/src/workers/solana/index.ts
Labels: solana

#9588 test(e2e): add pin success; re-enable pin mismatch
  packages/suite-web/e2e/support/commands.ts
  packages/suite-web/e2e/support/utils/shortcuts.ts
  packages/suite-web/e2e/tests/settings/t1b1-device-settings.test.ts
  packages/suite/src/components/suite/PinInput/index.tsx
  packages/trezor-user-env-link/src/api.ts
Labels: e2e

#9540 Feat/discovery UI
  packages/theme/src/borders.ts
  suite-common/graph/src/hooks.ts
  suite-common/icons/assets/icons/infoLight.svg
  suite-common/icons/src/icons.ts
  suite-native/assets/package.json
  suite-native/assets/src/assetsSelectors.ts
  suite-native/assets/src/components/Assets.tsx
  suite-native/assets/src/components/DiscoveryAssetsLoader.tsx
  suite-native/assets/tsconfig.json
  suite-native/atoms/src/Button/TextButton.tsx
  suite-native/atoms/src/Skeleton/BoxSkeleton.tsx
  suite-native/atoms/src/Skeleton/ListItemSkeleton.tsx
  suite-native/atoms/src/index.ts
  suite-native/intl/src/en.ts
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-home/package.json
  suite-native/module-home/src/components/EmptyHomeScreenPlaceholder.tsx
  suite-native/module-home/src/components/PortfolioGraph.tsx
  suite-native/module-home/src/components/PortfolioGraphHeader.tsx
  suite-native/module-home/src/constants.ts
  suite-native/module-home/src/screens/HomeScreen.tsx
  suite-native/module-home/tsconfig.json
  yarn.lock
Labels: mobile-app, UI

#9650 Bump beta version to 23.11.0
  packages/suite/package.json
Labels: deployment

#8678 docs: update readme.md
  README.md
Labels: documentation

#9663 Feat/batched discovery
  suite-common/wallet-core/src/discovery/discoveryThunks.ts
  suite-native/accounts/src/index.ts
  suite-native/accounts/src/selectors.ts
  suite-native/discovery/package.json
  suite-native/discovery/src/discoveryMiddleware.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/discovery/src/types.ts
  suite-native/discovery/src/utils.ts
  suite-native/discovery/tsconfig.json
  suite-native/module-accounts-import/src/accountsImportThunks.ts
  yarn.lock
Labels: mobile-app

#9625 Feat/connect navigation
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/app/package.json
  suite-native/app/tsconfig.json
  suite-native/device/package.json
  suite-native/device/redux.d.ts
  suite-native/device/src/hooks/useConnectDevice.tsx
  suite-native/device/src/hooks/useDeviceConnect.tsx
  suite-native/device/src/index.ts
  suite-native/device/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-connect-device/src/screens/ConnectAndUnlockDeviceScreen.tsx
  suite-native/module-connect-device/src/screens/ConnectDeviceCrossroadsScreen.tsx
  yarn.lock
Labels: mobile-app

#9688 Replace forgotten Model R image
  packages/suite-data/files/images/png/trezor-t2b1-large.png
Labels: bug

#9651 feat(suite-native): New onboarding UI
  packages/theme/README.md
  packages/theme/designColors.json
  packages/theme/package.json
  packages/theme/scripts/generateColors.ts
  packages/theme/src/colors.ts
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  suite-native/atoms/package.json
  suite-native/atoms/src/StepsProgressBar.tsx
  suite-native/atoms/src/TrezorSuiteLiteHeader.tsx
  suite-native/atoms/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-onboarding/package.json
  suite-native/module-onboarding/src/assets/trezorT.png
  suite-native/module-onboarding/src/assets/trezorT@2x.png
  suite-native/module-onboarding/src/assets/trezorT@3x.png
  suite-native/module-onboarding/src/components/AnalyticsInfoRow.tsx
  suite-native/module-onboarding/src/components/OnboardingFooter.tsx
  suite-native/module-onboarding/src/components/OnboardingScreen.tsx
  suite-native/module-onboarding/src/components/OnboardingScreenHeader.tsx
  suite-native/module-onboarding/src/navigation/OnboardingStackNavigator.tsx
  suite-native/module-onboarding/src/screens/AnalyticsConsentScreen.tsx
  suite-native/module-onboarding/src/screens/ConnectTrezorScreen.tsx
  suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx
  suite-native/module-onboarding/src/screens/GetStartedScreen.tsx
  suite-native/module-onboarding/src/screens/TrackBalancesScreen.tsx
  suite-native/module-onboarding/src/screens/WelcomeScreen.tsx
  suite-native/module-onboarding/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile-app

#9655 chore(connect): add Solana docs and tests
  docs/packages/connect/methods/solanaGetAddress.md
  docs/packages/connect/methods/solanaGetPublicKey.md
  docs/packages/connect/methods/solanaSignTransaction.md
  packages/connect/e2e/__fixtures__/index.ts
  packages/connect/e2e/__fixtures__/solanaGetAddress.ts
  packages/connect/e2e/__fixtures__/solanaGetPublicKey.ts
  packages/connect/e2e/__fixtures__/solanaSignTransaction.ts
  packages/connect/src/api/solanaGetAddress.ts
  packages/connect/src/api/solanaGetPublicKey.ts
  packages/connect/src/api/solanaSignTransaction.ts
Labels: solana

#9690 feat(suite-native): BottomSheet has optional header content
  suite-native/atoms/src/Sheet/BottomSheet.tsx
  suite-native/atoms/src/Sheet/BottomSheetHeader.tsx
Labels: mobile-app

#9643 feat(components): update textarea
  packages/components/src/components/form/Input/Input.tsx
  packages/components/src/components/form/InputStyles.ts
  packages/components/src/components/form/Select/Select.tsx
  packages/components/src/components/form/Textarea/CharacterCount.tsx
  packages/components/src/components/form/Textarea/Textarea.stories.tsx
  packages/components/src/components/form/Textarea/Textarea.tsx
  packages/components/src/components/form/TopAddons.tsx
  packages/components/src/components/form/form.stories.tsx
  packages/components/tsconfig.json
  packages/suite/src/views/wallet/sign-verify/index.tsx
  packages/suite/tsconfig.json
Labels: components

#9673 Remove redundant success toasts from onboarding
  packages/suite/src/actions/backup/backupActions.ts
  packages/suite/src/actions/settings/deviceSettingsActions.ts
  packages/suite/src/views/onboarding/steps/Backup.tsx
  packages/suite/src/views/onboarding/steps/Pin.tsx
  packages/suite/src/views/onboarding/steps/SecurityCheck/DeviceAuthenticity.tsx
  suite-common/device-authenticity/src/deviceAuthenticityThunks.ts
Labels: onboarding

#9710 Chore/feature flag android
  suite-native/app/ios/Podfile.lock
  suite-native/feature-flags/package.json
  suite-native/feature-flags/src/useIsUsbDeviceConnectFeatureEnabled.tsx
  yarn.lock
Labels: mobile-app

#9629 feat(suite-native): header container
  suite-common/icons/assets/icons/chevronUpAndDown.svg
  suite-common/icons/assets/icons/questionMark.svg
  suite-common/icons/src/icons.ts
  suite-native/accounts/src/components/AccountsSearchForm.tsx
  suite-native/accounts/src/components/SearchableAccountsListScreenHeader.tsx
  suite-native/intl/src/en.ts
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/components/AccountImportHeader.tsx
  suite-native/module-accounts-import/src/components/AccountImportSubHeader.tsx
  suite-native/module-accounts-import/src/screens/AccountImportLoadingScreen.tsx
  suite-native/module-accounts-import/src/screens/AccountImportSummaryScreen.tsx
  suite-native/module-accounts-import/src/screens/ScanQRCodeModalScreen.tsx
  suite-native/module-accounts-import/src/screens/SelectNetworkScreen.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-accounts-import/tsconfig.json
  suite-native/module-accounts-management/package.json
  suite-native/module-accounts-management/src/components/AccountDetailScreenHeader.tsx
  suite-native/module-accounts-management/src/components/AddAccountsButton.tsx
  suite-native/module-accounts-management/src/components/TokenAccountDetailScreenHeader.tsx
  suite-native/module-accounts-management/src/components/TokenAccountDetailScreenSubHeader.tsx
  suite-native/module-accounts-management/src/screens/AccountDetailScreen.tsx
  suite-native/module-accounts-management/src/screens/AccountSettingsScreen.tsx
  suite-native/module-accounts-management/src/screens/AccountsScreen.tsx
  suite-native/module-accounts-management/tsconfig.json
  suite-native/module-connect-device/src/components/ConnectDeviceBackground.tsx
  suite-native/module-connect-device/src/components/ConnectDeviceScreenHeader.tsx
  suite-native/module-connect-device/src/components/ConnectingTrezorHelp.tsx
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/module-home/src/screens/HomeScreen.tsx
  suite-native/module-onboarding/src/components/OnboardingScreen.tsx
  suite-native/module-onboarding/src/screens/AnalyticsConsentScreen.tsx
  suite-native/module-onboarding/src/screens/WelcomeScreen.tsx
  suite-native/module-receive/package.json
  suite-native/module-receive/src/screens/ReceiveAccountsScreen.tsx
  suite-native/module-receive/src/screens/ReceiveScreen.tsx
  suite-native/module-receive/tsconfig.json
  suite-native/module-settings/package.json
  suite-native/module-settings/src/components/SupportCard.tsx
  suite-native/module-settings/src/screens/SettingsAboutUsScreen.tsx
  suite-native/module-settings/src/screens/SettingsCustomizationScreen.tsx
  suite-native/module-settings/src/screens/SettingsFAQScreen.tsx
  suite-native/module-settings/src/screens/SettingsLocalizationScreen.tsx
  suite-native/module-settings/src/screens/SettingsPrivacyAndSecurity.tsx
  suite-native/module-settings/tsconfig.json
  suite-native/navigation/src/components/GoBackIcon.tsx
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/src/components/ScreenContent.tsx
  suite-native/navigation/src/components/ScreenContentWrapper.tsx
  suite-native/navigation/src/components/ScreenHeader.tsx
  suite-native/navigation/src/components/ScreenHeaderWrapper.tsx
  suite-native/navigation/src/components/ScreenSubHeader.tsx
  suite-native/navigation/src/index.ts
  suite-native/receive/package.json
  suite-native/receive/src/screens/ReceiveModal.tsx
  suite-native/receive/tsconfig.json
  suite-native/transactions/src/screens/TransactionDetailScreen.tsx
  yarn.lock
Labels: mobile-app

#9693 feat(suite-native): discovery testnets
  suite-native/config/src/index.ts
  suite-native/config/src/supportedNetworks.ts
  suite-native/discovery/package.json
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/discovery/src/discoveryMiddleware.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/discovery/src/index.ts
  suite-native/discovery/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-accounts-import/src/components/AccountImportSummary.tsx
  suite-native/module-accounts-import/src/components/SelectableNetworkList.tsx
  suite-native/module-dev-utils/package.json
  suite-native/module-dev-utils/src/components/DevCheckBoxListItem.tsx
  suite-native/module-dev-utils/src/components/RenderingUtils.tsx
  suite-native/module-dev-utils/src/components/TestnetsToggle.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/module-dev-utils/tsconfig.json
  suite-native/state/src/extraDependencies.ts
  suite-native/state/src/reducers.ts
  yarn.lock
Labels: mobile-app

#9705 feat(suite-native): discovery account labels
  packages/suite/src/actions/wallet/coinjoinAccountActions.ts
  suite-common/wallet-core/src/accounts/accountsActions.ts
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/accounts/tests/accountsReducer.test.ts
  suite-common/wallet-core/src/discovery/discoveryThunks.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/module-accounts-import/src/accountsImportThunks.ts
Labels: mobile-app

#9728 chore(suite-native): remove translations for dev utils
  suite-native/intl/src/en.ts
  suite-native/module-dev-utils/src/components/TestnetsToggle.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
Labels: mobile-app

#9718 fix(suite): settings buttons
  packages/suite/src/components/suite/Settings/components/TextColumn.tsx
  packages/suite/src/views/settings/device/FirmwareTypeChange.tsx
  packages/suite/src/views/settings/device/FirmwareVersion.tsx
Labels: UI

#9739 chore(suite-native): updated version of reanimated and skia
  suite-common/icons/package.json
  suite-native/accounts/package.json
  suite-native/alerts/package.json
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  suite-native/atoms/package.json
  suite-native/atoms/src/Button/TextButton.tsx
  suite-native/graph/package.json
  suite-native/link/package.json
  suite-native/message-system/package.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-management/package.json
  suite-native/notifications/package.json
  suite-native/react-native-graph/package.json
  suite-native/test-utils/package.json
  suite-native/toasts/package.json
  suite-native/transactions/package.json
  yarn.lock
Labels: mobile-app

#9744 fix(suite-native): correct image height on onboarding
  suite-native/module-onboarding/src/screens/ConnectTrezorScreen.tsx
Labels: mobile-app

#9737 feat(suite-native): device supported networks discovery
  suite-native/config/src/supportedNetworks.ts
  suite-native/module-accounts-import/src/components/SelectableNetworkList.tsx
Labels: mobile-app

#9748 fix(theme): fix titleSmall line height
  packages/theme/src/typography.ts
Labels: UI

#9750 fix(theme): fix CI
  packages/components/src/components/typography/Link/Link.tsx
  packages/components/src/components/typography/Paragraph/Paragraph.tsx
  packages/suite-web/e2e/tests/suite/tooltip.test.ts
  packages/suite/src/components/guide/OpenGuideFromTooltip.tsx
  packages/suite/src/support/suite/styles/GlobalStyle.tsx
Labels: ci

#9574 fix(coinmarket): Add destination tag in sell overview
  packages/suite/package.json
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/sell/offers/Offers/SelectedOffer/components/SendTransaction.tsx
  yarn.lock
Labels: +Invity

#9681 feat(coinmarket): USDT20 to USDT rename backward compatibility
  packages/suite/src/utils/wallet/coinmarket/__tests__/buyUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/__tests__/coinmarketUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/buyUtils.ts
  packages/suite/src/utils/wallet/coinmarket/coinmarketUtils.ts
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/ReceiveCryptoSelect/index.tsx
Labels: +Invity

#9694 chore(suite-native): homescreen crossroads
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/device/deviceConstants.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-native/app/ios/Podfile.lock
  suite-native/app/src/initActions.ts
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/assets/src/assetsSelectors.ts
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/assets/src/components/Assets.tsx
  suite-native/assets/src/components/DiscoveryAssetsLoader.tsx
  suite-native/device/src/hooks/useDeviceConnect.tsx
  suite-native/intl/src/en.ts
  suite-native/module-accounts-import/src/accountsImportThunks.ts
  suite-native/module-accounts-import/src/components/AccountImportSubHeader.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-management/src/components/AccountSettingsRemoveCoinButton.tsx
  suite-native/module-connect-device/src/components/ConnectDeviceScreenHeader.tsx
  suite-native/module-connect-device/src/navigation/ConnectDeviceStackNavigator.tsx
  suite-native/module-connect-device/src/screens/ConnectDeviceCrossroadsScreen.tsx
  suite-native/module-home/package.json
  suite-native/module-home/src/assets/darkDashboard.png
  suite-native/module-home/src/assets/darkDashboard@2x.png
  suite-native/module-home/src/assets/darkDashboard@3x.png
  suite-native/module-home/src/assets/dashboard.png
  suite-native/module-home/src/assets/dashboard@2x.png
  suite-native/module-home/src/assets/dashboard@3x.png
  suite-native/module-home/src/components/EmptyConnectedDeviceState.tsx
  suite-native/module-home/src/components/EmptyHomeRenderer.tsx
  suite-native/module-home/src/components/EmptyHomeScreenPlaceholder.tsx
  suite-native/module-home/src/components/EmptyPortfolioCrossroads.tsx
  suite-native/module-home/src/components/EmptyPortfolioTrackerState.tsx
  suite-native/module-home/src/components/PortfolioContent.tsx
  suite-native/module-home/src/components/PortfolioGraph.tsx
  suite-native/module-home/src/components/SettingsButtonLink.tsx
  suite-native/module-home/src/screens/HomeScreen.tsx
  suite-native/module-home/tsconfig.json
  suite-native/module-onboarding/package.json
  suite-native/module-onboarding/src/screens/AnalyticsConsentScreen.tsx
  suite-native/module-settings/src/screens/SettingsScreen.tsx
  suite-native/navigation/package.json
  suite-native/navigation/src/components/ScreenContentWrapper.tsx
  suite-native/navigation/src/components/ScreenHeader.tsx
  suite-native/navigation/src/components/ScreenHeaderWrapper.tsx
  suite-native/navigation/src/components/TabBar.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/navigation/tsconfig.json
  yarn.lock
Labels: mobile-app

#9779 ref(suite-native): remove unused unwrap
  suite-native/app/src/initActions.ts
Labels: mobile-app

#9784 chore(suite-native): fix account key undefined
  suite-common/wallet-core/src/device/deviceConstants.ts
Labels: mobile-app

#9769 test(e2e): suite: make recovery test work
  packages/suite-web/e2e/tests/onboarding/analytics-consent.test.ts
  packages/suite-web/e2e/tests/onboarding/t2t1-create-wallet.test.ts
  packages/suite-web/e2e/tests/onboarding/t2t1-recovery-fail.test.ts
  packages/suite-web/e2e/tests/onboarding/t2t1-recovery-success.test.ts
Labels: e2e

#9722 feat(coinmarket): Trade box
  packages/components/src/components/assets/Icon/icons.ts
  packages/components/src/images/icons/trend_down.svg
  packages/components/src/images/icons/trend_up.svg
  packages/suite-analytics/src/constants.ts
  packages/suite-analytics/src/types/events.ts
  packages/suite/src/components/suite/OverflowItems.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/transactions/TradeBox/TradeBox.tsx
  packages/suite/src/views/wallet/transactions/TradeBox/TradeBoxMenu.tsx
  packages/suite/src/views/wallet/transactions/TradeBox/TradeBoxPrices.tsx
  packages/suite/src/views/wallet/transactions/Transactions.tsx
Labels: +Invity
