Repository trezor/trezor-suite, pull requests merged in 2023-03, with the labels that each got.

#7741 Explicitly set proxyAgent protocol in `request-manager` because of Sentry
  packages/request-manager/src/interceptor.ts
Labels: release, coinjoin

#7749 fix(suite-native): separate id of unecrypted storage
  suite-native/storage/src/atomWithUnecryptedStorage.ts
  suite-native/storage/src/storage.ts
Labels: bug, mobile

#7744 fix(suite): fix coinjoin fiat balance formatting
  packages/suite/src/components/suite/FiatValue.tsx
  packages/suite/src/components/suite/FormattedCryptoAmount.tsx
  packages/suite/src/components/wallet/PrivacyAccount/CryptoAmountWithHeader.tsx
Labels: release, coinjoin

#7750 Prevent coinjoin session from automaticcally restoring on Suite start
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/utils/suite/storage.ts
Labels: coinjoin

#7751 Strip temporary session properties when it is saved
  packages/suite/src/utils/suite/storage.ts
Labels: coinjoin

#7676 feat(suite-native): Display ETH tokens
  suite-common/formatters/src/formatters/prepareCryptoAmountFormatter.ts
  suite-common/wallet-config/src/index.ts
  suite-common/wallet-config/src/types.ts
  suite-common/wallet-core/src/blockchain/blockchainThunks.ts
  suite-common/wallet-utils/src/accountUtils.ts
  suite-native/atoms/src/Divider.tsx
  suite-native/ethereum-tokens/package.json
  suite-native/ethereum-tokens/src/index.ts
  suite-native/ethereum-tokens/src/types.ts
  suite-native/ethereum-tokens/tsconfig.json
  suite-native/formatters/package.json
  suite-native/formatters/src/components/AmountText.tsx
  suite-native/formatters/src/components/CryptoAmountFormatter.tsx
  suite-native/formatters/src/components/CryptoToFiatAmountFormatter.tsx
  suite-native/formatters/src/components/EmptyAmountText.tsx
  suite-native/formatters/src/components/EthereumTokenAmountFormatter.tsx
  suite-native/formatters/src/components/EthereumTokenSymbolFormatter.tsx
  suite-native/formatters/src/components/FiatAmountFormatter.tsx
  suite-native/formatters/src/components/TokenToFiatAmountFormatter.tsx
  suite-native/formatters/src/index.ts
  suite-native/formatters/tsconfig.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/components/AccountImportEthereumTokens.tsx
  suite-native/module-accounts-import/src/components/AccountImportOverview.tsx
  suite-native/module-accounts-import/src/components/AccountImportOverviewCard.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummary.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-import/src/components/DevXpub.tsx
  suite-native/module-accounts-import/src/components/EthereumTokenInfo.tsx
  suite-native/module-accounts-import/src/screens/AccountImportLoadingScreen.tsx
  suite-native/module-accounts-import/tsconfig.json
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailParametersSheet.tsx
  yarn.lock
Labels: mobile-app

#7752 fix(suite-native): info plist mic update
  suite-native/app/ios/TrezorSuite/Info.plist
Labels: mobile-app

#7756 fix(suite-native): app version
  suite-native/app/package.json
Labels: mobile-app

#7754 chore(mobile): faster date + time formatting
  packages/connect-ui/src/index.tsx
  packages/suite-desktop/src/modules/bridge.ts
  packages/suite/src/hooks/suite/useFormattersConfig.ts
  suite-common/formatters/package.json
  suite-common/formatters/src/formatters/prepareDateFormatter.ts
  suite-common/formatters/src/formatters/prepareMonthNameFormatter.ts
  suite-common/formatters/src/formatters/prepareTimeFormatter.ts
  suite-common/formatters/src/tests/MockedFormatterProvider.tsx
  suite-common/formatters/src/types.ts
  suite-native/app/android/app/build.gradle
  suite-native/app/ios/Podfile.lock
  suite-native/app/src/hooks/useFormattersConfig.ts
  yarn.lock
Labels: mobile-app

#7747 update suite guide version
  packages/suite-data/src/guide/constants.ts
Labels: release, guide

#7761 chore(mobile): refactor Stack component
  suite-native/app/ios/Podfile.lock
  suite-native/atoms/src/Box.tsx
  suite-native/atoms/src/HStack.tsx
  suite-native/atoms/src/Stack.tsx
  suite-native/atoms/src/VStack.tsx
  suite-native/atoms/src/index.ts
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/module-settings/src/components/ColorSchemePicker.tsx
Labels: mobile-app

#7763 chore(mobile): add logs for fiat rates actions
  suite-common/logger/src/logsMiddleware.ts
Labels: mobile-app

#7753 fix(suite-native): screen top inset
  suite-native/navigation/src/components/Screen.tsx
Labels: mobile-app

#7760 fix(coinjoin): Status exceptions and request timeout
  packages/coinjoin/src/client/CoinjoinClient.ts
  packages/coinjoin/src/client/Status.ts
  packages/coinjoin/src/types/client.ts
  packages/coinjoin/src/utils/roundUtils.ts
  packages/coinjoin/tests/client/Status.test.ts
Labels: release

#7759 Crowdin translations update
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/el.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: release, translations

#7745 feat(suite-native): about us screen
  packages/icons/assets/icons/facebook.svg
  packages/icons/assets/icons/github.svg
  packages/icons/assets/icons/pdf.svg
  packages/icons/assets/icons/trezor.svg
  packages/icons/assets/icons/twitter.svg
  packages/icons/src/icons.ts
  suite-native/atoms/src/Link.tsx
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-settings/package.json
  suite-native/module-settings/src/components/AboutUsBanners.tsx
  suite-native/module-settings/src/components/SupportSettings.tsx
  suite-native/module-settings/src/navigation/SettingsStackNavigator.tsx
  suite-native/module-settings/src/screens/SettingsAboutUsScreen.tsx
  suite-native/module-settings/src/screens/SettingsScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile-app

#7787 feat(suite-native): toast notification component
  packages/icons/assets/icons/info.svg
  packages/icons/assets/icons/warningTriangle.svg
  packages/icons/src/icons.ts
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/notifications/package.json
  suite-native/notifications/src/components/ToastNotification.tsx
  suite-native/notifications/src/index.ts
  suite-native/notifications/tsconfig.json
  yarn.lock
Labels: notifications, mobile-app

#7559 Ignore ChromeRuntime port events if port is not created by current popup
  packages/connect-web/src/popup/index.ts
Labels: connect

#7793 chore(mobile): upgrade reanimated
  packages/icons/package.json
  suite-native/app/android/app/src/main/java/io/trezor/suite/MainApplication.java
  suite-native/app/ios/.xcode.env
  suite-native/app/ios/Podfile.lock
  suite-native/app/ios/TrezorSuite/AppDelegate.mm
  suite-native/app/metro.config.js
  suite-native/app/package.json
  suite-native/atoms/package.json
  suite-native/graph/package.json
  suite-native/module-accounts-import/package.json
  suite-native/notifications/package.json
  suite-native/react-native-graph/package.json
  suite-native/test-utils/package.json
  suite-native/transactions/package.json
  yarn.lock
Labels: mobile-app

#7784 Add z-index to DayHeader
  packages/components/src/config/variables.ts
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/DayHeader/index.tsx
  packages/suite/src/views/wallet/transactions/components/TransactionList/components/TransactionsGroup/index.tsx
Labels: bug, transactions

#7791 feat(message-system,coinjoin): hide coinjoin by debug menu
  packages/message-system/src/config/config.v1.json
Labels: release, coinjoin, message-system

#7796 chore(mobile): separate some steps in CI for better debug
  .github/workflows/suite-native_develop_ci.yml
Labels: mobile-app

#7778 fix(suite-native): customizable qrcode background elevation
  suite-native/atoms/src/Button/Button.tsx
  suite-native/module-send-receive/src/components/ReceiveAddress.tsx
  suite-native/module-send-receive/src/screens/ReceiveModalScreen.tsx
  suite-native/qr-code/src/components/QRCode.tsx
Labels: bug, mobile-app

#7797 fix(suite-native): color scheme text color
  suite-native/module-settings/src/components/AboutUsBanners.tsx
Labels: mobile-app

#7795 feat(suite-native): alert sheet notification
  suite-native/atoms/src/Sheet/AlertSheet.tsx
  suite-native/atoms/src/Sheet/useBottomSheetAnimation.ts
  suite-native/atoms/src/Sheet/useShakeAnimation.ts
  suite-native/atoms/src/index.ts
Labels: mobile-app

#7818 chore(mobile): fix graph date format
  suite-native/graph/src/components/GraphDateFormatter.tsx
Labels: mobile-app

#7757 feat(suite-native):tokens as account
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/accounts/src/components/AccountListItemInteractive.tsx
  suite-native/accounts/src/components/TokenList.tsx
  suite-native/accounts/src/components/TokenListItem.tsx
  suite-native/accounts/tsconfig.json
  suite-native/ethereum-tokens/package.json
  suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts
  suite-native/ethereum-tokens/src/index.ts
  suite-native/ethereum-tokens/src/types.ts
  suite-native/ethereum-tokens/src/utils.ts
  suite-native/ethereum-tokens/tsconfig.json
  suite-native/module-accounts-import/src/components/AccountImportEthereumTokens.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  yarn.lock
Labels: mobile-app

#7822 feat(suite-native): update gems
  suite-native/app/.ruby-version
  suite-native/app/Gemfile.lock
Labels: mobile-app

#7825 feat(suite-native): update actions ruby version
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
  .github/workflows/suite-native_staging_ci.yml
Labels: mobile-app

#7826 fix(suite-native): working directory ruby
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
  .github/workflows/suite-native_staging_ci.yml
Labels: mobile-app

#7772 Feat/notification logic
  suite-common/toast-notifications/package.json
  suite-common/toast-notifications/src/notificationsActions.ts
  suite-common/toast-notifications/src/notificationsSelectors.ts
  suite-common/toast-notifications/src/types.ts
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  suite-native/app/src/navigation/AppTabNavigator.tsx
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/app/src/navigation/routes.ts
  suite-native/app/tsconfig.json
  suite-native/assets/src/components/Assets.tsx
  suite-native/module-accounts/src/components/TransactionListHeader.tsx
  suite-native/module-dev-utils/src/fixtures.ts
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-send-receive/package.json
  suite-native/module-send-receive/src/index.ts
  suite-native/module-send-receive/src/navigation/SendReceiveStackNavigator.tsx
  suite-native/module-send-receive/src/screens/ReceiveAccountsScreen.tsx
  suite-native/module-send-receive/src/screens/ReceiveScreen.tsx
  suite-native/module-send-receive/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/notifications/package.json
  suite-native/notifications/src/components/Notification.tsx
  suite-native/notifications/src/components/NotificationRenderer.tsx
  suite-native/notifications/src/components/TransactionNotification.tsx
  suite-native/notifications/src/components/TransactionNotificationDescription.tsx
  suite-native/notifications/src/index.ts
  suite-native/notifications/tsconfig.json
  suite-native/state/package.json
  suite-native/state/src/reducers.ts
  suite-native/state/tsconfig.json
  suite-native/transactions/src/components/TransactionsEmptyState.tsx
  yarn.lock
Labels: mobile-app

#7829 Chore/devkit fw remove downgrade binaries
  packages/connect-common/files/devkit/firmware/1/fw_downgrade_bld_to_1.3.2_im.bin
  packages/connect-common/files/devkit/firmware/1/fw_downgrade_bld_to_1.3.3_im.bin
  packages/connect-common/files/devkit/firmware/1/fw_downgrade_bld_v3_to_1.3.2_im.bin
Labels: release

#7836 fix(suite-native): update ruby version
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
  .github/workflows/suite-native_staging_ci.yml
Labels: mobile-app

#7831 chore(mobile): better dev xpubs
  suite-native/graph/src/components/GraphDateFormatter.tsx
  suite-native/module-accounts-import/src/components/DevXpub.tsx
Labels: mobile-app

#7848 feat(suite-native): upgrade RN, assemble android
  package.json
  packages/env-utils/package.json
  packages/icons/package.json
  packages/styles/package.json
  packages/transport-native/package.json
  suite-native/accounts/package.json
  suite-native/app/android/fastlane/Fastfile
  suite-native/app/babel.config.js
  suite-native/app/package.json
  suite-native/assets/package.json
  suite-native/atoms/package.json
  suite-native/graph/package.json
  suite-native/helpers/package.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts/package.json
  suite-native/module-dev-utils/package.json
  suite-native/module-home/package.json
  suite-native/module-send-receive/package.json
  suite-native/module-settings/package.json
  suite-native/navigation/package.json
  suite-native/notifications/package.json
  suite-native/qr-code/package.json
  suite-native/react-native-graph/package.json
  suite-native/storage/package.json
  suite-native/theme/package.json
  suite-native/transactions/package.json
  suite-native/video-assets/package.json
  yarn.lock
Labels: mobile-app

#7854 Revert "chore(wallet-utils): move cardanoUtils to suite-common"
  packages/suite/src/actions/wallet/coinmarket/coinmarketCommonActions.ts
  packages/suite/src/actions/wallet/discoveryActions.ts
  packages/suite/src/actions/wallet/receiveActions.ts
  packages/suite/src/actions/wallet/send/sendFormCardanoActions.ts
  packages/suite/src/actions/wallet/sendFormActions.ts
  packages/suite/src/components/suite/modals/ReviewTransaction/index.tsx
  packages/suite/src/hooks/wallet/useCardanoStaking.ts
  packages/suite/src/utils/wallet/__fixtures__/cardanoUtils.ts
  packages/suite/src/utils/wallet/__tests__/cardanoUtils.test.ts
  packages/suite/src/utils/wallet/cardanoUtils.ts
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/TokenSelect.tsx
  suite-common/wallet-core/src/transactions/transactionsThunks.ts
  suite-common/wallet-utils/jest.config.js
  suite-common/wallet-utils/npmMocks.tsx
  suite-common/wallet-utils/package.json
  suite-common/wallet-utils/src/index.ts
  yarn.lock
Labels: mobile-app

#7832 feat(suite): add an autopause button to the critical phase modal
  packages/components/src/images/icons/cross.svg
  packages/suite/src/actions/wallet/coinjoinAccountActions.ts
  packages/suite/src/actions/wallet/coinjoinClientActions.ts
  packages/suite/src/actions/wallet/constants/coinjoinConstants.ts
  packages/suite/src/components/suite/modals/CriticalCoinjoinPhase/AutoPauseButton.tsx
  packages/suite/src/components/suite/modals/CriticalCoinjoinPhase/index.tsx
  packages/suite/src/components/wallet/CoinjoinSummary/CoinjoinStatusWheel/index.tsx
  packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts
  packages/suite/src/reducers/wallet/coinjoinReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/wallet/coinjoin.ts
  packages/suite/src/utils/suite/storage.ts
Labels: coinjoin

#7833 fix(suite-native): Tokens issues
  suite-native/accounts/src/components/TokenListItem.tsx
  suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/components/AccountImportEthereumTokens.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-import/tsconfig.json
  yarn.lock
Labels: mobile-app

#7874 fix(suite-native): remove comment
  suite-native/app/android/app/src/release/io/trezor/suite/ReactNativeFlipper.java
Labels: mobile-app

#7875 refactor(suite-native): directory matches flavor
  suite-native/app/android/app/src/prod/io/trezor/suite/ReactNativeFlipper.java
Labels: mobile-app

#7885 fix(suite-native): prodRelease dir
  suite-native/app/android/app/src/prod/io/trezor/suite/ReactNativeFlipper.java
  suite-native/app/android/app/src/prodRelease/io/trezor/suite/ReactNativeFlipper.java
  suite-native/app/android/app/src/releaseProd/io/trezor/suite/ReactNativeFlipper.java
  suite-native/app/android/fastlane/Fastfile
Labels: mobile-app

#7892 fix(suite-native): path to production keys
  .github/workflows/suite-native_production_ci.yml
Labels: mobile-app

#7896 fix(suite-native): google play json file
  .github/workflows/suite-native_production_ci.yml
Labels: mobile-app

#7898 feat(suite-native): faq content
  suite-native/module-settings/src/components/FAQInfoPanel.tsx
Labels: mobile-app

#7895 fix(suite-native): scrollbar glitch
  suite-native/navigation/src/components/ScreenContent.tsx
Labels: bug, mobile-app

#7899 feat(suite-native): acordion fade in animation
  suite-native/atoms/src/AccordionItem.tsx
Labels: mobile-app

#7890 fix(suite-native): graph-axis-label-visible
  suite-native/graph/src/components/AxisLabel.tsx
Labels: bug, mobile-app

#7894 fix(suite-native): transaction notifications disabled
  suite-native/app/src/App.tsx
Labels: notifications, mobile-app

#7909 feat(suite-native): app text content polished
  suite-common/wallet-config/src/networksConfig.ts
  suite-native/app/src/navigation/routes.ts
  suite-native/assets/src/components/Assets.tsx
  suite-native/atoms/src/Input/InputWrapper.tsx
  suite-native/module-accounts-import/src/components/AccountImportHeader.tsx
  suite-native/module-accounts-import/src/components/AccountImportOverview.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-import/src/components/SelectableNetworkList.tsx
  suite-native/module-accounts-import/src/components/XpubHint.tsx
  suite-native/module-accounts-import/src/components/XpubImportSection.tsx
  suite-native/module-accounts-import/src/screens/ScanQRCodeModalScreen.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-accounts/src/components/AccountRenameButton.tsx
  suite-native/module-accounts/src/components/AccountsScreenHeader.tsx
  suite-native/module-accounts/src/screens/AccountSettingsScreen.tsx
  suite-native/module-home/src/components/DashboardHeader.tsx
  suite-native/module-home/src/components/PortfolioGraphHeader.tsx
  suite-native/module-send-receive/package.json
  suite-native/module-send-receive/src/components/ReceiveAddress.tsx
  suite-native/module-send-receive/src/components/ReceiveTextHint.tsx
  suite-native/module-send-receive/src/screens/ReceiveScreen.tsx
  suite-native/module-send-receive/tsconfig.json
  suite-native/module-settings/src/components/SupportSettings.tsx
  suite-native/module-settings/src/screens/SettingsAboutUsScreen.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx
  yarn.lock
Labels: mobile-app

#7883 feat(suite-native): Settings
  packages/icons/assets/icons/database.svg
  packages/icons/assets/icons/detective.svg
  packages/icons/src/icons.ts
  suite-native/app/src/hooks/useFormattersConfig.ts
  suite-native/atoms/src/DiscreetText.tsx
  suite-native/atoms/src/Select/SelectItem.tsx
  suite-native/atoms/src/Select/SelectTrigger.tsx
  suite-native/module-home/src/components/DashboardHeader.tsx
  suite-native/module-settings/package.json
  suite-native/module-settings/src/components/ApplicationSettings.tsx
  suite-native/module-settings/src/components/CryptoUnitsSelector.tsx
  suite-native/module-settings/src/components/TouchableSwitchRow.tsx
  suite-native/module-settings/src/navigation/SettingsStackNavigator.tsx
  suite-native/module-settings/src/screens/SettingsAnalyticsScreen.tsx
  suite-native/module-settings/src/screens/SettingsCustomizationScreen.tsx
  suite-native/module-settings/src/screens/SettingsLocalisationScreen.tsx
  suite-native/module-settings/src/screens/SettingsPrivacyAndSecurity.tsx
  suite-native/module-settings/src/slice.ts
  suite-native/module-settings/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile-app

#7837 feat(suite-native): custom alert logic
  suite-native/alerts/package.json
  suite-native/alerts/src/alertsAtoms.ts
  suite-native/alerts/src/components/AlertRenderer.tsx
  suite-native/alerts/src/components/AlertSheet.tsx
  suite-native/alerts/src/index.ts
  suite-native/alerts/src/useAlert.ts
  suite-native/alerts/src/useShakeAnimation.ts
  suite-native/alerts/tsconfig.json
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  suite-native/app/tsconfig.json
  suite-native/atoms/src/Sheet/useBottomSheetAnimation.ts
  suite-native/atoms/src/index.ts
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/screens/AccountImportLoadingScreen.tsx
  suite-native/module-accounts-import/tsconfig.json
  yarn.lock
Labels: notifications, mobile-app

#7938 fix(suite-native): github workflow lane
  .github/workflows/suite-native_production_ci.yml
Labels: mobile-app

#7824 fix: gemfile for dependabot
  suite-native/app/Gemfile
Labels: mobile-app

#7942 fix(suite-native): remove precheck
  suite-native/app/ios/fastlane/Fastfile
Labels: mobile-app

#7947 fix(suite-native): copy bug
  suite-native/module-settings/src/components/AboutUsBanners.tsx
Labels: mobile-app
