Repository trezor/trezor-suite, pull requests merged in 2023-07, with the labels that each got.

#8854 fix(coinjoin): get InputBanned time from ExceptionData
  packages/coinjoin/src/client/coordinatorRequest.ts
  packages/coinjoin/src/client/round/inputRegistration.ts
Labels: coinjoin

#8828 chore(dependencies): exclude protestware file from build output
  packages/suite-desktop/electron-builder-config.js
Labels: low hanging fruit

#8846 Add buy button to dashboard grid and table asset view
  packages/suite-web/e2e/tests/dashboard/dashboard.test.ts
  packages/suite/src/components/wallet/CoinmarketBuyButton.tsx
  packages/suite/src/components/wallet/index.tsx
  packages/suite/src/views/dashboard/components/AssetsCard/components/AssetGrid.tsx
  packages/suite/src/views/dashboard/components/AssetsCard/components/AssetTable.tsx
  packages/suite/src/views/dashboard/components/AssetsCard/index.tsx
Labels: +Invity

#8855 fix(coinjoin): do not ban inputs locally after unsuccessful round
  packages/coinjoin/src/client/round/endedRound.ts
  packages/coinjoin/tests/client/endedRound.test.ts
Labels: coinjoin

#8856 fix(coinjoin): add random delays to outputRegistration phase
  packages/coinjoin/src/client/round/outputDecomposition.ts
  packages/coinjoin/src/client/round/outputRegistration.ts
  packages/coinjoin/src/client/round/transactionSigning.ts
  packages/coinjoin/src/utils/roundUtils.ts
  packages/coinjoin/tests/client/outputRegistration.test.ts
  packages/coinjoin/tests/utils/roundUtils.test.ts
Labels: coinjoin

#8859 Bump beta version to 23.8.0
  packages/suite/package.json
Labels: deployment

#8868 fix(suite): fix images paths
  packages/suite/src/components/guide/SupportFeedbackSelection.tsx
Labels: release, low hanging fruit

#8616 chore(suite-native): discovery redux logic refactor
  packages/suite/src/actions/suite/__fixtures__/suiteActions.ts
  packages/suite/src/actions/suite/__tests__/storageActions.test.ts
  packages/suite/src/actions/wallet/__fixtures__/discoveryActions.ts
  packages/suite/src/actions/wallet/__tests__/discoveryActions.test.ts
  packages/suite/src/actions/wallet/constants/discoveryConstants.ts
  packages/suite/src/actions/wallet/constants/index.ts
  packages/suite/src/actions/wallet/discoveryActions.ts
  packages/suite/src/actions/wallet/selectedAccountActions.ts
  packages/suite/src/components/suite/AddAccountButton/index.tsx
  packages/suite/src/components/suite/SwitchDevice/components/WalletInstance.tsx
  packages/suite/src/hooks/suite/__fixtures__/useDiscovery.ts
  packages/suite/src/hooks/suite/__tests__/useDiscovery.test.tsx
  packages/suite/src/hooks/suite/useDiscovery.ts
  packages/suite/src/middlewares/suite/analyticsMiddleware.ts
  packages/suite/src/middlewares/suite/logsMiddleware.ts
  packages/suite/src/middlewares/suite/sentryMiddleware.ts
  packages/suite/src/middlewares/wallet/coinjoinMiddleware.ts
  packages/suite/src/middlewares/wallet/discoveryMiddleware.ts
  packages/suite/src/middlewares/wallet/graphMiddleware.ts
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/reducers/suite/metadataReducer.ts
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/reducers/wallet/discoveryReducer.ts
  packages/suite/src/reducers/wallet/index.ts
  packages/suite/src/support/extraDependencies.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/types/wallet/index.ts
  packages/suite/src/utils/suite/__tests__/logsUtils.test.ts
  packages/suite/src/utils/suite/logsUtils.ts
  packages/suite/src/views/dashboard/components/PortfolioCard/components/Exception.tsx
  suite-common/redux-utils/src/extraDependenciesType.ts
  suite-common/test-utils/src/extraDependenciesMock.ts
  suite-common/wallet-constants/src/discovery.ts
  suite-common/wallet-types/src/discovery.ts
Labels: code, mobile-app, monorepo

#8857 Feat/graph interactions
  suite-common/formatters/src/utils/sign.ts
  suite-common/graph/src/graphBalanceEvents.ts
  suite-common/graph/src/graphDataFetching.ts
  suite-common/graph/src/graphUtils.ts
  suite-common/graph/src/hooks.ts
  suite-common/graph/src/tests/graphBalanceEvents.test.ts
  suite-common/graph/src/tests/graphUtils.test.ts
  suite-common/graph/src/types.ts
  suite-common/suite-types/src/sign.ts
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  suite-native/formatters/package.json
  suite-native/formatters/src/components/CryptoAmountFormatter.tsx
  suite-native/formatters/src/components/SignValueFormatter.tsx
  suite-native/graph/package.json
  suite-native/graph/src/components/Graph.tsx
  suite-native/graph/src/components/GraphContextProvider.tsx
  suite-native/graph/src/components/GraphDateFormatter.tsx
  suite-native/graph/src/components/TransactionEvent.tsx
  suite-native/graph/src/components/TransactionEventTooltip.tsx
  suite-native/graph/src/hooks.ts
  suite-native/graph/src/tests/utils.test.ts
  suite-native/graph/src/utils.ts
  suite-native/graph/tsconfig.json
  suite-native/module-accounts/package.json
  suite-native/module-accounts/src/components/AccountDetailGraph.tsx
  suite-native/module-accounts/src/components/AccountDetailGraphHeader.tsx
  suite-native/module-accounts/tsconfig.json
  suite-native/module-home/package.json
  suite-native/module-home/src/components/PortfolioGraph.tsx
  suite-native/module-home/src/components/PortfolioGraphHeader.tsx
  suite-native/module-home/tsconfig.json
  suite-native/react-native-graph/package.json
  suite-native/react-native-graph/src/AnimatedLineGraph.tsx
  suite-native/react-native-graph/src/CreateGraphPath.ts
  suite-native/react-native-graph/src/DefaultGraphEvent.tsx
  suite-native/react-native-graph/src/LineGraph.tsx
  suite-native/react-native-graph/src/LineGraphProps.ts
  suite-native/react-native-graph/src/StaticLineGraph.tsx
  suite-native/react-native-graph/src/hooks/useEventTooltipProps.ts
  suite-native/react-native-graph/src/index.ts
  yarn.lock
Labels: mobile-app

#8911 chore(suite-native): remove unused file
  suite-native/module-home/src/components/DashboardHeaderDeviceChip.tsx
Labels: mobile-app

#8912 fix(suite-native): downgrade proxy-memoize
  suite-common/toast-notifications/package.json
  suite-common/wallet-core/package.json
  suite-native/assets/package.json
  suite-native/ethereum-tokens/package.json
  suite-native/fiat-rates/package.json
  suite-native/transactions/package.json
  yarn.lock
Labels: package, mobile-app, monorepo

#8893 feat(suite-native): alert upon importing address
  suite-native/app/ios/Podfile.lock
  suite-native/atoms/src/Pictogram.tsx
  suite-native/module-accounts-import/src/components/XpubHint.tsx
  suite-native/module-accounts-import/src/components/XpubHintBottomSheet.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
Labels: mobile-app

#8932 chore(suite-native): use validation for non-eth network types
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
Labels: mobile-app

#8906 fix(coinjoin): end round in any input-registration fails
  packages/coinjoin/src/client/CoinjoinRound.ts
  packages/coinjoin/tests/client/CoinjoinRound.test.ts
Labels: coinjoin

#8949 chore(suite): remove CoinjoinAccount.previousSessions
  packages/suite/src/actions/wallet/__fixtures__/coinjoinClientActions.ts
  packages/suite/src/actions/wallet/__tests__/coinjoinClientActions.test.ts
  packages/suite/src/reducers/wallet/__fixtures__/coinjoinReducer.ts
  packages/suite/src/reducers/wallet/coinjoinReducer.ts
  packages/suite/src/storage/migrations/index.ts
  packages/suite/src/types/wallet/coinjoin.ts
Labels: coinjoin

#8917 Restrict Select menu to use portal in modals only
  packages/components/src/components/Modal/index.tsx
  packages/components/src/components/form/Select/index.tsx
Labels: bug, components

#8967 chore(suite): remove translation keys that are no longer used
  docs/packages/suite/send.md
  packages/suite/src/support/messages.ts
Labels: low hanging fruit, translations

#8970 fix(suite-native): receive text copy
  suite-native/receive/src/components/ReceiveTextHint.tsx
Labels: mobile-app

#8977 fix(components): prevent closing select menu when scrolling through o…
  packages/components/src/components/form/Select/index.tsx
Labels: components

#8968 fix(suite-native): long amounts formatting
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/atoms/src/Table.tsx
  suite-native/formatters/src/components/CryptoAmountFormatter.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailInputsSheetSection.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailValuesSheet.tsx
Labels: mobile-app

#8969 fix(suite-native): graph refetches values after currency change
  suite-common/graph/src/graphDataFetching.ts
  suite-native/atoms/src/Select/SelectTrigger.tsx
Labels: mobile-app

#8902 feat(suite-native): change addresses displayed
  suite-common/icons/assets/icons/change.svg
  suite-common/icons/generateIcons.js
  suite-common/icons/src/components/CryptoIcon.tsx
  suite-common/icons/src/icons.ts
  suite-common/icons/src/index.ts
  suite-common/icons/src/tokenIcons.ts
  suite-native/transactions/src/components/TransactionDetail/ChangeAddressesHeader.tsx
  suite-native/transactions/src/components/TransactionDetail/TokenTransactionDetailSummary.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailAddressesSection.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailAddressesSheet.tsx
  suite-native/transactions/src/selectors.ts
  suite-native/transactions/src/tests/fixtures/transactions.ts
  suite-native/transactions/src/tests/utils.test.ts
  suite-native/transactions/src/types.ts
  suite-native/transactions/src/utils.ts
Labels: mobile-app

#8938 chore: update the import order linter config
  .eslintrc.js
Labels: code

#8989 feat(suite-native): internal transfer only transactions
  suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts
Labels: mobile-app

#8987 fix(suite): remove imprisoned utxos from the set of ExcludedUtxos
  packages/suite/src/actions/wallet/send/sendFormBitcoinActions.ts
  packages/suite/src/hooks/wallet/form/useExcludedUtxos.ts
  packages/suite/src/hooks/wallet/useSendForm.ts
  packages/suite/src/hooks/wallet/useSendFormCompose.ts
  suite-common/wallet-types/src/sendForm.ts
  suite-common/wallet-utils/src/sendFormUtils.ts
Labels: coinjoin

#8996 chore(suite-native): update fastlane
  suite-native/app/Gemfile.lock
Labels: ci, mobile-app

#9016 fix(suite): fix tx summary details button color
  packages/suite/src/components/suite/modals/ReviewTransaction/components/Summary.tsx
Labels: UI

#8983 fix(suite-native): axil label overflow
  suite-native/graph/src/components/AxisLabel.tsx
Labels: mobile-app

#8988 fix(suite-native): include tokens transactions list
  suite-native/transactions/src/components/TransactionsList/TransactionList.tsx
Labels: mobile-app

#8950 fix(suite-native): event tooltip zero sum values
  suite-native/formatters/src/components/CryptoAmountFormatter.tsx
  suite-native/graph/src/components/TransactionEventTooltip.tsx
Labels: mobile-app

#8930 fix(suite): app crash on decimal gwei on new TT fw
  packages/suite/src/components/suite/modals/ReviewTransaction/constructOutputs.ts
Labels: ethereum

#8864 Chore/firmware redux toolkit
  packages/suite/src/actions/firmware/__fixtures__/firmwareActions.ts
  packages/suite/src/actions/firmware/__tests__/firmwareActions.test.ts
  packages/suite/src/actions/firmware/constants/firmware.ts
  packages/suite/src/actions/firmware/constants/index.ts
  packages/suite/src/actions/firmware/firmwareActions.ts
  packages/suite/src/actions/firmware/firmwareThunks.ts
  packages/suite/src/actions/suite/__tests__/suiteActions.test.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/components/firmware/CheckSeed.tsx
  packages/suite/src/hooks/suite/useFirmware.ts
  packages/suite/src/middlewares/firmware/firmwareMiddleware.ts
  packages/suite/src/middlewares/suite/__tests__/buttonRequestMiddleware.test.ts
  packages/suite/src/middlewares/suite/__tests__/firmwareMiddleware.test.ts
  packages/suite/src/middlewares/suite/buttonRequestMiddleware.ts
  packages/suite/src/middlewares/suite/logsMiddleware.ts
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/reducers/firmware/firmwareReducer.ts
  packages/suite/src/reducers/firmware/index.ts
  packages/suite/src/reducers/store.ts
  packages/suite/src/reducers/suite/deviceReducer.ts
  packages/suite/src/support/extraDependencies.ts
  packages/suite/src/types/suite/index.ts
  packages/suite/src/views/settings/debug/Devkit.tsx
  suite-common/redux-utils/src/extraDependenciesType.ts
  suite-common/test-utils/src/extraDependenciesMock.ts
Labels: code, mobile-app, monorepo

#9032 chore(suite-native): bump version number
  suite-native/app/package.json
Labels: mobile-app

#8948 feat(suite-native): persistent graph timeframe storage
  suite-common/graph/src/hooks.ts
  suite-native/graph/package.json
  suite-native/graph/src/components/GraphContextProvider.tsx
  suite-native/graph/src/hooks.ts
  suite-native/graph/src/index.ts
  suite-native/graph/src/slice.ts
  suite-native/graph/src/types.ts
  suite-native/graph/tsconfig.json
  suite-native/module-accounts/src/components/AccountDetailGraph.tsx
  suite-native/module-home/src/components/PortfolioGraph.tsx
  suite-native/state/package.json
  suite-native/state/src/reducers.ts
  suite-native/state/tsconfig.json
  yarn.lock
Labels: mobile-app

#9022 fix(suite): fix hologram sticker tooltip not being visible
  packages/components/src/components/Tooltip/index.tsx
  packages/suite/src/components/onboarding/Hologram.tsx
  packages/suite/src/views/onboarding/steps/Welcome/components/PreOnboardingSetup/SecurityCheck.tsx
Labels: UI

#9017 fix(suite): show stop on hover when there is no deadline yet in CJ status wheel
  packages/suite/src/components/wallet/CoinjoinSummary/CoinjoinStatusWheel/ProgressContent.tsx
Labels: coinjoin

#9042 fix(suite-native): axisl label padding
  suite-native/graph/src/components/AxisLabel.tsx
Labels: mobile-app

#9043 fix(suite-native): axisl label padding (#9042)
  suite-native/graph/src/components/AxisLabel.tsx
Labels: release-native

#9051 chore(suite-desktop,e2e): fix command to run suite-desktop e2e tests
  docker/docker-compose.suite-desktop-ci.yml
  docker/docker-compose.suite-desktop-test.yml
Labels: low hanging fruit

#9048 Crowdin translations update
  packages/suite-data/files/translations/af.json
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/da.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/el.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fi.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/he.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/id.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/no.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#9064 fix(mobile): freeze on attempt to import address as account
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
Labels: mobile-app

#9056 Fix 'Cannot read properties of undefined (reading 'amount')'
  packages/suite/src/views/wallet/send/components/Options/components/EthereumOptions/Data.tsx
  packages/suite/src/views/wallet/send/components/Options/components/EthereumOptions/index.tsx
Labels: bug, ethereum

#9070 feat(suite): new homescreens for T2T1
  packages/suite-data/files/images/homescreens/COLOR_240x240/smile-1.jpg
  packages/suite-data/files/images/homescreens/COLOR_240x240/smile-2.jpg
  packages/suite/src/components/suite/HomescreenGallery.tsx
  packages/suite/src/constants/suite/homescreens.ts
Labels: release

#9061 feat(suite-desktop,tor): ensure that sentry issues wait in queue till Tor is Enabled
  packages/suite-desktop-core/src/app.ts
  packages/suite-desktop-core/src/libs/sentry.ts
  packages/suite-desktop-core/src/modules/index.ts
  packages/suite-desktop-core/src/modules/tor.ts
Labels: release
