Repository trezor/trezor-suite, pull requests merged in 2024-08, with the labels that each got.

#13582 fix(suite-native): open links via useOpenLink to catch errors
  suite-native/link/src/useOpenLink.ts
  suite-native/message-system/src/components/FeatureMessageScreen.tsx
  suite-native/transactions/src/screens/TransactionDetailScreen.tsx
Labels: mobile

#13486 Feat/native/discovery improvements
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/analytics/src/events.ts
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/discovery/src/discoveryMiddleware.ts
  suite-native/discovery/src/discoverySelectors.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/discovery/src/useIsDiscoveryDurationTooLong.tsx
  suite-native/discovery/src/utils.ts
  suite-native/module-dev-utils/src/components/DiscoveryCoinsFilter.tsx
Labels: mobile

#13608 fix(suite-native): fix assign to read-only property shadowOffset error
  suite-native/biometrics/src/components/BiometricsIcon.tsx
Labels: mobile

#13619 chore(suite-native): FIREBASE_TOKEN replaced by GOOGLE_APPLICATION_CREDENTIALS
  suite-native/app/eas-post-success.sh
Labels: ci, mobile

#13624 Crowdin translations update
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/da.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/el.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/he.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#13287 feat(mobile): support ETH tokens in graphs
  suite-common/graph/package.json
  suite-common/graph/redux.d.ts
  suite-common/graph/src/balanceHistoryUtils.ts
  suite-common/graph/src/graphBalanceEvents.ts
  suite-common/graph/src/graphDataFetching.ts
  suite-common/graph/src/graphUtils.ts
  suite-common/graph/src/hooks.ts
  suite-common/graph/src/index.ts
  suite-common/graph/src/tests/__fixtures__/btc.ts
  suite-common/graph/src/tests/__fixtures__/eth.ts
  suite-common/graph/src/tests/__fixtures__/xrp.ts
  suite-common/graph/src/tests/balanceHistoryUtils.test.ts
  suite-common/graph/src/tests/graphUtils.test.ts
  suite-common/graph/src/types.ts
  suite-common/graph/tsconfig.json
  suite-common/transaction-cache-engine/package.json
  suite-common/transaction-cache-engine/src/MemoryStorage.ts
  suite-common/transaction-cache-engine/src/TransactionCacheEngine.ts
  suite-common/transaction-cache-engine/src/index.ts
  suite-common/transaction-cache-engine/src/tests/TransactionCacheEngine.test.ts
  suite-common/transaction-cache-engine/src/tests/__fixtures__/btc.ts
  suite-common/transaction-cache-engine/src/tests/__fixtures__/index.ts
  suite-common/transaction-cache-engine/src/tests/__fixtures__/xrp.ts
  suite-common/transaction-cache-engine/src/types.ts
  suite-common/transaction-cache-engine/src/utils/asyncUtils.ts
  suite-common/transaction-cache-engine/src/utils/balanceHistory.ts
  suite-common/transaction-cache-engine/src/utils/tests/asyncUtils.test.ts
  suite-common/transaction-cache-engine/tsconfig.json
  suite-common/wallet-core/src/transactions/transactionsThunks.ts
  suite-native/accounts/package.json
  suite-native/accounts/src/hooks/useTransactionCache.ts
  suite-native/accounts/src/index.ts
  suite-native/accounts/src/transactionCacheMiddleware.ts
  suite-native/accounts/tsconfig.json
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  suite-native/app/src/initActions.ts
  suite-native/app/tsconfig.json
  suite-native/graph/src/hooks.ts
  suite-native/state/package.json
  suite-native/state/src/store.ts
  suite-native/state/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: mobile

#13637 chore(transport): remove unused json-stable-stringify dep
  packages/transport/package.json
  yarn.lock
Labels: low hanging fruit

#13573 GitBook revision update
  packages/suite-data/src/guide/constants.ts
Labels: guide

#13653 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite/src/support/messages.ts
Labels: translations

#13656 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite/src/support/messages.ts
Labels: translations

#13667 fix(suite): fix type error in knowledgebaseurls
  packages/suite/src/constants/suite/experimental.ts
Labels: low hanging fruit

#13666 chore: remove prepare-release script
  package.json
  scripts/prepare-release.sh
Labels: deployment

#13548 feat(suite-native): move coin enabling to settings menu
  suite-common/icons/assets/icons/coins.svg
  suite-common/icons/src/icons.ts
  suite-native/app/package.json
  suite-native/app/tsconfig.json
  suite-native/coin-enabling/package.json
  suite-native/coin-enabling/redux.d.ts
  suite-native/coin-enabling/src/components/DiscoveryCoinsFilter.tsx
  suite-native/coin-enabling/src/hooks/useCoinEnabling.tsx
  suite-native/coin-enabling/src/index.ts
  suite-native/coin-enabling/tsconfig.json
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/intl/src/en.ts
  suite-native/module-dev-utils/package.json
  suite-native/module-dev-utils/src/components/DiscoveryCoinsFilter.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/module-dev-utils/tsconfig.json
  suite-native/module-settings/package.json
  suite-native/module-settings/src/components/ApplicationSettings.tsx
  suite-native/module-settings/src/components/SettingsSection.tsx
  suite-native/module-settings/src/navigation/SettingsStackNavigator.tsx
  suite-native/module-settings/src/screens/SettingsCoinEnablingScreen.tsx
  suite-native/module-settings/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  tsconfig.json
  yarn.lock
Labels: mobile

#13685 fix(coinmarket): update electron routes
  packages/suite-desktop-ui/src/support/Router.tsx
Labels: bug, +Invity

#13692 feat(suite-native): app settings reorg
  suite-native/intl/src/en.ts
  suite-native/module-settings/src/components/FeaturesSettings.tsx
  suite-native/module-settings/src/components/PreferencesSettings.tsx
  suite-native/module-settings/src/components/SettingsSection.tsx
  suite-native/module-settings/src/components/SupportSettings.tsx
  suite-native/module-settings/src/screens/SettingsScreen.tsx
Labels: mobile

#13697 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ja.json
  packages/suite/src/support/messages.ts
Labels: translations

#13661 feat(mobile): graph for erc20 token prices
  suite-common/graph/src/balanceHistoryUtils.ts
  suite-common/graph/src/graphBalanceEvents.ts
  suite-common/graph/src/tests/balanceHistoryUtils.test.ts
  suite-common/graph/src/tests/graphBalanceEvents.test.ts
  suite-common/graph/src/types.ts
  suite-native/ethereum-tokens/src/ethereumTokensSelectors.ts
  suite-native/graph/package.json
  suite-native/graph/src/components/TransactionEventTooltip.tsx
  suite-native/graph/src/hooks.ts
  suite-native/graph/tsconfig.json
  suite-native/module-accounts-management/src/components/AccountDetailCryptoValue.tsx
  suite-native/module-accounts-management/src/components/AccountDetailGraph.tsx
  suite-native/module-accounts-management/src/components/AccountDetailGraphHeader.tsx
  suite-native/module-accounts-management/src/components/AccountDetailTokenHeader.tsx
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
  yarn.lock
Labels: mobile

#13707 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#13681 feat(suite-native): account purge and discovery on coin enabling
  suite-native/coin-enabling/src/components/DiscoveryCoinsFilter.tsx
  suite-native/coin-enabling/src/hooks/useCoinEnabling.tsx
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/discovery/src/discoveryMiddleware.ts
  suite-native/discovery/src/discoverySelectors.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
  suite-native/state/package.json
  suite-native/state/src/extraDependencies.ts
  suite-native/state/tsconfig.json
  yarn.lock
Labels: mobile

#13717 chore(connect-common): add fw 2.8.1
  packages/connect-common/files/firmware/t2t1/releases.json
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.7.2-bitcoinonly.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.7.2.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.8.1-bitcoinonly.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.8.1.bin
  packages/connect-common/files/firmware/t3t1/releases.json
  packages/connect-common/files/firmware/t3t1/trezor-t3t1-2.8.0-bitcoinonly.bin
  packages/connect-common/files/firmware/t3t1/trezor-t3t1-2.8.0.bin
  packages/connect-common/files/firmware/t3t1/trezor-t3t1-2.8.1-bitcoinonly.bin
  packages/connect-common/files/firmware/t3t1/trezor-t3t1-2.8.1.bin
Labels: release

#13725 fix(suite-native): remove odd space in device switcher
  suite-native/device-manager/src/components/DeviceManagerModal.tsx
Labels: mobile

#13718 feat(suite-native): coin enabling in settings final UI
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/atoms/src/Switch.tsx
  suite-native/coin-enabling/package.json
  suite-native/coin-enabling/src/assets/BtcSvg.tsx
  suite-native/coin-enabling/src/components/BtcOnlyCoinEnablingContent.tsx
  suite-native/coin-enabling/src/components/DiscoveryCoinsFilter.tsx
  suite-native/coin-enabling/src/components/NetworkSymbolSwitchItem.tsx
  suite-native/coin-enabling/src/index.ts
  suite-native/coin-enabling/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-settings/src/screens/SettingsCoinEnablingScreen.tsx
  yarn.lock
Labels: mobile

#13805 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite/src/support/messages.ts
Labels: translations

#13811 chore(mobile): minor graph improvements
  suite-common/graph/src/tests/balanceHistoryUtils.test.ts
  suite-common/graph/src/types.ts
  suite-native/graph/src/components/Graph.tsx
  suite-native/graph/src/components/TransactionEventTooltip.tsx
  suite-native/graph/src/hooks.ts
Labels: mobile

#13785 feat(suite-native): changing switch visuals to stand out more
  suite-native/atoms/src/Switch.tsx
  suite-native/coin-enabling/src/components/NetworkSymbolSwitchItem.tsx
Labels: mobile

#13836 Crowdin translations update
  packages/suite-data/files/translations/be.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/tr.json
  packages/suite/src/support/messages.ts
Labels: translations

#13866 fix(mobile): fix reload on iOS
  suite-common/icons/package.json
  suite-native/app/package.json
  suite-native/atoms/package.json
  suite-native/graph/package.json
  suite-native/module-accounts-import/package.json
  suite-native/react-native-graph/package.json
  suite-native/receive/package.json
  suite-native/transactions/package.json
  yarn.lock
Labels: mobile

#13855 fix(suite-native): interrupted discovery might have been considered finished
  suite-native/discovery/src/utils.ts
Labels: mobile

#13877 Set connection status default to online
  suite-native/connection-status/src/useIsOfflineBannerVisible.tsx
Labels: mobile

#13878 Crowdin translations update
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/be.json
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/el.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/vi.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#13892 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/vi.json
  packages/suite/src/support/messages.ts
Labels: translations

#13851 feat(suite-native): make coin enabling list items pressable
  suite-native/coin-enabling/src/components/NetworkSymbolSwitchItem.tsx
Labels: mobile

#13858 feat(suite-native): for coin enabling show first empty account
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile

#13911 chore(suite-native): bump app version to 24.8.2
  suite-native/app/package.json
Labels: mobile

#13918 feat(suite-native): netinfo isConnected and reachabiltyUrl
  suite-native/connection-status/src/useIsOfflineBannerVisible.tsx
Labels: mobile, release-native

#13930 feat(suite-native): reachability isInternetReachable
  suite-native/connection-status/src/useIsOfflineBannerVisible.tsx
Labels: mobile

#13928 fix(coinmarket): delete temporarly best rate & update exchange list
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketFeaturedOffers/CoinmarketFeaturedOffersItem.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormOfferItem.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffersItem.tsx
Labels: bug, +Invity

#13942 fix(suite-native): put back last working setup for netinfo
  suite-native/connection-status/src/useIsOfflineBannerVisible.tsx
Labels: mobile

#13947 chore(scripts): add list-outdated
  package.json
  scripts/list-outdated-dependencies/common-dependencies.txt
  scripts/list-outdated-dependencies/connect-dependencies.txt
  scripts/list-outdated-dependencies/list-outdated-dependencies.sh
  scripts/list-outdated-dependencies/mission-dependencies.txt
  scripts/list-outdated-dependencies/mobile-dependencies.txt
  scripts/list-outdated-dependencies/qa-dependencies.txt
  scripts/list-outdated-dependencies/trends-dependencies.txt
  scripts/list-outdated-dependencies/usability-dependencies.txt
Labels: dependencies

#13952 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/sv.json
  packages/suite/src/support/messages.ts
Labels: translations

#13955 fix(suite-native): if cardano is on, discovery ends too early
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile

#13956 feat(mobile): Refactor AccountList + TokenSelectModal
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/accounts/src/components/AccountListItemBase.tsx
  suite-native/accounts/src/components/AccountListItemInteractive.tsx
  suite-native/accounts/src/components/AccountsList.tsx
  suite-native/accounts/src/components/TokenSelectBottomSheet.tsx
  suite-native/accounts/src/index.ts
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/assets/src/components/Assets.tsx
  suite-native/atoms/src/Card/Card.tsx
  suite-native/atoms/src/Skeleton/ListItemSkeleton.tsx
  suite-native/module-accounts-management/src/screens/AccountsScreen/AccountsScreen.tsx
  suite-native/module-receive/src/screens/ReceiveAccountsScreen.tsx
  suite-native/module-send/src/screens/SendAccountsScreen.tsx
  suite-native/receive/src/components/ReceiveAccountDetailsCard.tsx
  yarn.lock
Labels: mobile

#13967 chore(scripts): rearrange command to pass shellcheck
  scripts/list-outdated-dependencies/list-outdated-dependencies.sh
Labels: dependencies

#13991 feat(wallet-core): disableAccountsThunk can exclude portfolio accounts
  suite-common/wallet-core/src/accounts/accountsThunks.ts
Labels: mobile

#13951 fix(suite-native): align styles of the Input component with design
  packages/theme/src/colors.ts
  suite-native/atoms/src/Input/Input.tsx
Labels: mobile

#14010 fix(suite-native): ignore first evm ledger derivation path in discovery
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile

#14004 chore(mobile): upgrade deps to RN 0.75
  package.json
  packages/styles/package.json
  suite-common/icons/package.json
  suite-native/accounts/package.json
  suite-native/alerts/package.json
  suite-native/app/package.json
  suite-native/assets/package.json
  suite-native/atoms/package.json
  suite-native/biometrics/package.json
  suite-native/coin-enabling/package.json
  suite-native/connection-status/package.json
  suite-native/device-authorization/package.json
  suite-native/device-manager/package.json
  suite-native/device/package.json
  suite-native/feature-flags/package.json
  suite-native/formatters/package.json
  suite-native/forms/package.json
  suite-native/graph/package.json
  suite-native/message-system/package.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-management/package.json
  suite-native/module-add-accounts/package.json
  suite-native/module-authorize-device/package.json
  suite-native/module-dev-utils/package.json
  suite-native/module-home/package.json
  suite-native/module-onboarding/package.json
  suite-native/module-receive/package.json
  suite-native/module-send/package.json
  suite-native/module-settings/package.json
  suite-native/navigation/package.json
  suite-native/notifications/package.json
  suite-native/qr-code/package.json
  suite-native/react-native-graph/package.json
  suite-native/receive/package.json
  suite-native/state/package.json
  suite-native/storage/package.json
  suite-native/test-utils/package.json
  suite-native/theme/package.json
  suite-native/toasts/package.json
  suite-native/transactions/package.json
  suite-native/video-assets/package.json
  yarn.lock
Labels: mobile
