Repository trezor/trezor-suite, pull requests merged in 2024-01, with the labels that each got.

#10445 feat(suite-native): remove chunking after address is confirmed
  suite-native/app/ios/Podfile.lock
  suite-native/qr-code/src/components/AddressQRCode.tsx
Labels: mobile-app

#10447 fix(suite-native): passphrase dialog on device
  suite-native/app/src/App.tsx
Labels: mobile-app

#10450 fix(suite-native): account type labels
  suite-common/wallet-config/src/networksConfig.ts
  suite-common/wallet-core/src/accounts/constants.ts
  suite-native/module-accounts-import/src/constants.ts
Labels: mobile-app

#10455 Solana token issues
  packages/blockchain-link-types/src/solana.ts
  packages/blockchain-link-utils/src/solana.ts
  packages/blockchain-link-utils/src/tests/fixtures/solana.ts
  packages/blockchain-link-utils/src/tests/solana.test.ts
  packages/blockchain-link/src/workers/solana/index.ts
Labels: release, solana

#10459 fix(ci): remove unused fastlane plugin
  suite-native/app/Gemfile.lock
  suite-native/app/fastlane/Pluginfile
Labels: mobile-app

#10465 chore(suite-native): extend CI trigger paths
  .github/workflows/suite-native_develop_ci.yml
Labels: mobile-app

#10457 fix(mobile): fix crashes during discovery
  packages/react-native-usb/src/ReactNativeUsb.types.ts
  packages/react-native-usb/src/index.ts
  suite-native/react-native-graph/src/AnimatedLineGraph.tsx
Labels: mobile-app

#10461 fix(mobile): fix animation related crashes
  suite-common/icons/package.json
  suite-native/accounts/package.json
  suite-native/alerts/package.json
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  suite-native/assets/package.json
  suite-native/atoms/package.json
  suite-native/device-manager/package.json
  suite-native/graph/package.json
  suite-native/link/package.json
  suite-native/message-system/package.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-management/package.json
  suite-native/notifications/package.json
  suite-native/react-native-graph/package.json
  suite-native/receive/package.json
  suite-native/test-utils/package.json
  suite-native/toasts/package.json
  suite-native/transactions/package.json
  yarn.lock
Labels: mobile-app

#10469 Bump beta version to 24.2.0
  packages/suite/package.json
Labels: deployment

#10462 tests(suite): reorganize passphrase tests
  packages/suite-web/e2e/tests/suite/passphrase-input.test.ts
  packages/suite-web/e2e/tests/suite/passphrase-legacy.test.ts
  packages/suite-web/e2e/tests/suite/passphrase.test.ts
Labels: e2e

#10473 fix(suite-native): enable discovery for all device supported networks
  suite-native/app/ios/Podfile.lock
  suite-native/config/src/supportedNetworks.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/module-accounts-import/src/components/AccountImportSummary.tsx
  suite-native/state/src/extraDependencies.ts
Labels: mobile-app

#10472 fix/wipe-code-switch
  packages/suite-analytics/src/constants.ts
  packages/suite-analytics/src/types/events.ts
  packages/suite/src/actions/settings/deviceSettingsActions.ts
  packages/suite/src/components/suite/notifications/NotificationRenderer/NotificationRenderer.tsx
  packages/suite/src/config/suite/settings.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/SettingsDevice/WipeCode.tsx
  suite-common/toast-notifications/src/types.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
Labels: settings, release

#10478 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#10483 chore(suite-native): upgrade app version
  suite-native/app/package.json
Labels: mobile-app

#10485 chore(connect): publish config experiment
  packages/connect-plugin-ethereum/package.json
Labels: monorepo

#10482 chore(suite-native): networks whitelist
  suite-native/config/package.json
  suite-native/config/src/supportedNetworks.ts
  suite-native/config/tsconfig.json
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/module-accounts-import/src/components/AccountImportSummary.tsx
  suite-native/state/src/extraDependencies.ts
  yarn.lock
Labels: mobile-app

#10481 fix(graph): allow negative balance in graph to fix rare bitcoin graph issues
  suite-common/graph/src/graphDataFetching.ts
Labels: mobile-app

#10494 fix(suite-native): feature flag
  suite-native/feature-flags/package.json
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/feature-flags/tsconfig.json
  yarn.lock
Labels: mobile-app

#10484 feat(suite-native): account type grouped account list
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/accounts/constants.ts
  suite-native/accounts/src/components/AccountListItemInteractive.tsx
  suite-native/accounts/src/components/AccountsList.tsx
  suite-native/accounts/src/components/AccountsListGroup.tsx
  suite-native/accounts/src/components/GroupedAccountsList.tsx
  suite-native/accounts/src/selectors.ts
  suite-native/accounts/src/tests/selectors.test.ts
  suite-native/accounts/src/types.ts
  suite-native/accounts/src/utils.ts
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/assets/src/components/NetworkAssetsBottomSheet.tsx
  suite-native/blockchain/src/blockchainThunks.ts
Labels: mobile-app

#10490 chore(suite): sentry upgrade
  packages/suite-web/package.json
  packages/suite/package.json
  suite-common/sentry/package.json
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  suite-native/module-dev-utils/package.json
  yarn.lock
Labels: sentry, mobile-app

#9858 fix(suite): list cardanoGetPublicKey in connect wrapped methods
  packages/suite/src/actions/wallet/__fixtures__/publicKeyActions.ts
  suite-common/connect-init/src/connectInitThunks.ts
Labels: good first issue, low hanging fruit

#10544 fix(suite-native): T1B1 device font fixed
  packages/theme/fonts/PixelOperatorMono8-Regular.ttf
Labels: mobile-app

#10495 fix(suite-native): account type migration fix
  suite-native/state/src/reducers.ts
  suite-native/storage/package.json
  suite-native/storage/src/index.ts
  suite-native/storage/src/migrations/account/v3.ts
  suite-native/storage/src/tests/migrations/accountV3.test.ts
  suite-native/storage/tsconfig.json
  yarn.lock
Labels: mobile-app

#10547 feat(suite-native): improve mobile accessibility
  suite-native/atoms/src/AccordionItem.tsx
  suite-native/atoms/src/ListItem/SelectableListItem.tsx
  suite-native/atoms/src/Radio.tsx
  suite-native/atoms/src/Select/SelectItem.tsx
  suite-native/atoms/src/Sheet/BottomSheetHeader.tsx
  suite-native/atoms/src/Switch.tsx
  suite-native/atoms/src/index.ts
  suite-native/device-manager/src/components/DeviceSwitch.tsx
  suite-native/module-accounts-import/src/components/AccountImportSubHeader.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-connect-device/src/components/ConnectDeviceScreenHeader.tsx
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-settings/src/components/AboutUsBanners.tsx
  suite-native/module-settings/src/components/TouchableSwitchRow.tsx
  suite-native/navigation/src/components/GoBackIcon.tsx
  suite-native/qr-code/src/components/QRCodeScanner.tsx
Labels: mobile-app

#10551 GitBook revision update
  packages/suite-data/src/guide/constants.ts
Labels: guide

#10564 Fix/font accessibility
  suite-native/atoms/src/Text.tsx
  suite-native/atoms/src/TrezorSuiteLiteHeader.tsx
  suite-native/module-onboarding/src/screens/AnalyticsConsentScreen.tsx
  suite-native/module-onboarding/src/screens/WelcomeScreen.tsx
Labels: mobile-app, accessibility

#10581 chore(suite-data): update gitbook revision
  packages/suite-data/src/guide/constants.ts
Labels: release, guide

#10585 fix(suite-native): add dogecoin
  suite-native/config/src/supportedNetworks.ts
Labels: mobile-app

#10582 Fix/freeze between navigation stacks
  suite-native/accounts/package.json
  suite-native/app/package.json
  suite-native/assets/package.json
  suite-native/device-manager/package.json
  suite-native/device/package.json
  suite-native/intl/src/en.ts
  suite-native/intl/src/index.ts
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-management/package.json
  suite-native/module-connect-device/package.json
  suite-native/module-dev-utils/package.json
  suite-native/module-home/package.json
  suite-native/module-home/src/assets/ConnectTrezorSvg.tsx
  suite-native/module-home/src/assets/DarkConnectedTrezorSvg.tsx
  suite-native/module-home/src/assets/connectTrezor.svg
  suite-native/module-home/src/assets/darkConnectTrezor.svg
  suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyPortfolioCrossroads.tsx
  suite-native/module-onboarding/package.json
  suite-native/module-onboarding/src/components/CoinsSvg.tsx
  suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx
  suite-native/module-onboarding/src/screens/TrackBalancesScreen.tsx
  suite-native/module-receive/package.json
  suite-native/module-settings/package.json
  suite-native/navigation/package.json
  suite-native/notifications/package.json
  suite-native/qr-code/package.json
  suite-native/receive/package.json
  suite-native/transactions/package.json
  yarn.lock
Labels: mobile-app

#10578 Fix/eth tokens discovery
  suite-native/accounts/src/components/AccountListItemInteractive.tsx
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/fiat-rates/src/fiatRatesMiddleware.ts
Labels: mobile-app

#10588 fix(suite-native): settings navigation
  suite-native/module-accounts-management/src/screens/AccountsScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyPortfolioCrossroads.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyPortfolioTrackerState.tsx
  suite-native/module-home/src/screens/HomeScreen/components/SettingsButtonLink.tsx
  suite-native/navigation/package.json
  suite-native/navigation/src/components/TabBar.tsx
  suite-native/navigation/tsconfig.json
  yarn.lock
Labels: mobile-app

#10605 Crowdin translations update
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/lol.json
  packages/suite/src/support/messages.ts
Labels: translations

#10609 fix(suite-native): legacy segwit address T1B1
  suite-native/receive/src/utils.ts
Labels: mobile-app

#10622 fix(suite-native): discovery skeleton layout
  suite-native/atoms/src/Skeleton/ListItemSkeleton.tsx
Labels: mobile-app

#10623 fix(suite-native): receive address xpub fix
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile-app

#10626 ref(suite-native): remove receive banners
  suite-native/intl/src/en.ts
  suite-native/receive/assets/check.png
  suite-native/receive/assets/check@2x.png
  suite-native/receive/assets/check@3x.png
  suite-native/receive/assets/darkCheck.png
  suite-native/receive/assets/darkCheck@2x.png
  suite-native/receive/assets/darkCheck@3x.png
  suite-native/receive/assets/darkTrezorTruth.png
  suite-native/receive/assets/darkTrezorTruth@2x.png
  suite-native/receive/assets/darkTrezorTruth@3x.png
  suite-native/receive/assets/trezorTruth.png
  suite-native/receive/assets/trezorTruth@2x.png
  suite-native/receive/assets/trezorTruth@3x.png
  suite-native/receive/package.json
  suite-native/receive/src/components/ShowAddressButtons.tsx
  suite-native/receive/src/components/VerificationWalkthroughBottomSheet.tsx
  suite-native/receive/tsconfig.json
  yarn.lock
Labels: mobile-app

#10625 chore(suite-native): remove cancel from connecting screen
  suite-native/module-connect-device/src/components/ConnectDeviceScreenHeader.tsx
  suite-native/module-connect-device/src/components/ConnectDeviceSreenView.tsx
Labels: mobile-app

#10629 fix(suite-native): homescreen spacings
  suite-native/atoms/src/Skeleton/ListItemSkeleton.tsx
  suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
Labels: mobile-app

#10633 fix(suite-native): receive copy
  suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx
Labels: mobile-app

#10630 feat(suite-native): empty states copy
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AccountListPlaceholder.tsx
  suite-native/accounts/src/components/AccountsList.tsx
  suite-native/accounts/tsconfig.json
  suite-native/intl/src/en.ts
  yarn.lock
Labels: mobile-app

#10635 fix(suite-native): correct error for firmwareless device
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/device/src/hooks/useDetectDeviceError.tsx
Labels: mobile-app

#10637 fix(mobile): icons in Modal
  suite-common/icons/src/components/CryptoIcon.tsx
  suite-common/icons/src/components/FlagIcon.tsx
  suite-common/icons/src/components/Icon.tsx
  suite-common/icons/src/useRerenderOnAppState.ios.ts
  suite-common/icons/src/useRerenderOnAppState.ts
Labels: mobile-app

#10651 chore(mobile): update Skia to latest version
  suite-common/icons/package.json
  suite-native/app/ios/Podfile.lock
  suite-native/app/package.json
  suite-native/atoms/package.json
  suite-native/graph/package.json
  suite-native/module-accounts-import/package.json
  suite-native/react-native-graph/package.json
  suite-native/receive/package.json
  suite-native/transactions/package.json
  yarn.lock
Labels: mobile-app

#10648 fix(suite-native): empty passphrase
  suite-native/app/src/App.tsx
Labels: mobile-app

#10638 Update graph tooltip
  packages/suite/src/support/messages.ts
  packages/suite/src/views/dashboard/components/PortfolioCard/index.tsx
Labels: graph, solana

#10662 fix(suite-native): fastlane syntax
  suite-native/app/android/fastlane/Fastfile
Labels: mobile-app

#10665 Fix/revert sentry
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
  .github/workflows/suite-native_staging_ci.yml
  suite-native/app/Gemfile.lock
  suite-native/app/android/fastlane/Fastfile
  suite-native/app/fastlane/Pluginfile
Labels: mobile-app

#10660 Handle unsupported devices during device auth check
  packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx
Labels: bug

#10652 fix(suite-native): flat graph for zero value
  suite-common/graph/src/graphUtils.ts
Labels: mobile-app

#10561 fix: small UI bugs
  packages/components/src/components/Badge/Badge.stories.tsx
  packages/components/src/components/Badge/Badge.tsx
  packages/components/src/components/form/Checkbox/Checkbox.tsx
  packages/suite/src/components/backup/AfterBackupCheckboxes.tsx
  packages/suite/src/components/backup/PreBackupCheckboxes.tsx
  packages/suite/src/components/firmware/SelectCustomFirmware.tsx
  packages/suite/src/components/suite/ChangeDeviceLabel.tsx
  packages/suite/src/components/suite/InstructionStep.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/WipeDeviceModal.tsx
  packages/suite/src/components/suite/troubleshooting/tips.tsx
  packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountItem.tsx
  packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsList.tsx
  packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AccountsMenu.tsx
  packages/suite/src/components/wallet/WalletLayout/AccountsMenu/TokensCount.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/suite/anchor.ts
  packages/suite/src/views/dashboard/components/PromoBanner.tsx
  packages/suite/src/views/onboarding/steps/Final.tsx
  packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx
  packages/suite/src/views/recovery/index.tsx
  packages/suite/src/views/settings/SettingsGeneral/SettingsGeneral.tsx
  packages/suite/src/views/settings/SettingsGeneral/VersionWithUpdate.tsx
  packages/suite/src/views/settings/SettingsGeneral/VersionWithUpdate/VersionWithGithubTooltip.tsx
  packages/suite/src/views/start/StartContent.tsx
Labels: UI

#10668 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/sk.json
  packages/suite/src/support/messages.ts
Labels: translations

#10669 Add Portuguese as a community translation
  packages/suite/src/config/suite/languages.ts
Labels: translations

#10670 chore(suite-native): upgrade app version
  suite-native/app/package.json
Labels: mobile-app

#10516 fix(components): fix Select styles
  packages/components/src/components/form/Select/Select.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AccountTypeSelect/AccountTypeSelect.tsx
Labels: UI

#10693 chore(suite-native): add passphrase FF & refactor usage
  suite-native/device-manager/src/components/DeviceManager.tsx
  suite-native/device/src/middlewares/deviceMiddleware.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/feature-flags/src/index.ts
  suite-native/feature-flags/src/useFeatureFlag.tsx
  suite-native/feature-flags/src/useIsUsbDeviceConnectFeatureEnabled.tsx
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyHomeRenderer.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
  suite-native/module-onboarding/src/components/OnboardingScreenHeader.tsx
  suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx
  suite-native/module-onboarding/src/screens/TrackBalancesScreen.tsx
  suite-native/module-onboarding/src/screens/WelcomeScreen.tsx
  suite-native/module-settings/src/components/FAQInfoPanel.tsx
Labels: mobile-app

#10698 chore(suite-native): dead code clean up
  suite-native/atoms/src/Chip.tsx
  suite-native/atoms/src/index.ts
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-settings/src/components/CoinsSettings.tsx
  suite-native/module-settings/src/index.ts
Labels: mobile-app

#10680 chore(suite-native): track breadcrumbs for sentry on screen change
  suite-native/app/ios/Podfile.lock
  suite-native/navigation/package.json
  suite-native/navigation/src/components/NavigationContainerWithAnalytics.tsx
  yarn.lock
Labels: mobile-app

#10708 fix(suite-native): select persisted devices selector
  suite-common/wallet-core/src/device/deviceReducer.ts
Labels: mobile-app

#10717 fix(suite-native): device selectors naming
  packages/suite/src/actions/wallet/selectedAccountActions.ts
  packages/suite/src/components/suite/CoinList/CoinList.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx
  packages/suite/src/middlewares/wallet/discoveryMiddleware.ts
  packages/suite/src/middlewares/wallet/graphMiddleware.ts
  packages/suite/src/support/extraDependencies.ts
  packages/suite/src/views/dashboard/components/AssetsCard/index.tsx
  packages/suite/src/views/settings/SettingsCoins/SettingsCoins.tsx
  suite-common/redux-utils/src/extraDependenciesType.ts
  suite-common/test-utils/src/extraDependenciesMock.ts
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-common/wallet-core/src/discovery/discoveryReducer.ts
  suite-common/wallet-core/src/discovery/discoveryThunks.ts
  suite-native/accounts/src/components/AccountsList.tsx
  suite-native/accounts/src/selectors.ts
  suite-native/assets/src/components/NetworkAssetsBottomSheet.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/device-manager/src/components/PortfolioTrackerDeviceManagerContent.tsx
  suite-native/device/src/hooks/useDetectDeviceError.tsx
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/device/src/screens/DeviceInfoModalScreen.tsx
  suite-native/device/src/selectors.ts
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/module-accounts-import/src/accountsImportThunks.ts
  suite-native/module-accounts-import/src/components/AccountImportSubHeader.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-management/src/screens/AccountSettingsScreen.tsx
  suite-native/module-accounts-management/src/screens/AccountsScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyHomeRenderer.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraph.tsx
  suite-native/receive/src/components/ReceiveAddressCard.tsx
  suite-native/receive/src/components/ShowAddressButtons.tsx
  suite-native/receive/src/components/UnverifiedAddress.tsx
  suite-native/receive/src/hooks/useAccountReceiveAddress.tsx
Labels: mobile-app

#10719 fix(suite-native): fee rate formatter
  suite-native/formatters/src/components/FeeFormatter.tsx
Labels: mobile-app

#10712 Feat/discovery networks disable
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/module-dev-utils/package.json
  suite-native/module-dev-utils/src/components/DiscoveryCoinsFilter.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/module-dev-utils/tsconfig.json
  yarn.lock
Labels: mobile-app

#10732 chore(suite-common): remove selectCurrentDevice
  packages/suite/src/support/extraDependencies.ts
  suite-common/redux-utils/src/extraDependenciesType.ts
  suite-common/test-utils/src/extraDependenciesMock.ts
  suite-common/toast-notifications/src/notificationsActions.ts
  suite-common/toast-notifications/src/tests/notificationsReducer.test.ts
Labels: mobile-app

#10733 feat(suite-native): android face recognition
  suite-common/icons/assets/cryptoIcons/dsol.svg
  suite-common/icons/assets/cryptoIcons/sol.svg
  suite-common/icons/assets/icons/face.svg
  suite-common/icons/assets/icons/touchId.svg
  suite-common/icons/src/icons.ts
  suite-native/biometrics/package.json
  suite-native/biometrics/src/index.ts
  suite-native/biometrics/src/tests/utils.test.ts
  suite-native/biometrics/src/utils.ts
  suite-native/intl/src/en.ts
  suite-native/module-home/src/screens/HomeScreen/components/BiometricsBottomSheet.tsx
  suite-native/module-home/src/screens/HomeScreen/components/BiometricsBottomSheetIcons.tsx
  yarn.lock
Labels: mobile-app

#10706 fix(blockchain-link-utils): display Solana `self` token txs correctly
  packages/blockchain-link-utils/src/solana.ts
Labels: solana

#10703 chore(suite-native): passphrase modal with form
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  suite-native/app/tsconfig.json
  suite-native/device-manager/package.json
  suite-native/device-manager/src/components/AddHiddenWalletButton.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/device-manager/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/passphrase/package.json
  suite-native/passphrase/src/PassphraseFormModal.tsx
  suite-native/passphrase/src/PassphraseModalRenderer.tsx
  suite-native/passphrase/src/index.ts
  suite-native/passphrase/src/isPassphraseModalVisibleAtom.ts
  suite-native/passphrase/tsconfig.json
  yarn.lock
Labels: mobile-app

#10747 chore(suite-native): improve dev utils
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
Labels: mobile-app

#10701 fix(suite): fix the sign-verify address Select
  packages/suite/src/views/wallet/sign-verify/components/HiddenAddressRow.tsx
  packages/suite/src/views/wallet/sign-verify/components/VerifyAddressButton.tsx
Labels: bug

#10672 Feat/solana: get sol token metadata from coingecko
  packages/blockchain-link-utils/src/solana.ts
  packages/blockchain-link-utils/src/tests/solana.test.ts
  packages/blockchain-link/src/workers/solana/index.ts
  packages/blockchain-link/src/workers/solana/tokenUtils.ts
Labels: solana

#10758 fix(suite-native): multiline input
  suite-native/atoms/src/Input/Input.tsx
Labels: mobile-app

#10767 chore(suite-native): secure input, no capitalize
  suite-native/passphrase/src/PassphraseFormModal.tsx
Labels: mobile-app

#10738 ref(suite-common): move passphrase related logic to common
  packages/components/package.json
  packages/components/src/components/Passphrase/PassphraseTypeCard.tsx
  packages/components/tsconfig.json
  packages/suite/package.json
  packages/suite/src/actions/suite/modalActions.ts
  packages/suite/src/components/suite/PinMatrix/PinInput/PinInput.tsx
  packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/PassphraseModal.tsx
  packages/suite/src/constants/suite/inputs.ts
  packages/suite/src/hooks/wallet/sign-verify/useSignVerifyForm.ts
  packages/suite/src/views/wallet/coinmarket/buy/components/BuyForm/Inputs/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/FiatInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/p2p/form/Inputs.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Inputs/CryptoInput/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Inputs/FiatInput/index.tsx
  packages/suite/src/views/wallet/send/components/Options/BitcoinOptions/Locktime.tsx
  packages/suite/src/views/wallet/send/components/Options/EthereumOptions/Data.tsx
  packages/suite/src/views/wallet/send/components/Options/RippleOptions/DestinationTag.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Address/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/OpReturn/index.tsx
  packages/suite/tsconfig.json
  packages/validation/README.md
  packages/validation/src/index.ts
  suite-common/validators/package.json
  suite-common/validators/src/config.ts
  suite-common/validators/src/index.ts
  suite-common/validators/src/inputsLengthConfig.ts
  suite-common/validators/src/schemas/passphraseSchema.ts
  suite-common/validators/src/schemas/pinSchema.ts
  suite-common/validators/src/types.ts
  suite-common/validators/tsconfig.json
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-native/accounts/package.json
  suite-native/accounts/src/useAccountLabelForm.ts
  suite-native/accounts/tsconfig.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-accounts-import/tsconfig.json
  suite-native/module-accounts-management/package.json
  suite-native/module-accounts-management/tsconfig.json
  suite-native/module-connect-device/package.json
  suite-native/module-connect-device/src/components/PinForm.tsx
  suite-native/module-connect-device/src/components/PinFormControlButtons.tsx
  suite-native/module-connect-device/src/components/PinMatrixButton.tsx
  suite-native/module-connect-device/src/constants/pinFormConstants.ts
  suite-native/module-connect-device/tsconfig.json
  suite-native/passphrase/package.json
  suite-native/passphrase/src/PassphraseFormModal.tsx
  suite-native/passphrase/tsconfig.json
  yarn.lock
Labels: mobile-app

#10786 fix(suite-native): bottom sheet pan gesture sticky
  suite-native/atoms/src/Sheet/useBottomSheetAnimation.ts
Labels: mobile-app

#10774 Fix/graph axis overflow
  suite-native/graph/package.json
  suite-native/graph/src/components/AxisLabel.tsx
  suite-native/graph/src/components/Graph.tsx
  yarn.lock
Labels: mobile-app

#10744 fix(connect): rebootToBootloader misbehaviour
  packages/connect/src/core/index.ts
  packages/suite/src/hooks/firmware/useRebootRequest.ts
Labels: QA

#10778 feat(suite-native): close sheets by click outside
  suite-native/atoms/src/Sheet/BottomSheet.tsx
  suite-native/device-manager/src/components/DeviceManagerModal.tsx
Labels: mobile-app

#10692 Unify isCodesignBuild checks
  packages/env-utils/src/envUtils.ts
  packages/suite-build/configs/base.webpack.config.ts
  packages/suite-desktop-core/package.json
  packages/suite-desktop-core/src/libs/constants.ts
  packages/suite-desktop-core/tsconfig.json
  packages/suite/src/actions/suite/analyticsActions.ts
  packages/suite/src/actions/suite/guideActions.ts
  packages/suite/src/reducers/store.ts
  packages/suite/src/utils/suite/logsUtils.ts
  suite-common/message-system/scripts/sign-config.ts
  suite-common/message-system/src/messageSystemThunks.ts
  suite-common/suite-utils/src/build.ts
  yarn.lock
Labels: code

#10892 chore(message-system): remove phishing and solana messages
  suite-common/message-system/config/config.v1.json
Labels: message-system

#10568 GitBook revision update
  packages/suite-data/src/guide/constants.ts
Labels: guide

#10917 Expo build fixes
  suite-native/app/package.json
  suite-native/module-dev-utils/package.json
  suite-native/navigation/package.json
  yarn.lock
Labels: mobile-app

#10801 feat(suite-native): modals renderer
  packages/blockchain-link-types/package.json
  suite-native/alerts/src/components/AlertRenderer.tsx
  suite-native/app/src/App.tsx
  suite-native/app/src/ModalsRenderer.tsx
  suite-native/biometrics/src/components/AuthenticatorProvider.tsx
  suite-native/biometrics/src/components/BiometricsModalRenderer.tsx
  suite-native/biometrics/src/index.ts
  suite-native/notifications/src/components/NotificationRenderer.tsx
  suite-native/passphrase/src/PassphraseModalRenderer.tsx
  suite-native/toasts/src/components/ToastRenderer.tsx
Labels: mobile-app
