Repository trezor/trezor-suite, pull requests merged in 2024-02, with the labels that each got.

#10702 fix(suite-native): prevent biometrics request deadlock on ios
  suite-native/biometrics/package.json
  suite-native/biometrics/src/biometricsAtoms.ts
  suite-native/biometrics/src/components/BiometricOverlay.tsx
  suite-native/biometrics/src/components/BiometricsIcons.tsx
  suite-native/biometrics/src/index.ts
  suite-native/biometrics/src/useBiometrics.tsx
  suite-native/biometrics/src/useBiometricsSettings.ts
  suite-native/biometrics/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-home/src/screens/HomeScreen/components/BiometricsBottomSheet.tsx
  suite-native/module-home/src/screens/HomeScreen/components/BiometricsBottomSheetIcons.tsx
  yarn.lock
Labels: mobile-app

#10977 chore(ci): remove the suite-e rebase workflow
  .github/workflows/bot-rebase-suite-e.yml
Labels: ci

#10987 ci: disallow retry
  ci/test.yml
Labels: e2e

#10995 test(suite): improve flaky passphrase test
  packages/suite-web/e2e/tests/suite/passphrase.test.ts
Labels: e2e

#10966 fix(suite): coin filter outline
  packages/components/src/components/assets/CoinLogo/CoinLogo.tsx
  packages/suite/src/components/wallet/WalletLayout/AccountsMenu/CoinsFilter.tsx
Labels: UI

#10998 test(suite): improve flaky discreet-mode test
  packages/suite-web/e2e/tests/dashboard/discreet-mode.test.ts
Labels: e2e

#10990 Fix/xpub address validation
  suite-common/validators/package.json
  suite-common/validators/src/index.ts
  suite-common/validators/src/schemas/xpubSchema.ts
  suite-common/validators/tsconfig.json
  suite-common/wallet-utils/src/accountUtils.ts
  suite-native/forms/src/hooks/useForm.ts
  suite-native/intl/src/en.ts
  suite-native/module-accounts-import/src/components/XpubHint.tsx
  suite-native/module-accounts-import/src/components/XpubHintBottomSheet.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-accounts-management/src/components/AccountSettingsShowXpubButton.tsx
  suite-native/qr-code/package.json
  suite-native/qr-code/src/components/XpubQRCodeBottomSheet.tsx
  suite-native/qr-code/tsconfig.json
  yarn.lock
Labels: mobile-app

#10993 chore(suite-native): reintroduce redux flipper plugin
  suite-native/app/app.config.ts
  suite-native/app/package.json
  suite-native/app/plugins/withGradleProperties.js
  suite-native/state/package.json
  suite-native/state/src/store.ts
  yarn.lock
Labels: mobile-app

#11034 fix(connect): stream pollyfills
  suite-common/validators/src/index.ts
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
Labels: mobile-app

#11042 fix(suite-native): add qrcode padding
  suite-native/qr-code/src/components/QRCode.tsx
Labels: mobile-app

#11064 Revert "feat(blockchain-link); get sol token metadata from coingecko"
  packages/blockchain-link-utils/src/solana.ts
  packages/blockchain-link-utils/src/tests/solana.test.ts
  packages/blockchain-link/src/workers/solana/index.ts
  packages/blockchain-link/src/workers/solana/tokenUtils.ts
Labels: solana

#11050 fix(coinmarket): fix alignment of an exchange quote cta button
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/List/ExchangeQuote.tsx
Labels: bug

#11075 Crowdin translations update
  packages/suite-data/files/translations/af.json
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#11066 chore(ci) GitHub workflow run time analytics
  .github/workflows/validation.yml
  scripts/githubAnalytics.ts
  scripts/package.json
  yarn.lock
Labels: monorepo

#11080 Bump beta version to 24.3.0
  packages/suite/package.json
Labels: deployment

#11019 fix(suite): fix the notifications page on mobile
  packages/suite/src/components/wallet/WalletLayout/AccountsMenu/MobileAccountsMenu.tsx
  packages/suite/src/views/suite/notifications/index.tsx
Labels: UI

#11056 fix(suite-native): input top padding
  suite-native/atoms/src/Input/Input.tsx
Labels: mobile-app

#11039 Fix/persisted native message system
  suite-common/message-system/src/messageSystemReducer.ts
  suite-common/message-system/src/messageSystemSelectors.ts
  suite-common/message-system/src/messageSystemThunks.ts
  suite-native/message-system/src/messageSystemMiddleware.ts
  suite-native/state/src/reducers.ts
Labels: mobile-app

#11017 feat(theme): update dark theme shadows
  packages/theme/src/boxShadows.ts
Labels: UI

#11016 fix(suite): remove a useless animation from the Asset Table
  packages/suite/src/views/dashboard/components/AssetsView/components/AssetRow.tsx
Labels: UI

#11022 feat(suite): fix the discovery button animation
  packages/suite/src/components/wallet/WalletLayout/AccountsMenu/CoinsFilter.tsx
  packages/suite/src/views/settings/SettingsCoins/SettingsCoins.tsx
Labels: UI

#11087 chore(suite): hide polygon trade in trade section
  packages/suite/src/hooks/settings/useEnabledNetworks.ts
  packages/suite/src/hooks/wallet/useCoinmarketExchangeOffers.ts
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
Labels: release

#11095 fix(suite): polish send details
  packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewOutputList/TransactionReviewDetails.tsx
  packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewSummary.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/IOAddress.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/TxDetailModal.tsx
Labels: UI

#11031 fix(suite): fix trade input value not fitting
  packages/components/src/components/form/Select/Select.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoInput/SendCryptoSelect/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
Labels: UI

#11120 fix(suite): fetching fiat rates using eth token definitions
  suite-common/wallet-config/src/types.ts
  suite-common/wallet-core/src/token-definitions/tokenDefinitionsMiddleware.ts
  suite-common/wallet-core/src/token-definitions/tokenDefinitionsReducer.ts
  suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunks.ts
Labels: release

#11157 chore: downgrade electron-updater to fix build
  packages/connect-examples/electron-main-process/package.json
  packages/connect-examples/electron-renderer-with-assets/package.json
  packages/connect-examples/electron-renderer-with-popup/package.json
  packages/suite-desktop/package.json
  yarn.lock
Labels: dependencies

#11178 Crowdin translations update
  packages/suite-data/files/translations/af.json
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/da.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fi.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/he.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/id.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/no.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#11119 feat(suite-native): Add Account with type selection
  packages/theme/src/boxShadows.ts
  suite-native/atoms/src/SelectableItem.tsx
  suite-native/atoms/src/index.ts
  suite-native/intl/src/en.ts
  suite-native/module-add-accounts/package.json
  suite-native/module-add-accounts/src/components/AccountTypeDecisionBootomSheet.tsx
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
  suite-native/module-add-accounts/src/navigation/AddCoinAccountStackNavigator.tsx
  suite-native/module-add-accounts/src/screens/AddCoinAccountScreen.tsx
  suite-native/module-add-accounts/src/screens/SelectAccountTypeScreen.tsx
  suite-native/module-add-accounts/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile-app

#10898 feat(suite-native): expo eas
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
  .github/workflows/suite-native_staging_ci.yml
  packages/connect-iframe/webpack/base.webpack.config.ts
  packages/env-utils/package.json
  packages/env-utils/src/envUtils.native.ts
  suite-native/app/.env.debug
  suite-native/app/.env.develop
  suite-native/app/.env.production
  suite-native/app/.env.staging
  suite-native/app/README.md
  suite-native/app/app.config.ts
  suite-native/app/eas.json
  suite-native/app/fastlane/AndroidFastfile
  suite-native/app/fastlane/Appfile
  suite-native/app/fastlane/Fastfile
  suite-native/app/fastlane/IosFastfile
  suite-native/app/fastlane/Pluginfile
  suite-native/app/package.json
  suite-native/app/plugins/withAndroidSigningConfig.js
  suite-native/app/src/SentryProvider.tsx
  suite-native/app/upload-to-firebase.sh
  suite-native/config/src/debugUtils.ts
  suite-native/config/src/environment.ts
  suite-native/config/src/index.ts
  suite-native/module-dev-utils/src/components/BuildInfo.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/module-settings/package.json
  suite-native/module-settings/src/components/AppVersion.tsx
  suite-native/module-settings/src/components/ProductionDebug.tsx
  suite-native/module-settings/tsconfig.json
  yarn.lock
Labels: ci, mobile-app

#11193 fix(suite-native): fix dependency version
  suite-native/module-add-accounts/package.json
  yarn.lock
Labels: mobile-app

#11198 Submitting state for T1 PIN form
  suite-native/intl/src/en.ts
  suite-native/module-connect-device/src/components/ConnectDeviceSreenView.tsx
  suite-native/module-connect-device/src/components/PinForm.tsx
  suite-native/module-connect-device/src/components/PinFormControlButtons.tsx
  suite-native/module-connect-device/src/components/PinFormProgress.tsx
Labels: mobile-app

#11196 Make year dynamic in search tips and fix syntax
  docs/features/localization.md
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/transactions/TransactionList/NoSearchResults.tsx
Labels: translations

#11181 chore(components): use package name in import instead of relative path
  packages/components/src/components/buttons/buttonStyleUtils.ts
Labels: code

#11206 feat(suite-native): report token contract to analytics
  suite-native/analytics/src/events.ts
  suite-native/graph/src/hooks.ts
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-management/src/screens/AccountDetailScreen.tsx
  suite-native/transactions/src/screens/TransactionDetailScreen.tsx
Labels: mobile-app

#11203 fix(suite-native): shorten commit hash
  .github/workflows/suite-native_develop_ci.yml
  suite-native/app/app.config.ts
  suite-native/app/upload-to-firebase.sh
  suite-native/module-settings/src/components/AppVersion.tsx
Labels: ci, mobile-app

#11212 fix(suite-native): git commit sha
  suite-native/module-settings/src/components/AppVersion.tsx
Labels: mobile-app

#11205 fix(connect): set min version for rebootToBootloader to correct value
  packages/connect/src/data/config.ts
Labels: bug, connect

#11214 fix(suite-native): remove commit message
  .github/workflows/suite-native_develop_ci.yml
Labels: mobile-app

#11218 fix(suite-native): fix missing animation by defining width
  suite-native/module-connect-device/src/screens/ConnectAndUnlockDeviceScreen.tsx
  suite-native/module-onboarding/src/screens/ConnectTrezorScreen.tsx
Labels: mobile-app

#11197 feat(suite-native): production workflow
  .github/workflows/suite-native_production_ci.yml
  suite-native/app/app.config.ts
  suite-native/app/eas.json
  suite-native/app/plugins/withRemoveiOSNotificationEntitlement.js
  suite-native/app/upload-to-firebase.sh
Labels: mobile-app

#11255 Fix commit message check script for CI
  .github/workflows/commit-messages-check.yml
  scripts/check-commit-messages.sh
Labels: ci

#11263 fix(suite-native): eas develop
  .github/workflows/suite-native_develop_ci.yml
Labels: ci, mobile-app

#11287 chore(suite-native): blacklist polygon
  suite-native/config/src/supportedNetworks.ts
Labels: mobile-app

#11276 chore(repo): remove build:lib for some simple packages
  packages/analytics/package.json
  packages/connect-analytics/package.json
  packages/connect-common/package.json
  packages/connect-plugin-stellar/package.json
  packages/env-utils/package.json
  packages/node-utils/tsconfig.lib.json
  packages/protocol/package.json
  packages/schema-utils/package.json
Labels: monorepo

#11288 chore(repo): remove build from protobuf
  .eslintrc.js
  packages/connect-explorer/src/data/methods/cardano/getAddress.ts
  packages/connect/e2e/__fixtures__/cardanoGetAddress.ts
  packages/connect/e2e/__fixtures__/cardanoGetAddressDerivations.ts
  packages/connect/e2e/__fixtures__/cardanoGetNativeScriptHash.ts
  packages/connect/e2e/__fixtures__/cardanoSignTransaction.ts
  packages/connect/src/api/ethereum/api/ethereumSignMessage.ts
  packages/connect/src/api/ethereum/api/ethereumSignTransaction.ts
  packages/connect/src/api/ethereum/api/ethereumSignTypedData.ts
  packages/connect/src/api/ethereum/ethereumDefinitions.ts
  packages/connect/src/api/ethereum/ethereumSignTx.ts
  packages/connect/src/constants/index.ts
  packages/connect/src/device/DeviceCommands.ts
  packages/connect/src/types/device.ts
  packages/protobuf/package.json
  packages/protobuf/src/index.ts
Labels: monorepo

#11221 chore(suite-native): ignore useless warning in LogBox
  suite-native/app/src/App.tsx
  suite-native/app/src/LogBox.ts
Labels: mobile-app

#11328 Fix database migration test
  packages/suite-web/e2e/tests/suite/database-migration.test.ts
Labels: e2e

#11325 chore(suite-native): analytics for add new account
  suite-native/analytics/src/constants.ts
  suite-native/analytics/src/events.ts
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile-app

#11329 chore(suite-native): testnet cannot be imported as bitcoin account
  suite-native/intl/src/en.ts
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
Labels: mobile-app

#11318 feat(suite-native): token definitions redux logic
  packages/suite-desktop/tsconfig.json
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/TxDetailModal.tsx
  packages/suite/src/components/wallet/TransactionItem/TransactionItem.tsx
  suite-common/wallet-core/src/index.ts
  suite-common/wallet-core/src/token-definitions/tokenDefinitionsSelectors.ts
  suite-common/wallet-core/src/transactions/transactionsReducer.ts
  suite-native/fiat-rates/src/fiatRatesMiddleware.ts
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-import/src/screens/AccountImportLoadingScreen.tsx
  suite-native/state/package.json
  suite-native/state/src/reducers.ts
  suite-native/state/src/store.ts
  suite-native/state/tsconfig.json
  suite-native/token-definitions/package.json
  suite-native/token-definitions/src/index.ts
  suite-native/token-definitions/src/tokenDefinitionsMiddleware.ts
  suite-native/token-definitions/tsconfig.json
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
  tsconfig.json
  yarn.lock
Labels: mobile-app

#11332 feat(suite-native): Add coin behind feature flag
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AddAccountsButton.tsx
  suite-native/accounts/src/components/SearchableAccountsListScreenHeader.tsx
  suite-native/accounts/src/index.ts
  suite-native/accounts/src/useIsAddCoinAccountEnabled.ts
  suite-native/accounts/tsconfig.json
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  yarn.lock
Labels: mobile-app

#11339 chore(suite-native): bump app version
  suite-native/app/package.json
Labels: mobile-app

#11282 Add new coin 4 - Polish UI/UX
  suite-common/icons/assets/icons/checkCircleSolid.svg
  suite-common/icons/src/icons.ts
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/accounts/src/components/AddAccountsButton.tsx
  suite-native/accounts/src/components/SearchableAccountsListScreenHeader.tsx
  suite-native/atoms/src/Pictogram.tsx
  suite-native/atoms/src/SelectableItem.tsx
  suite-native/intl/src/en.ts
  suite-native/module-accounts-management/src/components/CoinPriceCard.tsx
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
  suite-native/module-accounts-management/src/screens/AccountDetailContentScreen.tsx
  suite-native/module-accounts-management/src/screens/AccountDetailLoadingScreen.tsx
  suite-native/module-accounts-management/src/screens/AccountDetailScreen.tsx
  suite-native/module-accounts-management/src/screens/AccountsScreen.tsx
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
  suite-native/module-add-accounts/src/screens/AddCoinAccountScreen.tsx
  suite-native/module-receive/src/screens/ReceiveAccountsScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/receive/src/screens/ReceiveModalScreen.tsx
  suite-native/transactions/src/components/TransactionsEmptyState.tsx
Labels: mobile-app

#11342 feat(coinmarket): hide unrecognized tokens in trade section
  packages/suite/src/hooks/wallet/useCoinmarketExchangeForm.ts
  packages/suite/src/hooks/wallet/useCoinmarketSellForm.ts
  packages/suite/src/types/wallet/coinmarketExchangeForm.ts
  packages/suite/src/types/wallet/coinmarketSellForm.ts
  packages/suite/src/utils/wallet/coinmarket/__fixtures__/coinmarketUtils.ts
  packages/suite/src/utils/wallet/coinmarket/__tests__/coinmarketUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/coinmarketUtils.ts
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoInput/SendCryptoSelect/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Inputs/CryptoInput/index.tsx
Labels: +Invity

#11335 feat(coinmarket): support Solana tokens in trade section
  packages/suite/src/utils/wallet/coinmarket/coinmarketUtils.ts
  packages/suite/src/utils/wallet/coinmarket/commonUtils.ts
  packages/suite/src/views/wallet/coinmarket/buy/components/BuyForm/Inputs/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoInput/SendCryptoSelect/index.tsx
  packages/suite/src/views/wallet/coinmarket/sell/components/SellForm/Inputs/CryptoInput/index.tsx
Labels: +Invity

#11371 Make commit message check work with other remotes
  .github/workflows/commit-messages-check.yml
Labels: ci
