Repository trezor/trezor-suite, pull requests merged in 2024-07, with the labels that each got.

#13038 fix(suite): evm bump fee ts5
  packages/suite/src/middlewares/suite/buttonRequestMiddleware.ts
Labels: release

#12967 feat(suite-native): device switcher can scroll
  suite-native/device-manager/src/components/DeviceList.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/device-manager/src/components/DeviceManagerModal.tsx
Labels: mobile

#12889 feat(suite-native): handle pin by state, not button requests
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/device-authorization/package.json
  suite-native/device-authorization/src/deviceAuthorizationSlice.ts
  suite-native/device-authorization/src/index.ts
  suite-native/device-authorization/src/utils.ts
  suite-native/device-authorization/tsconfig.json
  suite-native/device/package.json
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/device/src/middlewares/buttonRequestMiddleware.ts
  suite-native/device/tsconfig.json
  suite-native/module-connect-device/package.json
  suite-native/module-connect-device/src/components/ConnectDeviceScreenHeader.tsx
  suite-native/module-connect-device/src/components/ConnectingTrezorHelp.tsx
  suite-native/module-connect-device/src/components/PinFormControlButtons.tsx
  suite-native/module-connect-device/src/components/PinOnDevice.tsx
  suite-native/module-connect-device/src/navigation/ConnectDeviceStackNavigator.tsx
  suite-native/module-connect-device/tsconfig.json
  suite-native/state/package.json
  suite-native/state/src/reducers.ts
  suite-native/state/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: mobile

#13110 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/tr.json
  packages/suite/src/support/messages.ts
Labels: translations

#13122 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#13134 Crowdin translations update
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite/src/support/messages.ts
Labels: translations

#13139 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite/src/support/messages.ts
Labels: translations

#13135 test(suite-web): move timeout to the right call
  packages/suite-web/e2e/tests/wallet/pending-transactions.test.ts
Labels: e2e

#13144 Bump beta version to 24.8.0
  packages/suite/package.json
Labels: deployment

#13116 feat(coinmarket): default fiat currencies
  packages/suite/src/actions/wallet/__tests__/coinmarketBuyActions.test.ts
  packages/suite/src/actions/wallet/coinmarketBuyActions.ts
  packages/suite/src/constants/wallet/coinmarket/fiatCurrencies.ts
  packages/suite/src/constants/wallet/coinmarket/formDefaults.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketBuyForm.tsx
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketBuyFormDefaultValues.tsx
  packages/suite/src/reducers/wallet/__tests__/coinmarketReducer.test.ts
  packages/suite/src/types/coinmarket/coinmarket.ts
  packages/suite/src/types/coinmarket/coinmarketForm.ts
  packages/suite/src/types/wallet/coinmarketCommonTypes.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputFiat.tsx
Labels: feature, +Invity

#13079 feat(coinmarket): buy redesign - offers filter
  packages/suite/src/types/coinmarket/coinmarketForm.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputAccount.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputCountry.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputFiat.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputLabel.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputLoader.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputPaymentMethod.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInputs.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormOffer.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketHeader/CoinmarketHeader.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketHeader/CoinmarketHeaderFilter.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketHeader/CoinmarketHeaderSummary.tsx
  packages/suite/src/views/wallet/coinmarket/index.tsx
Labels: feature, +Invity, code

#12984 Uninitialized device directed to suite web
  suite-native/alerts/src/alertsAtoms.ts
  suite-native/alerts/src/components/AlertSheet.tsx
  suite-native/device/package.json
  suite-native/device/src/components/IncompatibleDeviceModalAppendix.tsx
  suite-native/device/src/components/IncompatibleFirmwareModalAppendix.tsx
  suite-native/device/src/components/UninitializedDeviceModalAppendix.tsx
  suite-native/device/src/hooks/useDetectDeviceError.tsx
  suite-native/device/tsconfig.json
  suite-native/intl/src/en.ts
  yarn.lock
Labels: mobile, UI

#13151 chore(suite-native): blacklist bsc on mobile
  suite-native/config/src/supportedNetworks.ts
Labels: mobile

#13170 chore(suite): add tutorial step to onboarding for TS5
  packages/suite/src/config/onboarding/steps.ts
  packages/suite/src/types/onboarding/index.ts
  packages/suite/src/utils/onboarding/__tests__/steps.test.ts
  packages/suite/src/utils/onboarding/steps.ts
Labels: onboarding, release

#13178 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ru.json
  packages/suite/src/support/messages.ts
Labels: translations

#13158 fix(suite-native): onboard and connect test
  suite-native/app/e2e/tests/onboardAndConnect.test.ts
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraph.tsx
Labels: mobile

#13203 fix(transport): correctly reference class instance method
  packages/transport/src/api/usb.ts
Labels: release

#13207 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite/src/support/messages.ts
Labels: translations

#13216 chore(suite): new-official-lngs-IT-PBR-TR
  packages/suite/src/config/suite/languages.ts
Labels: release

#13120 fix(mobile): fix wallet mobile transform
  suite-native/graph/src/slice.ts
  suite-native/storage/src/tests/utils.test.ts
  suite-native/storage/src/transforms/utils.ts
  suite-native/storage/src/transforms/walletTransforms.ts
Labels: mobile

#13244 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/sv.json
  packages/suite/src/support/messages.ts
Labels: translations

#13269 fix(connect): handle missing language binary
  packages/connect/src/device/Device.ts
Labels: release-native

#13255 fix(suite-native): unlock device mutex on callback rejection
  suite-native/device-mutex/src/requestDeviceAccess.ts
  suite-native/device-mutex/src/tests/DeviceAccessMutex.test.ts
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/module-connect-device/src/components/PinFormControlButtons.tsx
  suite-native/module-connect-device/src/screens/ConnectAndUnlockDeviceScreen.tsx
  suite-native/module-send/src/sendFormThunks.ts
  suite-native/receive/src/hooks/useAccountReceiveAddress.tsx
Labels: mobile

#13289 fix(suite-native): e2e tests always install yarn
  .github/workflows/test-suite-native-e2e-android.yml
Labels: mobile

#13301 ci(suite-native): nightly e2e tests
  .github/workflows/test-suite-native-e2e-android.yml
Labels: mobile

#13321 feat(suite-native): incorrect passphrase copy
  suite-native/alerts/src/alertsAtoms.ts
  suite-native/intl/src/en.ts
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
  suite-native/receive/src/hooks/useAccountReceiveAddress.tsx
Labels: mobile

#13305 feat(suite-native): Passphrase UI pimping
  suite-native/atoms/src/AlertBox.tsx
  suite-native/atoms/src/ListItem/BottomSheetListItem.tsx
  suite-native/atoms/src/index.ts
  suite-native/device/package.json
  suite-native/device/src/components/UninitializedDeviceModalAppendix.tsx
  suite-native/device/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-authorize-device/src/assets/passphrase/QuestionMarks.tsx
  suite-native/module-authorize-device/src/assets/passphrase/questionMarks.png
  suite-native/module-authorize-device/src/components/passphrase/EmptyWalletInfoSheet.tsx
  suite-native/module-authorize-device/src/components/passphrase/PassphraseScreenHeader.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseEmptyWalletScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseFormScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseVerifyEmptyWalletScreen.tsx
  yarn.lock
Labels: mobile

#12523 feat(suite-native) Device switcher with fiat balance
  suite-native/device-manager/package.json
  suite-native/device-manager/src/components/WalletItem.tsx
  suite-native/device-manager/src/components/WalletList.tsx
  suite-native/device-manager/tsconfig.json
  suite-native/device/package.json
  suite-native/device/src/selectors.ts
  suite-native/device/src/utils.ts
  suite-native/device/tsconfig.json
  yarn.lock
Labels: mobile

#13246 Fix/native/passphrase flow errors
  suite-native/device-authorization/src/deviceAuthorizationSlice.ts
  suite-native/device-authorization/src/passphraseThunks.ts
  suite-native/module-authorize-device/src/components/passphrase/PassphraseScreenHeader.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseConfirmOnTrezorScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseEnterOnTrezorScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseLoadingScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseVerifyEmptyWalletScreen.tsx
  suite-native/module-authorize-device/src/useRedirectOnPassphraseCompletion.ts
Labels: mobile

#13320 fix(suite-native): passphrase submit button is never hidden behind ke…
  suite-native/module-authorize-device/src/components/passphrase/PassphraseForm.tsx
  suite-native/navigation/src/components/ScreenContentWrapper.tsx
  suite-native/navigation/src/components/ScrollViewContext.tsx
  suite-native/navigation/src/index.ts
Labels: mobile

#13352 feat(suite-native): dashboard ui fixes
  suite-native/intl/src/en.ts
  suite-native/module-home/src/screens/HomeScreen/components/EmptyPortfolioCrossroads.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyPortfolioTrackerState.tsx
Labels: mobile

#13343 Fix/native/remove passphrase device on pin cancel
  suite-native/module-authorize-device/src/components/connect/ConnectDeviceScreenHeader.tsx
  suite-native/module-authorize-device/src/components/connect/ConnectDeviceScreenView.tsx
  suite-native/module-authorize-device/src/components/connect/PinOnDevice.tsx
  suite-native/module-authorize-device/src/screens/connect/ConnectingDeviceScreen.tsx
  suite-native/module-authorize-device/src/screens/connect/PinScreen.tsx
Labels: mobile

#13296 feat(suite): Update bar traffic lights on mac
  packages/suite-desktop-core/src/app.ts
  packages/suite/src/components/onboarding/OnboardingLayout.tsx
  packages/suite/src/components/suite/TrafficLightOffset.tsx
  packages/suite/src/components/suite/layouts/LoggedOutLayout.tsx
  packages/suite/src/components/suite/layouts/SuiteLayout/MobileMenu/MobileMenu.tsx
  packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/Sidebar.tsx
  packages/suite/src/support/suite/styles/GlobalStyle.tsx
  packages/suite/src/views/suite/SwitchDevice/SwitchDeviceModal.tsx
Labels: build-desktop

#13398 fix(suite-native): passphrase warning height on all screens
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseFormScreen.tsx
Labels: mobile

#13357 feat(suite-native): analytics
  suite-native/analytics/src/constants.ts
  suite-native/analytics/src/events.ts
  suite-native/device-authorization/package.json
  suite-native/device-authorization/src/hooks/useHandleDuplicatePassphrase.ts
  suite-native/device-authorization/tsconfig.json
  suite-native/device-manager/src/components/AddHiddenWalletButton.tsx
  suite-native/module-authorize-device/package.json
  suite-native/module-authorize-device/src/components/passphrase/EnterPassphraseOnTrezorButton.tsx
  suite-native/module-authorize-device/src/components/passphrase/PassphraseForm.tsx
  suite-native/module-authorize-device/src/components/passphrase/PassphraseScreenHeader.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseConfirmOnTrezorScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseEmptyWalletScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseEnterOnTrezorScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseFormScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseLoadingScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseVerifyEmptyWalletScreen.tsx
  suite-native/module-authorize-device/tsconfig.json
  yarn.lock
Labels: mobile

#13395 Fix/native/passphrase form navigation
  suite-native/device-authorization/src/hooks/useHandleDeviceRequestsPassphrase.ts
  suite-native/device-authorization/src/hooks/useHandlePassphraseMismatch.tsx
  suite-native/device-authorization/src/index.ts
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseConfirmOnTrezorScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseEnterOnTrezorScreen.tsx
  suite-native/module-authorize-device/src/useRedirectOnPassphraseCompletion.ts
Labels: mobile

#13401 Install regular firmware after clicking the respective button in onboarding
  packages/suite/src/components/firmware/FirmwareInitial.tsx
Labels: bug, onboarding, build-desktop

#13424 fix(suite-native): passphrase UI tweaks
  suite-native/module-authorize-device/src/components/passphrase/PassphraseForm.tsx
  suite-native/module-authorize-device/src/components/passphrase/PassphraseScreenHeader.tsx
Labels: mobile

#13428 chore(suite-native): bump app version to 24.8.0
  suite-native/app/package.json
Labels: mobile

#13429 chore(suite-native): remove passphrase FF
  suite-native/app/package.json
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
Labels: mobile

#13434 fix(suite): removing obsolete security check copy
  packages/suite/src/support/messages.ts
  packages/suite/src/views/dashboard/components/PortfolioCard/components/EmptyWallet.tsx
Labels: build-desktop

#13437 Fix/native/add new account visibility
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
Labels: mobile

#13513 chore(suite): remove duplicated file
  packages/suite/src/utils/wallet/reviewTransactionUtils.ts
Labels: code

#13564 feat(analytics): start reporting font scale and pixel density
  suite-native/analytics/src/events.ts
  suite-native/app/src/hooks/useReportAppInitToAnalytics.ts
Labels: data, mobile

#13569 fix(suite-native): handle font scale to make elements visible
  suite-native/device-manager/src/components/DeviceAction.tsx
  suite-native/device-manager/src/components/DeviceItem/DeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceList.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
Labels: mobile, UI, accessibility

#13568 chore(suite-native): cancel pin only if it was requested
  suite-native/module-authorize-device/src/components/connect/ConnectDeviceScreenHeader.tsx
Labels: mobile
