Repository trezor/trezor-suite, pull requests merged in 2024-03, with the labels that each got.

#11373 chore(suite-native): delete always falsy condition
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraph.tsx
Labels: low hanging fruit, mobile-app

#11401 fix(suite-native): mock zlib for native bundle
  suite-native/app/metro.config.js
Labels: mobile-app

#11388 fix(suite-native): prevent biometrics throttling
  suite-native/biometrics/src/components/BiometricOverlay.tsx
  suite-native/biometrics/src/useBiometrics.tsx
Labels: mobile-app

#11409 Chore/release cherry picks
  suite-native/app/app.config.ts
  suite-native/app/metro.config.js
  suite-native/app/package.json
  suite-native/biometrics/src/components/BiometricOverlay.tsx
  suite-native/biometrics/src/useBiometrics.tsx
  suite-native/module-dev-utils/package.json
  suite-native/navigation/package.json
  yarn.lock
Labels: mobile-app

#11397 chore: add prebuild as root script
  package.json
Labels: mobile-app

#11396 fix(coinmarket): Fix max limit message
  packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/List/BuyQuote.tsx
Labels: +Invity

#11449 fix(wallet-utils): do not add unstake amount
  suite-common/wallet-utils/src/accountUtils.ts
  suite-common/wallet-utils/src/transactionUtils.ts
Labels: release

#11452 chore(suite-data): update tor to 0.4.8.10
  packages/suite-data/files/bin/tor/linux-arm64/tor
  packages/suite-data/files/bin/tor/linux-x64/tor
  packages/suite-data/files/bin/tor/mac-arm64/tor
  packages/suite-data/files/bin/tor/mac-x64/tor
  packages/suite-data/files/bin/tor/update.sh
  packages/suite-data/files/bin/tor/win-x64/tor.exe
Labels: tor

#11451 Feat/include tokens
  packages/suite/src/support/messages.ts
  suite-common/wallet-config/src/networksConfig.ts
Labels: release

#11456 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#11458 feat(suite-native): enable add coin feature flag
  suite-native/feature-flags/src/featureFlagsSlice.ts
Labels: mobile-app

#11453 chore(suite): remove polygon from debug mode
  packages/suite/src/components/suite/modals/ConfirmEvmExplanationModal.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/index.tsx
  packages/suite/src/views/wallet/receive/components/FreshAddress.tsx
  packages/suite/src/views/wallet/send/components/Outputs/index.tsx
  suite-common/wallet-config/src/networksConfig.ts
Labels: release

#11463 Bump beta version to 24.4.0
  packages/suite/package.json
Labels: deployment

#11472 fix(suite): align custom firmware modal correctly
  packages/suite/src/views/firmware/FirmwareCustom.tsx
Labels: release

#11495 fix(suite-native): app crashes on graph
  suite-native/atoms/src/Text.tsx
  suite-native/graph/src/components/GraphError.tsx
  suite-native/intl/src/en.ts
  suite-native/react-native-graph/src/AnimatedLineGraph.tsx
Labels: mobile-app

#11504 feat(suite-native): show toast on device cancel
  suite-native/intl/src/en.ts
  suite-native/receive/src/hooks/useAccountReceiveAddress.tsx
Labels: mobile-app

#11509 Feat/discreet text improvements
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/atoms/src/DiscreetText.tsx
  suite-native/atoms/src/DiscreetText/DiscreetCanvas.tsx
  suite-native/atoms/src/DiscreetText/DiscreetText.tsx
  suite-native/atoms/src/DiscreetText/DiscreetTextTrigger.tsx
  suite-native/atoms/src/DiscreetText/useDiscreetMode.ts
  suite-native/atoms/src/index.ts
  suite-native/formatters/src/components/FiatBalanceFormatter.tsx
  suite-native/module-accounts-management/src/components/AccountDetailCryptoValue.tsx
  suite-native/module-accounts-management/src/components/AccountDetailGraphHeader.tsx
  suite-native/module-accounts-management/src/components/AccountDetailTokenHeader.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraphHeader.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx
Labels: mobile-app

#11517 fix(suite-native): periodic token definitions check
  suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunks.ts
  suite-native/app/src/initActions.ts
Labels: mobile-app

#11513 chore(suite):fix sign and verify test
  packages/suite-web/e2e/tests/wallet/sign-and-verify.test.ts
Labels: e2e, low hanging fruit

#11243 Suite - Implement device translations (only settings for Beta)
  packages/connect/src/api/changeLanguage.ts
  packages/connect/src/data/config.ts
  packages/suite/src/actions/settings/deviceSettingsActions.ts
  packages/suite/src/components/suite/notifications/NotificationRenderer/NotificationRenderer.tsx
  packages/suite/src/constants/suite/anchors.ts
  packages/suite/src/hooks/suite/useDevice.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/SettingsDevice/ChangeLanguage.tsx
  packages/suite/src/views/settings/SettingsDevice/SettingsDevice.tsx
  suite-common/connect-init/src/connectInitThunks.ts
  suite-common/toast-notifications/src/types.ts
  suite-common/wallet-core/src/firmware/firmwareThunks.ts
Labels: translations

#11436 fix(suite-native): more simplified biometrics auth
  suite-native/biometrics/src/biometricsAtoms.ts
  suite-native/biometrics/src/components/BiometricOverlay.tsx
  suite-native/biometrics/src/components/BiometricsModalRenderer.tsx
  suite-native/biometrics/src/useBiometrics.tsx
Labels: mobile-app

#11538 fix(suite): distinguish account symbol for labelling addresses
  packages/suite/src/components/suite/labeling/AddressLabeling.tsx
  packages/suite/src/components/wallet/TransactionItem/TransactionTarget/TargetAddressLabel.tsx
  packages/suite/src/components/wallet/TransactionItem/TransactionTarget/TokenTransferAddressLabel.tsx
  packages/suite/src/components/wallet/TransactionItem/TransactionTarget/TransactionTarget.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Address/index.tsx
  suite-common/wallet-core/src/transactions/transactionsThunks.ts
  suite-common/wallet-utils/src/accountUtils.ts
Labels: release

#11542 fix(suite): do not fetch everstake data when staking not enabled
  packages/suite/src/hooks/suite/useEverstakePoolStats.ts
Labels: release

#11557 fix(suite): prevent graph tooltip from rendering during discovery.
  packages/suite/src/components/suite/graph/TransactionsGraph/GraphTooltipDashboard.tsx
Labels: bug, release

#11598 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#11593 Feat/native add coin UI polish
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/assets/src/components/Assets.tsx
  suite-native/atoms/src/SelectableItem.tsx
  suite-native/intl/src/en.ts
  suite-native/module-accounts-management/src/components/AccountDetailScreenHeader.tsx
  suite-native/module-accounts-management/src/components/TokenAccountDetailScreenSubHeader.tsx
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
  suite-native/module-accounts-management/src/screens/AccountDetailLoadingScreen.tsx
  suite-native/module-accounts-management/src/screens/AccountsScreen.tsx
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
  suite-native/module-add-accounts/src/screens/SelectAccountTypeScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyConnectedDeviceState.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
  suite-native/module-receive/src/screens/ReceiveAccountsScreen.tsx
  suite-native/navigation/src/components/GoBackIcon.tsx
  suite-native/navigation/src/index.ts
  suite-native/navigation/src/navigators.ts
  suite-native/receive/src/screens/ReceiveModalScreen.tsx
  suite-native/transactions/src/components/TransactionsEmptyState.tsx
Labels: mobile-app

#11603 fix(components): fix selector to select empty input
  packages/components/src/components/form/Input/Input.tsx
Labels: bug, components

#11552 chore(suite): reorganize media queries and selectors
  packages/suite/src/views/wallet/send/index.tsx
Labels: code

#11631 fix(suite-native): better back handling after add coin error
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
Labels: release, mobile-app

#11645 chore(suite-native): pimp useAddCoinAccount
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
Labels: mobile-app

#11648 fix(suite-native): app name
  suite-native/app/app.config.ts
Labels: mobile-app, release-native

#11651 fix(suite-native): fix thunk name
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile-app

#11635 feat(suite-native): do not allow to cancel PIN entry during discovery
  suite-native/intl/src/en.ts
  suite-native/module-connect-device/src/components/ConnectDeviceScreenHeader.tsx
Labels: mobile-app, release-native

#11650 Chore/release cherry picks
  suite-native/app/app.config.ts
  suite-native/intl/src/en.ts
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
  suite-native/module-connect-device/src/components/ConnectDeviceScreenHeader.tsx
Labels: mobile-app, release-native

#11638 feat(coinmarket): Add suite version header to Invity API calls
  packages/suite/src/services/suite/invityAPI.ts
Labels: +Invity

#11677 fix(suite-native): add account path index
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile-app

#11686 feat(suite-native): order accounts by networks
  suite-native/accounts/package.json
  suite-native/accounts/src/selectors.ts
  suite-native/accounts/src/tests/selectors.test.ts
  suite-native/accounts/src/utils.ts
  suite-native/accounts/tsconfig.json
  suite-native/config/package.json
  suite-native/config/src/supportedNetworks.ts
  suite-native/config/tsconfig.json
  yarn.lock
Labels: mobile-app

#11679 Skip CheckSeedStep when device is not initialized
  packages/suite/src/components/firmware/FirmwareInitial.tsx
  packages/suite/src/views/firmware/FirmwareCustom.tsx
Labels: bug, settings

#11680 chore(suite): unify background colors in firmware installation
  packages/suite/src/components/firmware/FirmwareProgressBar.tsx
Labels: UI

#11683 Add prompt to reconnect device to check seed step
  packages/suite/src/components/firmware/CheckSeedStep.tsx
  packages/suite/src/components/firmware/FirmwareInitial.tsx
Labels: bug, settings

#11704 fix(suite-native): env variables in expo
  suite-native/app/eas.json
Labels: mobile-app

#11707 Crowdin translations update
  packages/connect-explorer-theme/style.css
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite/src/support/messages.ts
Labels: translations

#11715 fix(suite-native): expo env
  suite-native/app/app.config.ts
Labels: mobile-app

#11682 fix(suite-native): fetch fiat rates of newly added account tokens
  packages/suite/src/actions/wallet/tokenActions.ts
  packages/suite/src/hooks/wallet/__fixtures__/useSendForm.ts
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/FiatInput/FiatSelect/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoInput/SendCryptoSelect/index.tsx
  packages/suite/src/views/wallet/coinmarket/savings/setup/index.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/Fiat.tsx
  packages/suite/src/views/wallet/send/components/Outputs/components/Amount/components/TokenSelect.tsx
  suite-common/wallet-core/src/fiat-rates/fiatRatesMiddleware.ts
  suite-common/wallet-core/src/fiat-rates/fiatRatesReducer.ts
  suite-common/wallet-core/src/fiat-rates/fiatRatesThunks.ts
  suite-native/module-accounts-import/src/screens/AccountImportLoadingScreen.tsx
Labels: mobile-app

#11722 chore(suite-native): remove add account feature flag
  suite-native/accounts/src/components/AddAccountsButton.tsx
  suite-native/accounts/src/index.ts
  suite-native/accounts/src/useIsAddCoinAccountEnabled.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
Labels: mobile-app

#11724 Fix/tiny font
  suite-native/atoms/src/DiscreetText/DiscreetText.tsx
  suite-native/module-accounts-management/src/components/AccountDetailCryptoValue.tsx
Labels: mobile-app

#11720 ref(suite-native): typed env
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
  suite-native/config/src/environment.ts
  suite-native/config/src/index.ts
  suite-native/config/src/jws.ts
Labels: mobile-app

#11728 fix(suite-native): define env for build
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
Labels: mobile-app

#11734 fix(suite-native): transaction detail header overflow
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx
Labels: mobile-app, release-native

#11731 fix(suite-native): development name
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
Labels: mobile-app

#11742 fix(mobile): fix env variables + build
  .github/workflows/suite-native_production_ci.yml
  suite-native/app/babel.config.js
  suite-native/app/package.json
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  yarn.lock
Labels: mobile-app

#11740 fix(connect): enable changeLanguage in initialize mode
  packages/connect/src/api/changeLanguage.ts
Labels: bug, connect

#11636 feat(coinmarket): Hide low fee option in sell
  packages/suite/src/hooks/wallet/useCoinmarketSellForm.ts
Labels: +Invity

#11799 chore(suite-native): remove unused env
  .github/workflows/suite-native_production_ci.yml
Labels: mobile-app

#11810 fix(suite-native): remove jws as env variable
  packages/env-utils/package.json
  packages/env-utils/src/envUtils.native.ts
  packages/env-utils/src/envUtils.ts
  packages/env-utils/src/index.ts
  packages/env-utils/src/types.ts
  packages/env-utils/tsconfig.json
  packages/env-utils/tsconfig.lib.json
  packages/suite-build/package.json
  packages/suite-build/tsconfig.json
  packages/suite-build/utils/env.ts
  suite-common/wallet-constants/src/index.ts
  suite-common/wallet-constants/src/jws.ts
  suite-common/wallet-core/src/token-definitions/tokenDefinitionsThunks.ts
  suite-native/app/.env.debug
  suite-native/app/.env.develop
  suite-native/app/.env.production
  suite-native/app/package.json
  suite-native/app/src/initActions.ts
  suite-native/app/tsconfig.json
  suite-native/config/src/environment.ts
  yarn.lock
Labels: mobile-app, build-desktop

#11820 Revert "chore(transport, trezor-user-env-link): remove cross-fetch"
  packages/transport/package.json
  packages/transport/src/utils/bridgeApiCall.ts
  packages/trezor-user-env-link/package.json
  packages/trezor-user-env-link/src/websocket-client.ts
  yarn.lock
Labels: dependencies

#11801 feat(coinmarket): hide fees column in quote list
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/List/BuyQuote.tsx
Labels: +Invity

#11832 chore(ci): add timeout to suite-desktop build jobs
  .github/workflows/build-desktop-apps.yml
Labels: build-desktop
