Repository trezor/trezor-suite, pull requests merged in 2024-06, with the labels that each got.

#12647 fix(suite): exchange currency
  packages/suite/src/actions/wallet/coinmarketExchangeActions.ts
  packages/suite/src/actions/wallet/constants/coinmarketExchangeConstants.ts
  packages/suite/src/hooks/wallet/useCoinmarketExchangeOffers.ts
  packages/suite/src/reducers/wallet/__tests__/coinmarketReducer.test.ts
  packages/suite/src/reducers/wallet/coinmarketReducer.ts
Labels: bug

#12679 Add new TS3 CA pubkeys and update timestamp
  packages/connect/src/data/deviceAuthenticityConfig.ts
Labels: release

#12605 feat(suite-desktop): rollout node bridge to 0% of users
  packages/suite-desktop-api/src/messages.ts
  packages/suite-desktop-core/src/index.d.ts
  packages/suite-desktop-core/src/modules/bridge.ts
  packages/suite/src/views/settings/SettingsDebug/TransportBackends.tsx
Labels: release

#12690 fix(suite-native): redundant graph time frame dispatch
  suite-native/graph/src/hooks.ts
Labels: mobile

#12533 fix(suite): card component bug
  packages/components/src/components/Card/Card.tsx
Labels: bug, components

#12697 fix(suite): select device model correctly
  packages/suite/src/views/firmware/FirmwareUpdate.tsx
Labels: bug, settings

#12698 fix(suite): fix condition for wipe warning
  packages/suite/src/views/firmware/FirmwareUpdate.tsx
Labels: bug

#12571 GitBook revision update
  packages/suite-data/src/guide/constants.ts
Labels: guide

#12735 feat(coinmarket): redesign exchange offers
  packages/suite/src/actions/wallet/__tests__/coinmarketExchangeActions.test.ts
  packages/suite/src/actions/wallet/coinmarketExchangeActions.ts
  packages/suite/src/hooks/wallet/coinmarket/offers/useCoinmarketExchangeOffers.ts
  packages/suite/src/reducers/wallet/__tests__/coinmarketReducer.test.ts
  packages/suite/src/reducers/wallet/coinmarketReducer.ts
  packages/suite/src/services/suite/invityAPI.ts
  packages/suite/src/types/coinmarket/coinmarket.ts
  packages/suite/src/types/coinmarket/coinmarketOffers.ts
  packages/suite/src/utils/wallet/coinmarket/__fixtures__/exchangeUtils.ts
  packages/suite/src/utils/wallet/coinmarket/__tests__/exchangeUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/coinmarketTypingUtils.ts
  packages/suite/src/utils/wallet/coinmarket/exchangeUtils.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketHeader/CoinmarketHeader.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketHeader/CoinmarketHeaderSummary.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffersItem.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketUtils/CoinmarketUtilsPrice.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/List/ExchangeQuote.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/List/ExchangeQuoteList.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/Offers/index.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/offers/index.tsx
Labels: feature, +Invity

#12742 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/tr.json
  packages/suite/src/support/messages.ts
Labels: translations

#12746 Bump beta version to 24.7.0
  packages/suite/package.json
Labels: deployment

#12747 feat(suite-native): enable demo screen in develop build
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
Labels: mobile

#12754 Crowdin translations update
  packages/suite-data/files/translations/af.json
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/da.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fi.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/he.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#12786 chore(connect-common): T3T1 support
  packages/connect-common/files/coins.json
Labels: release

#12713 fix(suite-native): e2e tests flakiness
  .github/workflows/test-suite-native-e2e-android.yml
  suite-native/app/.detoxrc.js
  suite-native/app/e2e/tests/invalidAccountsImport.test.ts
  suite-native/app/e2e/tests/onboardAndConnect.test.ts
Labels: mobile

#12766 chore(suite): setup ev certificate signing for windows app
  packages/suite-desktop-core/scripts/hardwareToken.cfg
  packages/suite-desktop-core/scripts/jsign-6.0.jar
  packages/suite-desktop-core/scripts/sign-windows.ts
  packages/suite-desktop/electron-builder-config.js
Labels: release, build-desktop

#12804 Move ReconnectDevicePrompt to FirmwareInstallation
  packages/suite/src/components/firmware/FirmwareInstallation.tsx
  packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx
  packages/suite/src/views/firmware/FirmwareModal.tsx
  packages/suite/src/views/onboarding/steps/FirmwareStep.tsx
Labels: bug, onboarding, release

#12808 chore(connect-common): update firmware binaries to 2.7.2
  packages/connect-common/files/firmware/t2b1/releases.json
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.7.0-bitcoinonly.bin
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.7.0.bin
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.7.2-bitcoinonly.bin
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.7.2.bin
  packages/connect-common/files/firmware/t2t1/releases.json
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.7.0-bitcoinonly.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.7.0.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.7.2-bitcoinonly.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.7.2.bin
  packages/connect-common/files/firmware/t3t1/releases.json
  packages/connect-common/files/firmware/t3t1/trezor-t3t1-2.7.2-bitcoinonly.bin
  packages/connect-common/files/firmware/t3t1/trezor-t3t1-2.7.2.bin
Labels: release

#12837 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#12855 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ja.json
  packages/suite/src/support/messages.ts
Labels: translations

#12870 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite/src/support/messages.ts
Labels: translations

#12876 Fix/native/cancel pin on passphrase
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/app/package.json
  suite-native/app/src/navigation/AppTabNavigator.tsx
  suite-native/app/tsconfig.json
  suite-native/device/src/hooks/useHandleDeviceRequestsPassphrase.ts
  suite-native/device/src/index.ts
  suite-native/module-connect-device/package.json
  suite-native/module-connect-device/src/components/ConnectDeviceScreenHeader.tsx
  suite-native/module-connect-device/src/components/PinOnDevice.tsx
  suite-native/module-connect-device/tsconfig.json
  suite-native/module-passphrase/src/components/EnterPassphraseOnTrezorButton.tsx
  suite-native/module-passphrase/src/components/PassphraseScreenHeader.tsx
  suite-native/passphrase/src/index.ts
  suite-native/passphrase/src/passphraseSlice.ts
  suite-native/passphrase/src/useHandleDeviceRequestsPassphrase.ts
  yarn.lock
Labels: mobile

#12885 Revert "Fix/native/cancel pin on passphrase (#12876)"
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/app/package.json
  suite-native/app/src/navigation/AppTabNavigator.tsx
  suite-native/app/tsconfig.json
  suite-native/device/src/hooks/useHandleDeviceRequestsPassphrase.ts
  suite-native/device/src/index.ts
  suite-native/module-connect-device/package.json
  suite-native/module-connect-device/src/components/ConnectDeviceScreenHeader.tsx
  suite-native/module-connect-device/src/components/PinOnDevice.tsx
  suite-native/module-connect-device/tsconfig.json
  suite-native/module-passphrase/src/components/EnterPassphraseOnTrezorButton.tsx
  suite-native/module-passphrase/src/components/PassphraseScreenHeader.tsx
  suite-native/passphrase/src/index.ts
  suite-native/passphrase/src/passphraseSlice.ts
  suite-native/passphrase/src/useHandleDeviceRequestsPassphrase.ts
  yarn.lock
Labels: mobile

#12888 chore(suite-native): global passphrase hook
  suite-native/app/package.json
  suite-native/app/src/navigation/AppTabNavigator.tsx
  suite-native/app/tsconfig.json
  suite-native/device/src/hooks/useHandleDeviceRequestsPassphrase.ts
  suite-native/device/src/index.ts
  suite-native/module-passphrase/src/components/EnterPassphraseOnTrezorButton.tsx
  suite-native/module-passphrase/src/components/PassphraseScreenHeader.tsx
  suite-native/passphrase/src/index.ts
  suite-native/passphrase/src/passphraseSlice.ts
  suite-native/passphrase/src/useHandleDeviceRequestsPassphrase.ts
  yarn.lock
Labels: mobile

#12835 fix(suite-native): loading spinner animation
  suite-native/atoms/src/Spinner/Spinner.tsx
  suite-native/atoms/src/Spinner/refresh-spinner-end-success.json
  suite-native/atoms/src/Spinner/refresh-spinner-end-warning.json
  suite-native/atoms/src/Spinner/refresh-spinner-middle.json
  suite-native/atoms/src/Spinner/refresh-spinner-start.json
  suite-native/module-accounts-import/src/components/AccountImportLoader.tsx
Labels: mobile

#12928 fix(suite-native): error on failed initStore
  suite-native/state/package.json
  suite-native/state/src/StoreProvider.tsx
  yarn.lock
Labels: mobile

#12953 chore(suite): simplify OptionWithContent
  packages/suite/src/views/onboarding/steps/SelectBackupType/LegacyOptions.tsx
  packages/suite/src/views/onboarding/steps/SelectBackupType/OptionWithContent.tsx
  packages/suite/src/views/onboarding/steps/SelectBackupType/ShamirOptions.tsx
Labels: onboarding

#12970 fix(suite): break lines correctly for legacy addresses
  packages/suite/src/components/suite/DeviceDisplay/DisplayPaginatedText.tsx
  packages/suite/src/components/suite/DeviceDisplay/__tests__/parseTextToPagesAndLines.test.ts
  packages/suite/src/components/suite/DeviceDisplay/parseTextToPagesAndLines.ts
Labels: bug

#12956 fix(suite-native): fix initial selection of portfolio tracker device
  suite-native/device/src/middlewares/deviceMiddleware.ts
Labels: bug, mobile

#12978 Add docs on wsl development
  README.md
  docs/SUMMARY.md
  docs/misc/development-on-windows.md
Labels: documentation

#12996 fix:(blockchain-link): omit solana foreign tx effects
  packages/blockchain-link-utils/src/solana.ts
  packages/blockchain-link-utils/src/tests/fixtures/solana.ts
  packages/blockchain-link-utils/src/tests/solana.test.ts
Labels: build-desktop

#12986 fix(suite-native): correct detection of selectIsDeviceUsingPassphrase
  suite-common/wallet-core/src/device/deviceReducer.ts
Labels: mobile

#13021 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/zh.json
Labels: translations

#13030 chore(suite): upgrade crowdin-cli
  packages/suite/package.json
  yarn.lock
Labels: dependencies, translations

#13058 feat(suite-native): Coin Enabling feature flag
  suite-native/discovery/package.json
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/discovery/tsconfig.json
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-dev-utils/src/components/DiscoveryCoinsFilter.tsx
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  yarn.lock
Labels: mobile

#13063 chore(suite-native): disable IsCoinEnablingActive for everyone by default
  suite-native/feature-flags/src/featureFlagsSlice.ts
Labels: mobile

#13062 test(suite-web): increase timeout to avoid flakiness
  packages/suite-web/e2e/tests/wallet/pending-transactions.test.ts
Labels: e2e

#13073 feat(suite-native): passphrase loading has subtitle
  suite-native/intl/src/en.ts
  suite-native/module-passphrase/src/screens/PassphraseLoadingScreen.tsx
Labels: mobile

#13068 fix(suite-native): feature gate for view only setting
  suite-native/module-settings/src/components/ApplicationSettings.tsx
Labels: mobile

#13067 feat(suite-native): passphrase on device only when possible
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/module-passphrase/src/components/PassphraseForm.tsx
Labels: mobile
