Repository trezor/trezor-suite, pull requests merged in 2024-04, with the labels that each got.

#11804 fix(coinmarket): fix bad token contract selected in exchange
  packages/suite/src/views/wallet/coinmarket/exchange/components/ExchangeForm/Inputs/SendCryptoInput/SendCryptoSelect/index.tsx
Labels: +Invity

#11843 fix(suite-native): spacing on graph balance
  suite-native/formatters/src/components/FiatBalanceFormatter.tsx
Labels: mobile-app

#11812 chore(ci): faster suite web e2e
  .github/workflows/build-test-suite-web-e2e.yaml
  docker/docker-compose.suite-ci.yml
  packages/connect-iframe/package.json
  packages/connect-web/package.json
  packages/suite-data/package.json
  packages/suite-web/e2e/run_tests.ts
  packages/suite-web/package.json
  suite-common/message-system/package.json
  yarn.lock
Labels: e2e, build-desktop

#11864 chore(electron): update electron, electron-builder/updater
  package.json
  packages/connect-examples/electron-main-process/package.json
  packages/connect-examples/electron-renderer-with-assets/package.json
  packages/connect-examples/electron-renderer-with-popup/package.json
  packages/suite-desktop-api/package.json
  packages/suite-desktop-core/package.json
  packages/suite-desktop/package.json
  yarn.lock
Labels: build-desktop

#11904 ci: remove build:libs from stable codesign build
  ci/build.yml
Labels: deployment

#11821 Test/detox e2e
  .github/workflows/native-test-e2e-android.yml
  docker/docker-compose.suite-native-ci.yml
  packages/transport/src/utils/applyBridgeApiCallHeaders.native.ts
  packages/transport/src/utils/applyBridgeApiCallHeaders.ts
  packages/transport/src/utils/applyContentTypeHeader.ts
  packages/transport/src/utils/bridgeApiCall.ts
  suite-native/app/.detoxrc.js
  suite-native/app/app.config.ts
  suite-native/app/e2e/README.md
  suite-native/app/e2e/jest.config.js
  suite-native/app/e2e/tests/onboardAndConnect.test.ts
  suite-native/app/e2e/utils.ts
  suite-native/app/package.json
  suite-native/app/src/LogBox.ts
  suite-native/module-home/src/screens/HomeScreen/components/BiometricsBottomSheet.tsx
  yarn.lock
Labels: mobile-app

#11905 fix(suite-native): expo sentry plugin
  suite-native/app/app.config.ts
Labels: mobile-app

#11846 feat(suite-native): token discovery analytics
  packages/analytics/src/types.ts
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/token-definitions/tokenDefinitionsSelectors.ts
  suite-native/analytics/src/events.ts
  suite-native/discovery/src/discoverySelectors.ts
  suite-native/discovery/src/discoveryThunks.ts
Labels: data, mobile-app

#11818 chore(suite): stop using JWS public key as environment variable
  packages/suite-build/configs/base.webpack.config.ts
  packages/suite-build/package.json
  packages/suite-build/tsconfig.json
  packages/suite-build/utils/env.ts
  packages/suite/src/actions/suite/__tests__/initAction.test.ts
  packages/suite/src/actions/suite/initAction.ts
  suite-common/message-system/src/__fixtures__/messageSystemActions.ts
  suite-common/message-system/src/__tests__/messageSystemActions.test.ts
  suite-common/message-system/src/messageSystemThunks.ts
  suite-common/wallet-constants/src/jws.ts
  suite-native/app/package.json
  suite-native/app/src/initActions.ts
  suite-native/app/tsconfig.json
  yarn.lock
Labels: build-desktop

#11910 feat(suite-native): Simplify biometrics UI logic
  suite-native/biometrics/package.json
  suite-native/biometrics/src/components/BiometricOverlay.tsx
  suite-native/biometrics/src/components/BiometricsIcon.tsx
  suite-native/biometrics/src/components/BiometricsIcons.tsx
  suite-native/biometrics/src/index.ts
  suite-native/biometrics/src/tests/utils.test.ts
  suite-native/biometrics/src/useBiometricsSettings.ts
  suite-native/biometrics/src/utils.ts
  suite-native/intl/src/en.ts
  suite-native/module-home/src/screens/HomeScreen/components/BiometricsBottomSheet.tsx
  suite-native/module-settings/src/screens/SettingsPrivacyAndSecurity.tsx
Labels: mobile-app

#11933 feat(suite-native): add possibility to enable view-only for connected device
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/intl/src/en.ts
  suite-native/module-settings/package.json
  suite-native/module-settings/src/screens/SettingsViewOnly.tsx
  suite-native/module-settings/tsconfig.json
  yarn.lock
Labels: mobile-app

#10762 refactor(connect): optional token symbol
  packages/blockchain-link-types/src/blockbook-api.ts
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/IODetails/IODetails.tsx
  packages/suite/src/components/wallet/TransactionItem/TransactionHeader.tsx
  packages/suite/src/hooks/suite/useFiatFromCryptoValue.ts
  suite-common/wallet-core/src/accounts/accountsThunks.ts
  suite-common/wallet-core/src/blockchain/blockchainThunks.ts
  suite-common/wallet-utils/src/accountUtils.ts
  suite-common/wallet-utils/src/exportTransactionsUtils.ts
Labels: connect, mobile-app, EVM

#11865 Feat/production apk
  .github/workflows/suite-native_production_ci.yml
  suite-native/app/eas-post-success.sh
  suite-native/app/eas.json
  suite-native/app/package.json
  suite-native/app/upload-to-firebase.sh
Labels: mobile-app

#11941 chore(suite-native): allow passphrase on debug
  suite-native/feature-flags/src/featureFlagsSlice.ts
Labels: mobile-app

#11928 Feat/receive remember
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/atoms/src/Button/Button.tsx
  suite-native/intl/src/en.ts
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/receive/package.json
  suite-native/receive/src/components/ReceiveAccount.tsx
  suite-native/receive/src/components/ReceiveAddressCard.tsx
  suite-native/receive/src/components/ShowAddressButtons.tsx
  suite-native/receive/src/components/ShowAddressViewOnlyBottomSheet.tsx
  suite-native/receive/src/components/UnverifiedAddress.tsx
  suite-native/receive/src/components/UnverifiedAddressWarning.tsx
  suite-native/receive/src/hooks/useAccountReceiveAddress.tsx
  suite-native/receive/tsconfig.json
  yarn.lock
Labels: mobile-app

#11954 fix(suite): hide devkit flag during installation of custom firmware
  packages/suite/src/components/firmware/FirmwareOffer.tsx
Labels: settings

#11642 fix(blockchain-link): emit disconnect on every socket disconnect
  packages/blockchain-link/src/workers/baseWebsocket.ts
Labels: connect

#11952 fix(suite): fix labeling layout
  packages/suite/src/components/suite/labeling/MetadataLabeling/MetadataLabeling.tsx
Labels: bug, labelling, UI

#11961 fix(suite-native): correct onboarding animation height
  suite-native/module-onboarding/src/screens/ConnectTrezorScreen.tsx
Labels: mobile-app

#11962 feat(suite-native): pineapple should be included
  suite-common/icons/src/components/CryptoIconWithPercentage.tsx
  suite-common/icons/src/components/PizzaIcon.tsx
  suite-common/icons/src/components/pizza1.png
  suite-common/icons/src/components/pizza2.png
  suite-common/icons/src/components/pizza3.png
Labels: mobile-app

#11970 fix(components): set handle cursor to default when switch is disabled
  packages/components/src/components/form/Switch/Switch.tsx
Labels: bug, components

#11870 Bump beta version to 24.5.0
  packages/suite/package.json
Labels: deployment

#11971 chore(suite-native): remove unused duplicate file
  suite-native/helpers/src/utils.ts
Labels: mobile-app

#11989 feat(suite-native): passphrase toggle
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/module-dev-utils/package.json
  suite-native/module-dev-utils/src/components/DevicePassphraseSwitch.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/module-dev-utils/tsconfig.json
  yarn.lock
Labels: mobile-app

#11990 feat(suite-native): upgrade rn
  package.json
  packages/styles/package.json
  suite-common/icons/package.json
  suite-native/accounts/package.json
  suite-native/alerts/package.json
  suite-native/app/package.json
  suite-native/assets/package.json
  suite-native/atoms/package.json
  suite-native/biometrics/package.json
  suite-native/device-manager/package.json
  suite-native/device/package.json
  suite-native/feature-flags/package.json
  suite-native/formatters/package.json
  suite-native/graph/package.json
  suite-native/helpers/package.json
  suite-native/intl/package.json
  suite-native/message-system/package.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-management/package.json
  suite-native/module-add-accounts/package.json
  suite-native/module-connect-device/package.json
  suite-native/module-dev-utils/package.json
  suite-native/module-home/package.json
  suite-native/module-onboarding/package.json
  suite-native/module-passphrase/package.json
  suite-native/module-receive/package.json
  suite-native/module-settings/package.json
  suite-native/navigation/package.json
  suite-native/notifications/package.json
  suite-native/qr-code/package.json
  suite-native/react-native-graph/package.json
  suite-native/receive/package.json
  suite-native/state/package.json
  suite-native/storage/package.json
  suite-native/theme/package.json
  suite-native/transactions/package.json
  suite-native/video-assets/package.json
  yarn.lock
Labels: mobile-app

#11980 Feat/send module init
  suite-native/app/package.json
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/app/tsconfig.json
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
  suite-native/module-send/package.json
  suite-native/module-send/src/index.ts
  suite-native/module-send/src/navigation/SendStackNavigator.tsx
  suite-native/module-send/src/screens/SendAccountsScreen.tsx
  suite-native/module-send/src/screens/SendFormScreen.tsx
  suite-native/module-send/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  tsconfig.json
  yarn.lock
Labels: mobile-app

#11987 fix(suite-native): fix reading system color scheme
  suite-native/app/app.config.ts
Labels: mobile-app

#11984 Feat/form UI
  suite-native/intl/src/en.ts
  suite-native/module-passphrase/package.json
  suite-native/module-passphrase/src/components/PassphraseForm.tsx
  suite-native/module-passphrase/src/screens/PassphraseFormScreen.tsx
  suite-native/module-passphrase/tsconfig.json
  yarn.lock
Labels: mobile-app

#11992 fix(suite-native): coin discovery analytics objectless structure
  packages/analytics/src/types.ts
  suite-native/analytics/src/constants.ts
  suite-native/analytics/src/events.ts
  suite-native/discovery/package.json
  suite-native/discovery/src/discoverySelectors.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/discovery/tsconfig.json
  yarn.lock
Labels: mobile-app

#10954 GitBook revision update
  packages/suite-data/src/guide/constants.ts
Labels: guide

#12006 feat(suite-native): passphrase confirm on device sheet
  suite-native/intl/src/en.ts
  suite-native/module-passphrase/package.json
  suite-native/module-passphrase/src/assets/DeviceTS3Svg.tsx
  suite-native/module-passphrase/src/components/ConfirmOnDeviceBottomSheet.tsx
  suite-native/module-passphrase/tsconfig.json
  yarn.lock
Labels: mobile-app

#12026 chore(suite-native): upgrade RN reanimated
  suite-common/icons/package.json
  suite-native/accounts/package.json
  suite-native/alerts/package.json
  suite-native/app/package.json
  suite-native/assets/package.json
  suite-native/atoms/package.json
  suite-native/device-manager/package.json
  suite-native/graph/package.json
  suite-native/message-system/package.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-management/package.json
  suite-native/module-connect-device/package.json
  suite-native/module-passphrase/package.json
  suite-native/notifications/package.json
  suite-native/react-native-graph/package.json
  suite-native/receive/package.json
  suite-native/test-utils/package.json
  suite-native/toasts/package.json
  suite-native/transactions/package.json
  yarn.lock
Labels: mobile-app

#12030 chore(suite-naive): report graph errors to sentry
  suite-native/graph/package.json
  suite-native/graph/src/hooks.ts
  yarn.lock
Labels: mobile-app

#12038 fix(suite-native): correct AlertSheet layout
  suite-native/alerts/src/components/AlertSheet.tsx
Labels: mobile-app

#12033 chore(suite): add SettingsSectionItem
  packages/suite-web/e2e/tests/settings/t2t1-device-settings.test.ts
  packages/suite/src/components/settings/SettingsSectionItem.tsx
  packages/suite/src/components/settings/index.tsx
  packages/suite/src/views/settings/SettingsCoins/SettingsCoins.tsx
  packages/suite/src/views/settings/SettingsDebug/GithubIssue.tsx
  packages/suite/src/views/settings/SettingsDebug/InvityApi.tsx
  packages/suite/src/views/settings/SettingsDebug/OAuthApi.tsx
  packages/suite/src/views/settings/SettingsDebug/TranslationMode.tsx
  packages/suite/src/views/settings/SettingsDebug/WipeData.tsx
  packages/suite/src/views/settings/SettingsDevice/AutoLock.tsx
  packages/suite/src/views/settings/SettingsDevice/BackupFailed.tsx
  packages/suite/src/views/settings/SettingsDevice/BackupRecoverySeed.tsx
  packages/suite/src/views/settings/SettingsDevice/ChangeLanguage.tsx
  packages/suite/src/views/settings/SettingsDevice/ChangePin.tsx
  packages/suite/src/views/settings/SettingsDevice/CheckRecoverySeed.tsx
  packages/suite/src/views/settings/SettingsDevice/CustomFirmware.tsx
  packages/suite/src/views/settings/SettingsDevice/DeviceAuthenticityOptOut.tsx
  packages/suite/src/views/settings/SettingsDevice/DeviceLabel.tsx
  packages/suite/src/views/settings/SettingsDevice/DisplayRotation.tsx
  packages/suite/src/views/settings/SettingsDevice/FirmwareTypeChange.tsx
  packages/suite/src/views/settings/SettingsDevice/FirmwareVersion.tsx
  packages/suite/src/views/settings/SettingsDevice/Homescreen.tsx
  packages/suite/src/views/settings/SettingsDevice/Passphrase.tsx
  packages/suite/src/views/settings/SettingsDevice/PinProtection.tsx
  packages/suite/src/views/settings/SettingsDevice/SafetyChecks.tsx
  packages/suite/src/views/settings/SettingsDevice/WipeCode.tsx
  packages/suite/src/views/settings/SettingsDevice/WipeDevice.tsx
  packages/suite/src/views/settings/SettingsGeneral/AddressDisplay.tsx
  packages/suite/src/views/settings/SettingsGeneral/Analytics.tsx
  packages/suite/src/views/settings/SettingsGeneral/BitcoinAmountUnit.tsx
  packages/suite/src/views/settings/SettingsGeneral/ClearStorage.tsx
  packages/suite/src/views/settings/SettingsGeneral/ConnectLabelingProvider.tsx
  packages/suite/src/views/settings/SettingsGeneral/DisconnectLabelingProvider.tsx
  packages/suite/src/views/settings/SettingsGeneral/EarlyAccess.tsx
  packages/suite/src/views/settings/SettingsGeneral/Fiat.tsx
  packages/suite/src/views/settings/SettingsGeneral/Labeling.tsx
  packages/suite/src/views/settings/SettingsGeneral/Language.tsx
  packages/suite/src/views/settings/SettingsGeneral/ShowApplicationLog.tsx
  packages/suite/src/views/settings/SettingsGeneral/Theme.tsx
  packages/suite/src/views/settings/SettingsGeneral/Tor.tsx
  packages/suite/src/views/settings/SettingsGeneral/TorOnionLinks.tsx
  packages/suite/src/views/settings/SettingsGeneral/VersionWithUpdate.tsx
Labels: settings, code

#12056 chore(suite-native): add redux logger to native
  suite-native/state/package.json
  suite-native/state/src/store.ts
  yarn.lock
Labels: mobile-app

#12058 feat(suite-native): install deps on lifecycle hook
  suite-native/app/package.json
Labels: mobile-app

#12065 chore(suite-native): remove eas preinstall script
  suite-native/app/package.json
Labels: mobile-app

#12086 Resolve app freezing on SOL accounts
  packages/blockchain-link-utils/src/solana.ts
  packages/blockchain-link-utils/src/tests/solana.test.ts
  packages/blockchain-link/src/workers/solana/index.ts
Labels: build-desktop

#12091 chore(mobile): slighty faster mobile app build trigger
  .github/workflows/suite-native_develop_ci.yml
  .github/workflows/suite-native_production_ci.yml
Labels: mobile-app

#12040 Feat/simple native send form
  suite-common/wallet-core/src/fees/feesReducer.ts
  suite-native/formatters/src/components/CryptoAmountFormatter.tsx
  suite-native/forms/src/fields/TextInputField.tsx
  suite-native/forms/src/hooks/useField.ts
  suite-native/module-send/package.json
  suite-native/module-send/src/components/SendForm.tsx
  suite-native/module-send/src/screens/SendFormScreen.tsx
  suite-native/module-send/src/sendFormSchema.ts
  suite-native/module-send/tsconfig.json
  suite-native/state/src/reducers.ts
  yarn.lock
Labels: mobile-app

#12004 chore(ci,suite-desktop): upload also mac arm file as separate artifact for faster download
  .github/workflows/build-desktop-apps.yml
Labels: ci, build-desktop

#12108 fix(components): make prop transient
  packages/components/src/components/form/TopAddons.tsx
Labels: bug, code

#12098 chore(suite-native): upgrade native version
  suite-native/app/package.json
Labels: mobile-app

#12093 Feat/minor ux enhacements
  suite-native/atoms/src/Text.tsx
  suite-native/module-accounts-management/src/components/AccountRenameForm.tsx
  suite-native/qr-code/src/components/AddressQRCode.tsx
  suite-native/qr-code/src/components/XpubQRCodeCard.tsx
  suite-native/receive/src/components/UnverifiedAddressDevice.tsx
Labels: mobile-app

#12049 feat(coinmarket): Add payment method filter
  packages/suite-web/e2e/tests/coinmarket/buy.test.ts
  packages/suite/src/hooks/wallet/useCoinmarketBuyOffers.ts
  packages/suite/src/reducers/wallet/useCoinmarketFilterReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/wallet/coinmarketBuyOffers.ts
  packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/List/BuyQuoteFilter.tsx
  packages/suite/src/views/wallet/coinmarket/buy/offers/Offers/List/BuyQuoteList.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketPaymentPlainType.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketPaymentType.tsx
Labels: feature, +Invity

#12036 Feat/mobile wallet discovery on empty passphrase
  suite-common/message-system/src/messageSystemThunks.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-native/app/src/App.tsx
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/discovery/src/utils.ts
Labels: mobile-app

#12125 fix(suite-native): correct flag fetching for view only popup
  suite-native/module-home/src/screens/HomeScreen/components/EnableViewOnlyBottomSheet.tsx
Labels: mobile-app, release-native

#12138 fix(suite): remove scrollbar from fees section
  packages/suite/src/components/wallet/Fees/Fees.tsx
Labels: bug, send, UI

#12142 fix(coinmarket): filter error offers
  packages/suite/src/reducers/wallet/useCoinmarketFilterReducer.ts
Labels: bug, +Invity

#12169 refactor(suite-native): form alert, cancel sheet
  suite-common/icons/assets/icons/arrowLineUpRight.svg
  suite-common/icons/src/icons.ts
  suite-native/intl/src/en.ts
  suite-native/module-passphrase/package.json
  suite-native/module-passphrase/src/components/PassphraseScreenHeader.tsx
  suite-native/module-passphrase/src/screens/PassphraseConfirmOnDeviceScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseFormScreen.tsx
  suite-native/module-passphrase/tsconfig.json
  yarn.lock
Labels: mobile-app

#12171 feat(suite-native): getting ready for TS5
  suite-native/device/src/assets/t3t1.png
  suite-native/intl/src/en.ts
  suite-native/module-connect-device/src/assets/pin-t3t1.png
  suite-native/module-settings/src/components/FAQInfoPanel.tsx
Labels: mobile-app

#12185 GitBook revision update
  packages/suite-data/src/guide/constants.ts
Labels: guide

#12208 Show correct step for disconnect event
  packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx
Labels: bug
