Repository trezor/trezor-suite, pull requests merged in 2024-09, with the labels that each got.

#14036 fix(suite-native): align welcome screen with design
  packages/theme/src/colors.ts
  suite-native/atoms/src/StepsProgressBar.tsx
  suite-native/intl/src/en.ts
  suite-native/module-onboarding/package.json
  suite-native/module-onboarding/src/components/OnboardingScreen.tsx
  suite-native/module-onboarding/src/screens/AnalyticsConsentScreen.tsx
  suite-native/module-onboarding/src/screens/ConnectTrezorScreen.tsx
  suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx
  suite-native/module-onboarding/src/screens/TrackBalancesScreen.tsx
  suite-native/module-onboarding/src/screens/WelcomeScreen.tsx
  yarn.lock
Labels: mobile

#13976 feat(suite-native): enable coin via add new coin account flow
  suite-native/coin-enabling/src/coinEnablingSelectors.ts
  suite-native/coin-enabling/src/components/DiscoveryCoinsFilter.tsx
  suite-native/coin-enabling/src/components/NetworkSymbolSwitchItem.tsx
  suite-native/coin-enabling/src/hooks/useCoinEnabling.tsx
  suite-native/coin-enabling/src/index.ts
  suite-native/coin-enabling/src/screens/CoinEnablingInitScreen.tsx
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/intl/src/en.ts
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
  suite-native/module-add-accounts/src/hooks/useAddCoinAccountAlerts.ts
  suite-native/module-add-accounts/src/navigation/AddCoinAccountStackNavigator.tsx
  suite-native/module-add-accounts/src/screens/AddCoinAccountScreen.tsx
  suite-native/module-add-accounts/src/screens/AddCoinDiscoveryFinishedScreen.tsx
  suite-native/module-add-accounts/src/screens/AddCoinDiscoveryRunningScreen.tsx
  suite-native/module-home/src/hooks/useCoinEnablingInitialCheck.tsx
  suite-native/module-settings/src/screens/SettingsCoinEnablingScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
Labels: mobile

#14037 feat(suite-native): use enabled networks for msg system settings validation
  suite-native/message-system/package.json
  suite-native/message-system/src/messageSystemMiddleware.ts
  suite-native/message-system/tsconfig.json
  yarn.lock
Labels: mobile

#14083 feat(suite-native): add Polygon feature flag to enable its discovery for mobile
  suite-native/config/src/supportedNetworks.ts
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
Labels: mobile

#14066 chore: add isDeviceAcquired type guard
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/components/suite/SecurityCheck/DeviceCompromised.tsx
  packages/suite/src/components/suite/banners/SuiteBanners/SuiteBanners.tsx
  packages/suite/src/middlewares/wallet/discoveryMiddleware.ts
  packages/suite/src/views/backup/index.tsx
  packages/suite/src/views/recovery/index.tsx
  suite-common/suite-utils/src/device.ts
  suite-common/wallet-core/src/device/deviceThunks.ts
Labels: code

#14091 fix(suite): fix condition to display tooltip over used address button
  packages/suite/src/views/wallet/receive/components/UsedAddresses.tsx
Labels: bug

#14049 chore(suite-native): coin enabling analytics
  suite-native/analytics/src/constants.ts
  suite-native/analytics/src/events.ts
  suite-native/app/package.json
  suite-native/app/src/hooks/useReportAppInitToAnalytics.ts
  suite-native/app/tsconfig.json
  suite-native/coin-enabling/package.json
  suite-native/coin-enabling/src/components/DiscoveryCoinsFilter.tsx
  suite-native/coin-enabling/src/components/NetworkSymbolSwitchItem.tsx
  suite-native/coin-enabling/src/screens/CoinEnablingInitScreen.tsx
  suite-native/coin-enabling/tsconfig.json
  yarn.lock
Labels: mobile

#14081 feat(mobile): improve Account import flow performance
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/device-manager/src/components/DeviceItem/DeviceItemContent.tsx
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/accountsImportThunks.ts
  suite-native/module-accounts-import/src/components/AccountImportEthereumTokens.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-import/tsconfig.json
  yarn.lock
Labels: mobile

#14098 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite/src/support/messages.ts
Labels: translations

#14099 Crowdin translations update
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/el.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/vi.json
  packages/suite-data/files/translations/zh.json
Labels: translations

#14027 fix(suite-native): display fiat value skeleton while fiat rates are loading
  suite-common/assets/src/utils.ts
  suite-native/assets/src/assetsSelectors.ts
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/formatters/src/components/FiatAmountFormatter.tsx
  suite-native/graph/src/components/GraphFiatBalance.tsx
  suite-native/graph/src/index.ts
  suite-native/module-accounts-management/src/accountDetailGraphAtoms.ts
  suite-native/module-accounts-management/src/components/AccountDetailGraph.tsx
  suite-native/module-accounts-management/src/components/AccountDetailGraphHeader.tsx
  suite-native/module-home/package.json
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraph.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraphHeader.tsx
  suite-native/module-home/src/screens/HomeScreen/portfolioGraphAtoms.ts
  suite-native/module-home/tsconfig.json
  yarn.lock
Labels: mobile

#14102 Bump beta version to 24.10.0
  packages/suite/package.json
Labels: deployment

#13772 feat(coinmarket): Add DCA landing page (#13724)
  packages/components/src/components/Image/images.ts
  packages/suite-data/files/images/png/coinmarket-dca-invity-app-qr.png
  packages/suite-data/files/images/png/coinmarket-dca-invity-app-qr@2x.png
  packages/suite-data/files/images/png/coinmarket-invity-icon.png
  packages/suite-data/files/images/png/coinmarket-invity-icon@2x.png
  packages/suite-data/files/translations/en.json
  packages/suite-desktop-ui/src/support/Router.tsx
  packages/suite-web/src/support/Router.tsx
  packages/suite/src/constants/wallet/coinmarket/regional.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/DCA/index.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayoutNew/CoinmarketLayoutNavigation/CoinmarketLayoutNavigation.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayoutNew/CoinmarketLayoutNavigation/CoinmarketLayoutNavigationItem.tsx
  packages/urls/src/urls.ts
  suite-common/icons/assets/icons/arrowDownLong.svg
  suite-common/icons/assets/icons/eyeBold.svg
  suite-common/icons/src/icons.ts
  suite-common/suite-config/src/routes.ts
Labels: READY FOR REVIEW, +Invity

#14124 chore(suite-native): bump app version to 24.9.1
  suite-native/app/package.json
Labels: mobile

#14115 Change default bitcoin like network fee unit to sat/vB
  packages/suite-web/e2e/tests/coinmarket/exchange.test.ts
  suite-common/wallet-utils/src/sendFormUtils.ts
Labels: low hanging fruit

#14106 fix(suite-native): move coin enabling init check to navigator
  suite-native/app/package.json
  suite-native/app/src/hooks/useCoinEnablingInitialCheck.tsx
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/coin-enabling/src/coinEnablingSelectors.ts
  suite-native/coin-enabling/src/screens/CoinEnablingInitScreen.tsx
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-home/package.json
  suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx
  suite-native/module-home/tsconfig.json
  yarn.lock
Labels: mobile

#14125 Fix inactive button when device check is disabled
  packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx
Labels: release

#14110 fix(coinmarket): fix crypto ticker in limits message
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketBuyForm.tsx
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketSellForm.ts
Labels: bug, +Invity, release

#14130 fix(coinmarket): fix network labels
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputCryptoSelect.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormOffer.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketInfo/CoinmarketInfoHeader.tsx
Labels: bug, +Invity, release

#14134 fix(coinmarket): update receive select
  packages/suite/src/constants/wallet/coinmarket/form.ts
  packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketFormActions.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeFormDefaultValues.ts
  packages/suite/src/utils/wallet/coinmarket/__tests__/exchangeUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/exchangeUtils.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputCryptoSelect.tsx
Labels: bug, +Invity, release

#14137 fix(coinmarket): unify icon thickness and remove unused ones (#14135)
  packages/suite/src/views/wallet/coinmarket/DCA/index.tsx
  suite-common/icons-deprecated/assets/icons/arrowDownLong.svg
  suite-common/icons-deprecated/assets/icons/eyeBold.svg
  suite-common/icons-deprecated/src/icons.ts
Labels: bug, +Invity

#14112 fix(coinmarket): currency rates
  packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketFormActions.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketSellForm.ts
  packages/suite/src/types/coinmarket/coinmarket.ts
  packages/suite/src/types/coinmarket/coinmarketForm.ts
  packages/suite/src/utils/wallet/coinmarket/__tests__/coinmarketUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/coinmarketUtils.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketBalance.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInputs.tsx
Labels: bug, +Invity, release

#14122 fix(suite-native): tweak fiat amount skeletons to prevent layout shift
  suite-native/atoms/src/Skeleton/BoxSkeleton.tsx
  suite-native/formatters/src/components/EmptyAmountSkeleton.tsx
  suite-native/formatters/src/components/FiatAmountFormatter.tsx
  suite-native/graph/src/components/GraphFiatBalance.tsx
  suite-native/graph/src/hooks.ts
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraph.tsx
Labels: mobile

#14131 feat(suite-native): use our custom URL to check network reachability to prevent pinging google
  suite-native/app/src/App.tsx
  suite-native/connection-status/src/configureNetInfo.ts
  suite-native/connection-status/src/index.ts
Labels: low hanging fruit, mobile

#14165 fix(suite-native): add missing bottom margin to discovery assets loader
  suite-native/assets/src/components/DiscoveryAssetsLoader.tsx
Labels: mobile

#14166 Enable displaying receive addresses when revision check is failed but disabled
  packages/suite/src/components/suite/Preloader/Preloader.tsx
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/views/wallet/receive/components/FreshAddress.tsx
  packages/suite/src/views/wallet/receive/components/UsedAddresses.tsx
  suite-common/wallet-core/src/device/deviceReducer.ts
Labels: bug, release

#14174 test: staking-big-number
  packages/suite-web/e2e/tests/wallet/staking.test.ts
Labels: e2e

#14167 feat(suite-native): Coin Enabling settings screens polishing
  suite-native/coin-enabling/package.json
  suite-native/coin-enabling/src/components/NetworkSymbolSwitchItem.tsx
  suite-native/coin-enabling/src/screens/CoinEnablingInitScreen.tsx
  suite-native/coin-enabling/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-settings/package.json
  suite-native/module-settings/src/screens/SettingsCoinEnablingScreen.tsx
  suite-native/module-settings/tsconfig.json
  yarn.lock
Labels: mobile

#14197 feat(suite-native): add test ids for Coin Enabling
  suite-native/coin-enabling/src/components/NetworkSymbolSwitchItem.tsx
  suite-native/coin-enabling/src/screens/CoinEnablingInitScreen.tsx
  suite-native/module-add-accounts/src/components/AccountTypeDecisionBottomSheet.tsx
  suite-native/module-add-accounts/src/screens/AddCoinDiscoveryFinishedScreen.tsx
  suite-native/module-settings/src/components/FeaturesSettings.tsx
  suite-native/module-settings/src/components/PreferencesSettings.tsx
  suite-native/module-settings/src/components/SupportSettings.tsx
Labels: mobile

#14158 feat(coinmarket): add analytics on confirm transaction
  packages/suite-analytics/src/constants.ts
  packages/suite-analytics/src/types/events.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketBuyForm.tsx
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketSellForm.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerify.tsx
Labels: feature, data, +Invity

#14227 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/no.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/tr.json
  packages/suite/src/support/messages.ts
Labels: translations

#14222 chore(suite-native): netinfo added to mobile outdated deps list
  scripts/list-outdated-dependencies/mobile-dependencies.txt
Labels: mobile

#14138 feat(suite-native) improve coin enabling flow
  suite-native/module-home/src/screens/HomeScreen/components/BiometricsBottomSheet.tsx
  suite-native/module-settings/package.json
  suite-native/module-settings/src/screens/SettingsCoinEnablingScreen.tsx
  suite-native/module-settings/tsconfig.json
  yarn.lock
Labels: mobile

#14246 fix(suite-native): show amount error message even if field not dirty
  suite-native/module-send/src/components/AmountErrorMessage.tsx
  suite-native/module-send/src/components/AmountInputs.tsx
Labels: mobile

#14232 feat(suite-native): show consistent Tokens label across the app
  suite-native/accounts/src/components/SelectableNetworkItem.tsx
  suite-native/coin-enabling/package.json
  suite-native/coin-enabling/src/components/NetworkSymbolSwitchItem.tsx
  suite-native/coin-enabling/tsconfig.json
  suite-native/intl/src/en.ts
  yarn.lock
Labels: mobile

#14228 fix(suite-native): after coin enabling is enabled, show relevant normal accounts
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile

#14234 fix(mobile): fix app perf for big number of tokens
  packages/suite/src/actions/wallet/tokenActions.ts
  packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketFiatValues.tsx
  packages/suite/src/hooks/wallet/useSendFormImport.ts
  packages/suite/src/views/wallet/send/Outputs/Amount/FiatInput.tsx
  packages/suite/src/views/wallet/send/Outputs/Amount/TokenSelect.tsx
  suite-common/token-definitions/package.json
  suite-common/token-definitions/src/tokenDefinitionsSelectors.ts
  suite-common/token-definitions/src/tokenDefinitionsUtils.ts
  suite-common/wallet-core/src/fiat-rates/fiatRatesMiddleware.ts
  suite-common/wallet-core/src/fiat-rates/fiatRatesReducer.ts
  suite-common/wallet-core/src/fiat-rates/fiatRatesThunks.ts
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/accounts/src/components/AccountListItemInteractive.tsx
  suite-native/accounts/src/components/AccountsList.tsx
  suite-native/accounts/src/components/TokenList.tsx
  suite-native/accounts/src/types.ts
  suite-native/assets/package.json
  suite-native/assets/src/assetsSelectors.ts
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/assets/src/components/Assets.tsx
  suite-native/assets/src/components/NetworkAssetsBottomSheet.tsx
  suite-native/assets/tsconfig.json
  suite-native/discovery/src/discoverySelectors.ts
  suite-native/formatters/src/components/CryptoAmountFormatter.tsx
  suite-native/formatters/src/components/FiatAmountFormatter.tsx
  suite-native/graph/package.json
  suite-native/graph/src/hooks.ts
  suite-native/graph/src/selectors.ts
  suite-native/graph/tsconfig.json
  suite-native/module-accounts-import/src/accountsImportThunks.ts
  suite-native/module-accounts-import/src/components/EthereumTokenInfo.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraph.tsx
  suite-native/tokens/src/ethereumTokensSelectors.ts
  suite-native/tokens/src/tokensSelectors.ts
  suite-native/transactions/src/selectors.ts
  yarn.lock
Labels: mobile

#14149 feat(suite-native): QR code scanner bottom sheet
  scripts/list-outdated-dependencies/mobile-dependencies.txt
  suite-common/icons-deprecated/assets/icons/image.svg
  suite-common/icons-deprecated/assets/icons/lightbulb.svg
  suite-common/icons-deprecated/src/icons.ts
  suite-native/app/app.config.ts
  suite-native/app/package.json
  suite-native/intl/src/en.ts
  suite-native/module-accounts-import/src/components/XpubImportSection.tsx
  suite-native/module-accounts-import/src/navigation/AccountsImportStackNavigator.tsx
  suite-native/module-accounts-import/src/screens/ScanQRCodeModalScreen.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-send/package.json
  suite-native/module-send/src/components/AddressInput.tsx
  suite-native/module-send/src/components/QrCodeBottomSheetIcon.tsx
  suite-native/module-send/src/components/RecipientInputs.tsx
  suite-native/module-send/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/qr-code/package.json
  suite-native/qr-code/src/components/CameraPermissionError.tsx
  suite-native/qr-code/src/components/PickQRFromGalleryButton.tsx
  suite-native/qr-code/src/components/QRCodeScanner.tsx
  suite-native/qr-code/src/components/ScanQRBottomSheet.tsx
  suite-native/qr-code/src/hooks/useCameraPermission.ts
  suite-native/qr-code/src/index.ts
  suite-native/qr-code/tsconfig.json
  suite-native/test-utils/src/expoMock.js
  yarn.lock
Labels: mobile

#14104 feat(coinmarket): rename exchange to swap
  packages/suite-data/files/translations/en.json
  packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/HeaderActions.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/CoinmarketTermsModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/UserContextModal.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/types/coinmarket/coinmarket.ts
  packages/suite/src/utils/wallet/coinmarket/__tests__/coinmarketUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/coinmarketUtils.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketFeaturedOffers/CoinmarketFeaturedOffersItem.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayout/CoinmarketLayoutNavigation.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayoutNew/CoinmarketLayoutNavigation/CoinmarketLayoutNavigation.tsx
  packages/suite/src/views/wallet/coinmarket/exchange_new/CoinmarketExchangeConfirm.tsx
  packages/suite/src/views/wallet/coinmarket/exchange_new/CoinmarketExchangeForm.tsx
  packages/suite/src/views/wallet/coinmarket/exchange_new/CoinmarketExchangeOffers.tsx
  packages/suite/src/views/wallet/coinmarket/exchange_new/components/ExchangeForm/CoinmarketExchangeOfferInfo.tsx
  packages/suite/src/views/wallet/coinmarket/exchange_new/detail/index.tsx
  packages/suite/src/views/wallet/transactions/TradeBox/TradeBoxMenu.tsx
Labels: feature, +Invity

#14272 fix(coinmarket): exclude unsupported networks by address validator in trade section
  packages/suite/package.json
  packages/suite/src/hooks/wallet/coinmarket/useCoinmarketInfo.ts
  packages/suite/src/reducers/wallet/__tests__/coinmarketReducer.test.ts
  packages/suite/src/types/coinmarket/coinmarket.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerify.tsx
  yarn.lock
Labels: bug, +Invity, release

#14299 fix(suite): do not show number of hidden tokens in case it is zero
  packages/suite/src/views/wallet/tokens/common/TokensLayout/TokensLayoutNavigation.tsx
Labels: release

#14264 feat(mobile): minor perf stuff
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/device-manager/package.json
  suite-native/device-manager/src/components/DeviceItem/DeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceItem/SimpleDeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceSwitch.tsx
  suite-native/device-manager/tsconfig.json
  yarn.lock
Labels: mobile

#14254 fix(suite-native): check btc firmware instead of btc only device for coin enabling
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/app/src/hooks/useCoinEnablingInitialCheck.tsx
  suite-native/module-settings/src/screens/SettingsCoinEnablingScreen.tsx
Labels: mobile

#14291 fix(coinmarket): show DCA page only for Bitcoin accounts #14290
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayout/CoinmarketLayout.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayoutNew/CoinmarketLayout.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayoutNew/CoinmarketLayoutNavigation/CoinmarketLayoutNavigation.tsx
Labels: +Invity

#14273 fix(suite-native): let passphrase flow finish sooner if some account is found
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/discovery/discoveryReducer.ts
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseLoadingScreen.tsx
Labels: mobile

#14312 feat(suite-native): change text in coin enabling
  suite-native/intl/src/en.ts
Labels: mobile

#14293 fix(suite-native): fix extra line breaks on some Android phones
  suite-native/formatters/package.json
  suite-native/formatters/src/components/AmountText.tsx
  suite-native/formatters/tsconfig.json
  yarn.lock
Labels: mobile

#14313 chore(suite-native): set fixed firebase CLI version for android dev build distribution
  suite-native/app/eas-post-success.sh
Labels: ci, mobile, android

#14267 fix(suite-native): check discovery existence instead of whether it is active
  suite-native/accounts/src/components/AddAccountsButton.tsx
  suite-native/assets/src/components/Assets.tsx
  suite-native/device-manager/src/components/DeviceList.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/discovery/src/discoverySelectors.ts
  suite-native/discovery/src/discoveryThunks.ts
  suite-native/discovery/src/useIsDiscoveryDurationTooLong.tsx
  suite-native/module-add-accounts/src/screens/AddCoinDiscoveryRunningScreen.tsx
  suite-native/module-authorize-device/src/components/connect/ConnectDeviceScreenHeader.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseConfirmOnTrezorScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseEnterOnTrezorScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EnableViewOnlyBottomSheet.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraphHeader.tsx
  suite-native/module-settings/src/components/ViewOnly/WalletRow.tsx
Labels: mobile

#14316 fix(suite-native): camera permissions restored
  suite-native/app/app.config.ts
Labels: mobile

#14317 fix(suite): remove redundant H3 wrapper
  packages/suite/src/views/dashboard/components/PortfolioCard/index.tsx
Labels: code

#14292 feat(suite-native): allow sending bitcoin transactions denominated in sats
  suite-common/formatters/jest.config.js
  suite-common/formatters/src/index.ts
  suite-common/formatters/src/utils/convert.ts
  suite-common/formatters/src/utils/convertCryptoToFiatAmount.ts
  suite-common/formatters/src/utils/tests/convert.test.ts
  suite-common/formatters/src/utils/tests/convertCryptoToFiatAmount.test.ts
  suite-native/formatters/src/hooks/useCryptoFiatConverters.ts
  suite-native/formatters/src/hooks/useFiatFromCryptoValue.ts
  suite-native/module-send/src/components/CryptoAmountInput.tsx
  suite-native/module-send/src/components/FiatAmountInput.tsx
  suite-native/module-send/src/components/RecipientsSummary.tsx
  suite-native/module-send/src/screens/SendOutputsScreen.tsx
  suite-native/module-send/src/sendFormMiddleware.ts
  suite-native/module-send/src/sendFormThunks.ts
  suite-native/module-send/src/sendOutputsFormSchema.ts
  suite-native/module-send/src/useSendAmountTransformers.ts
  suite-native/module-send/src/utils.ts
  suite-native/settings/package.json
  suite-native/settings/src/settingsSlice.ts
  suite-native/settings/tsconfig.json
  suite-native/state/package.json
  suite-native/state/src/extraDependencies.ts
  suite-native/state/src/store.ts
  suite-native/state/tsconfig.json
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailValuesSheet.tsx
  yarn.lock
Labels: mobile

#14355 feat(mobile): remove token count from home
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/components/EthereumTokenInfo.tsx
  suite-native/module-accounts-import/tsconfig.json
  suite-native/tokens/src/ethereumTokensSelectors.ts
  suite-native/tokens/src/tokensSelectors.ts
  suite-native/transactions/src/selectors.ts
  yarn.lock
Labels: mobile

#14357 fix(mobile): different total fiat across the app
  suite-native/assets/src/assetsSelectors.ts
  suite-native/module-accounts-import/src/components/DevXpub.tsx
Labels: mobile

#14354 fix(suite-native): update when biometrics prompt is shown
  suite-native/module-home/src/screens/HomeScreen/components/BiometricsBottomSheet.tsx
Labels: mobile

#14345 fix(suite-native): make cardano discovery work correct
  suite-common/wallet-core/src/discovery/discoveryThunks.ts
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile

#14381 fix(suite): fix t3b1 homescreen name
  packages/suite/src/components/suite/HomescreenGallery.tsx
  packages/suite/src/constants/suite/homescreens.ts
Labels: bug

#14375 chore(ci): use larger workers for android builds to prevent failing
  suite-native/app/eas.json
Labels: ci, mobile

#14373 chore(suite-native): get rid of ios email warnings about missing entitlement
  suite-native/app/app.config.ts
Labels: mobile

#14387 chore(urls): add internal Url type to check URL prefix
  packages/urls/src/github.ts
  packages/urls/src/types.ts
  packages/urls/src/urls.ts
  packages/urls/tests/urls.test.ts
Labels: code

#14394 fix(components): fix animation path
  packages/components/src/components/animations/LottieAnimation.tsx
Labels: bug

#14402 fix(suite-native): hide coin enabling when disabled device connect ff
  suite-native/module-settings/src/components/FeaturesSettings.tsx
Labels: mobile

#14396 fix(mobile): different total fiat across the app
  suite-common/graph/src/balanceHistoryUtils.ts
  suite-common/graph/src/graphDataFetching.ts
  suite-common/graph/src/tests/__fixtures__/eth.ts
  suite-native/graph/package.json
  suite-native/graph/src/components/TransactionEventTooltip.tsx
  suite-native/graph/src/hooks.ts
  suite-native/graph/src/selectors.ts
  suite-native/graph/tsconfig.json
  suite-native/module-accounts-import/src/components/DevXpub.tsx
  yarn.lock
Labels: mobile

#14407 chore(ci): disable yarn hardening for android e2e workflow to make it a bit faster
  .github/workflows/test-suite-native-e2e-android.yml
Labels: ci, mobile

#14413 chore(suite-native): bump app version to 24.9.2
  suite-native/app/package.json
Labels: mobile

#14420 android e2e pipeline fix
  .github/workflows/test-suite-native-e2e-android.yml
Labels: ci, mobile

#14348 feat(suite-native): send form normal fee level validation
  suite-native/module-send/src/components/FeeOptionsList.tsx
  suite-native/module-send/src/screens/SendOutputsScreen.tsx
  suite-native/module-send/src/sendFormThunks.ts
  suite-native/module-send/src/sendOutputsFormSchema.ts
Labels: mobile

#14424 chore(suite-native): workaround removal due to updated connect
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile

#14422 feat(suite-native): only show one skeleton for discovery in progress
  suite-native/assets/src/components/Assets.tsx
  suite-native/assets/src/components/DiscoveryAssetsLoader.tsx
Labels: mobile

#14435 fix(suite-desktop-core): autostart launch issue
  packages/suite-desktop-core/src/app.ts
Labels: build-desktop

#14409 Revert "chore(suite-native): get rid of ios email warnings about missing entitlement"
  suite-native/app/app.config.ts
Labels: mobile

#14367 chore(suite-native): remove deprecated iconset from Demo screen to prevent crashes
  suite-native/module-dev-utils/package.json
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-dev-utils/tsconfig.json
  yarn.lock
Labels: mobile

#14443 feat(suite-native): allow to use plural syntax and use it for Token/Tokens message
  scripts/list-outdated-dependencies/mobile-dependencies.txt
  suite-native/intl/package.json
  suite-native/intl/src/IntlProvider.tsx
  suite-native/intl/src/en.ts
  yarn.lock
Labels: mobile

#14439 chore(suite-native): capture console errors to sentry on mobile too
  package.json
  suite-native/app/package.json
  suite-native/app/src/SentryProvider.tsx
  suite-native/device/package.json
  suite-native/graph/package.json
  suite-native/module-dev-utils/package.json
  suite-native/navigation/package.json
  suite-native/state/package.json
  suite-native/storage/package.json
  yarn.lock
Labels: mobile

#14446 fix(mobile): reflect token fiat value in account list
  suite-native/accounts/src/components/AccountListItem.tsx
  suite-native/accounts/src/components/AccountListItemInteractive.tsx
Labels: mobile

#14460 Crowdin translations update
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/no.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/vi.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#14488 fix(ci): nx output style
  .github/workflows/check-code-validation.yml
  package.json
Labels: ci

#14477 fix(suite-native): send confirm on device bottom sheet
  suite-native/device/src/components/ConfirmOnTrezorBottomSheet.tsx
  suite-native/device/src/components/ConfirmOnTrezorImage.tsx
  suite-native/intl/src/en.ts
  suite-native/module-send/src/components/OutputsReviewFooter.tsx
  suite-native/module-send/src/components/SendConfirmOnDeviceImage.tsx
  suite-native/module-send/src/screens/SendAddressReviewScreen.tsx
  suite-native/receive/src/components/ReceiveAccount.tsx
Labels: mobile

#14464 feat(suite-native): send navigation improvements
  suite-native/intl/src/en.ts
  suite-native/module-accounts-management/package.json
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
  suite-native/module-accounts-management/tsconfig.json
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
  suite-native/module-send/src/components/AddressReviewStepList.tsx
  suite-native/module-send/src/components/OutputsReviewFooter.tsx
  suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx
  yarn.lock
Labels: mobile

#14479 feat(suite-native): send decimals validation
  suite-native/module-send/src/screens/SendOutputsScreen.tsx
  suite-native/module-send/src/sendOutputsFormSchema.ts
Labels: mobile

#14500 feat(suite-native): add feature flag to allow bnb smart chain
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
Labels: mobile

#14340 fix(coinmarket): transaction wrapping
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactionId.tsx
Labels: bug, +Invity

#14487 feat(mobile): use flashlist for tokens bottom sheet
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AccountListItemBase.tsx
  suite-native/accounts/src/components/AccountListItemInteractive.tsx
  suite-native/accounts/src/components/AccountSectionTitle.tsx
  suite-native/accounts/src/components/AccountSelectBottomSheet.tsx
  suite-native/accounts/src/components/AccountsList.tsx
  suite-native/accounts/src/components/AccountsList/AccountsList.tsx
  suite-native/accounts/src/components/AccountsList/AccountsListEmptyPlaceholder.tsx
  suite-native/accounts/src/components/AccountsList/AccountsListItem.tsx
  suite-native/accounts/src/components/AccountsList/AccountsListItemBase.tsx
  suite-native/accounts/src/components/AccountsList/AccountsListTokenItem.tsx
  suite-native/accounts/src/components/AccountsListGroup.tsx
  suite-native/accounts/src/components/GroupedAccountsList.tsx
  suite-native/accounts/src/components/TokenList.tsx
  suite-native/accounts/src/components/TokenListItem.tsx
  suite-native/accounts/src/components/TokenSelectBottomSheet.tsx
  suite-native/accounts/src/index.ts
  suite-native/accounts/src/selectors.ts
  suite-native/accounts/src/types.ts
  suite-native/assets/src/assetsSelectors.ts
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/assets/src/components/NetworkAssetsBottomSheet.tsx
  suite-native/atoms/src/Sheet/BottomSheet.tsx
  suite-native/module-accounts-import/src/components/AccountAlreadyImported.tsx
  suite-native/module-add-accounts/src/screens/AddCoinDiscoveryFinishedScreen.tsx
  suite-native/receive/src/components/ReceiveAccountDetailsCard.tsx
  yarn.lock
Labels: mobile

#14457 feat(coinmarket): Add filters for exchange comparator
  packages/suite-data/files/translations/en.json
  packages/suite/src/constants/wallet/coinmarket/form.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeFormDefaultValues.ts
  packages/suite/src/hooks/wallet/coinmarket/offers/useCoinmarketCommonOffers.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/coinmarket/coinmarketForm.ts
  packages/suite/src/views/wallet/coinmarket/DCA/index.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketCryptoAmount.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketHeader/CoinmarketExchangeHeaderSummary.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketHeader/CoinmarketHeader.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketHeader/CoinmarketHeaderFilter.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketHeader/CoinmarketHeaderSummary.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketHeader/CoinmarketOffersExchangeFiltersPanel.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffers.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffersExchange.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffersExchangeQuotesByTypeSection.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffersItem.tsx
Labels: +Invity

#14210 fix(coinmarket): coinmarket amount wrapper
  packages/suite/src/views/wallet/coinmarket/index.tsx
Labels: bug, +Invity

#14294 fix(coinmarket): fix crypto ticker in receive dropdown
  packages/suite/src/hooks/wallet/coinmarket/useCoinmarketInfo.ts
  packages/suite/src/types/coinmarket/coinmarket.ts
  packages/suite/src/types/coinmarket/coinmarketVerify.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerify.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerifyOptions.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerifyOptionsItem.tsx
Labels: bug, +Invity, release

#14486 Simplify mobile ENV variables
  .github/workflows/release-suite-native-develop.yml
  .github/workflows/release-suite-native-production.yml
  .github/workflows/test-suite-native-e2e-android.yml
  scripts/list-outdated-dependencies/mobile-dependencies.txt
  suite-native/app/.detoxrc.js
  suite-native/app/.env.develop
  suite-native/app/.env.development
  suite-native/app/.env.production
  suite-native/app/.env.test
  suite-native/app/.gitignore
  suite-native/app/README.md
  suite-native/app/app.config.ts
  suite-native/app/babel.config.js
  suite-native/app/e2e/README.md
  suite-native/app/eas.json
  suite-native/app/package.json
  suite-native/app/plugins/withEnvFile.js
  suite-native/config/README.md
  suite-native/config/package.json
  suite-native/config/src/environment.ts
  suite-native/test-utils/src/expoMock.js
  yarn.lock
Labels: mobile

#14522 fix(test): database-migration-test
  packages/suite-web/e2e/tests/suite/database-migration.test.ts
Labels: e2e

#14506 fix(suite-common): sanitise fetching graph history rates for empty account
  suite-common/graph/src/graphDataFetching.ts
Labels: mobile

#14494 Crowdin translations update
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/ca.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/vi.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#14523 feat(suite-native): send analytics
  suite-native/analytics/src/constants.ts
  suite-native/analytics/src/events.ts
  suite-native/analytics/src/index.ts
  suite-native/analytics/src/types.ts
  suite-native/forms/src/fields/TextInputField.tsx
  suite-native/module-send/package.json
  suite-native/module-send/src/components/AddressInput.tsx
  suite-native/module-send/src/components/AmountInputs.tsx
  suite-native/module-send/src/components/FeeOption.tsx
  suite-native/module-send/src/components/FeeOptionsList.tsx
  suite-native/module-send/src/components/OutputsReviewFooter.tsx
  suite-native/module-send/src/components/RecipientInputs.tsx
  suite-native/module-send/src/components/SendFeesForm.tsx
  suite-native/module-send/src/sendFormThunks.ts
  suite-native/module-send/tsconfig.json
  suite-native/navigation/package.json
  suite-native/navigation/src/components/NavigationContainerWithAnalytics.tsx
  suite-native/navigation/src/useReportSendFlowExitToAnalytics.ts
  yarn.lock
Labels: mobile

#14540 feat(suite-native): send review cancelation dialog
  suite-native/intl/src/en.ts
  suite-native/module-send/package.json
  suite-native/module-send/src/components/AddressReviewStepList.tsx
  suite-native/module-send/src/components/CryptoAmountInput.tsx
  suite-native/module-send/src/components/FiatAmountInput.tsx
  suite-native/module-send/src/hooks/useSendAmountTransformers.ts
  suite-native/module-send/src/hooks/useShowReviewCancellationAlert.tsx
  suite-native/module-send/src/navigation/SendStackNavigator.tsx
  suite-native/module-send/src/screens/SendAddressReviewScreen.tsx
  suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx
  suite-native/module-send/src/screens/SendOutputsScreen.tsx
  suite-native/module-send/src/sendFormThunks.ts
  suite-native/module-send/tsconfig.json
  yarn.lock
Labels: mobile

#14320 feat(coinmarket): possibility to proceed with unverified address
  packages/suite-data/files/translations/en.json
  packages/suite/src/actions/wallet/coinmarket/__fixtures__/coinmarketCommonActions/verifyAddress.ts
  packages/suite/src/actions/wallet/coinmarket/coinmarketCommonActions.ts
  packages/suite/src/actions/wallet/coinmarketBuyActions.ts
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ConfirmUnverifiedAddressModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ConfirmUnverifiedModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ConfirmUnverifiedProceedModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ConfirmUnverifiedXpubModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/UserContextModal.tsx
  packages/suite/src/components/suite/modals/index.tsx
  packages/suite/src/reducers/wallet/coinmarketReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerify.tsx
  suite-common/suite-types/src/modal.ts
Labels: feature, +Invity

#14539 fix(suite-desktop): fix bridge controls in debug menu
  packages/suite-desktop-core/src/app.ts
  packages/suite-desktop-core/src/modules/bridge.ts
  packages/suite/src/views/settings/SettingsDebug/TransportBackends.tsx
Labels: Bridge -> nodeUSB

#14570 fix(coinmarket): sell process
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketSellForm.ts
Labels: bug, +Invity

#14594 fix(suite-native): wrong alignment of + and - on some places
  suite-native/formatters/src/components/EthereumTokenToFiatAmountFormatter.tsx
  suite-native/graph/src/components/TransactionEventTooltip.tsx
Labels: mobile

#14561 feat(mobile): staking view-only
  suite-common/wallet-utils/src/stakingUtils.ts
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AccountSectionTitle.tsx
  suite-native/accounts/src/components/AccountSelectBottomSheet.tsx
  suite-native/accounts/src/components/AccountsList/AccountsList.tsx
  suite-native/accounts/src/components/AccountsList/AccountsListItem.tsx
  suite-native/accounts/src/components/AccountsList/AccountsListStakingItem.tsx
  suite-native/accounts/src/components/AccountsList/StakingBadge.tsx
  suite-native/accounts/src/components/TokenSelectBottomSheet.tsx
  suite-native/accounts/src/index.ts
  suite-native/accounts/src/selectors.ts
  suite-native/accounts/src/types.ts
  suite-native/accounts/tsconfig.json
  suite-native/app/package.json
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/app/tsconfig.json
  suite-native/assets/package.json
  suite-native/assets/src/assetsSelectors.ts
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/assets/src/components/Assets.tsx
  suite-native/assets/src/components/NetworkAssetsBottomSheet.tsx
  suite-native/assets/tsconfig.json
  suite-native/atoms/src/AlertBox.tsx
  suite-native/atoms/src/RoundedIcon.tsx
  suite-native/intl/src/en.ts
  suite-native/module-accounts-management/src/screens/AccountsScreen/AccountsScreen.tsx
  suite-native/module-staking-management/package.json
  suite-native/module-staking-management/src/components/StakePendingCard.tsx
  suite-native/module-staking-management/src/components/StakingBalancesOverviewCard.tsx
  suite-native/module-staking-management/src/components/StakingDetailScreenHeader.tsx
  suite-native/module-staking-management/src/components/StakingInfo.tsx
  suite-native/module-staking-management/src/components/StakingUnavailableBottomSheet.tsx
  suite-native/module-staking-management/src/index.ts
  suite-native/module-staking-management/src/screens/StakingDetailScreen.tsx
  suite-native/module-staking-management/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/staking/package.json
  suite-native/staking/src/ethereumStakingSelectors.ts
  suite-native/staking/src/index.ts
  suite-native/staking/src/selectors.ts
  suite-native/staking/src/types.ts
  suite-native/staking/src/utils.ts
  suite-native/staking/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: mobile

#14624 fix(coinmarket): add missing dynamic flag for some translations
  packages/suite/src/support/messages.ts
Labels: +Invity

#14630 fix(suite): fix coin control guide link
  packages/suite/src/views/wallet/send/Options/BitcoinOptions/BitcoinOptions.tsx
Labels: bug, guide

#14632 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations
