Repository trezor/trezor-suite, pull requests merged in 2024-11, with the labels that each got.

#15163 fix(suite-native): fix video selection for XPUB vs address hints
  suite-native/module-accounts-import/src/components/XpubHintBottomSheet.tsx
Labels: bug, mobile

#15118 feat(suite-native): ethereum send info messages
  suite-native/intl/src/en.ts
  suite-native/link/src/components/Link.tsx
  suite-native/module-send/package.json
  suite-native/module-send/src/components/AddressInput.tsx
  suite-native/module-send/src/components/CorrectNetworkMessageCard.tsx
  suite-native/module-send/src/components/SendOutputFields.tsx
  suite-native/module-send/src/hooks/useTokenOfNetworkAlert.tsx
  suite-native/module-send/tsconfig.json
  yarn.lock
Labels: mobile

#15168 Decrease Backdrop z-index
  packages/components/src/components/modals/Modal/Backdrop.tsx
  packages/theme/src/zIndices.ts
Labels: bug, components, release

#15120 feat(suite-native): send token drafts
  packages/suite/src/actions/wallet/send/sendFormThunks.ts
  packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx
  suite-common/wallet-core/src/send/sendFormActions.ts
  suite-common/wallet-core/src/send/sendFormReducer.ts
  suite-common/wallet-types/src/index.ts
  suite-common/wallet-types/src/send.ts
  suite-common/wallet-utils/src/sendFormUtils.ts
  suite-native/module-send/src/components/AddressReviewStepList.tsx
  suite-native/module-send/src/components/OutputsReviewFooter.tsx
  suite-native/module-send/src/components/ReviewOutputItemList.tsx
  suite-native/module-send/src/components/ReviewOutputSummaryItem.tsx
  suite-native/module-send/src/screens/SendAddressReviewScreen.tsx
  suite-native/module-send/src/screens/SendOutputsScreen.tsx
  suite-native/module-send/src/selectors.ts
  suite-native/module-send/src/sendFormThunks.ts
Labels: mobile

#15171 fix(suite-native): CryptoIcon in send
  suite-native/module-send/src/hooks/useTokenOfNetworkAlert.tsx
Labels: mobile

#15170 feat(suite-native): enhance layout of the account import summary screen
  suite-native/intl/src/en.ts
  suite-native/module-accounts-import/src/components/AccountAlreadyImportedScreen.tsx
  suite-native/module-accounts-import/src/components/AccountImportConfirmFormScreen.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummary.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryScreen.tsx
  suite-native/module-accounts-import/src/screens/AccountImportSummaryScreen.tsx
Labels: mobile

#15192 fix(coinmarket): Confirm on Trezor and Send button infinite loading while sell
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketSellForm.ts
Labels: +Invity

#15166 fix(suite-native): send minimal amount validation
  suite-native/module-send/src/sendFormThunks.ts
Labels: bug, mobile

#15172 chore(ci): check existing EAS builds before creating a new one
  .github/workflows/build-suite-native-preview.yml
Labels: ci, mobile, build-mobile

#15179 feat(suite-native): send address checksum
  suite-native/intl/src/en.ts
  suite-native/module-send/package.json
  suite-native/module-send/src/components/AddressChecksumMessage.tsx
  suite-native/module-send/src/components/AddressInput.tsx
  suite-native/module-send/src/components/TokenOfNetworkAlertContent.tsx
  suite-native/module-send/src/hooks/useAddressValidationAlerts.tsx
  suite-native/module-send/tsconfig.json
  yarn.lock
Labels: mobile

#15216 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#15142 fix(transport-bridge): synchronize was too strict, allow enumerate an…
  packages/transport/src/api/abstract.ts
  packages/transport/src/api/usb.ts
Labels: build-desktop

#15217 feat(suite): delete redundant buy button on the portfolio page
  packages/suite/src/views/dashboard/PortfolioCard/PortfolioCard.tsx
  packages/suite/src/views/dashboard/PortfolioCard/PortfolioCardHeader.tsx
Labels: +Invity

#15213 fix(trade): swap/sell all balance on a account
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketSellForm.ts
  packages/suite/src/hooks/wallet/useCoinmarketRecomposeAndSign.ts
Labels: bug, +Invity

#15186 fix(suite-native): revise navigation and spacing of the Sync my coins flow
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/intl/src/en.ts
  suite-native/module-accounts-import/src/components/AccountAlreadyImportedScreen.tsx
  suite-native/module-accounts-import/src/components/AccountImportConfirmFormScreen.tsx
  suite-native/module-accounts-import/src/components/AccountImportOverview.tsx
  suite-native/module-accounts-import/src/components/AccountImportOverviewCard.tsx
  suite-native/module-accounts-import/src/components/AccountImportSubHeader.tsx
  suite-native/module-accounts-import/src/components/TokenInfoCard.tsx
  suite-native/module-accounts-import/src/navigation/AccountsImportStackNavigator.tsx
  suite-native/module-accounts-import/src/screens/AccountImportLoadingScreen.tsx
  suite-native/module-accounts-import/src/screens/AccountImportSummaryScreen.tsx
  suite-native/module-accounts-import/src/screens/SelectNetworkScreen.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx
  suite-native/navigation/src/index.ts
  suite-native/navigation/src/useNavigateToInitialScreen.ts
Labels: mobile

#15212 fix(trade): crashing app
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketInfo/CoinmarketInfoHeader.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketInfo/CoinmarketInfoItem.tsx
Labels: bug, +Invity

#15244 fix(suite): copy to clipboard
  packages/suite/src/components/suite/modals/ReduxModal/CopyAddressModal.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketTransactionId.tsx
Labels: release

#15249 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite/src/support/messages.ts
Labels: translations

#15250 Bump beta version to 24.12.0
  packages/suite/package.json
Labels: deployment

#15251 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
Labels: translations

#15174 feat(suite-native): for only passphrase remembered add also standard wallet
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/device-manager/package.json
  suite-native/device-manager/src/components/WalletItem.tsx
  suite-native/device-manager/tsconfig.json
  suite-native/device/src/middlewares/deviceMiddleware.ts
  yarn.lock
Labels: mobile

#15207 fix(suite-native): track btc firmware instead of btc device to analytics
  suite-native/device/src/hooks/useReportDeviceConnectToAnalytics.ts
Labels: mobile

#15236 refactor(suite-native): replace useAuthorizationGoBack with navigateToInitialScreen
  suite-native/device-authorization/src/hooks/useAuthorizationGoBack.ts
  suite-native/device-authorization/src/index.ts
  suite-native/module-authorize-device/src/components/passphrase/NoPassphraseButton.tsx
  suite-native/module-authorize-device/src/components/passphrase/PassphraseScreenHeader.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseEnableOnDeviceScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseEnterOnTrezorScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseFeatureUnlockFormScreen.tsx
  suite-native/module-authorize-device/src/useRedirectOnPassphraseCompletion.ts
  suite-native/navigation/src/useNavigateToInitialScreen.ts
Labels: mobile

#15256 fix(suite-desktop-core): tray update setting when window open, left click on windows
  packages/suite-desktop-api/src/api.ts
  packages/suite-desktop-api/src/validation.ts
  packages/suite-desktop-core/src/app.ts
  packages/suite-desktop-core/src/modules/index.ts
  packages/suite-desktop-core/src/modules/tray.ts
  packages/suite/src/views/settings/SettingsGeneral/ShowOnTray.tsx
Labels: build-desktop

#15263 feat(suite-native): only download token definitions for relevant networks
  suite-native/discovery/package.json
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/discovery/src/discoveryMiddleware.ts
  suite-native/discovery/tsconfig.json
  suite-native/module-accounts-import/src/accountsImportThunks.ts
  suite-native/state/package.json
  suite-native/state/src/extraDependencies.ts
  suite-native/state/tsconfig.json
  suite-native/tokens/src/tokensSelectors.ts
  yarn.lock
Labels: mobile

#15234 fix(suite-native): revise and unify spacing of account-related screens
  suite-native/accounts/src/components/SearchableAccountsListScreenHeader.tsx
  suite-native/module-accounts-import/src/components/AccountImportConfirmFormScreen.tsx
  suite-native/module-accounts-management/src/components/AccountDetailScreenHeader.tsx
  suite-native/module-accounts-management/src/components/CoinPriceCard.tsx
  suite-native/module-accounts-management/src/components/IncludeTokensToggle.tsx
  suite-native/module-accounts-management/src/screens/AccountSettingsScreen.tsx
  suite-native/module-accounts-management/src/screens/AccountsScreen/AccountsScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
  suite-native/module-receive/src/screens/ReceiveAccountsScreen.tsx
  suite-native/receive/src/components/ReceiveAccount.tsx
  suite-native/receive/src/screens/ReceiveModalScreen.tsx
  suite-native/transactions/src/components/TransactionsEmptyState.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionList.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
Labels: mobile

#15274 feat(suite-desktop): autostat option only in debug
  packages/suite/src/views/settings/SettingsGeneral/SettingsGeneral.tsx
  packages/suite/src/views/suite/bridge-requested/index.tsx
Labels: release

#15210 chore: update node-gyp to v10
  .github/workflows/build-desktop-apps.yml
  package.json
  yarn.lock
Labels: build-desktop

#15286 feat(suite-native): whitelist pol and bnb and remove feature flags
  suite-native/config/src/supportedNetworks.ts
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
Labels: mobile

#15283 fix(trade): buy input decimals
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputFiatCrypto/CoinmarketFormInputCryptoAmount.tsx
Labels: bug, +Invity, release

#15302 fix(suite-desktop-core): is autostart enabled condition on windows
  packages/suite-desktop-core/src/modules/auto-start.ts
Labels: release, build-desktop

#15313 chore(suite-native): bump app version to 24.11.1
  suite-native/app/package.json
Labels: mobile

#15320 fix(suite-native): txn detail visual fixes
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx
Labels: mobile

#15317 fix(suite): workers not loading in electron
  packages/suite-desktop-core/src/app.ts
Labels: release, build-desktop

#15282 feat(suite-native): sort networks according to networksConfig
  suite-native/accounts/src/utils.ts
  suite-native/assets/src/assetsSelectors.ts
  suite-native/config/src/supportedNetworks.ts
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
Labels: mobile

#15319 feat(suite-native): bitcoin and ethereum send enabled
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-accounts-management/package.json
  suite-native/module-accounts-management/src/selectors.ts
  suite-native/module-accounts-management/tsconfig.json
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  yarn.lock
Labels: mobile

#15303 fix(suite-native): send transaction detail redirect
  suite-common/wallet-core/src/send/sendFormThunks.ts
  suite-native/module-send/src/components/OutputsReviewFooter.tsx
Labels: mobile

#15342 fix(suite-native): redirect to token send on review cancel
  suite-native/module-send/src/components/AddressReviewStepList.tsx
Labels: mobile

#15330 feat(suite-native): show placeholder when standard wallet is not present
  suite-native/device-manager/package.json
  suite-native/device-manager/src/components/WalletItem.tsx
  suite-native/device-manager/src/components/WalletItemBase.tsx
  suite-native/device-manager/src/components/WalletList.tsx
  suite-native/device/src/selectors.ts
  yarn.lock
Labels: mobile

#15347 Add type check to messages.ts and fix translations
  docs/features/localization.md
  packages/suite-desktop-ui/src/support/DesktopUpdater/Available.tsx
  packages/suite-desktop-ui/src/support/DesktopUpdater/JustUpdated.tsx
  packages/suite/src/components/wallet/TransactionItem/InstantStakeBadge.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/suite/homescreen.ts
  packages/suite/src/utils/suite/validation.ts
  packages/suite/src/views/dashboard/PromoBanner.tsx
  packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx
  packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/InstantStakeBanner.tsx
  suite-common/wallet-utils/src/accountUtils.ts
Labels: bug, translations

#15344 feat(suite-native): fetch token definitions while importing account
  suite-native/module-accounts-import/src/accountsImportThunks.ts
Labels: mobile

#15357 chore(suite-native): bump native to 24.11.2
  suite-native/app/package.json
Labels: mobile

#15370 fix(suite-native): send token analytics
  suite-native/module-send/src/components/OutputsReviewFooter.tsx
Labels: mobile, release-native

#15371 fix(mobile): update staking data on mobile
  suite-native/app/src/initActions.ts
  suite-native/module-staking-management/package.json
  suite-native/module-staking-management/redux.d.ts
  suite-native/module-staking-management/src/screens/StakingDetailScreen.tsx
  suite-native/state/src/reducers.ts
  yarn.lock
Labels: mobile

#15375 fix(connect): remove unwanted acquire in case when deriveCardano chan…
  packages/connect/src/device/Device.ts
Labels: release-native

#15372 fix(mobile): update staking data on mobile
  suite-native/module-staking-management/src/screens/StakingDetailScreen.tsx
Labels: mobile

#15379 fix(suite-native): only fetch token defs for supported portfolio networks
  suite-native/module-accounts-import/src/accountsImportThunks.ts
Labels: mobile

#15402 Skip storing draft in RBF form, reintroduce precomposedForm
  packages/suite/src/actions/wallet/send/sendFormThunks.ts
  packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx
  packages/suite/src/reducers/wallet/__tests__/sendFormReducer.test.ts
  suite-common/wallet-core/src/send/sendFormActions.ts
  suite-common/wallet-core/src/send/sendFormReducer.ts
  suite-common/wallet-core/src/send/sendFormThunks.ts
Labels: bug, send

#15331 feat(suite-native): add authenticity check to device settings
  packages/suite/src/constants/suite/device.ts
  packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx
  packages/suite/src/views/settings/SettingsDevice/SettingsDevice.tsx
  scripts/list-outdated-dependencies/mobile-dependencies.txt
  suite-common/icons/generateIconFont.ts
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.json
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.ttf
  suite-common/suite-constants/src/device.ts
  suite-native/app/app.config.ts
  suite-native/app/globalPolyfills.js
  suite-native/app/package.json
  suite-native/atoms/src/IconListItem.tsx
  suite-native/atoms/src/Pictogram.tsx
  suite-native/atoms/src/index.ts
  suite-native/device-manager/src/components/DeviceSettingsButton.tsx
  suite-native/device/src/hooks/useDetectDeviceError.tsx
  suite-native/icons/src/Icon.tsx
  suite-native/intl/src/en.ts
  suite-native/link/src/constants.ts
  suite-native/link/src/index.ts
  suite-native/module-device-settings/package.json
  suite-native/module-device-settings/src/components/DeviceAuthenticityCard.tsx
  suite-native/module-device-settings/src/components/DeviceFirmwareCard.tsx
  suite-native/module-device-settings/src/components/DevicePinProtectionCard.tsx
  suite-native/module-device-settings/src/components/DeviceSettingsCardLayout.tsx
  suite-native/module-device-settings/src/navigation/DeviceAuthenticityStackNavigator.tsx
  suite-native/module-device-settings/src/navigation/DeviceSettingsStackNavigator.tsx
  suite-native/module-device-settings/src/screens/DeviceAuthenticitySummaryScreen.tsx
  suite-native/module-device-settings/src/screens/DeviceSettingsModalScreen.tsx
  suite-native/module-device-settings/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#15436 fix(mobile): missing date 📅 for transactions
  suite-native/notifications/src/components/TransactionNotification.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailInputsSheet.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
Labels: mobile

#15437 chore(suite-native): bump native to 24.11.3
  suite-native/app/package.json
Labels: mobile

#15435 Fix cancel button in second step of dry run recovery
  packages/suite/src/views/recovery/index.tsx
Labels: bug

#15383 chore(mobile) : expo upgrade sdk 52 🚀
  jest.config.native.js
  package.json
  packages/connect-examples/mobile-expo/package.json
  packages/react-native-usb/android/build.gradle
  packages/react-native-usb/src/ReactNativeUsbModule.ts
  packages/react-native-usb/src/index.ts
  packages/styles/package.json
  patches/README.md
  patches/react-native-quick-crypto+0.7.6.patch
  suite-native/accounts/package.json
  suite-native/alerts/package.json
  suite-native/app/app.config.ts
  suite-native/app/package.json
  suite-native/app/src/SentryProvider.tsx
  suite-native/app/src/snow/Snow.tsx
  suite-native/app/src/snow/Snowflake.tsx
  suite-native/assets/package.json
  suite-native/atoms/package.json
  suite-native/biometrics/package.json
  suite-native/coin-enabling/package.json
  suite-native/connection-status/package.json
  suite-native/device-manager/package.json
  suite-native/device/package.json
  suite-native/feature-flags/package.json
  suite-native/formatters/package.json
  suite-native/forms/package.json
  suite-native/graph/package.json
  suite-native/helpers/package.json
  suite-native/icons/package.json
  suite-native/message-system/package.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-management/package.json
  suite-native/module-add-accounts/package.json
  suite-native/module-authorize-device/package.json
  suite-native/module-connect-popup/package.json
  suite-native/module-dev-utils/package.json
  suite-native/module-device-settings/package.json
  suite-native/module-device-settings/tsconfig.json
  suite-native/module-home/package.json
  suite-native/module-onboarding/package.json
  suite-native/module-receive/package.json
  suite-native/module-send/package.json
  suite-native/module-settings/package.json
  suite-native/module-staking-management/package.json
  suite-native/navigation/package.json
  suite-native/notifications/package.json
  suite-native/qr-code/package.json
  suite-native/react-native-graph/package.json
  suite-native/receive/package.json
  suite-native/state/package.json
  suite-native/storage/package.json
  suite-native/test-utils/package.json
  suite-native/test-utils/src/setupReactReanimatedMock.js
  suite-native/theme/package.json
  suite-native/transactions/package.json
  suite-native/video-assets/package.json
  yarn.lock
Labels: mobile

#15446 test(suite-native): add e2e test for device authenticity check
  suite-native/app/e2e/pageObjects/bottomSheetActions.ts
  suite-native/app/e2e/pageObjects/deviceAuthenticitySummary.ts
  suite-native/app/e2e/pageObjects/deviceSettingsActions.ts
  suite-native/app/e2e/tests/deviceSettings.test.ts
  suite-native/app/e2e/utils.ts
  suite-native/module-device-settings/src/components/DeviceAuthenticityCard.tsx
  suite-native/module-device-settings/src/screens/DeviceAuthenticitySummaryScreen.tsx
Labels: mobile

#15461 fix(suite-native): always show portfolio graph during discovery
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraph.tsx
Labels: mobile

#15459 test(suite-native): send custom fee e2e
  suite-native/app/e2e/pageObjects/send/sendFeesActions.ts
  suite-native/app/e2e/tests/send.test.ts
  suite-native/module-send/src/components/CustomFee.tsx
  suite-native/module-send/src/components/CustomFeeBottomSheet.tsx
  suite-native/module-send/src/components/CustomFeeInputs.tsx
Labels: mobile

#15401 fix(trade): pending transaction and re-requesting
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeWatchSendApproval.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketOfferExchange/CoinmarketOfferExchangeSendApproval.tsx
Labels: bug, +Invity

#15495 fix(suite-native): ensure that passphrase retry flow finishes correctly
  suite-native/device-authorization/src/passphraseThunks.ts
Labels: mobile

#15528 fix(suite-native): prevent error Cannot read property 'addresses' of undefined
  suite-native/transactions/src/selectors.ts
Labels: sentry, mobile

#15545 fix: getAccountInfo useDevice state fix
  packages/connect/src/api/getAccountInfo.ts
Labels: build-desktop

#15560 Prevent text wrapping in NotificationCard's Button
  packages/suite/src/components/suite/NotificationCard.tsx
Labels: UI

#15325 chore(suite-analytics): remove suite-analytics from common code
  packages/suite/src/actions/firmware/__fixtures__/firmwareActions.ts
  packages/suite/src/middlewares/suite/analyticsMiddleware.ts
  suite-common/wallet-core/package.json
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-common/wallet-core/src/firmware/firmwareThunks.ts
  suite-common/wallet-core/tsconfig.json
  yarn.lock
Labels: data, code, monorepo

#15454 feat(suite-native): Ripple send
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/analytics/src/types.ts
  suite-native/app/e2e/pageObjects/send/sendOutputsReviewActions.ts
  suite-native/atoms/src/Hint.tsx
  suite-native/atoms/src/Input/InputWrapper.tsx
  suite-native/intl/src/en.ts
  suite-native/module-send/src/components/AddressReviewStepList.tsx
  suite-native/module-send/src/components/AmountErrorMessage.tsx
  suite-native/module-send/src/components/AmountInputs.tsx
  suite-native/module-send/src/components/DestinationTagInput.tsx
  suite-native/module-send/src/components/FeeOption.tsx
  suite-native/module-send/src/components/OutputsReviewFooter.tsx
  suite-native/module-send/src/components/RecipientInputs.tsx
  suite-native/module-send/src/components/ReviewDestinationTagCard.tsx
  suite-native/module-send/src/components/ReviewOutputItem.tsx
  suite-native/module-send/src/components/ReviewOutputItemContent.tsx
  suite-native/module-send/src/components/ReviewOutputItemList.tsx
  suite-native/module-send/src/components/SendFeesForm.tsx
  suite-native/module-send/src/components/SendScreenSubHeader.tsx
  suite-native/module-send/src/components/SlidingFooterOverlay.tsx
  suite-native/module-send/src/hooks/useHandleOnDeviceTransactionReview.tsx
  suite-native/module-send/src/hooks/useHandleSendReviewFailure.tsx
  suite-native/module-send/src/hooks/useSendAmountTransformers.ts
  suite-native/module-send/src/navigation/SendStackNavigator.tsx
  suite-native/module-send/src/screens/SendAddressReviewScreen.tsx
  suite-native/module-send/src/screens/SendDestinationTagReviewScreen.tsx
  suite-native/module-send/src/screens/SendOutputsScreen.tsx
  suite-native/module-send/src/selectors.ts
  suite-native/module-send/src/sendFormSlice.ts
  suite-native/module-send/src/sendOutputsFormSchema.ts
  suite-native/module-send/src/utils.ts
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/navigation/src/useReportSendFlowExitToAnalytics.ts
Labels: mobile

#15557 chore(suite-native): expo-video
  scripts/list-outdated-dependencies/mobile-dependencies.txt
  suite-native/app/app.config.ts
  suite-native/app/package.json
  suite-native/video-assets/package.json
  suite-native/video-assets/src/components/Video.tsx
  yarn.lock
Labels: mobile

#15562 fix(suite-native): unmemoized selectors
  suite-native/assets/src/assetsSelectors.ts
  suite-native/tokens/src/tokensSelectors.ts
Labels: mobile

#15590 chore(suite): update network symbol naming
  packages/product-components/src/components/SelectAssetModal/AssetItem.tsx
  packages/product-components/src/components/SelectAssetModal/SelectAssetModal.stories.tsx
  packages/product-components/src/components/SelectAssetModal/SelectAssetModal.storiesData.ts
  packages/product-components/src/components/SelectAssetModal/SelectAssetModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/ConfirmAddressModal.tsx
  packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketFiatValues.tsx
  packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketFormActions.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeFormDefaultValues.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketSellFormDefaultValues.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketVerifyAccount.tsx
  packages/suite/src/hooks/wallet/coinmarket/useCoinmarketInfo.ts
  packages/suite/src/types/coinmarket/coinmarket.ts
  packages/suite/src/types/coinmarket/coinmarketVerify.ts
  packages/suite/src/utils/wallet/coinmarket/coinmarketUtils.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketAddressOptions.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketBalance.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputAccount.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputCryptoSelect.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputFiatCrypto/CoinmarketFormInputCryptoAmount.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInputs.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormOfferCryptoAmount.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerifyOptionsItem.tsx
  packages/suite/src/views/wallet/send/Outputs/TokenSelect/TokenSelect.tsx
  suite-common/wallet-utils/src/__tests__/filterReceiveAccounts.test.ts
  suite-common/wallet-utils/src/filterReceiveAccounts.ts
Labels: chore

#15592 fix(mobile): fix skia crash 💥
  suite-native/app/package.json
  suite-native/atoms/package.json
  suite-native/graph/package.json
  suite-native/icons/package.json
  suite-native/module-accounts-import/package.json
  suite-native/react-native-graph/package.json
  suite-native/receive/package.json
  suite-native/transactions/package.json
  yarn.lock
Labels: mobile

#15521 feat(suite-native): advanced recipient address validation
  suite-native/forms/src/hooks/useField.ts
  suite-native/module-send/src/components/AddressInput.tsx
  suite-native/module-send/src/components/SendMaxButton.tsx
  suite-native/module-send/src/screens/SendOutputsScreen.tsx
  suite-native/module-send/src/sendOutputsFormSchema.ts
Labels: mobile

#15128 feat(tokens): Add relevant swap/buy/sell buttons to Tokens list
  packages/components/src/components/Dropdown/Dropdown.tsx
  packages/suite/src/actions/wallet/coinmarket/coinmarketCommonActions.ts
  packages/suite/src/actions/wallet/constants/coinmarketCommonConstants.ts
  packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketBuildAccountGroups.ts
  packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketFormActions.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketBuyFormDefaultValues.tsx
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeFormDefaultValues.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketSellFormDefaultValues.ts
  packages/suite/src/middlewares/wallet/coinmarketMiddleware.ts
  packages/suite/src/reducers/wallet/coinmarketReducer.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/wallet/coinmarket/__fixtures__/coinmarketUtils.ts
  packages/suite/src/utils/wallet/coinmarket/__tests__/coinmarketUtils.test.ts
  packages/suite/src/utils/wallet/coinmarket/coinmarketUtils.ts
  packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRow.tsx
  packages/suite/src/views/wallet/tokens/common/TokensTable/TokensTable.tsx
Labels: +Invity
