Repository trezor/trezor-suite, pull requests merged in 2024-05, with the labels that each got.

#12245 chore(suite-native): reverse-ports app script
  suite-native/app/README.md
  suite-native/app/package.json
Labels: mobile-app

#12242 fix(suite-native): transaction missing data ui error
  suite-native/transactions/src/components/TransactionDetail/NetworkTransactionDetailSummary.tsx
Labels: mobile-app

#12267 fix(suite): eth staking banner on btc only fw when eth enabled
  packages/suite/src/views/dashboard/components/StakeEthCard/StakeEthCard.tsx
Labels: release

#12290 chore(suite-native): allow network filtering on develop during discovery
  suite-native/discovery/src/discoveryThunks.ts
Labels: mobile

#12285 fix(suite): Fix tooltip on hover
  packages/suite/src/actions/suite/__fixtures__/suiteActions.ts
  packages/suite/src/components/suite/Preloader/Preloader.tsx
  packages/suite/src/components/suite/modals/ModalSwitcher/ForegroundAppModal.tsx
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/views/settings/SettingsDebug/SettingsDebug.tsx
  packages/suite/src/views/settings/SettingsDebug/ViewOnlySettings.tsx
  packages/suite/src/views/settings/SettingsDevice/SettingsDevice.tsx
  packages/suite/src/views/view-only/ViewOnlyTooltip.tsx
Labels: build-desktop

#12287 Crowdin translations update
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/he.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#12284 Stable: Solana token list
  packages/blockchain-link-utils/package.json
  packages/blockchain-link-utils/src/solana.ts
  packages/blockchain-link-utils/tsconfig.json
  packages/blockchain-link-utils/tsconfig.lib.json
  packages/connect-iframe/webpack/base.webpack.config.ts
  yarn.lock
Labels: release, build-desktop

#12327 chore(suite-native): change device naming to model name
  suite-common/icons/assets/icons/trezorT1B1.svg
  suite-common/icons/assets/icons/trezorT2B1.svg
  suite-common/icons/assets/icons/trezorT2T1.svg
  suite-common/icons/assets/icons/trezorT3T1.svg
  suite-common/icons/src/icons.ts
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-passphrase/src/assets/DeviceT2B1Svg.tsx
  suite-native/module-passphrase/src/screens/PassphraseConfirmOnTrezorScreen.tsx
  suite-native/module-settings/src/components/SupportSettings.tsx
  suite-native/module-settings/src/components/TrezorModelIcon.tsx
  suite-native/module-settings/src/components/ViewOnly/TrezorModelIcon.tsx
Labels: mobile

#12348 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite/src/support/messages.ts
Labels: translations

#12333 feat(suite-native): enter passphrase on trezor
  suite-native/atoms/src/TextDivider.tsx
  suite-native/intl/src/en.ts
  suite-native/module-accounts-import/src/components/DevXpub.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-passphrase/src/components/EnterPassphraseOnTrezorButton.tsx
  suite-native/module-passphrase/src/components/PassphraseForm.tsx
  suite-native/module-passphrase/src/navigation/PassphraseStackNavigator.tsx
  suite-native/module-passphrase/src/screens/PassphraseEnterOnTrezorScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseFormScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
Labels: mobile

#12338 feat(suite-native): reauthorize device
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-native/device/src/hooks/useHandleDeviceRequestsPassphrase.ts
  suite-native/module-passphrase/src/passphraseThunks.ts
  suite-native/module-passphrase/src/screens/PassphraseEmptyWalletScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseVerifyEmptyWalletScreen.tsx
Labels: mobile

#12358 fix(suite-native): tiny passphrase flow fixes
  suite-native/intl/src/en.ts
  suite-native/module-passphrase/src/components/PassphraseForm.tsx
  suite-native/module-passphrase/src/screens/PassphraseEmptyWalletScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseVerifyEmptyWalletScreen.tsx
Labels: mobile

#12363 feat(suite-native): forget device when view only disabled
  suite-native/module-settings/src/components/ViewOnly/WalletRow.tsx
Labels: mobile

#12214 Bump beta version to 24.6.0
  packages/suite/package.json
Labels: deployment

#12355 test(suite-desktop-core): add comment describing how to run the legac…
  packages/suite-desktop-core/e2e/support/common.ts
Labels: e2e

#12370 refactor(suite-native): passphrase screen
  suite-native/module-passphrase/src/components/PassphraseContentScreen.tsx
  suite-native/module-passphrase/src/components/PassphraseScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseConfirmOnTrezorScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseEmptyWalletScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseEnterOnTrezorScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseFormScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseLoadingScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseVerifyEmptyWalletScreen.tsx
Labels: mobile

#12392 fix(suite-native): passphrase screen naming
  suite-native/module-passphrase/src/components/PassphraseContentScreenWrapper.tsx
  suite-native/module-passphrase/src/components/PassphraseScreenWrapper.tsx
  suite-native/module-passphrase/src/screens/PassphraseConfirmOnTrezorScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseEmptyWalletScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseEnterOnTrezorScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseFormScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseLoadingScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseVerifyEmptyWalletScreen.tsx
Labels: mobile

#12300 feat(suite-native): new device switcher
  suite-common/icons/assets/icons/linkChain.svg
  suite-common/icons/assets/icons/linkChainBroken.svg
  suite-common/icons/src/icons.ts
  suite-common/suite-utils/src/device.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/atoms/src/TextDivider.tsx
  suite-native/device-manager/package.json
  suite-native/device-manager/src/components/AddHiddenWalletButton.tsx
  suite-native/device-manager/src/components/DeviceAction.tsx
  suite-native/device-manager/src/components/DeviceControlButtons.tsx
  suite-native/device-manager/src/components/DeviceInfoButton.tsx
  suite-native/device-manager/src/components/DeviceItem.tsx
  suite-native/device-manager/src/components/DeviceItem/ConnectionDot.tsx
  suite-native/device-manager/src/components/DeviceItem/DeviceItem.tsx
  suite-native/device-manager/src/components/DeviceItem/DeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceItem/DeviceItemIcon.tsx
  suite-native/device-manager/src/components/DeviceItem/SimpleDeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceItem/WalletDetailDeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceList.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/device-manager/src/components/DeviceManagerModal.tsx
  suite-native/device-manager/src/components/DeviceModelIcon.tsx
  suite-native/device-manager/src/components/DeviceSwitch.tsx
  suite-native/device-manager/src/components/DevicesToggleButton.tsx
  suite-native/device-manager/src/components/PortfolioTrackerDeviceManagerContent.tsx
  suite-native/device-manager/src/components/WalletItem.tsx
  suite-native/device-manager/src/components/WalletList.tsx
  suite-native/device-manager/src/index.ts
  suite-native/device-manager/tsconfig.json
  suite-native/device/package.json
  suite-native/device/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-settings/src/components/TrezorModelIcon.tsx
  suite-native/module-settings/src/components/ViewOnly/DevicesManagement.tsx
  suite-native/module-settings/src/components/ViewOnly/TrezorModelIcon.tsx
  suite-native/module-settings/src/components/ViewOnly/WalletRow.tsx
  yarn.lock
Labels: mobile

#12439 Crowdin translations update
  packages/suite-data/files/translations/ar.json
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/da.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/sv.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#12455 fix(suite-native): view only pimping
  suite-native/atoms/src/Divider.tsx
  suite-native/device-manager/src/components/DeviceItem/ConnectionDot.tsx
  suite-native/device-manager/src/index.ts
  suite-native/module-settings/src/components/ViewOnly/DevicesManagement.tsx
  suite-native/module-settings/src/components/ViewOnly/WalletRow.tsx
Labels: mobile

#12458 fix(suite-native): dont show remember banner after disabled
  suite-native/module-settings/src/components/ViewOnly/WalletRow.tsx
Labels: mobile

#12461 fix(suite-native): show address view only
  suite-native/receive/src/components/ShowAddressButtons.tsx
Labels: mobile

#12465 chore(suite-native): longer timeout for test
  suite-native/app/e2e/tests/onboardAndConnect.test.ts
Labels: mobile

#12469 fix(mobile): wrong graph after device switch and then refetch
  suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraph.tsx
  suite-native/module-home/src/screens/HomeScreen/useHomeRefreshControl.tsx
Labels: mobile

#12479 Fix view only persistance
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-common/wallet-core/src/discovery/discoveryReducer.ts
  suite-native/app/src/initActions.ts
  suite-native/device/src/deviceThunks.ts
  suite-native/device/src/index.ts
  suite-native/device/src/middlewares/deviceMiddleware.ts
  suite-native/graph/src/slice.ts
Labels: mobile

#12477 fix(suite-native): useEmptyPassphrase on undefined device instance
  suite-common/wallet-core/src/device/deviceReducer.ts
Labels: mobile

#12489 fix(mobile): fix infinite loading of XRP
  suite-common/transaction-cache-engine/package.json
  suite-common/transaction-cache-engine/src/TransactionCacheEngine.ts
  suite-common/transaction-cache-engine/src/tests/TransactionCacheEngine.test.ts
  suite-common/transaction-cache-engine/tsconfig.json
  suite-native/app/package.json
  suite-native/app/src/initActions.ts
  suite-native/app/tsconfig.json
  yarn.lock
Labels: mobile

#12492 ci(suite-native): upgrade setup-java e2e workflow
  .github/workflows/test-suite-native-e2e-android.yml
Labels: mobile

#12503 feat(suite-native): faq copy
  suite-native/intl/src/en.ts
  suite-native/module-settings/src/components/FAQInfoPanel.tsx
Labels: mobile, release-native

#12508 feat(suite-native): TextInput secure text does not prompt autofill
  suite-native/forms/src/fields/TextInputField.tsx
Labels: mobile

#12452 fix(suite-native): device switcher pimping
  suite-native/atoms/src/TextDivider.tsx
  suite-native/device-manager/src/components/AddHiddenWalletButton.tsx
  suite-native/device-manager/src/components/DeviceItem/DeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceItem/DeviceItemIcon.tsx
  suite-native/device-manager/src/components/DeviceItem/SimpleDeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceItem/WalletDetailDeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceList.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/device-manager/src/components/DeviceManagerModal.tsx
  suite-native/device-manager/src/components/DeviceSwitch.tsx
  suite-native/device-manager/src/components/WalletItem.tsx
  suite-native/device-manager/src/components/WalletList.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseEmptyWalletScreen.tsx
Labels: mobile, release-native

#12509 fix(suite-native): locks the app orientation in a portrait mode
  suite-native/app/app.config.ts
Labels: mobile

#12529 feat(suite-native): remove tracker subtitle from closed switcher
  suite-native/device-manager/src/components/DeviceItem/DeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceItem/SimpleDeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceSwitch.tsx
Labels: mobile, release-native

#12534 fix(suite-native): animation on accordion
  suite-native/atoms/src/Accordion/AccordionItem.tsx
  suite-native/atoms/src/Accordion/useAccordionAnimation.ts
  suite-native/atoms/src/AccordionItem.tsx
  suite-native/atoms/src/index.ts
  suite-native/module-settings/src/components/FAQInfoPanel.tsx
Labels: mobile, release-native

#12539 Fix and refactor selectors for empty device states
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/device-manager/src/components/DeviceItem/DeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceItem/SimpleDeviceItemContent.tsx
  suite-native/device-manager/src/components/PortfolioTrackerDeviceManagerContent.tsx
  suite-native/device/src/hooks/useDetectDeviceError.tsx
  suite-native/device/src/selectors.ts
  suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyHomeRenderer.tsx
  suite-native/module-home/src/screens/HomeScreen/useHomeRefreshControl.tsx
Labels: mobile, release-native

#12544 Feat/native/device switcher pimp
  suite-native/device-manager/src/components/DeviceList.tsx
Labels: mobile, release-native

#12519 fix(suite-native): orientation warning
  suite-native/app/app.config.ts
Labels: mobile

#12545 fix(suite-native): fix app freezed on click outside view only popup
  suite-native/module-home/src/screens/HomeScreen/components/EnableViewOnlyBottomSheet.tsx
Labels: mobile, release-native

#12548 fix(suite-native): accordion icon handler
  suite-native/atoms/src/Accordion/AccordionItem.tsx
Labels: mobile

#12567 chore(suite-native): longer e2e timeout for onboarding test
  suite-native/app/e2e/tests/onboardAndConnect.test.ts
Labels: mobile

#12588 test(suite-web): adapt e2e tests to changes in #12472
  packages/suite-web/e2e/tests/firmware/firmware.test.ts
Labels: e2e

#12611 chore(suite-native): upgrade app version
  suite-native/app/package.json
Labels: mobile

#12502 feat(suite-native): update passphrase copy
  suite-common/icons/package.json
  suite-common/icons/src/components/DeviceModelIcon.tsx
  suite-common/icons/src/index.ts
  suite-common/icons/tsconfig.json
  suite-native/device-manager/src/components/DeviceItem/DeviceItemIcon.tsx
  suite-native/device-manager/src/index.ts
  suite-native/intl/src/en.ts
  suite-native/module-passphrase/src/components/EnterPassphraseOnTrezorButton.tsx
  suite-native/module-passphrase/src/screens/PassphraseFormScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseLoadingScreen.tsx
  suite-native/module-passphrase/src/screens/PassphraseVerifyEmptyWalletScreen.tsx
  suite-native/module-settings/src/components/ViewOnly/DevicesManagement.tsx
  yarn.lock
Labels: mobile

#12526 feat(suite-native): enable passphrase on device
  packages/suite/src/actions/suite/__fixtures__/suiteActions.ts
  packages/suite/src/actions/suite/__tests__/suiteActions.test.ts
  packages/suite/src/components/suite/layouts/SuiteLayout/useAppShortcuts.tsx
  packages/suite/src/middlewares/suite/suiteMiddleware.ts
  packages/suite/src/reducers/suite/__fixtures__/deviceReducer.ts
  packages/suite/src/reducers/suite/__tests__/deviceReducer.test.ts
  packages/suite/src/views/dashboard/components/SecurityFeatures/index.tsx
  packages/suite/src/views/suite/SwitchDevice/DeviceItem/DeviceItem.tsx
  packages/suite/src/views/suite/SwitchDevice/DeviceItemLegacy/DeviceItem.tsx
  suite-common/wallet-core/src/device/deviceActions.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-native/device-manager/src/components/AddHiddenWalletButton.tsx
  suite-native/device/src/middlewares/deviceMiddleware.ts
  suite-native/intl/src/en.ts
  suite-native/module-passphrase/package.json
  suite-native/module-passphrase/src/navigation/PassphraseStackNavigator.tsx
  suite-native/module-passphrase/src/screens/PassphraseEnableOnDeviceScreen.tsx
  suite-native/module-passphrase/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/passphrase/src/passphraseSlice.ts
  suite-native/passphrase/src/useHandleDuplicatePassphrase.ts
  yarn.lock
Labels: mobile, build-desktop

#12654 fix(suite-native): analytics logs
  suite-native/analytics/src/analytics.ts
Labels: mobile

#12669 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite/src/support/messages.ts
Labels: translations

#12666 chore(mobile): Expo 51 + deps update
  jest.config.native.js
  package.json
  packages/styles/package.json
  suite-common/icons/package.json
  suite-native/accounts/package.json
  suite-native/alerts/package.json
  suite-native/app/README.md
  suite-native/app/app.config.ts
  suite-native/app/package.json
  suite-native/app/plugins/withGradleProperties.js
  suite-native/assets/package.json
  suite-native/atoms/package.json
  suite-native/biometrics/package.json
  suite-native/config/package.json
  suite-native/device-manager/package.json
  suite-native/device/package.json
  suite-native/feature-flags/package.json
  suite-native/formatters/package.json
  suite-native/graph/package.json
  suite-native/helpers/package.json
  suite-native/intl/package.json
  suite-native/message-system/package.json
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-management/package.json
  suite-native/module-add-accounts/package.json
  suite-native/module-connect-device/package.json
  suite-native/module-dev-utils/package.json
  suite-native/module-home/package.json
  suite-native/module-onboarding/package.json
  suite-native/module-passphrase/package.json
  suite-native/module-receive/package.json
  suite-native/module-send/package.json
  suite-native/module-settings/package.json
  suite-native/navigation/package.json
  suite-native/notifications/package.json
  suite-native/passphrase/package.json
  suite-native/qr-code/package.json
  suite-native/react-native-graph/package.json
  suite-native/receive/package.json
  suite-native/state/package.json
  suite-native/state/src/store.ts
  suite-native/storage/package.json
  suite-native/test-utils/package.json
  suite-native/test-utils/src/expoMock.js
  suite-native/theme/package.json
  suite-native/toasts/package.json
  suite-native/transactions/package.json
  suite-native/video-assets/package.json
  yarn.lock
Labels: mobile

#12655 feat(suite-native): when device error show correct alert
  suite-native/device/package.json
  suite-native/device/src/hooks/useDetectDeviceError.tsx
  suite-native/device/src/selectors.ts
  suite-native/intl/src/en.ts
  yarn.lock
Labels: mobile

#12680 chore(suite-native): correct dependency version
  suite-native/device/package.json
  yarn.lock
Labels: mobile
