Repository trezor/trezor-suite, pull requests merged in 2024-10, with the labels that each got.

#14644 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#14648 Change the EVM legacy discovery error on old firmware
  packages/suite/src/support/messages.ts
  packages/suite/src/views/dashboard/PortfolioCard/PortfolioCardException.tsx
Labels: build-desktop

#14663 fix(suite-native): use correct import path
  suite-native/module-accounts-management/src/accountDetailGraphAtoms.ts
Labels: mobile

#14660 fix(suite): migration-test
  packages/suite/src/storage/migrations/index.ts
Labels: e2e

#14633 feat(suite-native): make token selectors network agnostic
  suite-native/accounts/src/components/AccountsList/AccountsListTokenItem.tsx
  suite-native/assets/src/components/AssetItem.tsx
  suite-native/graph/src/components/TransactionEventTooltip.tsx
  suite-native/module-accounts-management/src/components/AccountDetailGraphHeader.tsx
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
  suite-native/module-accounts-management/src/screens/AccountDetailContentScreen.tsx
  suite-native/receive/src/components/TokenReceiveCard.tsx
  suite-native/receive/src/screens/ReceiveModalScreen.tsx
  suite-native/state/package.json
  suite-native/state/src/extraDependencies.ts
  suite-native/state/tsconfig.json
  suite-native/tokens/package.json
  suite-native/tokens/src/ethereumTokensSelectors.ts
  suite-native/tokens/src/index.ts
  suite-native/tokens/src/tokensSelectors.ts
  suite-native/tokens/src/types.ts
  suite-native/tokens/src/utils.ts
  suite-native/tokens/tsconfig.json
  suite-native/transactions/src/components/TransactionDetail/TokenTransactionDetailSummary.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailData.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailIncludedCoins.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailListItem.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailSummary.tsx
  suite-native/transactions/src/components/TransactionsList/TokenTransferListItem.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionList.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
  suite-native/transactions/src/screens/TransactionDetailScreen.tsx
  suite-native/transactions/src/selectors.ts
  yarn.lock
Labels: mobile

#14674 Bump beta version to 24.11.0
  packages/suite/package.json
Labels: deployment

#14680 fix(suite-native): align asset item values properly
  suite-native/accounts/src/components/AccountsList/AccountsListItemBase.tsx
Labels: mobile

#14685 fix(suite-native): ignore unknown URL schemes by connect popup
  suite-native/module-connect-popup/src/hooks/useConnectPopupNavigation.ts
Labels: mobile

#14683 fix(suite-native): send review old flow outputs
  suite-native/module-send/src/components/ReviewOutputItem.tsx
  suite-native/module-send/src/components/ReviewOutputItemContent.tsx
  suite-native/module-send/src/selectors.ts
Labels: mobile

#14689 refactor(suite-native): replace spacing literals with corresponding constants
  packages/theme/src/spacings.ts
  suite-native/accounts/src/components/AccountsList/AccountsListItemBase.tsx
  suite-native/accounts/src/components/SelectableNetworkItem.tsx
  suite-native/atoms/src/AlertBox.tsx
  suite-native/atoms/src/Badge.tsx
  suite-native/atoms/src/BottomSheetListItem.tsx
  suite-native/atoms/src/Button/Button.tsx
  suite-native/atoms/src/ScreenHeaderWrapper.tsx
  suite-native/atoms/src/Select/SelectTrigger.tsx
  suite-native/atoms/src/SelectableItem.tsx
  suite-native/atoms/src/Skeleton/ListItemSkeleton.tsx
  suite-native/atoms/src/TextDivider.tsx
  suite-native/biometrics/src/components/BiometricsIcon.tsx
  suite-native/coin-enabling/src/components/DiscoveryCoinsFilter.tsx
  suite-native/coin-enabling/src/components/NetworkSymbolSwitchItem.tsx
  suite-native/connection-status/src/OfflineBanner.tsx
  suite-native/device-manager/src/components/DeviceAction.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/device-manager/src/components/WalletItem.tsx
  suite-native/device-manager/src/components/WalletList.tsx
  suite-native/graph/src/components/PriceChangeIndicator.tsx
  suite-native/graph/src/components/TransactionEventTooltip.tsx
  suite-native/message-system/src/components/MessageBanner.tsx
  suite-native/message-system/src/components/MessageSystemBannerRenderer.tsx
  suite-native/module-accounts-management/src/components/CoinPriceCard.tsx
  suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseEmptyWalletScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseFormScreen.tsx
  suite-native/module-onboarding/src/components/AnalyticsInfoRow.tsx
  suite-native/module-onboarding/src/components/OnboardingScreenHeader.tsx
  suite-native/module-onboarding/src/screens/AnalyticsConsentScreen.tsx
  suite-native/module-onboarding/src/screens/WelcomeScreen.tsx
  suite-native/module-send/src/components/AddressInput.tsx
  suite-native/module-send/src/components/AddressReviewStep.tsx
  suite-native/module-send/src/components/AmountInputs.tsx
  suite-native/module-send/src/components/FeeOptionErrorMessage.tsx
  suite-native/module-send/src/components/FeeOptionsList.tsx
  suite-native/module-send/src/components/FeesFooter.tsx
  suite-native/module-send/src/components/RecipientsSummary.tsx
  suite-native/module-send/src/components/ReviewOutputCard.tsx
  suite-native/module-settings/src/components/TouchableSwitchRow.tsx
  suite-native/module-settings/src/components/ViewOnly/WalletRow.tsx
  suite-native/navigation/src/components/ScreenSubHeader.tsx
  suite-native/notifications/src/components/Notification.tsx
  suite-native/qr-code/src/components/QRCodeScanner.tsx
  suite-native/receive/src/components/ReceiveAccount.tsx
  suite-native/toasts/src/components/Toast.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailAddressesSection.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailSheets.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailSummary.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionIcon.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
Labels: mobile

#14575 refactor(coinmarket): replace useActions
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketBuyForm.tsx
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts
  packages/suite/src/types/coinmarket/coinmarketForm.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayout/CoinmarketAccountTransactions/ExchangeTransaction.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerify.tsx
Labels: +Invity, code

#14714 refactor(suite-native): use spacings constants for gap attributes
  suite-native/device-manager/src/components/DeviceItem/DeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/device-manager/src/components/WalletItem.tsx
  suite-native/module-add-accounts/src/screens/SelectAccountTypeScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseEmptyWalletScreen.tsx
  suite-native/module-settings/src/components/ViewOnly/DevicesManagement.tsx
Labels: mobile

#14710 refactor(suite-native): rename and add missing border radii constants
  packages/theme/src/borders.ts
  suite-native/accounts/src/components/AccountsList/AccountsListItemBase.tsx
  suite-native/alerts/src/components/AlertSheet.tsx
  suite-native/atoms/src/AlertBox.tsx
  suite-native/atoms/src/Card/Card.tsx
  suite-native/atoms/src/CheckBox.tsx
  suite-native/atoms/src/ErrorMessage.tsx
  suite-native/atoms/src/Input/Input.tsx
  suite-native/atoms/src/Input/SearchInput.tsx
  suite-native/atoms/src/OrderedListIcon.tsx
  suite-native/atoms/src/Select/SelectTrigger.tsx
  suite-native/atoms/src/SelectableItem.tsx
  suite-native/atoms/src/Sheet/BottomSheet.tsx
  suite-native/atoms/src/Skeleton/BoxSkeleton.tsx
  suite-native/atoms/src/Skeleton/ListItemSkeleton.tsx
  suite-native/atoms/src/StepsProgressBar.tsx
  suite-native/device-manager/src/components/DeviceAction.tsx
  suite-native/device-manager/src/components/DeviceManagerModal.tsx
  suite-native/device-manager/src/components/WalletItem.tsx
  suite-native/graph/src/components/GraphError.tsx
  suite-native/module-accounts-import/src/components/AccountImportOverviewCard.tsx
  suite-native/module-accounts-management/src/components/CoinPriceCard.tsx
  suite-native/module-authorize-device/src/components/passphrase/PassphraseForm.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseFormScreen.tsx
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/BiometricsBottomSheet.tsx
  suite-native/module-send/src/components/FeeOption.tsx
  suite-native/module-send/src/components/ReviewOutputCard.tsx
  suite-native/module-settings/src/components/ColorSchemePickerItem.tsx
  suite-native/qr-code/src/components/QRCodeScanner.tsx
  suite-native/receive/src/components/DevicePaginationButton.tsx
  suite-native/receive/src/components/UnverifiedAddressDevice.tsx
  suite-native/transactions/src/components/TransactionsEmptyState.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
  suite-native/video-assets/src/components/Video.tsx
Labels: mobile

#14694 feat(coinmarket): disable 'you buy' select in trezor btc only firmware
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx
  packages/suite/src/types/coinmarket/coinmarketForm.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputCryptoSelect.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInputs.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayout/CoinmarketLayoutNavigation.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayoutNew/CoinmarketLayoutNavigation/CoinmarketLayoutNavigation.tsx
  packages/suite/src/views/wallet/transactions/TradeBox/TradeBoxMenu.tsx
Labels: feature, +Invity

#14720 fix(suite-native): use 20px border radius instead of 24px
  packages/theme/src/borders.ts
  suite-native/atoms/src/Sheet/BottomSheet.tsx
  suite-native/graph/src/components/GraphError.tsx
  suite-native/module-accounts-import/src/components/AccountImportOverviewCard.tsx
  suite-native/module-authorize-device/src/components/passphrase/PassphraseForm.tsx
  suite-native/transactions/src/components/TransactionsEmptyState.tsx
  suite-native/video-assets/src/components/Video.tsx
Labels: mobile

#14676 chore(suite): update security check URLs
  packages/suite/src/components/suite/SecurityCheck/DeviceCompromised.tsx
  packages/suite/src/components/suite/SecurityCheck/SecurityCheckFail.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AuthenticateDeviceFailModal.tsx
  packages/suite/src/views/onboarding/steps/SecurityCheck/DeviceAuthenticity.tsx
  packages/urls/src/urls.ts
Labels: release

#14727 fix(suite-desktop): app reset on mac
  packages/suite-desktop-core/src/libs/app-utils.ts
Labels: build-desktop

#14705 fix(suite): fix DOM nesting (div child of p)
  packages/components/src/components/CollapsibleBox/CollapsibleBox.tsx
  packages/suite/src/components/settings/DeviceBanner.tsx
Labels: code

#14765 feat(suite-native): rework layout of the Device info screen
  packages/theme/src/borders.ts
  suite-native/atoms/src/AlertBox.tsx
  suite-native/atoms/src/index.ts
  suite-native/atoms/src/utils.ts
  suite-native/device/package.json
  suite-native/device/src/components/DeviceFirmwareCard.tsx
  suite-native/device/src/screens/DeviceInfoModalScreen.tsx
  suite-native/device/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/src/components/ScreenSubHeader.tsx
  yarn.lock
Labels: mobile

#14748 fix(coinmarket): hide swap in BTC-only firmware
  packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/HeaderActions.tsx
Labels: bug, +Invity

#14780 feat(suite-native): switch amount inputs when the inactive one is tapped
  suite-native/module-send/src/components/AmountInputs.tsx
  suite-native/module-send/src/components/CryptoAmountInput.tsx
  suite-native/module-send/src/components/FiatAmountInput.tsx
  suite-native/module-send/src/components/SwitchAmountsButton.tsx
  suite-native/module-send/src/types.ts
Labels: mobile

#14792 chore(suite-native): bump app version to 24.10.1
  suite-native/app/package.json
Labels: mobile

#12774 Ethereum tx data
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/AdvancedTxDetails.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/AdvancedTxDetails/Data.tsx
  packages/suite/src/support/messages.ts
Labels: build-desktop

#14801 refactor(suite-native): extract layout component for device settings card
  suite-common/icons-deprecated/src/components/DeviceModelIcon.tsx
  suite-native/device/src/components/DeviceFirmwareCard.tsx
  suite-native/device/src/components/DeviceSettingsCard.tsx
Labels: mobile

#14732 fix(suite-native): enable to confirm receive address outside our app
  packages/react-native-usb/android/src/main/java/io/trezor/rnusb/ReactNativeUsbModule.kt
Labels: mobile

#14802 chore(suite-native): add adhoc distribution
  .gitignore
  package.json
  suite-native/app/.env.preview
  suite-native/app/app.config.ts
  suite-native/app/assets/preview/appIcon.png
  suite-native/app/eas.json
  suite-native/app/package.json
  suite-native/config/src/environment.ts
Labels: mobile

#14757 feat(suite-native): report send review app exit to analytics
  suite-native/analytics/src/events.ts
  suite-native/module-send/package.json
  suite-native/module-send/src/atoms/wasAppLeftDuringReviewAtom.ts
  suite-native/module-send/src/components/AddressReviewStepList.tsx
  suite-native/module-send/src/components/OutputsReviewFooter.tsx
  yarn.lock
Labels: data, mobile

#14803 chore(suite-native): send feature flag used for btc like coins
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
  suite-native/module-accounts-management/src/selectors.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
Labels: mobile

#14816 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#14865 feat(suite-native): show correct network data for receive on POL and BNB
  suite-native/intl/src/en.ts
  suite-native/module-accounts-management/src/components/TokenAccountDetailScreenSubHeader.tsx
  suite-native/receive/src/components/ReceiveAccount.tsx
  suite-native/receive/src/components/ReceiveAddressCard.tsx
  suite-native/receive/src/components/TokenReceiveCard.tsx
Labels: mobile

#14825 feat(suite-native): correct network name for tokens in account detail
  suite-native/intl/src/en.ts
  suite-native/module-accounts-management/src/components/IncludeTokensToggle.tsx
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
Labels: mobile

#14872 fix(suite-native): send amount inputs scrolling
  suite-native/module-send/src/components/AmountInputs.tsx
  suite-native/module-send/src/components/CryptoAmountInput.tsx
  suite-native/module-send/src/components/FiatAmountInput.tsx
  suite-native/module-send/src/types.ts
Labels: mobile, release-native

#14882 fix(suite-native): show correct device label for each device
  suite-native/device-manager/src/components/DeviceItem/DeviceItemContent.tsx
  suite-native/module-settings/src/components/ViewOnly/WalletRow.tsx
Labels: bug, mobile

#14853 feat(suite-native): refactor ethereum formatters to generic token formatters
  suite-native/accounts/src/components/AccountsList/AccountsListTokenItem.tsx
  suite-native/formatters/src/components/TokenAmountFormatter.tsx
  suite-native/formatters/src/components/TokenToFiatAmountFormatter.tsx
  suite-native/formatters/src/index.ts
  suite-native/graph/src/components/TransactionEventTooltip.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryForm.tsx
  suite-native/module-accounts-import/src/components/TokenInfoCard.tsx
  suite-native/module-accounts-management/src/components/AccountDetailCryptoValue.tsx
  suite-native/receive/src/components/TokenReceiveCard.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailInputsSheetSection.tsx
  suite-native/transactions/src/components/TransactionsList/TokenTransferListItem.tsx
Labels: mobile

#14779 fix(suite-desktop-core): restart app when using autostart
  packages/suite-desktop-core/src/app.ts
  packages/suite-desktop-core/src/libs/app-utils.ts
Labels: build-desktop

#14884 feat(suite-common): add pol and bnb to graph
  packages/blockchain-link-types/src/common.ts
  suite-common/graph/src/balanceHistoryUtils.ts
  suite-common/graph/src/constants.ts
Labels: graph, connect, mobile

#13980 test(E2E): enabling skipped tests
  packages/suite-web/e2e/support/commands.ts
  packages/suite-web/e2e/support/pageObjects/modalObject.ts
  packages/suite-web/e2e/support/pageObjects/settingsDeviceObject.ts
  packages/suite-web/e2e/support/pageObjects/settingsMenuObject.ts
  packages/suite-web/e2e/support/utils/shortcuts.ts
  packages/suite-web/e2e/tests/analytics/events.test.ts
  packages/suite-web/e2e/tests/backup/t2t1-misc.test.ts
  packages/suite-web/e2e/tests/dashboard/assets.test.ts
  packages/suite-web/e2e/tests/metadata/remembered-device.test.ts
  packages/suite-web/e2e/tests/onboarding/firmware-update.test.ts
  packages/suite-web/e2e/tests/onboarding/t1b1-create-wallet.test.ts
  packages/suite-web/e2e/tests/onboarding/t1b1-recovery-advanced.test.ts
  packages/suite-web/e2e/tests/onboarding/t2t1-create-wallet.test.ts
  packages/suite-web/e2e/tests/settings/custom-firmware.test.ts
  packages/suite-web/e2e/tests/settings/t1b1-device-settings.test.ts
  packages/suite-web/e2e/tests/settings/t2t1-device-settings.test.ts
  packages/suite-web/e2e/tests/suite/passphrase-input.test.ts
  packages/suite-web/e2e/tests/suite/unacquired-device.test.ts
  packages/suite-web/e2e/tests/wallet/add-account-types.test.ts
  packages/suite-web/e2e/tests/wallet/cardano.test.ts
  packages/suite-web/e2e/tests/wallet/send-form-regtest.test.ts
  packages/suite/src/components/wallet/WalletLayout/AccountTopPanel/AccountNavigation.tsx
Labels: e2e

#14908 chore(suite-native): bump app version to 24.10.2
  suite-native/app/package.json
Labels: mobile

#14804 feat(suite-native): single fee option ui
  suite-native/intl/src/en.ts
  suite-native/module-send/src/components/FeeOption.tsx
  suite-native/module-send/src/components/FeeOptionsList.tsx
Labels: mobile

#14894 feat(suite-native): debug prefilled send form address button
  suite-native/accounts/src/selectors.ts
  suite-native/module-send/package.json
  suite-native/module-send/src/components/AddressInput.tsx
  suite-native/module-send/tsconfig.json
  yarn.lock
Labels: mobile

#14946 refactor(suite-native): create new module for device settings
  suite-native/app/package.json
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/app/tsconfig.json
  suite-native/device/package.json
  suite-native/device/src/assets/t1b1.png
  suite-native/device/src/assets/t2t1.png
  suite-native/device/src/assets/t3b1.png
  suite-native/device/src/assets/t3t1.png
  suite-native/device/src/components/DeviceImage.tsx
  suite-native/device/src/index.ts
  suite-native/device/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-device-settings/package.json
  suite-native/module-device-settings/src/components/DeviceFirmwareCard.tsx
  suite-native/module-device-settings/src/components/DeviceSettingsCard.tsx
  suite-native/module-device-settings/src/components/HowToUpdateBottomSheet.tsx
  suite-native/module-device-settings/src/index.ts
  suite-native/module-device-settings/src/screens/DeviceInfoModalScreen.tsx
  suite-native/module-device-settings/tsconfig.json
  tsconfig.json
  yarn.lock
Labels: mobile

#14960 fix(trade): nonsense fees
  packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketComposeTransaction.ts
  packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketFormActions.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketSellForm.ts
  packages/suite/src/hooks/wallet/form/useCompose.ts
  packages/suite/src/types/coinmarket/coinmarketForm.ts
Labels: bug, +Invity

#14890 feat(suite-native): allow enabled pol and bnb for portfolio tracker
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/intl/src/en.ts
  suite-native/module-accounts-import/package.json
  suite-native/module-accounts-import/src/components/AccountImportSummary.tsx
  suite-native/module-accounts-import/src/components/SelectableNetworkList.tsx
  suite-native/module-accounts-import/tsconfig.json
  yarn.lock
Labels: mobile

#14992 fix(trade): analytics event in dashboard
  packages/suite-analytics/src/constants.ts
  packages/suite-analytics/src/types/events.ts
  packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/TradeActions.tsx
Labels: bug, +Invity

#14891 feat(trade): structure separation
  packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageHeader.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/types/coinmarket/coinmarket.ts
  packages/suite/src/views/wallet/coinmarket/DCA/CoinmarketDCALanding.tsx
  packages/suite/src/views/wallet/coinmarket/buy/CoinmarketBuyConfirm.tsx
  packages/suite/src/views/wallet/coinmarket/buy/CoinmarketBuyDetail.tsx
  packages/suite/src/views/wallet/coinmarket/buy/CoinmarketBuyForm.tsx
  packages/suite/src/views/wallet/coinmarket/buy/CoinmarketBuyOffers.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketContainer.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayout/CoinmarketLayout.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayout/CoinmarketLayoutHeader.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketLayout/CoinmarketLayoutNavigation/CoinmarketLayoutNavigation.tsx
  packages/suite/src/views/wallet/coinmarket/exchange/CoinmarketExchangeForm.tsx
  packages/suite/src/views/wallet/coinmarket/sell/CoinmarketSellConfirm.tsx
  packages/suite/src/views/wallet/coinmarket/sell/CoinmarketSellDetail.tsx
  packages/suite/src/views/wallet/coinmarket/sell/CoinmarketSellForm.tsx
  packages/suite/src/views/wallet/coinmarket/sell/CoinmarketSellOffers.tsx
  packages/suite/src/views/wallet/coinmarket/transactions/CoinmarketTransactions.tsx
Labels: feature, +Invity

#14906 feat(suite-native): add device PIN protection card for non-T1B1 models
  packages/connect/src/constants/errors.ts
  suite-native/analytics/src/constants.ts
  suite-native/analytics/src/events.ts
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/atoms/src/ScreenHeaderWrapper.tsx
  suite-native/device-manager/src/components/AddHiddenWalletButton.tsx
  suite-native/device-manager/src/components/DeviceAction.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/device-manager/src/components/DeviceSettingsButton.tsx
  suite-native/device/src/assets/connector.png
  suite-native/device/src/components/ConnectorImage.tsx
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/device/src/index.ts
  suite-native/intl/src/en.ts
  suite-native/module-authorize-device/src/components/connect/ConnectDeviceScreenHeader.tsx
  suite-native/module-authorize-device/src/components/connect/ConnectDeviceScreenView.tsx
  suite-native/module-device-settings/package.json
  suite-native/module-device-settings/src/components/DevicePinActionButton.tsx
  suite-native/module-device-settings/src/components/DevicePinProtectionCard.tsx
  suite-native/module-device-settings/src/components/DeviceSettingsCard.tsx
  suite-native/module-device-settings/src/index.ts
  suite-native/module-device-settings/src/navigation/DevicePinProtectionStackNavigator.tsx
  suite-native/module-device-settings/src/navigation/DeviceSettingsStackNavigator.tsx
  suite-native/module-device-settings/src/screens/ContinueOnTrezorScreen.tsx
  suite-native/module-device-settings/src/screens/DeviceSettingsModalScreen.tsx
  suite-native/module-device-settings/tsconfig.json
  suite-native/navigation/src/components/GoBackIcon.tsx
  suite-native/navigation/src/components/ScreenSubHeader.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#14905 fix(suite-desktop-core): restart app when using autostart on linux
  packages/suite-desktop-core/src/modules/auto-updater.ts
Labels: build-desktop

#15007 feat(suite-native): ethereum send feature flag
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-accounts-management/src/selectors.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
Labels: mobile

#15016 fix(suite-native): prevent device actions cutoff by removing explicit height
  suite-native/device-manager/src/components/DeviceAction.tsx
Labels: low hanging fruit, mobile

#15017 chore(suite-native): SENTRY_AUTH_TOKEN should be taken directly from env variables
  suite-native/app/app.config.ts
Labels: sentry, low hanging fruit, mobile

#15048 refactor(suite-native): dev buttons prefix
  suite-native/module-accounts-import/src/components/DevXpub.tsx
  suite-native/module-send/src/components/AddressInput.tsx
Labels: mobile

#15040 feat(suite-native): enable device PIN protection card for model T1B1
  suite-native/intl/src/en.ts
  suite-native/module-authorize-device/package.json
  suite-native/module-authorize-device/src/components/connect/PinForm.tsx
  suite-native/module-authorize-device/src/components/connect/PinFormControlButtons.tsx
  suite-native/module-authorize-device/src/components/connect/PinFormProgress.tsx
  suite-native/module-authorize-device/src/components/connect/PinOnDevice.tsx
  suite-native/module-authorize-device/src/components/connect/PinOnKeypad.tsx
  suite-native/module-authorize-device/src/constants/deviceImageConstants.ts
  suite-native/module-authorize-device/src/index.ts
  suite-native/module-authorize-device/src/screens/connect/PinScreen.tsx
  suite-native/module-authorize-device/tsconfig.json
  suite-native/module-device-settings/package.json
  suite-native/module-device-settings/src/components/DeviceInteractionScreenWrapper.tsx
  suite-native/module-device-settings/src/components/DevicePinActionButton.tsx
  suite-native/module-device-settings/src/components/DeviceSettingsCard.tsx
  suite-native/module-device-settings/src/navigation/DevicePinProtectionStackNavigator.tsx
  suite-native/module-device-settings/src/navigation/DeviceSettingsStackNavigator.tsx
  suite-native/module-device-settings/src/screens/ContinueOnTrezorScreen.tsx
  suite-native/module-device-settings/src/screens/DeviceSettingsModalScreen.tsx
  suite-native/module-device-settings/src/screens/EnterPinScreen.tsx
  suite-native/module-device-settings/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#15056 feat(suite-native): allow PIN protection changes during discovery
  suite-native/module-device-settings/src/components/DevicePinActionButton.tsx
Labels: mobile

#13788 fix(staking): staking tx in staking tab
  packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/StakingDashboard.tsx
  packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/Transactions.tsx
  suite-common/wallet-core/src/transactions/transactionsReducer.ts
Labels: staking

#15066 feat(suite-native): other ethereum network account types have labels
  suite-common/wallet-core/src/accounts/accountsConstants.ts
Labels: mobile

#15072 ci(suite-native): enable to dispatch preview build by label 'build-mobile' on PR
  .github/workflows/build-suite-native-preview.yml
Labels: mobile, build-mobile

#14999 feat(suite-native): enable Solana via feature flag
  suite-common/graph/src/balanceHistoryUtils.ts
  suite-common/graph/src/constants.ts
  suite-native/app/globalPolyfills.js
  suite-native/app/package.json
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-accounts-import/src/components/DevXpub.tsx
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  suite-native/tokens/src/utils.ts
  yarn.lock
Labels: mobile

#15058 refactor(suite-native): fresh address selector
  suite-native/accounts/src/selectors.ts
  suite-native/module-send/src/components/AddressInput.tsx
  suite-native/receive/package.json
  suite-native/receive/src/hooks/useAccountReceiveAddress.tsx
  suite-native/receive/tsconfig.json
  yarn.lock
Labels: mobile

#15083 feat(suite-native): solana local graph history movements
  suite-common/graph/src/balanceHistoryUtils.ts
  suite-common/graph/src/graphDataFetching.ts
Labels: mobile

#14901 fix(blockchain-link): show better message for solana expired txs
  packages/blockchain-link/src/workers/solana/index.ts
Labels: solana

#15105 feat(suite-native): update UI for failed txns
  suite-common/icons/generateIconFont.ts
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.json
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.ttf
  suite-native/transactions/src/components/TransactionDetail/TransactionDetailHeader.tsx
  suite-native/transactions/src/components/TransactionsList/TokenTransferListItem.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionIcon.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItem.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionListItemContainer.tsx
Labels: mobile

#15103 feat(suite-native): add enable/change/disable PIN protection e2e test
  suite-native/app/e2e/pageObjects/bottomSheetActions.ts
  suite-native/app/e2e/pageObjects/coinEnablingActions.ts
  suite-native/app/e2e/pageObjects/connectingDevice.ts
  suite-native/app/e2e/pageObjects/deviceManagerActions.ts
  suite-native/app/e2e/pageObjects/deviceSettingsActions.ts
  suite-native/app/e2e/tests/deeplinkPopup.test.ts
  suite-native/app/e2e/tests/deviceSettings.test.ts
  suite-native/app/e2e/tests/onboardAndConnect.test.ts
  suite-native/app/e2e/tests/send.test.ts
  suite-native/device-manager/src/components/DeviceSettingsButton.tsx
  suite-native/device-manager/src/components/DeviceSwitch.tsx
  suite-native/module-device-settings/src/components/DevicePinActionButton.tsx
Labels: mobile

#15159 fix(suite-native): fix key for wallet rows
  suite-native/module-settings/src/components/ViewOnly/DevicesManagement.tsx
Labels: low hanging fruit, mobile

#15160 fix(suite-native): update gorhom bottom sheet to get rid of warning
  suite-native/app/package.json
  suite-native/atoms/package.json
  yarn.lock
Labels: dependencies, mobile
