Repository trezor/trezor-suite, pull requests merged in 2025-06, with the labels that each got.

#19252 chore(connect): move models to @trezor/device-utils
  packages/connect/src/device/Device.ts
  packages/device-utils/src/index.ts
  packages/device-utils/src/models.ts
  packages/suite/src/views/onboarding/steps/SecurityCheck/SecurityCheck.tsx
Labels: no-project

#19227 feat(suite-native): better UX copy for CTA if FW is already installed
  suite-native/intl/src/en.ts
  suite-native/module-device-onboarding/src/screens/UninitializedDeviceLandingScreen.tsx
Labels: low hanging fruit, mobile

#19250 fix(trading): changing approval transaction
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx
Labels: bug, +Invity

#19273 fix(wallet-utils): bump unstake eth tx
  suite-common/wallet-core/src/send/sendFormEthereumThunks.ts
  suite-common/wallet-utils/src/ethereumStakingUtils.ts
  suite-common/wallet-utils/src/transactionUtils.ts
Labels: release

#19240 fix(trading): do not update date of trade in watchTrade
  suite-common/trading/src/thunks/common/watchTradeThunk.ts
Labels: +Invity

#19266 fix(suite): migration incompatibility
  packages/suite/src/storage/CHANGELOG.md
  packages/suite/src/storage/index.ts
  packages/suite/src/storage/migrations/index.ts
  packages/suite/src/storage/migrations/trading/migrationCoinmarketToTrading.ts
  packages/suite/src/storage/migrations/versions/migrateToV55.ts
  packages/suite/src/storage/migrations/versions/migrateToV56.ts
Labels: bug

#19298 fix(connect): refactor check firmware revision download
  packages/connect/src/data/downloadReleasesMetadata.ts
  packages/connect/src/data/firmwareInfo.ts
  packages/connect/src/device/__tests__/DeviceList.test.ts
  packages/connect/src/device/checkFirmwareRevision.ts
Labels: no-project

#19317 feat(connect): add UI response for THP pairing tag
  packages/connect/src/constants/errors.ts
  packages/connect/src/core/index.ts
  packages/connect/src/device/Device.ts
  packages/connect/src/events/device.ts
  packages/connect/src/events/ui-request.ts
  packages/connect/src/events/ui-response.ts
Labels: no-project, cherry-pick🍒

#19322 chore: discovery code cleanup
  suite-common/wallet-core/src/discovery/discoveryThunks.ts
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/firmware/src/components/ConfirmFirmwareUpdateScreenFooter.tsx
  suite-native/module-authorize-device/src/components/connect/PinFormControlButtons.tsx
  suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/FirmwareUpdateAlert.tsx
Labels: no-project

#19346 fix: remove unused code
  packages/suite/src/components/firmware/FirmwareInitial.tsx
Labels: no-project

#19180 test(e2e): devicemodal switcher datatest separated
  packages/suite-desktop-core/e2e/support/pageObjects/dashboardPage.ts
  packages/suite/src/views/suite/SwitchDevice/SwitchDeviceModal.tsx
Labels: no-project

#19261 chore(suite-web): display meaningful error when navigating to /bridge…
  packages/suite/src/views/suite/bridge-requested/index.tsx
Labels: no-project

#18931 feat(e2e): update of firmware type switch OS matrix
  packages/suite-desktop-core/e2e/tests/manual/firmware/firmware-switch.test.ts
Labels: no-project

#19379 fix(suite): what is staking message
  packages/suite-data/files/translations/en.json
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/staking/components/StakingDashboard/components/EmptyStakingCard.tsx
Labels: no-project, cherry-pick🍒

#19374 feat(e2e): update of OS matrix for Android test
  packages/suite-desktop-core/e2e/tests/manual/browser/mobile-browser.test.ts
Labels: no-project

#19387 chore(ci): use coreutils numfmt to fix s3 index generation script
  scripts/generate-s3-index.sh
Labels: no-project

#19389 fix(connect-common): bump bl version to 2.1.10 on t3b1
  packages/connect-common/files/firmware/t3b1/releases.json
Labels: build-desktop

#19327 feat(suite-native): Device Onboarding - Skip Pin Setup
  suite-native/device/src/hooks/usePinAction.tsx
  suite-native/intl/src/en.ts
  suite-native/module-device-onboarding/src/screens/CreatePinScreen.tsx
Labels: mobile

#19429 fix(suite-native): Mobile Trade: Fix account list item balance alignment
  suite-native/module-trading/src/components/general/AccountList/AccountListBaseItem.tsx
Labels: mobile, no-project

#19404 refactor(connect): split Device related code to workflow modules
  packages/connect/src/core/index.ts
  packages/connect/src/device/Device.ts
  packages/connect/src/device/workflow/index.ts
  packages/connect/src/device/workflow/validateState.ts
  packages/connect/src/types/workflow.ts
Labels: connect, no-project

#19443 feat(suite-native): keep firmware screen awake
  scripts/list-outdated-dependencies/mobile-dependencies.txt
  suite-native/app/package.json
  suite-native/firmware/package.json
  suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx
  yarn.lock
Labels: mobile

#19448 chore(suite-web): don't open vite automatically in browser
  packages/suite-build/vite.config.ts
Labels: DX, no-project

#19459 chore(suite): remove unused device.authConfirm
  docs/analytics/sentry.md
  packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/PassphraseOnDeviceModal.tsx
  packages/suite/src/components/wallet/WalletLayout/AccountsMenu/AddAccountButton.tsx
  packages/suite/src/utils/wallet/selectDiscoveryOverallStatus.ts
  packages/suite/src/views/wallet/details/index.tsx
  packages/suite/src/views/wallet/receive/Receive.tsx
  packages/suite/src/views/wallet/tokens/common/TokensTable/TokenRow.tsx
  suite-common/suite-types/src/device.ts
  suite-common/test-utils/src/mocks.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-common/wallet-core/src/device/deviceSelectors.ts
  suite-common/wallet-core/src/discovery/discoverySelectors.ts
Labels: no-project

#19452 Fix: add standard wallet
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-common/wallet-core/src/discovery/discoveryThunks.ts
  suite-native/device-manager/src/components/WalletList.tsx
Labels: new discovery

#19481 fix(suite-native): make sure that passphrase form is opened when user…
  suite-native/module-authorize-device/src/components/passphrase/PassphraseMismatchAlert.tsx
Labels: bug, release-native, cherry-pick🍒, new discovery

#19497 chore(suite): use usePin hook in recovery component
  packages/suite/src/views/recovery/index.tsx
Labels: no-project

#19042 feat(ci): add build of transport-bluetooth binary
  .github/workflows/build-transport-bluetooth-binary.yml
  packages/transport-bluetooth/scripts/Dockerfile
  packages/transport-bluetooth/scripts/build.sh
Labels: no-project

#19516 test(connect): remove 1ms flaky override test
  packages/connect/e2e/tests/device/override.test.ts
Labels: no-project

#19513 chore(ci): fix transport-bluetooth binary actions build
  .github/workflows/build-transport-bluetooth-binary.yml
Labels: no-project

#19521 chore(suite): remove unneeded authorizationIntent variable
  packages/suite/src/middlewares/wallet/discoveryMiddleware.ts
Labels: no-project

#19500 fix(suite): select in modal workaround
  packages/components/src/components/form/Select/Select.tsx
  packages/components/src/components/form/Select/useDetectPortalTarget.ts
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/WalletConnectProposalModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/WalletConnectSwitchAccountModal.tsx
  packages/suite/src/views/suite/udev/index.tsx
Labels: build-desktop

#19499 chore(suite): remove buttonRequestsMiddleware from native
  packages/suite/src/middlewares/suite/buttonRequestMiddleware.ts
  suite-common/connect-init/src/connectInitThunks.ts
  suite-native/device/src/index.ts
  suite-native/device/src/middlewares/buttonRequestMiddleware.ts
  suite-native/state/src/store.ts
Labels: no-project

#19536 fix(suite-native): device onboarding e2e test firmware skip
  suite-native/app/e2e/pageObjects/deviceOnboardingActions.ts
Labels: mobile, no-project

#19537 test(connect): resetDevice tests conditional, omit t1
  packages/connect/e2e/tests/device/resetDevice.test.ts
Labels: no-project

#19540 ci: increase test:unit timeout to 30 minutes
  .github/workflows/check-code-validation.yml
Labels: no-project

#19519 chore: update packages to fix dependabot issues
  packages/address-validator/package.json
  packages/suite-build/package.json
  packages/suite-desktop-core/package.json
  yarn.lock
Labels: dependencies, no-project

#19484 fix(suite-native): prevent navigating to Connecting screen over Coin enabling
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/module-authorize-device/src/hooks/useOnDeviceReadyNavigation.ts
Labels: mobile, release-native, cherry-pick🍒, new discovery

#19563 chore(suite-native): remove redirection with condition that should never happen
  suite-native/module-authorize-device/src/hooks/useOnDeviceReadyNavigation.ts
Labels: mobile

#19573 fix(suite): Portfolio header skeleton for 0.00 wallet
  packages/suite/src/views/dashboard/PortfolioCard/PortfolioCardHeader.tsx
Labels: no-project

#19579 chore: remove useless extraDependencies in favor of direct imports
  packages/suite/src/actions/suite/constants/suiteConstants.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/actions/wallet/__fixtures__/publicKeyActions.ts
  packages/suite/src/actions/wallet/__tests__/publicKeyActions.test.ts
  packages/suite/src/support/extraDependencies.ts
  suite-common/connect-init/src/__tests__/connectInitThunks.test.ts
  suite-common/connect-init/src/connectInitThunks.ts
  suite-common/redux-utils/src/extraDependenciesType.ts
  suite-common/test-utils/src/extraDependenciesMock.ts
  suite-common/wallet-core/src/accounts/accountsThunks.ts
  suite-common/wallet-core/src/blockchain/blockchainThunks.ts
  suite-native/state/src/extraDependencies.ts
Labels: tech, no-project

#19580 chore(env-utils): cleanup unused or duplicated env utils
  packages/env-utils/src/envUtils.native.ts
  packages/env-utils/src/envUtils.ts
  packages/env-utils/src/index.ts
  packages/env-utils/src/types.ts
Labels: tech, no-project

#19574 fix(suite-native): initialize Connect after onboarding is finished
  suite-native/app/src/App.tsx
  suite-native/app/src/hooks/useReportAppInitToAnalytics.ts
  suite-native/app/src/initActions.ts
  suite-native/state/src/appSlice.ts
Labels: mobile

#19595 fix(suite): temporary hide dont show again checkbox in trading
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TradingTermsModal.tsx
Labels: no-project, cherry-pick🍒

#19598 refactor(suite-native): use standard feature flag for Bluetooth
  suite-native/app/.env.development
  suite-native/bluetooth/package.json
  suite-native/bluetooth/src/featureFlag.ts
  suite-native/bluetooth/src/hooks/useBluetoothAdapter.ts
  suite-native/bluetooth/src/index.ts
  suite-native/bluetooth/tsconfig.json
  suite-native/device-manager/src/components/DeviceList.tsx
  suite-native/feature-flags/src/__tests__/featureFlagsSlice.test.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx
  suite-native/module-dev-utils/package.json
  suite-native/module-dev-utils/src/components/BluetoothCard.tsx
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/module-dev-utils/tsconfig.json
  suite-native/module-home/src/screens/HomeScreen/components/EmptyPortfolioCrossroads.tsx
  suite-native/state/src/extraDependencies.ts
  yarn.lock
Labels: mobile

#19627 chore(message-system): update required message
  suite-common/message-system/config/config.v1.json
Labels: READY FOR REVIEW

#19689 chore(suite): add checks when creating object stores
  packages/suite/src/storage/migrations/versions/migrateToV56.ts
Labels: build-desktop, cherry-pick🍒

#19666 feat(suite-native): add kyc warning to buy
  suite-native/intl/src/en.ts
  suite-native/module-trading/src/components/buy/BuyProviderPicker.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyProviderPicker.comp.test.tsx
  suite-native/module-trading/src/components/general/OverviewRow.tsx
  suite-native/module-trading/src/components/general/ProviderSheet/ProviderListItem.tsx
  suite-native/module-trading/src/components/general/ProviderSheet/__tests__/ProviderListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/OverviewRow.comp.test.tsx
Labels: mobile, no-project

#19734 fix(suite-native): fix yarn error in EAS
  suite-native/app/eas.json
Labels: mobile

#19684 feat(suite-native): Settings: Change Device Name
  packages/utils/src/asciiUtils.ts
  suite-native/app/e2e/pageObjects/deviceSettingsActions.ts
  suite-native/app/e2e/tests/deviceSettings.test.ts
  suite-native/atoms/src/Input/Input.tsx
  suite-native/atoms/src/Input/InputWrapper.tsx
  suite-native/forms/package.json
  suite-native/forms/src/components/FormSubmitButton.tsx
  suite-native/forms/src/index.ts
  suite-native/intl/src/en.ts
  suite-native/module-device-settings/package.json
  suite-native/module-device-settings/src/components/DeviceInfo.tsx
  suite-native/module-device-settings/src/deviceNameFormSchema.tsx
  suite-native/module-device-settings/src/hooks/useChangeDeviceName.ts
  suite-native/module-device-settings/src/navigation/DeviceNameStackNavigator.tsx
  suite-native/module-device-settings/src/navigation/DeviceSettingsStackNavigator.tsx
  suite-native/module-device-settings/src/screens/DeviceNameLoadingScreen.tsx
  suite-native/module-device-settings/src/screens/DeviceNameScreen.tsx
  suite-native/module-device-settings/src/screens/DeviceSettingsModalScreen.tsx
  suite-native/module-device-settings/tsconfig.json
  suite-native/module-send/src/components/CustomFeeBottomSheet.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#19764 chore(suite-native): remove unused routes
  suite-native/device-manager/src/components/AddHiddenWalletButton.tsx
  suite-native/navigation/src/routes.ts
Labels: mobile, no-project

#19619 test(suite-native): device onboarding recovery e2e
  suite-native/app/e2e/pageObjects/deviceOnboardingActions.ts
  suite-native/app/e2e/tests/deviceOnboarding.test.ts
  suite-native/module-device-onboarding/src/screens/CreateOrRecoverCrossroadsScreen.tsx
  suite-native/module-device-onboarding/src/screens/RecoveryInstructionsScreen.tsx
Labels: mobile

#19600 feat(suite): modal tx review approve, sell, swap, revoke header
  packages/suite/src/components/suite/modals/ReduxModal/TransactionReviewModal/TransactionReviewModalContent.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/suite/transactionReview.ts
  scripts/list-outdated-dependencies/trends-dependencies.txt
  suite-common/trading/src/thunks/common/recomposeAndSignTxThunk.ts
  suite-common/trading/src/types.ts
  suite-common/wallet-types/src/sendForm.ts
  suite-common/wallet-utils/package.json
  suite-common/wallet-utils/src/__tests__/ethUtils.test.ts
  suite-common/wallet-utils/src/ethUtils.ts
  yarn.lock
Labels: feature

#19796 feat(connect-common): temporarily add 1.13.0 FW
  packages/connect-common/files/firmware/t1b1/ATTENTION temporarily including 1.13.0 here.txt
  packages/connect-common/files/firmware/t1b1/trezor-t1b1-1.13.0-bitcoinonly.bin
  packages/connect-common/files/firmware/t1b1/trezor-t1b1-1.13.0.bin
Labels: no-project

#19779 Make AuthenticateDeviceFailModal closable
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AuthenticateDeviceFailModal.tsx
Labels: UI

#19799 chore(suite-native): remove bluetooth build configuration flag
  suite-native/app/.env.development
  suite-native/app/app.config.ts
  suite-native/app/eas.json
  suite-native/state/src/extraDependencies.ts
Labels: mobile
