Repository trezor/trezor-suite, pull requests merged in 2025-03, with the labels that each got.

#17316 feat(blockchain-link-type): change bigint to string in persist
  packages/blockchain-link-types/src/solana.ts
  packages/blockchain-link/src/workers/solana/stakingAccounts.ts
Labels: solana, no-project

#17326 test(transport-bridge): use older emu
  packages/transport-test/e2e/bridge/bridge-complex-cases.test.ts
Labels: no-project

#17331 fix(connect): solana creating account parameter in e2e
  packages/connect/e2e/__fixtures__/solanaComposeTransaction.ts
Labels: no-project

#17337 chore(ci): remove typings arg from updateProjectReferences
  scripts/updateProjectReferences.ts
Labels: no-project

#17335 fix(suite-native): auto version bump
  .github/workflows/suite-native-monthly-version-bump.yml
Labels: mobile

#17333 chore(connect-web): add deprecation notice to iframe and popup
  packages/connect-iframe/src/index.ts
  packages/connect-popup/package.json
  packages/connect-popup/tsconfig.json
  packages/connect-ui/src/components/InfoPanel.tsx
  packages/connect-ui/src/index.tsx
  packages/connect/src/data/connectSettings.ts
  packages/connect/src/types/settings.ts
Labels: no-project

#16838 fix(suite-native): use react-native-keyboard-controller for keyboard handling
  scripts/list-outdated-dependencies/mobile-dependencies.txt
  suite-native/app/package.json
  suite-native/app/src/App.tsx
  suite-native/module-accounts-import/src/components/AccountImportConfirmFormScreen.tsx
  suite-native/module-accounts-import/src/components/AccountImportSummaryScreen.tsx
  suite-native/module-accounts-import/src/components/XpubHint.tsx
  suite-native/module-accounts-import/src/screens/XpubScanScreen.tsx
  suite-native/module-authorize-device/src/components/passphrase/PassphraseContentScreenWrapper.tsx
  suite-native/module-authorize-device/src/components/passphrase/PassphraseForm.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseFormScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseVerifyEmptyWalletScreen.tsx
  suite-native/module-send/src/components/AmountInputs.tsx
  suite-native/module-send/src/components/DestinationTagInput.tsx
  suite-native/module-send/src/components/SendScreen.tsx
  suite-native/module-send/src/screens/SendAccountsScreen.tsx
  suite-native/module-send/src/screens/SendAddressReviewScreen.tsx
  suite-native/module-send/src/screens/SendDestinationTagReviewScreen.tsx
  suite-native/module-send/src/screens/SendFeesScreen.tsx
  suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx
  suite-native/module-send/src/screens/SendOutputsScreen.tsx
  suite-native/navigation/package.json
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/src/components/ScreenContentWrapper.tsx
  suite-native/navigation/src/hooks/useIsKeyboardShown.ts
  suite-native/test-utils/package.json
  suite-native/test-utils/src/expoMock.js
  yarn.lock
Labels: mobile

#17344 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#17332 chore(suite-native): app version bumped to 25.3.1
  suite-native/app/package.json
Labels: mobile

#17257 refactor(suite): changed empty account with tokens texts and CTAs
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/transactions/components/AccountEmpty.tsx
Labels: release

#17355 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#17356 fix(trading): cleaning of modal account key
  packages/suite/src/middlewares/wallet/__tests__/tradingMiddleware.test.ts
  packages/suite/src/middlewares/wallet/tradingMiddleware.ts
Labels: bug, +Invity, staking

#17005 feat(trading): trading sign message flow
  packages/suite/package.json
  packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/types/trading/tradingForm.ts
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchange.tsx
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSignData.tsx
  suite-common/trading/package.json
  yarn.lock
Labels: +Invity, release

#17371 fix(suite-native): remove critical pictograms from send help sheets
  suite-native/module-send/src/components/AddressReviewHelpSheet.tsx
Labels: mobile

#17370 fix(suite): hide solana unstake amount
  packages/blockchain-link-types/src/common.ts
  packages/blockchain-link-utils/src/solana.ts
  packages/suite/src/components/suite/UnstakingTxAmount.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/Detail/AdvancedTxDetails/AmountDetails.tsx
  packages/suite/src/components/wallet/TransactionItem/TransactionHeader.tsx
  packages/suite/src/components/wallet/TransactionItem/TransactionHeading.tsx
  packages/suite/src/components/wallet/TransactionItem/TransactionTarget/TransactionTarget.tsx
  suite-common/wallet-core/src/transactions/transactionsReducer.ts
  suite-common/wallet-utils/src/transactionUtils.ts
Labels: release

#17376 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations, no-project

#17372 feat(everstake): added everstake solana user agent
  packages/blockchain-link/package.json
  packages/blockchain-link/src/workers/solana/stakingAccounts.ts
  suite-common/wallet-utils/package.json
  suite-common/wallet-utils/src/solanaStakingUtils.ts
  suite-common/wallet-utils/tsconfig.json
  yarn.lock
Labels: release

#17384 fix(suite-native): use correct box size for list icon numbers
  suite-native/atoms/src/BottomSheetListItem.tsx
  suite-native/atoms/src/OrderedListIcon.tsx
  suite-native/module-send/src/components/AddressReviewStep.tsx
Labels: mobile

#17391 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/lol.json
  packages/suite/src/support/messages.ts
Labels: translations, no-project

#17395 Bump beta version to 25.4.0
  packages/suite/package.json
Labels: deployment, no-project

#17398 fix(suite-native): use react-native-keyboard-controller for bottom sheets
  suite-native/atoms/package.json
  suite-native/atoms/src/Sheet/BottomSheet.tsx
  suite-native/atoms/src/Sheet/BottomSheetContainer.tsx
  suite-native/navigation/src/hooks/useIsKeyboardShown.ts
  yarn.lock
Labels: mobile

#17404 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#17053 chore(trading): move confirm trade
  suite-common/trading/package.json
  suite-common/trading/src/__fixtures__/buyUtils.ts
  suite-common/trading/src/selectors/tradingSelectors.ts
  suite-common/trading/src/thunks/buy/__tests__/confirmTradeThunk.test.ts
  suite-common/trading/src/thunks/buy/confirmTradeThunk.ts
  suite-common/trading/src/thunks/buy/index.ts
  suite-common/trading/tsconfig.json
  yarn.lock
Labels: +Invity, chore

#17377 chore(connect): parseFirmware function to be more clear
  packages/connect/src/data/DataManager.ts
  packages/connect/src/data/__tests__/firmwareInfo.test.ts
  packages/connect/src/data/firmwareInfo.ts
Labels: no-project

#17095 refactor(trading): buy reducer
  suite-common/trading/src/actions/buyActions.ts
  suite-common/trading/src/index.ts
  suite-common/trading/src/middlewares/__tests__/tradingMiddleware.test.ts
  suite-common/trading/src/middlewares/tradingMiddleware.ts
  suite-common/trading/src/reducers/__fixtures__/buyTradingReducer.ts
  suite-common/trading/src/reducers/__tests__/buyReducer.test.ts
  suite-common/trading/src/reducers/buyReducer.ts
  suite-common/trading/src/reducers/tradingReducer.ts
  suite-common/trading/src/thunks/__tests__/tradingThunk.test.ts
  suite-common/trading/src/thunks/buy/__tests__/loadInfoThunk.test.ts
  suite-common/trading/src/thunks/buy/confirmTradeThunk.ts
  suite-common/trading/src/thunks/buy/handleRequestThunk.ts
  suite-common/trading/src/thunks/buy/selectQuoteThunk.ts
  suite-common/trading/src/thunks/tradingThunks.ts
Labels: +Invity, code

#17446 fix(suite-desktop-core): fix async error in Windows signing
  packages/suite-desktop-core/scripts/sign-windows.ts
Labels: no-project

#17448 chore(transport-bridge): simplify ui
  packages/transport-bridge/package.json
  packages/transport-bridge/src/http.ts
  packages/transport-bridge/webpack/ui.webpack.config.ts
  scripts/list-outdated-dependencies/connect-dependencies.txt
  yarn.lock
Labels: no-project

#17450 chore(trading): move useTradingInfo hook to @suite-common/trading
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TradingTermsModal.tsx
  packages/suite/src/hooks/wallet/trading/form/common/useTradingFormActions.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingBuyForm.tsx
  packages/suite/src/hooks/wallet/trading/form/useTradingBuyFormDefaultValues.tsx
  packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingExchangeFormDefaultValues.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingSellForm.ts
  packages/suite/src/types/trading/trading.ts
  packages/suite/src/types/trading/tradingForm.ts
  packages/suite/src/utils/wallet/trading/__tests__/buyUtils.test.ts
  packages/suite/src/utils/wallet/trading/__tests__/exchangeUtils.test.ts
  packages/suite/src/utils/wallet/trading/__tests__/sellUtils.test.ts
  packages/suite/src/views/wallet/trading/common/TradingAddressOptions.tsx
  packages/suite/src/views/wallet/trading/common/TradingCryptoAmount.tsx
  packages/suite/src/views/wallet/trading/common/TradingFeaturedOffers/TradingFeaturedOffersAmounts.tsx
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputCryptoSelect.tsx
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputFiatCrypto/TradingFormInputCryptoAmount.tsx
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputFiatCrypto/TradingFormInputFiatCrypto.tsx
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOfferCryptoAmount.tsx
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingInfo/TradingInfoHeader.tsx
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendSwap.tsx
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerifyOptions.tsx
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerifyOptionsItem.tsx
  packages/suite/src/views/wallet/trading/common/TradingTransactions/TradingTransaction/TradingTransactionAmounts.tsx
  suite-common/trading/package.json
  suite-common/trading/redux.d.ts
  suite-common/trading/src/hooks/useTradingInfo.ts
  suite-common/trading/src/index.ts
  suite-common/trading/src/thunks/buy/__tests__/handleRequestThunk.test.ts
  suite-common/trading/src/types.ts
  suite-common/trading/tsconfig.json
  yarn.lock
Labels: no-project

#17461 chore: yarn format:all result
  .github/actions/check-previous-test-runs/action.yml
  .github/workflows/release-connect-intermediary.yml
  .github/workflows/template-connect-test-params.yml
  .github/workflows/test-suite-desktop-e2e.yml
Labels: no-project

#17432 chore(connect): update device authenticity config
  packages/connect/src/data/deviceAuthenticityConfig.ts
Labels: no-project

#17459 fix(trading): delete suite-analytics
  suite-common/trading/package.json
  suite-common/trading/src/thunks/buy/__tests__/confirmTradeThunk.test.ts
  suite-common/trading/src/thunks/buy/confirmTradeThunk.ts
  suite-common/trading/tsconfig.json
  yarn.lock
Labels: +Invity

#17096 refactor(trading): reducer
  suite-common/trading/src/actions/tradingActions.ts
  suite-common/trading/src/index.ts
  suite-common/trading/src/middlewares/__tests__/tradingMiddleware.test.ts
  suite-common/trading/src/middlewares/tradingMiddleware.ts
  suite-common/trading/src/reducers/__fixtures__/tradingReducer.ts
  suite-common/trading/src/reducers/tradingReducer.ts
  suite-common/trading/src/thunks/buy/confirmTradeThunk.ts
  suite-common/trading/src/thunks/buy/handleRequestThunk.ts
  suite-common/trading/src/thunks/tradingThunks.ts
Labels: +Invity, code

#17266 feat(suite-native): enable and discover account via trade
  suite-native/intl/src/en.ts
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
  suite-native/module-add-accounts/src/index.ts
  suite-native/module-add-accounts/src/screens/AddCoinAccountScreen.tsx
  suite-native/module-add-accounts/src/screens/AddCoinDiscoveryFinishedScreen.tsx
  suite-native/module-add-accounts/src/screens/AddCoinDiscoveryRunningScreen.tsx
  suite-native/module-add-accounts/src/screens/SelectAccountTypeScreen.tsx
  suite-native/module-trading/package.json
  suite-native/module-trading/src/components/buy/BuyCard.tsx
  suite-native/module-trading/src/components/buy/ReceiveAccountPicker.tsx
  suite-native/module-trading/src/components/buy/__tests__/ReceiveAccountPicker.comp.test.tsx
  suite-native/module-trading/src/components/general/AccountSheet/AccountListItem.tsx
  suite-native/module-trading/src/components/general/AccountSheet/AccountSheet.tsx
  suite-native/module-trading/src/components/general/AccountSheet/AccountSheetHeader.tsx
  suite-native/module-trading/src/components/general/AccountSheet/AddressListEmptyComponent.tsx
  suite-native/module-trading/src/components/general/AccountSheet/NoAccountsComponent.tsx
  suite-native/module-trading/src/components/general/AccountSheet/TradeAccountsList.tsx
  suite-native/module-trading/src/components/general/AccountSheet/TradeAccountsListFooter.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/NoAccountsComponent.test.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/TradeableAssetsSheet.tsx
  suite-native/module-trading/src/components/general/TradingBottomSheetSectionList.tsx
  suite-native/module-trading/src/hooks/__tests__/useReceiveAccountsListData.test.tsx
  suite-native/module-trading/src/hooks/__tests__/useSelectedAccount.test.ts
  suite-native/module-trading/src/hooks/useReceiveAccountsListData.ts
  suite-native/module-trading/src/hooks/useSectionList.tsx
  suite-native/module-trading/src/hooks/useSelectedAccount.ts
  suite-native/module-trading/src/navigation/TradingStackNavigator.tsx
  suite-native/module-trading/src/screens/ReceiveAccountsPickerScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#17415 fix(suite-native): show content in the bottom screen inset
  suite-native/module-accounts-management/src/screens/AccountDetailContentScreen.tsx
  suite-native/module-onboarding/src/screens/WelcomeScreen.tsx
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/src/components/ScreenContentWrapper.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionList.tsx
Labels: mobile

#17407 chore(suite): better bridge-deprecation url pattern
  suite-common/suite-config/src/routes.ts
Labels: no-project

#17486 chore(suite-native): Tests - fix unstable mock
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/AccountListItem.comp.test.tsx
Labels: no-project

#17485 chore(suite-native): tests for useSectionList
  suite-native/module-trading/src/hooks/__tests__/useSectionList.test.tsx
Labels: mobile, no-project

#17475 chore(connect-common): add fw binaries for 2.8.9
  packages/connect-common/files/firmware/t2b1/releases.json
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.8.7-bitcoinonly.bin
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.8.7.bin
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.8.9-bitcoinonly.bin
  packages/connect-common/files/firmware/t2b1/trezor-t2b1-2.8.9.bin
  packages/connect-common/files/firmware/t2t1/releases.json
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.8.8-bitcoinonly.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.8.8.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.8.9-bitcoinonly.bin
  packages/connect-common/files/firmware/t2t1/trezor-t2t1-2.8.9.bin
  packages/connect-common/files/firmware/t3b1/releases.json
  packages/connect-common/files/firmware/t3b1/trezor-t3b1-2.8.7-bitcoinonly.bin
  packages/connect-common/files/firmware/t3b1/trezor-t3b1-2.8.7.bin
  packages/connect-common/files/firmware/t3b1/trezor-t3b1-2.8.9-bitcoinonly.bin
  packages/connect-common/files/firmware/t3b1/trezor-t3b1-2.8.9.bin
  packages/connect-common/files/firmware/t3t1/releases.json
  packages/connect-common/files/firmware/t3t1/trezor-t3t1-2.8.7-bitcoinonly.bin
  packages/connect-common/files/firmware/t3t1/trezor-t3t1-2.8.7.bin
  packages/connect-common/files/firmware/t3t1/trezor-t3t1-2.8.9-bitcoinonly.bin
  packages/connect-common/files/firmware/t3t1/trezor-t3t1-2.8.9.bin
Labels: no-project

#17230 fix(suite-native): pin matrix screen oveflow
  suite-native/module-authorize-device/src/components/connect/PinOnKeypad.tsx
Labels: mobile

#17460 chore(connect): change `buildMessage` param. `encode` > `protocol`
  packages/connect/src/core/__tests__/onCallFirmwareUpdate.test.ts
  packages/transport/src/transports/abstractApi.ts
  packages/transport/src/transports/bridge.ts
  packages/transport/src/utils/send.ts
  packages/transport/tests/build-receive.test.ts
Labels: connect, no-project, cherry-pick🍒

#17498 feat(connect-web): enable coreMode auto by default
  packages/connect-web/src/impl/core-in-iframe.ts
Labels: no-project

#17479 fix(e2e): disable HW acceleration in playwright desktop
  packages/suite-desktop-core/e2e/support/electron.ts
Labels: no-project

#17462 feat(protocol): add `protocol-v2`
  packages/protocol/README.md
  packages/protocol/src/index.ts
  packages/protocol/src/protocol-bridge/decode.ts
  packages/protocol/src/protocol-v1/decode.ts
  packages/protocol/src/protocol-v2/constants.ts
  packages/protocol/src/protocol-v2/decode.ts
  packages/protocol/src/protocol-v2/encode.ts
  packages/protocol/src/protocol-v2/index.ts
  packages/protocol/src/types.ts
  packages/protocol/tests/protocol-v2.test.ts
Labels: connect, no-project, cherry-pick🍒

#17503 feat(connect-web): forward device events in popup mode
  packages/connect-popup/src/index.tsx
  packages/connect-web/src/impl/core-in-popup.ts
  packages/connect-web/src/popup/index.ts
Labels: no-project

#17488 fix(suite-native): icons size polishing
  suite-native/accounts/src/components/AccountsList/AccountsListItem.tsx
  suite-native/icons/src/CryptoIcon.tsx
  suite-native/icons/src/CryptoIconWithPercentage.tsx
  suite-native/icons/src/NetworkIcon.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionIcon.tsx
Labels: mobile, no-project

#17514 feat(suite-native): Mobile Trade: add unit test coverage limits
  suite-native/module-trading/jest.config.js
  suite-native/module-trading/package.json
  suite-native/module-trading/src/components/buy/__tests__/LegalSheet.comp.test.tsx
  suite-native/module-trading/src/components/general/AccountSheet/TradeAccountsListFooter.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/TradeAccountsListFooter.comp.test.tsx
  suite-native/module-trading/src/components/general/CountrySheet/__tests__/CountryListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/TradingEmptyComponent.comp.test.tsx
Labels: mobile, no-project

#17517 feat(suite-native): release mobile FW revision check
  suite-native/device/src/selectors.ts
  suite-native/feature-flags/src/__tests__/featureFlagsSlice.test.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  suite-native/module-settings/src/components/FeaturesSettings.tsx
Labels: mobile

#17528 chore(connect-popup): bump deprecation warning to 9.4.0
  packages/connect-ui/src/index.tsx
Labels: no-project

#17518 chore(packages): add native release script to global config
  package.json
  scripts/prepare-desktop-release.sh
  scripts/prepare-mobile-release.sh
Labels: no-project

#17534 Remove selectors returning whole state
  packages/suite-desktop-ui/src/support/DesktopUpdater.tsx
  packages/suite/src/components/suite/layouts/SuiteLayout/Sidebar/QuickActions/Update/UpdateTooltip.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ApplicationLogModal.tsx
  packages/suite/src/hooks/suite/useOnboarding.ts
  packages/suite/src/reducers/suite/desktopUpdateReducer.ts
Labels: no-project

#17540 feat(suite-native): update solana staking view only texts
  suite-native/intl/src/en.ts
Labels: mobile

#17529 npm-release: @trezor/connect 9.5.2-beta.1
  packages/blockchain-link-types/package.json
  packages/blockchain-link-utils/package.json
  packages/blockchain-link/package.json
  packages/connect-analytics/package.json
  packages/connect-common/package.json
  packages/connect-plugin-stellar/package.json
  packages/connect-web/package.json
  packages/connect-web/src/webextension/trezor-usb-permissions.js
  packages/connect-webextension/package.json
  packages/connect/CHANGELOG.md
  packages/connect/README.md
  packages/connect/package.json
  packages/connect/src/data/version.ts
  packages/protobuf/package.json
  packages/protocol/package.json
  packages/transport/package.json
  packages/utils/package.json
Labels: no-project

#17212 Fix/apply-global-patches-after-focus-install
  .github/actions/release-connect/action.yml
  .github/workflows/build-suite-native-preview.yml
  .github/workflows/release-suite-desktop-web-staging.yml
  .github/workflows/release-suite-native-develop.yml
  .github/workflows/release-suite-native-production.yml
Labels: mobile, no-project

#17554 fix(suite-native): welcome flow device disconnected alert
  suite-native/module-onboarding/src/screens/BiometricsScreen.tsx
Labels: mobile

#17559 fix(suite): improve http-receiver
  packages/suite-desktop-core/src/libs/http-receiver.ts
Labels: no-project

#17548 feat(suite-native): add real countries data to trading
  suite-native/module-trading/src/components/buy/CountryOfResidencePicker.tsx
  suite-native/module-trading/src/components/general/CountrySheet/CountryListItem.tsx
  suite-native/module-trading/src/components/general/CountrySheet/CountrySheet.tsx
  suite-native/module-trading/src/components/general/CountrySheet/__tests__/CountryListItem.comp.test.tsx
  suite-native/module-trading/src/types.ts
Labels: +Invity, mobile, no-project

#17431 feat(connect): common function for DeviceEvents listeners registration
  packages/connect/src/core/__tests__/onCallFirmwareUpdate.test.ts
  packages/connect/src/core/index.ts
  packages/connect/src/core/onCallFirmwareUpdate.ts
Labels: connect, no-project, cherry-pick🍒

#17539 fix(transport): `UDP` read from buffer or promise
  packages/transport/src/api/udp.ts
  packages/transport/src/utils/readMessageBuffer.ts
  packages/transport/tests/readMessageBuffer.test.ts
Labels: no-project

#17515 fix(suite): workaround 'loading takes too long' on big accounts by in…
  packages/suite/src/components/suite/Preloader/Preloader.tsx
Labels: no-project

#17569 chore(suite-native): bump suite-native version to 25.3.2
  suite-native/app/package.json
Labels: no-project

#17581 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations, cherry-pick🍒

#17584 fix(device-utils): add tsx as dev dependency
  packages/device-utils/package.json
  yarn.lock
Labels: no-project

#17547 feat(suite-native): set trading environment
  suite-native/module-dev-utils/package.json
  suite-native/module-dev-utils/src/components/TradingEnvironmentSelect.tsx
  suite-native/module-dev-utils/src/redux.d.ts
  suite-native/module-dev-utils/src/screens/DevUtilsScreen.tsx
  suite-native/module-dev-utils/tsconfig.json
  suite-native/module-trading/src/__tests__/tradingSlice.test.ts
  suite-native/module-trading/src/tradingSlice.ts
  suite-native/state/src/extraDependencies.ts
  yarn.lock
Labels: +Invity, mobile

#17586 chore(suite-native): do not upload @trezor/transport-bluetooth to EAS…
  .easignore
Labels: mobile, no-project

#17571 ci(github): add new npm packages to release action
  .github/actions/release-connect-npm/action.yml
Labels: no-project

#17578 feat(transport-bridge): start logging libusb errors
  packages/transport-bridge/src/core.ts
Labels: no-project

#17470 feat(suite): Add new color palette (1.0.0 -> 1.1.0)
  package.json
  packages/components/src/components/DataAnalytics.tsx
  packages/components/src/components/ElevationContext/ElevationContext.stories.tsx
  packages/components/src/components/buttons/buttonStyleUtils.ts
  packages/components/src/components/typography/Text/Text.stories.tsx
  packages/suite-desktop-core/e2e/tests/settings/autodetect.test.ts
  packages/theme/src/colors.ts
  packages/theme/src/index.ts
  packages/theme/src/palette.ts
  packages/utils/src/hexToRgba.ts
  scripts/convertFigmaPalette.ts
Labels: mobile, changelog

#17603 chore(suite-native): move trading state to tradingNew
  suite-native/module-trading/src/__tests__/tradingSlice.test.ts
  suite-native/module-trading/src/components/buy/__tests__/ReceiveAccountPicker.comp.test.tsx
  suite-native/module-trading/src/tradingSlice.ts
  suite-native/state/src/reducers.ts
Labels: +Invity, mobile

#17601 fix(suite-data): fix wallet connect source keys for translations
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/SettingsDebug/WalletConnect.tsx
Labels: no-project

#17610 chore(suite-web): move vite config to suite-build
  packages/suite-build/eslint.config.mjs
  packages/suite-build/package.json
  packages/suite-build/vite.config.ts
  packages/suite-web/eslint.config.mjs
  packages/suite-web/package.json
  yarn.lock
Labels: no-project

#17629 fix(connect): update typescript in install test
  packages/connect/e2e/test-yarn-install.sh
Labels: no-project

#17631 feat(suite-native): add payment method picker stub
  suite-native/module-trading/src/components/buy/PaymentCard.tsx
  suite-native/module-trading/src/components/buy/PaymentMethodPicker.tsx
  suite-native/module-trading/src/components/buy/__tests__/PaymentMethodPicker.test.tsx
  suite-native/module-trading/src/components/general/PaymentMethodsSheet/PaymentMethodListItem.tsx
  suite-native/module-trading/src/components/general/PaymentMethodsSheet/PaymentMethodsSheet.tsx
  suite-native/module-trading/src/components/general/PaymentMethodsSheet/__tests__/PaymentMethodListItem.comp.test.tsx
Labels: +Invity, mobile

#17602 fix(suite-desktop-core): refactor desktop state patches to avoid breaking change
  packages/suite-desktop-core/e2e/support/electron.ts
  packages/suite-desktop-core/src/__tests__/app-utils.test.ts
  packages/suite-desktop-core/src/libs/app-utils.ts
Labels: no-project

#17627 fix(suite-native): initialized device connection
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
Labels: mobile

#17643 chore(transport): usb - use arrayPartion instead of two filters
  packages/transport/src/api/usb.ts
Labels: no-project

#17647 fix(trading): buy dispatch
  packages/suite/src/hooks/wallet/trading/form/useTradingBuyForm.tsx
Labels: bug, +Invity

#17545 feat(native-suite): handling discovery/disconnect state in Settings
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/module-device-settings/src/components/DeviceAuthenticityCard.tsx
  suite-native/module-device-settings/src/components/DeviceFirmwareCard.tsx
  suite-native/module-device-settings/src/components/DevicePinActionButton.tsx
  suite-native/module-device-settings/src/hooks/useDeviceConnectionGuard.ts
  suite-native/module-device-settings/src/navigation/DeviceAuthenticityStackNavigator.tsx
  suite-native/module-device-settings/src/navigation/DevicePinProtectionStackNavigator.tsx
  suite-native/module-device-settings/src/screens/ConfirmFirmwareUpdateScreen.tsx
Labels: mobile

#17546 fix(trading): selecting account
  packages/suite/src/hooks/wallet/trading/form/common/useTradingFormActions.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingSellForm.ts
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputAccount.tsx
Labels: bug, +Invity

#17678 fix(suite-native): Mobile Trade: display country name and flag in buy…
  suite-native/module-trading/src/components/buy/CountryOfResidencePicker.tsx
  suite-native/module-trading/src/components/general/TradingOverviewRow.tsx
Labels: mobile, no-project

#17673 fix(suite-desktop-core): purge userData by using a flag instead of in playwright
  packages/suite-desktop-core/e2e/support/electron.ts
  packages/suite-desktop-core/e2e/tests/bridge-tor/spawn-bridge-daemon.test.ts
  packages/suite-desktop-core/src/app.ts
  packages/suite-desktop-core/src/libs/app-utils.ts
Labels: no-project

#17638 feat(suite-native): device onboarding tutorial
  suite-native/device/package.json
  suite-native/device/src/components/ContinueOnTrezorScreenContent.tsx
  suite-native/device/src/index.ts
  suite-native/device/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-dev-utils/tsconfig.json
  suite-native/module-device-onboarding/package.json
  suite-native/module-device-onboarding/src/navigation/DeviceOnboardingStackNavigator.tsx
  suite-native/module-device-onboarding/src/screens/ConfirmFirmwareUpdateScreen.tsx
  suite-native/module-device-onboarding/src/screens/DeviceTutorialScreen.tsx
  suite-native/module-device-onboarding/src/screens/FirmwareInstallationScreen.tsx
  suite-native/module-device-onboarding/tsconfig.json
  suite-native/module-device-settings/package.json
  suite-native/module-device-settings/src/screens/ContinueOnTrezorScreen.tsx
  suite-native/module-device-settings/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#17664 chore(transport): do not claim interface that is already claimed
  packages/transport/src/api/usb.ts
Labels: Bridge -> nodeUSB, no-project

#17700 fix(transport): usb: select configuration only if not already selected
  packages/transport/src/api/usb.ts
Labels: no-project

#17690 feat(native-suite): remove how to update fw btn
  suite-native/intl/src/en.ts
  suite-native/module-device-settings/src/components/HowToUpdateBottomSheet.tsx
  suite-native/module-device-settings/src/screens/DeviceSettingsModalScreen.tsx
Labels: mobile

#17697 chore(connect-popup): refactor old templates
  packages/connect-popup/src/static/popup.html
  packages/connect-popup/src/static/views/amount-too-low.html
  packages/connect-popup/src/static/views/bootloader.html
  packages/connect-popup/src/static/views/browser-not-supported.html
  packages/connect-popup/src/static/views/check-address.html
  packages/connect-popup/src/static/views/confirm-output.html
  packages/connect-popup/src/static/views/connect.html
  packages/connect-popup/src/static/views/device-management.html
  packages/connect-popup/src/static/views/export-account-info.html
  packages/connect-popup/src/static/views/export-address.html
  packages/connect-popup/src/static/views/export-xpub.html
  packages/connect-popup/src/static/views/firmware.html
  packages/connect-popup/src/static/views/follow-device.html
  packages/connect-popup/src/static/views/initialize.html
  packages/connect-popup/src/static/views/insufficient-funds.html
  packages/connect-popup/src/static/views/loader.html
  packages/connect-popup/src/static/views/no-backup.html
  packages/connect-popup/src/static/views/not-in-bootloader.html
  packages/connect-popup/src/static/views/passphrase-on-device.html
  packages/connect-popup/src/static/views/passphrase.html
  packages/connect-popup/src/static/views/permissions.html
  packages/connect-popup/src/static/views/pin.html
  packages/connect-popup/src/static/views/seedless.html
  packages/connect-popup/src/static/views/select-account.html
  packages/connect-popup/src/static/views/select-device.html
  packages/connect-popup/src/static/views/select-fee.html
  packages/connect-popup/src/static/views/simple-message.html
  packages/connect-popup/src/static/views/smartphones-not-supported.html
  packages/connect-popup/src/static/views/unknown.html
  packages/connect-popup/src/static/views/word.html
  packages/connect-popup/src/view/common.tsx
  packages/connect-popup/src/view/confirmation.ts
  packages/connect-popup/src/view/firmwareNotCompatible.ts
  packages/connect-popup/src/view/firmwareNotSupported.ts
  packages/connect-popup/src/view/selectAccount.ts
  packages/connect-popup/src/view/selectDevice.ts
  packages/connect-popup/src/view/selectFee.ts
  packages/connect-popup/webpack/prod.webpack.config.ts
  packages/connect/src/api/getAccountDescriptor.ts
  packages/connect/src/api/getAccountInfo.ts
  packages/connect/src/utils/__fixtures__/accountUtils.ts
  packages/connect/src/utils/accountUtils.ts
Labels: connect, no-project

#17702 fix(connect-popup): use local path to core
  packages/connect-popup/src/index.tsx
  packages/connect-popup/webpack/dev.webpack.config.ts
Labels: connect, no-project

#17713 chore(connect): in decode eth definitions move common proto messages …
  packages/connect/src/api/ethereum/ethereumDefinitions.ts
Labels: no-project

#17727 fix(connect-web): dev server output path
  packages/connect-web/webpack/dev.webpack.config.ts
Labels: no-project

#17729 chore(suite-native): Improve suite-native/test-utils for testing-library
  suite-native/accounts/jest.config.js
  suite-native/accounts/package.json
  suite-native/accounts/src/components/__tests__/AccountLabelFieldHint.comp.test.tsx
  suite-native/app/jest.config.js
  suite-native/app/package.json
  suite-native/app/src/navigation/__tests__/AppTabNavigator.comp.test.tsx
  suite-native/atoms/src/Card/__tests__/Card.comp.test.tsx
  suite-native/atoms/src/__tests__/PriceChangeBadge.comp.test.tsx
  suite-native/icons/src/tests/CryptoIconWithNetwork.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/CountryOfResidencePicker.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/LegalSheet.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/PaymentMethodPicker.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/ReceiveAccountCryptoBalance.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/ReceiveAccountPicker.comp.test.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/AccountListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/NoAccountsComponent.test.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/TradeAccountsListFooter.comp.test.tsx
  suite-native/module-trading/src/components/general/CountrySheet/__tests__/CountryListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/PaymentMethodsSheet/__tests__/PaymentMethodListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/__tests__/FavouriteIcon.comp.test.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/__tests__/TradeableAssetListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/__tests__/TradeableAssetsSheet.comp.test.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/__tests__/TradeableAssetsSheetHeader.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/AccountAddress.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/NetworkBadge.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/NetworkSymbolExtendedFormatter.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/SearchInputWithCancel.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/SelectTradeableAssetButton.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/TradeableAssetButton.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/TradingEmptyComponent.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/TradingOverviewRow.comp.test.tsx
  suite-native/module-trading/src/hooks/__tests__/useReceiveAccountsListData.test.tsx
  suite-native/module-trading/src/hooks/__tests__/useSectionList.test.tsx
  suite-native/module-trading/src/hooks/__tests__/useTradeableAssetDominantColor.test.ts
  suite-native/module-trading/src/navigation/__tests__/TradingStackNavigator.comp.test.tsx
  suite-native/test-utils/src/createRender.tsx
  suite-native/test-utils/src/index.tsx
  suite-native/test-utils/src/render.tsx
Labels: mobile, no-project

#17086 feat(suite-native): update social network links
  suite-common/icons/generateIconFont.ts
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.json
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.ttf
  suite-native/app/app.config.ts
  suite-native/intl/src/en.ts
  suite-native/link/src/useOpenLink.ts
  suite-native/module-settings/src/components/AboutUsBanners.tsx
Labels: mobile

#17750 chore(connect): outdated version error
  packages/connect-iframe/src/index.ts
  packages/connect-popup/src/index.tsx
  packages/connect-ui/src/components/InfoPanel.tsx
  packages/connect-ui/src/index.tsx
  packages/connect-ui/src/views/Error.tsx
  packages/connect/src/utils/versionCheck.ts
Labels: connect, no-project

#17758 fix(connect-ui): improve no transport error message on supported browsers
  packages/connect-ui/src/views/Transport.tsx
Labels: connect, no-project

#17473 fix(suite): change the Copy and Color of the banner signaling new dev…
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/en.json
  packages/suite/src/components/suite/ConnectDevicePrompt.tsx
  packages/suite/src/components/suite/PrerequisitesGuide/PrerequisitesGuide.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/suite/SwitchDevice/CardWithDevice.tsx
  suite-common/suite-utils/src/device.ts
Labels: QA OK

#17682 docs(suite-desktop): update Suite Desktop docs
  docs/packages/suite-desktop.md
Labels: documentation, no-project

#17774 Fw update lang update
  packages/connect/src/core/onCallFirmwareUpdate.ts
Labels: release, cherry-pick🍒

#17771 fix(connect-popup): fix test for new no transport message
  packages/connect-popup/e2e/tests/transport.test.ts
Labels: connect, no-project

#17721 feat(suite-native): account picker with account types
  jest.config.native.js
  suite-native/module-trading/src/__fixtures__/accounts.json
  suite-native/module-trading/src/components/general/AccountSheet/AccountListAddressItem.tsx
  suite-native/module-trading/src/components/general/AccountSheet/AccountListBaseItem.tsx
  suite-native/module-trading/src/components/general/AccountSheet/AccountListItem.tsx
  suite-native/module-trading/src/components/general/AccountSheet/AccountsList.tsx
  suite-native/module-trading/src/components/general/AccountSheet/AccountsListFooter.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/AccountListAddressItem.test.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/AccountListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/AccountsList.comp.test.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/AccountsListFooter.comp.test.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/NoAccountsComponent.comp.test.tsx
  suite-native/module-trading/src/hooks/__tests__/useReceiveAccountsListData.test.tsx
  suite-native/module-trading/src/screens/ReceiveAccountsPickerScreen.tsx
Labels: mobile

#17494 test(suite-native): app settings e2e
  suite-native/app/e2e/pageObjects/accountImportActions.ts
  suite-native/app/e2e/pageObjects/coinEnablingActions.ts
  suite-native/app/e2e/pageObjects/deviceSettingsActions.ts
  suite-native/app/e2e/pageObjects/homeActions.ts
  suite-native/app/e2e/pageObjects/send/sendOutputsReviewActions.ts
  suite-native/app/e2e/pageObjects/settingsActions.ts
  suite-native/app/e2e/pageObjects/tabBarActions.ts
  suite-native/app/e2e/tests/appSettings.test.ts
  suite-native/app/e2e/tests/appSettingsWithDevice.test.ts
  suite-native/app/e2e/tests/deeplinkPopup.test.ts
  suite-native/app/e2e/tests/deviceSettings.test.ts
  suite-native/app/e2e/tests/onboardAndConnect.test.ts
  suite-native/app/e2e/tests/passphraseFlow.test.ts
  suite-native/app/e2e/tests/receive.test.ts
  suite-native/app/e2e/tests/send.test.ts
  suite-native/app/e2e/utils.ts
  suite-native/atoms/src/DiscreetText/DiscreetText.tsx
  suite-native/atoms/src/DiscreetText/DiscreetTextTrigger.tsx
  suite-native/atoms/src/Select/Select.tsx
  suite-native/atoms/src/Select/SelectItem.tsx
  suite-native/atoms/src/Select/SelectTrigger.tsx
  suite-native/atoms/src/Sheet/BottomSheet.tsx
  suite-native/formatters/src/components/FiatBalanceFormatter.tsx
  suite-native/formatters/src/utils.ts
  suite-native/graph/src/components/GraphFiatBalance.tsx
  suite-native/module-settings/src/components/CryptoUnitsSelector.tsx
  suite-native/module-settings/src/components/CurrencySelector.tsx
  suite-native/module-settings/src/components/TouchableSwitchRow.tsx
  suite-native/module-settings/src/components/ViewOnly/WalletRow.tsx
  suite-native/module-settings/src/navigation/SettingsStackNavigator.tsx
  suite-native/module-settings/src/screens/SettingsPrivacyAndSecurityScreen.tsx
  suite-native/module-settings/src/screens/SettingsViewOnlyScreen.tsx
Labels: mobile

#17639 chore(blockchain-link): move solana types
  packages/blockchain-link-types/package.json
  packages/blockchain-link-types/src/solana.ts
  packages/blockchain-link-utils/package.json
  packages/blockchain-link-utils/src/solana-types.ts
  packages/blockchain-link-utils/src/solana.ts
  packages/blockchain-link-utils/src/tests/solana.test.ts
  packages/blockchain-link/src/workers/solana/index.ts
  scripts/list-outdated-dependencies/trends-dependencies.txt
  yarn.lock
Labels: no-project

#17825 chore(suite-native): add node-gyp to main dev dependencies to satisfy sharp build
  package.json
  scripts/list-outdated-dependencies/common-dependencies.txt
  yarn.lock
Labels: mobile, no-project

#17834 fix(suite): fix migration test
  packages/suite-desktop-core/e2e/tests/suite/db-migration.test.ts
Labels: no-project

#17857 chore(blockchain-link): update blockbook-api types
  packages/blockchain-link-types/src/blockbook-api.ts
Labels: no-project

#17858 fix(suite-desktop): connect-ws: move process detection to popup.hands…
  packages/suite-desktop-core/src/libs/connect-ws.ts
  packages/suite-desktop-core/src/libs/find-process-from-port.ts
Labels: no-project

#17417 feat(blockchain-link): migrate ripple-lib to xrpl.js
  jest.config.native.js
  packages/blockchain-link-types/src/common.ts
  packages/blockchain-link-types/src/params.ts
  packages/blockchain-link-utils/package.json
  packages/blockchain-link-utils/src/ripple.ts
  packages/blockchain-link/package.json
  packages/blockchain-link/src/workers/ripple/index.ts
  packages/blockchain-link/tests/integration/ripple.test.ts
  packages/blockchain-link/tests/unit/connection.test.ts
  packages/blockchain-link/tests/unit/fixtures/accounts/ripple/rfkV3EoXimH6JrG1QAyofgbVhnyZZDjWSj.json
  packages/blockchain-link/tests/unit/fixtures/estimateFee.ts
  packages/blockchain-link/tests/unit/fixtures/getAccountInfo-ripple.ts
  packages/blockchain-link/tests/unit/fixtures/getTransaction.ts
  packages/blockchain-link/tests/unit/fixtures/notifications-ripple.ts
  packages/blockchain-link/webpack/dev.js
  packages/blockchain-link/webpack/workers.web.js
  packages/connect-iframe/webpack/base.webpack.config.ts
  patches/README.md
  patches/ripple-lib+1.10.1.patch
  scripts/list-outdated-dependencies/trends-dependencies.txt
  suite-common/wallet-core/src/blockchain/blockchainThunks.ts
  suite-native/test-utils/src/TextEncoderMock.js
  yarn.lock
Labels: build-desktop

#17786 Connect in desktop preparation
  packages/connect-web/src/impl/core-in-suite-desktop.ts
  packages/connect/src/constants/errors.ts
  packages/suite-desktop-api/src/messages.ts
  packages/suite-desktop-core/src/libs/connect-ws.ts
Labels: no-project

#17873 chore(suite-native): Improve store initialization in component tests
  suite-native/test-utils/package.json
  suite-native/test-utils/src/StoreProviderForTests.tsx
  suite-native/test-utils/src/render.tsx
  yarn.lock
Labels: no-project

#17879 chore(suite-native): Enforce more strict test coverage for suite-nati…
  suite-native/module-trading/jest.config.js
Labels: mobile, no-project

#17886 ci: run e2e-test-trezor-user-env-link tests nightly
  .github/workflows/test-trezor-user-env-link-e2e.yml
Labels: no-project

#17887 fix(message-system): anchor to update app
  suite-common/message-system/config/config.v1.json
Labels: no-project

#17644 feat(suite): normalize sorting of the connected devices in the device…
  packages/suite/src/views/suite/SwitchDevice/SwitchDevice.tsx
  suite-common/suite-types/src/device.ts
  suite-common/suite-utils/src/device.ts
  suite-common/wallet-core/src/device/deviceReducer.ts
Labels: QA OK

#17902 fix(suite): include migrations under correct db version
  packages/suite/src/storage/migrations/index.ts
Labels: no-project

#17850 feat(suite-native): prepare webview to process buy trade form
  jest.config.native.js
  scripts/list-outdated-dependencies/mobile-dependencies.txt
  suite-native/app/package.json
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/module-trading/package.json
  suite-native/module-trading/src/index.ts
  suite-native/module-trading/src/jest.setup.tsx
  suite-native/module-trading/src/screens/TradingWebviewScreen.tsx
  suite-native/module-trading/src/screens/__tests__/TradeWebviewScreen.comp.test.tsx
  suite-native/module-trading/src/utils/__tests__/tradeFormUtils.test.ts
  suite-native/module-trading/src/utils/tradeFormUtils.ts
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#17929 chore(connect): update device authenticity config
  packages/connect/src/data/deviceAuthenticityConfig.ts
Labels: no-project

#17946 feat(suite-native): polished UI of TradeableAssetButton
  suite-native/module-trading/src/__fixtures__/tradeableAssets.ts
  suite-native/module-trading/src/components/general/FiatCurrencyButton.tsx
  suite-native/module-trading/src/components/general/FiatCurrencyIcon.tsx
  suite-native/module-trading/src/components/general/TradeableAssetButton.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/__tests__/TradeableAssetListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/TradeableAssetButton.comp.test.tsx
Labels: mobile

#17940 feat(suite-native): Mobile Trade: Full list of supported currency names
  suite-native/module-trading/src/selectors/__tests__/buySelectors.test.ts
  suite-native/module-trading/src/selectors/buySelectors.ts
  suite-native/module-trading/src/utils/supportedFiatCurrencies.ts
Labels: mobile

#17974 chore(message-system): introduce t3w1 type to message system schema
  suite-common/message-system/schema/config.schema.v1.json
Labels: message-system

#17983 fix(suite-types): message system t3w1 type
  suite-common/suite-types/src/messageSystem.ts
Labels: no-project

#17880 feat(trading): Update DCA landing page (#17885)
  packages/components/src/components/Image/Image.tsx
  packages/components/src/components/Image/images.ts
  packages/suite-data/files/images/png/trading-dca-invity-app-dark.webp
  packages/suite-data/files/images/png/trading-dca-invity-app-dark@2x.webp
  packages/suite-data/files/images/png/trading-dca-invity-app.webp
  packages/suite-data/files/images/png/trading-dca-invity-app@2x.webp
  packages/suite-data/files/translations/en.json
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TradingDCAModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/UserContextModal.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/trading/DCA/TradingDCALanding.tsx
  suite-common/suite-types/src/modal.ts
Labels: +Invity

#18005 chore(connect-explorer, connect-explorer-theme): upgrade next
  packages/connect-explorer-theme/package.json
  packages/connect-explorer/package.json
  yarn.lock
Labels: dependencies, no-project

#18006 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations
