Repository trezor/trezor-suite, pull requests merged in 2025-02, with the labels that each got.

#16754 fix(fiat-services): fix fetching fiat rates for timestamps range
  suite-common/fiat-services/src/coingecko.ts
Labels: no-project

#16756 ci(script): fix connect test generator
  scripts/ci/connect-test-matrix-generator.js
Labels: connect, no-project

#16751 GitBook revision update
  packages/suite-data/src/guide/constants.ts
Labels: guide

#16762 feat(suite-desktop): enable node-bridge in EAP
  packages/suite-desktop-core/src/modules/bridge.ts
Labels: no-project

#16672 feat(connect): increase interaction timeout from 10 to 20 minutes
  packages/connect/src/data/connectSettings.ts
Labels: no-project

#16699 chore(suite-desktop): enable trezor-connect logger when debug mode is…
  packages/suite-desktop-core/src/modules/trezor-connect.ts
Labels: no-project

#16616 feat(suite-native): onboarding unitialized device landing screen
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/device/src/hooks/useDetectDeviceError.tsx
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/device/src/index.ts
  suite-native/device/src/selectors.ts
  suite-native/device/src/types.ts
  suite-native/device/src/utils.ts
  suite-native/intl/src/en.ts
  suite-native/module-onboarding/package.json
  suite-native/module-onboarding/redux.d.ts
  suite-native/module-onboarding/src/assets/t3b1.png
  suite-native/module-onboarding/src/assets/t3t1.png
  suite-native/module-onboarding/src/components/HeaderUnderlineSvg.tsx
  suite-native/module-onboarding/src/navigation/OnboardingStackNavigator.tsx
  suite-native/module-onboarding/src/screens/UninitializedDeviceLandingScreen.tsx
  suite-native/module-onboarding/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#16606 refactor(suite-native): icon list item used in analytics screen
  suite-native/module-onboarding/src/components/AnalyticsInfoRow.tsx
Labels: mobile

#16392 fix(suite): fix migration test
  packages/suite-web/e2e/tests/suite/database-migration.test.ts
Labels: QA, no-project

#16770 chore(connect): re-enable logs redacting; redact also features
  packages/connect/src/device/DeviceCommands.ts
Labels: no-project

#16761 chore(trading): move type to suite-common
  packages/suite/src/actions/suite/storageActions.ts
  packages/suite/src/actions/wallet/tradingBuyActions.ts
  packages/suite/src/actions/wallet/tradingInfoActions.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingBuyFormDefaultValues.tsx
  packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingPaymentMethod.tsx
  packages/suite/src/hooks/wallet/trading/form/useTradingSellForm.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingSellFormDefaultValues.ts
  packages/suite/src/hooks/wallet/trading/useTradingDetail.ts
  packages/suite/src/hooks/wallet/trading/useTradingWatchTrade.ts
  packages/suite/src/reducers/wallet/__tests__/tradingReducer.test.ts
  packages/suite/src/reducers/wallet/tradingReducer.ts
  packages/suite/src/storage/definitions.ts
  packages/suite/src/storage/migrations/trading/migrationCoinmarketToTrading.ts
  packages/suite/src/types/trading/trading.ts
  packages/suite/src/types/trading/tradingDetail.ts
  packages/suite/src/types/trading/tradingForm.ts
  packages/suite/src/types/wallet/tradingCommonTypes.ts
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputPaymentMethod.tsx
  packages/suite/src/views/wallet/trading/common/TradingTransactions/TradingTransaction/TradingTransactionAmounts.tsx
  packages/suite/src/views/wallet/trading/common/TradingTransactions/TradingTransaction/TradingTransactionInfo.tsx
  packages/suite/src/views/wallet/trading/common/TradingTransactions/TradingTransaction/TradingTransactionStatus.tsx
  packages/suite/src/views/wallet/trading/common/TradingTransactions/TradingTransactionExchange.tsx
  packages/suite/src/views/wallet/trading/common/TradingTransactions/TradingTransactionsBuy.tsx
  packages/suite/src/views/wallet/trading/common/TradingTransactions/TradingTransactionsSell.tsx
  suite-common/trading/src/types.ts
Labels: +Invity, code

#16781 feat(trading): update l2 icons
  packages/components/src/components/AssetLogo/AssetLogo.tsx
  packages/product-components/src/components/SelectAssetModal/AssetItem.tsx
  packages/suite/src/views/wallet/trading/common/TradingCoinLogo.tsx
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputCryptoSelect.tsx
Labels: +Invity

#16719 fix(trading): trading account
  packages/suite/src/middlewares/wallet/tradingMiddleware.ts
Labels: bug, +Invity

#16779 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations, no-project

#16737 feat(suite): change copy for Device authentication ghost modal
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AuthenticateDeviceFailModal.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/onboarding/steps/SecurityCheck/DeviceAuthenticity.tsx
Labels: no-project

#16790 chore(suite-native): configure appleTeamId for iOS
  suite-native/app/app.config.ts
Labels: mobile

#16796 ci(scripts): add connect plugins to release process
  scripts/ci/get-connect-dependencies-to-release.ts
Labels: no-project

#16804 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#16805 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/zh.json
Labels: translations

#16810 chore(suite): L2 native token name
  suite-common/wallet-config/src/networksConfig.ts
Labels: release

#16806 chore(suite-data): update tor binaries
  packages/suite-data/files/bin/tor/linux-arm64/tor
  packages/suite-data/files/bin/tor/linux-x64/tor
  packages/suite-data/files/bin/tor/mac-arm64/tor
  packages/suite-data/files/bin/tor/mac-x64/tor
  packages/suite-data/files/bin/tor/update.sh
  packages/suite-data/files/bin/tor/win-x64/tor.exe
Labels: tor

#16812 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite/src/support/messages.ts
Labels: translations

#16813 fix DeviceBanner layout
  packages/suite/src/components/settings/DeviceBanner.tsx
Labels: bug

#16784 feat(suite): update network icons
  packages/product-components/src/components/CoinLogo/CoinLogo.tsx
  packages/product-components/src/components/CoinLogo/networks.ts
  packages/product-components/src/components/SelectAssetModal/NetworkTabs.tsx
  packages/product-components/src/images/networks/ada.svg
  packages/product-components/src/images/networks/arb.svg
  packages/product-components/src/images/networks/base.svg
  packages/product-components/src/images/networks/bch.svg
  packages/product-components/src/images/networks/bsc.svg
  packages/product-components/src/images/networks/btc.svg
  packages/product-components/src/images/networks/btc_test.svg
  packages/product-components/src/images/networks/doge.svg
  packages/product-components/src/images/networks/dsol.svg
  packages/product-components/src/images/networks/etc.svg
  packages/product-components/src/images/networks/eth.svg
  packages/product-components/src/images/networks/ltc.svg
  packages/product-components/src/images/networks/op.svg
  packages/product-components/src/images/networks/pol.svg
  packages/product-components/src/images/networks/sol.svg
  packages/product-components/src/images/networks/tada.svg
  packages/product-components/src/images/networks/thol.svg
  packages/product-components/src/images/networks/tsep.svg
  packages/product-components/src/images/networks/txrp.svg
  packages/product-components/src/images/networks/xrp.svg
  packages/product-components/src/images/networks/zec.svg
  packages/suite/src/components/suite/CoinList/Coin.tsx
  packages/suite/src/components/suite/layouts/SuiteLayout/PageHeader/PageNames/AccountName/AccountDetails.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/TxDetailModal/BasicTxDetails.tsx
  packages/suite/src/components/wallet/WalletLayout/AccountTopPanel/AccountTopPanel.tsx
  packages/suite/src/components/wallet/WalletLayout/AccountsMenu/CoinsFilter.tsx
  packages/suite/src/views/wallet/send/Outputs/TokenSelect/TokenSelect.tsx
  packages/suite/src/views/wallet/transactions/TradeBox/TradeBox.tsx
Labels: release

#16817 chore(suite): bump beta version to 25.3.0
  packages/suite/package.json
Labels: no-project

#16830 chore(wallet-core): add custom fetch limits for evms and xrp
  suite-common/wallet-config/src/utils.ts
  suite-common/wallet-core/src/blockchain/blockchainThunks.ts
Labels: release

#16831 fix(product-components): connect-explorer missing displaySymbol crash
  packages/product-components/src/components/CoinLogo/CoinLogo.tsx
Labels: no-project

#16799 feat(blockchain-link): add btc testnet4 to ui
  packages/blockchain-link/src/ui/config.ts
Labels: no-project

#16722 feat(suite-native): add DeviceCompromisedModal for FW revision check
  suite-native/app/e2e/utils.ts
  suite-native/app/package.json
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/app/tsconfig.json
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/intl/src/en.ts
  suite-native/module-authenticity-checks/package.json
  suite-native/module-authenticity-checks/src/index.ts
  suite-native/module-authenticity-checks/src/screens/DeviceCompromisedModalScreen.tsx
  suite-native/module-authenticity-checks/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#16749 feat(suite-native): block receiving when device compromised
  suite-native/intl/src/en.ts
  suite-native/module-accounts-management/package.json
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
  suite-native/module-accounts-management/tsconfig.json
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
  suite-native/receive/src/screens/ReceiveAccountsScreen.tsx
  suite-native/receive/src/screens/ReceiveAddressScreen.tsx
  suite-native/receive/src/screens/ReceiveBlockedDeviceCompromisedScreen.tsx
  suite-native/transactions/package.json
  suite-native/transactions/src/components/TransactionsEmptyState.tsx
  suite-native/transactions/tsconfig.json
  yarn.lock
Labels: mobile

#16855 GitBook revision update
  packages/suite-data/src/guide/constants.ts
Labels: guide, no-project

#16869 fix(connect): ts config in installing connect test
  packages/connect/e2e/test-yarn-install.sh
Labels: no-project

#16870 ci(github): disabling unchained tests for now
  .github/workflows/test-connect-popup.yml
Labels: no-project

#16879 fix(trading): stuck account
  packages/suite/src/hooks/wallet/trading/form/common/useTradingAccountKey.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingSellForm.ts
  packages/suite/src/middlewares/wallet/tradingMiddleware.ts
Labels: bug, +Invity

#16888 chore(ci): fix artifact version download for autoupdate test
  .github/workflows/release-suite-desktop-web-staging.yml
Labels: no-project

#16856 no changes, just cleanup
  suite-common/wallet-core/src/device/deviceThunks.ts
Labels: no-project

#16858 chore(suite-desktop): improve/fix misleading log message
  packages/suite-desktop-core/src/modules/index.ts
Labels: no-project

#16896 chore(connect): reduce verbosity of logs for better readability of te…
  packages/connect/src/core/index.ts
  packages/connect/src/index.ts
Labels: no-project

#16902 ci(scripts): fix add label argument for create pr
  scripts/ci/check-connect-data.ts
Labels: no-project

#16906 fix(suite-native): navigation animation tweaks
  suite-native/app/src/navigation/RootStackNavigator.tsx
Labels: mobile

#16861 fix(transport): transferOut timeout must be inside try block
  packages/transport/src/api/usb.ts
Labels: no-project

#16894 chore: remove unit test noise
  packages/request-manager/tests/interceptor-whitelist.test.ts
  packages/suite/src/components/suite/Preloader/__tests__/Preloader.test.tsx
  packages/suite/src/utils/suite/__tests__/ethereumStaking.test.ts
Labels: no-project

#16901 feat(mobile): update Skia
  suite-native/app/package.json
  suite-native/atoms/package.json
  suite-native/firmware/package.json
  suite-native/graph/package.json
  suite-native/icons/package.json
  suite-native/module-accounts-import/package.json
  suite-native/react-native-graph/package.json
  suite-native/receive/package.json
  suite-native/transactions/package.json
  yarn.lock
Labels: mobile

#16907 feat(suite-naive): release L2 networks
  suite-native/config/src/supportedNetworks.ts
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/feature-flags/src/__tests__/featureFlagsSlice.test.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-accounts-import/src/components/SelectableNetworkList.tsx
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
Labels: mobile

#16898 feat(suite-native): disable FW rev check by message system
  suite-common/message-system/src/messageSystemTypes.ts
  suite-native/device/package.json
  suite-native/device/src/selectors.ts
  suite-native/device/tsconfig.json
  yarn.lock
Labels: mobile

#16918 fix(suite-native): develop build pipeline fix
  .github/workflows/release-suite-native-develop.yml
Labels: mobile

#16915 request Destination tag for ripple
  suite-native/intl/src/en.ts
  suite-native/module-send/src/components/DestinationTagInput.tsx
  suite-native/module-send/src/screens/SendOutputsScreen.tsx
  suite-native/module-send/src/sendOutputsFormSchema.ts
  suite-native/receive/src/screens/ReceiveAddressScreen.tsx
Labels: mobile, Ripple

#16919 fix(suite-native): add missing footer bottom margin on coin enabling init screen
  suite-native/coin-enabling/src/screens/CoinEnablingInitScreen.tsx
Labels: mobile

#16924 chore(scripts): add lint to generatePackage templates
  scripts/package-template-native/package.json
  scripts/package-template/package.json
Labels: DX, no-project

#16916 fix(suite-native): has account transactions selector
  packages/suite/src/views/wallet/transactions/CoinjoinSummary/CoinjoinBalanceSection.tsx
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
  suite-native/tokens/src/tokensSelectors.ts
Labels: mobile

#16943 chore(monorepo): unify copy-webpack-plugin default import naming
  packages/connect-examples/electron-renderer-with-assets/webpack/config.dev.js
  packages/connect-examples/electron-renderer-with-assets/webpack/config.prod.js
  packages/connect-explorer/webpack/webextension.webpack.config.ts
  packages/connect-popup/webpack/prod.webpack.config.ts
  packages/connect-webextension/webpack/inline.webpack.config.ts
  packages/suite-build/configs/desktop.webpack.config.ts
  packages/suite-build/configs/web.webpack.config.ts
Labels: low hanging fruit, no-project

#16942 fix(suite-native): suspicious device back button removed
  suite-native/module-onboarding/src/screens/SuspiciousDeviceScreen.tsx
Labels: mobile

#16941 fix(suite-native): fix device onboarding feature flag evaluation
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/device/src/selectors.ts
Labels: mobile, release-native

#16933 feat(suite-native): bump app version to 25.2.2
  suite-native/app/package.json
Labels: mobile

#16883 feat(suite-native): onboarding security check
  suite-common/icons/cryptoAssets/networkIcons/ada_inverse.svg
  suite-common/icons/cryptoAssets/networkIcons/arb_inverse.svg
  suite-common/icons/cryptoAssets/networkIcons/base_inverse.svg
  suite-common/icons/cryptoAssets/networkIcons/sol_inverse.svg
  suite-common/icons/generateIconFont.ts
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.json
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.ttf
  suite-native/atoms/src/AlertBox.tsx
  suite-native/intl/src/en.ts
  suite-native/module-onboarding/package.json
  suite-native/module-onboarding/src/assets/t3b1Seal1.png
  suite-native/module-onboarding/src/assets/t3b1Seal2.png
  suite-native/module-onboarding/src/assets/t3t1Seal.png
  suite-native/module-onboarding/src/components/SecurityCheckStepCard.tsx
  suite-native/module-onboarding/src/components/SecuritySealDescription.tsx
  suite-native/module-onboarding/src/components/SecuritySealImages.tsx
  suite-native/module-onboarding/src/navigation/OnboardingStackNavigator.tsx
  suite-native/module-onboarding/src/screens/SecurityCheckScreen.tsx
  suite-native/module-onboarding/src/screens/UninitializedDeviceLandingScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#16917 chore(connect): enable taproot in connect discovery
  packages/connect/src/api/common/Discovery.ts
Labels: connect

#16950 fix(suite-native): apply blur correctly after Skia update
  suite-native/atoms/src/DiscreetText/DiscreetCanvas.tsx
Labels: bug, mobile, release-native

#16955 fix(suite-native): add missing footer margin to account import summary screen
  suite-native/module-accounts-import/src/components/AccountImportSummaryScreen.tsx
Labels: bug, mobile, UI

#16951 feat(suite-desktop): turn on ASAR integrity check
  packages/suite-desktop/electron-builder-config.js
Labels: no-project

#16953 fix(suite-native): welcome screen image
  suite-native/module-onboarding/src/screens/WelcomeScreen.tsx
Labels: mobile, release-native

#16960 fix(suite-native): handle device authenticity check for expired configs
  suite-native/analytics/src/types.ts
  suite-native/module-device-settings/src/components/DeviceAuthenticityCard.tsx
Labels: bug, mobile, release-native

#16966 fix(suite-native): transactions migrations
  suite-native/state/src/reducers.ts
Labels: mobile, release-native, cherry-pick🍒

#16976 chore(connect): update device authenticity config
  packages/connect/src/data/deviceAuthenticityConfig.ts
Labels: no-project

#16986 feat(suite-native): Mobile Trade: improve Buy section stub
  suite-native/intl/src/en.ts
  suite-native/module-trading/src/components/buy/BuyCard.tsx
  suite-native/module-trading/src/components/buy/ReceiveAccountCryptoBalance.tsx
  suite-native/module-trading/src/components/buy/ReceiveAccountPicker.tsx
  suite-native/module-trading/src/components/buy/__tests__/ReceiveAccountCryptoBalance.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/ReceiveAccountPicker.comp.test.tsx
  suite-native/module-trading/src/components/general/TradingOverviewRow.tsx
Labels: mobile, no-project

#16983 fix(suite): walletconnect sign eip1559 transactions
  suite-common/walletconnect/src/adapters/ethereum.ts
Labels: build-desktop

#17003 fix(suite): fix nightly web tests
  .github/workflows/test-suite-web-nightly.yml
Labels: no-project

#16968 chore(suite-desktop): set node-bridge only for mac and win
  packages/suite-desktop-core/src/modules/bridge.ts
Labels: release

#17015 feat(scripts): add timestamp update to check-connect-data
  scripts/ci/check-connect-data.ts
Labels: no-project

#17011 feat(suite-native): Mobile Trade: Legal notice and safety
  suite-native/intl/src/en.ts
  suite-native/module-trading/src/components/buy/Confirmation.tsx
  suite-native/module-trading/src/components/buy/LegalSheet.tsx
  suite-native/module-trading/src/hooks/__tests__/useBottomSheetControls.test.ts
  suite-native/module-trading/src/hooks/useBottomSheetControls.ts
  suite-native/module-trading/src/hooks/useTradeConfirmationControls.ts
  suite-native/module-trading/src/hooks/useTradeSheetControls.ts
  suite-native/module-trading/src/screens/TradingScreen.tsx
Labels: mobile

#17013 docs(connect-mobile): improve description of deeplinking protocol
  packages/connect-explorer/src/pages/details/deeplinking.mdx
Labels: connect, no-project

#16964 fix(suite-native): return to Onboarding from DeviceCompromisedModal
  suite-native/module-authenticity-checks/src/screens/DeviceCompromisedModalScreen.tsx
Labels: mobile, no-project

#16923 Experiment - mock debounce in send form unit test
  packages/suite/src/hooks/wallet/__tests__/useSendForm.test.tsx
Labels: no-project

#16965 chore(suite-native): refactor navigation route matching
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
Labels: mobile, no-project

#17007 ci(scripts): moving add label to differnt GH request
  scripts/ci/check-connect-data.ts
Labels: no-project

#17033 fix(scripts): handle asych properly in bump version connect
  scripts/ci/connect-bump-versions.ts
Labels: no-project

#17047 chore(connect): update device authenticity config
  packages/connect/src/data/deviceAuthenticityConfig.ts
Labels: no-project

#17027 fix(date-select): close date select after confirming date range or clicking cancel
  packages/components/src/components/Dropdown/Dropdown.tsx
  packages/components/src/components/Popover/Popover.tsx
  packages/suite/src/components/suite/graph/GraphRangeSelector.tsx
Labels: bug

#17009 feat(graph): remove solana from graph events apart of inserted latest value
  suite-common/graph/src/graphDataFetching.ts
Labels: graph, mobile, solana

#17059 fix(suite-native): staking icon size
  suite-native/accounts/src/components/AccountsList/AccountsListStakingItem.tsx
Labels: mobile

#17056 chore(suite-desktop-core): typescriptize electron builder hooks
  packages/suite-desktop-core/eslint.config.mjs
  packages/suite-desktop-core/package.json
  packages/suite-desktop-core/scripts/notarize.ts
  packages/suite-desktop-core/scripts/setElectronFuses.ts
  packages/suite-desktop-core/scripts/sign-windows.ts
  packages/suite-desktop-core/tsconfig.json
  packages/suite-desktop-core/tsconfig.lib.json
  packages/suite-desktop/electron-builder-config.js
Labels: build-desktop, no-project

#17074 ci: bump github/codeql-action to v3
  .github/workflows/check-codeql-analysis.yml
Labels: no-project

#17077 chore(trezor-user-link): stop sending specific version, backend shoul…
  packages/trezor-user-env-link/package.json
  packages/trezor-user-env-link/src/api.ts
  yarn.lock
Labels: no-project

#17083 fix(suite-native): maximum icon enlargement
  suite-native/icons/src/Icon.tsx
Labels: mobile

#17064 Message system - 80 - adjust copy for POL warning banner
  suite-common/message-system/config/config.v1.json
Labels: no-project

#17079 fix(suite-desktop-core): remove obsolete option from notarize call
  packages/suite-desktop-core/scripts/notarize.ts
Labels: no-project

#17065 fix(suite-native): suspicious device screen back navigation
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
Labels: mobile

#17105 docs(suite): don't instruct to build:libs needlessly
  docs/releases/adding-new-firmwares.md
  packages/suite-desktop/README.md
Labels: documentation, no-project

#17081 fix(suite-native): accounts screen loading flash glitch
  packages/suite/src/views/wallet/transactions/CoinjoinSummary/CoinjoinBalanceSection.tsx
  suite-common/wallet-core/src/accounts/accountsReducer.ts
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
  suite-native/tokens/src/tokensSelectors.ts
  suite-native/transactions/src/selectors.ts
Labels: mobile

#17085 chore(suite): skip flaky unit test
  packages/suite/src/hooks/wallet/__fixtures__/useSendForm.ts
  packages/suite/src/hooks/wallet/__tests__/useSendForm.test.tsx
Labels: no-project

#17132 chore(connect-explorer, connect-explorer-theme): update next
  packages/connect-explorer-theme/package.json
  packages/connect-explorer/package.json
  yarn.lock
Labels: dependencies, no-project

#17072 feat(suite-native): add icon to Learn More in FW check settings
  suite-native/module-settings/src/components/TurnOffFirmwareAuthenticityCheckCard.tsx
Labels: mobile, no-project

#17120 feat(suite-native): add trading slice to mobile
  suite-common/trading/src/index.ts
  suite-native/module-trading/src/__tests__/tradingSlice.test.ts
  suite-native/module-trading/src/index.ts
  suite-native/module-trading/src/redux.d.ts
  suite-native/module-trading/src/tradingSlice.ts
  suite-native/state/package.json
  suite-native/state/redux.d.ts
  suite-native/state/src/reducers.ts
  suite-native/state/src/store.ts
  suite-native/state/tsconfig.json
  yarn.lock
Labels: mobile, no-project

#16938 chore(suite-native): slightly refactor native supported networks
  suite-native/config/src/supportedNetworks.ts
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/module-accounts-import/src/components/SelectableNetworkList.tsx
  suite-native/module-accounts-import/src/screens/AccountImportSummaryScreen.tsx
Labels: mobile

#16971 Tenv link default model
  docker/docker-compose.connect-popup-ci.yml
  docker/docker-compose.connect-popup-test.yml
  docker/docker-compose.connect-test.yml
  docker/docker-compose.connect-webextension-test.yml
  docker/docker-compose.suite-ci-pw.yml
  docker/docker-compose.suite-ci.yml
  docker/docker-compose.suite-desktop-ci.yml
  docker/docker-compose.suite-dev.yml
  docker/docker-compose.suite-native-ci.yml
  docker/docker-compose.suite-test.yml
  docker/docker-compose.transport-test-ci.yml
  packages/suite-desktop-core/e2e/tests/onboarding/t1b1/t1b1-create-wallet.test.ts
  packages/suite-desktop-core/e2e/tests/onboarding/t1b1/t1b1-recovery-advanced.test.ts
  packages/suite-desktop-core/e2e/tests/onboarding/t1b1/t1b1-recovery-fail.test.ts
  packages/suite-desktop-core/e2e/tests/onboarding/t1b1/t1b1-recovery-success.test.ts
  packages/suite-desktop-core/e2e/tests/onboarding/t2t1/t2t1-create-wallet.test.ts
  packages/suite-desktop-core/e2e/tests/onboarding/t2t1/t2t1-recovery-fail.test.ts
  packages/suite-desktop-core/e2e/tests/onboarding/t3t1/t3t1-create-wallet.test.ts
Labels: no-project

#17183 fix(suite-native): show testnets during account import only if enabled
  suite-native/module-accounts-import/src/components/SelectableNetworkList.tsx
Labels: mobile

#17119 feat(mobile): prevent 3rd party access our packages
  packages/bundler-security/jest.config.js
  packages/bundler-security/package.json
  packages/bundler-security/src/WebpackSecurityPlugin.ts
  packages/bundler-security/src/constants.js
  packages/bundler-security/src/index.ts
  packages/bundler-security/src/metroSecureResolver.js
  packages/bundler-security/tests/metroSecureResolver.test.ts
  packages/bundler-security/tsconfig.json
  packages/connect-iframe/package.json
  packages/connect-iframe/tsconfig.json
  packages/connect-iframe/webpack/base.webpack.config.ts
  packages/suite-build/configs/base.webpack.config.ts
  packages/suite-build/package.json
  packages/suite-build/tsconfig.json
  scripts/generatePackage.js
  suite-native/app/metro.config.js
  suite-native/app/package.json
  suite-native/app/tsconfig.json
  suite-native/state/tsconfig.json
  yarn.lock
Labels: mobile

#17188 Fix condition for enabling device authenticity check
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/views/settings/SettingsDevice/DeviceAuthenticityOptOut.tsx
Labels: bug

#17201 fix(message-system): fix cta button on pol warning
  suite-common/message-system/config/config.v1.json
Labels: no-project

#17127 fix(connect): ts requires lib ES2022 even the target is ES2022
  packages/connect/tsconfig.lib.json
Labels: no-project

#17217 ci(github): add push branch to intermediery branch creation workflow
  .github/workflows/release-connect-intermediary.yml
Labels: no-project

#17190 feat(staking): added "Stake" buttons to assets and trade table
  packages/suite-analytics/src/types/events.ts
  packages/suite/src/views/dashboard/AssetsView/AssetCard/AssetCard.tsx
  packages/suite/src/views/dashboard/AssetsView/AssetTable/AssetRow.tsx
  packages/suite/src/views/dashboard/AssetsView/AssetsView.tsx
  packages/suite/src/views/dashboard/AssetsView/TradingButton.tsx
  packages/suite/src/views/wallet/transactions/TradeBox/TradeBox.tsx
Labels: staking

#17206 fix(suite): delete obsolete groups tests
  .github/workflows/test-suite-web-nightly.yml
Labels: no-project

#17228 fix(suite-native): my assets selector memo
  suite-native/accounts/src/selectors.ts
Labels: mobile

#17209 docs: more details on Windows signing
  docs/releases/signing-binaries-win.md
Labels: documentation, no-project

#17169 feat(suite-native): persist favourite trade assets
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/TradeableAssetsSheet.tsx
  suite-native/module-trading/src/tradingSlice.ts
  suite-native/state/src/reducers.ts
Labels: mobile

#17234 fix(suite-desktop-core): proper name & place for electron-builder hooks
  packages/suite-desktop-core/package.json
  packages/suite-desktop-core/tsconfig.scripts.json
  packages/suite-desktop/package.json
Labels: no-project

#17269 test(connect-popup): stabilize tests
  .github/workflows/template-connect-popup-test-params.yml
  packages/connect-popup/e2e/support/helpers.ts
  packages/connect-popup/e2e/tests/__fixtures__/methods.ts
  packages/connect-popup/e2e/tests/methods.test.ts
  packages/connect-popup/e2e/tests/passphrase.test.ts
  packages/connect-popup/e2e/tests/permissions.test.ts
  packages/connect-popup/e2e/tests/popup-close.test.ts
  packages/connect-popup/e2e/tests/popup-pages.test.ts
Labels: no-project

#17263 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/ko.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#17252 Add defensive condition to prevent reported crashes during onboarding
  packages/suite/src/components/firmware/FirmwareInitial.tsx
Labels: sentry

#17202 feat(trading): otc market banner
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOfferOTC.tsx
  suite-common/trading/src/invityAPI.ts
  suite-common/trading/src/types.ts
Labels: feature, +Invity, release

#17312 fix(suite): fix broken onboarding links
  packages/suite/src/components/suite/Preloader/Preloader.tsx
  packages/suite/src/support/suite/Redirect.tsx
Labels: no-project
