Repository trezor/trezor-suite, pull requests merged in 2025-05, with the labels that each got.

#18676 chore(suite-native): bump version to 25.5.1
  suite-native/app/package.json
Labels: ci, mobile

#18666 fix(trading): double requesting quotes
  packages/suite/src/hooks/wallet/trading/form/common/useTradingInitializer.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingBuyForm.tsx
  packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts
Labels: bug, +Invity

#18644 fix(suite-native): Device Onboarding: fix pin cancel behaviour
  suite-native/module-device-onboarding/src/screens/CreatePinScreen.tsx
Labels: mobile

#18667 fix(suite-native): Device Onboarding: fix swipeableWalkgrough Screen offset
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/SwipeableWalkthrough.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/SwipeableWalkthroughStep.tsx
  suite-native/module-device-onboarding/src/hooks/useSwipeableWalkthroughStepHeight.ts
Labels: mobile

#18673 feat(suite): always indicate when dust prevention occurs
  packages/suite/src/components/wallet/Fees/CustomFee/CustomFee.tsx
  packages/suite/src/components/wallet/Fees/CustomFee/CustomFeeMisc.tsx
  packages/suite/src/components/wallet/Fees/DustPreventionNotice.tsx
  packages/suite/src/components/wallet/Fees/Fees.tsx
  packages/suite/src/components/wallet/Fees/StandardFee/BitcoinFeeCards.tsx
  packages/suite/src/components/wallet/Fees/StandardFee/StandardFee.tsx
  packages/suite/src/support/messages.ts
Labels: bitcoin

#18680 chore(suite-desktop): rewrite builder hooks to ESM
  packages/suite-desktop-core/package.json
  packages/suite-desktop-core/scripts/notarize.ts
  packages/suite-desktop-core/scripts/setElectronFuses.ts
  packages/suite-desktop-core/scripts/sign-windows.ts
  packages/suite-desktop-core/tsconfig.scripts.json
  packages/suite-desktop/electron-builder-config.js
  packages/suite-desktop/package.json
  yarn.lock
Labels: build-desktop

#18610 trezor bot application rework
  .github/workflows/bot-crowdin-sync.yml
  .github/workflows/bot-rebase.yml
  .github/workflows/check-project-assignment.yml
  .github/workflows/release-connect-bump-versions.yml
  .github/workflows/release-connect-init.yml
  .github/workflows/release-suite-desktop-web-staging.yml
  .github/workflows/suite-native-monthly-version-bump.yml
  .github/workflows/test-suite-desktop-e2e-pr.yml
  .github/workflows/test-suite-native-e2e-android.yml
  .github/workflows/test-suite-web-e2e-pr.yml
  .github/workflows/update-connect-config.yml
Labels: no-project

#18705 Revert "chore: bump nx"
  package.json
  yarn.lock
Labels: ci, no-project

#18669 fix(suite-desktop-core): when Tor initialize fails
  packages/suite-desktop-core/src/modules/tor.ts
Labels: no-project

#18642 feat(suite-native): device onboarding analytics
  suite-native/analytics/src/constants.ts
  suite-native/analytics/src/events.ts
  suite-native/analytics/src/types.ts
  suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx
  suite-native/firmware/src/hooks/useFirmware.tsx
  suite-native/firmware/src/hooks/useFirmwareAnalytics.ts
  suite-native/link/src/components/Link.tsx
  suite-native/module-device-onboarding/atoms.ts
  suite-native/module-device-onboarding/src/components/SecurityCheckStepCard.tsx
  suite-native/module-device-onboarding/src/components/SecuritySealDescription.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep6.tsx
  suite-native/module-device-onboarding/src/screens/ConfirmFirmwareUpdateScreen.tsx
  suite-native/module-device-onboarding/src/screens/CreateOrRecoverCrossroadsScreen.tsx
  suite-native/module-device-onboarding/src/screens/CreatePinScreen.tsx
  suite-native/module-device-onboarding/src/screens/FirmwareInstallationScreen.tsx
  suite-native/module-device-onboarding/src/screens/SecurityCheckScreen.tsx
  suite-native/module-device-onboarding/src/screens/UninitializedDeviceLandingScreen.tsx
  suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx
Labels: mobile

#18697 fix(suite-native): update account picker text for portfolio tracker
  suite-native/intl/src/en.ts
  suite-native/module-trading/src/components/general/AccountSheet/NoAccountsComponent.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/NoAccountsComponent.comp.test.tsx
  suite-native/module-trading/src/screens/__tests__/ReceiveAccountsPickerScreen.comp.test.tsx
Labels: mobile

#18733 fix(suite): handle autostart before quit modal in Electron teardown
  packages/suite-desktop-core/e2e/support/testExtends/suiteBaseFixture.ts
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AutoStartBeforeQuitModal.tsx
Labels: no-project

#18716 fix(suite-desktop-core): connect event was unsubscribed
  packages/suite-desktop-core/src/modules/trezor-connect.ts
Labels: no-project

#18713 connect: discovery chores
  packages/connect/src/api/common/Discovery.ts
Labels: no-project

#18751 chore(suite-data): update tor to 0.4.8.14
  packages/suite-data/files/bin/tor/linux-arm64/tor
  packages/suite-data/files/bin/tor/linux-x64/tor
  packages/suite-data/files/bin/tor/mac-arm64/tor
  packages/suite-data/files/bin/tor/mac-x64/tor
  packages/suite-data/files/bin/tor/update.sh
  packages/suite-data/files/bin/tor/win-x64/tor.exe
Labels: tor

#18414 fix(suite): show device disconnect info in staking modal
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/UnstakeModal/UnstakeEthForm/UnstakeEthForm.tsx
  packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/EthStakingDashboard.tsx
  packages/suite/src/views/wallet/staking/components/SolStakingDashboard/SolStakingDashboard.tsx
Labels: no-project

#18758 fix(connect-popup): ethereumSignTransaction last confirmation step optional in e2e
  packages/connect-popup/e2e/tests/__fixtures__/methods.ts
  packages/connect-popup/e2e/tests/methods.test.ts
Labels: no-project

#18589 refactor(trading): created loadSellInfoThunk
  suite-common/trading/src/thunks/index.ts
  suite-common/trading/src/thunks/sell/__tests__/loadSellInfoThunk.test.ts
  suite-common/trading/src/thunks/sell/loadSellInfoThunk.ts
Labels: +Invity, chore

#18590 refactor(trading): sell handle request
  packages/suite/src/hooks/wallet/trading/form/common/useTradingComposeTransaction.ts
  packages/suite/src/hooks/wallet/trading/form/common/useTradingFormActions.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingSellForm.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingSellFormRedirectValues.tsx
  packages/suite/src/types/trading/tradingForm.ts
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputAccount.tsx
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInput/TradingFormInputFiatCrypto/TradingFormInputFiatCrypto.tsx
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInputs.tsx
  packages/suite/src/views/wallet/trading/common/TradingHeader/TradingHeaderFilter.tsx
  suite-common/trading/src/reducers/__tests__/tradingReducer.test.ts
  suite-common/trading/src/reducers/tradingReducer.ts
  suite-common/trading/src/thunks/index.ts
  suite-common/trading/src/thunks/sell/__tests__/handleSellRequestThunk.test.ts
  suite-common/trading/src/thunks/sell/handleSellRequestThunk.ts
  suite-common/trading/src/types.ts
  suite-common/trading/src/utils.ts
Labels: +Invity, chore

#18722 fix(connect): `BleUnpair` race condition
  packages/connect/src/api/bleUnpair.ts
  packages/connect/src/device/Device.ts
Labels: connect, no-project

#18764 Bump beta version to 25.6.0
  packages/suite/package.json
Labels: deployment

#18763 chore(suite-native): Mobile Trade: mock useMountedRecentlyFlag in tests
  suite-native/module-trading/src/components/buy/BuyForm.tsx
  suite-native/module-trading/src/hooks/__tests__/useMountedRecentlyFlag.test.ts
  suite-native/module-trading/src/hooks/useMountedRecentlyFlag.ts
  suite-native/module-trading/src/jest.setup.tsx
Labels: mobile, no-project

#18772 chore(ci): fix token generation for public repository
  .github/workflows/release-suite-desktop-web-staging.yml
Labels: no-project

#18592 refactor(trading): sell send transaction
  packages/suite/src/support/messages.ts
  suite-common/trading/src/thunks/index.ts
  suite-common/trading/src/thunks/sell/__tests__/sendSellTransactionThunk.test.ts
  suite-common/trading/src/thunks/sell/sendSellTransactionThunk.ts
Labels: +Invity, chore

#18594 refactor(trading): sell select quote
  suite-common/trading/src/thunks/index.ts
  suite-common/trading/src/thunks/sell/__tests__/selectSellQuoteThunk.test.ts
  suite-common/trading/src/thunks/sell/selectSellQuoteThunk.ts
  suite-common/trading/src/types.ts
Labels: +Invity, chore

#18595 refactor(trading): sell confirm trade
  suite-common/trading/src/thunks/index.ts
  suite-common/trading/src/thunks/sell/__tests__/confirmSellTradeThunk.test.ts
  suite-common/trading/src/thunks/sell/confirmSellTradeThunk.ts
Labels: +Invity, chore

#18756 feat(suite-native): Mobile Trade: Error states when api is unreachabl…
  suite-common/trading/src/selectors/__tests__/tradingSelectors.test.ts
  suite-common/trading/src/selectors/tradingSelectors.ts
  suite-common/trading/src/thunks/common/loadInitialDataThunk.ts
  suite-native/app/src/navigation/__tests__/AppTabNavigator.comp.test.tsx
  suite-native/intl/src/en.ts
  suite-native/module-trading/package.json
  suite-native/module-trading/src/components/general/Offline/DeviceOffline.tsx
  suite-native/module-trading/src/components/general/Offline/OfflineCard.tsx
  suite-native/module-trading/src/components/general/Offline/ServerOffline.tsx
  suite-native/module-trading/src/components/general/Offline/__tests__/ServerOffline.comp.test.tsx
  suite-native/module-trading/src/hooks/__tests__/useTradingBuyData.test.tsx
  suite-native/module-trading/src/hooks/useTradingBuyData.ts
  suite-native/module-trading/src/navigation/__tests__/TradingStackNavigator.comp.test.tsx
  suite-native/module-trading/src/screens/TradingScreen.tsx
  suite-native/module-trading/src/screens/__tests__/TradingScreen.comp.test.tsx
  yarn.lock
Labels: mobile

#18769 fix(transport): assign logger to AbstractApiTransport super class
  packages/transport-native-usb/src/nativeUsb.ts
  packages/transport/src/transports/abstractApi.ts
  packages/transport/src/transports/nodeusb.ts
Labels: connect, no-project

#18777 Push LFS objects before pushing to release repo
  scripts/prepare-desktop-release.sh
Labels: no-project

#18514 feat(trading): support ethereum sepolia testnet in trading
  suite-common/wallet-config/src/networksConfig.ts
Labels: READY FOR REVIEW, +Invity

#18765 chore(suite): update eliptic lib in everstake sdk
  package.json
  packages/suite/package.json
  yarn.lock
Labels: no-project

#18804 fix(scripts): prepublish script path
  scripts/prepublish.js
Labels: no-project

#18803 fix(trading): delete best rate quote for swap
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffer.tsx
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffersSwitcher.tsx
Labels: +Invity

#18801 fix(trading): catch json parsing errors
  suite-common/trading/src/__tests__/invityAPI.test.ts
  suite-common/trading/src/invityAPI.ts
Labels: chore

#18816 feat(trading): select Wordwide in Buy/Sell if tor is enabled
  packages/suite/src/hooks/wallet/trading/form/useTradingBuyFormDefaultValues.tsx
  packages/suite/src/hooks/wallet/trading/form/useTradingSellFormDefaultValues.ts
Labels: feature, +Invity

#18809 fix(suite-native): Mobile Trade: display error on providers loading error
  suite-common/trading/src/selectors/__tests__/tradingSelectors.test.ts
  suite-common/trading/src/selectors/tradingSelectors.ts
Labels: mobile

#18826 feat(suite-native): Mobile Trade: Update Bottom sheet headers UI
  suite-native/module-trading/src/components/general/AccountSheet/AccountSheetHeader.tsx
  suite-native/module-trading/src/components/general/SearchableSheetHeader.tsx
  suite-native/module-trading/src/components/general/SheetHeaderTitle.tsx
  suite-native/module-trading/src/components/general/SimpleSheetHeader.tsx
Labels: mobile

#18820 fix(suite-native): Mobile Trade: fix amount inputs validation
  suite-native/module-trading/src/components/buy/CryptoAmountInput.tsx
  suite-native/module-trading/src/components/buy/FiatAmountInput.tsx
  suite-native/module-trading/src/components/general/TradingAmountInput.tsx
  suite-native/module-trading/src/consts.ts
  suite-native/module-trading/src/hooks/__tests__/useQuotes.test.ts
  suite-native/module-trading/src/hooks/__tests__/useTradingBuyForm.test.tsx
  suite-native/module-trading/src/hooks/useQuotes.ts
  suite-native/module-trading/src/hooks/useTradingBuyForm.ts
  suite-native/module-trading/src/utils/__tests__/amountUtils.test.ts
  suite-native/module-trading/src/utils/__tests__/quotesUtils.test.ts
  suite-native/module-trading/src/utils/amountUtils.ts
  suite-native/module-trading/src/utils/buyFormValidationSchema.ts
Labels: mobile

#18823 fix(suite-native): Mobile Trade: Legal BottomSheet scroll
  suite-native/atoms/src/Sheet/BottomSheetModal.tsx
  suite-native/module-trading/src/components/buy/Confirmation.tsx
  suite-native/module-trading/src/components/buy/LegalSheet.tsx
  suite-native/module-trading/src/components/buy/__tests__/LegalSheet.comp.test.tsx
  suite-native/module-trading/src/hooks/useTradingBuyFlow.ts
Labels: mobile

#18684 fix(suite-native): failed device check during onboarding
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/module-authenticity-checks/src/useRenderDeviceCompromisedBanner.ts
Labels: mobile

#18693 fix(suite-native): wallet creation design qa fixes
  suite-native/atoms/src/Accordion/AccordionItem.tsx
  suite-native/atoms/src/Sheet/BottomSheet.tsx
  suite-native/atoms/src/useIllustrationColors.ts
  suite-native/device/src/components/TrezorDeviceSvg.tsx
  suite-native/firmware/package.json
  suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx
  suite-native/firmware/src/components/UpdateProgressIndicator.tsx
  suite-native/module-device-onboarding/src/components/ProtectWalletBackupSvg.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/HoldToConfirmButton.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/SwipeableWalkthroughStep.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupSheet/WalletBackupSheet.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupInstructionCards.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep3.tsx
  suite-native/module-device-onboarding/src/components/WalletCreationHint.tsx
  suite-native/module-device-onboarding/src/screens/WalletCreationScreen.tsx
  yarn.lock
Labels: mobile

#18854 fix(connect): add @trezor/type-utils to dependencies
  packages/blockchain-link-types/package.json
  packages/blockchain-link-types/tsconfig.json
  packages/blockchain-link-types/tsconfig.lib.json
  packages/coinjoin/package.json
  packages/coinjoin/src/client/CoinjoinPrison.ts
  packages/coinjoin/src/client/Status.ts
  packages/coinjoin/tsconfig.json
  packages/connect-popup/package.json
  packages/connect-popup/src/index.tsx
  packages/connect-popup/src/log.tsx
  packages/connect-popup/tsconfig.json
  packages/connect-web/package.json
  packages/connect-web/src/popup/index.ts
  packages/connect-web/tsconfig.json
  packages/connect-web/tsconfig.lib.json
  packages/connect/package.json
  packages/connect/src/backend/BackendManager.ts
  packages/connect/tsconfig.json
  packages/connect/tsconfig.lib.json
  yarn.lock
Labels: no-project

#18858 Add publishing details to @trezor/type-utils
  packages/type-utils/README.md
  packages/type-utils/package.json
Labels: no-project

#18861 chore(connect): enable entropy check for t1b1
  packages/connect/src/data/config.ts
  packages/connect/src/utils/__tests__/deviceFeaturesUtils.test.ts
Labels: cherry-pick🍒

#18852 fix(suite-native): better trade close handling
  suite-native/module-trading/src/screens/TradingWebviewScreen.tsx
  suite-native/module-trading/src/utils/__tests__/tradeUtils.test.ts
  suite-native/module-trading/src/utils/tradeUtils.ts
Labels: mobile

#18868 feat(suite-native): Mobile Trade: hide bottom sheet on back press
  suite-native/module-trading/src/components/buy/LegalSheet.tsx
  suite-native/module-trading/src/hooks/__tests__/useBottomSheetControls.test.ts
  suite-native/module-trading/src/hooks/useBottomSheetBackButtonSubscription.ts
  suite-native/module-trading/src/hooks/useBottomSheetControls.ts
Labels: mobile

#18893 refactor(suite-native): replace useRef with useBottomSheetModal
  suite-native/module-trading/src/components/buy/LegalSheet.tsx
  suite-native/module-trading/src/components/general/TradeDetailSheet/TradeDetailSheet.tsx
Labels: mobile

#18776 feat(suite-native): device backup banners
  packages/suite/src/components/suite/banners/SuiteBanners/SuiteBanners.tsx
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/app/src/BannersRenderer.tsx
  suite-native/app/src/hooks/useGlobalHooks.tsx
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/device/src/components/DeviceDangerBanner.tsx
  suite-native/device/src/components/DeviceDangerBannerExtension.tsx
  suite-native/device/src/deviceAtoms.ts
  suite-native/device/src/deviceThunks.ts
  suite-native/device/src/hooks/useRenderDeviceDangerBanner.ts
  suite-native/device/src/index.ts
  suite-native/intl/src/en.ts
  suite-native/module-authenticity-checks/package.json
  suite-native/module-authenticity-checks/src/DeviceCompromisedBannerAtoms.ts
  suite-native/module-authenticity-checks/src/components/DeviceCompromisedBanner.tsx
  suite-native/module-authenticity-checks/src/index.ts
  suite-native/module-authenticity-checks/src/useRenderDeviceCompromisedBanner.ts
  suite-native/module-authenticity-checks/tsconfig.json
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep5.tsx
  suite-native/module-device-onboarding/src/hooks/useWipeDeviceAlert.tsx
  suite-native/module-device-onboarding/src/index.ts
  suite-native/module-device-onboarding/src/screens/BackupFailedModalScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#18897 chore(ci): fix changed files step for revision check
  .github/workflows/check-code-validation.yml
Labels: no-project

#18901 fix(suite-native): resolve modal closing issue in LegalSheet component
  suite-native/module-trading/src/components/buy/LegalSheet.tsx
Labels: mobile, no-project

#18881 chore(connect): inform only once per 10 seconds about new evm block
  packages/connect/src/backend/Blockchain.ts
Labels: no-project

#18886 fix(nix): update to nixos-unstable to have electron_35
  shell.nix
Labels: no-project

#18915 feat(suite-native): Mobile Trade: Allow buy by default
  suite-native/app/src/navigation/__tests__/AppTabNavigator.comp.test.tsx
  suite-native/feature-flags/jest.config.js
  suite-native/feature-flags/package.json
  suite-native/module-trading/src/screens/__tests__/TradingScreen.comp.test.tsx
  suite-native/module-trading/src/selectors/__tests__/commonSelectors.test.ts
  suite-native/module-trading/src/selectors/commonSelectors.ts
Labels: mobile

#18924 Mobile Trade: make sure non-empty account descriptor is used for invityAPI
  suite-native/module-trading/src/hooks/__tests__/useTradingBuyForm.test.tsx
  suite-native/module-trading/src/hooks/useTradingBuyForm.ts
  suite-native/module-trading/src/utils/__tests__/tradeUtils.test.ts
  suite-native/module-trading/src/utils/tradeUtils.ts
Labels: mobile

#18892 feat(suite-native): add analytics for trading
  suite-native/analytics/package.json
  suite-native/analytics/src/constants.ts
  suite-native/analytics/src/events.ts
  suite-native/analytics/tsconfig.json
  suite-native/app/src/navigation/AppTabNavigator.tsx
  suite-native/module-trading/src/components/buy/BuyForm.tsx
  suite-native/module-trading/src/components/buy/TradingProviderPicker.tsx
  suite-native/module-trading/src/components/general/TradeDetailSheet/TradeDetailHeader.tsx
  suite-native/module-trading/src/components/general/TradeHistory/TradeHistoryListItem.tsx
  suite-native/module-trading/src/hooks/__tests__/useBuyQuotes.test.ts
  suite-native/module-trading/src/hooks/useBuyQuotes.ts
  suite-native/module-trading/src/hooks/useTradingBuyFlow.ts
  suite-native/module-trading/src/hooks/useTradingBuyForm.ts
  suite-native/module-trading/src/hooks/useTradingWatchTrade.ts
  suite-native/module-trading/src/screens/TradingScreen.tsx
  suite-native/module-trading/src/screens/TradingWebviewScreen.tsx
  suite-native/module-trading/src/utils/__tests__/tradeFormUtils.test.ts
  suite-native/module-trading/src/utils/__tests__/tradeUtils.test.ts
  suite-native/module-trading/src/utils/tradeFormUtils.ts
  suite-native/module-trading/src/utils/tradeUtils.ts
  suite-native/navigation/src/navigators.ts
  yarn.lock
Labels: mobile

#18920 chore(suite-desktop): downgrade electron-builder
  packages/connect-examples/electron-main-process/package.json
  packages/connect-examples/electron-renderer-with-popup/package.json
  packages/suite-desktop/package.json
  yarn.lock
Labels: dependencies, build-desktop, no-project

#18934 fix(suite-native): typos in wallet backup translations
  suite-native/intl/src/en.ts
Labels: mobile

#18802 fix(suite-native): fix button overflow on secutiry check screen
  suite-native/module-device-onboarding/src/components/SecurityCheckStepCard.tsx
Labels: mobile

#18933 chore(suite-desktop): correctly log info about legacy bridge
  packages/suite-desktop-core/src/modules/bridge.ts
Labels: no-project

#18936 feat(suite-native): analytics of entereing send/receive flow
  suite-native/accounts/src/components/AccountSelectBottomSheet.tsx
  suite-native/accounts/src/types.ts
  suite-native/analytics/src/constants.ts
  suite-native/analytics/src/events.ts
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
  suite-native/module-send/src/screens/SendAccountsScreen.tsx
  suite-native/receive/src/screens/ReceiveAccountsScreen.tsx
Labels: mobile

#18940 fix(suite-native): add close button to firmware update screen
  suite-native/module-device-settings/src/screens/ConfirmFirmwareUpdateScreen.tsx
Labels: mobile

#18942 Don't emit `CONNECT_UNACQUIRED` after `DISCONNECT`
  packages/connect/src/device/Device.ts
Labels: release

#18909 fix(suite-native): device onboarding ui qa 2
  suite-native/atoms/src/Sheet/BottomSheet.tsx
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/module-device-onboarding/src/components/WalletBackupSheet/WalletBackupCard/CardHeader.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupSheet/WalletBackupCard/WalletBackupCard.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupSheet/WalletBackupSheetFooter.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupInstructionCards.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep3.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep5.tsx
  suite-native/module-device-onboarding/src/screens/CreateOrRecoverCrossroadsScreen.tsx
Labels: mobile

#18900 chore(suite-native): remove device onboarding feature flag
  suite-common/message-system/src/messageSystemTypes.ts
  suite-native/app/.env.development
  suite-native/device/src/selectors.ts
  suite-native/feature-flags/src/__tests__/featureFlagsSlice.test.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  suite-native/module-home/src/screens/HomeScreen/components/__tests__/EmptyHomeRenderer.comp.test.tsx
Labels: mobile

#18946 fix(suite-native): unitialized device connected redirect
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
Labels: mobile, no-project

#18948 chore(suite-native): bump suite-native version to 25.5.2
  suite-native/app/package.json
Labels: mobile, no-project

#18952 chore(suite-native): remove unused stepper
  suite-native/atoms/src/StepsProgressBar.tsx
  suite-native/atoms/src/index.ts
Labels: mobile

#18953 fix(suite-native): wallet backup sheet buton copy
  suite-native/intl/src/en.ts
Labels: mobile

#18950 fix(suite-native): select fresh account memoization issue
  suite-native/accounts/src/selectors.ts
  suite-native/accounts/src/tests/selectors.test.ts
Labels: mobile

#18964 ci: update trezor-user-env to 4ab0279e7ef628d4548a8ecad38fed8130345c63
  .github/workflows/test-trezor-user-env-link-e2e.yml
  docker/docker-compose.connect-popup-ci.yml
  docker/docker-compose.connect-popup-test.yml
  docker/docker-compose.connect-test.yml
  docker/docker-compose.connect-webextension-test.yml
  docker/docker-compose.suite-ci-e2e.yml
  docker/docker-compose.suite-desktop-ci.yml
  docker/docker-compose.suite-dev.yml
  docker/docker-compose.suite-native-ci.yml
  docker/docker-compose.suite-test.yml
  docker/docker-compose.transport-test-ci.yml
Labels: no-project

#18960 fix(suite-native): do not start discovery before device onboarding is finished
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
Labels: mobile, release-native, cherry-pick🍒

#18954 feat:(suite): allow to go back when renaming device label while onboa…
  packages/suite/src/views/onboarding/steps/Final.tsx
Labels: no-project

#18975 fix(suite-native): fix provider consent double appearance
  suite-native/module-trading/src/components/buy/LegalSheet.tsx
Labels: mobile

#18955 fix: remove analytics from suite-common
  suite-common/connect-popup/src/connectPopupThunks.ts
  suite-common/walletconnect/src/walletConnectThunks.ts
Labels: no-project

#18962 chore(trading): fix styling for copy button in transactions
  packages/suite/src/views/wallet/trading/common/TradingTransactionId.tsx
  packages/suite/src/views/wallet/trading/common/TradingTransactions/TradingTransactionExchange.tsx
  packages/suite/src/views/wallet/trading/common/TradingTransactions/TradingTransactionsBuy.tsx
Labels: +Invity, chore

#18990 feat(suite-native): distinguish checks by DeviceCompromisedModal subtitle
  suite-native/intl/src/en.ts
  suite-native/module-authenticity-checks/src/components/DeviceAuthenticityCheckFailModalContent.tsx
  suite-native/module-authenticity-checks/src/components/DeviceCompromisedModalContent.tsx
  suite-native/module-authenticity-checks/src/components/EntropyCheckFailModalContent.tsx
  suite-native/module-authenticity-checks/src/components/FirmwareAuthenticityCheckFailModalContent.tsx
Labels: mobile

#18970 test(suite): change T2B1 to T3B1 to fix e2e
  packages/suite-desktop-core/e2e/support/pageObjects/onboarding/onboardingPage.ts
  packages/suite-desktop-core/e2e/tests/settings/t3b1-device-settings.test.ts
  packages/trezor-user-env-link/src/types.ts
Labels: no-project

#18976 fix(suite-native): better handling of cancellation of device auth check on the device
  suite-native/module-device-onboarding/src/components/DeviceOnboardingScreenWithExitButton.tsx
  suite-native/module-device-onboarding/src/hooks/useExitAlert.ts
  suite-native/module-device-onboarding/src/screens/ConnectAndUnlockDeviceScreen.tsx
  suite-native/module-device-onboarding/src/screens/DeviceAuthenticityScreen.tsx
Labels: mobile

#18985 refactor(trading): adds tradingAccountKey to TradingBuyState
  suite-common/trading/src/reducers/__fixtures__/buyTradingReducer.ts
  suite-common/trading/src/reducers/buyReducer.ts
  suite-common/trading/src/selectors/__tests__/tradingSelectors.test.ts
  suite-common/trading/src/selectors/tradingSelectors.ts
Labels: +Invity, chore

#19009 fix(suite-native): selectDeviceAuthenticity memoization
  suite-common/wallet-core/src/device/deviceReducer.ts
Labels: bug, mobile

#19013 fix(connect-explorer): new connect flow article wording
  packages/connect-explorer/src/pages/guides/new-connect-flow-in-trezor-suite.mdx
Labels: no-project

#19004 feat(suite-native): track buy form parameter changes in analytics
  suite-native/analytics/src/constants.ts
  suite-native/analytics/src/events.ts
  suite-native/module-trading/src/components/buy/CountryOfResidencePicker.tsx
  suite-native/module-trading/src/components/buy/PaymentMethodPicker.tsx
  suite-native/module-trading/src/components/buy/TradingProviderPicker.tsx
  suite-native/module-trading/src/components/general/ProviderSheet/ProvidersSheet.tsx
  suite-native/module-trading/src/hooks/useTradingBuyForm.ts
Labels: mobile

#19019 fix(suite-native): Mobile Trade: fix tests
  suite-native/analytics/src/jest.setup.ts
  suite-native/app/e2e/pageObjects/tradingBuyActions.ts
  suite-native/module-trading/src/components/general/AccountList/__tests__/AccountListItem.comp.test.tsx
  suite-native/module-trading/src/screens/__tests__/TradingHistoryScreen.comp.test.tsx
  suite-native/module-trading/src/screens/__tests__/TradingWebViewScreen.comp.test.tsx
Labels: mobile, no-project

#19026 ci(github): lets not use nx cloud cache in CI
  .github/workflows/check-code-validation.yml
Labels: no-project

#19033 ci(nx): fix caching issue by specifying build outputs
  .github/workflows/check-code-validation.yml
  packages/firmware-release-config/package.json
Labels: ci, no-project

#19039 firmwareHash undefined check
  packages/suite/src/utils/suite/storage.ts
Labels: no-project

#18988 fix(suite-native): mock analytics in unit tests
  jest.config.native.js
  suite-native/analytics/src/jest.setup.ts
Labels: mobile, no-project

#19055 fix(trading): eth priority fees
  suite-common/trading/src/thunks/common/recomposeAndSignTxThunk.ts
Labels: bug, +Invity

#19059 fix(suite-native): reanimated shadow warning
  suite-native/atoms/src/Card/Card.tsx
Labels: mobile

#19030 feat(suite-native): implement reset method for native USB device
  packages/react-native-usb/android/src/main/java/io/trezor/rnusb/ReactNativeUsbModule.kt
  packages/react-native-usb/src/ReactNativeUsb.types.ts
  packages/react-native-usb/src/ReactNativeUsbModule.ts
  packages/react-native-usb/src/index.ts
Labels: mobile

#19080 fix(suite-native): use correct size for the wipe device button
  suite-native/module-device-settings/src/components/WipeDeviceCard.tsx
Labels: mobile

#19002 test(firmware-release-config): change test file name
  packages/firmware-release-config/src/__tests__/firmwareReleaseConfig.test.ts
Labels: no-project

#19079 fix(trading): do not show offers for invalid form state
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOfferItem.tsx
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormOffersSwitcher.tsx
Labels: bug, +Invity

#19081 fix(suite-native): fix styles of Card with top Alert
  suite-native/atoms/src/Card/Card.tsx
  suite-native/atoms/src/Card/__tests__/Card.comp.test.tsx
Labels: mobile

#19114 fix(suite-native): Mobile Trade: display empty balance with unit
  suite-native/module-trading/src/components/buy/BuyReceiveAccountCryptoBalance.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyReceiveAccountCryptoBalance.comp.test.tsx
Labels: mobile

#19106 Correctly return `used` status for device
  packages/connect/src/device/Device.ts
Labels: no-project

#19070 fix(suite-desktop-core): restart on linux on update with autostart
  packages/suite-desktop-core/src/modules/auto-updater.ts
Labels: build-desktop, no-project

#19097 test(suite-native): Device Onboarding: Create Wallet e2e
  suite-native/app/.env.test
  suite-native/app/e2e/pageObjects/deviceOnboardingActions.ts
  suite-native/app/e2e/tests/deviceOnboarding.test.ts
  suite-native/app/e2e/utils.ts
  suite-native/firmware/src/components/ConfirmFirmwareUpdateScreenFooter.tsx
  suite-native/module-device-onboarding/src/components/CreateWalletLoader.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/HoldToConfirmButton.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/SwipeableWalkthroughStep.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupRecap/WalletBackupRecapStep1.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupRecap/WalletBackupRecapStep2.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupRecap/WalletBackupRecapStep3.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupSheet/WalletBackupCard/WalletBackupCard.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep1.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep2.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep3.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep4.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep5.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep6.tsx
  suite-native/module-device-onboarding/src/screens/CreateOrRecoverCrossroadsScreen.tsx
  suite-native/module-device-onboarding/src/screens/DeviceAuthenticitySuccessScreen.tsx
  suite-native/module-device-onboarding/src/screens/SuspiciousDeviceScreen.tsx
  suite-native/module-device-onboarding/src/screens/UninitializedDeviceLandingScreen.tsx
Labels: mobile

#19073 Feat: protocol-thp encode/decode
  packages/protocol/src/protocol-thp/ThpState.ts
  packages/protocol/src/protocol-thp/constants.ts
  packages/protocol/src/protocol-thp/crypto/crc32.ts
  packages/protocol/src/protocol-thp/decode.ts
  packages/protocol/src/protocol-thp/encode.ts
  packages/protocol/src/protocol-thp/index.ts
  packages/protocol/src/protocol-thp/messages/messageTypes.ts
  packages/protocol/src/protocol-thp/messages/protobufTypes.ts
  packages/protocol/src/protocol-thp/utils.ts
  packages/protocol/tests/protocol-thp/crc32.test.ts
  packages/protocol/tests/protocol-thp/protocol-thp.test.ts
  packages/protocol/tests/protocol-thp/utils.test.ts
Labels: connect, no-project, cherry-pick🍒

#19037 Add flake development environment
  .gitignore
  flake.lock
  flake.nix
Labels: no-project

#19156 Discovery connect followup
  packages/connect/src/api/discoverAccounts.ts
  packages/connect/src/types/api/discoverAccounts.ts
Labels: no-project

#19184 Mobile Trade: Clear receive account after wallet change
  suite-native/module-trading/src/__tests__/tradingSlice.test.ts
  suite-native/module-trading/src/hooks/buy/__tests__/useBuyForm.test.tsx
  suite-native/module-trading/src/hooks/buy/useBuyForm.ts
  suite-native/module-trading/src/tradingSlice.ts
Labels: mobile

#19198 Mobile Trade: fix displaying of Error badge when using sats
  suite-native/module-trading/src/components/buy/BuyFormFieldErrorBadge.tsx
  suite-native/module-trading/src/hooks/buy/__tests__/useBuyForm.test.tsx
  suite-native/module-trading/src/hooks/buy/useBuyForm.ts
  suite-native/module-trading/src/hooks/general/__tests__/useConvertFormValueToBaseUnit.test.ts
  suite-native/module-trading/src/hooks/general/useConvertFormValueToBaseUnit.ts
  suite-native/module-trading/src/types.ts
  suite-native/module-trading/src/utils/buy/buyFormValidationSchema.ts
Labels: mobile

#19190 Mobile Trade: Clear amount limits on asset / fiat currency change
  suite-native/module-trading/src/__tests__/tradingSlice.test.ts
  suite-native/module-trading/src/hooks/buy/__tests__/useBuyForm.test.tsx
  suite-native/module-trading/src/hooks/buy/__tests__/useBuyQuotes.test.ts
  suite-native/module-trading/src/hooks/buy/useBuyForm.ts
  suite-native/module-trading/src/tradingSlice.ts
Labels: mobile

#19199 feat(suite-native) hide zero balance tokens
  suite-native/accounts/src/selectors.ts
  suite-native/accounts/src/tests/selectors.test.ts
  suite-native/module-accounts-import/src/components/AccountImportConfirmFormScreen.tsx
Labels: mobile

#19191 chore(suite-native): bump app version to 25.5.3
  suite-native/app/package.json
Labels: mobile, no-project

#19208 chore(suite-native): Mobile Trade: refactor types
  suite-native/module-trading/src/__fixtures__/tradeableAssets.ts
  suite-native/module-trading/src/components/buy/BuyCountryOfResidencePicker.tsx
  suite-native/module-trading/src/components/buy/BuyFormFieldErrorBadge.tsx
  suite-native/module-trading/src/components/buy/BuyTradeableAssetPicker.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyAlert.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyAmountInput.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyAssetNetworkInfo.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyCryptoAmountInput.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyFiatAmountInput.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyForm.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyFormFieldErrorBadge.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyPaymentMethodPicker.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyProviderPicker.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyReceiveAccountCryptoBalance.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyReceiveAccountPicker.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyTradeableAssetPicker.comp.test.tsx
  suite-native/module-trading/src/components/general/AccountList/AccountList.tsx
  suite-native/module-trading/src/components/general/AccountList/AccountListAddressItem.tsx
  suite-native/module-trading/src/components/general/AccountList/AccountListBaseItem.tsx
  suite-native/module-trading/src/components/general/AccountList/AccountListItem.tsx
  suite-native/module-trading/src/components/general/AccountList/__tests__/AccountList.comp.test.tsx
  suite-native/module-trading/src/components/general/AccountList/__tests__/AccountListAddressItem.test.tsx
  suite-native/module-trading/src/components/general/AccountList/__tests__/AccountListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/CountrySheet/CountrySheet.tsx
  suite-native/module-trading/src/components/general/FiatCurrencySheet/FiatCurrencySheet.tsx
  suite-native/module-trading/src/components/general/SelectTradeableAssetButton.tsx
  suite-native/module-trading/src/components/general/TradeableAssetButton.tsx
  suite-native/module-trading/src/components/general/TradeableAssetSheet/TradeableAssetListItem.tsx
  suite-native/module-trading/src/components/general/TradeableAssetSheet/TradeableAssetSheet.tsx
  suite-native/module-trading/src/components/general/TradeableAssetSheet/__tests__/TradeableAssetSheet.comp.test.tsx
  suite-native/module-trading/src/hooks/buy/__tests__/useBuyFlow.test.ts
  suite-native/module-trading/src/hooks/buy/__tests__/useBuyForm.test.tsx
  suite-native/module-trading/src/hooks/buy/__tests__/useBuyQuotes.test.ts
  suite-native/module-trading/src/hooks/buy/useBuyFlow.ts
  suite-native/module-trading/src/hooks/buy/useBuyForm.ts
  suite-native/module-trading/src/hooks/buy/useBuyFormContext.ts
  suite-native/module-trading/src/hooks/buy/useBuyQuotes.ts
  suite-native/module-trading/src/hooks/general/__tests__/useFavouriteAssetsSectionList.test.tsx
  suite-native/module-trading/src/hooks/general/__tests__/useTradeableAssetsFilteredData.test.ts
  suite-native/module-trading/src/hooks/general/useFavouriteAssetsSectionList.ts
  suite-native/module-trading/src/hooks/general/useFiatCurrencyFilteredData.ts
  suite-native/module-trading/src/hooks/general/useReceiveAccountsListData.ts
  suite-native/module-trading/src/hooks/general/useSheetControls.ts
  suite-native/module-trading/src/hooks/general/useTradeableAssetsFilteredData.ts
  suite-native/module-trading/src/index.ts
  suite-native/module-trading/src/selectors/__tests__/favouritesSelectors.test.ts
  suite-native/module-trading/src/selectors/buySelectors.ts
  suite-native/module-trading/src/selectors/favouritesSelectors.ts
  suite-native/module-trading/src/tradingSlice.ts
  suite-native/module-trading/src/types.ts
  suite-native/module-trading/src/types/buy.ts
  suite-native/module-trading/src/types/general.ts
  suite-native/module-trading/src/utils/buy/buyFormValidationSchema.ts
  suite-native/module-trading/src/utils/general/__tests__/quotesUtils.test.ts
  suite-native/module-trading/src/utils/general/__tests__/tradeableAssetUtils.test.ts
  suite-native/module-trading/src/utils/general/quotesUtils.ts
  suite-native/module-trading/src/utils/general/tradeableAssetUtils.ts
Labels: mobile, no-project

#19139 fix(suite-native): card stepper item enhancement
  suite-native/atoms/src/CardStepper/CardStepperItem.tsx
Labels: mobile
