Repository trezor/trezor-suite, pull requests merged in 2025-04, with the labels that each got.

#18004 Don't expect BIP-380 from older fw
  packages/connect/e2e/__fixtures__/getPublicKey.ts
Labels: no-project

#18015 chore(suite-native): bump version to 25.4.1
  suite-native/app/package.json
Labels: ci, mobile

#17958 fix(message-system): remove unsued gitlab key
  suite-common/message-system/scripts/sign-config.ts
Labels: no-project

#18019 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
Labels: translations

#18018 chore(transport-bridge): remove build:bin; it was unused anyway
  packages/transport-bridge/package.json
  scripts/list-outdated-dependencies/connect-dependencies.txt
  yarn.lock
Labels: no-project

#17942 Reinit sessions background when initing webusb transport
  packages/transport/src/transports/abstractApi.ts
Labels: no-project

#18026 chore(suite-desktop): make node-bridge rollout conditions equal for a…
  packages/suite-desktop-core/src/modules/bridge.ts
Labels: low hanging fruit, Bridge -> nodeUSB

#18029 fix(suite-native): ios sharp build
  .github/workflows/release-suite-native-develop.yml
  .github/workflows/release-suite-native-production.yml
Labels: mobile, no-project

#18030 chore(connect-web): min required npm package version is 9.1.5
  packages/connect/src/utils/versionCheck.ts
Labels: no-project

#18038 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/lol.json
  packages/suite/src/support/messages.ts
Labels: translations

#17989 chore(suite): remove EIP1559 from debug
  suite-common/wallet-core/src/fees/feesThunks.ts
Labels: release

#18032 fix(wallet-constants): change solana epoch time back to 3 days
  suite-common/wallet-constants/src/solanaStakingConstants.ts
  suite-native/staking/src/__tests__/solanaStakingSelectors.test.ts
Labels: release

#18040 Crowdin translations update
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/zh.json
Labels: translations

#18046 fix(suite-native): REVERT ios sharp build
  .github/workflows/release-suite-native-develop.yml
  .github/workflows/release-suite-native-production.yml
Labels: mobile

#17567 chore(deps): update usb dependency from 2.14.0 to 2.15.0
  packages/suite-desktop/package.json
  packages/transport-bridge/package.json
  packages/transport-bridge/pkg.config.json
  packages/transport-test/package.json
  packages/transport/package.json
  yarn.lock
Labels: Bridge -> nodeUSB

#18045 docs(auth-server): clarify setup of testing credentials
  packages/auth-server/README.md
Labels: documentation, no-project

#18050 fix(repo): fix yarn.lock
  yarn.lock
Labels: no-project

#18042 Bump beta version to 25.5.0
  packages/suite/package.json
Labels: deployment

#18028 chore(suite-build): update vite
  packages/suite-build/package.json
  yarn.lock
Labels: no-project

#18074 fix(suite): on desktop, fix that the top title link in the guide was …
  packages/suite/src/components/guide/GuideViewWrapper.tsx
Labels: bug

#18014 feat(suite-native): implement trade assets filtering by search and network tabs
  suite-native/module-trading/src/__fixtures__/tradeableAssets.ts
  suite-native/module-trading/src/components/buy/BuyTradeableAssetsSheet.tsx
  suite-native/module-trading/src/components/general/SearchInputWithCancel.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/TradeableAssetsFilterTabs.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/TradeableAssetsSheet.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/TradeableAssetsSheetHeader.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/__tests__/TradeableAssetsFilterTabs.comp.test.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/__tests__/TradeableAssetsSheet.comp.test.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/__tests__/TradeableAssetsSheetHeader.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/SearchInputWithCancel.comp.test.tsx
  suite-native/module-trading/src/hooks/__tests__/useTradeableAssetsFilteredData.test.ts
  suite-native/module-trading/src/hooks/useBuyTradeableAssetsFilteredData.ts
  suite-native/module-trading/src/hooks/useTradeableAssetsFilteredData.ts
Labels: mobile

#18095 Remove unused analytics script
  scripts/githubAnalytics.ts
  scripts/list-outdated-dependencies/common-dependencies.txt
  scripts/list-outdated-dependencies/connect-dependencies.txt
  scripts/list-outdated-dependencies/qa-dependencies.txt
  scripts/package.json
  yarn.lock
Labels: dependencies, no-project

#17757 refactor(trading): move exchange reducer to suite-common
  packages/suite/src/hooks/wallet/trading/form/useTradingBuyForm.tsx
  suite-common/trading/src/constants.ts
  suite-common/trading/src/reducers/__fixtures__/buyTradingReducer.ts
  suite-common/trading/src/reducers/__fixtures__/exchangeTradingReducer.ts
  suite-common/trading/src/reducers/__fixtures__/tradingReducer.ts
  suite-common/trading/src/reducers/__tests__/exchangeReducer.test.ts
  suite-common/trading/src/reducers/buyReducer.ts
  suite-common/trading/src/reducers/exchangeReducer.ts
  suite-common/trading/src/reducers/tradingReducer.ts
  suite-common/trading/src/thunks/buy/__tests__/loadInfoThunk.test.ts
  suite-common/trading/src/types.ts
  suite-common/trading/src/utils/buy/buyUtils.ts
Labels: +Invity, chore

#18084 chore(suite-native): Mobile Trade: less intrusive animations in lists
  suite-native/module-trading/src/components/general/CountrySheet/CountryListItem.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/TradeableAssetsSheet.tsx
  suite-native/module-trading/src/hooks/useSectionList.tsx
Labels: mobile, no-project

#18059 GitBook revision update
  packages/suite-data/src/guide/constants.ts
Labels: guide

#17780 refactor(trading): create exchange selectors
  suite-common/trading/src/selectors/__tests__/tradingSelectors.test.ts
  suite-common/trading/src/selectors/tradingSelectors.ts
Labels: +Invity, chore

#17944 feat(suite-native): onboarding wallet backup tutorial
  suite-common/icons/generateIconFont.ts
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.json
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.ttf
  suite-native/atoms/src/IconListItem.tsx
  suite-native/atoms/src/useIllustrationColors.ts
  suite-native/device/src/components/TrezorDeviceSvg.tsx
  suite-native/device/src/index.ts
  suite-native/intl/src/en.ts
  suite-native/module-device-onboarding/package.json
  suite-native/module-device-onboarding/src/assets/RecoveryCardSvg.tsx
  suite-native/module-device-onboarding/src/assets/risk-cards-lottie.json
  suite-native/module-device-onboarding/src/components/BackupRiskCardsAnimation.tsx
  suite-native/module-device-onboarding/src/components/CreateWalletLoader.tsx
  suite-native/module-device-onboarding/src/components/ProtectWalletBackupSvg.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/SwipeableWalkthrough.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/SwipeableWalkthroughScreenHeader.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/SwipeableWalkthroughStep.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/SwipeableWalkthroughStepHeader.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep1.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep2.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep3.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep4.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep5.tsx
  suite-native/module-device-onboarding/src/constants.ts
  suite-native/module-device-onboarding/src/navigation/DeviceOnboardingStackNavigator.tsx
  suite-native/module-device-onboarding/src/screens/CreateWalletLoadingScreen.tsx
  suite-native/module-device-onboarding/src/screens/WalletBackupTutorialScreen.tsx
  suite-native/module-device-onboarding/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#18116 feat(suite-desktop): add trezor-connect incoming messages validation
  packages/connect-web/src/impl/core-in-suite-desktop.ts
  packages/suite-desktop-core/src/libs/connect-ws.ts
Labels: no-project

#18119 fix: prevent requiring unknown module error on suite-native
  packages/suite-build/package.json
  yarn.lock
Labels: mobile, no-project

#18134 fix(message-system): disable hash check other-error for 25.3 only on web
  suite-common/message-system/config/config.v1.json
Labels: message-system, no-project

#18093 fix(suite): detect feeInfo changes based on blockHeight to fix outdated fee calculation
  packages/suite/src/hooks/wallet/form/useCompose.ts
  packages/suite/src/hooks/wallet/form/useStakeCompose.ts
  packages/suite/src/hooks/wallet/trading/form/common/useTradingComposeTransaction.ts
  packages/suite/src/hooks/wallet/useSendForm.ts
  packages/suite/src/hooks/wallet/useSendFormCompose.ts
  packages/suite/src/hooks/wallet/useUnstakeEthForm.ts
  packages/suite/src/types/wallet/sendForm.ts
Labels: release

#18128 chore(suite): connect popup redux actions cleanup
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ConnectPopupModal.tsx
  suite-common/connect-popup/src/connectPopupActions.ts
  suite-common/connect-popup/src/connectPopupMiddleware.ts
  suite-common/connect-popup/src/connectPopupReducer.ts
  suite-common/connect-popup/src/connectPopupThunks.ts
  suite-common/connect-popup/src/connectPopupTypes.ts
  suite-common/connect-popup/src/methodHooks/addressConfirmation.ts
  suite-common/connect-popup/src/methodHooks/index.ts
  suite-native/module-connect-popup/src/screens/ConnectPopupScreen.tsx
Labels: no-project

#18138 chore(connect-ui): implement new async getOsVersion in analytics
  packages/connect-ui/src/utils/analytics.ts
Labels: data, no-project

#18151 feat(suite): hash check failure UI tweaks
  packages/suite/src/components/suite/SecurityCheck/DeviceCompromised.tsx
  packages/suite/src/components/suite/SecurityCheck/SecurityCheckFail.tsx
  packages/suite/src/components/suite/banners/SuiteBanners/FirmwareAuthenticityCheckBanner.tsx
  packages/suite/src/support/messages.ts
Labels: no-project

#18073 feat(trading): support ethereum holesky testnet in trading
  suite-common/wallet-config/src/networksConfig.ts
Labels: +Invity

#18158 chore(suite-native): changed btc to sats conversion
  suite-native/module-trading/src/hooks/useTradingBuyForm.ts
Labels: mobile

#18145 fix(suite-native): disable RTL support
  suite-native/app/src/App.tsx
  suite-native/app/src/rtl.ts
Labels: mobile

#17926 docs(e2e): clarify Playwright setup docs on Linux
  docs/tests/e2e-playwright-suite.md
Labels: documentation, no-project

#18058 chore(connect-examples): remove electron-renderer-with-assets example
  packages/connect-examples/README.md
  packages/connect-examples/electron-renderer-with-assets/.gitignore
  packages/connect-examples/electron-renderer-with-assets/README.md
  packages/connect-examples/electron-renderer-with-assets/eslint.config.mjs
  packages/connect-examples/electron-renderer-with-assets/package.json
  packages/connect-examples/electron-renderer-with-assets/src/electron.js
  packages/connect-examples/electron-renderer-with-assets/src/index.html
  packages/connect-examples/electron-renderer-with-assets/src/renderer.js
  packages/connect-examples/electron-renderer-with-assets/tsconfig.json
  packages/connect-examples/electron-renderer-with-assets/webpack/config.dev.js
  packages/connect-examples/electron-renderer-with-assets/webpack/config.prod.js
  packages/connect-examples/electron-renderer-with-assets/webpack/iframe.html
  scripts/list-outdated-dependencies/connect-dependencies.txt
  yarn.lock
Labels: no-project

#17896 fix(suite-native): report potential errors from connectInit
  suite-native/app/src/initActions.ts
Labels: mobile

#17797 feat(suite-desktop): open bluetooth permissions settings
  packages/suite-desktop-api/src/api.ts
  packages/suite-desktop-core/src/modules/system-settings.ts
Labels: no-project

#18160 Default fees used fix - #18159 alternative
  packages/suite-desktop-core/e2e/tests/trading/sell-bitcoin.test.ts
  packages/suite/src/hooks/wallet/form/useCompose.ts
Labels: release

#18189 fix(suite-native): fix Requiring unknown module undefined after wrong yarn.lock merge
  yarn.lock
Labels: dependencies, mobile, no-project

#18187 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#18196 Desktop ci build flag
  .github/workflows/build-desktop-apps.yml
Labels: no-project

#18201 fix(ci): worflow_dispatch inputs correctly wrapped in inputs keyword
  .github/workflows/build-desktop-apps.yml
Labels: no-project

#17878 refactor(trading): move exchange selecting quote
  packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts
  suite-common/trading/src/reducers/exchangeReducer.ts
  suite-common/trading/src/thunks/exchange/__tests__/selectQuoteThunk.test.ts
  suite-common/trading/src/thunks/exchange/selectQuoteThunk.ts
  suite-common/trading/src/thunks/index.ts
Labels: +Invity, chore

#17906 refactor(trading): move sign data and confirm
  suite-common/trading/src/__fixtures__/utils.ts
  suite-common/trading/src/__tests__/utils.test.ts
  suite-common/trading/src/thunks/exchange/__tests__/signDataAndConfirmThunk.test.ts
  suite-common/trading/src/thunks/exchange/signDataAndConfirmThunk.ts
  suite-common/trading/src/thunks/index.ts
Labels: +Invity, chore

#18210 fix(suite): wrong origin in connect popup
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ConnectPopupModal.tsx
Labels: no-project

#18211 chore(suite-native): bump suite-native version to 25.4.2
  suite-native/app/package.json
Labels: no-project

#18208 fix(suite): DeviceUsedElsewhere with BT off
  packages/suite/src/components/suite/PrerequisitesGuide/DeviceUsedElsewhere.tsx
  packages/suite/src/support/messages.ts
Labels: no-project

#18217 fix(connect-explorer): change deprecated icons
  packages/connect-explorer/src/pages/changelog.mdx
  packages/connect-explorer/src/pages/index.mdx
Labels: no-project

#18228 Icon with percentage - visual tweak
  suite-native/icons/src/CryptoIconWithPercentage.tsx
Labels: mobile

#18234 Improved `BaseProcess` error handling
  packages/suite-desktop-core/src/libs/processes/BaseProcess.ts
Labels: no-project

#18215 feat(suite-native): display date and time based on localization
  suite-common/formatters/src/formatters/prepareDateFormatter.ts
  suite-common/formatters/src/formatters/prepareDateTimeFormatter.ts
Labels: mobile

#18244 Bump vite and koa to resolve dependabot issues
  packages/suite-build/package.json
  yarn.lock
Labels: dependencies, no-project

#18254 chore(node-utils): move findProcessFromIncomingPort to node-utils
  packages/node-utils/src/findProcessFromIncomingPort.ts
  packages/node-utils/src/index.ts
  packages/suite-desktop-core/src/libs/connect-ws.ts
Labels: no-project

#18223 feat(websocket-client): autospoof Origin header in node.js
  packages/blockchain-link/src/workers/blockbook/websocket.ts
  packages/blockchain-link/src/workers/blockfrost/websocket.ts
  packages/coinjoin/tests/tools/benchmark-test.ts
  packages/websocket-client/src/client.ts
Labels: no-project

#18198 feature flags dusting
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/MetadataProviderModal/MetadataProviderModal.tsx
  suite-common/suite-config/src/features.ts
Labels: no-project

#18258 chore(security): fix prototype polluting
  suite-common/token-definitions/src/tokenDefinitionsUtils.ts
Labels: code, chore

#18214 feat(transport-bluetooth): add TrezorBluetooth client
  packages/transport-bluetooth/package.json
  packages/transport-bluetooth/src/client/trezor-bluetooth.ts
  packages/transport-bluetooth/src/client/types.ts
  packages/transport-bluetooth/src/index.ts
  packages/transport-bluetooth/tsconfig.json
  yarn.lock
Labels: no-project, cherry-pick🍒

#18260 Chore/optimize regex
  packages/styles/src/utils.ts
Labels: code, no-project

#18140 feat(suite-native): wallet backup instructions step
  suite-common/icons/generateIconFont.ts
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.json
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.ttf
  suite-native/intl/src/en.ts
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/HoldToConfirmButton.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/SwipeableWalkthroughStep.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupInstructionCards.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep6.tsx
  suite-native/module-device-onboarding/src/constants.ts
  suite-native/module-device-onboarding/src/navigation/DeviceOnboardingStackNavigator.tsx
  suite-native/module-device-onboarding/src/screens/WalletBackupTutorialScreen.tsx
  suite-native/module-device-onboarding/src/screens/WalletCreationScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
Labels: mobile

#18286 chore(suite-native): Mobile Trade: Memoize BuyForm
  suite-native/module-trading/src/components/buy/BuyCard.tsx
  suite-native/module-trading/src/components/buy/BuyForm.tsx
Labels: mobile, no-project

#18227 fix(transport): readMessageBuffer.cancleRead
  packages/transport/src/api/udp.ts
  packages/transport/src/utils/readMessageBuffer.ts
  packages/transport/tests/readMessageBuffer.test.ts
Labels: connect, no-project

#18285 chore(message-system): change experiment test to be deterministic
  suite-common/message-system/src/__tests__/experimentUtils.test.ts
Labels: message-system, chore, no-project

#18305 chore: add no-project label to crowdin sync
  .github/workflows/bot-crowdin-sync.yml
Labels: ci

#18048 refactor(trading): recompose and sign thunk
  packages/suite/src/middlewares/wallet/__tests__/tradingMiddleware.test.ts
  packages/suite/src/support/messages.ts
  packages/suite/src/utils/wallet/trading/__tests__/exchangeUtils.test.ts
  suite-common/trading/src/selectors/__tests__/tradingSelectors.test.ts
  suite-common/trading/src/selectors/tradingSelectors.ts
  suite-common/trading/src/thunks/common/__tests__/recomposeAndSignTxThunk.test.ts
  suite-common/trading/src/thunks/common/recomposeAndSignTxThunk.ts
  suite-common/trading/src/thunks/index.ts
Labels: +Invity, chore

#18287 feat(suite-native): Device onboarding: Recovery
  packages/urls/src/urls.ts
  suite-common/icons/assets/trezorBackup.svg
  suite-common/icons/generateIconFont.ts
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.json
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.ttf
  suite-native/atoms/src/IconListItem.tsx
  suite-native/device/src/hooks/useDetectDeviceError.tsx
  suite-native/intl/src/en.ts
  suite-native/module-device-onboarding/src/navigation/DeviceOnboardingStackNavigator.tsx
  suite-native/module-device-onboarding/src/screens/CreateOrRecoverCrossroadsScreen.tsx
  suite-native/module-device-onboarding/src/screens/RecoveryScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
Labels: mobile

#18318 fix(connect-web): remove unwanted timeout in core-in-desktop call
  packages/connect-web/src/impl/core-in-suite-desktop.ts
Labels: no-project

#18321 docs(suite-native): add android emulator troubleshooting hint
  suite-native/app/README.md
Labels: mobile, documentation, no-project

#18082 refactor(trading): send dex transaction
  packages/suite/src/support/messages.ts
  suite-common/trading/src/thunks/exchange/__tests__/sendDexTransactionThunk.test.ts
  suite-common/trading/src/thunks/exchange/sendDexTransactionThunk.ts
  suite-common/trading/src/thunks/index.ts
Labels: +Invity, chore

#18098 refactor(trading): move send transaction
  suite-common/trading/src/thunks/common/recomposeAndSignTxThunk.ts
  suite-common/trading/src/thunks/exchange/__tests__/sendTransactionThunk.test.ts
  suite-common/trading/src/thunks/exchange/sendDexTransactionThunk.ts
  suite-common/trading/src/thunks/exchange/sendTransactionThunk.ts
  suite-common/trading/src/thunks/index.ts
  suite-common/trading/src/types.ts
Labels: +Invity, chore

#18133 refactor(trading): exchange load info thunk
  suite-common/trading/src/reducers/__fixtures__/exchangeTradingReducer.ts
  suite-common/trading/src/reducers/exchangeReducer.ts
  suite-common/trading/src/thunks/exchange/__tests__/loadInfoThunk.test.ts
  suite-common/trading/src/thunks/exchange/__tests__/selectQuoteThunk.test.ts
  suite-common/trading/src/thunks/exchange/loadInfoThunk.ts
  suite-common/trading/src/thunks/index.ts
  suite-common/trading/src/utils/exchange/__fixtures__/exchangeUtils.ts
Labels: +Invity, chore

#18331 fix(suite-native): correct trade assets filter deselect
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/TradeableAssetsFilterTabs.tsx
Labels: mobile

#18179 refactor(trading): watch trade
  packages/suite/src/hooks/wallet/trading/useTradingWatchTrade.ts
  suite-common/trading/src/thunks/common/__tests__/watchTradeThunk.test.ts
  suite-common/trading/src/thunks/common/watchTradeThunk.ts
  suite-common/trading/src/thunks/index.ts
Labels: +Invity, chore

#18346 test(suite-desktop): update connect desktop assertion
  packages/suite-desktop-core/e2e/tests/trezor-connect/error.test.ts
Labels: no-project

#18299 feat(suite-desktop): add AssetsFilterPlugin webpack plugin
  packages/suite-build/configs/desktop.webpack.config.ts
  packages/suite-build/plugins/assets-filter-plugin.ts
Labels: no-project

#18366 feat(suite-native): add new app icons
  suite-native/app/app.config.ts
  suite-native/app/assets/production/appIcon.png
Labels: cherry-pick🍒

#18302 fix(suite-native): Alert Sheet fix
  suite-native/alerts/package.json
  suite-native/alerts/src/components/AlertSheet.tsx
  suite-native/alerts/tsconfig.json
  yarn.lock
Labels: mobile

#18369 ci: update trezor-user-env to b3473dd9dff4064c3e08db4b78a9dd4467a77eab
  .github/workflows/test-trezor-user-env-link-e2e.yml
  docker/docker-compose.connect-popup-ci.yml
  docker/docker-compose.connect-popup-test.yml
  docker/docker-compose.connect-test.yml
  docker/docker-compose.connect-webextension-test.yml
  docker/docker-compose.suite-ci-e2e.yml
  docker/docker-compose.suite-desktop-ci.yml
  docker/docker-compose.suite-dev.yml
  docker/docker-compose.suite-native-ci.yml
  docker/docker-compose.suite-test.yml
  docker/docker-compose.transport-test-ci.yml
Labels: no-project

#18367 feat(suite-native): basic trade provider picker
  suite-common/trading/src/selectors/__tests__/tradingSelectors.test.ts
  suite-common/trading/src/selectors/tradingSelectors.ts
  suite-common/trading/src/types.ts
  suite-native/intl/src/en.ts
  suite-native/module-trading/src/__fixtures__/invityProvider.json
  suite-native/module-trading/src/__fixtures__/providers.ts
  suite-native/module-trading/src/__fixtures__/quotes.json
  suite-native/module-trading/src/__fixtures__/tradingState.ts
  suite-native/module-trading/src/components/buy/Confirmation.tsx
  suite-native/module-trading/src/components/buy/LegalSheet.tsx
  suite-native/module-trading/src/components/buy/TradingProviderPicker.tsx
  suite-native/module-trading/src/components/buy/__tests__/Confirmation.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/LegalSheet.comp.test.tsx
  suite-native/module-trading/src/components/general/ProviderSheet/ProviderListItem.tsx
  suite-native/module-trading/src/components/general/ProviderSheet/ProvidersSheet.tsx
  suite-native/module-trading/src/components/general/ProviderSheet/__tests__/ProviderListItem.comp.test.tsx
  suite-native/module-trading/src/hooks/__tests__/useTradingBuyFlow.test.ts
  suite-native/module-trading/src/hooks/__tests__/useTradingBuyForm.test.tsx
  suite-native/module-trading/src/hooks/useTradingBuyFlow.ts
  suite-native/module-trading/src/hooks/useTradingBuyForm.ts
  suite-native/module-trading/src/types.ts
Labels: mobile

#18166 refactor(trading): connect exchange to the new reducer
  packages/suite/jest.config.js
  packages/suite/src/actions/wallet/__tests__/tradingExchangeActions.test.ts
  packages/suite/src/actions/wallet/constants/index.ts
  packages/suite/src/actions/wallet/constants/tradingExchangeConstants.ts
  packages/suite/src/actions/wallet/trading/__fixtures__/tradingCommonActions/verifyAddress.ts
  packages/suite/src/actions/wallet/trading/__tests__/tradingCommonActions.test.ts
  packages/suite/src/actions/wallet/trading/tradingCommonActions.ts
  packages/suite/src/actions/wallet/tradingExchangeActions.ts
  packages/suite/src/hooks/wallet/trading/form/common/useTradingAccountKey.ts
  packages/suite/src/hooks/wallet/trading/form/common/useTradingBuyHandleChange.ts
  packages/suite/src/hooks/wallet/trading/form/common/useTradingComposeTransaction.ts
  packages/suite/src/hooks/wallet/trading/form/common/useTradingExchangeHandleChange.ts
  packages/suite/src/hooks/wallet/trading/form/common/useTradingExchangeQuotesFilter.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingBuyForm.tsx
  packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingExchangeWatchSendApproval.ts
  packages/suite/src/hooks/wallet/trading/useTradingDetail.ts
  packages/suite/src/hooks/wallet/trading/useTradingWatchTrade.ts
  packages/suite/src/hooks/wallet/useStakeEthForm.ts
  packages/suite/src/hooks/wallet/useTradingRecomposeAndSign.ts
  packages/suite/src/hooks/wallet/useTradingRedirect.ts
  packages/suite/src/middlewares/wallet/__tests__/tradingMiddleware.test.ts
  packages/suite/src/middlewares/wallet/tradingMiddleware.ts
  packages/suite/src/reducers/wallet/__tests__/tradingReducer.test.ts
  packages/suite/src/reducers/wallet/tradingReducer.ts
  packages/suite/src/types/trading/trading.ts
  packages/suite/src/types/trading/tradingForm.ts
  packages/suite/src/types/wallet/index.ts
  packages/suite/src/utils/wallet/trading/__tests__/exchangeUtils.test.ts
  packages/suite/src/views/wallet/trading/common/TradingForm/TradingFormInputs.tsx
  packages/suite/src/views/wallet/trading/common/TradingHeader/TradingExchangeHeaderSummary.tsx
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchange.tsx
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendApproval.tsx
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingOfferExchange/TradingOfferExchangeSendSwap.tsx
  packages/suite/src/views/wallet/trading/common/TradingSelectedOffer/TradingVerify/TradingVerify.tsx
  packages/suite/src/views/wallet/trading/common/TradingTransactions/TradingTransactionExchange.tsx
  packages/suite/src/views/wallet/trading/common/TradingTransactions/TradingTransactionsList.tsx
  suite-common/trading/src/__fixtures__/utils.ts
  suite-common/trading/src/hooks/useTradingInfo.ts
  suite-common/trading/src/index.ts
  suite-common/trading/src/reducers/tradingReducer.ts
  suite-common/trading/src/selectors/__tests__/tradingSelectors.test.ts
  suite-common/trading/src/selectors/tradingSelectors.ts
  suite-common/trading/src/thunks/common/__tests__/loadInitialDataThunk.test.ts
  suite-common/trading/src/thunks/common/__tests__/verifyAddressThunk.test.ts
  suite-common/trading/src/thunks/common/loadInitialDataThunk.ts
  suite-common/trading/src/thunks/common/recomposeAndSignTxThunk.ts
  suite-common/trading/src/thunks/common/verifyAddressThunk.ts
  suite-common/trading/src/thunks/common/watchTradeThunk.ts
  suite-common/trading/src/thunks/exchange/__tests__/sendTransactionThunk.test.ts
  suite-common/trading/src/thunks/exchange/loadInfoThunk.ts
  suite-common/trading/src/thunks/exchange/selectQuoteThunk.ts
  suite-common/trading/src/thunks/exchange/sendTransactionThunk.ts
  suite-common/trading/src/thunks/exchange/signDataAndConfirmThunk.ts
  suite-common/trading/src/types.ts
  suite-common/trading/src/utils/exchange/__tests__/exchangeUtils.test.ts
  suite-common/trading/src/utils/exchange/exchangeUtils.ts
Labels: +Invity, chore

#18410 chore(connect): update device authenticity config
  packages/connect/src/data/deviceAuthenticityConfig.ts
Labels: no-project

#18423 fix(suite-native): Device Setting: return fw button
  suite-native/module-device-settings/src/components/DeviceFirmwareCard.tsx
Labels: mobile, release-native, cherry-pick🍒

#18443 fix(suite-data): correctly detect mobile chrome
  packages/suite-data/src/browser-detection/index.ts
Labels: no-project

#18421 chore(suite-native): Mobile Trade: refactor BuyForm to use quote directly
  suite-common/trading/src/selectors/__tests__/tradingSelectors.test.ts
  suite-common/trading/src/selectors/tradingSelectors.ts
  suite-native/module-trading/src/__fixtures__/quotes.json
  suite-native/module-trading/src/components/buy/Confirmation.tsx
  suite-native/module-trading/src/components/buy/PaymentMethodPicker.tsx
  suite-native/module-trading/src/components/buy/TradingProviderPicker.tsx
  suite-native/module-trading/src/components/buy/__tests__/TradingProviderPicker.comp.test.tsx
  suite-native/module-trading/src/components/general/PaymentMethodsSheet/PaymentMethodListItem.tsx
  suite-native/module-trading/src/components/general/PaymentMethodsSheet/PaymentMethodsSheet.tsx
  suite-native/module-trading/src/components/general/PaymentMethodsSheet/__tests__/PaymentMethodListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/ProviderSheet/ProviderListItem.tsx
  suite-native/module-trading/src/components/general/ProviderSheet/ProvidersSheet.tsx
  suite-native/module-trading/src/components/general/ProviderSheet/__tests__/ProviderListItem.comp.test.tsx
  suite-native/module-trading/src/hooks/__tests__/useTradingBuyFlow.test.ts
  suite-native/module-trading/src/hooks/__tests__/useTradingBuyForm.test.tsx
  suite-native/module-trading/src/hooks/useTradingBuyFlow.ts
  suite-native/module-trading/src/hooks/useTradingBuyForm.ts
  suite-native/module-trading/src/selectors/__tests__/buySelectors.test.ts
  suite-native/module-trading/src/selectors/buySelectors.ts
  suite-native/module-trading/src/types.ts
  suite-native/module-trading/src/utils/__tests__/quotesUtils.test.ts
  suite-native/module-trading/src/utils/quotesUtils.ts
Labels: mobile, no-project

#18458 fix(scripts): t3w1 empty config to avoid error
  scripts/ci/check-connect-data.ts
Labels: no-project

#18460 test(suite-desktop): split connect-ws.test file per connect method
  packages/suite-desktop-core/e2e/tests/trezor-connect/getAddress.test.ts
  packages/suite-desktop-core/e2e/tests/trezor-connect/signMessage.test.ts
Labels: no-project

#18464 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations, no-project

#18350 feat(suite-native): Device Onboarding: Wallet Backup Recap
  suite-common/icons/generateIconFont.ts
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.json
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.ttf
  suite-native/atoms/src/OrderedListIcon.tsx
  suite-native/helpers/package.json
  suite-native/helpers/src/hooks/useIsMultiline.tsx
  suite-native/helpers/src/index.ts
  suite-native/intl/src/en.ts
  suite-native/module-device-onboarding/package.json
  suite-native/module-device-onboarding/src/components/DeviceOnboardingScreenWithExitButton.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/HoldToConfirmButton.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/SwipeableWalkthrough.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/SwipeableWalkthroughScreenHeader.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/SwipeableWalkthroughStep.tsx
  suite-native/module-device-onboarding/src/components/SwipeableWalkthrough/SwipeableWalkthroughStepHeader.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupRecap/Underline.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupRecap/WalletBackupRecapBackButton.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupRecap/WalletBackupRecapListItem.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupRecap/WalletBackupRecapStep1.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupRecap/WalletBackupRecapStep2.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupRecap/WalletBackupRecapStep3.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupRecap/WalletBackupRecapStep4.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupRecap/WalletBackupRecapStepContent.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupRecap/presets.ts
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep.tsx
  suite-native/module-device-onboarding/src/hooks/useExitAlert.ts
  suite-native/module-device-onboarding/src/navigation/DeviceOnboardingStackNavigator.tsx
  suite-native/module-device-onboarding/src/screens/WalletBackupRecapScreen.tsx
  suite-native/module-device-onboarding/src/screens/WalletBackupTutorialScreen.tsx
  suite-native/module-device-onboarding/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#18329 feat(suite-native): Device onboarding: Create Pin
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/device/src/hooks/usePinAction.tsx
  suite-native/device/src/index.ts
  suite-native/intl/src/en.ts
  suite-native/module-authorize-device/src/index.ts
  suite-native/module-device-onboarding/src/navigation/DeviceOnboardingStackNavigator.tsx
  suite-native/module-device-onboarding/src/screens/CreatePinScreen.tsx
  suite-native/module-device-settings/package.json
  suite-native/module-device-settings/src/navigation/DevicePinProtectionStackNavigator.tsx
  suite-native/module-device-settings/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#18470 fix: add typecheck for translations, fix mismatch
  packages/suite/src/support/messages.ts
  packages/suite/src/support/messagesTypeCheck.ts
  packages/suite/src/views/wallet/staking/components/StakingDashboard/components/EmptyStakingCard.tsx
Labels: translations, no-project

#18477 chore: add permission for fetching oidc token
  .github/workflows/release-suite-native-production.yml
Labels: ci, no-project

#18429 fix(trading): stuck watch trade
  packages/suite/src/hooks/wallet/trading/useTradingWatchTrade.ts
  suite-common/trading/src/thunks/common/watchTradeThunk.ts
Labels: bug, +Invity

#18368 ci: remove release coins icons workflow
  .github/workflows/release-suite-coin-icons.yml
Labels: no-project

#18503 chore(connect): update device authenticity config
  packages/connect/src/data/deviceAuthenticityConfig.ts
Labels: no-project

#18484 feat(suite-native): skip device tutorial action
  suite-native/atoms/src/Button/Button.tsx
  suite-native/device/src/components/ContinueOnTrezorScreenContent.tsx
  suite-native/intl/src/en.ts
  suite-native/module-device-onboarding/src/screens/DeviceTutorialScreen.tsx
Labels: mobile

#18511 fix(device-manager): fix DeviceItem key to prevent two children with the same key
  suite-native/device-manager/src/components/DeviceList.tsx
Labels: mobile

#18520 feat(suite): fix CSV import for testnets
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ImportTransactionModal/useExampleCSV.tsx
  packages/suite/src/hooks/wallet/useSendFormImport.ts
Labels: no-project

#18530 test(suite): add unit test for isStepCategoryUsed
  packages/suite/src/utils/onboarding/__tests__/steps.test.ts
  packages/suite/src/utils/onboarding/steps.ts
Labels: no-project

#18488 feat(transport): add `getMessages` method
  packages/transport/src/transports/abstract.ts
Labels: no-project, cherry-pick🍒

#18512 chore(protobuf): minor changes in build scripts
  packages/protobuf/README.md
  packages/protobuf/scripts/protobuf-definitions.ts
  packages/protobuf/scripts/protobuf-patches/index.ts
  packages/protobuf/scripts/protobuf-types.ts
Labels: connect, no-project, cherry-pick🍒

#18533 ci: exclude .md from triggering actions
  .github/workflows/build-desktop-apps.yml
  .github/workflows/build-suite-native-preview.yml
  .github/workflows/build-suite-web.yml
  .github/workflows/release-suite-native-develop.yml
  .github/workflows/test-suite-desktop-e2e-pr.yml
  .github/workflows/test-suite-native-e2e-android.yml
  .github/workflows/test-suite-web-e2e-pr.yml
Labels: ci, no-project

#18493 chore(suite-native): specify EXPO env to fix EAS calls in androidAPK job
  .github/workflows/release-suite-native-production.yml
Labels: ci, no-project

#18556 chore(connect-web): min required npm package version is 9.2.1
  packages/connect/src/utils/versionCheck.ts
Labels: no-project

#18537 fix(suite-common): fix selectAnyAccountIsStakingActive memoization
  suite-common/wallet-core/src/transactions/transactionsReducer.ts
Labels: code

#18455 Closing Keyboard on showSheet
  suite-native/module-trading/src/hooks/__tests__/useBottomSheetControls.test.ts
  suite-native/module-trading/src/hooks/useBottomSheetControls.ts
Labels: mobile

#18565 fix(scripts): version-bump-prompt should be in root package.json
  package.json
  scripts/package.json
  yarn.lock
Labels: no-project

#18542 fix(transport): in webusb and node-bridge handle session null correctly
  packages/transport/src/sessions/background.ts
  packages/transport/tests/sessions.test.ts
Labels: no-project

#18578 chore(suite-native): fix missing act in quotesUtils test
  suite-native/module-trading/src/utils/__tests__/quotesUtils.test.ts
Labels: mobile, no-project

#18552 fix(suite-native): Testing: replace toBeDefined with toBeTruthy in component tests
  suite-native/accounts/src/components/__tests__/AccountLabelFieldHint.comp.test.tsx
  suite-native/app/src/navigation/__tests__/AppTabNavigator.comp.test.tsx
  suite-native/atoms/src/Card/__tests__/Card.comp.test.tsx
  suite-native/atoms/src/__tests__/PriceChangeBadge.comp.test.tsx
  suite-native/icons/src/tests/CryptoIconWithNetwork.comp.test.tsx
  suite-native/message-system/src/components/__tests__/ContextMessage.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyForm.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyFormFieldErrorBadge.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/Confirmation.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/CountryOfResidencePicker.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/CryptoAmountInput.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/FiatAmountInput.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/FiatCurrencyPicker.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/LegalSheet.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/PaymentMethodPicker.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/ReceiveAccountPicker.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/TradingProviderPicker.comp.test.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/AccountListAddressItem.test.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/AccountListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/AccountsListFooter.comp.test.tsx
  suite-native/module-trading/src/components/general/AccountSheet/__tests__/NoAccountsComponent.comp.test.tsx
  suite-native/module-trading/src/components/general/CountrySheet/__tests__/CountryListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/FiatCurrencySheet/__tests__/FiatCurrencyListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/PaymentMethodsSheet/__tests__/PaymentMethodListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/ProviderSheet/__tests__/ProviderListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/__tests__/FavouriteIcon.comp.test.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/__tests__/TradeableAssetListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/__tests__/TradeableAssetsFilterTabs.comp.test.tsx
  suite-native/module-trading/src/components/general/TradeableAssetsSheet/__tests__/TradeableAssetsSheetHeader.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/AccountAddress.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/NetworkSymbolExtendedFormatter.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/SearchInputWithCancel.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/SimpleSheetHeader.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/TradeableAssetButton.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/TradingAlert.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/TradingEmptyComponent.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/TradingOverviewRow.comp.test.tsx
  suite-native/module-trading/src/hooks/__tests__/useTradeableAssetsFilteredData.test.ts
  suite-native/module-trading/src/navigation/__tests__/TradingStackNavigator.comp.test.tsx
  suite-native/module-trading/src/screens/__tests__/TradeWebviewScreen.comp.test.tsx
Labels: mobile, no-project

#18583 test(suite-desktop): extend connect popup tests; add getAccountInfo t…
  packages/suite-desktop-core/e2e/support/pageObjects/connectPermissionsModal.ts
  packages/suite-desktop-core/e2e/tests/trezor-connect/getAccountInfo.test.ts
  packages/suite/src/components/suite/modals/ReduxModal/DeviceConfirmationModal/SelectAccountModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ConnectPermissionsModal.tsx
Labels: no-project

#18531 chore(connect): update device authenticity config
  packages/connect/src/data/deviceAuthenticityConfig.ts
Labels: no-project

#18614 chore(connect): ethereumSignMessage - catch errors in payload to prec…
  packages/connect/src/api/ethereum/api/ethereumSignTransaction.ts
Labels: no-project

#18612 Chore: cleanup dependency lists
  packages/auth-server/package.json
  packages/suite-build/package.json
  packages/suite/package.json
  packages/utxo-lib/package.json
  scripts/list-outdated-dependencies/engagement-dependencies.txt
  scripts/list-outdated-dependencies/foundation-dependencies.txt
  scripts/list-outdated-dependencies/trends-dependencies.txt
  scripts/package.json
  yarn.lock
Labels: no-project

#18517 fix(trading): max balance
  packages/suite/package.json
  packages/suite/src/hooks/wallet/trading/form/useTradingSellForm.ts
  suite-common/trading/package.json
  suite-common/trading/src/thunks/exchange/sendTransactionThunk.ts
  yarn.lock
Labels: bug, +Invity

#18541 chore(suite): ignore non-serializable fields in serializableCheck
  packages/suite/src/reducers/store.ts
Labels: code, no-project

#18648 fix(suite-native): prevent entering onboarding without feature flag turned on
  suite-native/module-home/src/screens/HomeScreen/components/EmptyHomeRenderer.tsx
Labels: release-native

#18651 fix(suite-native): account picker text alignment
  suite-native/module-trading/src/components/general/AccountSheet/AccountListBaseItem.tsx
Labels: mobile

#18653 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations, no-project

#18657 fix(suite-native): e2e detox path
  .github/workflows/test-suite-native-e2e-android.yml
  suite-native/app/package.json
Labels: mobile

#18655 chore(suite-native): Introduce EmptyHomeRenderer tests
  suite-native/module-home/jest.config.js
  suite-native/module-home/package.json
  suite-native/module-home/src/screens/HomeScreen/components/__tests__/EmptyHomeRenderer.comp.test.tsx
Labels: mobile, no-project

#18649 chore(suite-native): bump app version to 25.4.3
  suite-native/app/package.json
Labels: mobile

#18665 chore(suite): finish typecheck of translations
  packages/suite/src/support/defineMessagesWithTypeCheck.ts
  packages/suite/src/support/messagesTypeCheck.ts
Labels: no-project

#18547 fix(suite-desktop): url decoding before sanitization
  packages/node-utils/src/http.ts
  packages/node-utils/src/tests/http.test.ts
Labels: bug
