Repository trezor/trezor-suite, pull requests merged in 2025-07, with the labels that each got.

#19843 fix(trading): persistent sell fees
  packages/suite/src/hooks/wallet/trading/form/useTradingSellFormRedirectValues.ts
  packages/suite/src/utils/wallet/trading/__tests__/exchangeUtils.test.ts
  packages/suite/src/utils/wallet/trading/__tests__/sellUtils.test.ts
  packages/suite/src/utils/wallet/trading/exchangeUtils.ts
  packages/suite/src/utils/wallet/trading/sellUtils.ts
Labels: bug, +Invity

#19867 fix(trading): sell & exchange redirect on confirm page
  packages/suite/src/hooks/wallet/trading/form/common/useTradingFormActions.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingExchangeForm.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingSellForm.ts
  packages/suite/src/types/trading/trading.ts
  packages/suite/src/types/trading/tradingForm.ts
Labels: bug, +Invity

#19870 Add release notes for 25.7.x release
  packages/suite-desktop/releaseNotes/release-notes.md
Labels: READY FOR REVIEW

#19824 feat(suite): implement trade feedback form
  packages/suite-desktop-core/e2e/support/pageObjects/guidePanel.ts
  packages/suite-desktop-core/e2e/tests/suite/bug-report-form.test.ts
  packages/suite/package.json
  packages/suite/src/actions/suite/guideActions.ts
  packages/suite/src/components/guide/Feedback.tsx
  packages/suite/src/components/suite/EmojiRatingSelector.tsx
  packages/suite/src/components/suite/Experiment/ExperimentWrapper.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailBuy/TradingDetailBuy.tsx
  packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx
  packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailFeedback.tsx
  packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailSell/TradingDetailSell.tsx
  packages/suite/tsconfig.json
  suite-common/feedback/jest.config.js
  suite-common/feedback/package.json
  suite-common/feedback/src/constants.ts
  suite-common/feedback/src/feedbackActions.ts
  suite-common/feedback/src/feedbackUtils.ts
  suite-common/feedback/src/index.ts
  suite-common/feedback/src/types.ts
  suite-common/feedback/tests/feedbackUtils.test.ts
  suite-common/feedback/tsconfig.json
  suite-common/message-system/src/messageSystemSelectors.ts
  suite-common/message-system/src/messageSystemTypes.ts
  suite-common/message-system/src/useExperiment.ts
  suite-common/suite-types/package.json
  suite-common/suite-types/src/guide.ts
  suite-common/suite-types/tsconfig.json
  yarn.lock
Labels: release

#19155 fix(trading): fix link to Back to Account from transaction detail
  packages/suite/src/hooks/wallet/trading/useTradingWatchTrade.ts
  packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailExchange/TradingDetailExchange.tsx
  packages/suite/src/views/wallet/trading/common/TradingDetail/TradingDetailSell/TradingDetailSell.tsx
Labels: bug, +Invity

#19819 ci: remove suite coverageThreshold
  packages/suite/jest.config.js
Labels: ci, tech, no-project

#19885 fix(suite-native): fix switch atom border style
  suite-native/atoms/src/Switch.tsx
Labels: low hanging fruit, mobile, UI, no-project

#19887 fix(ci): build windows app with BT binary
  .github/workflows/build-desktop-apps.yml
Labels: no-project

#19911 fix(suite): solana token discovery error
  packages/blockchain-link/src/workers/solana/index.ts
Labels: build-desktop

#19909 fix(suite): race condition crashing Advanced Fee tab
  packages/suite/src/components/wallet/Fees/Fees.tsx
Labels: no-project

#19662 feat(trading): update amount for paymentRequest and tx preview modal
  suite-common/trading/src/thunks/common/__tests__/createPaymentRequestsThunk.test.ts
  suite-common/trading/src/thunks/common/__tests__/recomposeAndSignTxThunk.test.ts
  suite-common/trading/src/thunks/common/createPaymentRequestsThunk.ts
  suite-common/trading/src/thunks/common/recomposeAndSignTxThunk.ts
Labels: feature, +Invity

#19925 chore(suite): remove systeminformation lib
  packages/suite-desktop-core/package.json
  packages/suite-desktop-core/src/app.ts
  packages/suite-desktop-core/src/libs/info.ts
  packages/suite-desktop-core/src/libs/logger.ts
  packages/suite-desktop-core/webpack/core.webpack.config.ts
  scripts/list-outdated-dependencies/foundation-dependencies.txt
  yarn.lock
Labels: dependencies

#19893 chore(suite-native): bump target android sdk to 35
  suite-native/app/plugins/minSdkProjectGradlePatch.js
Labels: mobile, no-project

#19908 chore(suite): remove unused bridge-dev-restart notification
  packages/suite/src/components/suite/notifications/NotificationRenderer/NotificationRenderer.tsx
  packages/suite/src/support/messages.ts
  suite-common/toast-notifications/src/types.ts
Labels: no-project

#19935 feat(suite-native): report skips of onboarding analytics
  suite-common/analytics/src/events/suite-native/types.ts
  suite-native/module-device-onboarding/src/hooks/useReportOnboardingSuccessAnalytics.ts
  suite-native/module-device-onboarding/src/screens/CreatePinScreen.tsx
Labels: mobile

#19920 chore: add new iconset
  suite-common/icons/assets/shieldWater.svg
  suite-common/icons/assets/shieldWaterFilled.svg
  suite-common/icons/assets/trezorAluminiumBody.svg
  suite-common/icons/assets/trezorAluminiumBodyFilled.svg
  suite-common/icons/assets/trezorBody.svg
  suite-common/icons/assets/trezorBodyFilled.svg
  suite-common/icons/assets/trezorSafe5.svg
  suite-common/icons/assets/trezorSafe5Filled.svg
  suite-common/icons/assets/trezorSafe7.svg
  suite-common/icons/assets/trezorSafe7Filled.svg
  suite-common/icons/src/icons.ts
Labels: mobile

#19975 chore(message-system): Trading not available in GB on iOS for 25.6.1 and newer
  suite-common/message-system/config/config.v1.json
Labels: message-system

#19973 chore(suite-native): add e2e for wipe device
  suite-native/app/e2e/pageObjects/deviceSettingsActions.ts
  suite-native/app/e2e/tests/deviceSettings.test.ts
  suite-native/atoms/src/CardStepper/CardStepperItem.tsx
  suite-native/atoms/src/TitleHeader/TitleHeader.tsx
  suite-native/module-device-settings/src/components/WipeDeviceCard.tsx
  suite-native/module-home/src/screens/HomeScreen/components/UninitializedConnectedDeviceState.tsx
Labels: mobile

#19979 fix(suite-native): run messages validation after country code is saved
  suite-native/message-system/src/messageSystemMiddleware.ts
Labels: mobile, no-project

#19982 fix(e2e): fix typo in manual test template
  packages/suite-desktop-core/e2e/tests/manual/firmware/bootloader.test.ts
Labels: no-project

#19968 Show error for not enough gas coin while sending token
  suite-native/module-send/src/screens/SendOutputsScreen.tsx
  suite-native/module-send/src/sendOutputsFormSchema.ts
Labels: mobile

#19717 feat(suite-native): keep screen awake while interacting with device
  suite-native/device-mutex/package.json
  suite-native/device-mutex/src/requestDeviceAccess.ts
  suite-native/device/src/deviceThunks.ts
  suite-native/module-device-onboarding/src/screens/DeviceTutorialScreen.tsx
  suite-native/module-device-onboarding/src/screens/WalletCreationScreen.tsx
  yarn.lock
Labels: mobile

#20017 fix(suite-native): validate address for contract address on insert for ETH
  suite-native/module-send/src/hooks/useAddressValidationAlerts/useAddressValidationAlerts.ts
Labels: send, mobile, no-project

#20032 fix(common): added redux.d.ts types
  suite-common/message-system/redux.d.ts
Labels: no-project

#20016 feat(suite-native): enable stellar
  suite-native/discovery/src/discoverySelectors.ts
  suite-native/feature-flags/src/__tests__/featureFlagsSlice.test.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
Labels: mobile, no-project, stellar

#20038 chore(suite-native): skip check backup test
  suite-native/app/e2e/tests/deviceSettings.test.ts
Labels: no-project

#19882 feat(transport): send message progress
  packages/connect/src/api/firmware/uploadFirmware.ts
  packages/transport/src/constants.ts
  packages/transport/src/transports/abstract.ts
  packages/transport/src/transports/abstractApi.ts
Labels: connect, no-project

#20009 refactor: from regular to universal firmware type
  packages/connect/src/device/Device.ts
  packages/device-utils/src/firmwareUtils.ts
  packages/device-utils/src/types.ts
  packages/suite-desktop-core/src/modules/firmware.ts
  packages/suite/src/actions/firmware/__fixtures__/firmwareActions.ts
  packages/suite/src/components/firmware/FirmwareInitial.tsx
  packages/suite/src/config/onboarding/steps.ts
  packages/suite/src/storage/migrations/index.ts
  packages/suite/src/utils/firmware/index.ts
  packages/suite/src/utils/onboarding/__tests__/steps.test.ts
  suite-common/firmware/src/firmwareThunks.ts
  suite-common/firmware/src/hooks/useFirmwareInstallation.ts
  suite-common/message-system/schema/config.schema.v1.json
  suite-common/message-system/src/__fixtures__/messageSystemUtils.ts
  suite-common/suite-types/src/messageSystem.ts
  suite-common/test-utils/src/mocks.ts
  suite-native/module-trading/src/components/buy/__tests__/BuyTradeableAssetPicker.comp.test.tsx
  suite-native/module-trading/src/components/exchange/receive/__tests__/ExchangeTradeableAssetPicker.comp.test.tsx
Labels: no-project

#20077 chore(suite-native): touchable opacity shadow
  suite-native/atoms/src/Card/CompactCardWithIconLayout.tsx
Labels: mobile

#20088 Display message about Base and BNB networks sync issues
  suite-common/message-system/config/config.v1.json
Labels: message-system

#20049 fix(transport-bridge): error propagation
  packages/transport/src/api/abstract.ts
  packages/transport/src/api/usb.ts
  packages/transport/src/utils/bridgeApiCall.ts
  packages/transport/tests/apiUsb.test.ts
Labels: no-project, cherry-pick🍒

#19992 chore: remove gitlab mentions
  docker/docker-connect-test.sh
  docs/features/message-system.md
  docs/tests/e2e-connect-popup.md
  docs/tests/e2e-playwright-suite.md
  packages/connect-popup/e2e/tests/__fixtures__/methods.ts
  packages/connect/e2e/README.md
Labels: no-project

#20042 Remove `bchaddrjs` dependency
  packages/utxo-lib/package.json
  packages/utxo-lib/src/bchUtils.ts
  packages/utxo-lib/src/bs58check.ts
  packages/utxo-lib/src/types/cashaddrjs.d.ts
  packages/utxo-lib/tests/bchUtils.test.ts
  scripts/list-outdated-dependencies/foundation-dependencies.txt
  scripts/list-outdated-dependencies/trends-dependencies.txt
  yarn.lock
Labels: dependencies

#20151 fix(suite): use domain chainId in eip712 confirmation modal
  packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/SignMessageModal.tsx
Labels: release, cherry-pick🍒

#20133 fix/native/enable utxo selection for multiple accounts
  suite-native/intl/src/en.ts
  suite-native/module-send/src/atoms/coinControlAtoms.ts
  suite-native/module-send/src/components/CoinControl/SendUtxoScreenHeader.tsx
  suite-native/module-send/src/components/CoinControl/SwitchCoinControlButton.tsx
  suite-native/module-send/src/components/CoinControl/__tests__/SendUtxosScreenHeader.comp.test.tsx
  suite-native/module-send/src/components/OutputsReviewFooter.tsx
  suite-native/module-send/src/components/SendMaxButton.tsx
  suite-native/module-send/src/hooks/__tests__/useUtxoSelection.hook.test.ts
  suite-native/module-send/src/hooks/useSendForm.ts
  suite-native/module-send/src/hooks/useUtxoSelection.ts
  suite-native/module-send/src/screens/SendOutputsScreen.tsx
  suite-native/module-send/src/screens/SendUtxoScreen.tsx
  suite-native/module-send/src/types.ts
Labels: no-project

#20093 test(urls): adjust skipped urls in test
  packages/urls/tests/urls.test.ts
Labels: no-project

#20148 feat(suite): nicer MessageSystemDebugInfo
  packages/suite/src/views/settings/SettingsDebug/MessageSystemDebugInfo.tsx
Labels: DX, tech, no-project

#20160 fix(suite-native): empty settings section
  suite-native/atoms/src/TitledSection.tsx
  suite-native/atoms/src/index.ts
  suite-native/intl/src/en.ts
  suite-native/module-device-settings/src/screens/DeviceSettingsModalScreen.tsx
  suite-native/module-settings/src/components/ConnectionSettings.tsx
  suite-native/module-settings/src/components/FeaturesSettings.tsx
  suite-native/module-settings/src/components/GeneralSettings.tsx
  suite-native/module-settings/src/components/SettingsSection.tsx
  suite-native/module-settings/src/screens/SettingsSupportScreen.tsx
Labels: mobile

#20163 chore: replace cancelled with canceled in error codes
  packages/connect/src/constants/errors.ts
  packages/suite/src/actions/wallet/__fixtures__/coinjoinAccountActions.ts
  suite-common/sentry/src/index.ts
Labels: no-project

#20062 chore: reuse getFreePort from node-utils
  packages/coinjoin/package.json
  packages/coinjoin/tests/mocks/server.ts
  packages/coinjoin/tsconfig.json
  packages/e2e-utils/package.json
  packages/e2e-utils/src/mocks/backendServer.ts
  packages/e2e-utils/tsconfig.json
  yarn.lock
Labels: no-project

#20117 chore(connect): verbosely annotate return type of getMethodInfo in Ab…
  packages/connect/src/core/AbstractMethod.ts
Labels: no-project

#20162 chore(suite-native): check backup analytics
  suite-common/analytics/src/events/suite-native/constants.ts
  suite-common/analytics/src/events/suite-native/types.ts
  suite-native/module-check-backup/src/components/CheckBackupScreenWithExitButton.tsx
  suite-native/module-check-backup/src/hooks/useCheckBackupOnMount.tsx
  suite-native/module-check-backup/src/screens/DeviceCheckBackupSupportScreen.tsx
  suite-native/module-check-backup/src/screens/DeviceCheckBackupTutorialScreen.tsx
Labels: mobile

#20168 fix(suite): T1B1 initialization
  packages/suite/src/hooks/suite/useFirmwareInstallationProgressCheck.ts
Labels: release, cherry-pick🍒

#20065 chore(suite-native): update trezor icons
  suite-common/icons/assets/shieldWater.svg
  suite-common/icons/assets/shieldWaterFilled.svg
  suite-common/icons/assets/trezorAluminiumBody.svg
  suite-common/icons/assets/trezorAluminiumBodyFilled.svg
  suite-common/icons/assets/trezorBody.svg
  suite-common/icons/assets/trezorBodyFilled.svg
  suite-common/icons/assets/trezorSafe5.svg
  suite-common/icons/assets/trezorSafe5Filled.svg
  suite-common/icons/assets/trezorSafe7.svg
  suite-common/icons/assets/trezorSafe7Filled.svg
Labels: mobile

#20171 chore(suite-native): refactored ExchangeLegalSheet
  suite-native/module-trading/src/components/exchange/ExchangeLegalSheet.tsx
Labels: mobile, no-project

#20182 Get free ports
  packages/coinjoin/tests/mocks/server.ts
  packages/e2e-utils/src/mocks/backendServer.ts
  packages/node-utils/src/getFreePort.ts
  packages/node-utils/src/http.ts
  packages/node-utils/src/tests/findProcessFromIncomingPort.test.ts
  packages/suite-desktop-core/src/modules/bluetooth.ts
  packages/suite-desktop-core/src/modules/coinjoin.ts
  packages/suite-desktop-core/src/modules/tor.ts
  packages/transport-bridge/tests/http.test.ts
Labels: no-project

#20179 refactor(suite-native): introduce firmware update stack navigator
  suite-native/module-check-backup/src/hooks/useNavigateToCheckBackup.ts
  suite-native/module-device-settings/src/components/DeviceFirmwareCard.tsx
  suite-native/module-device-settings/src/navigation/DeviceSettingsStackNavigator.tsx
  suite-native/module-device-settings/src/navigation/FirmwareUpdateStackNavigator.tsx
  suite-native/module-device-settings/src/screens/ConfirmFirmwareUpdateScreen.tsx
  suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/FirmwareUpdateAlert.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
Labels: mobile

#20149 refactor(message-system): make message-system synchronous again by caching async osVersion
  packages/suite/src/actions/suite/__tests__/initAction.test.ts
  packages/suite/src/actions/suite/initAction.ts
  packages/suite/src/middlewares/suite/__tests__/messageSystemMiddleware.test.ts
  packages/suite/src/middlewares/suite/messageSystemMiddleware.ts
  suite-common/message-system/src/__fixtures__/messageSystemUtils.ts
  suite-common/message-system/src/__tests__/messageSystemUtils.test.ts
  suite-common/message-system/src/cachedEnvData.ts
  suite-common/message-system/src/index.ts
  suite-common/message-system/src/messageSystemUtils.ts
  suite-native/app/src/initActions.ts
  suite-native/message-system/src/messageSystemMiddleware.ts
  suite-native/module-trading/src/hooks/buy/useBuyQuotes.ts
Labels: no-project

#20214 fix(suite): Use local currency when importing csv values denominated in crypto
  packages/suite/src/hooks/wallet/useSendFormImport.ts
Labels: send, good first issue

#20175 fix(connect-examples): expo issue with typebox
  packages/connect-examples/mobile-expo/metro.config.js
Labels: mobile, no-project

#20231 ci(suite): fix web build
  packages/suite/package.json
  packages/suite/tsconfig.json
  yarn.lock
Labels: no-project

#20237 fix(suite): missing useEmptyPassphrase parameter in ethereumSignTypedData
  suite-common/trading/src/thunks/exchange/signDataAndConfirmThunk.ts
Labels: cherry-pick🍒

#20111 chore(message-system): cleanup feature flag types
  suite-common/message-system/schema/config.schema.v1.json
  suite-common/message-system/src/messageSystemSelectors.ts
  suite-common/suite-types/src/messageSystem.ts
Labels: no-project

#20248 fix(e2e): Fixed broken locktime test
  packages/suite-desktop-core/e2e/tests/wallet/send-form-regtest.test.ts
  packages/suite/src/views/wallet/send/Options/BitcoinOptions/Locktime/Locktime.tsx
  packages/suite/src/views/wallet/send/Options/BitcoinOptions/Locktime/LocktimeBlockHeight.tsx
  packages/suite/src/views/wallet/send/Options/BitcoinOptions/Locktime/LocktimeDatetime.tsx
Labels: bug, e2e

#19490 feat(connect): add thpCall module
  packages/connect/src/device/DeviceCurrentSession.ts
  packages/connect/src/device/thp/thpCall.ts
Labels: connect, no-project, cherry-pick🍒

#20243 feat(suite-native): only select swap supported my assets
  suite-native/intl/src/en.ts
  suite-native/module-trading/src/components/exchange/receive/ExchangeTradeableAssetsSheet.tsx
  suite-native/module-trading/src/components/general/AssetListItem.tsx
  suite-native/module-trading/src/components/general/MyAssetSheet/MyAssetListItem.tsx
  suite-native/module-trading/src/components/general/MyAssetSheet/MyAssetListSectionHeader.tsx
  suite-native/module-trading/src/components/general/MyAssetSheet/__tests__/MyAssetListItem.comp.test.tsx
  suite-native/module-trading/src/components/general/MyAssetSheet/__tests__/MyAssetSheet.comp.test.tsx
  suite-native/module-trading/src/components/general/NetworkBadge.tsx
  suite-native/module-trading/src/components/general/TradeableAssetSheet/TradeableAssetListItem.tsx
  suite-native/module-trading/src/components/general/__tests__/NetworkBadge.comp.test.tsx
  suite-native/module-trading/src/hooks/exchange/useExchangeBuyTradeableAssetsFilteredData.ts
  suite-native/module-trading/src/hooks/exchange/useExchangeTradeableAssetsFilteredData.ts
  suite-native/module-trading/src/hooks/general/__tests__/useSectionList.test.tsx
  suite-native/module-trading/src/hooks/general/useSectionList.tsx
  suite-native/module-trading/src/selectors/__tests__/exchangeSelectors.test.ts
  suite-native/module-trading/src/selectors/exchangeSelectors.ts
  suite-native/module-trading/src/types/general.ts
Labels: mobile

#20256 fix(suite): fee for networks with tokens and different symbol
  packages/suite/src/views/wallet/send/TotalSent/TotalSent.tsx
Labels: cherry-pick🍒

#20273 fix(suite-native): device authenticity check test
  suite-native/app/e2e/pageObjects/deviceSettingsActions.ts
  suite-native/app/e2e/tests/deviceSettings.test.ts
Labels: mobile

#20274 fix(suite-native): fix unstable selector mock in tests
  suite-native/module-trading/src/components/exchange/__tests__/ExchangeLegalSheet.comp.test.tsx
Labels: mobile, no-project

#20279 chore(message-system): add message about Base network sync issues
  suite-common/message-system/config/config.v1.json
Labels: message-system, no-project

#20288 [RELEASE_ONLY]: fix(suite-native): fix e2e element visibility for scroll function
  suite-native/app/e2e/utils.ts
Labels: mobile, no-project

#19966 feat(e2e): update manual test template
  packages/suite-desktop-core/e2e/tests/manual/accounts/pagination.test.ts
  packages/suite-desktop-core/e2e/tests/manual/autoupdate/auto-update.test.ts
  packages/suite-desktop-core/e2e/tests/manual/browser/mobile-browser.test.ts
  packages/suite-desktop-core/e2e/tests/manual/browser/webusb-transport.test.ts
  packages/suite-desktop-core/e2e/tests/manual/btc/receive.test.ts
  packages/suite-desktop-core/e2e/tests/manual/dashboard/portfolio.test.ts
  packages/suite-desktop-core/e2e/tests/manual/metadata/labels.test.ts
  packages/suite-desktop-core/e2e/tests/manual/settings/check-update.test.ts
  packages/suite-desktop-core/e2e/tests/manual/settings/wallet-loading.test.ts
  packages/suite-desktop-core/e2e/tests/manual/wallet/address-scan.test.ts
  packages/suite-desktop-core/e2e/tests/manual/wallet/device-switch.test.ts
  packages/suite-desktop-core/e2e/tests/manual/wallet/remember-wallet.test.ts
Labels: no-project

#20327 fix(connect): handle FW revision check offline errors from AbortController
  packages/connect/src/device/checkFirmwareRevision.ts
Labels: no-project

#20315 test(suite): add support for __info: true param in connect mock
  suite-common/connect-init/src/__tests__/connectInitThunks.test.ts
  suite-common/test-utils/__mocks__/@trezor/connect.ts
Labels: no-project

#20340 feat(suite): do not enforce FW update when debug mode
  packages/suite/src/components/firmware/FirmwareInitial.tsx
Labels: no-project

#20363 Dependabot bumps
  yarn.lock
Labels: dependencies, no-project

#20351 chore(message-system): update Bitcoin Testnet4 message
  suite-common/message-system/config/config.v1.json
Labels: message-system, no-project

#20373 fix(message-system): fix after Bitcoin Testnet4 message update
  suite-common/message-system/config/config.v1.json
Labels: message-system, no-project

#20402 chore(message-system): remove message about Base and BNB networks sync issues
  suite-common/message-system/config/config.v1.json
Labels: message-system, no-project

#20405 chore(suite-native): update knowledge base urls
  suite-native/intl/src/en.ts
  suite-native/link/src/constants.ts
  suite-native/module-add-accounts/src/components/AccountTypeDecisionBottomSheet.tsx
  suite-native/module-add-accounts/src/screens/SelectAccountTypeScreen.tsx
  suite-native/module-authorize-device/src/constants/pinFormConstants.ts
  suite-native/module-send/src/components/CorrectNetworkMessageCard.tsx
  suite-native/module-send/src/components/DestinationTagInput.tsx
  suite-native/module-settings/src/components/SupportCard.tsx
  suite-native/receive/src/components/AddressMismatchBottomSheet.tsx
  suite-native/receive/src/components/ShowAddressButtons.tsx
  suite-native/receive/src/screens/ReceiveAddressScreen.tsx
Labels: mobile

#20379 fix(native): use useNavigateToInitialScreen instead of plain goBack
  suite-native/module-accounts-management/src/components/AccountDetailScreenHeader.tsx
  suite-native/module-send/src/screens/SendAccountsScreen.tsx
Labels: mobile

#20452 feat(suite-desktop-core): enable firmware module
  packages/suite-desktop-core/src/modules/index.ts
Labels: no-project

#20374 Feat/native/auto eject alert
  suite-native/app/e2e/utils.ts
  suite-native/device/src/hooks/useDetectDeviceError.tsx
  suite-native/intl/src/en.ts
  suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/useShowAutoEjectAlert.tsx
  suite-native/settings/package.json
  suite-native/settings/src/settingsSlice.ts
  suite-native/settings/tsconfig.json
  yarn.lock
Labels: mobile

#20344 refactor(suite-common): useFirmwareInstallation uiEvents
  packages/suite/src/components/firmware/FirmwareInstallationStandalone.tsx
  packages/suite/src/components/firmware/ReconnectDevicePrompt.tsx
  packages/suite/src/views/firmware/FirmwareModal.tsx
  packages/suite/src/views/onboarding/steps/FirmwareInstallation.tsx
  suite-common/firmware/src/hooks/useFirmwareInstallation.ts
  suite-native/firmware/src/hooks/useFirmware.tsx
Labels: no-project

#20431 feat(suite-native): select and init confirmation of swap trade
  suite-native/intl/src/en.ts
  suite-native/module-trading/src/__fixtures__/buyQuotes.json
  suite-native/module-trading/src/__fixtures__/tradingState.ts
  suite-native/module-trading/src/components/buy/BuyConfirmation.tsx
  suite-native/module-trading/src/components/buy/BuyLegalSheet.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyPaymentMethodPicker.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyProviderPicker.comp.test.tsx
  suite-native/module-trading/src/components/exchange/ExchangeConfirmation.tsx
  suite-native/module-trading/src/components/exchange/__tests__/ExchangeConfirmation.comp.test.tsx
  suite-native/module-trading/src/hooks/buy/__tests__/useBuyFlow.test.ts
  suite-native/module-trading/src/hooks/buy/__tests__/useBuyForm.test.tsx
  suite-native/module-trading/src/hooks/buy/__tests__/useBuyQuotes.test.ts
  suite-native/module-trading/src/hooks/exchange/__tests__/useExchangeFlow.test.ts
  suite-native/module-trading/src/hooks/exchange/__tests__/useExchangeForm.test.ts
  suite-native/module-trading/src/hooks/exchange/useExchangeFlow.ts
  suite-native/module-trading/src/hooks/exchange/useExchangeForm.ts
  suite-native/module-trading/src/reducers/__tests__/buySlice.test.ts
  suite-native/module-trading/src/reducers/__tests__/tradingSlice.test.ts
  suite-native/module-trading/src/selectors/__tests__/buySelectors.test.ts
  suite-native/module-trading/src/utils/buy/__tests__/quotesUtils.test.ts
Labels: mobile

#20466 feat(suite-native): add basic sell tab placeholder
  suite-common/icons/generateIconFont.ts
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.json
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.ttf
  suite-common/trading/src/selectors/__tests__/tradingSelectors.test.ts
  suite-common/trading/src/selectors/tradingSelectors.ts
  suite-native/module-trading/src/components/general/ActiveTab.tsx
  suite-native/module-trading/src/components/general/Header/HeaderTabs.tsx
  suite-native/module-trading/src/components/general/Header/__tests__/Header.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/ActiveTab.comp.test.tsx
  suite-native/module-trading/src/components/sell/SellFormSkeleton.tsx
  suite-native/module-trading/src/components/sell/SellTab.tsx
  suite-native/module-trading/src/components/sell/SellTabContent.tsx
  suite-native/module-trading/src/components/sell/__tests__/SellTab.comp.test.tsx
  suite-native/module-trading/src/components/sell/__tests__/SellTabContent.comp.test.tsx
  suite-native/module-trading/src/hooks/sell/__tests__/useSellData.test.tsx
  suite-native/module-trading/src/hooks/sell/useSellData.tsx
Labels: mobile

#20450 chore(suite-native): caret-up-down icon
  suite-common/icons/assets/caretUpDownReverse.svg
  suite-common/icons/assets/caretUpDownReverseFilled.svg
  suite-common/icons/src/icons.ts
Labels: mobile, no-project

#20485 fix(nixos): sharp dependency build
  flake.nix
  package.json
  shell.nix
  yarn.lock
Labels: no-project

#20400 nix: update rust shell.nix to match root shell
  packages/transport-bluetooth/shell.nix
Labels: no-project
