Repository trezor/trezor-suite, pull requests merged in 2025-08, with the labels that each got.

#20490 Mobile Swap: extract SendOutputsReviewScreen to be reusable
  suite-native/intl/src/en.ts
  suite-native/module-send/package.json
  suite-native/module-send/src/components/AddressReviewStepList.tsx
  suite-native/module-send/src/components/FeesFooter.tsx
  suite-native/module-send/src/components/ReviewOutputItem.tsx
  suite-native/module-send/src/components/ReviewOutputItemContent.tsx
  suite-native/module-send/src/components/ReviewOutputItemList.tsx
  suite-native/module-send/src/components/ReviewOutputItemValues.tsx
  suite-native/module-send/src/selectors.ts
  suite-native/module-send/tsconfig.json
  suite-native/transaction-management/jest.config.js
  suite-native/transaction-management/package.json
  suite-native/transaction-management/redux.d.ts
  suite-native/transaction-management/src/__fixtures__/walletState.ts
  suite-native/transaction-management/src/components/ReviewOutputItemList/ReviewOutputCard.tsx
  suite-native/transaction-management/src/components/ReviewOutputItemList/ReviewOutputItem.tsx
  suite-native/transaction-management/src/components/ReviewOutputItemList/ReviewOutputItemContent.tsx
  suite-native/transaction-management/src/components/ReviewOutputItemList/ReviewOutputItemList.tsx
  suite-native/transaction-management/src/components/ReviewOutputItemList/ReviewOutputItemValues.tsx
  suite-native/transaction-management/src/components/ReviewOutputItemList/ReviewOutputStatusBadge.tsx
  suite-native/transaction-management/src/components/ReviewOutputItemList/ReviewOutputSummaryItem.tsx
  suite-native/transaction-management/src/components/ReviewOutputItemList/__tests__/ReviewOutputItem.comp.test.tsx
  suite-native/transaction-management/src/components/ReviewOutputItemList/__tests__/ReviewOutputItemList.comp.test.tsx
  suite-native/transaction-management/src/components/ReviewOutputItemList/__tests__/ReviewOutputItemValues.comp.test.tsx
  suite-native/transaction-management/src/components/ReviewOutputItemList/__tests__/ReviewOutputSummaryItem.comp.test.tsx
  suite-native/transaction-management/src/components/SlidingFooterOverlay.tsx
  suite-native/transaction-management/src/components/__tests__/SlidingFooterOverlay.comp.test.tsx
  suite-native/transaction-management/src/hooks/__tests__/useActiveStepOffset.test.ts
  suite-native/transaction-management/src/hooks/useActiveStepOffset.ts
  suite-native/transaction-management/src/index.ts
  suite-native/transaction-management/src/types.ts
  suite-native/transaction-management/tsconfig.json
  yarn.lock
Labels: mobile

#20530 fix(suite): fix BigAmount formatting
  packages/product-components/src/components/NumberInput/NumberInput.tsx
  packages/suite-desktop-core/e2e/support/common.ts
  packages/suite-desktop-core/e2e/tests/trading/buy-bitcoin.test.ts
  packages/suite-desktop-core/e2e/tests/trading/buy-ethereum.test.ts
  packages/suite-desktop-core/e2e/tests/trading/buy-solana-token.test.ts
  packages/suite-desktop-core/e2e/tests/trading/sell-inputs.test.ts
  packages/suite-desktop-core/e2e/tests/trading/sell-solana.test.ts
  packages/suite-desktop-core/e2e/tests/wallet/coin-balance.test.ts
  packages/suite/src/actions/settings/languageActions.ts
  packages/suite/src/actions/suite/suiteActions.ts
  packages/suite/src/components/suite/__tests__/NumberInput.test.tsx
  packages/suite/src/components/wallet/BigAmountValue.tsx
  packages/suite/src/config/suite/index.ts
  packages/suite/src/hooks/guide/useGuideLoadArticle.ts
  packages/suite/src/hooks/suite/useDebugLanguageShortcut.ts
  packages/suite/src/hooks/suite/useLocales.ts
  packages/suite/src/reducers/suite/suiteReducer.ts
  packages/suite/src/storage/migrations/versions/25.8.0.ts
  packages/suite/src/support/suite/Autodetect.tsx
  packages/suite/src/support/suite/ConnectedIntlProvider.tsx
  packages/suite/src/utils/suite/l10n.ts
  packages/suite/src/views/settings/SettingsDevice/ChangeLanguage.tsx
  packages/suite/src/views/settings/SettingsGeneral/Language.tsx
  suite-common/suite-types/src/index.ts
  suite-common/suite-types/src/languages.ts
  suite-common/wallet-utils/src/__tests__/balanceUtils.test.ts
  suite-common/wallet-utils/src/__tests__/localizeNumber.test.ts
  suite-common/wallet-utils/src/balanceUtils.ts
  suite-common/wallet-utils/src/localizeNumberUtils.ts
Labels: no-project

#20540 chore(message-system): mgr 58
  suite-common/message-system/config/config.v1.json
Labels: message-system, no-project

#19214 ci(connect): set node-bridge to default in tests
  .github/workflows/template-connect-test-params.yml
  .github/workflows/test-connect.yml
Labels: no-project

#20536 fix(suite-native): correct assets for selling in trade sell flow
  suite-common/trading/src/selectors/__tests__/tradingSelectors.test.ts
  suite-common/trading/src/selectors/tradingSelectors.ts
  suite-native/module-trading/src/components/exchange/send/ExchangeSendAssetPicker.tsx
  suite-native/module-trading/src/components/exchange/send/__tests__/ExchangeSendAssetPicker.comp.test.tsx
  suite-native/module-trading/src/components/general/MyAssetSheet/MyAssetSheet.tsx
  suite-native/module-trading/src/components/general/MyAssetSheet/__tests__/MyAssetSheet.comp.test.tsx
  suite-native/module-trading/src/components/sell/send/SellSendAssetPicker.tsx
  suite-native/module-trading/src/components/sell/send/__tests__/SellSendAssetPicker.test.tsx
  suite-native/module-trading/src/selectors/__tests__/commonSelectors.test.ts
  suite-native/module-trading/src/selectors/__tests__/exchangeSelectors.test.ts
  suite-native/module-trading/src/selectors/commonSelectors.ts
  suite-native/module-trading/src/selectors/exchangeSelectors.ts
Labels: mobile

#19898 fix(trading): update trading currency based on currency from settings
  packages/suite/src/hooks/wallet/trading/form/useTradingBuyFormDefaultValues.ts
  packages/suite/src/hooks/wallet/trading/form/useTradingSellFormDefaultValues.ts
Labels: bug

#20503 chore(suite-native): E2E isFirmwareUpdateEnabled Flag + Preloaded State Types
  suite-native/app/e2e/fixtures/onboardingCompleted.json
  suite-native/app/e2e/fixtures/onboardingCompleted.ts
  suite-native/app/e2e/fixtures/walletWithBtcAcc.json
  suite-native/app/e2e/fixtures/walletWithBtcAcc.ts
  suite-native/app/e2e/tests/accountManagement.test.ts
  suite-native/app/e2e/tests/appSettings.test.ts
  suite-native/app/e2e/tests/appSettingsWithDevice.test.ts
  suite-native/app/e2e/tests/bitcoinAccountsImport.test.ts
  suite-native/app/e2e/tests/deeplinkPopup.test.ts
  suite-native/app/e2e/tests/deviceOnboarding.test.ts
  suite-native/app/e2e/tests/deviceSettings.test.ts
  suite-native/app/e2e/tests/invalidAccountsImport.test.ts
  suite-native/app/e2e/tests/launchArguments.test.ts
  suite-native/app/e2e/tests/othersAccountsImport.test.ts
  suite-native/app/e2e/tests/passphraseFlow.test.ts
  suite-native/app/e2e/tests/receive.test.ts
  suite-native/app/e2e/tests/send.test.ts
  suite-native/app/e2e/tests/tradingBuyFlow.test.ts
  suite-native/app/e2e/utils.ts
  suite-native/atoms/package.json
  suite-native/atoms/src/constants.e2e.ts
  suite-native/atoms/src/constants.ts
  suite-native/atoms/tsconfig.json
  suite-native/config/src/launch-arguments.ts
  suite-native/firmware/src/hooks/useIsFirmwareUpdateFeatureEnabled/index.e2e.ts
  suite-native/firmware/src/hooks/useIsFirmwareUpdateFeatureEnabled/index.ts
  suite-native/firmware/src/hooks/useIsFirmwareUpdateFeatureEnabled/useIsFirmwareUpdateFeatureEnabled.tsx
  yarn.lock
Labels: mobile, no-project

#20578 chore(components): remove duplicated Icons export
  packages/components/src/index.ts
Labels: no-project

#20573 fix(trading): fix account not activated even if account is activated
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx
Labels: bug

#20590 fix(suite): switch device during connect getAddress call
  packages/suite/src/support/suite/useConnectPopupModals.tsx
  suite-common/connect-popup/src/connectPopupThunks.ts
Labels: build-desktop

#20613 chore(suite): amend release notes for 25.8x
  packages/suite-desktop/releaseNotes/release-notes.md
Labels: no-project

#20546 feat(suite-native): default navigation animation
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/navigation/src/config.ts
Labels: mobile

#20543 chore(tests): remove cypress mentions
  docker/ci-base/Dockerfile
  docker/docker-compose.suite-test.yml
  docker/docker-suite-install.sh
  docker/docker-suite-test.sh
  docker/test-runner/Dockerfile
  packages/components/src/components/form/Checkbox/Checkbox.tsx
  packages/components/src/components/form/Switch/Switch.tsx
  packages/connect-web/eslint.config.mjs
Labels: no-project

#20629 fix(suite-common): use correct naming of cable icons
  suite-common/icons/assets/cableUsbC.svg
  suite-common/icons/assets/cableUsbCFilled.svg
  suite-common/icons/assets/cableUsbMicro.svg
  suite-common/icons/assets/cableUsbMicroFilled.svg
  suite-common/icons/src/icons.ts
Labels: mobile

#20655 chore(message-system): amend update required message
  suite-common/message-system/config/config.v1.json
Labels: message-system, no-project

#20653 chore(suite): remove redundant if statement
  packages/suite/src/components/suite/banners/SuiteBanners/SuiteBanners.tsx
Labels: no-project

#20663 fix(suite-native): use ios_from_right as default navigation animation
  suite-native/navigation/src/config.ts
Labels: mobile

#20673 feat(suite-native): icons for remaining networks
  suite-common/icons/cryptoAssets/networkIcons/bch.svg
  suite-common/icons/cryptoAssets/networkIcons/bch_inverse.svg
  suite-common/icons/cryptoAssets/networkIcons/dash_inverse.svg
  suite-common/icons/cryptoAssets/networkIcons/doge.svg
  suite-common/icons/cryptoAssets/networkIcons/etc.svg
  suite-common/icons/cryptoAssets/networkIcons/etc_inverse.svg
  suite-common/icons/cryptoAssets/networkIcons/ltc.svg
  suite-common/icons/cryptoAssets/networkIcons/ltc_inverse.svg
  suite-common/icons/cryptoAssets/networkIcons/xlm.svg
  suite-common/icons/cryptoAssets/networkIcons/xlm_inverse.svg
  suite-common/icons/cryptoAssets/networkIcons/xrp.svg
  suite-common/icons/cryptoAssets/networkIcons/xrp_inverse.svg
  suite-common/icons/cryptoAssets/networkIcons/zec.svg
  suite-common/icons/cryptoAssets/networkIcons/zec_inverse.svg
  suite-common/icons/src/networkIcons.ts
Labels: mobile, no-project

#20561 feat(suite-native): device manager refactor
  suite-native/device-manager/src/components/ConnectButton.tsx
  suite-native/device-manager/src/components/DeviceItem/SimpleDeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceItem/WalletDetailDeviceItemContent.tsx
  suite-native/device-manager/src/components/DeviceList.tsx
  suite-native/device-manager/src/components/DeviceManagerContent.tsx
  suite-native/device-manager/src/components/DeviceManagerModal.tsx
  suite-native/device-manager/src/components/WalletItemBase.tsx
  suite-native/intl/src/en.ts
Labels: mobile

#20649 test(suite-native): fix setup when running locally on mac
  suite-native/app/e2e/utils.ts
Labels: no-project

#20676 fix(connect): cloneObject bottleneck in coinInfo
  packages/connect/src/data/coinInfo.ts
Labels: no-project

#20631 feat(suite-native): improve Bluetooth pairing flows
  suite-common/icons/generateIconFont.ts
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.json
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.ttf
  suite-native/app/app.config.ts
  suite-native/atoms/src/Button/TextButton.tsx
  suite-native/atoms/src/IconListItem.tsx
  suite-native/bluetooth/package.json
  suite-native/bluetooth/src/components/BluetoothDeviceCard.tsx
  suite-native/bluetooth/src/components/BluetoothDeviceList.tsx
  suite-native/bluetooth/src/components/BluetoothDeviceManager.tsx
  suite-native/bluetooth/src/components/NoTrezorNearbyCard.tsx
  suite-native/bluetooth/src/hooks/useBluetoothAlerts.ts
  suite-native/bluetooth/src/hooks/useBluetoothManager.ts
  suite-native/bluetooth/src/index.ts
  suite-native/bluetooth/src/selectors.ts
  suite-native/bluetooth/tsconfig.json
  suite-native/device/src/assets/turnOnDeviceLottie.json
  suite-native/device/src/components/TurnOnAndUnlockDeviceScreenContent.tsx
  suite-native/device/src/components/TurnOnDeviceAnimation.tsx
  suite-native/device/src/index.ts
  suite-native/intl/src/en.ts
  suite-native/module-authorize-device/src/assets/connect/pairing-android.webp
  suite-native/module-authorize-device/src/assets/connect/pairing-ios.webp
  suite-native/module-authorize-device/src/components/connect/BluetoothDeviceScreenHeader.tsx
  suite-native/module-authorize-device/src/components/connect/BluetoothPairingHelpButton.tsx
  suite-native/module-authorize-device/src/components/connect/BluetoothPairingHints.tsx
  suite-native/module-authorize-device/src/components/connect/BluetoothPairingSettings.tsx
  suite-native/module-authorize-device/src/components/connect/ConnectDeviceScreenHeader.tsx
  suite-native/module-authorize-device/src/navigation/AuthorizeDeviceStackNavigator.tsx
  suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx
  suite-native/module-authorize-device/src/screens/connect/ConnectBluetoothDeviceScreen.tsx
  suite-native/module-authorize-device/src/screens/connect/RemoveBluetoothDeviceScreen.tsx
  suite-native/module-authorize-device/src/screens/connect/TurnOnAndUnlockDeviceScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyPortfolioCrossroads.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#20357 Feat/bt server set state
  packages/transport-bluetooth/src/server/adapter_manager.rs
  packages/transport-bluetooth/src/server/device.rs
  packages/transport-bluetooth/src/server/message_handler.rs
  packages/transport-bluetooth/src/server/methods/mod.rs
  packages/transport-bluetooth/src/server/methods/set_state.rs
  packages/transport-bluetooth/src/server/types.rs
Labels: no-project

#20698 chore(suite-native): remove check backup feature flag
  suite-native/app/.env.test
  suite-native/feature-flags/src/__tests__/featureFlagsSlice.test.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/firmware/src/components/ConfirmBottomSheet.tsx
  suite-native/intl/src/en.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  suite-native/module-device-settings/src/screens/ConfirmFirmwareUpdateScreen.tsx
  suite-native/module-device-settings/src/screens/DeviceSettingsModalScreen.tsx
Labels: mobile

#20702 test(connect): disable t3w1 from tests
  .github/workflows/test-connect.yml
Labels: no-project

#20703 chore(connect): remove duplicate property assignment in bleUnpair method
  packages/connect/src/api/bleUnpair.ts
Labels: no-project

#20430 feat(suite-native): continue on your trezor 2.0
  packages/theme/src/borders.ts
  packages/theme/src/spacings.ts
  suite-native/device/package.json
  suite-native/device/src/components/ConfirmOnTrezor/ConfirmOnTrezorContent.tsx
  suite-native/device/src/components/ConfirmOnTrezor/ConfirmOnTrezorHeader.tsx
  suite-native/device/src/components/ConfirmOnTrezor/ConfirmOnTrezorIndicator.tsx
  suite-native/device/src/components/ConfirmOnTrezor/ConfirmOnTrezorInstructions.tsx
  suite-native/device/src/components/ConfirmOnTrezor/ConfirmOnTrezorWrapper.tsx
  suite-native/device/src/components/ConfirmOnTrezor/hooks/useConfirmOnTrezorController.ts
  suite-native/device/src/components/ConfirmOnTrezor/hooks/useConfirmOnTrezorSheet.ts
  suite-native/device/src/components/ConfirmOnTrezor/index.ts
  suite-native/device/src/index.ts
  suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx
  suite-native/firmware/src/hooks/useFirmware.tsx
  suite-native/intl/src/en.ts
  suite-native/module-device-onboarding/src/components/DeviceOnboardingScreenWithExitButton.tsx
  suite-native/module-device-onboarding/src/components/WalletInitScreenWrapper.tsx
  suite-native/module-device-onboarding/src/screens/FirmwareInstallationScreen.tsx
  suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx
  suite-native/module-send/src/components/AddressReviewStepList.tsx
  suite-native/module-send/src/components/SendConfirmOnDeviceImage.tsx
  suite-native/module-send/src/screens/SendAddressReviewScreen.tsx
  suite-native/module-send/src/screens/SendDestinationTagReviewScreen.tsx
  suite-native/module-send/src/screens/SendOutputsReviewScreen.tsx
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/receive/src/screens/ReceiveAddressScreen.tsx
  yarn.lock
Labels: mobile

#20671 connect method __info useful for validation
  packages/connect/e2e/tests/device/info.test.ts
  packages/connect/src/core/AbstractMethod.ts
Labels: no-project

#20732 native send form can pre-fill invalid feePerUnit decimals
  suite-native/module-send/src/components/SendFeesForm.tsx
  suite-native/module-send/src/sendFeesFormSchema.ts
  suite-native/module-send/src/utils.ts
Labels: send, mobile, release-native

#20665 chore(github): update stellar advanced definition to JSON format
  .github/workflows/release-suite-definitions.yml
Labels: no-project

#20606 core(codeowners): change code-owner roles
  CODEOWNERS
Labels: no-project

#20771 fix(connect-explorer-theme): z-index for dropdown on mobile
  packages/connect-explorer-theme/css/styles.css
  packages/connect-explorer-theme/src/components/sidebar.tsx
Labels: no-project

#20760 fix(components): props leaking into html img
  packages/components/src/components/Image/Image.tsx
Labels: no-project

#20775 test(connect): make it possible to run tests against model that has no …
  packages/connect/e2e/run.ts
Labels: no-project

#19633 chore(connect): add missing capabilities to config
  packages/connect/src/data/config.ts
  packages/connect/src/utils/__tests__/deviceFeaturesUtils.test.ts
Labels: connect, no-project

#20849 fix(suite): Translate hex value to human readable correctly
  packages/suite/src/views/wallet/send/Outputs/OpReturn.tsx
Labels: send

#20853 fix(suite-native): correct feature flag in selectIsEntropyCheckEnabledAndFailed
  suite-native/device/src/selectors.ts
Labels: no-project

#20855 fix traffic light offset wrapper
  packages/suite/src/components/suite/TrafficLightOffset.tsx
  packages/suite/src/views/suite/SwitchDevice/SwitchDeviceModal.tsx
Labels: no-project

#20704 feat(transport-bluetooth): use write with response
  packages/transport-bluetooth/src/client/bluetooth-api.ts
  packages/transport-bluetooth/src/client/transport.ts
  packages/transport-bluetooth/src/client/trezor-bluetooth.ts
  packages/transport-bluetooth/src/client/types.ts
Labels: no-project, cherry-pick🍒

#20903 feat(suite-native): Mobile Swap: reload quotes on trading account change
  suite-native/module-trading/src/hooks/exchange/__tests__/useExchangeQuotes.test.ts
  suite-native/module-trading/src/hooks/exchange/useExchangeQuotes.ts
Labels: mobile

#20907 Mobile Swap: make sure FiatCurrencies uses correct trade type context
  suite-native/module-trading/src/__fixtures__/tradingState.ts
  suite-native/module-trading/src/components/buy/BuyFiatCurrencyPicker.tsx
  suite-native/module-trading/src/components/buy/BuyFiatCurrencySheet.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyFiatCurrencySheet.comp.test.tsx
  suite-native/module-trading/src/components/general/FiatCurrencySheet/FiatCurrencySheet.tsx
  suite-native/module-trading/src/components/sell/fiat/SellFiatCurrencyPicker.tsx
  suite-native/module-trading/src/components/sell/fiat/SellFiatCurrencySheet.tsx
  suite-native/module-trading/src/components/sell/fiat/__tests__/SellFiatCurrencyPicker.test.tsx
  suite-native/module-trading/src/components/sell/fiat/__tests__/SellFiatCurrencySheet.comp.test.tsx
  suite-native/module-trading/src/hooks/general/__tests__/useFiatCurrencyFilteredData.test.ts
  suite-native/module-trading/src/hooks/general/useFiatCurrencyFilteredData.ts
Labels: mobile

#20904 chore(suite): remove unused CreateDeviceInstanceError
  suite-common/wallet-core/src/device/deviceThunks.ts
Labels: no-project

#20917 feat(suite): debug settings forget all BT devices
  packages/suite/src/views/settings/SettingsDebug/BluetoothEnabledCheckbox.tsx
  packages/suite/src/views/settings/SettingsDebug/ForgetBluetoothDevices.tsx
  packages/suite/src/views/settings/SettingsDebug/SettingsDebug.tsx
Labels: no-project

#20895 fix(suite-native): keep fiat value as null before loaded so skeleton is visible instead of zero
  suite-native/assets/src/assetsSelectors.ts
Labels: mobile, release-native

#20915 feat(suite-native): analytics for auto eject
  suite-common/analytics/src/events/suite-native/constants.ts
  suite-common/analytics/src/events/suite-native/types.ts
  suite-native/module-home/src/screens/HomeScreen/useShowAutoEjectAlert.tsx
  suite-native/module-settings/src/components/EjectWallets/AutoEjectSwitch.tsx
  suite-native/module-settings/src/components/EjectWallets/WalletRememberModeIconButton.tsx
Labels: mobile, release-native

#20875 fix(suite): banner did not display correct localization
  packages/suite/src/components/suite/banners/MessageSystemBanner.tsx
  suite-common/message-system/src/__fixtures__/messageSystemUtils.ts
Labels: bug

#20984 chore(suite-native): update device onboarding renders
  suite-native/device/src/types.ts
  suite-native/module-device-onboarding/src/assets/t2t1-seal.webp
  suite-native/module-device-onboarding/src/assets/t2t1.png
  suite-native/module-device-onboarding/src/assets/t2t1.webp
  suite-native/module-device-onboarding/src/assets/t2t1Seal.png
  suite-native/module-device-onboarding/src/assets/t3b1-seal-v1.webp
  suite-native/module-device-onboarding/src/assets/t3b1-seal-v2.webp
  suite-native/module-device-onboarding/src/assets/t3b1.png
  suite-native/module-device-onboarding/src/assets/t3b1.webp
  suite-native/module-device-onboarding/src/assets/t3b1Seal1.png
  suite-native/module-device-onboarding/src/assets/t3b1Seal2.png
  suite-native/module-device-onboarding/src/assets/t3t1-seal.webp
  suite-native/module-device-onboarding/src/assets/t3t1.png
  suite-native/module-device-onboarding/src/assets/t3t1.webp
  suite-native/module-device-onboarding/src/assets/t3t1Seal.png
  suite-native/module-device-onboarding/src/assets/t3w1-seal.webp
  suite-native/module-device-onboarding/src/assets/t3w1.webp
  suite-native/module-device-onboarding/src/components/DeviceModelImage.tsx
  suite-native/module-device-onboarding/src/components/SecuritySealImages.tsx
  suite-native/module-device-onboarding/src/screens/UninitializedDeviceLandingScreen.tsx
Labels: mobile

#20994 ci(connect): exlude t3w1 unspupported coin groups during matrix gener…
  scripts/ci/connect-test-matrix-generator.js
Labels: no-project

#20936 feat(suite-native): THP implementation for mobile
  packages/suite/src/components/firmware/FirmwareProgressBar.tsx
  packages/transport-native-bluetooth/src/api/BluetoothApi.ts
  packages/transport-native-bluetooth/src/api/bluetoothManager.ts
  suite-common/firmware/src/hooks/useFirmwareInstallation.ts
  suite-common/thp/src/autoInitThpAfterDeviceConnectionThunk.ts
  suite-common/thp/src/connectThpDeviceThunk.ts
  suite-common/thp/src/index.ts
  suite-common/thp/src/thpSelectors.ts
  suite-common/thp/tests/autoInitThpAfterDeviceConnectionThunk.test.ts
  suite-common/wallet-core/src/device/deviceSelectors.ts
  suite-native/bluetooth/src/bluetoothSlice.ts
  suite-native/device/src/hooks/useDetectDeviceError.tsx
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/device/src/utils.ts
  suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx
  suite-native/firmware/src/hooks/useFirmware.tsx
  suite-native/intl/src/en.ts
  suite-native/module-authorize-device/src/components/thp/ThpScreenHeader.tsx
  suite-native/module-authorize-device/src/hooks/useInitiateThpConnection.ts
  suite-native/module-authorize-device/src/navigation/AuthorizeDeviceStackNavigator.tsx
  suite-native/module-authorize-device/src/screens/thp/ThpCodeEntryScreen.tsx
  suite-native/module-authorize-device/src/screens/thp/ThpConfirmationScreen.tsx
  suite-native/module-device-onboarding/package.json
  suite-native/module-device-onboarding/src/components/DeviceOnboardingScreenWithExitButton.tsx
  suite-native/module-device-onboarding/src/hooks/useInitiateThpConnection.ts
  suite-native/module-device-onboarding/src/hooks/useNavigateToNextScreenAfterFirmwareInstallation.ts
  suite-native/module-device-onboarding/src/navigation/DeviceOnboardingStackNavigator.tsx
  suite-native/module-device-onboarding/src/screens/FirmwareInstallationScreen.tsx
  suite-native/module-device-onboarding/src/screens/ThpCodeEntryScreen.tsx
  suite-native/module-device-onboarding/src/screens/ThpConfirmationScreen.tsx
  suite-native/module-device-onboarding/src/screens/ThpPairingInfoScreen.tsx
  suite-native/module-device-onboarding/src/screens/ThpPairingSuccessScreen.tsx
  suite-native/module-device-onboarding/tsconfig.json
  suite-native/module-device-settings/src/hooks/useInitiateThpConnection.ts
  suite-native/module-device-settings/src/navigation/FirmwareUpdateStackNavigator.tsx
  suite-native/module-device-settings/src/screens/FirmwareInstallationScreen.tsx
  suite-native/module-device-settings/src/screens/ThpConfirmationScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyHomeRenderer.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyPortfolioCrossroads.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/state/package.json
  suite-native/state/src/extraDependencies.ts
  suite-native/state/src/reducers.ts
  suite-native/state/tsconfig.json
  suite-native/thp/package.json
  suite-native/thp/src/assets/CreateSecureConnectionSvg.tsx
  suite-native/thp/src/components/SecurityCodeInput.tsx
  suite-native/thp/src/components/ThpCodeEntryScreenContent.tsx
  suite-native/thp/src/components/ThpPairingInfoHelpButton.tsx
  suite-native/thp/src/components/ThpPairingInfoScreenContent.tsx
  suite-native/thp/src/components/ThpPairingSuccessScreenContent.tsx
  suite-native/thp/src/hooks/useThpAlert.tsx
  suite-native/thp/src/index.ts
  suite-native/thp/tsconfig.json
  yarn.lock
Labels: mobile

#21012 feat(suite-native): enable Connect device and Bluetooth FFs for adhoc builds
  suite-native/app/eas.json
Labels: mobile

#21020 chore(firmware-authenticity): do not Sentry report if device not connected
  suite-common/firmware-authenticity/src/useReportDeviceCompromised.ts
Labels: no-project

#21044 fix(suite-native): device settings ble card
  suite-native/module-device-settings/src/components/DeviceBluetoothCard.tsx
  suite-native/module-device-settings/src/screens/DeviceSettingsModalScreen.tsx
Labels: mobile, UI, no-project

#21054 feat(suite-native): show connect illustration on iOS dashboard
  suite-native/intl/src/en.ts
  suite-native/module-home/src/assets/TurnOnTrezorSvg.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyPortfolioCrossroads.tsx
Labels: mobile

#21080 chore(suite-native): update device renders
  suite-native/device/src/assets/t1b1.webp
  suite-native/device/src/assets/t2t1.webp
  suite-native/device/src/assets/t3b1.webp
  suite-native/device/src/assets/t3t1.webp
  suite-native/device/src/components/DeviceImage.tsx
Labels: mobile

#21085 feat(suite-native): prepare view only animation for Bluetooth devices
  .prettierignore
  suite-native/module-home/src/assets/auto-eject-cable-lottie.json
  suite-native/module-home/src/assets/auto-eject-wireless-lottie.json
  suite-native/module-home/src/screens/HomeScreen/components/AutoEjectAnimation.tsx
  suite-native/module-home/src/screens/HomeScreen/useShowAutoEjectAlert.tsx
Labels: mobile

#21112 feat(suite-native): show only pairable devices on the Turn on & unlock screen
  suite-native/bluetooth/jest.config.js
  suite-native/bluetooth/src/__tests__/selectors.test.ts
  suite-native/bluetooth/src/bluetoothSlice.ts
  suite-native/bluetooth/src/selectors.ts
  suite-native/module-authorize-device/src/screens/connect/ConnectBluetoothDeviceScreen.tsx
  suite-native/module-authorize-device/src/screens/connect/TurnOnAndUnlockDeviceScreen.tsx
Labels: mobile, bluetooth

#21119 style(suite): This backup argument should be camelCase
  packages/suite/src/actions/backup/backupActions.ts
Labels: code, no-project

#21060 chore(suite-data): Remove unused languages
  packages/suite-data/files/translations/af-ZA.json
  packages/suite-data/files/translations/ar-SA.json
  packages/suite-data/files/translations/be.json
  packages/suite-data/files/translations/ca-ES.json
  packages/suite-data/files/translations/da-DK.json
  packages/suite-data/files/translations/el-GR.json
  packages/suite-data/files/translations/fi-FI.json
  packages/suite-data/files/translations/he-IL.json
  packages/suite-data/files/translations/hi-IN.json
  packages/suite-data/files/translations/id-ID.json
  packages/suite-data/files/translations/jv-ID.json
  packages/suite-data/files/translations/ko.KR.json
  packages/suite-data/files/translations/lol-US.json
  packages/suite-data/files/translations/nl-NL.json
  packages/suite-data/files/translations/no-NO.json
  packages/suite-data/files/translations/pl-PL.json
  packages/suite-data/files/translations/ro-RO.json
  packages/suite-data/files/translations/si-LK.json
  packages/suite-data/files/translations/sk-SK.json
  packages/suite-data/files/translations/sr-RS.json
  packages/suite-data/files/translations/sv-SE.json
  packages/suite-data/files/translations/vi-VN.json
  packages/suite-data/files/translations/ww.json
  packages/suite/package.json
  packages/suite/src/hooks/suite/useLocales.ts
  suite-common/suite-types/src/languages.ts
Labels: ci, no-project

#20423 Feat: bluetooth server device update/disconnect handler
  packages/transport-bluetooth/src/server/adapter_manager.rs
  packages/transport-bluetooth/src/server/device.rs
  packages/transport-bluetooth/src/server/types.rs
Labels: no-project, cherry-pick🍒

#21148 fix(suite-native): fix typo in Expo env variable
  suite-native/app/.env.development
  suite-native/app/eas.json
  suite-native/settings/src/settingsSlice.ts
Labels: mobile

#21141 fix(suite-native): propagate manufacturer data changes to nearby devices
  packages/transport-native-bluetooth/src/api/bluetoothManager.ts
  suite-native/bluetooth/src/__tests__/selectors.test.ts
  suite-native/bluetooth/src/selectors.ts
Labels: mobile, bluetooth

#21150 fix(suite-native): use correct react-native-svg version for THP package
  suite-native/thp/package.json
  yarn.lock
Labels: mobile, THP

#21152 chore(suite-common): split thp finish actions
  packages/suite/src/actions/thp/removeThpAutoconnectThunk.ts
  packages/suite/src/components/connection/thp/ThpAutoconnectInfoModal.tsx
  packages/suite/src/components/connection/thp/ThpAutoconnectionModal.tsx
  packages/suite/src/components/connection/thp/ThpConnectionModal.tsx
  packages/suite/src/components/connection/thp/ThpPairingFailedModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/DeviceContextModal/ThpPairingPinEntryModal.tsx
  suite-common/thp/src/connectThpDeviceThunk.ts
  suite-common/thp/src/startThpAutoconnectThunk.ts
  suite-common/thp/src/thpActions.ts
  suite-common/thp/src/thpReducer.ts
  suite-common/wallet-core/src/device/deviceThunks.ts
  suite-native/thp/src/hooks/useThpAlert.tsx
Labels: mobile, no-project, THP

#21123 Mobile Sell: Receive method picker
  suite-native/module-trading/src/components/buy/BuyPaymentMethodPicker.tsx
  suite-native/module-trading/src/components/general/PaymentMethodSheet/PaymentMethodSheet.tsx
  suite-native/module-trading/src/components/sell/fiat/SellReceiveMethodPicker.tsx
  suite-native/module-trading/src/components/sell/fiat/__tests__/SellReceiveMethodPicker.comp.test.tsx
Labels: mobile

#21164 chore(connect): removing unecessary TODO comment
  packages/connect/src/device/Device.ts
Labels: no-project

#21169 chore: remove duplicite type declaration
  suite-native/app/e2e/pageObjects/deviceOnboardingActions.ts
  suite-native/device/src/deviceThunks.ts
  suite-native/device/src/types.ts
  suite-native/module-device-onboarding/src/components/WalletBackupSheet/WalletBackupCard/CardContent.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupSheet/WalletBackupCard/CardHeader.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupSheet/WalletBackupCard/WalletBackupCard.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupSheet/WalletBackupSheet.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupSheet/WalletBackupSheetFooter.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupSheet/presets.ts
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep5.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep6.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/presets.ts
  suite-native/module-device-onboarding/src/screens/WalletBackupTutorialScreen.tsx
Labels: no-project
