Repository trezor/trezor-suite, pull requests merged in 2025-10, with the labels that each got.

#22048 Mobile Swap: memoize selectReviewSummaryOutput
  suite-native/transaction-management/src/selectors.ts
Labels: mobile

#22042 fix(suite-native): android e2e pass web-hook secret
  .github/workflows/template-suite-native-e2e-android.yml
  .github/workflows/test-suite-native-e2e-android.yml
Labels: mobile, no-project

#22065 feat(suite-native): update send copy
  suite-native/intl/src/messages.ts
Labels: mobile

#22093 refactor(suite-common): tweak naming of isDeviceConnectedViaBluetooth
  suite-common/suite-utils/src/__fixtures__/device.ts
  suite-common/suite-utils/src/__tests__/device.test.ts
  suite-common/suite-utils/src/device.ts
  suite-common/wallet-core/src/device/deviceSelectors.ts
  suite-native/device/src/middlewares/deviceConnectionMiddleware.ts
Labels: no-project, bluetooth

#22083 fix: unpair BLE device when forgetting it
  packages/suite/src/actions/bluetooth/bluetoothEraseBondsThunk.ts
Labels: no-project

#22096 fix(suite-native): send DAC failure to DeviceCompromised screen
  suite-native/device/src/hooks/useDeviceAuthenticityCheck.ts
  suite-native/module-device-onboarding/src/screens/DeviceAuthenticityScreen.tsx
  suite-native/module-device-settings/src/navigation/DeviceAuthenticityStackNavigator.tsx
Labels: mobile, no-project

#22092 chore(suite): cleanup suite storage from unused native files
  packages/suite-storage/README.md
  packages/suite-storage/package.json
  packages/suite-storage/src/index.ts
  packages/suite-storage/src/native/index.ts
Labels: no-project

#22085 chore(suite): remove unused strings
  packages/suite/src/support/messages.ts
Labels: no-project

#21732 chore(transport-bluetooth): remove unused logger
  packages/transport-bluetooth/src/client/trezor-bluetooth.ts
Labels: no-project

#22109 chore(suite-native): decouple autoconnect hook
  suite-native/module-authorize-device/src/screens/thp/ThpConfirmationScreen.tsx
  suite-native/module-device-settings/src/components/DeviceAutoConnectCard.tsx
  suite-native/thp/package.json
  suite-native/thp/src/hooks/useThpAutoconnectActions.tsx
  suite-native/thp/src/hooks/useThpAutoconnectAlerts.tsx
  suite-native/thp/src/index.ts
  suite-native/thp/tsconfig.json
  yarn.lock
Labels: mobile, no-project, THP

#22106 Mobile Trade: Improve error logging in composeTardingTransactionThunk
  suite-native/module-trading/src/thunks.ts
  suite-native/module-trading/src/utils/general/__tests__/utils.test.ts
  suite-native/module-trading/src/utils/general/utils.ts
Labels: mobile, no-project

#22081 chore: optimize storageActions by making isAccessible sync
  packages/suite-storage/src/index.ts
  packages/suite/src/actions/suite/storageActions.ts
Labels: no-project

#22129 fix(connect): only get features after settings/pin change if device i…
  packages/connect/src/device/workflow/trezorPushNotification.ts
Labels: bug

#22133 fix(suite-native): use correct close action type
  suite-native/module-device-settings/src/screens/DeviceAuthenticityScreen.tsx
Labels: mobile

#22142 test(connect): quarantine cancel workflow thp pairing test
  packages/connect/e2e/tests/device/thpPairing.test.ts
Labels: no-project

#22148 Do not allow to click on a loading button
  suite-native/atoms/src/Button/Button.tsx
  suite-native/atoms/src/Button/IconButton.tsx
Labels: mobile

#22152 fix(suite-native): use device connection guard for wipe device
  suite-native/module-device-settings/src/navigation/WipeDeviceStackNavigator.tsx
Labels: mobile

#22112 fix(suite-native): fix QR scan error handling
  suite-native/module-accounts-import/src/useShowImportError.ts
Labels: mobile

#22163 refactor(suite-native): move useDeviceConnectionGuard to module device-authorization
  suite-native/device-authorization/src/hooks/useDeviceConnectionGuard.ts
  suite-native/device-authorization/src/index.ts
  suite-native/module-check-backup/package.json
  suite-native/module-check-backup/src/screens/DeviceCheckBackupTutorialScreen.tsx
  suite-native/module-check-backup/tsconfig.json
  suite-native/module-device-settings/package.json
  suite-native/module-device-settings/src/navigation/DeviceAuthenticityStackNavigator.tsx
  suite-native/module-device-settings/src/navigation/DeviceNameStackNavigator.tsx
  suite-native/module-device-settings/src/navigation/DevicePinProtectionStackNavigator.tsx
  suite-native/module-device-settings/src/navigation/WipeDeviceStackNavigator.tsx
  suite-native/module-device-settings/src/screens/ConfirmFirmwareUpdateScreen.tsx
  suite-native/module-device-settings/src/screens/WipeDeviceContinueOnTrezorScreen.tsx
  suite-native/module-device-settings/tsconfig.json
  yarn.lock
Labels: mobile

#22160 fix(suite-native): getIsDeviceConnectedViaBluetooth
  suite-common/suite-utils/src/__fixtures__/device.ts
  suite-common/suite-utils/src/device.ts
Labels: mobile, no-project

#22174 fix(suite-native): useDeviceConnectionGuard import
  suite-native/module-device-settings/src/screens/AutoConnectSettingsScreen.tsx
Labels: mobile, no-project

#22144 Mitigation for crashes when send precomposed fee level is error
  suite-native/module-send/src/components/SendFeesForm.tsx
  suite-native/module-send/src/hooks/useHandleOnDeviceTransactionReview.tsx
  suite-native/module-trading/src/components/fees/TradingFeesForm.tsx
  suite-native/module-trading/src/thunks.ts
  suite-native/transaction-management/src/hooks/fees/useFeeCalculation.ts
  suite-native/transaction-management/src/hooks/fees/useFeesForm.ts
Labels: send, mobile

#22166 feat(suite-native): show correct screen content when connected device is required
  suite-native/device-authorization/src/hooks/useDeviceConnectionGuard.ts
  suite-native/module-authorize-device/src/navigation/AuthorizeDeviceStackNavigator.tsx
  suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx
  suite-native/module-authorize-device/src/screens/connect/DeviceConnectionGuardScreen.tsx
  suite-native/module-send/src/components/SendFeesForm.tsx
  suite-native/module-send/src/hooks/useShowDeviceDisconnectedAlert.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
Labels: mobile, bluetooth

#22181 feat: revert colour of battery level alert buttons to red
  packages/suite/src/components/suite/modals/LowBatteryModal.tsx
  suite-native/device/src/hooks/useDeviceLowBatteryAlert.tsx
Labels: bluetooth

#22179 fix(suite-native): discovery after killing coin enabling init
  suite-native/device/src/middlewares/deviceConnectionMiddleware.ts
Labels: bug, mobile

#22164 feat(suite-native): do not close app while fw install alert
  suite-native/firmware/src/components/DoNotCloseAppBottomSheetTrigger.tsx
  suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx
  suite-native/intl/src/messages.ts
Labels: mobile

#22214 chore(suite): disable redux immutableCheck
  packages/suite/src/reducers/store.ts
Labels: DX, no-project

#22215 Revert "feat(connect-common): temporarily add 1.13.0 FW"
  packages/connect-common/files/firmware/t1b1/ATTENTION temporarily including 1.13.0 here.txt
  packages/connect-common/files/firmware/t1b1/trezor-t1b1-1.13.0-bitcoinonly.bin
  packages/connect-common/files/firmware/t1b1/trezor-t1b1-1.13.0.bin
Labels: no-project

#22248 Use stable empty array for nearby BLE devices selectors
  suite-native/bluetooth/src/selectors.ts
Labels: mobile, tech, no-project

#22234 feat(suite-native): release connect popup and walletConnect for ios
  suite-native/app/e2e/utils.ts
  suite-native/app/src/initActions.ts
  suite-native/config/src/launch-arguments.ts
  suite-native/feature-flags/src/__tests__/featureFlagsSlice.test.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-connect-popup/package.json
  suite-native/module-connect-popup/src/hooks/useConnectPopupNavigation.ts
  suite-native/module-connect-popup/tsconfig.json
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  suite-native/module-settings/src/components/ConnectionSettings.tsx
  yarn.lock
Labels: connect-popup, mobile, WalletConnect

#22245 chore(suite-native): Mobile Swap: Set enabling featureflags to enabled
  suite-native/module-trading/src/components/exchange/__tests__/ExchangeTab.comp.test.tsx
  suite-native/module-trading/src/screens/__tests__/TradingScreen.comp.test.tsx
  suite-native/module-trading/src/selectors/__tests__/commonSelectors.test.ts
  suite-native/module-trading/src/selectors/commonSelectors.ts
Labels: mobile

#22267 feat(suite-native): update copy to final in mobile swap
  suite-native/intl/src/messages.ts
  suite-native/module-trading/src/components/buy/__tests__/BuyForm.comp.test.tsx
  suite-native/module-trading/src/components/buy/__tests__/BuyTradeableAssetPicker.comp.test.tsx
  suite-native/module-trading/src/components/exchange/ExchangeApprovalLimitSheet/__tests__/ExchangeApprovalLimitSheet.comp.test.tsx
  suite-native/module-trading/src/components/exchange/receive/__tests__/ExchangeReceiveCard.comp.test.tsx
  suite-native/module-trading/src/components/exchange/receive/__tests__/ExchangeTradeableAssetPicker.comp.test.tsx
  suite-native/module-trading/src/components/exchange/send/__tests__/ExchangeSendCard.comp.test.tsx
  suite-native/module-trading/src/components/fees/__tests__/TradingFeesForm.comp.test.tsx
  suite-native/module-trading/src/components/general/__tests__/SelectTradeableAssetButton.comp.test.tsx
  suite-native/module-trading/src/components/sell/__tests__/SellCard.comp.test.tsx
  suite-native/module-trading/src/components/sell/__tests__/SellForm.comp.test.tsx
  suite-native/module-trading/src/screens/TradingExchangeApprovalScreen.tsx
Labels: mobile

#22301 chore: update tenv
  .github/workflows/test-trezor-user-env-link-e2e.yml
  docker/docker-compose.connect-popup-ci.yml
  docker/docker-compose.connect-popup-test.yml
  docker/docker-compose.connect-test.yml
  docker/docker-compose.connect-webextension-test.yml
  docker/docker-compose.suite-ci-e2e.yml
  docker/docker-compose.suite-desktop-ci.yml
  docker/docker-compose.suite-dev.yml
  docker/docker-compose.suite-native-ci.yml
  docker/docker-compose.transport-test-ci.yml
Labels: no-project
