Repository trezor/trezor-suite, pull requests merged in 2025-01, with the labels that each got.

#16123 test(connect): setupEmu does not accept settings
  packages/connect/e2e/common.setup.ts
Labels: no-project

#16133 fix(suite): tests network symbol
  .github/workflows/test-blockchain-link.yml
  packages/blockchain-link/tests/integration/blockbook.test.ts
  packages/blockchain-link/tests/integration/blockfrost.test.ts
  packages/e2e-utils/src/fixtures/blockbook.ts
Labels: bug, e2e

#16143 fix(components): reenable closing modals with ESC
  packages/components/src/components/NewModal/NewModal.tsx
Labels: bug, components

#16142 fix(suite): display symbols
  packages/suite/src/components/suite/modals/ReduxModal/ConfirmAddressModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/ImportTransactionModal/ImportTransactionModal.tsx
  packages/suite/src/components/wallet/TransactionItem/TransactionHeader.tsx
  packages/suite/src/hooks/wallet/coinmarket/useCoinmarketInfo.ts
  packages/suite/src/utils/wallet/coinmarket/coinmarketUtils.ts
  packages/suite/src/utils/wallet/exportTransactionsUtils.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketAddressOptions.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketBalance.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketCryptoAmount.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputAccount.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputFiatCrypto/CoinmarketFormInputCryptoAmount.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputFiatCrypto/CoinmarketFormInputFiatCrypto.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormSwitcherCryptoFiat.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInputs.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormOfferCryptoAmount.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketInfo/CoinmarketInfoHeader.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerify.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerifyOptions.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerifyOptionsItem.tsx
  suite-common/wallet-utils/src/accountUtils.ts
Labels: bug

#16160 fix(coinmarket): fix address validator check
  packages/suite/src/hooks/wallet/coinmarket/useCoinmarketInfo.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketVerify/CoinmarketVerify.tsx
Labels: bug, +Invity

#16103 fix(suite-native): tweak button styles for optical balance
  suite-native/atoms/src/Button/Button.tsx
  suite-native/module-dev-utils/src/screens/DemoScreen.tsx
Labels: mobile

#16177 fix(suite): translations network display symbols
  packages/suite/src/actions/wallet/stake/stakeFormActions.ts
  packages/suite/src/components/suite/FormFractionButtons.tsx
  packages/suite/src/components/suite/StakingProcess/UnstakingInfo.tsx
  packages/suite/src/components/suite/modals/ReduxModal/ConfirmAddressModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/ConfirmXpubModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/StakeEthInANutshellModal/StakeEthInANutshellModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/StakeModal/StakeEthForm/ConfirmStakeEthModal.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/StakeModal/StakeEthForm/Inputs.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/UnstakeModal/EverstakeModal.tsx
  packages/suite/src/components/suite/notifications/NotificationRenderer/NotificationRenderer.tsx
  packages/suite/src/support/messages.ts
  packages/suite/src/views/wallet/receive/components/Header.tsx
  packages/suite/src/views/wallet/staking/components/EthStakingDashboard/components/StakingCard.tsx
  packages/suite/src/views/wallet/transactions/components/AccountEmpty.tsx
  suite-common/wallet-core/src/send/sendFormEthereumThunks.ts
Labels: no-project

#16101 fix(suite-native): tweak coin enabling gradients
  suite-native/coin-enabling/src/components/DiscoveryCoinsFilter.tsx
  suite-native/coin-enabling/src/screens/CoinEnablingInitScreen.tsx
  suite-native/module-settings/src/screens/SettingsCoinEnablingScreen.tsx
Labels: mobile

#16179 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations, no-project

#16122 chore(suite-native): redact more graph error messages
  suite-native/graph/src/hooks.ts
Labels: sentry, mobile

#16183 chore/native/bump-app-to-25.1.1
  suite-native/app/package.json
Labels: mobile

#16187 fix(trade): incorrect api key after changing account in Sell & Swap
  packages/suite/src/middlewares/wallet/coinmarketMiddleware.ts
Labels: bug

#16174 fix(coinmarket): fix sell amount discrepancy
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketSellForm.ts
  packages/suite/src/hooks/wallet/coinmarket/useCoinmarketWatchTrade.ts
  packages/suite/src/types/coinmarket/coinmarketForm.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketOfferSell/CoinmarketOfferSell.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketSelectedOffer/CoinmarketSelectedOffer.tsx
Labels: bug, +Invity

#16191 fix(suite): empty account translation string symbol
  packages/suite/src/views/wallet/transactions/components/AccountEmpty.tsx
Labels: no-project

#16102 fix(suite-native): remove tab bar from settings subscreens
  suite-native/app/src/navigation/AppTabNavigator.tsx
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/app/src/navigation/routes.ts
  suite-native/module-settings/src/components/FeaturesSettings.tsx
  suite-native/module-settings/src/components/PreferencesSettings.tsx
  suite-native/module-settings/src/components/SupportSettings.tsx
  suite-native/module-settings/src/index.ts
  suite-native/module-settings/src/navigation/SettingsStackNavigator.tsx
  suite-native/module-settings/src/navigation/useSettingsNavigateTo.ts
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
Labels: mobile

#16169 fix(mobile): reanimated layout animation in modal crash
  suite-native/atoms/src/Sheet/BottomSheet.tsx
Labels: mobile

#16192 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite/src/support/messages.ts
Labels: translations, no-project

#16184 fix(suite-native): monthly app version bump
  .github/workflows/suite-native-monthly-version-bump.yml
Labels: mobile

#16195 fix(suite): add missing NewModal.Provider to LoggedOutLayout
  packages/suite/src/components/suite/layouts/LoggedOutLayout.tsx
Labels: no-project

#16093 feat(suite): add message system debug info
  packages/suite/src/views/settings/SettingsDebug/MessageSystemDebugInfo.tsx
  packages/suite/src/views/settings/SettingsDebug/SettingsDebug.tsx
Labels: no-project

#16203 chore(ci): add concurency and cancel in prgoress for workflows
  .github/workflows/build-node-bridge.yml
  .github/workflows/build-suite-native-preview.yml
  .github/workflows/build-suite-web.yml
  .github/workflows/check-project-assignment.yml
  .github/workflows/test-connect-misc.yml
  .github/workflows/test-connect-web.yml
  .github/workflows/test-misc.yml
  .github/workflows/test-suite-desktop-e2e.yml
  .github/workflows/test-suite-web-e2e-pw.yml
  .github/workflows/test-suite-web-e2e.yml
  .github/workflows/test-transport.yml
Labels: no-project

#16206 feat(suite-native): tweak receive flow and navigation
  suite-native/app/package.json
  suite-native/app/src/navigation/AppTabNavigator.tsx
  suite-native/app/src/navigation/routes.ts
  suite-native/app/tsconfig.json
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
  suite-native/module-receive/package.json
  suite-native/module-receive/src/index.ts
  suite-native/module-receive/src/navigation/ReceiveStackNavigator.tsx
  suite-native/module-receive/src/screens/ReceiveAccountsScreen.tsx
  suite-native/module-receive/tsconfig.json
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#16207 fix(suite): L2 non native token names
  packages/product-components/src/components/SelectAssetModal/AssetItem.tsx
  packages/suite/src/hooks/wallet/coinmarket/useCoinmarketInfo.ts
Labels: bug

#16090 fix(suite-native): use correct alert colors for the dark theme
  packages/theme/src/colors.ts
  packages/theme/src/palette.ts
Labels: mobile

#16213 chore(suite-native): bump app version to 25.1.2
  suite-native/app/package.json
Labels: mobile

#16025 fix(suite-native): ensure that devices with BTC-only firmware have BTC enabled
  suite-native/app/src/hooks/useCoinEnablingInitialCheck.tsx
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/discovery/src/discoveryMiddleware.ts
Labels: mobile

#16210 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations, no-project

#16218 fix(suite): removed disabled testnet coins from disabled mainnet coins section
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx
Labels: release

#16236 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations, no-project

#16248 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/nl.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations, no-project

#16255 chore(ci): fix autoupdate test release artifact download
  .github/workflows/release-suite-desktop-web-staging.yml
Labels: no-project

#16276 fix(suite-native): e2e view only sheet timeout fixed
  suite-native/app/e2e/pageObjects/alertSheetActions.ts
  suite-native/app/e2e/tests/send.test.ts
Labels: mobile

#16217 fix(suite-native): show fiat balance skeleton while graph is loading
  suite-native/graph/src/components/GraphFiatBalance.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraph.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioHeader.tsx
Labels: mobile

#16235 feat(suite-native): show screen header divider when content is scrolled
  suite-native/coin-enabling/src/screens/CoinEnablingInitScreen.tsx
  suite-native/module-settings/package.json
  suite-native/module-settings/src/screens/SettingsCoinEnablingScreen.tsx
  suite-native/module-settings/tsconfig.json
  suite-native/navigation/package.json
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/src/components/ScreenContentWrapper.tsx
  suite-native/navigation/src/components/TabBar.tsx
  suite-native/navigation/src/index.ts
  suite-native/navigation/src/useScrollDivider.tsx
  suite-native/transactions/src/components/TransactionsList/TransactionList.tsx
  yarn.lock
Labels: mobile

#16300 chore(suite-native): set L2 EVMs disabled on first run
  suite-native/feature-flags/src/featureFlagsSlice.ts
Labels: mobile, EVM

#16303 fix(suite-native): unify look & feel of screen headers
  suite-native/accounts/src/components/SearchableAccountsListHeader.tsx
  suite-native/accounts/src/index.ts
  suite-native/atoms/src/ScreenHeaderWrapper.tsx
  suite-native/device-manager/src/components/DeviceManagerScreenHeader.tsx
  suite-native/module-accounts-management/src/screens/AccountsScreen/AccountsScreen.tsx
  suite-native/module-authorize-device/src/components/connect/ConnectDeviceScreenView.tsx
  suite-native/module-authorize-device/src/components/passphrase/PassphraseContentScreenWrapper.tsx
  suite-native/module-authorize-device/src/components/passphrase/PassphraseScreenHeader.tsx
  suite-native/module-authorize-device/src/components/passphrase/PassphraseScreenWrapper.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseConfirmOnTrezorScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseEnableOnDeviceScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseFeatureUnlockFormScreen.tsx
  suite-native/module-authorize-device/src/screens/passphrase/PassphraseLoadingScreen.tsx
  suite-native/module-device-settings/src/screens/FirmwareUpdateScreen/FirmwareUpdateScreen.tsx
  suite-native/module-send/src/components/SendScreen.tsx
  suite-native/navigation/src/components/ScreenHeader.tsx
  suite-native/navigation/src/index.ts
Labels: mobile

#16274 feat(suite-native): stop hiding Solana behind feature flag
  suite-common/message-system/src/messageSystemTypes.ts
  suite-native/config/src/supportedNetworks.ts
  suite-native/discovery/src/discoveryConfigSlice.ts
  suite-native/discovery/src/discoverySelectors.ts
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
Labels: mobile, message-system

#16269 feat(mobile): make feature flags more dummy proof
  suite-native/accounts/src/components/AddAccountsButton.tsx
  suite-native/device-manager/src/components/DeviceManager.tsx
  suite-native/feature-flags/src/index.ts
  suite-native/feature-flags/src/useFeatureFlag.tsx
  suite-native/feature-flags/src/useToggleFeatureFlag.ts
  suite-native/module-accounts-import/src/screens/AccountImportSummaryScreen.tsx
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
  suite-native/module-connect-popup/src/hooks/useConnectPopupNavigation.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  suite-native/module-device-settings/src/components/DeviceFirmwareCard.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyHomeRenderer.tsx
  suite-native/module-onboarding/src/components/OnboardingScreenHeader.tsx
  suite-native/module-onboarding/src/screens/FeatureReceiveScreen.tsx
  suite-native/module-onboarding/src/screens/TrackBalancesScreen.tsx
  suite-native/module-onboarding/src/screens/WelcomeScreen.tsx
  suite-native/module-settings/src/components/FAQInfoPanel.tsx
  suite-native/module-settings/src/components/FeaturesSettings.tsx
Labels: mobile

#16321 feat(suite-native): Improve colors in account label hint
  suite-native/accounts/src/components/AccountLabelFieldHint.tsx
  suite-native/accounts/src/hooks/useAccountLabelForm.ts
Labels: mobile

#16329 fix(suite-native): align toasts vertically with the close icon
  suite-native/toasts/package.json
  suite-native/toasts/src/components/ToastRenderer.tsx
  suite-native/toasts/tsconfig.json
  yarn.lock
Labels: mobile

#16307 feat(suite-native): slightly better contrast for default switch background
  suite-native/atoms/src/Switch.tsx
Labels: mobile

#16326 fix(suite-desktop-core): app isHidden check is mac only
  packages/suite-desktop-core/src/app.ts
Labels: build-desktop

#16331 feat(suite-native): android edge to edge screen background
  scripts/list-outdated-dependencies/mobile-dependencies.txt
  suite-native/app/app.config.ts
  suite-native/app/package.json
  suite-native/navigation/package.json
  suite-native/navigation/src/components/Screen.tsx
  yarn.lock
Labels: mobile

#16277 fix(product-components): automatic focus in search input
  packages/product-components/src/components/SelectAssetModal/SearchAsset.tsx
Labels: bug, components

#16330 chore(ci): run web and desktop e2e test on release branch pushes
  .github/workflows/test-suite-desktop-e2e.yml
  .github/workflows/test-suite-web-e2e-pw.yml
Labels: no-project

#16347 fix(mobile): update and patch reanimated to fix crash
  patches/react-native-reanimated+3.16.7.patch
  suite-native/accounts/package.json
  suite-native/alerts/package.json
  suite-native/app/package.json
  suite-native/assets/package.json
  suite-native/atoms/package.json
  suite-native/coin-enabling/package.json
  suite-native/device-manager/package.json
  suite-native/device/package.json
  suite-native/firmware/package.json
  suite-native/graph/package.json
  suite-native/icons/package.json
  suite-native/message-system/package.json
  suite-native/module-accounts-import/package.json
  suite-native/module-authorize-device/package.json
  suite-native/module-send/package.json
  suite-native/navigation/package.json
  suite-native/notifications/package.json
  suite-native/react-native-graph/package.json
  suite-native/receive/package.json
  suite-native/toasts/package.json
  suite-native/transactions/package.json
  suite-native/video-assets/package.json
  yarn.lock
Labels: mobile

#16384 fix(connect): remove account.addresses from cardanoComposeTransaction
  packages/connect-explorer/src/pages/methods/cardano/cardanoComposeTransaction.mdx
  packages/connect/src/types/api/cardanoComposeTransaction.ts
  packages/suite/src/hooks/wallet/useCardanoStaking.ts
  suite-common/wallet-core/src/send/sendFormCardanoThunks.ts
Labels: connect, no-project

#16312 fix(suite-native): use correct receive flow screens for connected device
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AccountsList/AccountsList.tsx
  suite-native/accounts/src/components/AddAccountsButton.tsx
  suite-native/accounts/src/components/SearchableAccountsListHeader.tsx
  suite-native/accounts/tsconfig.json
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/atoms/src/Button/IconButton.tsx
  suite-native/intl/src/en.ts
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
  suite-native/module-add-accounts/src/screens/AddCoinAccountScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/receive/package.json
  suite-native/receive/src/components/ReceiveScreenHeader.tsx
  suite-native/receive/src/index.ts
  suite-native/receive/src/navigation/ReceiveStackNavigator.tsx
  suite-native/receive/src/screens/ReceiveAccountScreen.tsx
  suite-native/receive/src/screens/ReceiveAccountsScreen.tsx
  suite-native/receive/src/screens/ReceiveModalScreen.tsx
  yarn.lock
Labels: mobile

#16334 feat(mobile): nicer animation for discovery loader
  suite-native/assets/src/components/Assets.tsx
  suite-native/assets/src/components/DiscoveryAssetsLoader.tsx
  suite-native/atoms/src/Card/Card.tsx
Labels: mobile

#15387 ci(connect): test model one
  .github/workflows/test-connect.yml
  packages/connect/e2e/run.ts
  packages/connect/e2e/tests/device/cancel.test.ts
Labels: no-project

#16369 feat(graph): get graph events from txn history for arb, base, op
  suite-common/graph/src/balanceHistoryUtils.ts
  suite-common/graph/src/constants.ts
Labels: mobile, EVM, no-project

#16391 fix(suite-native): android button navigation bar colors
  scripts/list-outdated-dependencies/mobile-dependencies.txt
  suite-native/navigation/package.json
  suite-native/navigation/src/components/Screen.tsx
  yarn.lock
Labels: mobile

#16406 chore(connect): remove commented out fixtures for decred multisig
  packages/connect/e2e/__fixtures__/signTransactionDecred.ts
Labels: no-project

#16413 chore(suite): temporarily disable node bridge in eap
  packages/suite-desktop-core/src/modules/bridge.ts
Labels: cherry-pick🍒

#16414 fix(connect): solana transaction decode
  packages/connect/src/api/solana/solanaUtils.ts
Labels: connect, solana, build-desktop

#16404 chore(suite-common): rename formatter to more appropriate name
  suite-common/formatters/src/FormatterProvider.tsx
  suite-common/formatters/src/formatters/prepareCryptoAmountFormatter.ts
  suite-common/formatters/src/formatters/prepareDisplaySymbolFormatter.ts
  suite-common/formatters/src/formatters/tests/prepareDisplaySymbolFormatter.test.ts
  suite-native/accounts/src/components/SelectableNetworkItem.tsx
  suite-native/module-send/src/components/CryptoAmountInput.tsx
Labels: mobile, no-project

#16424 chore(suite-native): move SettingsSection to settings
  suite-native/module-settings/src/components/FeaturesSettings.tsx
  suite-native/module-settings/src/components/PreferencesSettings.tsx
  suite-native/module-settings/src/components/SupportSettings.tsx
  suite-native/module-settings/src/screens/SettingsAboutUsScreen.tsx
  suite-native/settings/package.json
  suite-native/settings/src/components/SettingsSection.tsx
  suite-native/settings/src/components/SettingsSectionItem.tsx
  suite-native/settings/src/components/SettingsSectionItemIcon.tsx
  suite-native/settings/src/components/SettingsSectionItemText.tsx
  suite-native/settings/src/index.ts
  suite-native/settings/tsconfig.json
  yarn.lock
Labels: mobile, no-project

#16318 feat(mobile): update FW alert on Home + remote feature flag
  suite-common/message-system/src/messageSystemTypes.ts
  suite-native/atoms/src/Stack.tsx
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/firmware/package.json
  suite-native/firmware/src/hooks/useIsFirmwareUpdateFeatureEnabled.tsx
  suite-native/firmware/src/index.ts
  suite-native/firmware/tsconfig.json
  suite-native/intl/src/en.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
  suite-native/module-device-settings/src/components/DeviceFirmwareCard.tsx
  suite-native/module-device-settings/src/screens/FirmwareUpdateScreen/FirmwareUpdateScreen.tsx
  suite-native/module-home/package.json
  suite-native/module-home/src/screens/HomeScreen/components/FirmwareUpdateAlert.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
  yarn.lock
Labels: mobile

#16387 chore(suite-native): introduce component tests
  jest.config.native.js
  suite-native/accounts/package.json
  suite-native/accounts/src/components/AccountLabelFieldHint.tsx
  suite-native/accounts/src/components/__tests__/AccountLabelFieldHint.comp.test.tsx
  suite-native/accounts/tsconfig.json
  suite-native/atoms/package.json
  suite-native/atoms/src/Card/__tests__/Card.comp.test.tsx
  suite-native/atoms/tsconfig.json
  suite-native/test-utils/package.json
  suite-native/test-utils/src/Provider.tsx
  suite-native/test-utils/src/index.ts
  suite-native/test-utils/src/index.tsx
  yarn.lock
Labels: mobile, no-project

#16420 feat(suite-native): add dev addresses to account import for testing altcoins
  suite-native/module-accounts-import/src/components/DevXpub.tsx
Labels: mobile, no-project

#16317 feat(mobile): upgrade FW report to analytics
  suite-native/analytics/src/constants.ts
  suite-native/analytics/src/events.ts
  suite-native/analytics/src/types.ts
  suite-native/firmware/src/components/MayBeStuckedBottomSheet.tsx
  suite-native/firmware/src/hooks/useFirmware.tsx
  suite-native/firmware/src/hooks/useFirmwareAnalytics.ts
  suite-native/firmware/src/screens/FirmwareUpdateInProgressScreen.tsx
Labels: mobile

#16453 fix(trade): delete limits after change currency
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormInput/CoinmarketFormInputCryptoSelect.tsx
Labels: bug, +Invity

#16458 hide solana staking
  suite-native/accounts/src/components/AccountSectionTitle.tsx
  suite-native/accounts/src/selectors.ts
  suite-native/assets/src/assetsSelectors.ts
Labels: mobile, solana

#16464 fix(suite-native): navigate to the initial screen after a coin is removed
  suite-native/module-accounts-management/src/components/AccountSettingsRemoveCoinButton.tsx
Labels: mobile

#16450 fix(trade): unnecessary requesting in buy/sell/swap
  packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketInitializer.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketBuyForm.tsx
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketSellForm.ts
  packages/suite/src/types/coinmarket/coinmarket.ts
Labels: bug, +Invity

#16467 fix(suite-native): connect popup use selected device
  suite-native/module-connect-popup/src/screens/ConnectPopupScreen.tsx
Labels: connect, connect-popup, mobile

#16455 feat(icons): add code icon to native, regenerate
  suite-common/icons/cryptoAssets/cryptoIcons/arb.svg
  suite-common/icons/generateIconFont.ts
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.json
  suite-common/icons/iconFontsMobile/TrezorSuiteIcons.ttf
  suite-native/app/app.config.ts
Labels: mobile, no-project

#16449 fix(suite-native): unify receive flow navigation for all use cases
  suite-native/accounts/src/components/AccountsList/AccountsListEmptyPlaceholder.tsx
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/module-accounts-management/src/components/TransactionListHeader.tsx
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
  suite-native/module-device-settings/src/components/DeviceInteractionScreenWrapper.tsx
  suite-native/navigation/src/components/GoBackIcon.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  suite-native/receive/package.json
  suite-native/receive/src/components/ReceiveScreenHeader.tsx
  suite-native/receive/src/index.ts
  suite-native/receive/src/navigation/ReceiveStackNavigator.tsx
  suite-native/receive/src/screens/ReceiveAccountScreen.tsx
  suite-native/receive/src/screens/ReceiveAccountsScreen.tsx
  suite-native/receive/src/screens/ReceiveAddressScreen.tsx
  suite-native/receive/src/screens/ReceiveModalScreen.tsx
  suite-native/receive/tsconfig.json
  suite-native/transactions/src/components/TransactionsEmptyState.tsx
  yarn.lock
Labels: mobile

#16473 feat(suite-native): hide firmware update alert for January releases
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioContent.tsx
Labels: mobile

#16475 fix(suite-desktop-core): connect popup process detection on windows
  packages/suite-desktop-core/src/libs/find-process-from-port.ts
Labels: connect, no-project

#16482 fix(suite-native): android navigation bar color on switching apps
  packages/styles/src/index.ts
  suite-native/navigation/src/components/Screen.tsx
  suite-native/navigation/src/hooks/useAndroidNavigationBarStyle.tsx
Labels: mobile

#16436 fix(trade): display DEX quotes
  packages/suite/src/hooks/wallet/coinmarket/form/common/useCoinmarketExchangeQuotesFilter.ts
  packages/suite/src/hooks/wallet/coinmarket/form/useCoinmarketExchangeForm.ts
  packages/suite/src/types/coinmarket/coinmarketForm.ts
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormOffer.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketForm/CoinmarketFormOffersSwitcher.tsx
  packages/suite/src/views/wallet/coinmarket/common/CoinmarketOffers/CoinmarketOffersExchange.tsx
Labels: bug, +Invity

#16479 chore(connect): simplify transportInfo
  packages/connect-common/files/bridge/releases.json
  packages/connect/src/data/DataManager.ts
  packages/connect/src/data/__tests__/transportInfo.test.ts
  packages/connect/src/data/transportInfo.ts
  packages/connect/src/data/udevInfo.ts
  packages/connect/src/events/transport.ts
  packages/connect/src/utils/assetUtils.ts
Labels: no-project

#16490 fix(suite-native): hide fw update for not backed up devices
  packages/suite/src/components/firmware/CheckSeedStep/CheckSeedStep.tsx
  suite-common/wallet-core/src/device/deviceReducer.ts
  suite-native/module-device-settings/src/components/DeviceFirmwareCard.tsx
Labels: mobile

#16457 fix(mobile): balance mismatch
  suite-common/graph/src/types.ts
  suite-native/accounts/src/selectors.ts
  suite-native/device/src/selectors.ts
  suite-native/graph/src/components/Graph.tsx
  suite-native/graph/src/components/GraphDateFormatter.tsx
  suite-native/graph/src/components/GraphFiatBalance.tsx
  suite-native/graph/src/hooks.ts
  suite-native/module-accounts-management/src/accountDetailGraphAtoms.ts
  suite-native/module-accounts-management/src/components/AccountDetailGraph.tsx
  suite-native/module-accounts-management/src/components/AccountDetailHeader.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioGraph.tsx
  suite-native/module-home/src/screens/HomeScreen/components/PortfolioHeader.tsx
  suite-native/module-home/src/screens/HomeScreen/portfolioGraphAtoms.ts
Labels: mobile

#16498 fix(suite-native): do not warn about bootloader and uninitialized device while FW update is running
  suite-native/device/src/hooks/useDetectDeviceError.tsx
Labels: mobile

#16500 fix(suite-native): firmware update is hidden for disconnected devices
  suite-native/module-device-settings/src/components/DeviceFirmwareCard.tsx
Labels: mobile

#16507 feat(suite-native): hide balance if discovery is still loading so it's not final
  suite-native/graph/src/components/GraphFiatBalance.tsx
Labels: mobile

#16511 chore(suite-native): bump suite-native version to 25.1.3
  suite-native/app/package.json
Labels: mobile, no-project

#16491 feat(suite-native): onboarding biometrics screen
  suite-native/biometrics/src/useBiometricsSettings.ts
  suite-native/intl/src/en.ts
  suite-native/module-home/src/screens/HomeScreen/useShowBiometricsAlert.tsx
  suite-native/module-onboarding/package.json
  suite-native/module-onboarding/src/navigation/OnboardingStackNavigator.tsx
  suite-native/module-onboarding/src/screens/AnalyticsConsentScreen.tsx
  suite-native/module-onboarding/src/screens/BiometricsScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
  yarn.lock
Labels: mobile

#16519 fix(suite-native): navigate to receive address screen after account is added
  suite-native/module-add-accounts/src/hooks/useAddCoinAccount.ts
Labels: mobile

#16529 fix(suite-native): empty homescreen paddings
  suite-native/module-home/src/screens/HomeScreen/HomeScreen.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyConnectedDeviceState.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyHomeRenderer.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyPortfolioCrossroads.tsx
  suite-native/module-home/src/screens/HomeScreen/components/EmptyPortfolioTrackerState.tsx
Labels: mobile

#16542 feat(suite-native): device onboarding feature flag
  suite-native/feature-flags/src/featureFlagsSlice.ts
  suite-native/module-dev-utils/src/components/FeatureFlags.tsx
Labels: mobile

#16478 fix(suite-native): prohibit swiping back from authorize device screens
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/coin-enabling/src/screens/CoinEnablingInitScreen.tsx
  suite-native/module-accounts-import/src/screens/AccountImportLoadingScreen.tsx
  suite-native/module-accounts-import/src/screens/AccountImportSummaryScreen.tsx
  suite-native/module-authorize-device/src/components/connect/ConnectDeviceScreenHeader.tsx
  suite-native/module-authorize-device/src/components/passphrase/PassphraseScreenHeader.tsx
  suite-native/module-authorize-device/src/navigation/AuthorizeDeviceStackNavigator.tsx
  suite-native/module-authorize-device/src/screens/connect/ConnectingDeviceScreen.tsx
  suite-native/navigation/src/index.ts
  suite-native/navigation/src/useHandleHardwareBackNavigation.ts
Labels: mobile

#16589 ci(scripts): add no-project label to connect-data pr
  scripts/ci/check-connect-data.ts
Labels: no-project

#16598 chore(suite): remove unused unstake fee component
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/UnstakeModal/UnstakeEthForm/Fees.tsx
Labels: no-project

#16592 refactor(suite/components): improve typing and performance of the VirtualizedList
  packages/components/jest.config.js
  packages/components/jest.setup.js
  packages/components/package.json
  packages/components/src/components/VirtualizedList/VirtualizedList.tsx
  packages/components/src/components/VirtualizedList/__tests__/VirtualizedList.test.tsx
  packages/product-components/src/components/SelectAssetModal/SelectAssetModal.tsx
  scripts/list-outdated-dependencies/common-dependencies.txt
  scripts/list-outdated-dependencies/qa-dependencies.txt
  yarn.lock
Labels: chore

#16614 fix: Wait for token definitions in import
  suite-native/module-accounts-import/src/accountsImportThunks.ts
Labels: mobile

#16618 chore(connect): cleanup unused types
  packages/connect/src/device/Device.ts
Labels: no-project

#16607 Add SafeAreaProvider to BasicProvider for component tests
  suite-native/test-utils/package.json
  suite-native/test-utils/src/BasicProvider.tsx
  suite-native/test-utils/src/expoMock.js
  yarn.lock
Labels: mobile, no-project

#16632 feat(suite-common): Introduce UnreachableCaseError helper
  suite-common/suite-utils/src/UnreachableCaseError.ts
Labels: mobile, DX, no-project

#16655 fix(suite-common): Export UnreachableCaseError from suite-utils
  suite-common/suite-utils/src/index.ts
Labels: mobile, DX, no-project

#16578 chore(monorepo): update deps responsibilities
  scripts/list-outdated-dependencies/connect-dependencies.txt
  scripts/list-outdated-dependencies/usability-dependencies.txt
Labels: no-project

#16662 fix(suite): env utils mock in Preloader unit test
  packages/suite/src/components/suite/Preloader/__tests__/Preloader.test.tsx
Labels: no-project

#16608 fix(suite-native): use linear gradient in screen footers with buttons
  suite-native/coin-enabling/package.json
  suite-native/coin-enabling/src/screens/CoinEnablingInitScreen.tsx
  suite-native/coin-enabling/tsconfig.json
  suite-native/module-accounts-import/src/components/AccountImportSummaryScreen.tsx
  suite-native/module-device-settings/src/screens/FirmwareUpdateScreen/FirmwareUpdateScreen.tsx
  suite-native/module-send/src/screens/SendOutputsScreen.tsx
  suite-native/navigation/package.json
  suite-native/navigation/src/components/ScreenFooterGradient.tsx
  suite-native/navigation/src/index.ts
  yarn.lock
Labels: mobile

#16613 feat(suite-native): Create generic picker header component
  suite-native/module-trading/src/components/general/PickerCloseButton.tsx
  suite-native/module-trading/src/components/general/PickerHeader.tsx
  suite-native/module-trading/src/components/general/__tests__/PickerHeader.comp.test.tsx
Labels: mobile, no-project

#16674 ci: add workflow_dispatch for build-suite-web
  .github/workflows/build-suite-web.yml
Labels: ci, DX, no-project

#16677 Improve `scheduleAction` stack trace
  packages/utils/src/scheduleAction.ts
Labels: no-project

#16008 feat(ci): upload apk to data.trezor.io for mobile release
  .github/workflows/release-suite-native-production.yml
Labels: no-project

#16680 fix(blockchain-link): stop ripple ping timeout if api disconnected
  packages/blockchain-link/src/workers/baseWorker.ts
  packages/blockchain-link/src/workers/ripple/index.ts
Labels: no-project

#16714 Remove @suite-native/icons jest mock
  jest.config.native.js
  suite-native/test-utils/src/atomsMock.js
Labels: mobile, no-project

#16663 Crowdin translations update
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#16730 Crowdin translations update
  packages/suite-data/files/translations/cs.json
  packages/suite-data/files/translations/de.json
  packages/suite-data/files/translations/en.json
  packages/suite-data/files/translations/es.json
  packages/suite-data/files/translations/fr.json
  packages/suite-data/files/translations/hu.json
  packages/suite-data/files/translations/it.json
  packages/suite-data/files/translations/ja.json
  packages/suite-data/files/translations/lol.json
  packages/suite-data/files/translations/pt.json
  packages/suite-data/files/translations/ro.json
  packages/suite-data/files/translations/ru.json
  packages/suite-data/files/translations/sk.json
  packages/suite-data/files/translations/tr.json
  packages/suite-data/files/translations/uk.json
  packages/suite-data/files/translations/zh.json
  packages/suite/src/support/messages.ts
Labels: translations

#16700 test(blockchain-link): use JestCustomEnv.js to detect exceeding liste…
  packages/blockchain-link/jest.config.unit.js
Labels: no-project

#16750 chore(eslint): ignore all libESM dirs
  packages/eslint/src/index.mjs
Labels: DX, no-project
