Repository trezor/trezor-suite, pull requests merged in 2025-09, with the labels that each got.

#21126 ci(suite-native): notify about nightly e2e failure
  .github/workflows/template-suite-native-e2e-android.yml
  .github/workflows/test-suite-native-e2e-android-t3w1.yml
  .github/workflows/test-suite-native-e2e-android.yml
Labels: e2e, ci, mobile, no-project

#21172 fix(product-components): react error passsing key as prop
  packages/product-components/src/components/DeviceAnimation/DeviceAnimation.tsx
  packages/product-components/src/components/DeviceAnimation/Video.tsx
Labels: no-project

#21218 fix(suite-desktop-core): ignore missing connect process info for linux
  packages/suite-desktop-core/src/libs/connect-ws.ts
Labels: build-desktop

#20987 feat(suite): allow adding the next account (sequential indices)
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountButton/AddAccountButton.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx
  suite-common/wallet-utils/src/accountUtils.ts
Labels: release

#21196 fix(suite-native): fix onboarding layout
  suite-native/atoms/src/SwipeableWalkthrough/SwipeableWalkthroughStep.tsx
  suite-native/module-check-backup/src/components/CheckBackupTutorialStep.tsx
Labels: mobile

#21230 ci(suite-native): fix e2e fail notification
  .github/workflows/template-suite-native-e2e-android.yml
Labels: ci, mobile, no-project

#21110 Suite - MEV Protection
  packages/blockchain-link-types/src/blockbook-api.ts
  packages/blockchain-link-types/src/blockbook.ts
  packages/blockchain-link-types/src/messages.ts
  packages/blockchain-link/src/ui/index.ui.ts
  packages/blockchain-link/src/workers/blockbook/index.ts
  packages/blockchain-link/src/workers/blockbook/websocket.ts
  packages/blockchain-link/src/workers/blockfrost/index.ts
  packages/blockchain-link/src/workers/electrum/methods/pushTransaction.ts
  packages/blockchain-link/src/workers/ripple/index.ts
  packages/blockchain-link/src/workers/solana/index.ts
  packages/blockchain-link/src/workers/stellar/index.ts
  packages/blockchain-link/tests/integration/stellar.test.ts
  packages/blockchain-link/tests/unit/pushTransaction.test.ts
  packages/connect/src/api/pushTransaction.ts
  packages/connect/src/backend/Blockchain.ts
  packages/connect/src/types/api/pushTransaction.ts
  packages/suite/src/actions/wallet/stakeActions.ts
  packages/suite/src/constants/suite/anchors.ts
  packages/suite/src/middlewares/wallet/storageMiddleware.ts
  packages/suite/src/storage/CHANGELOG.md
  packages/suite/src/support/messages.ts
  packages/suite/src/views/settings/SettingsGeneral/MevProtection.tsx
  packages/suite/src/views/settings/SettingsGeneral/SettingsGeneral.tsx
  suite-common/message-system/src/messageSystemTypes.ts
  suite-common/wallet-config/src/networksConfig.ts
  suite-common/wallet-config/src/types.ts
  suite-common/wallet-core/src/send/sendFormThunks.ts
  suite-common/wallet-core/src/settings/walletSettingsActions.ts
  suite-common/wallet-core/src/settings/walletSettingsConstants.ts
  suite-common/wallet-core/src/settings/walletSettingsReducer.ts
  suite-common/wallet-types/src/settings.ts
  suite-common/wallet-utils/src/__tests__/accountUtils.test.ts
  suite-common/wallet-utils/src/sendFormUtils.ts
  suite-common/walletconnect/src/adapters/ethereum.ts
Labels: release

#21235 fix(suite-native): fix useHandleHardwareBackNavigation
  suite-native/navigation/src/useHandleHardwareBackNavigation.ts
Labels: mobile, no-project

#21241 chore(suite-native): remove unused maestro config
  suite-native/app/.maestro/generateBTCAddress.yaml
  suite-native/app/.maestro/importBTCAsset.yaml
  suite-native/app/.maestro/importExistingBTCAsset.yaml
  suite-native/app/.maestro/importTwoBTCAssets.yaml
  suite-native/app/.maestro/subflows/finishCoinSyncAndMoveToPortfolio.yaml
  suite-native/app/.maestro/subflows/importNetworkByText.yaml
  suite-native/app/.maestro/subflows/onboarding.yaml
Labels: mobile, no-project

#21247 fix(suite-native): no bottom padding/insets on THP confirmation screens
  suite-native/module-authorize-device/src/screens/thp/ThpConfirmationScreen.tsx
  suite-native/module-device-onboarding/src/screens/ThpConfirmationScreen.tsx
  suite-native/module-device-settings/src/screens/ThpConfirmationScreen.tsx
Labels: mobile

#21233 fix(connect): thpCall error handling
  packages/connect/src/constants/errors.ts
  packages/connect/src/device/DeviceCurrentSession.ts
  packages/connect/src/device/thp/thpCall.ts
Labels: connect

#21102 feat(suite): show only real nearBy devices in BT list
  packages/suite/src/components/connection/ConnectDeviceGlobalModal.tsx
Labels: no-project

#21195 feat(suite-native): replace crypto with bitcoin in Bitcoin-only firmware
  suite-native/device/src/hooks/useCoinLabel.ts
  suite-native/device/src/index.ts
  suite-native/intl/src/en.ts
  suite-native/module-device-onboarding/src/screens/UninitializedDeviceLandingScreen.tsx
  suite-native/module-settings/src/components/AboutUsBanners.tsx
  suite-native/module-settings/src/components/FAQInfoPanel.tsx
  suite-native/module-trading/src/components/general/AccountList/AccountListBaseItem.tsx
  suite-native/module-trading/src/components/general/ProviderSheet/DexSectionHeader.tsx
  suite-native/module-trading/src/components/general/ProviderSheet/__tests__/ProviderSheetSectionHeader.comp.test.tsx
  suite-native/module-trading/src/components/history/TradeStatusBadge.tsx
  suite-native/module-trading/src/components/history/__tests__/TradeStatusBadge.comp.test.tsx
Labels: mobile

#21264 chore(suite): inline cardano patch in connectInitThunks
  suite-common/connect-init/src/cardanoConnectPatch.ts
  suite-common/connect-init/src/connectInitThunks.ts
Labels: no-project

#21161 test(connect): use only local firmware release config
  packages/connect/src/core/__tests__/onCallFirmwareUpdate.test.ts
  packages/connect/src/data/__tests__/DataManager.test.ts
  packages/connect/src/data/__tests__/firmwareInfo.test.ts
  packages/connect/src/device/__tests__/DeviceList.test.ts
  packages/connect/src/device/__tests__/handshakeWorkflow.test.ts
Labels: no-project

#21306 chore(suite-native): mmkv - enable flexible page size support
  patches/react-native-mmkv + 2.12.2.patch
Labels: mobile

#21298 fix(suite): prevent passphrase prompt on standard wallets when adding empty accounts
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/AddAccountModal/AddAccountModal.tsx
  suite-common/wallet-utils/src/accountUtils.ts
Labels: release

#21346 feat(suite-native): Mobile Swap: set swapSlippage on quoteSelect
  suite-native/module-trading/src/hooks/exchange/__tests__/useExchangeSelectQuote.test.ts
  suite-native/module-trading/src/hooks/exchange/useExchangeSelectQuote.ts
Labels: mobile

#21135 feat(transport-bluetooth): server connect_device and disconnect_device methods
  packages/transport-bluetooth/src/server/device.rs
  packages/transport-bluetooth/src/server/message_handler.rs
  packages/transport-bluetooth/src/server/methods/connect_device.rs
  packages/transport-bluetooth/src/server/methods/disconnect_device.rs
  packages/transport-bluetooth/src/server/methods/mod.rs
  packages/transport-bluetooth/src/server/platform/linux.rs
  packages/transport-bluetooth/src/server/platform/macos.rs
  packages/transport-bluetooth/src/server/platform/mod.rs
  packages/transport-bluetooth/src/server/platform/windows.rs
  packages/transport-bluetooth/src/server/types.rs
  packages/transport-bluetooth/src/server/utils.rs
Labels: cherry-pick🍒

#21367 fix(suite-native): replace navigation popTo with reset to prevent app crash
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
Labels: mobile, THP

#21349 fix(connect): current release for only remote fws
  packages/connect/src/device/Device.ts
Labels: no-project, cherry-pick🍒

#21384 chore(suite-native): thp confirmation redirect in middleware
  suite-common/thp/package.json
  suite-common/thp/src/index.ts
  suite-common/thp/src/thpUtils.ts
  suite-native/device/src/hooks/useHandleDeviceConnection.ts
  suite-native/device/src/middlewares/deviceConnectionMiddleware.ts
  yarn.lock
Labels: mobile, no-project

#21385 feat(suite-native): reorganize contents of Bluetooth device card
  suite-native/bluetooth/src/components/BluetoothDeviceCard.tsx
Labels: mobile, bluetooth

#21320 fix(suite): Show base currency amount even for bitcoin base currency
  packages/suite/src/views/wallet/send/Outputs/Amount/Amount.tsx
Labels: send, low hanging fruit, bitcoin

#21409 fix(suite-native): revert Mobile Swap: use lowercase token cryptoId
  suite-common/trading/src/__tests__/utils.test.ts
  suite-common/trading/src/utils.ts
Labels: no-project

#21476 chore(suite): hide MEV settings when no supported coins are enabled
  packages/suite/src/views/settings/SettingsGeneral/SettingsGeneral.tsx
  suite-common/wallet-core/src/settings/walletSettingsReducer.ts
  suite-native/module-settings/src/screens/SettingsDeviceChecksScreen.tsx
Labels: cherry-pick🍒

#21527 fix(suite): staking and unstaking times
  packages/suite/src/components/suite/StakingProcess/StakingInfo.tsx
  packages/suite/src/components/suite/StakingProcess/UnstakingInfo.tsx
  packages/suite/src/components/suite/modals/ReduxModal/UserContextModal/UnstakeModal/UnstakeForm/UnstakeForm.tsx
  packages/suite/src/views/wallet/staking/components/StakingDashboard/hooks/useProgressLabelsData.tsx
  suite-common/staking/src/__fixtures__/ethereumStaking.ts
  suite-common/staking/src/utils/ethereumStaking.ts
Labels: cherry-pick🍒

#21568 fix(suite-native): wipe thp device navigation
  suite-native/module-device-settings/src/navigation/WipeDeviceStackNavigator.tsx
  suite-native/module-device-settings/src/screens/WipeDeviceContinueOnTrezorScreen.tsx
Labels: mobile, THP

#21564 fix(suite-native): navigation reactivity on entropy check failure
  suite-native/device/src/deviceThunks.ts
Labels: mobile, release-native, cherry-pick🍒

#21571 feat(suite-native): coinEnablingInit in authorize stack
  suite-native/app/src/navigation/RootStackNavigator.tsx
  suite-native/coin-enabling/src/screens/CoinEnablingInitScreen.tsx
  suite-native/device/src/middlewares/deviceConnectionMiddleware.ts
  suite-native/module-authenticity-checks/src/components/FirmwareAuthenticityCheckFailModalContent.tsx
  suite-native/module-authorize-device/src/navigation/AuthorizeDeviceStackNavigator.tsx
  suite-native/module-device-onboarding/src/screens/CreatePinScreen.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/navigation/src/routes.ts
Labels: mobile, no-project

#21589 feat(suite-native): change size and colour of the Connect via Bluetooth button
  suite-native/device/src/components/ConnectAndUnlockDeviceScreenContent.tsx
  suite-native/device/src/components/TurnOnAndUnlockDeviceScreenContent.tsx
Labels: mobile

#21602 fix: missing depchecks in packages CR suggestion
  packages/urls/tests/urls.test.ts
Labels: no-project

#21605 fix(suite-native): use 0 decimals for sats value to fix the conversion
  suite-native/module-send/src/components/FiatAmountInput.tsx
Labels: mobile

#21630 fix(fiat-services): merge headers for native fetch
  suite-common/fiat-services/src/fetch.native.ts
  suite-common/fiat-services/tests/fetch.native.test.ts
Labels: mobile, cherry-pick🍒

#21503 fix(suite-native): fix button padding on FW installation screen
  suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx
Labels: mobile

#21287 Dev util to select message system config source also on mobile
  suite-common/message-system/src/messageSystemReducer.ts
  suite-native/module-dev-utils/src/components/MessageSystemConfigSourceSelect.tsx
  suite-native/module-dev-utils/src/components/MessageSystemInfo.tsx
Labels: mobile, no-project

#21665 fix(e2e): remove tada out of coins.test.ts
  packages/suite-desktop-core/e2e/tests/settings/coins.test.ts
Labels: no-project

#21670 feat(suite-native): prompt users to enable Location Services on old Androids
  packages/transport-native-bluetooth/src/api/bluetoothManager.ts
  packages/transport-native-bluetooth/src/index.ts
  suite-native/bluetooth/src/hooks/useBluetoothAlerts.ts
  suite-native/bluetooth/src/hooks/useBluetoothManager.ts
  suite-native/bluetooth/src/hooks/useBluetoothSettings.ts
  suite-native/intl/src/messages.ts
Labels: mobile, bluetooth

#21672 feat(suite-native): use blank screen renders in device onboarding
  suite-native/module-device-onboarding/src/assets/t2t1.webp
  suite-native/module-device-onboarding/src/assets/t3b1.webp
  suite-native/module-device-onboarding/src/assets/t3t1.webp
Labels: mobile

#21496 fix(suite-native): show select backup type only if the device is not nitialized
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep5.tsx
  suite-native/module-device-onboarding/src/components/WalletBackupTutorial/WalletBackupTutorialStep6.tsx
  suite-native/module-device-onboarding/src/screens/WalletBackupTutorialScreen.tsx
Labels: mobile

#21353 ci(suite-native): crowdin translations tooling
  .github/workflows/bot-crowdin-sync.yml
  suite-native/intl/.gitignore
  suite-native/intl/crowdin.yml
  suite-native/intl/package.json
  suite-native/intl/scripts/backportEnglish.ts
  suite-native/intl/scripts/extractTranslations.ts
  suite-native/intl/src/__tests__/utils.test.ts
  suite-native/intl/src/hooks/useTranslatedMessages.ts
  suite-native/intl/src/messages.ts
  suite-native/intl/src/translations/cs-CZ.json
  suite-native/intl/src/types.ts
  suite-native/intl/src/utils.ts
  suite-native/intl/translations/cs-CZ.json
  suite-native/intl/translations/en-US.json
  suite-native/intl/tsconfig.json
  yarn.lock
Labels: ci, mobile

#21722 refactor(suite-common): tweak naming of selectIsBluetoothDevice
  suite-common/wallet-core/src/device/deviceSelectors.ts
  suite-native/device/src/components/ConnectorImage.tsx
  suite-native/module-home/src/screens/HomeScreen/components/AutoEjectAnimation.tsx
Labels: mobile, bluetooth

#21740 fix(suite-native): translations ci GH token
  .github/workflows/bot-crowdin-sync.yml
Labels: mobile, no-project

#21746 ci(suite-native): translations ci pr commit message
  .github/workflows/bot-crowdin-sync.yml
Labels: mobile, no-project

#21741 fix(suite-native): fix rozenite metro setup
  suite-native/app/metro.config.js
  suite-native/app/package.json
  yarn.lock
Labels: mobile, no-project

#21733 fix(suite-native): Fw: fix progress animation default value
  suite-native/firmware/src/components/FirmwareInstallationScreenContent.tsx
Labels: mobile

#21738 feat(suite-native): guide users to confirm pairing also on device
  suite-native/bluetooth/src/components/BluetoothDeviceCard.tsx
  suite-native/intl/src/messages.ts
Labels: mobile, bluetooth

#21804 chore(token-definitions): use simple json instead of jws for definitions
  suite-common/token-definitions/package.json
  suite-common/token-definitions/scripts/utils/sign.ts
  suite-common/token-definitions/src/tokenDefinitionsConstants.ts
  suite-common/token-definitions/src/tokenDefinitionsUtils.ts
  suite-common/token-definitions/tsconfig.json
  yarn.lock
Labels: mobile

#21844 fix(suite-native): show device connector on the create PIN screen
  suite-native/device/src/components/ConnectorImage.tsx
  suite-native/device/src/components/ContinueOnTrezorScreenContent.tsx
  suite-native/module-device-onboarding/src/screens/CreatePinScreen.tsx
Labels: mobile

#21843 fix(connect): http errors handling for suite-native
  packages/connect/src/device/checkFirmwareRevision.ts
  packages/connect/src/utils/assetUtils.ts
  packages/connect/src/utils/assets-browser.ts
  packages/connect/src/utils/assets.native.ts
  packages/connect/src/utils/assets.ts
Labels: no-project

#21845 fix(suite-native): connecting remembered device
  suite-native/device/src/middlewares/deviceConnectionMiddleware.ts
Labels: mobile, no-project

#21850 fix(suite-native): localization files disabled without ff
  suite-native/intl/src/hooks/useTranslatedMessages.ts
Labels: mobile, no-project

#21761 fix(suite-native): Connect & Unlock: fix BT button visibility
  suite-native/device/src/components/ConnectAndUnlockDeviceScreenContent.tsx
  suite-native/module-authorize-device/src/screens/connect/ConnectAndUnlockDeviceScreen.tsx
Labels: mobile

#21884 fix(suite-native): platform specific alert import
  suite-native/bluetooth/src/hooks/useBluetoothAlerts.ts
  suite-native/bluetooth/src/hooks/useBluetoothPlatformSpecificAlerts.ts
Labels: mobile

#21942 feat(protocol): trezor-push-notification decode
  packages/protocol/src/errors.ts
  packages/protocol/src/index.ts
  packages/protocol/src/protocol-tpn/constants.ts
  packages/protocol/src/protocol-tpn/decode.ts
  packages/protocol/src/protocol-tpn/index.ts
  packages/protocol/tests/protocol-tpn.test.ts
Labels: bluetooth

#21921 feat(suite-native): in app rating
  scripts/list-outdated-dependencies/mobile-dependencies.txt
  suite-common/message-system/src/messageSystemTypes.ts
  suite-native/in-app-rating/package.json
  suite-native/in-app-rating/redux.d.ts
  suite-native/in-app-rating/src/hooks/useInAppRating.ts
  suite-native/in-app-rating/src/hooks/useIsInAppRatingEnabled.ts
  suite-native/in-app-rating/src/index.ts
  suite-native/in-app-rating/tsconfig.json
  suite-native/module-send/src/components/OutputsReviewFooter.tsx
  suite-native/navigation/src/navigators.ts
  suite-native/receive/package.json
  suite-native/receive/src/components/ReceiveScreenHeader.tsx
  suite-native/receive/src/screens/ReceiveAddressScreen.tsx
  suite-native/receive/tsconfig.json
  suite-native/transactions/package.json
  suite-native/transactions/src/screens/TransactionDetailScreen.tsx
  suite-native/transactions/tsconfig.json
  yarn.lock
Labels: mobile

#21979 fix(suite-native): e2e websocket hanging test
  suite-native/app/e2e/tests/deviceOnboarding.test.ts
Labels: mobile, no-project

#21980 fix(suite-native): flagging remembered device on connect
  suite-native/device/src/middlewares/deviceConnectionMiddleware.ts
Labels: mobile, THP

#21975 fix(suite-native): handle cancelling of Bluetooth pairing correctly
  packages/suite/src/components/suite/bluetooth/BluetoothDeviceListItem.tsx
  packages/suite/src/components/suite/bluetooth/BluetoothSelectedDevice.tsx
  packages/transport-native-bluetooth/src/api/bluetoothManager.ts
  packages/transport-native-bluetooth/src/api/types.ts
  suite-common/bluetooth/src/types.ts
  suite-native/bluetooth/package.json
  suite-native/bluetooth/src/hooks/useBluetoothAdapter.ts
  suite-native/bluetooth/tsconfig.json
  suite-native/intl/src/messages.ts
  yarn.lock
Labels: bug, mobile, bluetooth

#21991 fix(connect): initDevice when staticSessionId is not set yet
  packages/connect/src/core/index.ts
Labels: connect

#21996 chore(transport): add missing native Bluetooth transport name
  packages/connect/src/types/settings.ts
  packages/transport-native-bluetooth/src/transport.ts
  packages/transport/src/transports/abstract.ts
Labels: no-project

#22000 feat(suite-native): process Bluetooth battery level notifications
  packages/transport-native-bluetooth/src/api/BluetoothApi.ts
  packages/transport-native-bluetooth/src/api/bluetoothManager.ts
  packages/transport-native-bluetooth/src/api/types.ts
Labels: mobile, bluetooth

#21999 feat(connect): set settings notification
  packages/connect/src/device/Device.ts
  packages/connect/src/device/workflow/trezorPushNotification.ts
  packages/connect/src/types/workflow.ts
Labels: bluetooth

#22038 feat(suite-native): prepare support url with possible direct trade status
  suite-native/module-trading/src/__fixtures__/buyProviders.ts
  suite-native/module-trading/src/__fixtures__/exchangeProviders.ts
  suite-native/module-trading/src/__fixtures__/sellProviders.ts
  suite-native/module-trading/src/components/history/TradeDetailSheet/TradeDetailAlert.tsx
  suite-native/module-trading/src/components/history/TradeDetailSheet/__tests__/TradeDetailAlert.comp.test.tsx
Labels: mobile
